const jsonData = [
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/126",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 126 期",
    "link": "https://hellogithub.com/periodical/volume/126",
    "pub_date": "2026-09-28 08:05:08",
    "author": "",
    "description": "本期共有 39 个项目，包含 C 项目 (1)，C# 项目 (3)，C++ 项目 (1)，Go 项目 (4)，JavaScript 项目 (5)，Python 项目 (5)，Rust 项目 (3)，Skills (4)，Swift 项目 (4)，人工智能 (5)，其它 (4)",
    "content": "本期共有 39 个项目，包含 C 项目 (1)，C# 项目 (3)，C++ 项目 (1)，Go 项目 (4)，JavaScript 项目 (5)，Python 项目 (5)，Rust 项目 (3)，Skills (4)，Swift 项目 (4)，人工智能 (5)，其它 (4)"
  },
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/125",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 125 期",
    "link": "https://hellogithub.com/periodical/volume/125",
    "pub_date": "2026-08-28 08:14:02",
    "author": "",
    "description": "本期共有 40 个项目，包含 C 项目 (1)，C# 项目 (3)，C++ 项目 (2)，Go 项目 (4)，Java 项目 (2)，JavaScript 项目 (4)，Kotlin 项目 (1)，Python 项目 (4)，Rust 项目 (3)，Skills (4)，Swift 项目 (2)，人工智能 (5)，其它 (5)",
    "content": "本期共有 40 个项目，包含 C 项目 (1)，C# 项目 (3)，C++ 项目 (2)，Go 项目 (4)，Java 项目 (2)，JavaScript 项目 (4)，Kotlin 项目 (1)，Python 项目 (4)，Rust 项目 (3)，Skills (4)，Swift 项目 (2)，人工智能 (5)，其它 (5)"
  },
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/124",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 124 期",
    "link": "https://hellogithub.com/periodical/volume/124",
    "pub_date": "2026-07-28 08:10:05",
    "author": "",
    "description": "本期共有 40 个项目，包含 C 项目 (2)，C# 项目 (2)，C++ 项目 (1)，Go 项目 (4)，Java 项目 (1)，JavaScript 项目 (5)，Python 项目 (5)，Rust 项目 (2)，Skills (3)，Swift 项目 (3)，人工智能 (5)，其它 (5)，开源书籍 (2)",
    "content": "本期共有 40 个项目，包含 C 项目 (2)，C# 项目 (2)，C++ 项目 (1)，Go 项目 (4)，Java 项目 (1)，JavaScript 项目 (5)，Python 项目 (5)，Rust 项目 (2)，Skills (3)，Swift 项目 (3)，人工智能 (5)，其它 (5)，开源书籍 (2)"
  },
  {
    "id": "技术-github all-https://github.com/NVIDIA/OpenShell",
    "feed_name": "github all",
    "category": "技术",
    "title": "NVIDIA/OpenShell",
    "link": "https://github.com/NVIDIA/OpenShell",
    "pub_date": "",
    "author": "",
    "description": "OpenShell is the safe, private runtime for autonomous AI agents. https://docs.nvidia.com/openshell/latest/ Important New in OpenShell 0.1.x: a stable release cadence, new isolation primitives, an expanded extension surfa…",
    "content": "OpenShell is the safe, private runtime for autonomous AI agents. https://docs.nvidia.com/openshell/latest/ Important New in OpenShell 0.1.x: a stable release cadence, new isolation primitives, an expanded extension surface, and new APIs. Read the 0.1.0 upgrade…"
  },
  {
    "id": "技术-github all-https://github.com/debpalash/VoiceStudio",
    "feed_name": "github all",
    "category": "技术",
    "title": "debpalash/VoiceStudio",
    "link": "https://github.com/debpalash/VoiceStudio",
    "pub_date": "",
    "author": "",
    "description": "VoiceStudio is the open-source, fully-local ElevenLabs alternative — voice cloning, voice design, video dubbing, dictation, transcription & audiobook creation in 646 languages. https://voicestudio.sh VoiceStudio Open-sou…",
    "content": "VoiceStudio is the open-source, fully-local ElevenLabs alternative — voice cloning, voice design, video dubbing, dictation, transcription & audiobook creation in 646 languages. https://voicestudio.sh VoiceStudio Open-source voice cloning, voice design, video d…"
  },
  {
    "id": "技术-github all-https://github.com/mvschwarz/openrig",
    "feed_name": "github all",
    "category": "技术",
    "title": "mvschwarz/openrig",
    "link": "https://github.com/mvschwarz/openrig",
    "pub_date": "",
    "author": "",
    "description": "Multi-agent harness that runs Claude Code and Codex together as one system https://openrig.dev OpenRig A harness wraps a model. A rig wraps your harnesses. Define your agent team in YAML, boot it with one command. Claude…",
    "content": "Multi-agent harness that runs Claude Code and Codex together as one system https://openrig.dev OpenRig A harness wraps a model. A rig wraps your harnesses. Define your agent team in YAML, boot it with one command. Claude Code and Codex in the same rig, managed…"
  },
  {
    "id": "技术-github all-https://github.com/mksglu/context-mode",
    "feed_name": "github all",
    "category": "技术",
    "title": "mksglu/context-mode",
    "link": "https://github.com/mksglu/context-mode",
    "pub_date": "",
    "author": "",
    "description": "Context window optimization for AI coding agents. Sandboxes tool output (98% reduction), persists session memory, and enforces routing across 17 platforms via MCP + hooks. https://context-mode.com Context Mode The other …",
    "content": "Context window optimization for AI coding agents. Sandboxes tool output (98% reduction), persists session memory, and enforces routing across 17 platforms via MCP + hooks. https://context-mode.com Context Mode The other half of the context problem. Used across…"
  },
  {
    "id": "技术-github all-https://github.com/DietrichGebert/ponytail",
    "feed_name": "github all",
    "category": "技术",
    "title": "DietrichGebert/ponytail",
    "link": "https://github.com/DietrichGebert/ponytail",
    "pub_date": "",
    "author": "",
    "description": "Makes your AI agent think like the laziest senior dev in the room. The best code is the code you never wrote. https://ponytail.dev Ponytail He says nothing. He writes one line. It works. ~54% less code (up to 94%) · ~20%…",
    "content": "Makes your AI agent think like the laziest senior dev in the room. The best code is the code you never wrote. https://ponytail.dev Ponytail He says nothing. He writes one line. It works. ~54% less code (up to 94%) · ~20% cheaper · ~27% faster · 100% safe Measu…"
  },
  {
    "id": "技术-github all-https://github.com/harry0703/MoneyPrinterTurbo",
    "feed_name": "github all",
    "category": "技术",
    "title": "harry0703/MoneyPrinterTurbo",
    "link": "https://github.com/harry0703/MoneyPrinterTurbo",
    "pub_date": "",
    "author": "",
    "description": "利用 AI 大模型和自动化工作流，根据主题或关键词一键生成高清短视频。Generate HD short videos from a topic or keyword with an automated AI workflow. MoneyPrinterTurbo 💸 一站式 AI 短视频生成工具 只需提供视频主题或关键词，即可自动生成视频脚本、匹配素材、生成字幕和背景音乐，并合成高清短视频。 简体中文 | English | 日本語…",
    "content": "利用 AI 大模型和自动化工作流，根据主题或关键词一键生成高清短视频。Generate HD short videos from a topic or keyword with an automated AI workflow. MoneyPrinterTurbo 💸 一站式 AI 短视频生成工具 只需提供视频 主题 或 关键词 ，即可自动生成视频脚本、匹配素材、生成字幕和背景音乐，并合成高清短视频。 简体中文 | English | 日本語 | 版本发布 | 问题反馈 界面预览 🖥️ WebUI API 特别…"
  },
  {
    "id": "技术-github all-https://github.com/openclaw/openclaw",
    "feed_name": "github all",
    "category": "技术",
    "title": "openclaw/openclaw",
    "link": "https://github.com/openclaw/openclaw",
    "pub_date": "",
    "author": "",
    "description": "The AI that really does things. Any OS. Any Platform. The lobster way. 🦞 https://openclaw.ai OpenClaw 🦞 — Your assistant, on your devices, in your chats OpenClaw is an open-source AI assistant that runs on your own com…",
    "content": "The AI that really does things. Any OS. Any Platform. The lobster way. 🦞 https://openclaw.ai OpenClaw 🦞 — Your assistant, on your devices, in your chats OpenClaw is an open-source AI assistant that runs on your own computer and meets you in the channels you …"
  },
  {
    "id": "技术-github all-https://github.com/ComposioHQ/awesome-claude-skills",
    "feed_name": "github all",
    "category": "技术",
    "title": "ComposioHQ/awesome-claude-skills",
    "link": "https://github.com/ComposioHQ/awesome-claude-skills",
    "pub_date": "",
    "author": "",
    "description": "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows Awesome Claude Skills A comprehensive and curated list of 1000+ production ready and practical Claude Skills and Plugins f…",
    "content": "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows Awesome Claude Skills A comprehensive and curated list of 1000+ production ready and practical Claude Skills and Plugins for enhancing productivity across usecase…"
  },
  {
    "id": "技术-github all-https://github.com/mattpocock/skills",
    "feed_name": "github all",
    "category": "技术",
    "title": "mattpocock/skills",
    "link": "https://github.com/mattpocock/skills",
    "pub_date": "",
    "author": "",
    "description": "Skills for Real Engineers. Straight from my .agents directory. https://aihero.dev/skills Skills For Real Engineers My agent skills that I use every day to do real engineering - not vibe coding. Developing real applicatio…",
    "content": "Skills for Real Engineers. Straight from my .agents directory. https://aihero.dev/skills Skills For Real Engineers My agent skills that I use every day to do real engineering - not vibe coding. Developing real applications is hard. Approaches like GSD, BMAD, a…"
  },
  {
    "id": "技术-github all-https://github.com/heygen-com/hyperframes",
    "feed_name": "github all",
    "category": "技术",
    "title": "heygen-com/hyperframes",
    "link": "https://github.com/heygen-com/hyperframes",
    "pub_date": "",
    "author": "",
    "description": "Write HTML. Render video. Built for agents. Write HTML. Render video. Built for agents. Quickstart | Showcase | Playground | Catalog | Docs | Discord HyperFrames is an open-source framework for turning HTML, CSS, media, …",
    "content": "Write HTML. Render video. Built for agents. Write HTML. Render video. Built for agents. Quickstart | Showcase | Playground | Catalog | Docs | Discord HyperFrames is an open-source framework for turning HTML, CSS, media, and seekable animations into determinist…"
  },
  {
    "id": "技术-github all-https://github.com/firebase/firebase-ios-sdk",
    "feed_name": "github all",
    "category": "技术",
    "title": "firebase/firebase-ios-sdk",
    "link": "https://github.com/firebase/firebase-ios-sdk",
    "pub_date": "",
    "author": "",
    "description": "Firebase SDK for Apple App Development https://firebase.google.com Warning CocoaPods: New versions of the Firebase Apple SDK will no longer be published to CocoaPods after October 2026. Existing CocoaPods versions will r…",
    "content": "Firebase SDK for Apple App Development https://firebase.google.com Warning CocoaPods: New versions of the Firebase Apple SDK will no longer be published to CocoaPods after October 2026 . Existing CocoaPods versions will remain available and installations will …"
  },
  {
    "id": "技术-github all-https://github.com/modelcontextprotocol/servers",
    "feed_name": "github all",
    "category": "技术",
    "title": "modelcontextprotocol/servers",
    "link": "https://github.com/modelcontextprotocol/servers",
    "pub_date": "",
    "author": "",
    "description": "Model Context Protocol Servers https://modelcontextprotocol.io Model Context Protocol servers This repository is a collection of reference implementations for the Model Context Protocol (MCP), as well as references to co…",
    "content": "Model Context Protocol Servers https://modelcontextprotocol.io Model Context Protocol servers This repository is a collection of reference implementations for the Model Context Protocol (MCP), as well as references to community-built servers and additional res…"
  },
  {
    "id": "技术-github all-https://github.com/byoungd/up",
    "feed_name": "github all",
    "category": "技术",
    "title": "byoungd/up",
    "link": "https://github.com/byoungd/up",
    "pub_date": "",
    "author": "",
    "description": "An advanced guide which might benefit you a lot 🎉 . 韩先凯的人生进阶指南 人生进阶指南 离谱的人生 人生进阶 AI学习 AI指南 韩先凯的AI学习指南 英语学习指南/英语学习教程/英语学习/学英语 https://biezou.com title: 人生进阶指南｜AI 时代终身学习 description: 《人生进阶指南》帮助普通人在 AI 时代持续学习、完成真实项目、穿越人生低谷…",
    "content": "An advanced guide which might benefit you a lot 🎉 . 韩先凯的人生进阶指南 人生进阶指南 离谱的人生 人生进阶 AI学习 AI指南 韩先凯的AI学习指南 英语学习指南/英语学习教程/英语学习/学英语 https://biezou.com title: 人生进阶指南｜AI 时代终身学习 description: 《人生进阶指南》帮助普通人在 AI 时代持续学习、完成真实项目、穿越人生低谷并留下成长证据。 updated: 2026-09-02 人生进阶指南 中文 |…"
  },
  {
    "id": "技术-github all-https://github.com/colbymchenry/codegraph",
    "feed_name": "github all",
    "category": "技术",
    "title": "colbymchenry/codegraph",
    "link": "https://github.com/colbymchenry/codegraph",
    "pub_date": "",
    "author": "",
    "description": "Pre-indexed code knowledge graph, auto syncs on code changes, for Claude Code, Codex, Gemini, Cursor, OpenCode, AntiGravity, Kiro, CoPilot, and Hermes Agent — fewer tokens, fewer tool calls, 100% local https://colbymchen…",
    "content": "Pre-indexed code knowledge graph, auto syncs on code changes, for Claude Code, Codex, Gemini, Cursor, OpenCode, AntiGravity, Kiro, CoPilot, and Hermes Agent — fewer tokens, fewer tool calls, 100% local https://colbymchenry.github.io/codegraph/ CodeGraph Alread…"
  },
  {
    "id": "技术-github all-https://github.com/t8y2/dbx",
    "feed_name": "github all",
    "category": "技术",
    "title": "t8y2/dbx",
    "link": "https://github.com/t8y2/dbx",
    "pub_date": "",
    "author": "",
    "description": "25 MB lightweight cross-platform database client for 100+ databases, including MySQL, PostgreSQL, SQLite, Redis, MongoDB, DuckDB, SQL Server, and Dameng. Built-in AI, MCP Server, CLI, desktop and Docker. | 轻量级跨平台数据库管理工具，…",
    "content": "25 MB lightweight cross-platform database client for 100+ databases, including MySQL, PostgreSQL, SQLite, Redis, MongoDB, DuckDB, SQL Server, and Dameng. Built-in AI, MCP Server, CLI, desktop and Docker. | 轻量级跨平台数据库管理工具，支持 MySQL、PostgreSQL、SQLite、Redis、MongoDB…"
  },
  {
    "id": "技术-github all-https://github.com/NawfalMotii79/PLFM_RADAR",
    "feed_name": "github all",
    "category": "技术",
    "title": "NawfalMotii79/PLFM_RADAR",
    "link": "https://github.com/NawfalMotii79/PLFM_RADAR",
    "pub_date": "",
    "author": "",
    "description": "Open-source, low-cost 10.5 GHz PLFM phased array RADAR system AERIS-10: Open Source Pulse Linear Frequency Modulated Phased Array Radar AERIS-10 is an open-source, low-cost 10.5 GHz phased array radar system featuring Pu…",
    "content": "Open-source, low-cost 10.5 GHz PLFM phased array RADAR system AERIS-10: Open Source Pulse Linear Frequency Modulated Phased Array Radar AERIS-10 is an open-source, low-cost 10.5 GHz phased array radar system featuring Pulse Linear Frequency Modulated (LFM) mod…"
  },
  {
    "id": "技术-github all-https://github.com/VectifyAI/PageIndex",
    "feed_name": "github all",
    "category": "技术",
    "title": "VectifyAI/PageIndex",
    "link": "https://github.com/VectifyAI/PageIndex",
    "pub_date": "",
    "author": "",
    "description": "📑 PageIndex: Document Index for Vectorless, Reasoning-based RAG https://pageindex.ai PageIndex: Vectorless, Reasoning-based RAG Reasoning-based RAG ◦ No Vector DB, No Chunking ◦ Context-Aware Retrieval ◦ Reads Like a Hu…",
    "content": "📑 PageIndex: Document Index for Vectorless, Reasoning-based RAG https://pageindex.ai PageIndex: Vectorless, Reasoning-based RAG Reasoning-based RAG&nbsp; ◦ &nbsp;No Vector DB, No Chunking&nbsp; ◦ &nbsp;Context-Aware Retrieval&nbsp; ◦ &nbsp;Reads Like a Human …"
  },
  {
    "id": "技术-github python-https://github.com/vectorize-io/hindsight",
    "feed_name": "github python",
    "category": "技术",
    "title": "vectorize-io/hindsight",
    "link": "https://github.com/vectorize-io/hindsight",
    "pub_date": "",
    "author": "",
    "description": "Hindsight: Agent Memory That Learns https://hindsight.vectorize.io/ Documentation • Integrations • Cookbook • Benchmarks • Paper • Hindsight Cloud What is Hindsight? Hindsight™ is an agent memory system built to create s…",
    "content": "Hindsight: Agent Memory That Learns https://hindsight.vectorize.io/ Documentation • Integrations • Cookbook • Benchmarks • Paper • Hindsight Cloud What is Hindsight? Hindsight™ is an agent memory system built to create smarter agents that learn over time. Most…"
  },
  {
    "id": "技术-github python-https://github.com/anthropics/financial-services",
    "feed_name": "github python",
    "category": "技术",
    "title": "anthropics/financial-services",
    "link": "https://github.com/anthropics/financial-services",
    "pub_date": "",
    "author": "",
    "description": "Claude for Financial Services Reference agents, skills, and data connectors for the financial-services workflows we see most — investment banking, equity research, private equity, and wealth management. Everything here i…",
    "content": "Claude for Financial Services Reference agents, skills, and data connectors for the financial-services workflows we see most — investment banking, equity research, private equity, and wealth management. Everything here is available two ways from one source : i…"
  },
  {
    "id": "技术-github python-https://github.com/rohitg00/ai-engineering-from-scratch",
    "feed_name": "github python",
    "category": "技术",
    "title": "rohitg00/ai-engineering-from-scratch",
    "link": "https://github.com/rohitg00/ai-engineering-from-scratch",
    "pub_date": "",
    "author": "",
    "description": "Learn it. Build it. Ship it for others. https://aiengineeringfromscratch.com Read in your language: Español · Français · Português · Deutsch · Italiano · 简体中文 · 日本語 · 한국어 · हिन्दी · العربية · Русский · Türkçe Translated …",
    "content": "Learn it. Build it. Ship it for others. https://aiengineeringfromscratch.com Read in your language: Español · Français · Português · Deutsch · Italiano · 简体中文 · 日本語 · 한국어 · हिन्दी · العربية · Русский · Türkçe Translated landing pages, committed to the repo. En…"
  },
  {
    "id": "技术-github python-https://github.com/HKUDS/CLI-Anything",
    "feed_name": "github python",
    "category": "技术",
    "title": "HKUDS/CLI-Anything",
    "link": "https://github.com/HKUDS/CLI-Anything",
    "pub_date": "",
    "author": "",
    "description": "\"CLI-Anything: Making ALL Software Agent-Native\" -- CLI-Hub: https://clianything.cc/ https://clianything.cc/ CLI-Anything: Making ALL Software Agent-Native Today's Software Serves Humans👨‍💻. Tomorrow's Users will be Ag…",
    "content": "\"CLI-Anything: Making ALL Software Agent-Native\" -- CLI-Hub: https://clianything.cc/ https://clianything.cc/ &nbsp; CLI-Anything: Making ALL Software Agent-Native Today's Software Serves Humans👨‍💻. Tomorrow's Users will be Agents🤖. CLI-Anything: Bridging th…"
  },
  {
    "id": "技术-github python-https://github.com/davila7/claude-code-templates",
    "feed_name": "github python",
    "category": "技术",
    "title": "davila7/claude-code-templates",
    "link": "https://github.com/davila7/claude-code-templates",
    "pub_date": "",
    "author": "",
    "description": "CLI tool for configuring and monitoring Claude Code https://aitmpl.com Sponsored by Bright Data Bright Data proudly supports this project. Connect Claude Code to live web data — try their Skills and MCPs for web search, …",
    "content": "CLI tool for configuring and monitoring Claude Code https://aitmpl.com &nbsp;&nbsp; &nbsp;&nbsp; Sponsored by Bright Data Bright Data proudly supports this project. Connect Claude Code to live web data — try their Skills and MCPs for web search, scraping, and …"
  },
  {
    "id": "技术-github python-https://github.com/pytorch/pytorch",
    "feed_name": "github python",
    "category": "技术",
    "title": "pytorch/pytorch",
    "link": "https://github.com/pytorch/pytorch",
    "pub_date": "",
    "author": "",
    "description": "Tensors and Dynamic neural networks in Python with strong GPU acceleration https://pytorch.org PyTorch is a Python package that provides two high-level features: Tensor computation (like NumPy) with strong GPU accelerati…",
    "content": "Tensors and Dynamic neural networks in Python with strong GPU acceleration https://pytorch.org PyTorch is a Python package that provides two high-level features: Tensor computation (like NumPy) with strong GPU acceleration Deep neural networks built on a tape-…"
  },
  {
    "id": "技术-github python-https://github.com/TencentCloud/Octop",
    "feed_name": "github python",
    "category": "技术",
    "title": "TencentCloud/Octop",
    "link": "https://github.com/TencentCloud/Octop",
    "pub_date": "",
    "author": "",
    "description": "A smarter, self-hosted AI assistant — multi-user, multi-agent. https://octop.cloud A smarter, self-hosted AI assistant — multi-user, multi-agent. Highlights · Overview · Core Technology · Features · Roadmap · Quick Start…",
    "content": "A smarter, self-hosted AI assistant — multi-user, multi-agent. https://octop.cloud A smarter, self-hosted AI assistant — multi-user, multi-agent. Highlights · Overview · Core Technology · Features · Roadmap · Quick Start · Contents English · 中文 Octop is an ope…"
  },
  {
    "id": "技术-github python-https://github.com/alirezarezvani/claude-skills",
    "feed_name": "github python",
    "category": "技术",
    "title": "alirezarezvani/claude-skills",
    "link": "https://github.com/alirezarezvani/claude-skills",
    "pub_date": "",
    "author": "",
    "description": "380 Claude Code skills & agent skills & plugins (30+ Agents, 70+ custom commands, 380+ skills, customizable references, scripts)for Claude Code, Codex, Gemini CLI, Cursor, and 8 more coding agents — engineering, marketin…",
    "content": "380 Claude Code skills & agent skills & plugins (30+ Agents, 70+ custom commands, 380+ skills, customizable references, scripts)for Claude Code, Codex, Gemini CLI, Cursor, and 8 more coding agents — engineering, marketing, product, compliance, C-level advisory…"
  },
  {
    "id": "技术-github python-https://github.com/derv82/wifit3",
    "feed_name": "github python",
    "category": "技术",
    "title": "derv82/wifit3",
    "link": "https://github.com/derv82/wifit3",
    "pub_date": "",
    "author": "",
    "description": "Wifite but USB-only & cross-platform. wifit3 A standalone USB Wi-Fi auditor for Linux, Windows, and macOS. At least one of the supported USB adapters is required. Why? Cross-Platform: Runs identically on Linux, macOS, an…",
    "content": "Wifite but USB-only & cross-platform. wifit3 A standalone USB Wi-Fi auditor for Linux, Windows, and macOS. At least one of the supported USB adapters is required . Why? Cross-Platform: Runs identically on Linux, macOS, and Windows. Wireless Driver Heaven: Buil…"
  },
  {
    "id": "技术-github python-https://github.com/NVIDIA/Model-Optimizer",
    "feed_name": "github python",
    "category": "技术",
    "title": "NVIDIA/Model-Optimizer",
    "link": "https://github.com/NVIDIA/Model-Optimizer",
    "pub_date": "",
    "author": "",
    "description": "A unified library of SOTA model optimization techniques like quantization, distillation, pruning, neural architecture search, speculative decoding, etc. It compresses deep learning models for downstream deployment framew…",
    "content": "A unified library of SOTA model optimization techniques like quantization, distillation, pruning, neural architecture search, speculative decoding, etc. It compresses deep learning models for downstream deployment frameworks like TensorRT-LLM, TensorRT, vLLM, …"
  },
  {
    "id": "技术-github python-https://github.com/aayushch/laya",
    "feed_name": "github python",
    "category": "技术",
    "title": "aayushch/laya",
    "link": "https://github.com/aayushch/laya",
    "pub_date": "",
    "author": "",
    "description": "Laya is an open-source, local-first AI notification command center that aggregates Slack, Gmail, GitHub, Jira, Notion, Outlook, Calendar (and more) notifications using local LLMs via Ollama and LM Studio. Supports cloud …",
    "content": "Laya is an open-source, local-first AI notification command center that aggregates Slack, Gmail, GitHub, Jira, Notion, Outlook, Calendar (and more) notifications using local LLMs via Ollama and LM Studio. Supports cloud models via BYOK. Laya: Your AI Command C…"
  },
  {
    "id": "技术-github python-https://github.com/superdesigndev/treg",
    "feed_name": "github python",
    "category": "技术",
    "title": "superdesigndev/treg",
    "link": "https://github.com/superdesigndev/treg",
    "pub_date": "",
    "author": "",
    "description": "OpenRouter for agent tools. Join community here: https://discord.gg/6mQYYfFMAn https://treg.to Treg (OpenRouter for Tools) OpenRouter, but for agent tools instead of models. Point an agent at one base URL with one token …",
    "content": "OpenRouter for agent tools. Join community here: https://discord.gg/6mQYYfFMAn https://treg.to Treg (OpenRouter for Tools) OpenRouter, but for agent tools instead of models. Point an agent at one base URL with one token and it can do the job: a curated catalog…"
  },
  {
    "id": "技术-github python-https://github.com/strands-agents/harness-sdk",
    "feed_name": "github python",
    "category": "技术",
    "title": "strands-agents/harness-sdk",
    "link": "https://github.com/strands-agents/harness-sdk",
    "pub_date": "",
    "author": "",
    "description": "Build an agent harness and control it end-to-end. Open-source SDK for production AI agents in Python & TypeScript - any model, any cloud. http://strandsagents.com/ Strands Agents A model-driven approach to building AI ag…",
    "content": "Build an agent harness and control it end-to-end. Open-source SDK for production AI agents in Python & TypeScript - any model, any cloud. http://strandsagents.com/ Strands Agents A model-driven approach to building AI agents in just a few lines of code. Docume…"
  },
  {
    "id": "技术-github python-https://github.com/mvt-project/mvt",
    "feed_name": "github python",
    "category": "技术",
    "title": "mvt-project/mvt",
    "link": "https://github.com/mvt-project/mvt",
    "pub_date": "",
    "author": "",
    "description": "MVT (Mobile Verification Toolkit) helps with conducting forensics of mobile devices in order to find signs of a potential compromise. https://mvt.re Mobile Verification Toolkit Important We recently merged the \"v3\" branc…",
    "content": "MVT (Mobile Verification Toolkit) helps with conducting forensics of mobile devices in order to find signs of a potential compromise. https://mvt.re Mobile Verification Toolkit Important We recently merged the \"v3\" branch. This introduced breaking changes. If …"
  },
  {
    "id": "技术-github go-https://github.com/Tencent/WeKnora",
    "feed_name": "github go",
    "category": "技术",
    "title": "Tencent/WeKnora",
    "link": "https://github.com/Tencent/WeKnora",
    "pub_date": "",
    "author": "",
    "description": "Open-source LLM knowledge platform: turn raw documents into a queryable RAG, an autonomous reasoning agent, and a self-maintaining Wiki. https://weknora.weixin.qq.com English · 简体中文 · 日本語 · 한국어 Overview · Quick Start · W…",
    "content": "Open-source LLM knowledge platform: turn raw documents into a queryable RAG, an autonomous reasoning agent, and a self-maintaining Wiki. https://weknora.weixin.qq.com English · 简体中文 · 日本語 · 한국어 Overview · Quick Start · What's New · Features · Clients · Docs · …"
  },
  {
    "id": "技术-github go-https://github.com/google/ax",
    "feed_name": "github go",
    "category": "技术",
    "title": "google/ax",
    "link": "https://github.com/google/ax",
    "pub_date": "",
    "author": "",
    "description": "Google's open agentic orchestration runtime https://agentexecutor.io AX Warning AX and several of its features are in heavy development. We are actively refining our core concepts, protocols, and specifications, and will…",
    "content": "Google's open agentic orchestration runtime https://agentexecutor.io AX Warning AX and several of its features are in heavy development. We are actively refining our core concepts, protocols, and specifications, and will likely introduce major breaking changes…"
  },
  {
    "id": "技术-github go-https://github.com/agent-substrate/substrate",
    "feed_name": "github go",
    "category": "技术",
    "title": "agent-substrate/substrate",
    "link": "https://github.com/agent-substrate/substrate",
    "pub_date": "",
    "author": "",
    "description": "Agent Substrate: the core system Agent Substrate What is Agent Substrate? Agent Substrate is a secure-by-default agent execution runtime engineered to run millions of sandboxes with 10x higher density than standard conta…",
    "content": "Agent Substrate: the core system Agent Substrate What is Agent Substrate? Agent Substrate is a secure-by-default agent execution runtime engineered to run millions of sandboxes with 10x higher density than standard container runtimes. Purpose-built for the era…"
  },
  {
    "id": "技术-github go-https://github.com/kubernetes/kubernetes",
    "feed_name": "github go",
    "category": "技术",
    "title": "kubernetes/kubernetes",
    "link": "https://github.com/kubernetes/kubernetes",
    "pub_date": "",
    "author": "",
    "description": "Production-Grade Container Scheduling and Management https://kubernetes.io Kubernetes (K8s) Kubernetes, also known as K8s, is an open source system for managing containerized applications across multiple hosts. It provid…",
    "content": "Production-Grade Container Scheduling and Management https://kubernetes.io Kubernetes (K8s) Kubernetes, also known as K8s, is an open source system for managing containerized applications across multiple hosts. It provides basic mechanisms for the deployment, …"
  },
  {
    "id": "技术-github go-https://github.com/Asymptote-Labs/agent-beacon",
    "feed_name": "github go",
    "category": "技术",
    "title": "Asymptote-Labs/agent-beacon",
    "link": "https://github.com/Asymptote-Labs/agent-beacon",
    "pub_date": "",
    "author": "",
    "description": "The cross-harness, self-improving memory layer for AI agents. https://beacon.sh Website · Docs · Discord · Install · Commands Beacon captures agent session history across Claude Code, Cursor, Codex, OpenCode, and 20+ oth…",
    "content": "The cross-harness, self-improving memory layer for AI agents. https://beacon.sh Website · Docs · Discord · Install · Commands Beacon captures agent session history across Claude Code, Cursor, Codex, OpenCode, and 20+ other harnesses, then turns useful workflow…"
  },
  {
    "id": "技术-github go-https://github.com/prometheus/prometheus",
    "feed_name": "github go",
    "category": "技术",
    "title": "prometheus/prometheus",
    "link": "https://github.com/prometheus/prometheus",
    "pub_date": "",
    "author": "",
    "description": "The Prometheus monitoring system and time series database. https://prometheus.io/ Prometheus Visit prometheus.io for the full documentation, examples and guides. Prometheus, a Cloud Native Computing Foundation project, i…",
    "content": "The Prometheus monitoring system and time series database. https://prometheus.io/ Prometheus Visit prometheus.io for the full documentation, examples and guides. Prometheus, a Cloud Native Computing Foundation project, is a systems and service monitoring syste…"
  },
  {
    "id": "技术-github go-https://github.com/golang/go",
    "feed_name": "github go",
    "category": "技术",
    "title": "golang/go",
    "link": "https://github.com/golang/go",
    "pub_date": "",
    "author": "",
    "description": "The Go programming language https://go.dev The Go Programming Language Go is an open source programming language that makes it easy to build simple, reliable, and efficient software. Gopher image by Renee French, license…",
    "content": "The Go programming language https://go.dev The Go Programming Language Go is an open source programming language that makes it easy to build simple, reliable, and efficient software. Gopher image by Renee French , licensed under Creative Commons 4.0 Attributio…"
  },
  {
    "id": "技术-github go-https://github.com/cockroachdb/cockroach",
    "feed_name": "github go",
    "category": "技术",
    "title": "cockroachdb/cockroach",
    "link": "https://github.com/cockroachdb/cockroach",
    "pub_date": "",
    "author": "",
    "description": "CockroachDB — the cloud native, distributed SQL database designed for high availability, effortless scale, and control over data placement. https://www.cockroachlabs.com CockroachDB is a cloud-native distributed SQL data…",
    "content": "CockroachDB — the cloud native, distributed SQL database designed for high availability, effortless scale, and control over data placement. https://www.cockroachlabs.com CockroachDB is a cloud-native distributed SQL database designed to build, scale, and manag…"
  },
  {
    "id": "技术-github go-https://github.com/Gentleman-Programming/engram",
    "feed_name": "github go",
    "category": "技术",
    "title": "Gentleman-Programming/engram",
    "link": "https://github.com/Gentleman-Programming/engram",
    "pub_date": "",
    "author": "",
    "description": "Persistent memory system for AI coding agents. Agent-agnostic Go binary with SQLite + FTS5, MCP server, HTTP API, CLI, and TUI. https://engram.gentlemanprogramming.com/ Persistent memory for AI coding agents One brain. L…",
    "content": "Persistent memory system for AI coding agents. Agent-agnostic Go binary with SQLite + FTS5, MCP server, HTTP API, CLI, and TUI. https://engram.gentlemanprogramming.com/ Persistent memory for AI coding agents One brain. Local or cloud. Agent-agnostic, single bi…"
  },
  {
    "id": "技术-github go-https://github.com/flexprice/flexprice",
    "feed_name": "github go",
    "category": "技术",
    "title": "flexprice/flexprice",
    "link": "https://github.com/flexprice/flexprice",
    "pub_date": "",
    "author": "",
    "description": "Usage-based pricing and billing for developers 🔓 Cloud or self-hosted ⚙️ No-code UI 💰 Realtime usage metering 🎟 Credits & top-ups 🔑 Control feature access https://flexprice.io Monetization Infrastructure Built for AI…",
    "content": "Usage-based pricing and billing for developers 🔓 Cloud or self-hosted ⚙️ No-code UI 💰 Realtime usage metering 🎟 Credits & top-ups 🔑 Control feature access https://flexprice.io Monetization Infrastructure Built for AI Native Companies Flexprice lets AI-nati…"
  },
  {
    "id": "技术-github go-https://github.com/openbao/openbao",
    "feed_name": "github go",
    "category": "技术",
    "title": "openbao/openbao",
    "link": "https://github.com/openbao/openbao",
    "pub_date": "",
    "author": "",
    "description": "OpenBao is a software solution to manage, store, and distribute sensitive data including secrets, certificates, and keys. https://openbao.org/ OpenBao Please note: We take OpenBao's security and our users' trust very ser…",
    "content": "OpenBao is a software solution to manage, store, and distribute sensitive data including secrets, certificates, and keys. https://openbao.org/ OpenBao Please note : We take OpenBao's security and our users' trust very seriously. If you believe you have found a…"
  },
  {
    "id": "技术-github go-https://github.com/urfave/cli",
    "feed_name": "github go",
    "category": "技术",
    "title": "urfave/cli",
    "link": "https://github.com/urfave/cli",
    "pub_date": "",
    "author": "",
    "description": "A declarative, simple, fast, and fun package for building command line tools in Go https://cli.urfave.org Welcome to urfave/cli urfave/cli is a declarative, simple, fast, and fun package for building command line tools i…",
    "content": "A declarative, simple, fast, and fun package for building command line tools in Go https://cli.urfave.org Welcome to urfave/cli urfave/cli is a declarative , simple, fast, and fun package for building command line tools in Go featuring: commands and subcommand…"
  },
  {
    "id": "技术-github go-https://github.com/Armur-Ai/Pentest-Swarm-AI",
    "feed_name": "github go",
    "category": "技术",
    "title": "Armur-Ai/Pentest-Swarm-AI",
    "link": "https://github.com/Armur-Ai/Pentest-Swarm-AI",
    "pub_date": "",
    "author": "",
    "description": "Autonomous penetration testing using a swarm of AI agents. Orchestrates recon, classification, exploitation, and reporting specialists with ReAct reasoning — supports bug bounty, continuous monitoring, and CTF modes. Bui…",
    "content": "Autonomous penetration testing using a swarm of AI agents. Orchestrates recon, classification, exploitation, and reporting specialists with ReAct reasoning — supports bug bounty, continuous monitoring, and CTF modes. Built with Go and 7+ native security tools.…"
  },
  {
    "id": "技术-github go-https://github.com/rakyll/hey",
    "feed_name": "github go",
    "category": "技术",
    "title": "rakyll/hey",
    "link": "https://github.com/rakyll/hey",
    "pub_date": "",
    "author": "",
    "description": "HTTP load generator, ApacheBench (ab) replacement hey is a tiny program that sends some load to a web application. hey was originally called boom and was influenced from Tarek Ziade's tool at tarekziade/boom. Using the s…",
    "content": "HTTP load generator, ApacheBench (ab) replacement hey is a tiny program that sends some load to a web application. hey was originally called boom and was influenced from Tarek Ziade's tool at tarekziade/boom . Using the same name was a mistake as it resulted i…"
  },
  {
    "id": "技术-github go-https://github.com/docker/compose",
    "feed_name": "github go",
    "category": "技术",
    "title": "docker/compose",
    "link": "https://github.com/docker/compose",
    "pub_date": "",
    "author": "",
    "description": "Define and run multi-container applications with Docker https://docs.docker.com/compose/ Table of Contents Docker Compose Where to get Docker Compose Windows and macOS Linux Quick Start Contributing Legacy Docker Compose…",
    "content": "Define and run multi-container applications with Docker https://docs.docker.com/compose/ Table of Contents Docker Compose Where to get Docker Compose Windows and macOS Linux Quick Start Contributing Legacy Docker Compose Docker Compose is a tool for running mu…"
  },
  {
    "id": "技术-github go-https://github.com/netdata/netdata",
    "feed_name": "github go",
    "category": "技术",
    "title": "netdata/netdata",
    "link": "https://github.com/netdata/netdata",
    "pub_date": "",
    "author": "",
    "description": "The fastest path to AI-powered full stack observability, even for lean teams. https://www.netdata.cloud X-Ray Vision for your infrastructure! Every Metric, Every Second. No BS. Visit our Home Page MENU: WHO WE ARE | KEY …",
    "content": "The fastest path to AI-powered full stack observability, even for lean teams. https://www.netdata.cloud X-Ray Vision for your infrastructure! Every Metric, Every Second. No BS. Visit our Home Page MENU: WHO WE ARE | KEY FEATURES | GETTING STARTED | HOW IT WORK…"
  },
  {
    "id": "技术-github go-https://github.com/hashicorp/terraform",
    "feed_name": "github go",
    "category": "技术",
    "title": "hashicorp/terraform",
    "link": "https://github.com/hashicorp/terraform",
    "pub_date": "",
    "author": "",
    "description": "Terraform enables you to safely and predictably create, change, and improve infrastructure. It is a source-available tool that codifies APIs into declarative configuration files that can be shared amongst team members, t…",
    "content": "Terraform enables you to safely and predictably create, change, and improve infrastructure. It is a source-available tool that codifies APIs into declarative configuration files that can be shared amongst team members, treated as code, edited, reviewed, and ve…"
  },
  {
    "id": "技术-github rust-https://github.com/hydra-db/hydradb",
    "feed_name": "github rust",
    "category": "技术",
    "title": "hydra-db/hydradb",
    "link": "https://github.com/hydra-db/hydradb",
    "pub_date": "",
    "author": "",
    "description": "HydraDB - fast graph database on object storage https://hydradb.com HydraDB HydraDB is an object-store-native distributed graph database written in Rust. It combines durable graph storage on SlateDB with snapshot-consist…",
    "content": "HydraDB - fast graph database on object storage https://hydradb.com HydraDB HydraDB is an object-store-native distributed graph database written in Rust. It combines durable graph storage on SlateDB with snapshot-consistent OpenCypher queries, GraphBLAS traver…"
  },
  {
    "id": "技术-github rust-https://github.com/timhartmann7/omnyssh",
    "feed_name": "github rust",
    "category": "技术",
    "title": "timhartmann7/omnyssh",
    "link": "https://github.com/timhartmann7/omnyssh",
    "pub_date": "",
    "author": "",
    "description": "Fast, open-source SSH client and server manager for macOS, Windows and Linux. Desktop GUI and terminal TUI with a live metrics dashboard, tabbed terminal, SFTP file manager, port forwarding, one-click SSH keys and snippe…",
    "content": "Fast, open-source SSH client and server manager for macOS, Windows and Linux. Desktop GUI and terminal TUI with a live metrics dashboard, tabbed terminal, SFTP file manager, port forwarding, one-click SSH keys and snippets. Built in Rust. OmnySSH Every server …"
  },
  {
    "id": "技术-github rust-https://github.com/block/buzz",
    "feed_name": "github rust",
    "category": "技术",
    "title": "block/buzz",
    "link": "https://github.com/block/buzz",
    "pub_date": "",
    "author": "",
    "description": "A hive mind communication platform Buzz 🐝 A workspace where humans and agents build together, on a relay you own. Vision · Sovereign · Forge · Agents · Architecture · Releasing · Apache 2.0 People and agents building to…",
    "content": "A hive mind communication platform Buzz 🐝 A workspace where humans and agents build together, on a relay you own. Vision · Sovereign · Forge · Agents · Architecture · Releasing · Apache 2.0 People and agents building together in the same room. What is this, r…"
  },
  {
    "id": "技术-github rust-https://github.com/Nasiko-Labs/nasiko",
    "feed_name": "github rust",
    "category": "技术",
    "title": "Nasiko-Labs/nasiko",
    "link": "https://github.com/Nasiko-Labs/nasiko",
    "pub_date": "",
    "author": "",
    "description": "The Open Runtime for AI Agents https://www.nasiko.com Nasiko is the OpenRuntime for agents, coding harnesses, frameworks and tools. Find the coding agents already running. See what each one costs, by harness and model. R…",
    "content": "The Open Runtime for AI Agents https://www.nasiko.com Nasiko is the OpenRuntime for agents, coding harnesses, frameworks and tools. Find the coding agents already running. See what each one costs, by harness and model. Route them to the models you choose while…"
  },
  {
    "id": "技术-github rust-https://github.com/clash-verge-rev/clash-verge-rev",
    "feed_name": "github rust",
    "category": "技术",
    "title": "clash-verge-rev/clash-verge-rev",
    "link": "https://github.com/clash-verge-rev/clash-verge-rev",
    "pub_date": "",
    "author": "",
    "description": "A modern GUI client based on Tauri, designed to run in Windows, macOS and Linux for tailored proxy experience https://www.clashverge.dev Continuation of Clash Verge A Clash Meta GUI based on Tauri. Languages: 简体中文 · Engl…",
    "content": "A modern GUI client based on Tauri, designed to run in Windows, macOS and Linux for tailored proxy experience https://www.clashverge.dev Continuation of Clash Verge A Clash Meta GUI based on Tauri . Languages: 简体中文 · English · Español · Русский · 日本語 · 한국어 · ف…"
  },
  {
    "id": "技术-github rust-https://github.com/zeronsh/zeron",
    "feed_name": "github rust",
    "category": "技术",
    "title": "zeronsh/zeron",
    "link": "https://github.com/zeronsh/zeron",
    "pub_date": "",
    "author": "",
    "description": "A native control plane for Claude Code, Codex, Cursor, Devin and other coding agents. https://zeron.sh Zeron Control your coding agents (Claude Code, Codex, Cursor, Devin, Grok, Hermes, Pi, Antigravity) locally by defaul…",
    "content": "A native control plane for Claude Code, Codex, Cursor, Devin and other coding agents. https://zeron.sh Zeron Control your coding agents (Claude Code, Codex, Cursor, Devin, Grok, Hermes, Pi, Antigravity) locally by default, with optional multi-device sync. Engl…"
  },
  {
    "id": "技术-github rust-https://github.com/rust-lang/rust",
    "feed_name": "github rust",
    "category": "技术",
    "title": "rust-lang/rust",
    "link": "https://github.com/rust-lang/rust",
    "pub_date": "",
    "author": "",
    "description": "Empowering everyone to build reliable and efficient software. https://www.rust-lang.org Website | Getting started | Learn | Documentation | Contributing This is the main source code repository for Rust. It contains the c…",
    "content": "Empowering everyone to build reliable and efficient software. https://www.rust-lang.org Website | Getting started | Learn | Documentation | Contributing This is the main source code repository for Rust . It contains the compiler, standard library, and document…"
  },
  {
    "id": "技术-github rust-https://github.com/juspay/hyperswitch",
    "feed_name": "github rust",
    "category": "技术",
    "title": "juspay/hyperswitch",
    "link": "https://github.com/juspay/hyperswitch",
    "pub_date": "",
    "author": "",
    "description": "Open source, composable payments platform | PCI compliant | SaaS and Self-host options | Enables connectivity to multiple payment, payout, fraud, vault and tokenization providers | Uplifts authorization with intelligent …",
    "content": "Open source, composable payments platform | PCI compliant | SaaS and Self-host options | Enables connectivity to multiple payment, payout, fraud, vault and tokenization providers | Uplifts authorization with intelligent routing and revenue recovery | Reduce pa…"
  },
  {
    "id": "技术-github rust-https://github.com/Pumpkin-MC/Pumpkin",
    "feed_name": "github rust",
    "category": "技术",
    "title": "Pumpkin-MC/Pumpkin",
    "link": "https://github.com/Pumpkin-MC/Pumpkin",
    "pub_date": "",
    "author": "",
    "description": "Empowering everyone to host fast and efficient Minecraft servers https://pumpkinmc.org/ Pumpkin Pumpkin is a Minecraft server built entirely in Rust, offering a fast, efficient, and customizable experience. It prioritize…",
    "content": "Empowering everyone to host fast and efficient Minecraft servers https://pumpkinmc.org/ Pumpkin Pumpkin is a Minecraft server built entirely in Rust, offering a fast, efficient, and customizable experience. It prioritizes performance and player enjoyment while…"
  },
  {
    "id": "技术-github rust-https://github.com/pnpm/pnpm",
    "feed_name": "github rust",
    "category": "技术",
    "title": "pnpm/pnpm",
    "link": "https://github.com/pnpm/pnpm",
    "pub_date": "",
    "author": "",
    "description": "Fast, disk space efficient package manager https://pnpm.io 简体中文 | 日本語 | 한국어 | Italiano | Português Brasileiro Fast, disk space efficient package manager: Fast. Up to 2x faster than the alternatives (see benchmark). Effic…",
    "content": "Fast, disk space efficient package manager https://pnpm.io 简体中文 | 日本語 | 한국어 | Italiano | Português Brasileiro Fast, disk space efficient package manager: Fast. Up to 2x faster than the alternatives (see benchmark ). Efficient. Files inside node_modules are lin…"
  },
  {
    "id": "技术-github rust-https://github.com/lahfir/agent-desktop",
    "feed_name": "github rust",
    "category": "技术",
    "title": "lahfir/agent-desktop",
    "link": "https://github.com/lahfir/agent-desktop",
    "pub_date": "",
    "author": "",
    "description": "Agent Desktop gives any agent reliable computer use on the desktop. Built with Rust, it sees any app's real UI structure through OS accessibility trees and operates it — refs stay stable and actions stay safe to retry, i…",
    "content": "Agent Desktop gives any agent reliable computer use on the desktop. Built with Rust, it sees any app's real UI structure through OS accessibility trees and operates it — refs stay stable and actions stay safe to retry, instead of guessing from pixels. AGENT DE…"
  },
  {
    "id": "技术-github rust-https://github.com/longbridge/gpui-kit",
    "feed_name": "github rust",
    "category": "技术",
    "title": "longbridge/gpui-kit",
    "link": "https://github.com/longbridge/gpui-kit",
    "pub_date": "",
    "author": "",
    "description": "Rust GUI components for building fantastic cross-platform desktop application by using GPUI. http://gpui-kit.com GPUI Kit English | 简体中文 Build fantastic, high-performance desktop apps with Rust and GPUI. GPUI Kit is a co…",
    "content": "Rust GUI components for building fantastic cross-platform desktop application by using GPUI. http://gpui-kit.com GPUI Kit English | 简体中文 Build fantastic, high-performance desktop apps with Rust and GPUI. GPUI Kit is a comprehensive Rust desktop application fra…"
  },
  {
    "id": "技术-github rust-https://github.com/trailofbits/coop",
    "feed_name": "github rust",
    "category": "技术",
    "title": "trailofbits/coop",
    "link": "https://github.com/trailofbits/coop",
    "pub_date": "",
    "author": "",
    "description": "Isolated VM environment for running Claude Code and Codex https://github.com/trailofbits/coop/blob/main/docs/getting-started.md coop Isolated VM environments for running Claude Code, Codex, and Grok Build. Pronunciation:…",
    "content": "Isolated VM environment for running Claude Code and Codex https://github.com/trailofbits/coop/blob/main/docs/getting-started.md coop Isolated VM environments for running Claude Code, Codex, and Grok Build. Pronunciation: \"coop\" (/kuːp/) — one syllable, rhymes …"
  },
  {
    "id": "技术-github rust-https://github.com/pacifio/atlas",
    "feed_name": "github rust",
    "category": "技术",
    "title": "pacifio/atlas",
    "link": "https://github.com/pacifio/atlas",
    "pub_date": "",
    "author": "",
    "description": "Source control for agents. Use multiple coding agents, track their changes and query them in one place https://www.tryatlas.cc/ Atlas Source control for coding agents. Download · Docs · Website · Contributing · Issues At…",
    "content": "Source control for agents. Use multiple coding agents, track their changes and query them in one place https://www.tryatlas.cc/ Atlas Source control for coding agents. Download · Docs · Website · Contributing · Issues Atlas is source control for coding agents.…"
  },
  {
    "id": "技术-github rust-https://github.com/imsyy/yt-dlp-gui",
    "feed_name": "github rust",
    "category": "技术",
    "title": "imsyy/yt-dlp-gui",
    "link": "https://github.com/imsyy/yt-dlp-gui",
    "pub_date": "",
    "author": "",
    "description": "A modern cross-platform GUI for yt-dlp. Download videos from YouTube, Bilibili, TikTok and 1000+ sites. Built with Tauri + Vue. yt-dlp GUI A modern, beautiful desktop GUI for yt-dlp. Download videos from YouTube, Bilibil…",
    "content": "A modern cross-platform GUI for yt-dlp. Download videos from YouTube, Bilibili, TikTok and 1000+ sites. Built with Tauri + Vue. yt-dlp GUI A modern, beautiful desktop GUI for yt-dlp . Download videos from YouTube, Bilibili, Twitter/X and 1000+ websites with ea…"
  },
  {
    "id": "技术-github rust-https://github.com/run-llama/liteparse",
    "feed_name": "github rust",
    "category": "技术",
    "title": "run-llama/liteparse",
    "link": "https://github.com/run-llama/liteparse",
    "pub_date": "",
    "author": "",
    "description": "A fast, helpful, and open-source document parser https://developers.llamaindex.ai/liteparse/ LiteParse | | | | | | Docs English | 简体中文 Looking for LiteParse V1? Follow this link to the old code LiteParse is a standalone …",
    "content": "A fast, helpful, and open-source document parser https://developers.llamaindex.ai/liteparse/ LiteParse | | | | | | Docs English | 简体中文 Looking for LiteParse V1? Follow this link to the old code LiteParse is a standalone OSS PDF parsing tool focused exclusively…"
  },
  {
    "id": "技术-github rust-https://github.com/tokio-rs/topcoat",
    "feed_name": "github rust",
    "category": "技术",
    "title": "tokio-rs/topcoat",
    "link": "https://github.com/tokio-rs/topcoat",
    "pub_date": "",
    "author": "",
    "description": "A batteries-included framework for building web apps The full full-stack framework for Rust Topcoat is a modular, batteries-included Rust framework for building full-stack apps. It prioritizes simplicity and productivity…",
    "content": "A batteries-included framework for building web apps The full full-stack framework for Rust Topcoat is a modular, batteries-included Rust framework for building full-stack apps. It prioritizes simplicity and productivity. See Learn Topcoat to get started, or t…"
  },
  {
    "id": "技术-github rust-https://github.com/JayWebtech/autoshorts",
    "feed_name": "github rust",
    "category": "技术",
    "title": "JayWebtech/autoshorts",
    "link": "https://github.com/JayWebtech/autoshorts",
    "pub_date": "",
    "author": "",
    "description": "AutoShorts is a local-first desktop application for turning long-form video or audio recordings into high-impact, vertical short-form clip candidates (9:16 portrait) with AI-powered viral moment ranking. ⭐ Support AutoSh…",
    "content": "AutoShorts is a local-first desktop application for turning long-form video or audio recordings into high-impact, vertical short-form clip candidates (9:16 portrait) with AI-powered viral moment ranking. ⭐ Support AutoShorts AutoShorts AutoShorts is a local-fi…"
  },
  {
    "id": "技术-github rust-https://github.com/tauri-apps/tauri",
    "feed_name": "github rust",
    "category": "技术",
    "title": "tauri-apps/tauri",
    "link": "https://github.com/tauri-apps/tauri",
    "pub_date": "",
    "author": "",
    "description": "Build smaller, faster, and more secure desktop and mobile applications with a web frontend. https://tauri.app Introduction Tauri is a framework for building tiny, blazingly fast binaries for all major operating systems. …",
    "content": "Build smaller, faster, and more secure desktop and mobile applications with a web frontend. https://tauri.app Introduction Tauri is a framework for building tiny, blazingly fast binaries for all major operating systems. Developers can integrate any front-end f…"
  },
  {
    "id": "技术-github javascript-https://github.com/vercel/next.js",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "vercel/next.js",
    "link": "https://github.com/vercel/next.js",
    "pub_date": "",
    "author": "",
    "description": "The React Framework https://nextjs.org Next.js Getting Started Used by some of the world's largest companies, Next.js enables you to create full-stack web applications by extending the latest React features, and integrat…",
    "content": "The React Framework https://nextjs.org Next.js Getting Started Used by some of the world's largest companies, Next.js enables you to create full-stack web applications by extending the latest React features, and integrating powerful Rust-based JavaScript tooli…"
  },
  {
    "id": "技术-github javascript-https://github.com/pbakaus/impeccable",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "pbakaus/impeccable",
    "link": "https://github.com/pbakaus/impeccable",
    "pub_date": "",
    "author": "",
    "description": "The design language that makes your AI harness better at design. https://impeccable.style Impeccable Design guidance for AI coding agents. 1 skill, 24 commands, live browser iteration, and 61 deterministic detector rules…",
    "content": "The design language that makes your AI harness better at design. https://impeccable.style Impeccable Design guidance for AI coding agents. 1 skill, 24 commands, live browser iteration, and 61 deterministic detector rules for AI-generated frontend design. Quick…"
  },
  {
    "id": "技术-github javascript-https://github.com/mnfst/awesome-free-llm-apis",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "mnfst/awesome-free-llm-apis",
    "link": "https://github.com/mnfst/awesome-free-llm-apis",
    "pub_date": "",
    "author": "",
    "description": "List of Permanent Free LLM API (API Keys) LLM APIs with permanent free tiers for text inference. All endpoints are OpenAI SDK-compatible unless noted. Each link points to the provider's API key page. All of those free LL…",
    "content": "List of Permanent Free LLM API (API Keys) LLM APIs with permanent free tiers for text inference. All endpoints are OpenAI SDK-compatible unless noted. Each link points to the provider's API key page. All of those free LLM APIs are available at manifest.build -…"
  },
  {
    "id": "技术-github javascript-https://github.com/darkzOGx/youtube-automation-agent",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "darkzOGx/youtube-automation-agent",
    "link": "https://github.com/darkzOGx/youtube-automation-agent",
    "pub_date": "",
    "author": "",
    "description": "🎬 Fully automated YouTube channel management with AI agents. Creates, optimizes & publishes videos 24/7. Works with FREE Gemini API or OpenAI. No coding required! https://github.com/darkzOGx/youtube-automation-agent#rea…",
    "content": "🎬 Fully automated YouTube channel management with AI agents. Creates, optimizes & publishes videos 24/7. Works with FREE Gemini API or OpenAI. No coding required! https://github.com/darkzOGx/youtube-automation-agent#readme AgentTube - ECGHuNZSECqTXabaLjkVrTEn…"
  },
  {
    "id": "技术-github javascript-https://github.com/qist/tvbox",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "qist/tvbox",
    "link": "https://github.com/qist/tvbox",
    "pub_date": "",
    "author": "",
    "description": "OK影视、tvbox配置文件，如果喜欢，请Fork自用。使用前请仔细阅读仓库说明，一旦使用将被视为你已了解。 OK影视、TVBox、猫影视配置文件。所有资源均来自于各路大神无私分享，如有侵权，请联系删除。 所有以任何方式查看本仓库内容的人、或直接或间接使用本仓库内容的使用者都应仔细阅读此声明。本仓库管理者保留随时更改或补充此免责声明的权利。一旦使用、复制、修改了本仓库内容，则视为您已接受此免责声明。 本仓库管理者不能保证本仓库内容的合法…",
    "content": "OK影视、tvbox配置文件，如果喜欢，请Fork自用。使用前请仔细阅读仓库说明，一旦使用将被视为你已了解。 OK影视、TVBox、猫影视配置文件。所有资源均来自于各路大神无私分享，如有侵权，请联系删除。 所有以任何方式查看本仓库内容的人、或直接或间接使用本仓库内容的使用者都应仔细阅读此声明。本仓库管理者保留随时更改或补充此免责声明的权利。一旦使用、复制、修改了本仓库内容，则视为您已接受此免责声明。 本仓库管理者不能保证本仓库内容的合法性、准确性、完整性和有效性，请根据情况自行判断。本仓库内容，仅用于测试和学习研究…"
  },
  {
    "id": "技术-github javascript-https://github.com/pdone/lx-music-source",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "pdone/lx-music-source",
    "link": "https://github.com/pdone/lx-music-source",
    "pub_date": "",
    "author": "",
    "description": "洛雪音乐源 https://awaw.cc/post/lx-music-source lx-music-source 洛雪音乐源，内容源于网络 在线导入 - 原始链接 SixYin https://raw.githubusercontent.com/pdone/lx-music-source/main/sixyin/latest.js Huibq https://raw.githubusercontent.com/pdone/lx-mu…",
    "content": "洛雪音乐源 https://awaw.cc/post/lx-music-source lx-music-source 洛雪音乐源，内容源于网络 在线导入 - 原始链接 SixYin https://raw.githubusercontent.com/pdone/lx-music-source/main/sixyin/latest.js Huibq https://raw.githubusercontent.com/pdone/lx-music-source/main/huibq/latest.js Flower h…"
  },
  {
    "id": "技术-github javascript-https://github.com/androoAGI/starnet",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "androoAGI/starnet",
    "link": "https://github.com/androoAGI/starnet",
    "pub_date": "",
    "author": "",
    "description": "A living pixel-art station where real AI agents do real work. Local-first desktop agent harness - bring your own key, watch your crew actually run. https://github.com/androoAGI/starnet-releases/releases/latest A living p…",
    "content": "A living pixel-art station where real AI agents do real work. Local-first desktop agent harness - bring your own key, watch your crew actually run. https://github.com/androoAGI/starnet-releases/releases/latest A living pixel-art station where real AI agents do…"
  },
  {
    "id": "技术-github javascript-https://github.com/Mathieu2301/TradingView-API",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "Mathieu2301/TradingView-API",
    "link": "https://github.com/Mathieu2301/TradingView-API",
    "pub_date": "",
    "author": "",
    "description": "📈 Get real-time stocks from TradingView TradingView API Get realtime market prices and indicator values from Tradingview ! 🟢 Need help with your project? 🚀 Click here for personalized assistance on your project. 🔵 Te…",
    "content": "📈 Get real-time stocks from TradingView TradingView API Get realtime market prices and indicator values from Tradingview ! 🟢 Need help with your project? 🚀 Click here for personalized assistance on your project. 🔵 Telegram group 👉 To get help, exchange ti…"
  },
  {
    "id": "技术-github javascript-https://github.com/mrdoob/three.js",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "mrdoob/three.js",
    "link": "https://github.com/mrdoob/three.js",
    "pub_date": "",
    "author": "",
    "description": "JavaScript 3D Library. https://threejs.org/ three.js JavaScript 3D library The aim of the project is to create an easy-to-use, lightweight, cross-browser, general-purpose 3D library. The current builds only include WebGL…",
    "content": "JavaScript 3D Library. https://threejs.org/ three.js JavaScript 3D library The aim of the project is to create an easy-to-use, lightweight, cross-browser, general-purpose 3D library. The current builds only include WebGL and WebGPU renderers but SVG and CSS3D …"
  },
  {
    "id": "技术-github javascript-https://github.com/DuarteSantos8/openGym",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "DuarteSantos8/openGym",
    "link": "https://github.com/DuarteSantos8/openGym",
    "pub_date": "",
    "author": "",
    "description": "Self-hosted gym & body-weight tracker — plan routines, log workouts (supersets, warm-ups, cardio), see which muscles are trained, fatigued or detrained, import from FitNotes/Strong/Hevy, passkey login. Your data, your se…",
    "content": "Self-hosted gym & body-weight tracker — plan routines, log workouts (supersets, warm-ups, cardio), see which muscles are trained, fatigued or detrained, import from FitNotes/Strong/Hevy, passkey login. Your data, your server. https://opengym.duarte-santos.ch A…"
  },
  {
    "id": "技术-github lua-https://github.com/olimorris/codecompanion.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "olimorris/codecompanion.nvim",
    "link": "https://github.com/olimorris/codecompanion.nvim",
    "pub_date": "",
    "author": "",
    "description": "✨ AI Coding, Vim Style https://codecompanion.olimorris.dev A Neovim AI coding assistant for coding with LLMs (Anthropic, OpenAI, Gemini, Copilot and more) and AI agents. With built-in support for Agent Client Protocol (A…",
    "content": "✨ AI Coding, Vim Style https://codecompanion.olimorris.dev A Neovim AI coding assistant for coding with LLMs (Anthropic, OpenAI, Gemini, Copilot and more ) and AI agents. With built-in support for Agent Client Protocol (ACP) , Model Context Protocol (MCP) , an…"
  },
  {
    "id": "技术-github lua-https://github.com/Kong/kong",
    "feed_name": "github lua",
    "category": "技术",
    "title": "Kong/kong",
    "link": "https://github.com/Kong/kong",
    "pub_date": "",
    "author": "",
    "description": "🦍 The API and AI Gateway https://konghq.com/install/ Kong or Kong Gateway is a cloud-native, platform-agnostic, scalable API 𖧹 LLM 𖧹 MCP Gateway distinguished for its high performance and extensibility via plugins. It…",
    "content": "🦍 The API and AI Gateway https://konghq.com/install/ Kong or Kong Gateway is a cloud-native, platform-agnostic, scalable API 𖧹 LLM 𖧹 MCP Gateway distinguished for its high performance and extensibility via plugins. It also provides advanced AI traffic capab…"
  },
  {
    "id": "技术-github lua-https://github.com/AndyHazz/bookshelf.koplugin",
    "feed_name": "github lua",
    "category": "技术",
    "title": "AndyHazz/bookshelf.koplugin",
    "link": "https://github.com/AndyHazz/bookshelf.koplugin",
    "pub_date": "",
    "author": "",
    "description": "A nice looking home screen for KOReader. Lets you pick a book from your shelf and read it, with some customisation around the book preview info that's shown. Bookshelf A friendly home screen for KOReader. Browse your lib…",
    "content": "A nice looking home screen for KOReader. Lets you pick a book from your shelf and read it, with some customisation around the book preview info that's shown. Bookshelf A friendly home screen for KOReader. Browse your library by series, author, genre, collectio…"
  },
  {
    "id": "技术-github lua-https://github.com/bryanthaboi/gen1recomp",
    "feed_name": "github lua",
    "category": "技术",
    "title": "bryanthaboi/gen1recomp",
    "link": "https://github.com/bryanthaboi/gen1recomp",
    "pub_date": "",
    "author": "",
    "description": "Gen1Recomp - A native Lua / LÖVE2D recreation of Gen 1 and 2 Poke G1R Deluxe aka Gen1Recomp A native LÖVE2D recreation of Poke Red, Blue, Yellow, Gold, Silver, Crystal, FireRed, LeafGreen, and Emerald. The engine and map…",
    "content": "Gen1Recomp - A native Lua / LÖVE2D recreation of Gen 1 and 2 Poke G1R Deluxe aka Gen1Recomp A native LÖVE2D recreation of Poke Red, Blue, Yellow, Gold, Silver, Crystal, FireRed, LeafGreen, and Emerald. The engine and map behavior are hand-written Lua; game dat…"
  },
  {
    "id": "技术-github lua-https://github.com/koreader/koreader",
    "feed_name": "github lua",
    "category": "技术",
    "title": "koreader/koreader",
    "link": "https://github.com/koreader/koreader",
    "pub_date": "",
    "author": "",
    "description": "An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats, running on Cervantes, Kindle, Kobo, PocketBook and Android devices http://koreader.rocks/ KOReader is a document viewer primarily aimed a…",
    "content": "An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats, running on Cervantes, Kindle, Kobo, PocketBook and Android devices http://koreader.rocks/ KOReader is a document viewer primarily aimed at e-ink readers. Download • User guide •…"
  },
  {
    "id": "技术-github lua-https://github.com/saghen/blink.cmp",
    "feed_name": "github lua",
    "category": "技术",
    "title": "saghen/blink.cmp",
    "link": "https://github.com/saghen/blink.cmp",
    "pub_date": "",
    "author": "",
    "description": "Performant, batteries-included completion plugin for Neovim https://cmp.saghen.dev Warning V2 is under active development with many breaking changes. Consider staying on stable by using branch = 'v1' or version = \"1.*\" i…",
    "content": "Performant, batteries-included completion plugin for Neovim https://cmp.saghen.dev Warning V2 is under active development with many breaking changes. Consider staying on stable by using branch = 'v1' or version = \"1.*\" in your lazy.nvim config. See the V1 docs…"
  },
  {
    "id": "技术-github lua-https://github.com/lewis6991/gitsigns.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "lewis6991/gitsigns.nvim",
    "link": "https://github.com/lewis6991/gitsigns.nvim",
    "pub_date": "",
    "author": "",
    "description": "Git integration for buffers gitsigns.nvim Deep buffer integration for Git 👀 Preview Hunk Actions Line Blame ✨ Features Signs Adds signs to the sign column to indicate added, changed, and deleted lines. Supports differen…",
    "content": "Git integration for buffers gitsigns.nvim Deep buffer integration for Git 👀 Preview Hunk Actions Line Blame ✨ Features Signs Adds signs to the sign column to indicate added, changed, and deleted lines. Supports different signs for staged changes. Add counts t…"
  },
  {
    "id": "技术-github lua-https://github.com/coder/claudecode.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "coder/claudecode.nvim",
    "link": "https://github.com/coder/claudecode.nvim",
    "pub_date": "",
    "author": "",
    "description": "🧩 Claude Code Neovim IDE Extension claudecode.nvim The first Neovim IDE integration for Claude Code — bringing Anthropic's AI coding assistant to your favorite editor with a pure Lua implementation. 🎯 TL;DR: When Anthr…",
    "content": "🧩 Claude Code Neovim IDE Extension claudecode.nvim The first Neovim IDE integration for Claude Code — bringing Anthropic's AI coding assistant to your favorite editor with a pure Lua implementation. 🎯 TL;DR: When Anthropic released Claude Code with VS Code a…"
  },
  {
    "id": "技术-github lua-https://github.com/neovim/nvim-lspconfig",
    "feed_name": "github lua",
    "category": "技术",
    "title": "neovim/nvim-lspconfig",
    "link": "https://github.com/neovim/nvim-lspconfig",
    "pub_date": "",
    "author": "",
    "description": "Quickstart configs for Nvim LSP nvim-lspconfig nvim-lspconfig is a collection of LSP server configurations for the Nvim LSP client. View all configs, or run :help lspconfig-all from Nvim. Important ⚠️ require('lspconfig'…",
    "content": "Quickstart configs for Nvim LSP nvim-lspconfig nvim-lspconfig is a collection of LSP server configurations for the Nvim LSP client . View all configs , or run :help lspconfig-all from Nvim. Important ⚠️ require('lspconfig') (the legacy \"framework\" of nvim-lspc…"
  },
  {
    "id": "技术-github lua-https://github.com/mason-org/mason-lspconfig.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "mason-org/mason-lspconfig.nvim",
    "link": "https://github.com/mason-org/mason-lspconfig.nvim",
    "pub_date": "",
    "author": "",
    "description": "Extension to mason.nvim that makes it easier to use lspconfig with mason.nvim. mason-lspconfig.nvim mason-lspconfig bridges mason.nvim with the lspconfig plugin - making it easier to use both plugins together. :help maso…",
    "content": "Extension to mason.nvim that makes it easier to use lspconfig with mason.nvim. mason-lspconfig.nvim mason-lspconfig bridges mason.nvim with the lspconfig plugin - making it easier to use both plugins together. :help mason-lspconfig.nvim Latest version: v2.3.0 …"
  },
  {
    "id": "技术-github lua-https://github.com/HDoujinDownloader/HDoujinDownloader",
    "feed_name": "github lua",
    "category": "技术",
    "title": "HDoujinDownloader/HDoujinDownloader",
    "link": "https://github.com/HDoujinDownloader/HDoujinDownloader",
    "pub_date": "",
    "author": "",
    "description": "A general-purpose doujinshi and image gallery downloader https://doujindownloader.com HDoujin Downloader is a general-purpose doujinshi and image gallery downloader that works with a wide variety of different websites. F…",
    "content": "A general-purpose doujinshi and image gallery downloader https://doujindownloader.com HDoujin Downloader is a general-purpose doujinshi and image gallery downloader that works with a wide variety of different websites. Features Runs as a portable executable, w…"
  },
  {
    "id": "技术-github lua-https://github.com/ibhagwan/fzf-lua",
    "feed_name": "github lua",
    "category": "技术",
    "title": "ibhagwan/fzf-lua",
    "link": "https://github.com/ibhagwan/fzf-lua",
    "pub_date": "",
    "author": "",
    "description": "Improved fzf.vim written in lua fzf ❤️ lua Quickstart • Installation • Usage • Commands • Customization • Wiki “because you can and you love fzf” - @junegunn \"fzf changed my command life, it can change yours too, if you …",
    "content": "Improved fzf.vim written in lua fzf ❤️ lua Quickstart • Installation • Usage • Commands • Customization • Wiki “because you can and you love fzf” - @junegunn \"fzf changed my command life, it can change yours too, if you allow it\" - @ibhagwan Quickstart To quic…"
  },
  {
    "id": "技术-github lua-https://github.com/b0o/SchemaStore.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "b0o/SchemaStore.nvim",
    "link": "https://github.com/b0o/SchemaStore.nvim",
    "pub_date": "",
    "author": "",
    "description": "🛍 JSON schemas for Neovim https://schemastore.org SchemaStore.nvim A Neovim plugin that provides the SchemaStore catalog for use with jsonls and yamlls. Install Lazy.nvim: \"b0o/schemastore.nvim\", Packer: use \"b0o/schema…",
    "content": "🛍 JSON schemas for Neovim https://schemastore.org SchemaStore.nvim A Neovim plugin that provides the SchemaStore catalog for use with jsonls and yamlls . Install Lazy.nvim : \"b0o/schemastore.nvim\", Packer : use \"b0o/schemastore.nvim\" Usage To use SchemaStore.…"
  },
  {
    "id": "技术-github lua-https://github.com/xhcherry/GTA5-Stand-LuaAIO",
    "feed_name": "github lua",
    "category": "技术",
    "title": "xhcherry/GTA5-Stand-LuaAIO",
    "link": "https://github.com/xhcherry/GTA5-Stand-LuaAIO",
    "pub_date": "",
    "author": "",
    "description": "GTA5 Mod Stand Lua All in One:快捷任务、crash、模组(人物|车辆|地图|模型)、娱乐等多种拓展功能玩法的lua脚本 GTA5-Stand-LuaAIO --> 中文版本/English Version GTA5 Mod Stand Lua All in One:将快捷任务、远程崩溃、模组(人物|车辆|地图|模型)、娱乐等多种standlua脚本于一体的综合库 目录 GTA5-Stand-LuaAIO 目…",
    "content": "GTA5 Mod Stand Lua All in One:快捷任务、crash、模组(人物|车辆|地图|模型)、娱乐等多种拓展功能玩法的lua脚本 GTA5-Stand-LuaAIO --> 中文版本 / English Version GTA5 Mod Stand Lua All in One:将快捷任务、远程崩溃、模组(人物|车辆|地图|模型)、娱乐等多种standlua脚本于一体的综合库 目录 GTA5-Stand-LuaAIO 目录 合集优势 简易安装教程 一劳永逸安装教程 文件目录结构 仓库Lua二次开…"
  },
  {
    "id": "技术-github lua-https://github.com/gbprod/yanky.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "gbprod/yanky.nvim",
    "link": "https://github.com/gbprod/yanky.nvim",
    "pub_date": "",
    "author": "",
    "description": "Improved Yank and Put functionalities for Neovim 🍃 yanky.nvim The aim of yanky.nvim is to improve yank and put functionalities for Neovim. French slogan: \"Vas-y Yanky, c'est bon !\" - Yanky Vincent Or in English: \"Yanky-…",
    "content": "Improved Yank and Put functionalities for Neovim 🍃 yanky.nvim The aim of yanky.nvim is to improve yank and put functionalities for Neovim. French slogan: \"Vas-y Yanky, c'est bon !\" - Yanky Vincent Or in English: \"Yanky-ki-yay, motherf*cker\" - John McYanky ✨ F…"
  },
  {
    "id": "技术-github lua-https://github.com/RestedXP/RXPGuides",
    "feed_name": "github lua",
    "category": "技术",
    "title": "RestedXP/RXPGuides",
    "link": "https://github.com/RestedXP/RXPGuides",
    "pub_date": "",
    "author": "",
    "description": "RXPGuides is a platform to write in-game leveling guides for WoW Classic https://www.restedxp.com/ RestedXP Guides Overview This is a platform to write in-game leveling guides for WoW Classic Writing your own guides If y…",
    "content": "RXPGuides is a platform to write in-game leveling guides for WoW Classic https://www.restedxp.com/ RestedXP Guides Overview This is a platform to write in-game leveling guides for WoW Classic Writing your own guides If you wish to create your own guides using …"
  },
  {
    "id": "技术-github lua-https://github.com/Questie/Questie",
    "feed_name": "github lua",
    "category": "技术",
    "title": "Questie/Questie",
    "link": "https://github.com/Questie/Questie",
    "pub_date": "",
    "author": "",
    "description": "Questie: The WoW Classic quest helper Questie Language version English Español 简体中文 Download We suggest you use the CurseForge Client to manage your WoW addons in general. You will find Questie here on CurseForge. Altern…",
    "content": "Questie: The WoW Classic quest helper Questie Language version English Español 简体中文 Download We suggest you use the CurseForge Client to manage your WoW addons in general. You will find Questie here on CurseForge . Alternatively you can always use the latest G…"
  }
];

export default jsonData;
