const jsonData = [
  {
    "id": "技术-阮一峰的网络日志-http://www.ruanyifeng.com/blog/2026/06/weekly-issue-400.html",
    "feed_name": "阮一峰的网络日志",
    "category": "技术",
    "title": "科技爱好者周刊（第 400 期）：rsync 的争论",
    "link": "http://www.ruanyifeng.com/blog/2026/06/weekly-issue-400.html",
    "pub_date": "2026-06-12 07:26:08",
    "author": "阮一峰",
    "description": "这里记录每周值得分享的科技内容，周五发布。（[通知] 下周端午假期，周刊休息。） 本杂志开源，欢迎投稿。另有《谁在招人》服务，发布程序员招聘信息。合作请邮件联系（yifeng.ruan@gmail.com）。 封面图 上海体育学院内的绿瓦书店，是上海首家体育主题书店。中庭有13米高的\"明月山\"，四周是小路，意为\"书山有路勤为径\"。（via） rsync 的争论 rsync 是计算机同步最常用的工具，属于服务器的基本命令。 最近，有人发现…",
    "content": "这里记录每周值得分享的科技内容，周五发布。（ [通知] 下周端午假期，周刊休息。 ） 本杂志 开源 ，欢迎 投稿 。另有 《谁在招人》 服务，发布程序员招聘信息。合作请 邮件联系 （yifeng.ruan@gmail.com）。 封面图 上海体育学院内的绿瓦书店，是上海首家体育主题书店。中庭有13米高的\"明月山\"，四周是小路，意为\"书山有路勤为径\"。（ via ） rsync 的争论 rsync 是计算机同步最常用的工具，属于服务器的基本命令。 最近，有人发现，它的 最新版本 3.4.3 是由 Claude 生成的…"
  },
  {
    "id": "技术-阮一峰的网络日志-http://www.ruanyifeng.com/blog/2026/06/weekly-issue-399.html",
    "feed_name": "阮一峰的网络日志",
    "category": "技术",
    "title": "科技爱好者周刊（第 399 期）：中国 AI 大厂访问记",
    "link": "http://www.ruanyifeng.com/blog/2026/06/weekly-issue-399.html",
    "pub_date": "2026-06-05 08:07:45",
    "author": "阮一峰",
    "description": "这里记录每周值得分享的科技内容，周五发布。 本杂志开源，欢迎投稿。另有《谁在招人》服务，发布程序员招聘信息。合作请邮件联系（yifeng.ruan@gmail.com）。 封面图 本周开馆的深圳国际美术馆。（via） 中国 AI 大厂访问记 今年5月上旬，一个美国访问团来到中国，访问了14家 AI 和机器人公司。 访问对象包括 DeepSeek、月之暗面、MiniMax、智谱、字节跳动、阿里、蚂蚁、小米、零一万物、宇树、魔搭社区等。 所…",
    "content": "这里记录每周值得分享的科技内容，周五发布。 本杂志 开源 ，欢迎 投稿 。另有 《谁在招人》 服务，发布程序员招聘信息。合作请 邮件联系 （yifeng.ruan@gmail.com）。 封面图 本周开馆的深圳国际美术馆。（ via ） 中国 AI 大厂访问记 今年5月上旬，一个美国访问团来到中国，访问了14家 AI 和机器人公司。 访问对象包括 DeepSeek、月之暗面、MiniMax、智谱、字节跳动、阿里、蚂蚁、小米、零一万物、宇树、魔搭社区等。 所有成员都是科技分析师，回到美国后，每个人都写了访问观感： K…"
  },
  {
    "id": "技术-阮一峰的网络日志-http://www.ruanyifeng.com/blog/2026/05/weekly-issue-398.html",
    "feed_name": "阮一峰的网络日志",
    "category": "技术",
    "title": "科技爱好者周刊（第 398 期）：Token 费用难以负担",
    "link": "http://www.ruanyifeng.com/blog/2026/05/weekly-issue-398.html",
    "pub_date": "2026-05-29 08:08:39",
    "author": "阮一峰",
    "description": "这里记录每周值得分享的科技内容，周五发布。 本杂志开源，欢迎投稿。另有《谁在招人》服务，发布程序员招聘信息。合作请邮件联系（yifeng.ruan@gmail.com）。 封面图 去年开放的浙江省安吉县的安吉文化艺术中心。当地盛产竹子，屋顶都采用竹叶造型。（daemin_kg@ig） Token 费用难以负担 上周，OpenClaw（龙虾）的创始人彼得·斯坦伯格（Peter Steinberger）贴出了自己的 Token 使用量。 他…",
    "content": "这里记录每周值得分享的科技内容，周五发布。 本杂志 开源 ，欢迎 投稿 。另有 《谁在招人》 服务，发布程序员招聘信息。合作请 邮件联系 （yifeng.ruan@gmail.com）。 封面图 去年开放的浙江省安吉县的安吉文化艺术中心。当地盛产竹子，屋顶都采用竹叶造型。（ daemin_kg@ig ） Token 费用难以负担 上周，OpenClaw（龙虾）的创始人彼得·斯坦伯格（Peter Steinberger）贴出了自己的 Token 使用量 。 他不是故意炫耀，自己用了多少 Token，而是为了介绍工具软…"
  },
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/122",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 122 期",
    "link": "https://hellogithub.com/periodical/volume/122",
    "pub_date": "2026-05-28 08:07:51",
    "author": "",
    "description": "本期共有 39 个项目，包含 C 项目 (2)，C# 项目 (3)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (5)，Python 项目 (4)，Rust 项目 (3)，Skills (3)，Swift 项目 (3)，人工智能 (5)，其它 (5)",
    "content": "本期共有 39 个项目，包含 C 项目 (2)，C# 项目 (3)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (5)，Python 项目 (4)，Rust 项目 (3)，Skills (3)，Swift 项目 (3)，人工智能 (5)，其它 (5)"
  },
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/121",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 121 期",
    "link": "https://hellogithub.com/periodical/volume/121",
    "pub_date": "2026-04-28 08:05:57",
    "author": "",
    "description": "本期共有 40 个项目，包含 C 项目 (1)，C# 项目 (2)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (4)，Kotlin 项目 (1)，Python 项目 (3)，Rust 项目 (4)，Skills (4)，Swift 项目 (3)，人工智能 (5)，其它 (5)，开源书籍 (2)",
    "content": "本期共有 40 个项目，包含 C 项目 (1)，C# 项目 (2)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (4)，Kotlin 项目 (1)，Python 项目 (3)，Rust 项目 (4)，Skills (4)，Swift 项目 (3)，人工智能 (5)，其它 (5)，开源书籍 (2)"
  },
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/120",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 120 期",
    "link": "https://hellogithub.com/periodical/volume/120",
    "pub_date": "2026-03-27 08:08:31",
    "author": "",
    "description": "本期共有 40 个项目，包含 C 项目 (1)，C# 项目 (4)，C++ 项目 (2)，Go 项目 (4)，Java 项目 (3)，JavaScript 项目 (5)，Kotlin 项目 (2)，Python 项目 (4)，Rust 项目 (3)，Swift 项目 (2)，人工智能 (5)，其它 (5)",
    "content": "本期共有 40 个项目，包含 C 项目 (1)，C# 项目 (4)，C++ 项目 (2)，Go 项目 (4)，Java 项目 (3)，JavaScript 项目 (5)，Kotlin 项目 (2)，Python 项目 (4)，Rust 项目 (3)，Swift 项目 (2)，人工智能 (5)，其它 (5)"
  },
  {
    "id": "技术-github all-https://github.com/iptv-org/iptv",
    "feed_name": "github all",
    "category": "技术",
    "title": "iptv-org/iptv",
    "link": "https://github.com/iptv-org/iptv",
    "pub_date": "",
    "author": "",
    "description": "Collection of publicly available IPTV channels from all over the world IPTV Collection of publicly available IPTV (Internet Protocol television) channels from all over the world. Table of contents 🚀 How to use? 📺 Playl…",
    "content": "Collection of publicly available IPTV channels from all over the world IPTV Collection of publicly available IPTV (Internet Protocol television) channels from all over the world. Table of contents 🚀 How to use? 📺 Playlists 🗓 EPG 🗄 Database 👨‍💻 API 📚 Res…"
  },
  {
    "id": "技术-github all-https://github.com/teslamate-org/teslamate",
    "feed_name": "github all",
    "category": "技术",
    "title": "teslamate-org/teslamate",
    "link": "https://github.com/teslamate-org/teslamate",
    "pub_date": "",
    "author": "",
    "description": "A self-hosted data logger for your Tesla 🚘 [main maintainer=@JakobLichterfeld] TeslaMate A powerful, self-hosted data logger for your Tesla. Written in Elixir Data is stored in a Postgres database Visualization and data…",
    "content": "A self-hosted data logger for your Tesla 🚘 [main maintainer=@JakobLichterfeld] TeslaMate A powerful, self-hosted data logger for your Tesla. Written in Elixir Data is stored in a Postgres database Visualization and data analysis with Grafana Vehicle data is p…"
  },
  {
    "id": "技术-github all-https://github.com/Panniantong/Agent-Reach",
    "feed_name": "github all",
    "category": "技术",
    "title": "Panniantong/Agent-Reach",
    "link": "https://github.com/Panniantong/Agent-Reach",
    "pub_date": "",
    "author": "",
    "description": "Give your AI agent eyes to see the entire internet. Read & search Twitter, Reddit, YouTube, GitHub, Bilibili, XiaoHongShu — one CLI, zero API fees. 👁️ Agent Reach 给你的 AI Agent 一键装上互联网能力 当下最稳的接入方式，替你选好、装好、体检好——接入方式会换代，你不…",
    "content": "Give your AI agent eyes to see the entire internet. Read & search Twitter, Reddit, YouTube, GitHub, Bilibili, XiaoHongShu — one CLI, zero API fees. 👁️ Agent Reach 给你的 AI Agent 一键装上互联网能力 当下最稳的接入方式，替你选好、装好、体检好——接入方式会换代，你不用操心 🇨🇳 国内访问：本项目托管于 AtomGit 镜像 （与 GitHu…"
  },
  {
    "id": "技术-github all-https://github.com/meshery/meshery",
    "feed_name": "github all",
    "category": "技术",
    "title": "meshery/meshery",
    "link": "https://github.com/meshery/meshery",
    "pub_date": "",
    "author": "",
    "description": "Meshery, the cloud native manager --> --> If you like Meshery, please ★ this repository to show your support! 🤩 MESHERY IS A CLOUD NATIVE COMPUTING FOUNDATION PROJECT A self-service engineering platform, Meshery, is the…",
    "content": "Meshery, the cloud native manager --> --> If you like Meshery, please ★ this repository to show your support! 🤩 MESHERY IS A CLOUD NATIVE COMPUTING FOUNDATION PROJECT A self-service engineering platform, Meshery , is the open source, cloud native manager that…"
  },
  {
    "id": "技术-github all-https://github.com/chatwoot/chatwoot",
    "feed_name": "github all",
    "category": "技术",
    "title": "chatwoot/chatwoot",
    "link": "https://github.com/chatwoot/chatwoot",
    "pub_date": "",
    "author": "",
    "description": "Open-source live-chat, email support, omni-channel desk. An alternative to Intercom, Zendesk, Salesforce Service Cloud etc. 🔥💬 Chatwoot The modern customer support platform, an open-source alternative to Intercom, Zend…",
    "content": "Open-source live-chat, email support, omni-channel desk. An alternative to Intercom, Zendesk, Salesforce Service Cloud etc. 🔥💬 Chatwoot The modern customer support platform, an open-source alternative to Intercom, Zendesk, Salesforce Service Cloud etc. Chatw…"
  },
  {
    "id": "技术-github all-https://github.com/krahets/hello-algo",
    "feed_name": "github all",
    "category": "技术",
    "title": "krahets/hello-algo",
    "link": "https://github.com/krahets/hello-algo",
    "pub_date": "",
    "author": "",
    "description": "《Hello 算法》：动画图解、一键运行的数据结构与算法教程。支持简中、繁中、English、日本語，提供 Python, Java, C++, C, C#, JS, Go, Swift, Rust, Ruby, Kotlin, TS, Dart 等代码实现 动画图解、一键运行的数据结构与算法教程 简体中文 ｜ 繁體中文 ｜ English ｜ 日本語 ｜ Русский 关于本书 本项目旨在打造一本开源免费、新手友好的数据结构与算法入…",
    "content": "《Hello 算法》：动画图解、一键运行的数据结构与算法教程。支持简中、繁中、English、日本語，提供 Python, Java, C++, C, C#, JS, Go, Swift, Rust, Ruby, Kotlin, TS, Dart 等代码实现 动画图解、一键运行的数据结构与算法教程 简体中文 ｜ 繁體中文 ｜ English ｜ 日本語 ｜ Русский 关于本书 本项目旨在打造一本开源免费、新手友好的数据结构与算法入门教程。 全书采用动画图解，内容清晰易懂、学习曲线平滑，引导初学者探索数据结构与…"
  },
  {
    "id": "技术-github all-https://github.com/freeCodeCamp/freeCodeCamp",
    "feed_name": "github all",
    "category": "技术",
    "title": "freeCodeCamp/freeCodeCamp",
    "link": "https://github.com/freeCodeCamp/freeCodeCamp",
    "pub_date": "",
    "author": "",
    "description": "freeCodeCamp.org's open-source codebase and curriculum. Learn math, programming, and computer science for free. freeCodeCamp.org's open-source codebase and curriculum freeCodeCamp.org is a friendly community where you ca…",
    "content": "freeCodeCamp.org's open-source codebase and curriculum. Learn math, programming, and computer science for free. freeCodeCamp.org 's open-source codebase and curriculum freeCodeCamp.org is a friendly community where you can learn to code for free. It is run by …"
  },
  {
    "id": "技术-github all-https://github.com/trycua/cua",
    "feed_name": "github all",
    "category": "技术",
    "title": "trycua/cua",
    "link": "https://github.com/trycua/cua",
    "pub_date": "",
    "author": "",
    "description": "Open-source infrastructure for Computer-Use Agents. Sandboxes, SDKs, and benchmarks to train and evaluate AI agents that can control full desktops (macOS, Linux, Windows). Build, benchmark, and deploy agents that use com…",
    "content": "Open-source infrastructure for Computer-Use Agents. Sandboxes, SDKs, and benchmarks to train and evaluate AI agents that can control full desktops (macOS, Linux, Windows). Build, benchmark, and deploy agents that use computers Choose Your Path Building your ow…"
  },
  {
    "id": "技术-github all-https://github.com/jwasham/coding-interview-university",
    "feed_name": "github all",
    "category": "技术",
    "title": "jwasham/coding-interview-university",
    "link": "https://github.com/jwasham/coding-interview-university",
    "pub_date": "",
    "author": "",
    "description": "A complete computer science study plan to become a software engineer. Coding Interview University I originally created this as a short to-do list of study topics for becoming a software engineer, but it grew to the large…",
    "content": "A complete computer science study plan to become a software engineer. Coding Interview University I originally created this as a short to-do list of study topics for becoming a software engineer, but it grew to the large list you see today. After going through…"
  },
  {
    "id": "技术-github all-https://github.com/rohitg00/ai-engineering-from-scratch",
    "feed_name": "github all",
    "category": "技术",
    "title": "rohitg00/ai-engineering-from-scratch",
    "link": "https://github.com/rohitg00/ai-engineering-from-scratch",
    "pub_date": "",
    "author": "",
    "description": "Learn it. Build it. Ship it for others. From the creator of Agent Memory - #1 Persistent memory ⭐ which naturally works with any agents or chat assistants. ░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒…",
    "content": "Learn it. Build it. Ship it for others. From the creator of Agent Memory - #1 Persistent memory ⭐ which naturally works with any agents or chat assistants. ░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒ 84% of studen…"
  },
  {
    "id": "技术-github all-https://github.com/music-assistant/server",
    "feed_name": "github all",
    "category": "技术",
    "title": "music-assistant/server",
    "link": "https://github.com/music-assistant/server",
    "pub_date": "",
    "author": "",
    "description": "Music Assistant is a free, opensource Media library manager that connects to your streaming services and a wide range of connected speakers. The server is the beating heart, the core of Music Assistant and must run on an…",
    "content": "Music Assistant is a free, opensource Media library manager that connects to your streaming services and a wide range of connected speakers. The server is the beating heart, the core of Music Assistant and must run on an always-on device like a Raspberry Pi, a…"
  },
  {
    "id": "技术-github all-https://github.com/Free-TV/IPTV",
    "feed_name": "github all",
    "category": "技术",
    "title": "Free-TV/IPTV",
    "link": "https://github.com/Free-TV/IPTV",
    "pub_date": "",
    "author": "",
    "description": "M3U Playlist for free TV channels Free TV This is an M3U playlist for free TV channels around the World. Either free locally (over the air): Or free on the Internet: Plex TV Pluto TV (English, Spanish, French, Italian) R…",
    "content": "M3U Playlist for free TV channels Free TV This is an M3U playlist for free TV channels around the World. Either free locally (over the air): Or free on the Internet: Plex TV Pluto TV (English, Spanish, French, Italian) Redbox Live TV Roku TV Samsung TV Plus Yo…"
  },
  {
    "id": "技术-github all-https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots",
    "feed_name": "github all",
    "category": "技术",
    "title": "Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots",
    "link": "https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots",
    "pub_date": "",
    "author": "",
    "description": "Introduction to Autonomous Robots Introduction-to-Autonomous-Robots An open textbook focusing on computational principles of autonomous robots. The source-code is released under Creative Commons 4.0 (CC-BY-NC-ND), wherea…",
    "content": "Introduction to Autonomous Robots Introduction-to-Autonomous-Robots An open textbook focusing on computational principles of autonomous robots. The source-code is released under Creative Commons 4.0 (CC-BY-NC-ND), whereas the print version is copyrighted by MI…"
  },
  {
    "id": "技术-github all-https://github.com/Raphire/Win11Debloat",
    "feed_name": "github all",
    "category": "技术",
    "title": "Raphire/Win11Debloat",
    "link": "https://github.com/Raphire/Win11Debloat",
    "pub_date": "",
    "author": "",
    "description": "A simple, lightweight PowerShell script that allows you to remove pre-installed apps, disable telemetry, as well as perform various other changes to declutter and customize your Windows experience. Win11Debloat works for…",
    "content": "A simple, lightweight PowerShell script that allows you to remove pre-installed apps, disable telemetry, as well as perform various other changes to declutter and customize your Windows experience. Win11Debloat works for both Windows 10 and Windows 11. Win11De…"
  },
  {
    "id": "技术-github all-https://github.com/mikeroyal/Self-Hosting-Guide",
    "feed_name": "github all",
    "category": "技术",
    "title": "mikeroyal/Self-Hosting-Guide",
    "link": "https://github.com/mikeroyal/Self-Hosting-Guide",
    "pub_date": "",
    "author": "",
    "description": "Self-Hosting Guide. Learn all about locally hosting (on premises & private web servers) and managing software applications by yourself or your organization. Including Cloud, LLMs, WireGuard, Automation, Home Assistant, a…",
    "content": "Self-Hosting Guide. Learn all about locally hosting (on premises & private web servers) and managing software applications by yourself or your organization. Including Cloud, LLMs, WireGuard, Automation, Home Assistant, and Networking. Self Hosting Guide A guid…"
  },
  {
    "id": "技术-github all-https://github.com/itsfatduck/optimizerDuck",
    "feed_name": "github all",
    "category": "技术",
    "title": "itsfatduck/optimizerDuck",
    "link": "https://github.com/itsfatduck/optimizerDuck",
    "pub_date": "",
    "author": "",
    "description": "Free, open-source Windows optimization tool for performance, privacy, and simplicity. optimizerDuck optimizerDuck is a free, open-source Windows optimization tool focused on performance, privacy, and simplicity. Getting …",
    "content": "Free, open-source Windows optimization tool for performance, privacy, and simplicity. optimizerDuck optimizerDuck is a free, open-source Windows optimization tool focused on performance, privacy, and simplicity. Getting Started | How It Works | FAQ English | T…"
  },
  {
    "id": "技术-github all-https://github.com/NVIDIA/SkillSpector",
    "feed_name": "github all",
    "category": "技术",
    "title": "NVIDIA/SkillSpector",
    "link": "https://github.com/NVIDIA/SkillSpector",
    "pub_date": "",
    "author": "",
    "description": "Security scanner for AI agent skills. Detect vulnerabilities, malicious patterns, and security risks. SkillSpector Security scanner for AI agent skills. Detect vulnerabilities, malicious patterns, and security risks befo…",
    "content": "Security scanner for AI agent skills. Detect vulnerabilities, malicious patterns, and security risks. SkillSpector Security scanner for AI agent skills. Detect vulnerabilities, malicious patterns, and security risks before installing agent skills. Overview AI …"
  },
  {
    "id": "技术-github all-https://github.com/shiyu-coder/Kronos",
    "feed_name": "github all",
    "category": "技术",
    "title": "shiyu-coder/Kronos",
    "link": "https://github.com/shiyu-coder/Kronos",
    "pub_date": "",
    "author": "",
    "description": "Kronos: A Foundation Model for the Language of Financial Markets Kronos: A Foundation Model for the Language of Financial Markets Deutsch | Español | Français | 日本語 | 한국어 | Português | Русский | 中文 Kronos is the first op…",
    "content": "Kronos: A Foundation Model for the Language of Financial Markets Kronos: A Foundation Model for the Language of Financial Markets Deutsch | Español | Français | 日本語 | 한국어 | Português | Русский | 中文 Kronos is the first open-source foundation model for financial…"
  },
  {
    "id": "技术-github python-https://github.com/mvanhorn/last30days-skill",
    "feed_name": "github python",
    "category": "技术",
    "title": "mvanhorn/last30days-skill",
    "link": "https://github.com/mvanhorn/last30days-skill",
    "pub_date": "",
    "author": "",
    "description": "AI agent skill that researches any topic across Reddit, X, YouTube, HN, Polymarket, and the web - then synthesizes a grounded summary /last30days An AI agent-led search engine scored by upvotes, likes, and real money - n…",
    "content": "AI agent skill that researches any topic across Reddit, X, YouTube, HN, Polymarket, and the web - then synthesizes a grounded summary /last30days An AI agent-led search engine scored by upvotes, likes, and real money - not editors. This README tracks the curre…"
  },
  {
    "id": "技术-github python-https://github.com/chopratejas/headroom",
    "feed_name": "github python",
    "category": "技术",
    "title": "chopratejas/headroom",
    "link": "https://github.com/chopratejas/headroom",
    "pub_date": "",
    "author": "",
    "description": "Compress tool outputs, logs, files, and RAG chunks before they reach the LLM. 60-95% fewer tokens, same answers. Library, proxy, MCP server. 60–95% fewer tokens · library · proxy · MCP · 6 algorithms · local-first · reve…",
    "content": "Compress tool outputs, logs, files, and RAG chunks before they reach the LLM. 60-95% fewer tokens, same answers. Library, proxy, MCP server. ██╗ ██╗███████╗ █████╗ ██████╗ ██████╗ ██████╗ ██████╗ ███╗ ███╗ ██║ ██║██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔═══██╗██╔═══…"
  },
  {
    "id": "技术-github python-https://github.com/RyanCodrai/turbovec",
    "feed_name": "github python",
    "category": "技术",
    "title": "RyanCodrai/turbovec",
    "link": "https://github.com/RyanCodrai/turbovec",
    "pub_date": "",
    "author": "",
    "description": "A vector index built on TurboQuant, written in Rust with Python bindings A 10 million document corpus takes 31 GB of RAM as float32. turbovec fits it in 4 GB - and searches it faster than FAISS. turbovec is a Rust vector…",
    "content": "A vector index built on TurboQuant, written in Rust with Python bindings A 10 million document corpus takes 31 GB of RAM as float32. turbovec fits it in 4 GB - and searches it faster than FAISS. turbovec is a Rust vector index with Python bindings, built on Go…"
  },
  {
    "id": "技术-github python-https://github.com/roboflow/supervision",
    "feed_name": "github python",
    "category": "技术",
    "title": "roboflow/supervision",
    "link": "https://github.com/roboflow/supervision",
    "pub_date": "",
    "author": "",
    "description": "We write your reusable computer vision tools. 💜 notebooks | inference | autodistill | maestro 👋 hello We are your essential toolkit for computer vision. From data loading to real-time zone counting, we provide the buil…",
    "content": "We write your reusable computer vision tools. 💜 notebooks | inference | autodistill | maestro 👋 hello We are your essential toolkit for computer vision. From data loading to real-time zone counting, we provide the building blocks so you can focus on building…"
  },
  {
    "id": "技术-github python-https://github.com/microsoft/markitdown",
    "feed_name": "github python",
    "category": "技术",
    "title": "microsoft/markitdown",
    "link": "https://github.com/microsoft/markitdown",
    "pub_date": "",
    "author": "",
    "description": "Python tool for converting files and office documents to Markdown. MarkItDown Important MarkItDown performs I/O with the privileges of the current process. Like open() or requests.get(), it will access resources that the…",
    "content": "Python tool for converting files and office documents to Markdown. MarkItDown Important MarkItDown performs I/O with the privileges of the current process. Like open() or requests.get(), it will access resources that the process itself can access. Sanitize you…"
  },
  {
    "id": "技术-github python-https://github.com/huggingface/OpenEnv",
    "feed_name": "github python",
    "category": "技术",
    "title": "huggingface/OpenEnv",
    "link": "https://github.com/huggingface/OpenEnv",
    "pub_date": "",
    "author": "",
    "description": "An interface library for RL post training with environments. OpenEnv: Agentic Execution Environments An e2e framework for creating, deploying and using isolated execution environments for agentic RL training, built using…",
    "content": "An interface library for RL post training with environments. OpenEnv: Agentic Execution Environments An e2e framework for creating, deploying and using isolated execution environments for agentic RL training, built using Gymnasium style simple APIs. Featured E…"
  },
  {
    "id": "技术-github python-https://github.com/soxoj/maigret",
    "feed_name": "github python",
    "category": "技术",
    "title": "soxoj/maigret",
    "link": "https://github.com/soxoj/maigret",
    "pub_date": "",
    "author": "",
    "description": "🕵️‍♂️ Collect a dossier on a person by username from 3000+ sites Maigret English · 简体中文 Maigret collects a dossier on a person by username only, checking for accounts on a huge number of sites and gathering all the avai…",
    "content": "🕵️‍♂️ Collect a dossier on a person by username from 3000+ sites Maigret English · 简体中文 Maigret collects a dossier on a person by username only , checking for accounts on a huge number of sites and gathering all the available information from web pages. No AP…"
  },
  {
    "id": "技术-github python-https://github.com/LMCache/LMCache",
    "feed_name": "github python",
    "category": "技术",
    "title": "LMCache/LMCache",
    "link": "https://github.com/LMCache/LMCache",
    "pub_date": "",
    "author": "",
    "description": "LMCache: Supercharge Your LLM with the Fastest KV Cache Layer A KV Cache Management Layer for Scalable LLM Inference Blog | Documentation | Join Slack | Community Meeting | Roadmap Updates [2026/05] 🔥 Agentic workload b…",
    "content": "LMCache: Supercharge Your LLM with the Fastest KV Cache Layer A KV Cache Management Layer for Scalable LLM Inference Blog | Documentation | Join Slack | Community Meeting | Roadmap Updates [2026/05] 🔥 Agentic workload benchmark on AMD MI300X ( blog ). [2026/0…"
  },
  {
    "id": "技术-github python-https://github.com/modelscope/FunASR",
    "feed_name": "github python",
    "category": "技术",
    "title": "modelscope/FunASR",
    "link": "https://github.com/modelscope/FunASR",
    "pub_date": "",
    "author": "",
    "description": "Industrial-grade speech recognition toolkit: 170x realtime, 50+ languages, speaker diarization, emotion detection, streaming, and OpenAI-compatible API. (简体中文|English|日本語|한국어) Industrial speech recognition. 170x fas…",
    "content": "Industrial-grade speech recognition toolkit: 170x realtime, 50+ languages, speaker diarization, emotion detection, streaming, and OpenAI-compatible API. ( 简体中文 |English| 日本語 | 한국어 ) Industrial speech recognition. 170x faster than Whisper. 50+ languages. S…"
  },
  {
    "id": "技术-github python-https://github.com/comet-ml/opik",
    "feed_name": "github python",
    "category": "技术",
    "title": "comet-ml/opik",
    "link": "https://github.com/comet-ml/opik",
    "pub_date": "",
    "author": "",
    "description": "Debug, evaluate, and monitor your LLM applications, RAG systems, and agentic workflows with comprehensive tracing, automated evaluations, and production-ready dashboards. English | 简体中文 | 日本語 | Português (Brasil) | 한국어 E…",
    "content": "Debug, evaluate, and monitor your LLM applications, RAG systems, and agentic workflows with comprehensive tracing, automated evaluations, and production-ready dashboards. English | 简体中文 | 日本語 | Português (Brasil) | 한국어 Español | Français | Deutsch | Русский | …"
  },
  {
    "id": "技术-github python-https://github.com/Open-LLM-VTuber/Open-LLM-VTuber",
    "feed_name": "github python",
    "category": "技术",
    "title": "Open-LLM-VTuber/Open-LLM-VTuber",
    "link": "https://github.com/Open-LLM-VTuber/Open-LLM-VTuber",
    "pub_date": "",
    "author": "",
    "description": "Talk to any LLM with hands-free voice interaction, voice interruption, and Live2D taking face running locally across platforms Open-LLM-VTuber 📢 v2.0 Development: We are focusing on Open-LLM-VTuber v2.0 — a complete rew…",
    "content": "Talk to any LLM with hands-free voice interaction, voice interruption, and Live2D taking face running locally across platforms Open-LLM-VTuber 📢 v2.0 Development : We are focusing on Open-LLM-VTuber v2.0 — a complete rewrite of the codebase. v2.0 is currently…"
  },
  {
    "id": "技术-github python-https://github.com/safishamsi/graphify",
    "feed_name": "github python",
    "category": "技术",
    "title": "safishamsi/graphify",
    "link": "https://github.com/safishamsi/graphify",
    "pub_date": "",
    "author": "",
    "description": "AI coding assistant skill (Claude Code, Codex, OpenCode, Cursor, Gemini CLI, and more). Turn any folder of code, SQL schemas, R scripts, shell scripts, docs, papers, images, or videos into a queryable knowledge graph. Ap…",
    "content": "AI coding assistant skill (Claude Code, Codex, OpenCode, Cursor, Gemini CLI, and more). Turn any folder of code, SQL schemas, R scripts, shell scripts, docs, papers, images, or videos into a queryable knowledge graph. App code + database schema + infrastructur…"
  },
  {
    "id": "技术-github python-https://github.com/Andyyyy64/whichllm",
    "feed_name": "github python",
    "category": "技术",
    "title": "Andyyyy64/whichllm",
    "link": "https://github.com/Andyyyy64/whichllm",
    "pub_date": "",
    "author": "",
    "description": "Find the local LLM that actually runs and performs best on your hardware. Ranked by real, recency-aware benchmarks, not parameter count. One command, run it instantly. whichllm Find the best local LLM that actually runs …",
    "content": "Find the local LLM that actually runs and performs best on your hardware. Ranked by real, recency-aware benchmarks, not parameter count. One command, run it instantly. whichllm Find the best local LLM that actually runs on your hardware. Auto-detects your GPU/…"
  },
  {
    "id": "技术-github python-https://github.com/PaddlePaddle/PaddleOCR",
    "feed_name": "github python",
    "category": "技术",
    "title": "PaddlePaddle/PaddleOCR",
    "link": "https://github.com/PaddlePaddle/PaddleOCR",
    "pub_date": "",
    "author": "",
    "description": "Turn any PDF or image document into structured data for your AI. A powerful, lightweight OCR toolkit that bridges the gap between images/PDFs and LLMs. Supports 100+ languages. Global Leading OCR Toolkit & Document AI En…",
    "content": "Turn any PDF or image document into structured data for your AI. A powerful, lightweight OCR toolkit that bridges the gap between images/PDFs and LLMs. Supports 100+ languages. Global Leading OCR Toolkit &amp; Document AI Engine English | 简体中文 | 繁體中文 | 日本語 | 한…"
  },
  {
    "id": "技术-github python-https://github.com/maziyarpanahi/openmed",
    "feed_name": "github python",
    "category": "技术",
    "title": "maziyarpanahi/openmed",
    "link": "https://github.com/maziyarpanahi/openmed",
    "pub_date": "",
    "author": "",
    "description": "Local-first healthcare AI: clinical NER & HIPAA PII de-identification that runs 100% on-device. 1,000+ medical models, 12 languages, Apple MLX + Python, no cloud, no patient data leaving your network. Apache-2.0 Local-fi…",
    "content": "Local-first healthcare AI: clinical NER & HIPAA PII de-identification that runs 100% on-device. 1,000+ medical models, 12 languages, Apple MLX + Python, no cloud, no patient data leaving your network. Apache-2.0 Local-first healthcare AI that never leaves the …"
  },
  {
    "id": "技术-github python-https://github.com/Sumanth077/Hands-On-AI-Engineering",
    "feed_name": "github python",
    "category": "技术",
    "title": "Sumanth077/Hands-On-AI-Engineering",
    "link": "https://github.com/Sumanth077/Hands-On-AI-Engineering",
    "pub_date": "",
    "author": "",
    "description": "A curated collection of practical AI projects implementing OCR systems, RAG, AI agents, and other AI use cases. 🚀 Hands-On AI Engineering A curated collection of practical, production-ready AI projects across multiple m…",
    "content": "A curated collection of practical AI projects implementing OCR systems, RAG, AI agents, and other AI use cases. 🚀 Hands-On AI Engineering A curated collection of practical, production-ready AI projects across multiple modalities, including language models, mu…"
  },
  {
    "id": "技术-github python-https://github.com/NVIDIA/physicsnemo",
    "feed_name": "github python",
    "category": "技术",
    "title": "NVIDIA/physicsnemo",
    "link": "https://github.com/NVIDIA/physicsnemo",
    "pub_date": "",
    "author": "",
    "description": "Open-source deep-learning framework for building, training, and fine-tuning deep learning models using state-of-the-art Physics-ML methods NVIDIA PhysicsNeMo 📝 NVIDIA PhysicsNeMo is undergoing an update to v2.0 - all th…",
    "content": "Open-source deep-learning framework for building, training, and fine-tuning deep learning models using state-of-the-art Physics-ML methods NVIDIA PhysicsNeMo 📝 NVIDIA PhysicsNeMo is undergoing an update to v2.0 - all the features, with easier installation and…"
  },
  {
    "id": "技术-github go-https://github.com/kenn-io/agentsview",
    "feed_name": "github go",
    "category": "技术",
    "title": "kenn-io/agentsview",
    "link": "https://github.com/kenn-io/agentsview",
    "pub_date": "",
    "author": "",
    "description": "Local-first session search, analytics, insights, and token use statistics for coding agents, supporting Claude Code, Codex, and more than 20 other agents. agentsview Browse, search, and track costs across all your AI cod…",
    "content": "Local-first session search, analytics, insights, and token use statistics for coding agents, supporting Claude Code, Codex, and more than 20 other agents. agentsview Browse, search, and track costs across all your AI coding agents. One binary, no accounts, eve…"
  },
  {
    "id": "技术-github go-https://github.com/masterking32/MasterDnsVPN",
    "feed_name": "github go",
    "category": "技术",
    "title": "masterking32/MasterDnsVPN",
    "link": "https://github.com/masterking32/MasterDnsVPN",
    "pub_date": "",
    "author": "",
    "description": "Advanced DNS tunneling VPN for censorship bypass, optimized beyond DNSTT and SlipStream with low-overhead ARQ, resolver load balancing, high packet-loss stability and speed. # MasterDnsVPN Project 🔐 | 🇮🇷 فارسی | 🇬🇧 …",
    "content": "Advanced DNS tunneling VPN for censorship bypass, optimized beyond DNSTT and SlipStream with low-overhead ARQ, resolver load balancing, high packet-loss stability and speed. # MasterDnsVPN Project 🔐 | 🇮🇷 فارسی | 🇬🇧 English | 🇷🇺 Русский | 🇨🇳 中文 | 🇪🇸 …"
  },
  {
    "id": "技术-github go-https://github.com/juicedata/juicefs",
    "feed_name": "github go",
    "category": "技术",
    "title": "juicedata/juicefs",
    "link": "https://github.com/juicedata/juicefs",
    "pub_date": "",
    "author": "",
    "description": "JuiceFS is a distributed POSIX file system built on top of Redis and S3. JuiceFS is a high-performance POSIX file system released under Apache License 2.0, particularly designed for the cloud-native environment. The data…",
    "content": "JuiceFS is a distributed POSIX file system built on top of Redis and S3. JuiceFS is a high-performance POSIX file system released under Apache License 2.0, particularly designed for the cloud-native environment. The data, stored via JuiceFS, will be persisted …"
  },
  {
    "id": "技术-github go-https://github.com/runatlantis/atlantis",
    "feed_name": "github go",
    "category": "技术",
    "title": "runatlantis/atlantis",
    "link": "https://github.com/runatlantis/atlantis",
    "pub_date": "",
    "author": "",
    "description": "Terraform Pull Request Automation Atlantis Terraform Pull Request Automation Resources What is Atlantis? What does it do? Why should you use it? Stargazers over time Resources How to get started: www.runatlantis.io/guide…",
    "content": "Terraform Pull Request Automation Atlantis Terraform Pull Request Automation Resources What is Atlantis? What does it do? Why should you use it? Stargazers over time Resources How to get started: www.runatlantis.io/guide Full documentation: www.runatlantis.io/…"
  },
  {
    "id": "技术-github go-https://github.com/zitadel/zitadel",
    "feed_name": "github go",
    "category": "技术",
    "title": "zitadel/zitadel",
    "link": "https://github.com/zitadel/zitadel",
    "pub_date": "",
    "author": "",
    "description": "ZITADEL - Identity infrastructure, simplified for you. The Identity Infrastructure for Developers ZITADEL is an open-source identity and access management platform built for teams that need more than basic auth. Whether …",
    "content": "ZITADEL - Identity infrastructure, simplified for you. The Identity Infrastructure for Developers ZITADEL is an open-source identity and access management platform built for teams that need more than basic auth. Whether you're securing a SaaS product, building…"
  },
  {
    "id": "技术-github go-https://github.com/hashicorp/terraform",
    "feed_name": "github go",
    "category": "技术",
    "title": "hashicorp/terraform",
    "link": "https://github.com/hashicorp/terraform",
    "pub_date": "",
    "author": "",
    "description": "Terraform enables you to safely and predictably create, change, and improve infrastructure. It is a source-available tool that codifies APIs into declarative configuration files that can be shared amongst team members, t…",
    "content": "Terraform enables you to safely and predictably create, change, and improve infrastructure. It is a source-available tool that codifies APIs into declarative configuration files that can be shared amongst team members, treated as code, edited, reviewed, and ve…"
  },
  {
    "id": "技术-github go-https://github.com/tulir/whatsmeow",
    "feed_name": "github go",
    "category": "技术",
    "title": "tulir/whatsmeow",
    "link": "https://github.com/tulir/whatsmeow",
    "pub_date": "",
    "author": "",
    "description": "Go library for the WhatsApp web multidevice API whatsmeow whatsmeow is a Go library for the WhatsApp web multidevice API. Discussion Matrix room: #whatsmeow:maunium.net For questions about the WhatsApp protocol (like how…",
    "content": "Go library for the WhatsApp web multidevice API whatsmeow whatsmeow is a Go library for the WhatsApp web multidevice API. Discussion Matrix room: #whatsmeow:maunium.net For questions about the WhatsApp protocol (like how to send a specific type of message), yo…"
  },
  {
    "id": "技术-github go-https://github.com/restic/restic",
    "feed_name": "github go",
    "category": "技术",
    "title": "restic/restic",
    "link": "https://github.com/restic/restic",
    "pub_date": "",
    "author": "",
    "description": "Fast, secure, efficient backup program Introduction restic is a backup program that is fast, efficient and secure. It supports the three major operating systems (Linux, macOS, Windows) and a few smaller ones (FreeBSD, Op…",
    "content": "Fast, secure, efficient backup program Introduction restic is a backup program that is fast, efficient and secure. It supports the three major operating systems (Linux, macOS, Windows) and a few smaller ones (FreeBSD, OpenBSD). For detailed usage and installat…"
  },
  {
    "id": "技术-github go-https://github.com/Wei-Shaw/sub2api",
    "feed_name": "github go",
    "category": "技术",
    "title": "Wei-Shaw/sub2api",
    "link": "https://github.com/Wei-Shaw/sub2api",
    "pub_date": "",
    "author": "",
    "description": "Sub2API is an open-source relay platform that unifies Claude, OpenAI, Gemini, and Antigravity subscriptions into a single endpoint. It supports account sharing and cost-sharing, with seamless native tool compatibility. S…",
    "content": "Sub2API is an open-source relay platform that unifies Claude, OpenAI, Gemini, and Antigravity subscriptions into a single endpoint. It supports account sharing and cost-sharing, with seamless native tool compatibility. Sub2API AI API Gateway Platform for Subsc…"
  },
  {
    "id": "技术-github go-https://github.com/navidrome/navidrome",
    "feed_name": "github go",
    "category": "技术",
    "title": "navidrome/navidrome",
    "link": "https://github.com/navidrome/navidrome",
    "pub_date": "",
    "author": "",
    "description": "🎧 Your Personal Streaming Service Navidrome Music Server Navidrome is an open source web-based music collection server and streamer. It gives you freedom to listen to your music collection from any browser or mobile dev…",
    "content": "🎧 Your Personal Streaming Service Navidrome Music Server &nbsp; Navidrome is an open source web-based music collection server and streamer. It gives you freedom to listen to your music collection from any browser or mobile device. It's like your personal Spot…"
  },
  {
    "id": "技术-github go-https://github.com/netbirdio/netbird",
    "feed_name": "github go",
    "category": "技术",
    "title": "netbirdio/netbird",
    "link": "https://github.com/netbirdio/netbird",
    "pub_date": "",
    "author": "",
    "description": "Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and granular access controls. Start using NetBird at netbird.io See Documentation Join our Slack channel or our Community forum 🚀 We are …",
    "content": "Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and granular access controls. Start using NetBird at netbird.io See Documentation Join our Slack channel or our Community forum 🚀 We are hiring! Join us at careers.netbird.io Ne…"
  },
  {
    "id": "技术-github go-https://github.com/Ed1s0nZ/CyberStrikeAI",
    "feed_name": "github go",
    "category": "技术",
    "title": "Ed1s0nZ/CyberStrikeAI",
    "link": "https://github.com/Ed1s0nZ/CyberStrikeAI",
    "pub_date": "",
    "author": "",
    "description": "CyberStrikeAI is an AI-native security testing platform built in Go. It integrates 100+ security tools, an intelligent orchestration engine, role-based testing with predefined security roles, a skills system with special…",
    "content": "CyberStrikeAI is an AI-native security testing platform built in Go. It integrates 100+ security tools, an intelligent orchestration engine, role-based testing with predefined security roles, a skills system with specialized testing skills, and comprehensive l…"
  },
  {
    "id": "技术-github go-https://github.com/maximhq/bifrost",
    "feed_name": "github go",
    "category": "技术",
    "title": "maximhq/bifrost",
    "link": "https://github.com/maximhq/bifrost",
    "pub_date": "",
    "author": "",
    "description": "Fastest enterprise AI gateway (50x faster than LiteLLM) with adaptive load balancer, cluster mode, guardrails, 1000+ models support & Bifrost AI Gateway The fastest way to build AI applications that never go down Bifrost…",
    "content": "Fastest enterprise AI gateway (50x faster than LiteLLM) with adaptive load balancer, cluster mode, guardrails, 1000+ models support & Bifrost AI Gateway The fastest way to build AI applications that never go down Bifrost is a high-performance AI gateway that u…"
  },
  {
    "id": "技术-github go-https://github.com/rclone/rclone",
    "feed_name": "github go",
    "category": "技术",
    "title": "rclone/rclone",
    "link": "https://github.com/rclone/rclone",
    "pub_date": "",
    "author": "",
    "description": "\"rsync for cloud storage\" - Google Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Wasabi, Google Cloud Storage, Azure Blob, Azure Files, Yandex Files Website | Documentation | Download | Contributing | Change…",
    "content": "\"rsync for cloud storage\" - Google Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Wasabi, Google Cloud Storage, Azure Blob, Azure Files, Yandex Files Website | Documentation | Download | Contributing | Changelog | Installation | Forum Rclone Rclone…"
  },
  {
    "id": "技术-github go-https://github.com/bluenviron/mediamtx",
    "feed_name": "github go",
    "category": "技术",
    "title": "bluenviron/mediamtx",
    "link": "https://github.com/bluenviron/mediamtx",
    "pub_date": "",
    "author": "",
    "description": "Ready-to-use Media-over-QUIC / SRT / WebRTC / RTSP / RTMP / LL-HLS / MPEG-TS / RTP live media server and media proxy that allows to read, publish, proxy, record and playback real-time video and audio streams. MediaMTX is…",
    "content": "Ready-to-use Media-over-QUIC / SRT / WebRTC / RTSP / RTMP / LL-HLS / MPEG-TS / RTP live media server and media proxy that allows to read, publish, proxy, record and playback real-time video and audio streams. MediaMTX is a ready-to-use and zero-dependency live…"
  },
  {
    "id": "技术-github go-https://github.com/gruntwork-io/terragrunt",
    "feed_name": "github go",
    "category": "技术",
    "title": "gruntwork-io/terragrunt",
    "link": "https://github.com/gruntwork-io/terragrunt",
    "pub_date": "",
    "author": "",
    "description": "Terragrunt is a flexible orchestration tool that allows Infrastructure as Code written in OpenTofu/Terraform to scale. Terragrunt 🎉 Terragrunt v1.0 is here! Read the announcement to learn more. Terragrunt is a flexible …",
    "content": "Terragrunt is a flexible orchestration tool that allows Infrastructure as Code written in OpenTofu/Terraform to scale. Terragrunt 🎉 Terragrunt v1.0 is here! Read the announcement to learn more. Terragrunt is a flexible orchestration tool that allows Infrastru…"
  },
  {
    "id": "技术-github go-https://github.com/docker/docker-agent",
    "feed_name": "github go",
    "category": "技术",
    "title": "docker/docker-agent",
    "link": "https://github.com/docker/docker-agent",
    "pub_date": "",
    "author": "",
    "description": "AI Agent Builder and Runtime by Docker Engineering 🤖 Docker Agent 🤖 Build, run, and share AI agents with a declarative YAML config, rich tool ecosystem, and multi-agent orchestration. What is Docker Agent? docker-agent…",
    "content": "AI Agent Builder and Runtime by Docker Engineering 🤖 Docker Agent 🤖 Build, run, and share AI agents with a declarative YAML config, rich tool ecosystem, and multi-agent orchestration. What is Docker Agent? docker-agent lets you create and run intelligent AI …"
  },
  {
    "id": "技术-github go-https://github.com/temporalio/temporal",
    "feed_name": "github go",
    "category": "技术",
    "title": "temporalio/temporal",
    "link": "https://github.com/temporalio/temporal",
    "pub_date": "",
    "author": "",
    "description": "Temporal service Temporal—durable execution platform Introduction • Getting Started • Contributing • Temporal Docs • Temporal 101 Introduction Temporal is a durable execution platform that enables developers to build sca…",
    "content": "Temporal service Temporal—durable execution platform Introduction &nbsp;&nbsp;•&nbsp;&nbsp; Getting Started &nbsp;&nbsp;•&nbsp;&nbsp; Contributing &nbsp;&nbsp;•&nbsp;&nbsp; Temporal Docs &nbsp;&nbsp;•&nbsp;&nbsp; Temporal 101 Introduction Temporal is a durable…"
  },
  {
    "id": "技术-github go-https://github.com/traefik/traefik",
    "feed_name": "github go",
    "category": "技术",
    "title": "traefik/traefik",
    "link": "https://github.com/traefik/traefik",
    "pub_date": "",
    "author": "",
    "description": "The Cloud Native Application Proxy Traefik (pronounced traffic) is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy. Traefik integrates with your existing infrastructure components (D…",
    "content": "The Cloud Native Application Proxy Traefik (pronounced traffic ) is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy. Traefik integrates with your existing infrastructure components ( Docker , Swarm mode , Kubernetes , Cons…"
  },
  {
    "id": "技术-github go-https://github.com/ethereum/go-ethereum",
    "feed_name": "github go",
    "category": "技术",
    "title": "ethereum/go-ethereum",
    "link": "https://github.com/ethereum/go-ethereum",
    "pub_date": "",
    "author": "",
    "description": "Go implementation of the Ethereum protocol Go Ethereum Golang execution layer implementation of the Ethereum protocol. Automated builds are available for stable releases and the unstable master branch. Binary archives ar…",
    "content": "Go implementation of the Ethereum protocol Go Ethereum Golang execution layer implementation of the Ethereum protocol. Automated builds are available for stable releases and the unstable master branch. Binary archives are published at https://geth.ethereum.org…"
  },
  {
    "id": "技术-github go-https://github.com/seaweedfs/seaweedfs",
    "feed_name": "github go",
    "category": "技术",
    "title": "seaweedfs/seaweedfs",
    "link": "https://github.com/seaweedfs/seaweedfs",
    "pub_date": "",
    "author": "",
    "description": "SeaweedFS is a distributed storage system for object storage (S3), file systems, and Iceberg tables, designed to handle billions of files with O(1) disk access and effortless horizontal scaling. SeaweedFS Sponsor Seaweed…",
    "content": "SeaweedFS is a distributed storage system for object storage (S3), file systems, and Iceberg tables, designed to handle billions of files with O(1) disk access and effortless horizontal scaling. SeaweedFS Sponsor SeaweedFS via Patreon SeaweedFS is an independe…"
  },
  {
    "id": "技术-github rust-https://github.com/biomejs/biome",
    "feed_name": "github rust",
    "category": "技术",
    "title": "biomejs/biome",
    "link": "https://github.com/biomejs/biome",
    "pub_date": "",
    "author": "",
    "description": "A toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter, usable via CLI and LSP. हिन्दी | English | Español | Français | 繁體中文 | 简体中文 | 日本語 | Polski | Português d…",
    "content": "A toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter, usable via CLI and LSP. हिन्दी | English | Español | Français | 繁體中文 | 简体中文 | 日本語 | Polski | Português do Brasil | 한국어 | Русский | Українська Bi…"
  },
  {
    "id": "技术-github rust-https://github.com/aaif-goose/goose",
    "feed_name": "github rust",
    "category": "技术",
    "title": "aaif-goose/goose",
    "link": "https://github.com/aaif-goose/goose",
    "pub_date": "",
    "author": "",
    "description": "an open source, extensible AI agent that goes beyond code suggestions - install, execute, edit, and test with any LLM 🦆 goose has moved! This project has moved from block/goose to the Agentic AI Foundation (AAIF) at the…",
    "content": "an open source, extensible AI agent that goes beyond code suggestions - install, execute, edit, and test with any LLM 🦆 goose has moved! This project has moved from block/goose to the Agentic AI Foundation (AAIF) at the Linux Foundation. Some links and refere…"
  },
  {
    "id": "技术-github rust-https://github.com/rolldown/rolldown",
    "feed_name": "github rust",
    "category": "技术",
    "title": "rolldown/rolldown",
    "link": "https://github.com/rolldown/rolldown",
    "pub_date": "",
    "author": "",
    "description": "Fast Rust bundler for JavaScript/TypeScript with Rollup-compatible API. Rolldown Rolldown is a JavaScript/TypeScript bundler written in Rust intended to serve as the future bundler used in Vite. It provides Rollup-compat…",
    "content": "Fast Rust bundler for JavaScript/TypeScript with Rollup-compatible API. Rolldown Rolldown is a JavaScript/TypeScript bundler written in Rust intended to serve as the future bundler used in Vite . It provides Rollup-compatible APIs and plugin interface, but wil…"
  },
  {
    "id": "技术-github rust-https://github.com/cube-js/cube",
    "feed_name": "github rust",
    "category": "技术",
    "title": "cube-js/cube",
    "link": "https://github.com/cube-js/cube",
    "pub_date": "",
    "author": "",
    "description": "📊 Cube Core is open-source semantic layer for AI, BI and embedded analytics Website • Docs • Examples • Blog • Slack • X Cube Core is the open-source semantic layer. Define metrics, dimensions, joins, and access rules o…",
    "content": "📊 Cube Core is open-source semantic layer for AI, BI and embedded analytics Website • Docs • Examples • Blog • Slack • X Cube Core is the open-source semantic layer. Define metrics, dimensions, joins, and access rules once in code, then expose them through SQ…"
  },
  {
    "id": "技术-github rust-https://github.com/dmtrKovalenko/fff",
    "feed_name": "github rust",
    "category": "技术",
    "title": "dmtrKovalenko/fff",
    "link": "https://github.com/dmtrKovalenko/fff",
    "pub_date": "",
    "author": "",
    "description": "The fastest and the most accurate file search toolkit for AI agents, Neovim, Rust, C, and NodeJS A file search toolkit for humans and AI agents. Really fast. Typo-resistant path and content search, frecency-ranked file a…",
    "content": "The fastest and the most accurate file search toolkit for AI agents, Neovim, Rust, C, and NodeJS A file search toolkit for humans and AI agents. Really fast. Typo-resistant path and content search, frecency-ranked file access, a background watcher, and a light…"
  },
  {
    "id": "技术-github rust-https://github.com/swc-project/swc",
    "feed_name": "github rust",
    "category": "技术",
    "title": "swc-project/swc",
    "link": "https://github.com/swc-project/swc",
    "pub_date": "",
    "author": "",
    "description": "Rust-based platform for the Web Make the web (development) faster. SWC (stands for Speedy Web Compiler) is a super-fast TypeScript / JavaScript compiler written in Rust. It's a library for Rust and JavaScript at the same…",
    "content": "Rust-based platform for the Web Make the web (development) faster. SWC (stands for Speedy Web Compiler ) is a super-fast TypeScript / JavaScript compiler written in Rust. It's a library for Rust and JavaScript at the same time. If you are using SWC from Rust, …"
  },
  {
    "id": "技术-github rust-https://github.com/farion1231/cc-switch",
    "feed_name": "github rust",
    "category": "技术",
    "title": "farion1231/cc-switch",
    "link": "https://github.com/farion1231/cc-switch",
    "pub_date": "",
    "author": "",
    "description": "A cross-platform desktop All-in-One assistant for Claude Code, Codex, OpenCode, OpenClaw, Gemini CLI & Hermes Agent. Only official website: ccswitch.io CC Switch The All-in-One Manager for Claude Code, Claude Desktop, Co…",
    "content": "A cross-platform desktop All-in-One assistant for Claude Code, Codex, OpenCode, OpenClaw, Gemini CLI & Hermes Agent. Only official website: ccswitch.io CC Switch The All-in-One Manager for Claude Code, Claude Desktop, Codex, Gemini CLI, OpenCode, OpenClaw &amp…"
  },
  {
    "id": "技术-github rust-https://github.com/uutils/coreutils",
    "feed_name": "github rust",
    "category": "技术",
    "title": "uutils/coreutils",
    "link": "https://github.com/uutils/coreutils",
    "pub_date": "",
    "author": "",
    "description": "Cross-platform Rust rewrite of the GNU coreutils uutils coreutils uutils coreutils is a cross-platform reimplementation of the GNU coreutils in Rust. While all programs have been implemented, some options might be missin…",
    "content": "Cross-platform Rust rewrite of the GNU coreutils uutils coreutils uutils coreutils is a cross-platform reimplementation of the GNU coreutils in Rust . While all programs have been implemented, some options might be missing or different behavior might be experi…"
  },
  {
    "id": "技术-github rust-https://github.com/vortex-data/vortex",
    "feed_name": "github rust",
    "category": "技术",
    "title": "vortex-data/vortex",
    "link": "https://github.com/vortex-data/vortex",
    "pub_date": "",
    "author": "",
    "description": "An extensible, state-of-the-art framework for columnar compression, and the fastest FOSS columnar file format. Formerly at @spiraldb, now an Incubation Stage project at LFAI&Data, part of the Linux Foundation. 🌪️ Vortex…",
    "content": "An extensible, state-of-the-art framework for columnar compression, and the fastest FOSS columnar file format. Formerly at @spiraldb, now an Incubation Stage project at LFAI&Data, part of the Linux Foundation. 🌪️ Vortex Join the community on Slack! | Document…"
  },
  {
    "id": "技术-github rust-https://github.com/pydantic/monty",
    "feed_name": "github rust",
    "category": "技术",
    "title": "pydantic/monty",
    "link": "https://github.com/pydantic/monty",
    "pub_date": "",
    "author": "",
    "description": "A minimal, secure Python interpreter written in Rust for use by AI Monty A minimal, secure Python interpreter written in Rust for use by AI. Experimental - This project is still in development, and not ready for the prim…",
    "content": "A minimal, secure Python interpreter written in Rust for use by AI Monty A minimal, secure Python interpreter written in Rust for use by AI. Experimental - This project is still in development, and not ready for the prime time. A minimal, secure Python interpr…"
  },
  {
    "id": "技术-github rust-https://github.com/GyulyVGC/sniffnet",
    "feed_name": "github rust",
    "category": "技术",
    "title": "GyulyVGC/sniffnet",
    "link": "https://github.com/GyulyVGC/sniffnet",
    "pub_date": "",
    "author": "",
    "description": "Comfortably monitor your Internet traffic 🕵️‍♂️ Application to comfortably monitor your Internet traffic. Cross-platform. Intuitive. Reliable. Translated in: 🇨🇳 🇩🇪 🇫🇷 🇷🇺 🇵🇹 🇪🇦 🇮🇹 🇵🇱 + 16 more languages S…",
    "content": "Comfortably monitor your Internet traffic 🕵️‍♂️ Application to comfortably monitor your Internet traffic. Cross-platform. Intuitive. Reliable. Translated in: 🇨🇳 🇩🇪 🇫🇷 🇷🇺 🇵🇹 🇪🇦 🇮🇹 🇵🇱 +&nbsp;16&nbsp;more&nbsp;languages Support Sniffnet's develop…"
  },
  {
    "id": "技术-github rust-https://github.com/zhom/donutbrowser",
    "feed_name": "github rust",
    "category": "技术",
    "title": "zhom/donutbrowser",
    "link": "https://github.com/zhom/donutbrowser",
    "pub_date": "",
    "author": "",
    "description": "Simple Yet Powerful Anti-Detect Browser 🍩 Donut Browser Open Source Anti-Detect Browser donutbrowser.com Features Unlimited browser profiles — each fully isolated with its own fingerprint, cookies, extensions, and data …",
    "content": "Simple Yet Powerful Anti-Detect Browser 🍩 Donut Browser Open Source Anti-Detect Browser donutbrowser.com Features Unlimited browser profiles — each fully isolated with its own fingerprint, cookies, extensions, and data Anti-detect Chromium engine — powered by…"
  },
  {
    "id": "技术-github rust-https://github.com/astral-sh/ruff",
    "feed_name": "github rust",
    "category": "技术",
    "title": "astral-sh/ruff",
    "link": "https://github.com/astral-sh/ruff",
    "pub_date": "",
    "author": "",
    "description": "An extremely fast Python linter and code formatter, written in Rust. Ruff Docs | Playground An extremely fast Python linter and code formatter, written in Rust. Linting the CPython codebase from scratch. ⚡️ 10-100x faste…",
    "content": "An extremely fast Python linter and code formatter, written in Rust. Ruff Docs | Playground An extremely fast Python linter and code formatter, written in Rust. Linting the CPython codebase from scratch. ⚡️ 10-100x faster than existing linters (like Flake8) an…"
  },
  {
    "id": "技术-github rust-https://github.com/web-infra-dev/rspack",
    "feed_name": "github rust",
    "category": "技术",
    "title": "web-infra-dev/rspack",
    "link": "https://github.com/web-infra-dev/rspack",
    "pub_date": "",
    "author": "",
    "description": "Fast Rust-based bundler for the web with a modernized webpack API 🦀 Rspack English | 简体中文 Rspack is a fast Rust-based bundler for the web. It modernizes the webpack API to enable seamless replacement of webpack while de…",
    "content": "Fast Rust-based bundler for the web with a modernized webpack API 🦀 Rspack English | 简体中文 Rspack is a fast Rust-based bundler for the web. It modernizes the webpack API to enable seamless replacement of webpack while delivering lightning-fast build speeds. ✨ …"
  },
  {
    "id": "技术-github rust-https://github.com/servo/servo",
    "feed_name": "github rust",
    "category": "技术",
    "title": "servo/servo",
    "link": "https://github.com/servo/servo",
    "pub_date": "",
    "author": "",
    "description": "Servo aims to empower developers with a lightweight, high-performance alternative for embedding web technologies in applications. The Servo Parallel Browser Engine Project Servo is a prototype web browser engine written …",
    "content": "Servo aims to empower developers with a lightweight, high-performance alternative for embedding web technologies in applications. The Servo Parallel Browser Engine Project Servo is a prototype web browser engine written in the Rust language. It is currently de…"
  },
  {
    "id": "技术-github rust-https://github.com/tensorzero/tensorzero",
    "feed_name": "github rust",
    "category": "技术",
    "title": "tensorzero/tensorzero",
    "link": "https://github.com/tensorzero/tensorzero",
    "pub_date": "",
    "author": "",
    "description": "TensorZero is an open-source LLMOps platform that unifies an LLM gateway, observability, evaluation, optimization, and experimentation. TensorZero TensorZero is an open-source LLMOps platform that unifies: Gateway: acces…",
    "content": "TensorZero is an open-source LLMOps platform that unifies an LLM gateway, observability, evaluation, optimization, and experimentation. TensorZero TensorZero is an open-source LLMOps platform that unifies: Gateway: access every LLM provider through a unified A…"
  },
  {
    "id": "技术-github rust-https://github.com/slint-ui/slint",
    "feed_name": "github rust",
    "category": "技术",
    "title": "slint-ui/slint",
    "link": "https://github.com/slint-ui/slint",
    "pub_date": "",
    "author": "",
    "description": "Slint is an open-source declarative GUI toolkit to build native user interfaces for Rust, C++, JavaScript, or Python apps. Slint is an open-source declarative GUI toolkit for building native user interfaces for embedded …",
    "content": "Slint is an open-source declarative GUI toolkit to build native user interfaces for Rust, C++, JavaScript, or Python apps. Slint is an open-source declarative GUI toolkit for building native user interfaces for embedded systems, desktops, and mobile platforms.…"
  },
  {
    "id": "技术-github rust-https://github.com/iced-rs/iced",
    "feed_name": "github rust",
    "category": "技术",
    "title": "iced-rs/iced",
    "link": "https://github.com/iced-rs/iced",
    "pub_date": "",
    "author": "",
    "description": "A cross-platform GUI library for Rust, inspired by Elm Iced A cross-platform GUI library for Rust focused on simplicity and type-safety. Inspired by Elm. Features Simple, easy-to-use, batteries-included API Type-safe, re…",
    "content": "A cross-platform GUI library for Rust, inspired by Elm Iced A cross-platform GUI library for Rust focused on simplicity and type-safety. Inspired by Elm . Features Simple, easy-to-use, batteries-included API Type-safe, reactive programming model Cross-platform…"
  },
  {
    "id": "技术-github rust-https://github.com/agentgateway/agentgateway",
    "feed_name": "github rust",
    "category": "技术",
    "title": "agentgateway/agentgateway",
    "link": "https://github.com/agentgateway/agentgateway",
    "pub_date": "",
    "author": "",
    "description": "Next Generation Agentic Proxy for AI Agents and MCP servers first complete connectivity solution for Agentic AI. Agentgateway is an open source proxy built on AI-native protocols (MCP & A2A) that provides drop-in securit…",
    "content": "Next Generation Agentic Proxy for AI Agents and MCP servers The first complete connectivity solution for Agentic AI. Agentgateway is an open source proxy built on AI-native protocols ( MCP &amp; A2A ) that provides drop-in security, observability, and governan…"
  },
  {
    "id": "技术-github javascript-https://github.com/openai/plugins",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "openai/plugins",
    "link": "https://github.com/openai/plugins",
    "pub_date": "",
    "author": "",
    "description": "OpenAI Plugins Plugins This repository contains a curated collection of Codex plugin examples. Each plugin lives under plugins/ / with a required .codex-plugin/plugin.json manifest and optional companion surfaces such as…",
    "content": "OpenAI Plugins Plugins This repository contains a curated collection of Codex plugin examples. Each plugin lives under plugins/&lt;name&gt;/ with a required .codex-plugin/plugin.json manifest and optional companion surfaces such as skills/ , .app.json , .mcp.j…"
  },
  {
    "id": "技术-github javascript-https://github.com/asgeirtj/system_prompts_leaks",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "asgeirtj/system_prompts_leaks",
    "link": "https://github.com/asgeirtj/system_prompts_leaks",
    "pub_date": "",
    "author": "",
    "description": "Extracted system prompts from Anthropic - Claude Fable 5, Opus 4.8, Claude Code, Claude Design. OpenAI - ChatGPT 5.5 Thinking, GPT 5.5 Instant, Codex. Google - Gemini 3.5 Flash, 3.1 Pro, Antigravity. xAI - Grok, Cursor, …",
    "content": "Extracted system prompts from Anthropic - Claude Fable 5, Opus 4.8, Claude Code, Claude Design. OpenAI - ChatGPT 5.5 Thinking, GPT 5.5 Instant, Codex. Google - Gemini 3.5 Flash, 3.1 Pro, Antigravity. xAI - Grok, Cursor, Copilot, VS Code, Perplexity, and more. …"
  },
  {
    "id": "技术-github javascript-https://github.com/santifer/career-ops",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "santifer/career-ops",
    "link": "https://github.com/santifer/career-ops",
    "pub_date": "",
    "author": "",
    "description": "AI-powered job search system built on Claude Code. 14 skill modes, Go dashboard, PDF generation, batch processing. Career-Ops English | Español | Français | Português (Brasil) | 한국어 | 日本語 | 简体中文 | 繁體中文 | Українська | Рус…",
    "content": "AI-powered job search system built on Claude Code. 14 skill modes, Go dashboard, PDF generation, batch processing. Career-Ops English | Español | Français | Português (Brasil) | 한국어 | 日本語 | 简体中文 | 繁體中文 | Українська | Русский | Polski | العربية I spent months a…"
  },
  {
    "id": "技术-github javascript-https://github.com/prettier/prettier",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "prettier/prettier",
    "link": "https://github.com/prettier/prettier",
    "pub_date": "",
    "author": "",
    "description": "Prettier is an opinionated code formatter. Opinionated Code Formatter JavaScript · TypeScript · Flow · JSX · JSON CSS · SCSS · Less HTML · Vue · Angular GraphQL · Markdown · YAML Your favorite language? Intro Prettier is…",
    "content": "Prettier is an opinionated code formatter. Opinionated Code Formatter JavaScript · TypeScript · Flow · JSX · JSON CSS · SCSS · Less HTML · Vue · Angular GraphQL · Markdown · YAML Your favorite language? Intro Prettier is an opinionated code formatter. It enfor…"
  },
  {
    "id": "技术-github javascript-https://github.com/zen-browser/desktop",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "zen-browser/desktop",
    "link": "https://github.com/zen-browser/desktop",
    "pub_date": "",
    "author": "",
    "description": "Welcome to a calmer internet Zen Browser Zen is a firefox-based browser with the aim of pushing your productivity to a new level! Download • Website • Documentation • Release Notes Firefox Versions Release - Is currently…",
    "content": "Welcome to a calmer internet Zen Browser Zen is a firefox-based browser with the aim of pushing your productivity to a new level! Download • Website • Documentation • Release Notes Firefox Versions Release - Is currently built using Firefox version 151.0.4 ! \ud83d…"
  },
  {
    "id": "技术-github javascript-https://github.com/fastify/fastify",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "fastify/fastify",
    "link": "https://github.com/fastify/fastify",
    "pub_date": "",
    "author": "",
    "description": "Fast and low overhead web framework, for Node.js An efficient server implies a lower cost of the infrastructure, better responsiveness under load, and happy users. How can you efficiently handle the resources of your ser…",
    "content": "Fast and low overhead web framework, for Node.js An efficient server implies a lower cost of the infrastructure, better responsiveness under load, and happy users. How can you efficiently handle the resources of your server, knowing that you are serving the hi…"
  },
  {
    "id": "技术-github javascript-https://github.com/webpack/webpack",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "webpack/webpack",
    "link": "https://github.com/webpack/webpack",
    "pub_date": "",
    "author": "",
    "description": "A bundler for javascript and friends. Packs many modules into a few bundled assets. Code Splitting allows for loading parts of the application on demand. Through \"loaders\", modules can be CommonJs, AMD, ES6 modules, CSS,…",
    "content": "A bundler for javascript and friends. Packs many modules into a few bundled assets. Code Splitting allows for loading parts of the application on demand. Through \"loaders\", modules can be CommonJs, AMD, ES6 modules, CSS, Images, JSON, Coffeescript, LESS, ... a…"
  },
  {
    "id": "技术-github javascript-https://github.com/pbakaus/impeccable",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "pbakaus/impeccable",
    "link": "https://github.com/pbakaus/impeccable",
    "pub_date": "",
    "author": "",
    "description": "The design language that makes your AI harness better at design. Impeccable Design guidance for AI coding agents. 1 skill, 23 commands, live browser iteration, and 41 deterministic detector rules for AI-generated fronten…",
    "content": "The design language that makes your AI harness better at design. Impeccable Design guidance for AI coding agents. 1 skill, 23 commands, live browser iteration, and 41 deterministic detector rules for AI-generated frontend design. Quick start: From your project…"
  },
  {
    "id": "技术-github javascript-https://github.com/expressjs/express",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "expressjs/express",
    "link": "https://github.com/expressjs/express",
    "pub_date": "",
    "author": "",
    "description": "Fast, unopinionated, minimalist web framework for node. Fast, unopinionated, minimalist web framework for Node.js. This project has a Code of Conduct. Table of contents Table of contents Installation Features Docs & Comm…",
    "content": "Fast, unopinionated, minimalist web framework for node. Fast, unopinionated, minimalist web framework for Node.js . This project has a Code of Conduct . Table of contents Table of contents Installation Features Docs &amp; Community Quick Start Philosophy Examp…"
  },
  {
    "id": "技术-github javascript-https://github.com/blackmatrix7/ios_rule_script",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "blackmatrix7/ios_rule_script",
    "link": "https://github.com/blackmatrix7/ios_rule_script",
    "pub_date": "",
    "author": "",
    "description": "分流规则、重写写规则及脚本。 Rules And Scripts 前言 各平台的分流规则、复写规则及自动化脚本。 特别声明 本项目内所有资源文件，禁止任何公众号、自媒体进行任何形式的转载、发布。 编写本项目主要目的为学习和研究ES6，无法保证项目内容的合法性、准确性、完整性和有效性。 本项目涉及的数据由使用的个人或组织自行填写，本项目不对数据内容负责，包括但不限于数据的真实性、准确性、合法性。使用本项目所造成的一切后果，与本项目的所有贡…",
    "content": "分流规则、重写写规则及脚本。 Rules And Scripts 前言 各平台的分流规则、复写规则及自动化脚本。 特别声明 本项目内所有资源文件，禁止任何公众号、自媒体进行任何形式的转载、发布。 编写本项目主要目的为学习和研究ES6，无法保证项目内容的合法性、准确性、完整性和有效性。 本项目涉及的数据由使用的个人或组织自行填写，本项目不对数据内容负责，包括但不限于数据的真实性、准确性、合法性。使用本项目所造成的一切后果，与本项目的所有贡献者无关，由使用的个人或组织完全承担。 本项目中涉及的第三方硬件、软件等，与本项…"
  },
  {
    "id": "技术-github javascript-https://github.com/NaiboWang/EasySpider",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "NaiboWang/EasySpider",
    "link": "https://github.com/NaiboWang/EasySpider",
    "pub_date": "",
    "author": "",
    "description": "A visual no-code/code-free web crawler/spider易采集：一个可视化浏览器自动化测试/数据采集/网页爬虫软件，可以无代码图形化的设计和执行爬虫任务。别名：ServiceWrapper面向Web应用的智能化服务封装系统。 易采集/EasySpider: Visual Code-Free Web Crawler 一个完全免费（包括商业使用和二次开发）的可视化浏览器自动化测试/数据采集/爬虫软件，可以使…",
    "content": "A visual no-code/code-free web crawler/spider易采集：一个可视化浏览器自动化测试/数据采集/网页爬虫软件，可以无代码图形化的设计和执行爬虫任务。别名：ServiceWrapper面向Web应用的智能化服务封装系统。 易采集/EasySpider: Visual Code-Free Web Crawler 一个 完全免费 （ 包括商业使用和二次开发 ）的可视化浏览器自动化测试/数据采集/爬虫软件，可以使用图形化界面，无代码可视化的设计和执行任务。只需要在网页上选择自己想要操…"
  },
  {
    "id": "技术-github javascript-https://github.com/eslint/eslint",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "eslint/eslint",
    "link": "https://github.com/eslint/eslint",
    "pub_date": "",
    "author": "",
    "description": "Find and fix problems in your JavaScript code. ESLint Website | Configure ESLint | Rules | Contribute to ESLint | Report Bugs | Code of Conduct | X | Discord | Mastodon | Bluesky ESLint is a tool for identifying and repo…",
    "content": "Find and fix problems in your JavaScript code. ESLint Website | Configure ESLint | Rules | Contribute to ESLint | Report Bugs | Code of Conduct | X | Discord | Mastodon | Bluesky ESLint is a tool for identifying and reporting on patterns found in ECMAScript/Ja…"
  },
  {
    "id": "技术-github javascript-https://github.com/npm/cli",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "npm/cli",
    "link": "https://github.com/npm/cli",
    "pub_date": "",
    "author": "",
    "description": "the package manager for JavaScript npm - a JavaScript package manager Requirements You should be running a currently supported version of Node.js to run npm. For a list of which versions of Node.js are currently supporte…",
    "content": "the package manager for JavaScript npm - a JavaScript package manager Requirements You should be running a currently supported version of Node.js to run npm . For a list of which versions of Node.js are currently supported, please see the Node.js releases page…"
  },
  {
    "id": "技术-github javascript-https://github.com/eyaltoledano/claude-task-master",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "eyaltoledano/claude-task-master",
    "link": "https://github.com/eyaltoledano/claude-task-master",
    "pub_date": "",
    "author": "",
    "description": "An AI-powered task-management system you can drop into Cursor, Lovable, Windsurf, Roo, and others. Taskmaster: A task management system for AI-driven development, designed to work seamlessly with any AI chat. | Docs By @…",
    "content": "An AI-powered task-management system you can drop into Cursor, Lovable, Windsurf, Roo, and others. Taskmaster : A task management system for AI-driven development, designed to work seamlessly with any AI chat. | Docs By @eyaltoledano &amp; @RalphEcom A task ma…"
  },
  {
    "id": "技术-github javascript-https://github.com/rabbitmq/rabbitmq-server",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "rabbitmq/rabbitmq-server",
    "link": "https://github.com/rabbitmq/rabbitmq-server",
    "pub_date": "",
    "author": "",
    "description": "Open source RabbitMQ: core server and tier 1 (built-in) plugins RabbitMQ Server RabbitMQ is a feature rich, multi-protocol messaging and streaming broker. It supports: AMQP 1.0 AMQP 0-9-1 RabbitMQ Stream Protocol MQTT 3.…",
    "content": "Open source RabbitMQ: core server and tier 1 (built-in) plugins RabbitMQ Server RabbitMQ is a feature rich , multi-protocol messaging and streaming broker. It supports: AMQP 1.0 AMQP 0-9-1 RabbitMQ Stream Protocol MQTT 3.1, 3.1.1, and 5.0 STOMP 1.0 through 1.2…"
  },
  {
    "id": "技术-github lua-https://github.com/Kong/kong",
    "feed_name": "github lua",
    "category": "技术",
    "title": "Kong/kong",
    "link": "https://github.com/Kong/kong",
    "pub_date": "",
    "author": "",
    "description": "🦍 The API and AI Gateway Kong or Kong Gateway is a cloud-native, platform-agnostic, scalable API 𖧹 LLM 𖧹 MCP Gateway distinguished for its high performance and extensibility via plugins. It also provides advanced AI t…",
    "content": "🦍 The API and AI Gateway Kong or Kong Gateway is a cloud-native, platform-agnostic, scalable API 𖧹 LLM 𖧹 MCP Gateway distinguished for its high performance and extensibility via plugins. It also provides advanced AI traffic capabilities with multi-LLM suppo…"
  },
  {
    "id": "技术-github lua-https://github.com/apache/apisix",
    "feed_name": "github lua",
    "category": "技术",
    "title": "apache/apisix",
    "link": "https://github.com/apache/apisix",
    "pub_date": "",
    "author": "",
    "description": "The Cloud-Native API Gateway and AI Gateway Apache APISIX API Gateway ｜ AI Gateway Apache APISIX is a dynamic, real-time, high-performance API Gateway. APISIX API Gateway provides rich traffic management features such as…",
    "content": "The Cloud-Native API Gateway and AI Gateway Apache APISIX API Gateway ｜ AI Gateway Apache APISIX is a dynamic, real-time, high-performance API Gateway. APISIX API Gateway provides rich traffic management features such as load balancing, dynamic upstream, canar…"
  },
  {
    "id": "技术-github lua-https://github.com/amzxyz/rime-wanxiang",
    "feed_name": "github lua",
    "category": "技术",
    "title": "amzxyz/rime-wanxiang",
    "link": "https://github.com/amzxyz/rime-wanxiang",
    "pub_date": "",
    "author": "",
    "description": "「万象拼音」：把算法留在幕后，把纯粹还给指尖，用更现代的数据，接管你的候选。Q群：11033572 / 11631066 🌳 万象拼音 重塑 Rime 生态，带来极致的输入体验。 🌌 万象拼音——基于深度优化的词库和语法模型 💎 核心基石： 万象词库 经 AI 与海量语料深度优化(目前已进入手动维护期)，是一款专为“语句流”“类大厂”打造的全方案立体词库。它将带调拼音标注、词组构成与精准词频作为体验基石，以日常与专业词汇为主体，结…",
    "content": "「万象拼音」：把算法留在幕后，把纯粹还给指尖，用更现代的数据，接管你的候选。Q群：11033572 / 11631066 🌳 万象拼音 重塑 Rime 生态，带来极致的输入体验。 🌌 万象拼音——基于深度优化的词库和语法模型 💎 核心基石： 万象词库 经 AI 与海量语料深度优化(目前已进入手动维护期)，是一款专为“语句流”“类大厂”打造的全方案立体词库。它将 带调拼音标注、词组构成与精准词频 作为体验基石，以日常与专业词汇为主体，结合语法模型，为您带来精准、流畅的输入体验。 开放生态 ：支持高度自定义，鼓励…"
  },
  {
    "id": "技术-github lua-https://github.com/LazyVim/LazyVim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "LazyVim/LazyVim",
    "link": "https://github.com/LazyVim/LazyVim",
    "pub_date": "",
    "author": "",
    "description": "Neovim config for the lazy Install · Configure · Docs LazyVim is a Neovim setup powered by 💤 lazy.nvim to make it easy to customize and extend your config. Rather than having to choose between starting from scratch or u…",
    "content": "Neovim config for the lazy Install · Configure · Docs LazyVim is a Neovim setup powered by 💤 lazy.nvim to make it easy to customize and extend your config. Rather than having to choose between starting from scratch or using a pre-made distro, LazyVim offers t…"
  },
  {
    "id": "技术-github lua-https://github.com/coder/claudecode.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "coder/claudecode.nvim",
    "link": "https://github.com/coder/claudecode.nvim",
    "pub_date": "",
    "author": "",
    "description": "🧩 Claude Code Neovim IDE Extension claudecode.nvim The first Neovim IDE integration for Claude Code — bringing Anthropic's AI coding assistant to your favorite editor with a pure Lua implementation. 🎯 TL;DR: When Anthr…",
    "content": "🧩 Claude Code Neovim IDE Extension claudecode.nvim The first Neovim IDE integration for Claude Code — bringing Anthropic's AI coding assistant to your favorite editor with a pure Lua implementation. 🎯 TL;DR: When Anthropic released Claude Code with VS Code a…"
  },
  {
    "id": "技术-github lua-https://github.com/neovim/nvim-lspconfig",
    "feed_name": "github lua",
    "category": "技术",
    "title": "neovim/nvim-lspconfig",
    "link": "https://github.com/neovim/nvim-lspconfig",
    "pub_date": "",
    "author": "",
    "description": "Quickstart configs for Nvim LSP nvim-lspconfig nvim-lspconfig is a collection of LSP server configurations for the Nvim LSP client. View all configs, or run :help lspconfig-all from Nvim. Important ⚠️ require('lspconfig'…",
    "content": "Quickstart configs for Nvim LSP nvim-lspconfig nvim-lspconfig is a collection of LSP server configurations for the Nvim LSP client . View all configs , or run :help lspconfig-all from Nvim. Important ⚠️ require('lspconfig') (the legacy \"framework\" of nvim-lspc…"
  },
  {
    "id": "技术-github lua-https://github.com/koreader/koreader",
    "feed_name": "github lua",
    "category": "技术",
    "title": "koreader/koreader",
    "link": "https://github.com/koreader/koreader",
    "pub_date": "",
    "author": "",
    "description": "An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats, running on Cervantes, Kindle, Kobo, PocketBook and Android devices KOReader is a document viewer primarily aimed at e-ink readers. Downlo…",
    "content": "An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats, running on Cervantes, Kindle, Kobo, PocketBook and Android devices KOReader is a document viewer primarily aimed at e-ink readers. Download • User guide • Wiki • Developer docs …"
  },
  {
    "id": "技术-github lua-https://github.com/ThePrimeagen/99",
    "feed_name": "github lua",
    "category": "技术",
    "title": "ThePrimeagen/99",
    "link": "https://github.com/ThePrimeagen/99",
    "pub_date": "",
    "author": "",
    "description": "Neovim AI agent done right 99 The AI client that Neovim deserves, built by those that still enjoy to code. IF YOU ARE HERE FROM THE YT VIDEO So many things have changed. So please be careful! WARNING :: API CHANGES RIGHT…",
    "content": "Neovim AI agent done right 99 The AI client that Neovim deserves, built by those that still enjoy to code. IF YOU ARE HERE FROM THE YT VIDEO So many things have changed. So please be careful! WARNING :: API CHANGES RIGHT NOW It will happen that apis will disap…"
  },
  {
    "id": "技术-github lua-https://github.com/esmuellert/codediff.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "esmuellert/codediff.nvim",
    "link": "https://github.com/esmuellert/codediff.nvim",
    "pub_date": "",
    "author": "",
    "description": "A Neovim plugin that provides VSCode-style diff rendering with two-tier highlighting (line + character level) in side-by-side and inline layouts, using VSCode's algorithm implemented in C. codediff.nvim A Neovim plugin t…",
    "content": "A Neovim plugin that provides VSCode-style diff rendering with two-tier highlighting (line + character level) in side-by-side and inline layouts, using VSCode's algorithm implemented in C. codediff.nvim A Neovim plugin that provides VSCode-style diff rendering…"
  },
  {
    "id": "技术-github lua-https://github.com/PathOfBuildingCommunity/PathOfBuilding",
    "feed_name": "github lua",
    "category": "技术",
    "title": "PathOfBuildingCommunity/PathOfBuilding",
    "link": "https://github.com/PathOfBuildingCommunity/PathOfBuilding",
    "pub_date": "",
    "author": "",
    "description": "Offline build planner for Path of Exile. Path of Building Community Welcome to Path of Building, an offline build planner for Path of Exile! Features Comprehensive offence + defence calculations: Calculate your skill DPS…",
    "content": "Offline build planner for Path of Exile. Path of Building Community Welcome to Path of Building, an offline build planner for Path of Exile! Features Comprehensive offence + defence calculations: Calculate your skill DPS, damage over time, life/mana/ES totals …"
  },
  {
    "id": "技术-github lua-https://github.com/LandSandBoat/server",
    "feed_name": "github lua",
    "category": "技术",
    "title": "LandSandBoat/server",
    "link": "https://github.com/LandSandBoat/server",
    "pub_date": "",
    "author": "",
    "description": "⛵ LandSandBoat - a server emulator for Final Fantasy XI LandSandBoat An open-source server emulator for FFXI. Getting Started A quick start guide, the frequently asked questions, and a table of \"what works\" are all avail…",
    "content": "⛵ LandSandBoat - a server emulator for Final Fantasy XI LandSandBoat An open-source server emulator for FFXI. Getting Started A quick start guide , the frequently asked questions , and a table of \" what works \" are all available on our wiki . Interacting with …"
  },
  {
    "id": "技术-github lua-https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2",
    "feed_name": "github lua",
    "category": "技术",
    "title": "PathOfBuildingCommunity/PathOfBuilding-PoE2",
    "link": "https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2",
    "pub_date": "",
    "author": "",
    "description": "Path of Building 2 Community Welcome to Path of Building 2, an offline build planner for Path of Exile 2! Download Head over to the Releases page to download the install wizard or portable zip. Features Comprehensive off…",
    "content": "Path of Building 2 Community Welcome to Path of Building 2, an offline build planner for Path of Exile 2! Download Head over to the Releases page to download the install wizard or portable zip. Features Comprehensive offence + defence calculations: Calculate y…"
  },
  {
    "id": "技术-github lua-https://github.com/igorlfs/nvim-dap-view",
    "feed_name": "github lua",
    "category": "技术",
    "title": "igorlfs/nvim-dap-view",
    "link": "https://github.com/igorlfs/nvim-dap-view",
    "pub_date": "",
    "author": "",
    "description": "Visualize debugging sessions in neovim nvim-dap-view Modern debugging UI for neovim https://github.com/user-attachments/assets/357bb05d-5645-4cfc-9975-97313c57e770 Introduction A UI for nvim-dap[1]. Installation Warning …",
    "content": "Visualize debugging sessions in neovim nvim-dap-view Modern debugging UI for neovim https://github.com/user-attachments/assets/357bb05d-5645-4cfc-9975-97313c57e770 Introduction A UI for nvim-dap [1] . Installation Warning Requires neovim 0.11+ vim.pack.add({ {…"
  },
  {
    "id": "技术-github lua-https://github.com/stevearc/oil.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "stevearc/oil.nvim",
    "link": "https://github.com/stevearc/oil.nvim",
    "pub_date": "",
    "author": "",
    "description": "Neovim file explorer: edit your filesystem like a buffer oil.nvim A vim-vinegar like file explorer that lets you edit your filesystem like a normal Neovim buffer. https://user-images.githubusercontent.com/506791/20972711…",
    "content": "Neovim file explorer: edit your filesystem like a buffer oil.nvim A vim-vinegar like file explorer that lets you edit your filesystem like a normal Neovim buffer. https://user-images.githubusercontent.com/506791/209727111-6b4a11f4-634a-4efa-9461-80e9717cea94.m…"
  },
  {
    "id": "技术-github lua-https://github.com/iDvel/rime-ice",
    "feed_name": "github lua",
    "category": "技术",
    "title": "iDvel/rime-ice",
    "link": "https://github.com/iDvel/rime-ice",
    "pub_date": "",
    "author": "",
    "description": "Rime 配置：雾凇拼音 | 长期维护的简体词库 雾凇拼音 雾凇拼音是一份开箱即用的简体中文 Rime 输入法配置，词库长期维护，基本功能齐全，使用完全离线，质量稳定可靠。 雾凇拼音包含全拼和双拼输入方案、长期维护的精校词库、各类扩展功能和详尽的注释。适配小狼毫 Weasel、鼠须管 Squirrel、Fcitx5、iBus 等几乎所有 Rime 应用。你可以不折腾，一键下载部署后即刻使用；可以借着完善的注释和社区生态，让 AI 帮你定…",
    "content": "Rime 配置：雾凇拼音 | 长期维护的简体词库 雾凇拼音 雾凇拼音 是一份开箱即用的简体中文 Rime 输入法配置，词库长期维护，基本功能齐全，使用完全离线，质量稳定可靠。 雾凇拼音包含全拼和双拼输入方案、长期维护的精校词库、各类扩展功能和详尽的注释。适配小狼毫 Weasel、鼠须管 Squirrel、Fcitx5、iBus 等几乎所有 Rime 应用。你可以不折腾，一键下载部署后即刻使用；可以借着完善的注释和社区生态，让 AI 帮你定制改造；也可以将之作为深入了解和自定义 Rime 的起点。 使用雾凇拼音，享受…"
  },
  {
    "id": "技术-github lua-https://github.com/olimorris/codecompanion.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "olimorris/codecompanion.nvim",
    "link": "https://github.com/olimorris/codecompanion.nvim",
    "pub_date": "",
    "author": "",
    "description": "✨ AI Coding, Vim Style A Neovim AI coding assistant for coding with LLMs (Anthropic, OpenAI, Gemini, Copilot and more) and AI agents. With built-in support for Agent Client Protocol (ACP), Model Context Protocol (MCP), a…",
    "content": "✨ AI Coding, Vim Style A Neovim AI coding assistant for coding with LLMs (Anthropic, OpenAI, Gemini, Copilot and more ) and AI agents. With built-in support for Agent Client Protocol (ACP) , Model Context Protocol (MCP) , and agents like Claude Code and Codex …"
  },
  {
    "id": "技术-github lua-https://github.com/Courseplay/Courseplay_FS25",
    "feed_name": "github lua",
    "category": "技术",
    "title": "Courseplay/Courseplay_FS25",
    "link": "https://github.com/Courseplay/Courseplay_FS25",
    "pub_date": "",
    "author": "",
    "description": "Courseplay for Farming Simulator 2025 Courseplay Beta for Farming Simulator 25 Download the latest developer version (the file FS25_Courseplay.zip). Courseplay Website This and the Giants ModHub is the only official sour…",
    "content": "Courseplay for Farming Simulator 2025 Courseplay Beta for Farming Simulator 25 Download the latest developer version (the file FS25_Courseplay.zip). Courseplay Website This and the Giants ModHub is the only official source for Courseplay , if you see it anywhe…"
  },
  {
    "id": "技术-github lua-https://github.com/nvim-lua/kickstart.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "nvim-lua/kickstart.nvim",
    "link": "https://github.com/nvim-lua/kickstart.nvim",
    "pub_date": "",
    "author": "",
    "description": "A launch point for your personal nvim configuration kickstart.nvim Introduction A starting point for Neovim that is: Small Single-file Completely Documented NOT a Neovim distribution, but instead a starting point for you…",
    "content": "A launch point for your personal nvim configuration kickstart.nvim Introduction A starting point for Neovim that is: Small Single-file Completely Documented NOT a Neovim distribution, but instead a starting point for your configuration. Installation Install Ne…"
  },
  {
    "id": "技术-github lua-https://github.com/yetone/avante.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "yetone/avante.nvim",
    "link": "https://github.com/yetone/avante.nvim",
    "pub_date": "",
    "author": "",
    "description": "Use your Neovim like using Cursor AI IDE! avante.nvim avante.nvim is a Neovim plugin designed to emulate the behaviour of the Cursor AI IDE. It provides users with AI-driven code suggestions and the ability to apply thes…",
    "content": "Use your Neovim like using Cursor AI IDE! avante.nvim avante.nvim is a Neovim plugin designed to emulate the behaviour of the Cursor AI IDE. It provides users with AI-driven code suggestions and the ability to apply these recommendations directly to their sour…"
  },
  {
    "id": "技术-github lua-https://github.com/b0o/SchemaStore.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "b0o/SchemaStore.nvim",
    "link": "https://github.com/b0o/SchemaStore.nvim",
    "pub_date": "",
    "author": "",
    "description": "🛍 JSON schemas for Neovim SchemaStore.nvim A Neovim plugin that provides the SchemaStore catalog for use with jsonls and yamlls. Install Lazy.nvim: \"b0o/schemastore.nvim\", Packer: use \"b0o/schemastore.nvim\" Usage To use…",
    "content": "🛍 JSON schemas for Neovim SchemaStore.nvim A Neovim plugin that provides the SchemaStore catalog for use with jsonls and yamlls . Install Lazy.nvim : \"b0o/schemastore.nvim\", Packer : use \"b0o/schemastore.nvim\" Usage To use SchemaStore.nvim with lspconfig + js…"
  },
  {
    "id": "技术-github lua-https://github.com/lewis6991/async.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "lewis6991/async.nvim",
    "link": "https://github.com/lewis6991/async.nvim",
    "pub_date": "",
    "author": "",
    "description": "Async library for Neovim plugins async.nvim Structured concurrency for Lua 5.1, built on stackful coroutines. async.nvim lets you write callback-driven work in a direct style while keeping clear task ownership: parents w…",
    "content": "Async library for Neovim plugins async.nvim Structured concurrency for Lua 5.1, built on stackful coroutines. async.nvim lets you write callback-driven work in a direct style while keeping clear task ownership: parents wait for attached children, unhandled chi…"
  },
  {
    "id": "技术-github lua-https://github.com/gbprod/yanky.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "gbprod/yanky.nvim",
    "link": "https://github.com/gbprod/yanky.nvim",
    "pub_date": "",
    "author": "",
    "description": "Improved Yank and Put functionalities for Neovim 🍃 yanky.nvim The aim of yanky.nvim is to improve yank and put functionalities for Neovim. French slogan: \"Vas-y Yanky, c'est bon !\" - Yanky Vincent Or in English: \"Yanky-…",
    "content": "Improved Yank and Put functionalities for Neovim 🍃 yanky.nvim The aim of yanky.nvim is to improve yank and put functionalities for Neovim. French slogan: \"Vas-y Yanky, c'est bon !\" - Yanky Vincent Or in English: \"Yanky-ki-yay, motherf*cker\" - John McYanky ✨ F…"
  }
];

export default jsonData;
