const jsonData = [
  {
    "id": "技术-阮一峰的网络日志-http://www.ruanyifeng.com/blog/2026/07/weekly-issue-404.html",
    "feed_name": "阮一峰的网络日志",
    "category": "技术",
    "title": "科技爱好者周刊（第 404 期）：你需要知道的 AI 内存知识",
    "link": "http://www.ruanyifeng.com/blog/2026/07/weekly-issue-404.html",
    "pub_date": "2026-07-17 07:51:19",
    "author": "阮一峰",
    "description": "这里记录每周值得分享的科技内容，周五发布。 本杂志开源，欢迎投稿。另有《谁在招人》服务，发布程序员招聘信息。合作请邮件联系（yifeng.ruan@gmail.com）。 封面图 上海某商场正在举办的\"海绵宝宝\"展览。（via） 你需要知道的 AI 内存知识 自己在家运行 AI 模型，可以选择两种硬件。 一种是独立显卡，目前最顶级的消费级显卡是英伟达的 RTX 5090，带有 32GB 显存，售价3万元人民币左右。 另一种是采用板载芯片…",
    "content": "这里记录每周值得分享的科技内容，周五发布。 本杂志 开源 ，欢迎 投稿 。另有 《谁在招人》 服务，发布程序员招聘信息。合作请 邮件联系 （yifeng.ruan@gmail.com）。 封面图 上海某商场正在举办的\"海绵宝宝\"展览。（ via ） 你需要知道的 AI 内存知识 自己在家运行 AI 模型，可以选择两种硬件。 一种是独立显卡，目前最顶级的消费级显卡是英伟达的 RTX 5090，带有 32GB 显存，售价3万元人民币左右。 另一种是采用板载芯片组（CPU + 板载显卡 + 板载内存）的家用电脑，比如采用…"
  },
  {
    "id": "技术-阮一峰的网络日志-http://www.ruanyifeng.com/blog/2026/07/weekly-issue-403.html",
    "feed_name": "阮一峰的网络日志",
    "category": "技术",
    "title": "科技爱好者周刊（第 403 期）：为什么 Dropbox 不成功",
    "link": "http://www.ruanyifeng.com/blog/2026/07/weekly-issue-403.html",
    "pub_date": "2026-07-10 08:05:31",
    "author": "阮一峰",
    "description": "这里记录每周值得分享的科技内容，周五发布。 本杂志开源，欢迎投稿。另有《谁在招人》服务，发布程序员招聘信息。合作请邮件联系（yifeng.ruan@gmail.com）。 封面图 贵州修文县的\"穹岛·天坑咖啡\"，咖啡店建在巨大的溶洞之中。（via） 为什么 Dropbox 不成功 Dropbox，大家都知道吧？ 它成立于2007年，创始人是麻省理工学院的学生，经常丢失 U 盘，于是想到可以把文件上传到服务器。 他就创业了，做出了世界第一…",
    "content": "这里记录每周值得分享的科技内容，周五发布。 本杂志 开源 ，欢迎 投稿 。另有 《谁在招人》 服务，发布程序员招聘信息。合作请 邮件联系 （yifeng.ruan@gmail.com）。 封面图 贵州修文县的\"穹岛·天坑咖啡\"，咖啡店建在巨大的溶洞之中。（ via ） 为什么 Dropbox 不成功 Dropbox，大家都知道吧？ 它成立于2007年，创始人是麻省理工学院的学生，经常丢失 U 盘，于是想到可以把文件上传到服务器。 他就创业了，做出了世界第一个\"云盘\"，当时是革命性产品。 这就是 Dropbox 的来…"
  },
  {
    "id": "技术-阮一峰的网络日志-http://www.ruanyifeng.com/blog/2026/07/weekly-issue-402.html",
    "feed_name": "阮一峰的网络日志",
    "category": "技术",
    "title": "科技爱好者周刊（第 402 期）：我在智念 AI 的日子（小说）",
    "link": "http://www.ruanyifeng.com/blog/2026/07/weekly-issue-402.html",
    "pub_date": "2026-07-03 07:33:49",
    "author": "阮一峰",
    "description": "这里记录每周值得分享的科技内容，周五发布。 本杂志开源，欢迎投稿。另有《谁在招人》服务，发布程序员招聘信息。合作请邮件联系（yifeng.ruan@gmail.com）。 封面图 内蒙古乌兰察布的\"草原方舟\"，内部是一个文化空间，举办艺术展览、文化交流、商业活动等。（via） 我在智念 AI 的日子（小说） 下面是一篇老外写的超短篇小说，也可能是 AI 写的，我不确定，但觉得很有趣，分享给大家。 为了易读，我做了一些修改，把内容\"中国化…",
    "content": "这里记录每周值得分享的科技内容，周五发布。 本杂志 开源 ，欢迎 投稿 。另有 《谁在招人》 服务，发布程序员招聘信息。合作请 邮件联系 （yifeng.ruan@gmail.com）。 封面图 内蒙古乌兰察布的\"草原方舟\"，内部是一个文化空间，举办艺术展览、文化交流、商业活动等。（ via ） 我在智念 AI 的日子（小说） 下面是一篇老外写的 超短篇小说 ，也可能是 AI 写的，我不确定，但觉得很有趣，分享给大家。 为了易读，我做了一些修改，把内容\"中国化\"了。 1、 十四个月之前，我加入了一家叫做\"智念 AI…"
  },
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/123",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 123 期",
    "link": "https://hellogithub.com/periodical/volume/123",
    "pub_date": "2026-06-29 08:10:22",
    "author": "",
    "description": "本期共有 38 个项目，包含 C 项目 (2)，C# 项目 (1)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (5)，Kotlin 项目 (1)，Python 项目 (5)，Rust 项目 (3)，Skills (4)，Swift 项目 (2)，人工智能 (5)，其它 (4)",
    "content": "本期共有 38 个项目，包含 C 项目 (2)，C# 项目 (1)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (5)，Kotlin 项目 (1)，Python 项目 (5)，Rust 项目 (3)，Skills (4)，Swift 项目 (2)，人工智能 (5)，其它 (4)"
  },
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/122",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 122 期",
    "link": "https://hellogithub.com/periodical/volume/122",
    "pub_date": "2026-05-28 08:07:51",
    "author": "",
    "description": "本期共有 39 个项目，包含 C 项目 (2)，C# 项目 (3)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (5)，Python 项目 (4)，Rust 项目 (3)，Skills (3)，Swift 项目 (3)，人工智能 (5)，其它 (5)",
    "content": "本期共有 39 个项目，包含 C 项目 (2)，C# 项目 (3)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (5)，Python 项目 (4)，Rust 项目 (3)，Skills (3)，Swift 项目 (3)，人工智能 (5)，其它 (5)"
  },
  {
    "id": "技术-HelloGitHub 月刊-https://hellogithub.com/periodical/volume/121",
    "feed_name": "HelloGitHub 月刊",
    "category": "技术",
    "title": "HelloGitHub 第 121 期",
    "link": "https://hellogithub.com/periodical/volume/121",
    "pub_date": "2026-04-28 08:05:57",
    "author": "",
    "description": "本期共有 40 个项目，包含 C 项目 (1)，C# 项目 (2)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (4)，Kotlin 项目 (1)，Python 项目 (3)，Rust 项目 (4)，Skills (4)，Swift 项目 (3)，人工智能 (5)，其它 (5)，开源书籍 (2)",
    "content": "本期共有 40 个项目，包含 C 项目 (1)，C# 项目 (2)，C++ 项目 (2)，Go 项目 (4)，JavaScript 项目 (4)，Kotlin 项目 (1)，Python 项目 (3)，Rust 项目 (4)，Skills (4)，Swift 项目 (3)，人工智能 (5)，其它 (5)，开源书籍 (2)"
  },
  {
    "id": "技术-github all-https://github.com/Robbyant/lingbot-map",
    "feed_name": "github all",
    "category": "技术",
    "title": "Robbyant/lingbot-map",
    "link": "https://github.com/Robbyant/lingbot-map",
    "pub_date": "",
    "author": "",
    "description": "A feed-forward 3D foundation model for reconstructing scenes from streaming data LingBot-Map: Geometric Context Transformer for Streaming 3D Reconstruction Robbyant Team https://github.com/user-attachments/assets/fe39e09…",
    "content": "A feed-forward 3D foundation model for reconstructing scenes from streaming data LingBot-Map: Geometric Context Transformer for Streaming 3D Reconstruction Robbyant Team https://github.com/user-attachments/assets/fe39e095-af2c-4ec9-b68d-a8ba97e505ab 🗺️ Meet L…"
  },
  {
    "id": "技术-github all-https://github.com/apache/ossie",
    "feed_name": "github all",
    "category": "技术",
    "title": "apache/ossie",
    "link": "https://github.com/apache/ossie",
    "pub_date": "",
    "author": "",
    "description": "Apache Ossie, industry wide specification effort to standardize how we exchange semantic metadata across analytics, AI and BI platforms, providing a vendor neutral, single source of truth for semantic data Apache Ossie (…",
    "content": "Apache Ossie, industry wide specification effort to standardize how we exchange semantic metadata across analytics, AI and BI platforms, providing a vendor neutral, single source of truth for semantic data Apache Ossie (incubating) Apache Ossie is a collaborat…"
  },
  {
    "id": "技术-github all-https://github.com/PostHog/posthog",
    "feed_name": "github all",
    "category": "技术",
    "title": "PostHog/posthog",
    "link": "https://github.com/PostHog/posthog",
    "pub_date": "",
    "author": "",
    "description": "🦔 PostHog is the leading platform for building self-driving products. Our developer tools – AI observability, analytics, session replay, flags, experiments, error tracking, logs, and more – capture all the context agent…",
    "content": "🦔 PostHog is the leading platform for building self-driving products. Our developer tools – AI observability, analytics, session replay, flags, experiments, error tracking, logs, and more – capture all the context agents need to diagnose problems, uncover opp…"
  },
  {
    "id": "技术-github all-https://github.com/ibelick/ui-skills",
    "feed_name": "github all",
    "category": "技术",
    "title": "ibelick/ui-skills",
    "link": "https://github.com/ibelick/ui-skills",
    "pub_date": "",
    "author": "",
    "description": "Skills for Design Engineers UI Skills Skills for Design Engineers More on ui-skills.com Run npx ui-skills start to route your agent through the right UI skill set for the task. CLI npx ui-skills npx ui-skills start npx u…",
    "content": "Skills for Design Engineers UI Skills Skills for Design Engineers More on ui-skills.com Run npx ui-skills start to route your agent through the right UI skill set for the task. CLI npx ui-skills npx ui-skills start npx ui-skills categories npx ui-skills list -…"
  },
  {
    "id": "技术-github all-https://github.com/rohitg00/ai-engineering-from-scratch",
    "feed_name": "github all",
    "category": "技术",
    "title": "rohitg00/ai-engineering-from-scratch",
    "link": "https://github.com/rohitg00/ai-engineering-from-scratch",
    "pub_date": "",
    "author": "",
    "description": "Learn it. Build it. Ship it for others. From the creator of Agent Memory - #1 Persistent memory ⭐ which naturally works with any agents or chat assistants. ░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒…",
    "content": "Learn it. Build it. Ship it for others. From the creator of Agent Memory - #1 Persistent memory ⭐ which naturally works with any agents or chat assistants. ░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒░░░▒▒▒ 84% of studen…"
  },
  {
    "id": "技术-github all-https://github.com/tirth8205/code-review-graph",
    "feed_name": "github all",
    "category": "技术",
    "title": "tirth8205/code-review-graph",
    "link": "https://github.com/tirth8205/code-review-graph",
    "pub_date": "",
    "author": "",
    "description": "Local-first code intelligence graph for MCP and CLI. Builds a persistent map of your codebase so AI coding tools read only what matters, with benchmarked context reductions on reviews and large-repo workflows. code-revie…",
    "content": "Local-first code intelligence graph for MCP and CLI. Builds a persistent map of your codebase so AI coding tools read only what matters, with benchmarked context reductions on reviews and large-repo workflows. code-review-graph Stop burning tokens. Start revie…"
  },
  {
    "id": "技术-github all-https://github.com/elder-plinius/G0DM0D3",
    "feed_name": "github all",
    "category": "技术",
    "title": "elder-plinius/G0DM0D3",
    "link": "https://github.com/elder-plinius/G0DM0D3",
    "pub_date": "",
    "author": "",
    "description": "LIBERATED AI CHAT ▄████ ██████ ██████ ███▄ ▄███ ██████ ██████ ██████ ██ ██ ██ ██ ██ ██ ███ ██ ██ ██ ██ ██ ██ ██ ▄███ ██ ██ ██ ██ ██ █ ██ ██ ██ ██ ██ █████ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██████ ████ ██████ ██ ██ █…",
    "content": "LIBERATED AI CHAT ▄████ ██████ ██████ ███▄ ▄███ ██████ ██████ ██████ ██ ██ ██ ██ ██ ██ ███ ██ ██ ██ ██ ██ ██ ██ ▄███ ██ ██ ██ ██ ██ █ ██ ██ ██ ██ ██ █████ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██ ██████ ████ ██████ ██ ██ ████ ██████ ██████ ──────────────────────…"
  },
  {
    "id": "技术-github all-https://github.com/lyogavin/airllm",
    "feed_name": "github all",
    "category": "技术",
    "title": "lyogavin/airllm",
    "link": "https://github.com/lyogavin/airllm",
    "pub_date": "",
    "author": "",
    "description": "AirLLM 70B inference with single 4GB GPU Quickstart | Configurations | MacOS | Example notebooks | FAQ AirLLM dramatically reduces inference memory usage, letting 70B large language models run on a single 4GB GPU card — …",
    "content": "AirLLM 70B inference with single 4GB GPU Quickstart | Configurations | MacOS | Example notebooks | FAQ AirLLM dramatically reduces inference memory usage, letting 70B large language models run on a single 4GB GPU card — without quantization, distillation, or p…"
  },
  {
    "id": "技术-github all-https://github.com/KnockOutEZ/wigolo",
    "feed_name": "github all",
    "category": "技术",
    "title": "KnockOutEZ/wigolo",
    "link": "https://github.com/KnockOutEZ/wigolo",
    "pub_date": "",
    "author": "",
    "description": "The go-to web for your AI coding agent — local-first search, fetch, crawl & research over MCP. No API keys, no cloud, $0/query. Public beta. Local-first web intelligence for AI agents — no keys, no cloud, no metered bill…",
    "content": "The go-to web for your AI coding agent — local-first search, fetch, crawl & research over MCP. No API keys, no cloud, $0/query. Public beta. Local-first web intelligence for AI agents — no keys, no cloud, no metered bill. works with&nbsp;&nbsp; Claude Code · C…"
  },
  {
    "id": "技术-github all-https://github.com/codecrafters-io/build-your-own-x",
    "feed_name": "github all",
    "category": "技术",
    "title": "codecrafters-io/build-your-own-x",
    "link": "https://github.com/codecrafters-io/build-your-own-x",
    "pub_date": "",
    "author": "",
    "description": "Master programming by recreating your favorite technologies from scratch. Build your own This repository is a compilation of well-written, step-by-step guides for re-creating our favorite technologies from scratch. What …",
    "content": "Master programming by recreating your favorite technologies from scratch. Build your own &lt;insert-technology-here&gt; This repository is a compilation of well-written, step-by-step guides for re-creating our favorite technologies from scratch. What I cannot …"
  },
  {
    "id": "技术-github all-https://github.com/MoonshotAI/kimi-cli",
    "feed_name": "github all",
    "category": "技术",
    "title": "MoonshotAI/kimi-cli",
    "link": "https://github.com/MoonshotAI/kimi-cli",
    "pub_date": "",
    "author": "",
    "description": "Kimi Code CLI is your next CLI agent. Kimi CLI Kimi Code | Documentation | 文档 Important Kimi CLI is evolving into Kimi Code CLI — the next-generation terminal AI agent from the same team. Installing Kimi Code CLI automat…",
    "content": "Kimi Code CLI is your next CLI agent. Kimi CLI Kimi Code | Documentation | 文档 Important Kimi CLI is evolving into Kimi Code CLI — the next-generation terminal AI agent from the same team. Installing Kimi Code CLI automatically migrates your configuration and s…"
  },
  {
    "id": "技术-github go-https://github.com/Wei-Shaw/sub2api",
    "feed_name": "github go",
    "category": "技术",
    "title": "Wei-Shaw/sub2api",
    "link": "https://github.com/Wei-Shaw/sub2api",
    "pub_date": "",
    "author": "",
    "description": "Sub2API 一站式开源中转服务，让 Claude、Openai 、Gemini、Grok订阅统一接入，支持拼车共享，更高效分摊成本，原生工具无缝使用。 Sub2API AI API Gateway Platform for Subscription Quota Distribution English | 中文 | 日本語 ⚠️ Important Notice Please read the following carefully…",
    "content": "Sub2API 一站式开源中转服务，让 Claude、Openai 、Gemini、Grok订阅统一接入，支持拼车共享，更高效分摊成本，原生工具无缝使用。 Sub2API AI API Gateway Platform for Subscription Quota Distribution English | 中文 | 日本語 ⚠️ Important Notice Please read the following carefully before using this project: 🚨 Terms of …"
  },
  {
    "id": "技术-github go-https://github.com/microsoft/typescript-go",
    "feed_name": "github go",
    "category": "技术",
    "title": "microsoft/typescript-go",
    "link": "https://github.com/microsoft/typescript-go",
    "pub_date": "",
    "author": "",
    "description": "Staging repo for development of native port of TypeScript TypeScript 7 Not sure what this is? Read the announcement post! Preview A preview build is available on npm as @typescript/native-preview. npm install @typescript…",
    "content": "Staging repo for development of native port of TypeScript TypeScript 7 Not sure what this is? Read the announcement post! Preview A preview build is available on npm as @typescript/native-preview . npm install @typescript/native-preview npx tsgo # Use this as …"
  },
  {
    "id": "技术-github go-https://github.com/pocketbase/pocketbase",
    "feed_name": "github go",
    "category": "技术",
    "title": "pocketbase/pocketbase",
    "link": "https://github.com/pocketbase/pocketbase",
    "pub_date": "",
    "author": "",
    "description": "Open Source realtime backend in 1 file PocketBase is an open source Go backend that includes: embedded database (SQLite) with realtime subscriptions built-in files and users management convenient Admin dashboard UI and s…",
    "content": "Open Source realtime backend in 1 file PocketBase is an open source Go backend that includes: embedded database ( SQLite ) with realtime subscriptions built-in files and users management convenient Admin dashboard UI and simple REST-ish API For documentation a…"
  },
  {
    "id": "技术-github go-https://github.com/chenyme/grok2api",
    "feed_name": "github go",
    "category": "技术",
    "title": "chenyme/grok2api",
    "link": "https://github.com/chenyme/grok2api",
    "pub_date": "",
    "author": "",
    "description": "Multi-account API gateway for Grok Build, Grok Web, and Grok Console A multi-account API gateway for Grok Build, Grok Web, and Grok Console English | 简体中文 Tip Check out DEEIX-AI / DEEIX-Chat, a lightweight, integrated AI…",
    "content": "Multi-account API gateway for Grok Build, Grok Web, and Grok Console A multi-account API gateway for Grok Build, Grok Web, and Grok Console English | 简体中文 Tip Check out DEEIX-AI / DEEIX-Chat , a lightweight, integrated AI platform for model routing, chat, file…"
  },
  {
    "id": "技术-github go-https://github.com/multica-ai/multica",
    "feed_name": "github go",
    "category": "技术",
    "title": "multica-ai/multica",
    "link": "https://github.com/multica-ai/multica",
    "pub_date": "",
    "author": "",
    "description": "The open-source managed agents platform. Turn coding agents into real teammates — assign tasks, track progress, compound skills. Multica Your next 10 hires won't be human. The open-source managed agents platform. Turn co…",
    "content": "The open-source managed agents platform. Turn coding agents into real teammates — assign tasks, track progress, compound skills. Multica Your next 10 hires won't be human. The open-source managed agents platform. Turn coding agents into real teammates — assign…"
  },
  {
    "id": "技术-github go-https://github.com/schollz/croc",
    "feed_name": "github go",
    "category": "技术",
    "title": "schollz/croc",
    "link": "https://github.com/schollz/croc",
    "pub_date": "",
    "author": "",
    "description": "Easily and securely send things from one computer to another 🐊 📦 This project’s future depends on community support. Become a sponsor today. About croc is a tool that allows any two computers to simply and securely tra…",
    "content": "Easily and securely send things from one computer to another 🐊 📦 This project’s future depends on community support. Become a sponsor today . About croc is a tool that allows any two computers to simply and securely transfer files and folders. AFAIK, croc is…"
  },
  {
    "id": "技术-github go-https://github.com/gosom/google-maps-scraper",
    "feed_name": "github go",
    "category": "技术",
    "title": "gosom/google-maps-scraper",
    "link": "https://github.com/gosom/google-maps-scraper",
    "pub_date": "",
    "author": "",
    "description": "scrape data from Google Maps. Extracts data such as the name, address, phone number, website URL, rating, reviews number, latitude and longitude, reviews,email and more for each place Google Maps Scraper Extract Google M…",
    "content": "scrape data from Google Maps. Extracts data such as the name, address, phone number, website URL, rating, reviews number, latitude and longitude, reviews,email and more for each place Google Maps Scraper Extract Google Maps business leads, emails, reviews, pho…"
  },
  {
    "id": "技术-github go-https://github.com/Gentleman-Programming/engram",
    "feed_name": "github go",
    "category": "技术",
    "title": "Gentleman-Programming/engram",
    "link": "https://github.com/Gentleman-Programming/engram",
    "pub_date": "",
    "author": "",
    "description": "Persistent memory system for AI coding agents. Agent-agnostic Go binary with SQLite + FTS5, MCP server, HTTP API, CLI, and TUI. Persistent memory for AI coding agents One brain. Local or cloud. Agent-agnostic, single bin…",
    "content": "Persistent memory system for AI coding agents. Agent-agnostic Go binary with SQLite + FTS5, MCP server, HTTP API, CLI, and TUI. Persistent memory for AI coding agents One brain. Local or cloud. Agent-agnostic, single binary, zero dependencies. Installation • E…"
  },
  {
    "id": "技术-github go-https://github.com/sundowndev/phoneinfoga",
    "feed_name": "github go",
    "category": "技术",
    "title": "sundowndev/phoneinfoga",
    "link": "https://github.com/sundowndev/phoneinfoga",
    "pub_date": "",
    "author": "",
    "description": "Information gathering framework for phone numbers Information gathering framework for phone numbers Documentation • API documentation • Related blog post About PhoneInfoga is one of the most advanced tools to scan intern…",
    "content": "Information gathering framework for phone numbers Information gathering framework for phone numbers Documentation • API documentation • Related blog post About PhoneInfoga is one of the most advanced tools to scan international phone numbers. It allows you to …"
  },
  {
    "id": "技术-github go-https://github.com/hashicorp/vault",
    "feed_name": "github go",
    "category": "技术",
    "title": "hashicorp/vault",
    "link": "https://github.com/hashicorp/vault",
    "pub_date": "",
    "author": "",
    "description": "A tool for secrets management, encryption as a service, and privileged access management Vault Please note: We take Vault's security and our users' trust very seriously. If you believe you have found a security issue in …",
    "content": "A tool for secrets management, encryption as a service, and privileged access management Vault Please note : We take Vault's security and our users' trust very seriously. If you believe you have found a security issue in Vault, please responsibly disclose by c…"
  },
  {
    "id": "技术-github go-https://github.com/hashicorp/terraform-provider-aws",
    "feed_name": "github go",
    "category": "技术",
    "title": "hashicorp/terraform-provider-aws",
    "link": "https://github.com/hashicorp/terraform-provider-aws",
    "pub_date": "",
    "author": "",
    "description": "The AWS Provider enables Terraform to manage AWS resources. Terraform AWS Provider The AWS Provider enables Terraform to manage AWS resources. Contributing guide Quarterly development roadmap FAQ Tutorials discuss.hashic…",
    "content": "The AWS Provider enables Terraform to manage AWS resources. Terraform AWS Provider The AWS Provider enables Terraform to manage AWS resources. Contributing guide Quarterly development roadmap FAQ Tutorials discuss.hashicorp.com Please note: We take Terraform's…"
  },
  {
    "id": "技术-github go-https://github.com/QuantumNous/new-api",
    "feed_name": "github go",
    "category": "技术",
    "title": "QuantumNous/new-api",
    "link": "https://github.com/QuantumNous/new-api",
    "pub_date": "",
    "author": "",
    "description": "A unified AI model hub for aggregation & distribution. It supports cross-converting various LLMs into OpenAI-compatible, Claude-compatible, or Gemini-compatible formats. A centralized gateway for personal and enterprise …",
    "content": "A unified AI model hub for aggregation & distribution. It supports cross-converting various LLMs into OpenAI-compatible, Claude-compatible, or Gemini-compatible formats. A centralized gateway for personal and enterprise model management. 🍥 New API 🍥 Next-Gen…"
  },
  {
    "id": "技术-github go-https://github.com/binwiederhier/ntfy",
    "feed_name": "github go",
    "category": "技术",
    "title": "binwiederhier/ntfy",
    "link": "https://github.com/binwiederhier/ntfy",
    "pub_date": "",
    "author": "",
    "description": "Send push notifications to your phone or desktop using PUT/POST Special thanks to: Warp, built for coding with multiple AI agents. Available for MacOS, Linux, & Windows ntfy.sh | Send push notifications to your phone or …",
    "content": "Send push notifications to your phone or desktop using PUT/POST Special thanks to: Warp, built for coding with multiple AI agents. Available for MacOS, Linux, &amp; Windows ntfy.sh | Send push notifications to your phone or desktop via PUT/POST ntfy (pronounce…"
  },
  {
    "id": "技术-github go-https://github.com/pocket-id/pocket-id",
    "feed_name": "github go",
    "category": "技术",
    "title": "pocket-id/pocket-id",
    "link": "https://github.com/pocket-id/pocket-id",
    "pub_date": "",
    "author": "",
    "description": "The most user-friendly OpenID Connect Certified™ and OAuth 2.0 provider that lets users sign in to your applications with passkeys. Pocket ID Pocket ID is an easy-to-use OpenID Connect Certified™ and OAuth 2.0 provider t…",
    "content": "The most user-friendly OpenID Connect Certified™ and OAuth 2.0 provider that lets users sign in to your applications with passkeys. Pocket ID Pocket ID is an easy-to-use OpenID Connect Certified™ and OAuth 2.0 provider that lets users sign in to your applicati…"
  },
  {
    "id": "技术-github go-https://github.com/lima-vm/lima",
    "feed_name": "github go",
    "category": "技术",
    "title": "lima-vm/lima",
    "link": "https://github.com/lima-vm/lima",
    "pub_date": "",
    "author": "",
    "description": "Linux virtual machines, with a focus on running containers [🌎Web site] [📖Documentation] [👤Slack (#lima)] Lima: Linux Machines Lima launches Linux virtual machines with automatic file sharing and port forwarding (simil…",
    "content": "Linux virtual machines, with a focus on running containers [🌎 Web site ] [📖 Documentation ] [👤 Slack ( #lima ) ] Lima: Linux Machines Lima launches Linux virtual machines with automatic file sharing and port forwarding (similar to WSL2). The original goal o…"
  },
  {
    "id": "技术-github go-https://github.com/vxcontrol/pentagi",
    "feed_name": "github go",
    "category": "技术",
    "title": "vxcontrol/pentagi",
    "link": "https://github.com/vxcontrol/pentagi",
    "pub_date": "",
    "author": "",
    "description": "Fully autonomous AI Agents system capable of performing complex penetration testing tasks PentAGI Penetration testing Artificial General Intelligence Join the Community! Connect with security researchers, AI enthusiasts,…",
    "content": "Fully autonomous AI Agents system capable of performing complex penetration testing tasks PentAGI P enetration testing A rtificial G eneral I ntelligence Join the Community! Connect with security researchers, AI enthusiasts, and fellow ethical hackers. Get sup…"
  },
  {
    "id": "技术-github go-https://github.com/ollama/ollama",
    "feed_name": "github go",
    "category": "技术",
    "title": "ollama/ollama",
    "link": "https://github.com/ollama/ollama",
    "pub_date": "",
    "author": "",
    "description": "Get up and running with Kimi-K2.6, GLM-5.2, MiniMax, DeepSeek, gpt-oss, Qwen, Gemma and other models. Ollama Start building with open models. Download macOS curl -fsSL https://ollama.com/install.sh | sh or download manua…",
    "content": "Get up and running with Kimi-K2.6, GLM-5.2, MiniMax, DeepSeek, gpt-oss, Qwen, Gemma and other models. Ollama Start building with open models. Download macOS curl -fsSL https://ollama.com/install.sh | sh or download manually Windows irm https://ollama.com/insta…"
  },
  {
    "id": "技术-github go-https://github.com/argoproj/argo-cd",
    "feed_name": "github go",
    "category": "技术",
    "title": "argoproj/argo-cd",
    "link": "https://github.com/argoproj/argo-cd",
    "pub_date": "",
    "author": "",
    "description": "Declarative Continuous Deployment for Kubernetes Releases: Code: Social: Argo CD - Declarative Continuous Delivery for Kubernetes What is Argo CD? Argo CD is a declarative GitOps continuous delivery tool for Kubernetes. …",
    "content": "Declarative Continuous Deployment for Kubernetes Releases: Code: Social: Argo CD - Declarative Continuous Delivery for Kubernetes What is Argo CD? Argo CD is a declarative GitOps continuous delivery tool for Kubernetes. Why Argo CD? Application definitions, co…"
  },
  {
    "id": "技术-github go-https://github.com/qax-os/excelize",
    "feed_name": "github go",
    "category": "技术",
    "title": "qax-os/excelize",
    "link": "https://github.com/qax-os/excelize",
    "pub_date": "",
    "author": "",
    "description": "Go language library for reading and writing Microsoft Excel™ (XLAM / XLSM / XLSX / XLTM / XLTX) spreadsheets Excelize Introduction Excelize is a library written in pure Go providing a set of functions that allow you to w…",
    "content": "Go language library for reading and writing Microsoft Excel™ (XLAM / XLSM / XLSX / XLTM / XLTX) spreadsheets Excelize Introduction Excelize is a library written in pure Go providing a set of functions that allow you to write to and read from XLAM / XLSM / XLSX…"
  },
  {
    "id": "技术-github go-https://github.com/tailscale/tailscale",
    "feed_name": "github go",
    "category": "技术",
    "title": "tailscale/tailscale",
    "link": "https://github.com/tailscale/tailscale",
    "pub_date": "",
    "author": "",
    "description": "The easiest, most secure way to use WireGuard and 2FA. Tailscale https://tailscale.com Private WireGuard® networks made easy Overview This repository contains the majority of Tailscale's open source code. Notably, it inc…",
    "content": "The easiest, most secure way to use WireGuard and 2FA. Tailscale https://tailscale.com Private WireGuard® networks made easy Overview This repository contains the majority of Tailscale's open source code. Notably, it includes the tailscaled daemon and the tail…"
  },
  {
    "id": "技术-github go-https://github.com/hashicorp/terraform",
    "feed_name": "github go",
    "category": "技术",
    "title": "hashicorp/terraform",
    "link": "https://github.com/hashicorp/terraform",
    "pub_date": "",
    "author": "",
    "description": "Terraform enables you to safely and predictably create, change, and improve infrastructure. It is a source-available tool that codifies APIs into declarative configuration files that can be shared amongst team members, t…",
    "content": "Terraform enables you to safely and predictably create, change, and improve infrastructure. It is a source-available tool that codifies APIs into declarative configuration files that can be shared amongst team members, treated as code, edited, reviewed, and ve…"
  },
  {
    "id": "技术-github rust-https://github.com/openai/codex",
    "feed_name": "github rust",
    "category": "技术",
    "title": "openai/codex",
    "link": "https://github.com/openai/codex",
    "pub_date": "",
    "author": "",
    "description": "Lightweight coding agent that runs in your terminal Codex CLI is a coding agent from OpenAI that runs locally on your computer. If you want Codex in your code editor (VS Code, Cursor, Windsurf), install in your IDE. If y…",
    "content": "Lightweight coding agent that runs in your terminal Codex CLI is a coding agent from OpenAI that runs locally on your computer. If you want Codex in your code editor (VS Code, Cursor, Windsurf), install in your IDE. If you want the desktop app experience, run …"
  },
  {
    "id": "技术-github rust-https://github.com/openinterpreter/openinterpreter",
    "feed_name": "github rust",
    "category": "技术",
    "title": "openinterpreter/openinterpreter",
    "link": "https://github.com/openinterpreter/openinterpreter",
    "pub_date": "",
    "author": "",
    "description": "A coding agent for open models like Kimi K3 Open Interpreter A coding agent optimized for low-cost models. Blog post ↗ English • Español • 简体中文 Note Today: Kimi K3 is here. We have reimplemented the provider-recommended …",
    "content": "A coding agent for open models like Kimi K3 Open Interpreter A coding agent optimized for low-cost models. Blog post ↗ English • Español • 简体中文 Note Today: Kimi K3 is here. We have reimplemented the provider-recommended Kimi Code harness in Rust, giving you ma…"
  },
  {
    "id": "技术-github rust-https://github.com/ogulcancelik/herdr",
    "feed_name": "github rust",
    "category": "技术",
    "title": "ogulcancelik/herdr",
    "link": "https://github.com/ogulcancelik/herdr",
    "pub_date": "",
    "author": "",
    "description": "agent multiplexer that lives in your terminal. herdr herdr.dev · install · quick start · docs · sponsors https://github.com/user-attachments/assets/043ec09f-4bdd-41d5-aee0-8fda6b83e267 agent multiplexer that lives in you…",
    "content": "agent multiplexer that lives in your terminal. herdr herdr.dev · install · quick start · docs · sponsors https://github.com/user-attachments/assets/043ec09f-4bdd-41d5-aee0-8fda6b83e267 agent multiplexer that lives in your terminal. every agent at a glance — bl…"
  },
  {
    "id": "技术-github rust-https://github.com/oven-sh/bun",
    "feed_name": "github rust",
    "category": "技术",
    "title": "oven-sh/bun",
    "link": "https://github.com/oven-sh/bun",
    "pub_date": "",
    "author": "",
    "description": "Incredibly fast JavaScript runtime, bundler, test runner, and package manager – all in one Bun Documentation • Discord • Issues • Roadmap Read the docs → What is Bun? Bun is an all-in-one toolkit for JavaScript and TypeS…",
    "content": "Incredibly fast JavaScript runtime, bundler, test runner, and package manager – all in one Bun Documentation &nbsp;&nbsp;•&nbsp;&nbsp; Discord &nbsp;&nbsp;•&nbsp;&nbsp; Issues &nbsp;&nbsp;•&nbsp;&nbsp; Roadmap Read the docs → What is Bun? Bun is an all-in-one …"
  },
  {
    "id": "技术-github rust-https://github.com/screenpipe/screenpipe",
    "feed_name": "github rust",
    "category": "技术",
    "title": "screenpipe/screenpipe",
    "link": "https://github.com/screenpipe/screenpipe",
    "pub_date": "",
    "author": "",
    "description": "YC (S26) | Record your screen 24/7 and plug into your agents. Local, private, secure. Connect to OpenClaw, Hermes agent and 100+ apps [ screenpipe | YC S26 ] screenpipe remembers how you actually work It captures what yo…",
    "content": "YC (S26) | Record your screen 24/7 and plug into your agents. Local, private, secure. Connect to OpenClaw, Hermes agent and 100+ apps [ screenpipe | YC S26 ] screenpipe remembers how you actually work It captures what you see, say, and do, locally, 24/7, then …"
  },
  {
    "id": "技术-github rust-https://github.com/malisper/pgrust",
    "feed_name": "github rust",
    "category": "技术",
    "title": "malisper/pgrust",
    "link": "https://github.com/malisper/pgrust",
    "pub_date": "",
    "author": "",
    "description": "Postgres rewritten in Rust, now passing 100% of the Postgres regression tests pgrust A Postgres rewrite in Rust. Browser demo | Discord | Get pgrust updates | Issues pgrust targets compatibility with Postgres 18.3 and ma…",
    "content": "Postgres rewritten in Rust, now passing 100% of the Postgres regression tests pgrust A Postgres rewrite in Rust. Browser demo &nbsp;&nbsp;|&nbsp;&nbsp; Discord &nbsp;&nbsp;|&nbsp;&nbsp; Get pgrust updates &nbsp;&nbsp;|&nbsp;&nbsp; Issues pgrust targets compati…"
  },
  {
    "id": "技术-github rust-https://github.com/memvid/memvid",
    "feed_name": "github rust",
    "category": "技术",
    "title": "memvid/memvid",
    "link": "https://github.com/memvid/memvid",
    "pub_date": "",
    "author": "",
    "description": "Memory layer for AI Agents. Replace complex RAG pipelines with a serverless, single-file memory layer. Give your agents instant retrieval and long-term memory. Memvid is a single-file memory layer for AI agents with inst…",
    "content": "Memory layer for AI Agents. Replace complex RAG pipelines with a serverless, single-file memory layer. Give your agents instant retrieval and long-term memory. Memvid is a single-file memory layer for AI agents with instant retrieval and long-term memory. Pers…"
  },
  {
    "id": "技术-github rust-https://github.com/astral-sh/uv",
    "feed_name": "github rust",
    "category": "技术",
    "title": "astral-sh/uv",
    "link": "https://github.com/astral-sh/uv",
    "pub_date": "",
    "author": "",
    "description": "An extremely fast Python package and project manager, written in Rust. uv An extremely fast Python package and project manager, written in Rust. Installing Trio's dependencies with a warm cache. Highlights A single tool …",
    "content": "An extremely fast Python package and project manager, written in Rust. uv An extremely fast Python package and project manager, written in Rust. Installing Trio 's dependencies with a warm cache. Highlights A single tool to replace pip , pip-tools , pipx , poe…"
  },
  {
    "id": "技术-github rust-https://github.com/andrewrabert/jellium-desktop",
    "feed_name": "github rust",
    "category": "技术",
    "title": "andrewrabert/jellium-desktop",
    "link": "https://github.com/andrewrabert/jellium-desktop",
    "pub_date": "",
    "author": "",
    "description": "An unofficial desktop client for Jellyfin Jellium Desktop An unofficial Jellyfin desktop client built on CEF and mpv. Downloads Linux AppImage x86_64 aarch64 Arch Linux (AUR): jellium-desktop-git Flatpak (non-Flathub bun…",
    "content": "An unofficial desktop client for Jellyfin Jellium Desktop An unofficial Jellyfin desktop client built on CEF and mpv . Downloads Linux AppImage x86_64 aarch64 Arch Linux (AUR): jellium-desktop-git Flatpak (non-Flathub bundle) macOS Apple Silicon Intel After in…"
  },
  {
    "id": "技术-github rust-https://github.com/astral-sh/ruff",
    "feed_name": "github rust",
    "category": "技术",
    "title": "astral-sh/ruff",
    "link": "https://github.com/astral-sh/ruff",
    "pub_date": "",
    "author": "",
    "description": "An extremely fast Python linter and code formatter, written in Rust. Ruff Docs | Playground An extremely fast Python linter and code formatter, written in Rust. Linting the CPython codebase from scratch. ⚡️ 10-100x faste…",
    "content": "An extremely fast Python linter and code formatter, written in Rust. Ruff Docs | Playground An extremely fast Python linter and code formatter, written in Rust. Linting the CPython codebase from scratch. ⚡️ 10-100x faster than existing linters (like Flake8) an…"
  },
  {
    "id": "技术-github rust-https://github.com/Zackriya-Solutions/meetily",
    "feed_name": "github rust",
    "category": "技术",
    "title": "Zackriya-Solutions/meetily",
    "link": "https://github.com/Zackriya-Solutions/meetily",
    "pub_date": "",
    "author": "",
    "description": "Privacy first, AI meeting assistant with 4x faster Parakeet/Whisper live transcription, speaker diarization, and Ollama summarization built on Rust. 100% local processing. no cloud required. Meetily (Meetly Ai - https://…",
    "content": "Privacy first, AI meeting assistant with 4x faster Parakeet/Whisper live transcription, speaker diarization, and Ollama summarization built on Rust. 100% local processing. no cloud required. Meetily (Meetly Ai - https://meetily.ai) is the #1 Self-hosted, Open-…"
  },
  {
    "id": "技术-github rust-https://github.com/emilk/egui",
    "feed_name": "github rust",
    "category": "技术",
    "title": "emilk/egui",
    "link": "https://github.com/emilk/egui",
    "pub_date": "",
    "author": "",
    "description": "egui: an easy-to-use immediate mode GUI in Rust that runs on both web and native 🖌 egui: an easy-to-use GUI in pure Rust 👉 Click to run the web demo 👈 egui (pronounced \"e-gooey\") is a simple, fast, and highly portable…",
    "content": "egui: an easy-to-use immediate mode GUI in Rust that runs on both web and native 🖌 egui: an easy-to-use GUI in pure Rust 👉 Click to run the web demo 👈 egui (pronounced \"e-gooey\") is a simple, fast, and highly portable immediate mode GUI library for Rust. eg…"
  },
  {
    "id": "技术-github rust-https://github.com/TencentCloud/CubeSandbox",
    "feed_name": "github rust",
    "category": "技术",
    "title": "TencentCloud/CubeSandbox",
    "link": "https://github.com/TencentCloud/CubeSandbox",
    "pub_date": "",
    "author": "",
    "description": "Instant, Concurrent, Secure & Lightweight Sandbox for AI Agents. CubeSandbox Instant, Concurrent, Secure & Lightweight Sandbox Service for AI Agents 中文文档 · Quick Start · Documentation · Changelog · X(Twitter) · End User …",
    "content": "Instant, Concurrent, Secure & Lightweight Sandbox for AI Agents. CubeSandbox Instant, Concurrent, Secure &amp; Lightweight Sandbox Service for AI Agents 中文文档 · Quick Start · Documentation · Changelog · X(Twitter) · End User Program Cube Sandbox is a high-perfo…"
  },
  {
    "id": "技术-github rust-https://github.com/helix-editor/helix",
    "feed_name": "github rust",
    "category": "技术",
    "title": "helix-editor/helix",
    "link": "https://github.com/helix-editor/helix",
    "pub_date": "",
    "author": "",
    "description": "A post-modern modal text editor. A Kakoune / Neovim inspired editor, written in Rust. The editing model is very heavily based on Kakoune; during development I found myself agreeing with most of Kakoune's design decisions…",
    "content": "A post-modern modal text editor. A Kakoune / Neovim inspired editor, written in Rust. The editing model is very heavily based on Kakoune; during development I found myself agreeing with most of Kakoune's design decisions. For more information, see the website …"
  },
  {
    "id": "技术-github rust-https://github.com/stalwartlabs/stalwart",
    "feed_name": "github rust",
    "category": "技术",
    "title": "stalwartlabs/stalwart",
    "link": "https://github.com/stalwartlabs/stalwart",
    "pub_date": "",
    "author": "",
    "description": "All-in-one Mail & Collaboration server. Secure, scalable and fluent in every protocol (IMAP, JMAP, SMTP, CalDAV, CardDAV, WebDAV). Secure, scalable mail & collaboration server with comprehensive protocol support 🛡️ (IMA…",
    "content": "All-in-one Mail & Collaboration server. Secure, scalable and fluent in every protocol (IMAP, JMAP, SMTP, CalDAV, CardDAV, WebDAV). Secure, scalable mail &amp; collaboration server with comprehensive protocol support 🛡️ (IMAP, JMAP, SMTP, CalDAV, CardDAV, WebD…"
  },
  {
    "id": "技术-github rust-https://github.com/nushell/nushell",
    "feed_name": "github rust",
    "category": "技术",
    "title": "nushell/nushell",
    "link": "https://github.com/nushell/nushell",
    "pub_date": "",
    "author": "",
    "description": "A new type of shell Nushell A new type of shell. Table of Contents Status Learning About Nu Installation Configuration Philosophy Pipelines Opening files Plugins Goals Officially Supported By Contributing License Status …",
    "content": "A new type of shell Nushell A new type of shell. Table of Contents Status Learning About Nu Installation Configuration Philosophy Pipelines Opening files Plugins Goals Officially Supported By Contributing License Status This project has reached a minimum-viabl…"
  },
  {
    "id": "技术-github rust-https://github.com/a2x/cs2-dumper",
    "feed_name": "github rust",
    "category": "技术",
    "title": "a2x/cs2-dumper",
    "link": "https://github.com/a2x/cs2-dumper",
    "pub_date": "",
    "author": "",
    "description": "Counter-Strike: 2 Offset Dumper cs2-dumper An external offset/interface dumper for Counter-Strike 2, with support for both Windows & Linux. Powered by memflow. The native Linux version is available in the linux branch (c…",
    "content": "Counter-Strike: 2 Offset Dumper cs2-dumper An external offset/interface dumper for Counter-Strike 2, with support for both Windows &amp; Linux. Powered by memflow . The native Linux version is available in the linux branch (currently outdated). For a work-in-p…"
  },
  {
    "id": "技术-github rust-https://github.com/linera-io/linera-protocol",
    "feed_name": "github rust",
    "category": "技术",
    "title": "linera-io/linera-protocol",
    "link": "https://github.com/linera-io/linera-protocol",
    "pub_date": "",
    "author": "",
    "description": "Main repository for the Linera protocol Linera is a decentralized blockchain infrastructure designed for highly scalable, secure, low-latency Web3 applications. Documentation Visit our developer page and read our whitepa…",
    "content": "Main repository for the Linera protocol Linera is a decentralized blockchain infrastructure designed for highly scalable, secure, low-latency Web3 applications. Documentation Visit our developer page and read our whitepaper to learn more about the Linera proto…"
  },
  {
    "id": "技术-github rust-https://github.com/ai-dynamo/dynamo",
    "feed_name": "github rust",
    "category": "技术",
    "title": "ai-dynamo/dynamo",
    "link": "https://github.com/ai-dynamo/dynamo",
    "pub_date": "",
    "author": "",
    "description": "A Datacenter Scale Distributed Inference Serving Framework | Docs | Roadmap | Recipes | Examples | Prebuilt Containers | Digest | Design Proposals | How to Contribute | Dynamo The open-source, datacenter-scale inference …",
    "content": "A Datacenter Scale Distributed Inference Serving Framework | Docs | Roadmap | Recipes | Examples | Prebuilt Containers | Digest | Design Proposals | How to Contribute | Dynamo The open-source, datacenter-scale inference stack. Dynamo is the orchestration layer…"
  },
  {
    "id": "技术-github javascript-https://github.com/openai/codex-plugin-cc",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "openai/codex-plugin-cc",
    "link": "https://github.com/openai/codex-plugin-cc",
    "pub_date": "",
    "author": "",
    "description": "Use Codex from Claude Code to review code or delegate tasks. Codex plugin for Claude Code Use Codex from inside Claude Code for code reviews or to delegate tasks to Codex. This plugin is for Claude Code users who want an…",
    "content": "Use Codex from Claude Code to review code or delegate tasks. Codex plugin for Claude Code Use Codex from inside Claude Code for code reviews or to delegate tasks to Codex. This plugin is for Claude Code users who want an easy way to start using Codex from the …"
  },
  {
    "id": "技术-github javascript-https://github.com/ilysenko/codex-desktop-linux",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "ilysenko/codex-desktop-linux",
    "link": "https://github.com/ilysenko/codex-desktop-linux",
    "pub_date": "",
    "author": "",
    "description": "Unofficial ChatGPT desktop app for Linux (formerly the Codex app), built locally from OpenAI’s official macOS app. Includes Chat, Work, and Codex. Packages for Debian/Ubuntu (.deb), Fedora/openSUSE (.rpm), Arch (pacman),…",
    "content": "Unofficial ChatGPT desktop app for Linux (formerly the Codex app), built locally from OpenAI’s official macOS app. Includes Chat, Work, and Codex. Packages for Debian/Ubuntu (.deb), Fedora/openSUSE (.rpm), Arch (pacman), Nix/NixOS, and AppImage, with Wayland a…"
  },
  {
    "id": "技术-github javascript-https://github.com/WebKit/WebKit",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "WebKit/WebKit",
    "link": "https://github.com/WebKit/WebKit",
    "pub_date": "",
    "author": "",
    "description": "Home of the WebKit project, the browser engine used by Safari, Mail, App Store and many other applications on macOS, iOS and Linux. WebKit WebKit is a cross-platform web browser engine. On iOS and macOS, it powers Safari…",
    "content": "Home of the WebKit project, the browser engine used by Safari, Mail, App Store and many other applications on macOS, iOS and Linux. WebKit WebKit is a cross-platform web browser engine. On iOS and macOS, it powers Safari, Mail, Apple Books, and many other appl…"
  },
  {
    "id": "技术-github javascript-https://github.com/pbakaus/impeccable",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "pbakaus/impeccable",
    "link": "https://github.com/pbakaus/impeccable",
    "pub_date": "",
    "author": "",
    "description": "The design language that makes your AI harness better at design. Impeccable Design guidance for AI coding agents. 1 skill, 23 commands, live browser iteration, and 46 deterministic detector rules for AI-generated fronten…",
    "content": "The design language that makes your AI harness better at design. Impeccable Design guidance for AI coding agents. 1 skill, 23 commands, live browser iteration, and 46 deterministic detector rules for AI-generated frontend design. Quick start: From your project…"
  },
  {
    "id": "技术-github javascript-https://github.com/microsoft/power-platform-skills",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "microsoft/power-platform-skills",
    "link": "https://github.com/microsoft/power-platform-skills",
    "pub_date": "",
    "author": "",
    "description": "A plugin marketplace for Claude Code/GitHub Copilot that provides Power Platform development plugins, including reusable skills, agents, and commands for building and deploying solutions. Power Platform Skills Official a…",
    "content": "A plugin marketplace for Claude Code/GitHub Copilot that provides Power Platform development plugins, including reusable skills, agents, and commands for building and deploying solutions. Power Platform Skills Official agent skills/plugins for Power Platform d…"
  },
  {
    "id": "技术-github javascript-https://github.com/poteto/hiring-without-whiteboards",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "poteto/hiring-without-whiteboards",
    "link": "https://github.com/poteto/hiring-without-whiteboards",
    "pub_date": "",
    "author": "",
    "description": "⭐️ Companies that don't have a broken hiring process Hiring Without Whiteboards A list of companies (or teams) that don't do \"whiteboard\" interviews. \"Whiteboards\" are used as a metaphor, and are a symbol for the kinds o…",
    "content": "⭐️ Companies that don't have a broken hiring process Hiring Without Whiteboards A list of companies (or teams) that don't do \"whiteboard\" interviews. \"Whiteboards\" are used as a metaphor, and are a symbol for the kinds of CS trivia questions that are associate…"
  },
  {
    "id": "技术-github javascript-https://github.com/coreyhaines31/marketingskills",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "coreyhaines31/marketingskills",
    "link": "https://github.com/coreyhaines31/marketingskills",
    "pub_date": "",
    "author": "",
    "description": "Marketing skills for Claude Code and AI agents. CRO, copywriting, SEO, analytics, and growth engineering. Marketing Skills for AI Agents A collection of AI agent skills focused on marketing tasks. Built for technical mar…",
    "content": "Marketing skills for Claude Code and AI agents. CRO, copywriting, SEO, analytics, and growth engineering. Marketing Skills for AI Agents A collection of AI agent skills focused on marketing tasks. Built for technical marketers and founders who want AI coding a…"
  },
  {
    "id": "技术-github javascript-https://github.com/wwebjs/whatsapp-web.js",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "wwebjs/whatsapp-web.js",
    "link": "https://github.com/wwebjs/whatsapp-web.js",
    "pub_date": "",
    "author": "",
    "description": "A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app About whatsapp‑web.js is a powerful Node.js library that lets you interact with WhatsApp Web, making it easy to build a dynamic What…",
    "content": "A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app About whatsapp‑web.js is a powerful Node.js library that lets you interact with WhatsApp Web, making it easy to build a dynamic WhatsApp API with nearly all features of the…"
  },
  {
    "id": "技术-github javascript-https://github.com/vercel/next.js",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "vercel/next.js",
    "link": "https://github.com/vercel/next.js",
    "pub_date": "",
    "author": "",
    "description": "The React Framework Next.js Getting Started Used by some of the world's largest companies, Next.js enables you to create full-stack web applications by extending the latest React features, and integrating powerful Rust-b…",
    "content": "The React Framework Next.js Getting Started Used by some of the world's largest companies, Next.js enables you to create full-stack web applications by extending the latest React features, and integrating powerful Rust-based JavaScript tooling for the fastest …"
  },
  {
    "id": "技术-github javascript-https://github.com/hmjz100/LinkSwift",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "hmjz100/LinkSwift",
    "link": "https://github.com/hmjz100/LinkSwift",
    "pub_date": "",
    "author": "",
    "description": "一个基于 JavaScript 的网盘文件下载地址获取工具。基于【网盘直链下载助手】修改 ，支持 百度网盘 / 阿里云盘 / 中国移动云盘 / 天翼云盘 / 迅雷云盘 / 夸克网盘 / UC网盘 / 123云盘 八大网盘 Important 如果您是从 GreasyFork 找到这的，建议前往下方的 安装 选择一个合适的源覆盖安装，避免因脚本失效或 GF 黑产刷子导致无法及时更新。 “出淤泥而不染，濯清涟而不妖” 搭配使用，效果更佳！\ud83d…",
    "content": "一个基于 JavaScript 的网盘文件下载地址获取工具。基于【网盘直链下载助手】修改 ，支持 百度网盘 / 阿里云盘 / 中国移动云盘 / 天翼云盘 / 迅雷云盘 / 夸克网盘 / UC网盘 / 123云盘 八大网盘 Important 如果您是从 GreasyFork 找到这的，建议前往下方的 安装 选择一个合适的源覆盖安装，避免因脚本失效或 GF 黑产刷子导致无法及时更新。 “出淤泥而不染，濯清涟而不妖” 搭配使用，效果更佳！👋扩展脚本 123 云盘会员青春版 | 百度网盘会员青春版 | 阿里云盘会员青春…"
  },
  {
    "id": "技术-github javascript-https://github.com/zarazhangrui/follow-builders",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "zarazhangrui/follow-builders",
    "link": "https://github.com/zarazhangrui/follow-builders",
    "pub_date": "",
    "author": "",
    "description": "AI builders digest — monitors top AI builders on X and YouTube podcasts, remixes their content into digestible summaries. Follow builders, not influencers. English | 中文 Follow Builders, Not Influencers An AI-powered dige…",
    "content": "AI builders digest — monitors top AI builders on X and YouTube podcasts, remixes their content into digestible summaries. Follow builders, not influencers. English | 中文 Follow Builders, Not Influencers An AI-powered digest that tracks the top builders in AI — …"
  },
  {
    "id": "技术-github javascript-https://github.com/bigskysoftware/htmx",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "bigskysoftware/htmx",
    "link": "https://github.com/bigskysoftware/htmx",
    "pub_date": "",
    "author": "",
    "description": "htmx - high power tools for HTML htmx\" title=\"high power tools for HTML\" /> high power tools for HTML introduction htmx allows you to access AJAX, CSS Transitions, WebSockets and Server Sent Events directly in HTML, usin…",
    "content": "htmx - high power tools for HTML htmx\" title=\"high power tools for HTML\" /> high power tools for HTML introduction htmx allows you to access AJAX , CSS Transitions , WebSockets and Server Sent Events directly in HTML, using attributes , so you can build modern…"
  },
  {
    "id": "技术-github javascript-https://github.com/thedotmack/claude-mem",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "thedotmack/claude-mem",
    "link": "https://github.com/thedotmack/claude-mem",
    "pub_date": "",
    "author": "",
    "description": "Persistent Context Across Sessions for Every Agent – Captures everything your agent does during sessions, compresses it with AI, and injects relevant context back into future sessions. Works with Claude Code, OpenClaw, C…",
    "content": "Persistent Context Across Sessions for Every Agent – Captures everything your agent does during sessions, compresses it with AI, and injects relevant context back into future sessions. Works with Claude Code, OpenClaw, Codex, Gemini, Hermes, Copilot, OpenCode …"
  },
  {
    "id": "技术-github javascript-https://github.com/advplyr/audiobookshelf",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "advplyr/audiobookshelf",
    "link": "https://github.com/advplyr/audiobookshelf",
    "pub_date": "",
    "author": "",
    "description": "Self-hosted audiobook and podcast server Documentation · Support · Demo About Audiobookshelf is a self-hosted audiobook and podcast server. Features Fully open-source, including the android & iOS app (in beta) Stream all…",
    "content": "Self-hosted audiobook and podcast server Documentation · Support · Demo About Audiobookshelf is a self-hosted audiobook and podcast server. Features Fully open-source , including the android &amp; iOS app (in beta) Stream all audio formats on the fly Search an…"
  },
  {
    "id": "技术-github javascript-https://github.com/atlassian/atlassian-mcp-server",
    "feed_name": "github javascript",
    "category": "技术",
    "title": "atlassian/atlassian-mcp-server",
    "link": "https://github.com/atlassian/atlassian-mcp-server",
    "pub_date": "",
    "author": "",
    "description": "Official remote MCP server for Atlassian. Securely connect Jira, Confluence, Jira Service Management, Bitbucket, and Compass to Claude, ChatGPT, Cursor, VS Code, and other AI tools using OAuth 2.1 or API tokens. Atlassia…",
    "content": "Official remote MCP server for Atlassian. Securely connect Jira, Confluence, Jira Service Management, Bitbucket, and Compass to Claude, ChatGPT, Cursor, VS Code, and other AI tools using OAuth 2.1 or API tokens. Atlassian Rovo MCP Server The official Model Con…"
  },
  {
    "id": "技术-github lua-https://github.com/neovim/nvim-lspconfig",
    "feed_name": "github lua",
    "category": "技术",
    "title": "neovim/nvim-lspconfig",
    "link": "https://github.com/neovim/nvim-lspconfig",
    "pub_date": "",
    "author": "",
    "description": "Quickstart configs for Nvim LSP nvim-lspconfig nvim-lspconfig is a collection of LSP server configurations for the Nvim LSP client. View all configs, or run :help lspconfig-all from Nvim. Important ⚠️ require('lspconfig'…",
    "content": "Quickstart configs for Nvim LSP nvim-lspconfig nvim-lspconfig is a collection of LSP server configurations for the Nvim LSP client . View all configs , or run :help lspconfig-all from Nvim. Important ⚠️ require('lspconfig') (the legacy \"framework\" of nvim-lspc…"
  },
  {
    "id": "技术-github lua-https://github.com/iDvel/rime-ice",
    "feed_name": "github lua",
    "category": "技术",
    "title": "iDvel/rime-ice",
    "link": "https://github.com/iDvel/rime-ice",
    "pub_date": "",
    "author": "",
    "description": "Rime 配置：雾凇拼音 | 长期维护的简体词库 雾凇拼音 雾凇拼音是一份开箱即用的简体中文 Rime 输入法配置，词库长期维护，基本功能齐全，使用完全离线，质量稳定可靠。 雾凇拼音包含全拼和双拼输入方案、长期维护的精校词库、各类扩展功能和详尽的注释。适配小狼毫 Weasel、鼠须管 Squirrel、Fcitx5、iBus 等几乎所有 Rime 应用。你可以不折腾，一键下载部署后即刻使用；可以借着完善的注释和社区生态，让 AI 帮你定…",
    "content": "Rime 配置：雾凇拼音 | 长期维护的简体词库 雾凇拼音 雾凇拼音 是一份开箱即用的简体中文 Rime 输入法配置，词库长期维护，基本功能齐全，使用完全离线，质量稳定可靠。 雾凇拼音包含全拼和双拼输入方案、长期维护的精校词库、各类扩展功能和详尽的注释。适配小狼毫 Weasel、鼠须管 Squirrel、Fcitx5、iBus 等几乎所有 Rime 应用。你可以不折腾，一键下载部署后即刻使用；可以借着完善的注释和社区生态，让 AI 帮你定制改造；也可以将之作为深入了解和自定义 Rime 的起点。 使用雾凇拼音，享受…"
  },
  {
    "id": "技术-github lua-https://github.com/bol-van/zapret-win-bundle",
    "feed_name": "github lua",
    "category": "技术",
    "title": "bol-van/zapret-win-bundle",
    "link": "https://github.com/bol-van/zapret-win-bundle",
    "pub_date": "",
    "author": "",
    "description": "zapret and blockcheck binary bundle for windows zapret winws bundle for windows main zapret1 repository main zapret2 repository requirements : Windows 7 x64, Windows server 2008 R2 (ESU updates or windivert files replace…",
    "content": "zapret and blockcheck binary bundle for windows zapret winws bundle for windows main zapret1 repository main zapret2 repository requirements : Windows 7 x64, Windows server 2008 R2 (ESU updates or windivert files replacement required) Windows 8+ x64, Windows s…"
  },
  {
    "id": "技术-github lua-https://github.com/koreader/koreader",
    "feed_name": "github lua",
    "category": "技术",
    "title": "koreader/koreader",
    "link": "https://github.com/koreader/koreader",
    "pub_date": "",
    "author": "",
    "description": "An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats, running on Cervantes, Kindle, Kobo, PocketBook and Android devices KOReader is a document viewer primarily aimed at e-ink readers. Downlo…",
    "content": "An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats, running on Cervantes, Kindle, Kobo, PocketBook and Android devices KOReader is a document viewer primarily aimed at e-ink readers. Download • User guide • Wiki • Developer docs …"
  },
  {
    "id": "技术-github lua-https://github.com/nvim-lua/kickstart.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "nvim-lua/kickstart.nvim",
    "link": "https://github.com/nvim-lua/kickstart.nvim",
    "pub_date": "",
    "author": "",
    "description": "A launch point for your personal nvim configuration kickstart.nvim Introduction A starting point for Neovim that is: Small Single-file Completely Documented NOT a Neovim distribution, but instead a starting point for you…",
    "content": "A launch point for your personal nvim configuration kickstart.nvim Introduction A starting point for Neovim that is: Small Single-file Completely Documented NOT a Neovim distribution, but instead a starting point for your configuration. Installation Install Ne…"
  },
  {
    "id": "技术-github lua-https://github.com/apache/apisix",
    "feed_name": "github lua",
    "category": "技术",
    "title": "apache/apisix",
    "link": "https://github.com/apache/apisix",
    "pub_date": "",
    "author": "",
    "description": "The Cloud-Native API Gateway and AI Gateway Apache APISIX API Gateway ｜ AI Gateway Apache APISIX is a dynamic, real-time, high-performance API Gateway. APISIX API Gateway provides rich traffic management features such as…",
    "content": "The Cloud-Native API Gateway and AI Gateway Apache APISIX API Gateway ｜ AI Gateway Apache APISIX is a dynamic, real-time, high-performance API Gateway. APISIX API Gateway provides rich traffic management features such as load balancing, dynamic upstream, canar…"
  },
  {
    "id": "技术-github lua-https://github.com/overextended/ox_inventory",
    "feed_name": "github lua",
    "category": "技术",
    "title": "overextended/ox_inventory",
    "link": "https://github.com/overextended/ox_inventory",
    "pub_date": "",
    "author": "",
    "description": "Slot-based inventory with metadata. ox_inventory A complete and modern inventory system for FiveM, providing a flexible slot-based inventory with support for shops, stashes, crafting, and vehicle storage. Refer to CONTRI…",
    "content": "Slot-based inventory with metadata. ox_inventory A complete and modern inventory system for FiveM, providing a flexible slot-based inventory with support for shops, stashes, crafting, and vehicle storage. Refer to CONTRIBUTING.md for contribution guidelines an…"
  },
  {
    "id": "技术-github lua-https://github.com/CorsixTH/CorsixTH",
    "feed_name": "github lua",
    "category": "技术",
    "title": "CorsixTH/CorsixTH",
    "link": "https://github.com/CorsixTH/CorsixTH",
    "pub_date": "",
    "author": "",
    "description": "Open source clone of Theme Hospital Latest Release Matrix Space | Matrix Chat | Discord | Report Issue | Reddit | Twitter/X | Facebook A reimplementation of the 1997 Bullfrog business sim Theme Hospital. As well as faith…",
    "content": "Open source clone of Theme Hospital Latest Release Matrix Space | Matrix Chat | Discord | Report Issue | Reddit | Twitter/X | Facebook A reimplementation of the 1997 Bullfrog business sim Theme Hospital. As well as faithfully recreating the original, CorsixTH …"
  },
  {
    "id": "技术-github lua-https://github.com/PathOfBuildingCommunity/PathOfBuilding",
    "feed_name": "github lua",
    "category": "技术",
    "title": "PathOfBuildingCommunity/PathOfBuilding",
    "link": "https://github.com/PathOfBuildingCommunity/PathOfBuilding",
    "pub_date": "",
    "author": "",
    "description": "Offline build planner for Path of Exile. Path of Building Community Welcome to Path of Building, an offline build planner for Path of Exile! Features Comprehensive offence + defence calculations: Calculate your skill DPS…",
    "content": "Offline build planner for Path of Exile. Path of Building Community Welcome to Path of Building, an offline build planner for Path of Exile! Features Comprehensive offence + defence calculations: Calculate your skill DPS, damage over time, life/mana/ES totals …"
  },
  {
    "id": "技术-github lua-https://github.com/hrsh7th/nvim-cmp",
    "feed_name": "github lua",
    "category": "技术",
    "title": "hrsh7th/nvim-cmp",
    "link": "https://github.com/hrsh7th/nvim-cmp",
    "pub_date": "",
    "author": "",
    "description": "A completion plugin for neovim coded in Lua. nvim-cmp A completion engine plugin for neovim written in Lua. Completion sources are installed from external repositories and \"sourced\". https://github.com/hrsh7th/nvim-cmp/a…",
    "content": "A completion plugin for neovim coded in Lua. nvim-cmp A completion engine plugin for neovim written in Lua. Completion sources are installed from external repositories and \"sourced\". https://github.com/hrsh7th/nvim-cmp/assets/22756295/afa70011-9121-4e42-aedd-0…"
  },
  {
    "id": "技术-github lua-https://github.com/id577/FS25_AdvancedDamageSystem",
    "feed_name": "github lua",
    "category": "技术",
    "title": "id577/FS25_AdvancedDamageSystem",
    "link": "https://github.com/id577/FS25_AdvancedDamageSystem",
    "pub_date": "",
    "author": "",
    "description": "Advanced Damage System mod for Farming Simulator 25 Important Support the Project Advanced Damage System is a passion project, and I’m doing my best to make it more realistic, stable, and enjoyable for the FS25 community…",
    "content": "Advanced Damage System mod for Farming Simulator 25 Important Support the Project Advanced Damage System is a passion project, and I’m doing my best to make it more realistic, stable, and enjoyable for the FS25 community. If you like the mod and want to suppor…"
  },
  {
    "id": "技术-github lua-https://github.com/Kong/kong",
    "feed_name": "github lua",
    "category": "技术",
    "title": "Kong/kong",
    "link": "https://github.com/Kong/kong",
    "pub_date": "",
    "author": "",
    "description": "🦍 The API and AI Gateway Kong or Kong Gateway is a cloud-native, platform-agnostic, scalable API 𖧹 LLM 𖧹 MCP Gateway distinguished for its high performance and extensibility via plugins. It also provides advanced AI t…",
    "content": "🦍 The API and AI Gateway Kong or Kong Gateway is a cloud-native, platform-agnostic, scalable API 𖧹 LLM 𖧹 MCP Gateway distinguished for its high performance and extensibility via plugins. It also provides advanced AI traffic capabilities with multi-LLM suppo…"
  },
  {
    "id": "技术-github lua-https://github.com/ibhagwan/fzf-lua",
    "feed_name": "github lua",
    "category": "技术",
    "title": "ibhagwan/fzf-lua",
    "link": "https://github.com/ibhagwan/fzf-lua",
    "pub_date": "",
    "author": "",
    "description": "Improved fzf.vim written in lua fzf ❤️ lua Quickstart • Installation • Usage • Commands • Customization • Wiki “because you can and you love fzf” - @junegunn \"fzf changed my command life, it can change yours too, if you …",
    "content": "Improved fzf.vim written in lua fzf ❤️ lua Quickstart • Installation • Usage • Commands • Customization • Wiki “because you can and you love fzf” - @junegunn \"fzf changed my command life, it can change yours too, if you allow it\" - @ibhagwan Quickstart To quic…"
  },
  {
    "id": "技术-github lua-https://github.com/opentibiabr/otclient",
    "feed_name": "github lua",
    "category": "技术",
    "title": "opentibiabr/otclient",
    "link": "https://github.com/opentibiabr/otclient",
    "pub_date": "",
    "author": "",
    "description": "An alternative tibia client for otserv written in C++20 and Lua, made with a modular system that uses lua scripts for ingame interface and functionality, making otclient flexible and easy to customize OTClient - Redempti…",
    "content": "An alternative tibia client for otserv written in C++20 and Lua, made with a modular system that uses lua scripts for ingame interface and functionality, making otclient flexible and easy to customize OTClient - Redemption 📋 Table of Contents What is OTClient…"
  },
  {
    "id": "技术-github lua-https://github.com/KristalTeam/Kristal",
    "feed_name": "github lua",
    "category": "技术",
    "title": "KristalTeam/Kristal",
    "link": "https://github.com/KristalTeam/Kristal",
    "pub_date": "",
    "author": "",
    "description": "Deltarune fangame engine for Love2D Kristal Kristal is a powerful DELTARUNE fangame and battle engine, made with LÖVE. It allows you to make custom DELTARUNE worlds, battles, and more! Warning Make sure to read the downl…",
    "content": "Deltarune fangame engine for Love2D Kristal Kristal is a powerful DELTARUNE fangame and battle engine, made with LÖVE . It allows you to make custom DELTARUNE worlds, battles, and more! Warning Make sure to read the downloading section of this README before at…"
  },
  {
    "id": "技术-github lua-https://github.com/olimorris/codecompanion.nvim",
    "feed_name": "github lua",
    "category": "技术",
    "title": "olimorris/codecompanion.nvim",
    "link": "https://github.com/olimorris/codecompanion.nvim",
    "pub_date": "",
    "author": "",
    "description": "✨ AI Coding, Vim Style A Neovim AI coding assistant for coding with LLMs (Anthropic, OpenAI, Gemini, Copilot and more) and AI agents. With built-in support for Agent Client Protocol (ACP), Model Context Protocol (MCP), a…",
    "content": "✨ AI Coding, Vim Style A Neovim AI coding assistant for coding with LLMs (Anthropic, OpenAI, Gemini, Copilot and more ) and AI agents. With built-in support for Agent Client Protocol (ACP) , Model Context Protocol (MCP) , and agents like Claude Code and Codex …"
  }
];

export default jsonData;
