const jsonData = [
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795412-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "hi168正式关闭，请尽快迁移数据，以免数据丢失！",
    "link": "https://www.nodeseek.com/post-795412-1",
    "pub_date": "2026-06-27 07:54:28",
    "author": "",
    "description": "为优化平台资源配置，本平台即日起将全面转型，聚焦对机构及企业客户业务，个人用户业务相关服务将于2026年6月28日正式关闭。请您在此之前尽快备份个人数据，并关注以下退款与关停安排。",
    "content": "为优化平台资源配置，本平台即日起将全面转型，聚焦对机构及企业客户业务，个人用户业务相关服务将于2026年6月28日正式关闭。请您在此之前尽快备份个人数据，并关注以下退款与关停安排。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795411-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "fable5真的快回来了吗？",
    "link": "https://www.nodeseek.com/post-795411-1",
    "pub_date": "2026-06-27 07:53:39",
    "author": "",
    "description": "据传这几天一直在谈判，也有说很快回来了，有没有确切消息。",
    "content": "据传这几天一直在谈判，也有说很快回来了，有没有确切消息。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795410-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "评价一下这个礼物",
    "link": "https://www.nodeseek.com/post-795410-1",
    "pub_date": "2026-06-27 07:49:51",
    "author": "",
    "description": "不玻璃心",
    "content": "不玻璃心"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795409-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "分享谷歌可注册的邮箱6位短字母ID第三弹，赚个🍗",
    "link": "https://www.nodeseek.com/post-795409-1",
    "pub_date": "2026-06-27 07:49:19",
    "author": "",
    "description": "有需要的下方自取，希望得到免费的鸡腿🍗🍗🍗一个插件已经验证过，均可注册或更改邮箱前缀（更改地址）想要插件的PM随意打赏点红包直接发给你，目前日跑20w无风控，注重个随心所欲不白嫖~~~列表里有几个比较好的，看谁眼尖、手速比较快了！拿走请留下鸡腿，谢谢AKKKWWAKKKXXBKKKMMBKKKNNBKKKPP",
    "content": "有需要的下方自取，希望得到免费的鸡腿🍗🍗🍗一个插件已经验证过，均可注册或更改邮箱前缀（更改地址）想要插件的PM随意打赏点红包直接发给你，目前日跑20w无风控，注重个随心所欲不白嫖~~~列表里有几个比较好的，看谁眼尖、手速比较快了！拿走请留下鸡腿，谢谢AKKKWWAKKKXXBKKKMMBKKKNNBKKKPP"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795408-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "之前从来没有球员做到过双金球+双欧冠+双世界杯",
    "link": "https://www.nodeseek.com/post-795408-1",
    "pub_date": "2026-06-27 07:48:44",
    "author": "",
    "description": "",
    "content": ""
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795407-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "bybit收15u，汇率6.9，要bybit内转",
    "link": "https://www.nodeseek.com/post-795407-1",
    "pub_date": "2026-06-27 07:44:58",
    "author": "",
    "description": "bybit收15u，汇率6.9，要bybit内转，支付宝口令",
    "content": "bybit收15u，汇率6.9，要bybit内转，支付宝口令"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795406-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "早上醒来，三台坠了",
    "link": "https://www.nodeseek.com/post-795406-1",
    "pub_date": "2026-06-27 07:41:59",
    "author": "",
    "description": "过于常态化了，无语了，看来还要加油多收点🐔了，备用能多一点",
    "content": "过于常态化了，无语了，看来还要加油多收点🐔了，备用能多一点"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795405-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "话说你们codex都用哪一个模式",
    "link": "https://www.nodeseek.com/post-795405-1",
    "pub_date": "2026-06-27 07:41:53",
    "author": "",
    "description": "以前都是开到超高，最近有一次打开默认选择中，发现用起来也没什么差别，但是额度消耗好像减少非常非常多，最近就一直用的中",
    "content": "以前都是开到超高，最近有一次打开默认选择中，发现用起来也没什么差别，但是额度消耗好像减少非常非常多，最近就一直用的中"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795404-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "210出Nobrand jp-4 6.18折扣",
    "link": "https://www.nodeseek.com/post-795404-1",
    "pub_date": "2026-06-27 07:38:39",
    "author": "",
    "description": "2c2g/4T流量4T流量重置费只要16元！！！同价格zouter只有1T官方push出附NQ硬件测试，网络上游是Skyline，论坛有很多测试了",
    "content": "2c2g/4T流量4T流量重置费只要16元！！！同价格zouter只有1T官方push出附NQ硬件测试，网络上游是Skyline，论坛有很多测试了"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795403-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "15r 出 wap.ac tw hinet 1 刀",
    "link": "https://www.nodeseek.com/post-795403-1",
    "pub_date": "2026-06-27 07:38:34",
    "author": "",
    "description": "带v4出口和独立v61刀月付到期2026-7-2515Rpush出",
    "content": "带v4出口和独立v61刀月付到期2026-7-2515Rpush出"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795401-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "请问vps服务商会更新机房硬件吗",
    "link": "https://www.nodeseek.com/post-795401-1",
    "pub_date": "2026-06-27 07:33:04",
    "author": "",
    "description": "厂商采购一批机器，不可能一直用下去吧？每隔几年，是不是就会升级下硬件？如果升级硬件，那现有用户是无痛升级呢，还是购买新套餐啊？大妈从an4升级an5，就是重新推出套餐噻？an4用户可以选择继续使用旧平台，或者升级到an5套餐？",
    "content": "厂商采购一批机器，不可能一直用下去吧？每隔几年，是不是就会升级下硬件？如果升级硬件，那现有用户是无痛升级呢，还是购买新套餐啊？大妈从an4升级an5，就是重新推出套餐噻？an4用户可以选择继续使用旧平台，或者升级到an5套餐？"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795399-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "GPT5.6 发布，但是用上还早",
    "link": "https://www.nodeseek.com/post-795399-1",
    "pub_date": "2026-06-27 07:29:30",
    "author": "",
    "description": "截至官方最新说明，GPT-5.6目前是limitedpreview（有限预览）：包括GPT-5.6Sol、Terra、Luna，只开放给一小部分受信任的合作伙伴和组织，通过OpenAIAPI和Codex使用；ChatGPT里暂时不能用GPT-5.6。OpenAI说计划在“未来几周”把它推广到ChatGPT、Code",
    "content": "截至官方最新说明，GPT-5.6目前是limitedpreview（有限预览）：包括GPT-5.6Sol、Terra、Luna，只开放给一小部分受信任的合作伙伴和组织，通过OpenAIAPI和Codex使用；ChatGPT里暂时不能用GPT-5.6。OpenAI说计划在“未来几周”把它推广到ChatGPT、Code"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795398-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "Chrome浏览器提示密码泄露",
    "link": "https://www.nodeseek.com/post-795398-1",
    "pub_date": "2026-06-27 07:28:19",
    "author": "",
    "description": "平常密码都使用的Chrome自带的密码管理器，近期频繁提示密码泄露，最开始没关注。这两天不小心点进去一看，所有密码全部泄露了连淘宝密码都给我干出去了，然后就是各种账号提示异国登陆还有什么类似的自动填充密码安全且本地的推荐吗",
    "content": "平常密码都使用的Chrome自带的密码管理器，近期频繁提示密码泄露，最开始没关注。这两天不小心点进去一看，所有密码全部泄露了连淘宝密码都给我干出去了，然后就是各种账号提示异国登陆还有什么类似的自动填充密码安全且本地的推荐吗"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795397-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "【车找人】Google AI plus 补2人",
    "link": "https://www.nodeseek.com/post-795397-1",
    "pub_date": "2026-06-27 07:10:22",
    "author": "",
    "description": "GoogleAIplus2T方案，美区家庭组，土区apple订阅,补2个，年付92。",
    "content": "GoogleAIplus2T方案，美区家庭组，土区apple订阅,补2个，年付92。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795396-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "大妈怎么还不补货",
    "link": "https://www.nodeseek.com/post-795396-1",
    "pub_date": "2026-06-27 07:04:43",
    "author": "",
    "description": "不是说马上补货吗，急急急，话说新ip段是不是能降低被q风险",
    "content": "不是说马上补货吗，急急急，话说新ip段是不是能降低被q风险"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223247#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 微信是否真的在实时监控用户的聊天？",
    "link": "https://www.v2ex.com/t/1223247#reply1",
    "pub_date": "2026-06-27 07:00:39",
    "author": "Alloyt",
    "description": "昨天北京发生的事情大家也应该知道，早上准备发视频给我朋友看，但是发现无法发送相关视频，微信是不是在实时监控用户的聊天记录？ https://imgur.com/a/FA3a8gi",
    "content": "昨天北京发生的事情大家也应该知道，早上准备发视频给我朋友看，但是发现无法发送相关视频，微信是不是在实时监控用户的聊天记录？ https://imgur.com/a/FA3a8gi"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795395-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "现在一个手机号可以同时注册两个微信账号",
    "link": "https://www.nodeseek.com/post-795395-1",
    "pub_date": "2026-06-27 07:00:18",
    "author": "",
    "description": "切换号码，添加账号，注册新账号，选择通过当前微信手机号辅助注册。",
    "content": "切换号码，添加账号，注册新账号，选择通过当前微信手机号辅助注册。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795394-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "DMIT69段EB Corona目前正常",
    "link": "https://www.nodeseek.com/post-795394-1",
    "pub_date": "2026-06-27 06:58:09",
    "author": "",
    "description": "",
    "content": ""
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795393-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "gpt邀請reset怎么沒了",
    "link": "https://www.nodeseek.com/post-795393-1",
    "pub_date": "2026-06-27 06:52:17",
    "author": "",
    "description": "當需要用gpt邀請reset的時候，發現沒了大家是這樣的嗎",
    "content": "當需要用gpt邀請reset的時候，發現沒了大家是這樣的嗎"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795392-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "DMIT炸了？",
    "link": "https://www.nodeseek.com/post-795392-1",
    "pub_date": "2026-06-27 06:51:27",
    "author": "",
    "description": "怎么我的corona上线离线仰卧起坐呢？甚至CPU还过载警告了",
    "content": "怎么我的corona上线离线仰卧起坐呢？甚至CPU还过载警告了"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-795390-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "有没有Claude拼车 人找车",
    "link": "https://www.nodeseek.com/post-795390-1",
    "pub_date": "2026-06-27 06:37:36",
    "author": "",
    "description": "有没有Claude拼车人找车",
    "content": "有没有Claude拼车人找车"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223245#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[投资] 接上篇，顺着钱流的方向看整个 AI 产业链",
    "link": "https://www.v2ex.com/t/1223245#reply1",
    "pub_date": "2026-06-27 06:33:00",
    "author": "totoismi",
    "description": "接上篇 \"矿工视角看现在的英伟达\" 钱都流到哪了，谁在赚？ 这篇就顺着这个问题，把 AI 产业链从下到上逐层拆开看。 结论挺反直觉的——这么大一个产业，目前真正在赚钱的，就只有最底层的芯片层。而且赚的还不是用户的钱，是各家巨头融来的、借来的、自己家底里掏出来的钱。 往上看： 基建层在烧钱。Google 母公司自由现金流一年从 733 亿跌到 82 亿，几乎全进了数据中心。一家印钞机被逼得要发债。 模型层在亏钱。OpenAI 年化营收 2…",
    "content": "接上篇 \"矿工视角看现在的英伟达\" 钱都流到哪了，谁在赚？ 这篇就顺着这个问题，把 AI 产业链从下到上逐层拆开看。 结论挺反直觉的——这么大一个产业，目前真正在赚钱的，就只有最底层的芯片层。而且赚的还不是用户的钱，是各家巨头融来的、借来的、自己家底里掏出来的钱。 往上看： 基建层在烧钱。Google 母公司自由现金流一年从 733 亿跌到 82 亿，几乎全进了数据中心。一家印钞机被逼得要发债。 模型层在亏钱。OpenAI 年化营收 200 亿，同年预计亏 140 亿。每收 1 块倒贴 7 毛。 应用层……还没长出…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223244#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 用 Node.js 写了个工业级 Modbus 协议栈，想听听大家的看法",
    "link": "https://www.v2ex.com/t/1223244#reply0",
    "pub_date": "2026-06-27 05:19:27",
    "author": "xiejay97",
    "description": "最近把一个压箱底的项目开源了：njs-modbus，一个零依赖、strict TypeScript 的 Node.js Modbus 协议栈，支持 TCP / RTU / ASCII / UDP / TLS 。 先上链接： GitHub： https://github.com/xiejay97/njs-modbus 深度介绍（中文版）：README.zh-CN.md 为什么又要造轮子？ 在 IIoT 边缘干了十多年，被各种 Modbus…",
    "content": "最近把一个压箱底的项目开源了： njs-modbus ，一个零依赖、strict TypeScript 的 Node.js Modbus 协议栈，支持 TCP / RTU / ASCII / UDP / TLS 。 先上链接： GitHub： https://github.com/xiejay97/njs-modbus 深度介绍（中文版）： README.zh-CN.md 为什么又要造轮子？ 在 IIoT 边缘干了十多年，被各种 Modbus 库坑惨了： GC 一抖，100 ms 轮询变 300 ms ，PLC 直…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223243#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] 一个 Senior Agent Engineer 应该是什么样子的。",
    "link": "https://www.v2ex.com/t/1223243#reply1",
    "pub_date": "2026-06-27 05:09:31",
    "author": "PhiloTech",
    "description": "如题，我很了解下，顶级的 AE 到底是什么画像，具备哪些能力呢。",
    "content": "如题，我很了解下，顶级的 AE 到底是什么画像，具备哪些能力呢。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223242#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] crossoverchina 和 codeweavers 有什么区别？",
    "link": "https://www.v2ex.com/t/1223242#reply5",
    "pub_date": "2026-06-27 03:37:50",
    "author": "LTuser",
    "description": "准备买台 mac mini 打游戏，发现 CrossOver 搜出来两个域名，价格差距还蛮离谱？盗版商？ codeweavers 中永久版 345.8 刀 crossoverchina 中永久版 188 人民币 看上去很有陷阱的样子？但如果破解版卖这个价格有点离谱。",
    "content": "准备买台 mac mini 打游戏，发现 CrossOver 搜出来两个域名，价格差距还蛮离谱？盗版商？ codeweavers 中永久版 345.8 刀 crossoverchina 中永久版 188 人民币 看上去很有陷阱的样子？但如果破解版卖这个价格有点离谱。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223241#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] Weft：一套可变架构的 AI 平台，每一层都能换（Rust + Flutter + WASM）",
    "link": "https://www.v2ex.com/t/1223241#reply0",
    "pub_date": "2026-06-27 02:46:58",
    "author": "ailiheizi",
    "description": "做了个开源的 AI 平台，叫 Weft 。核心想法是「可变架构」——前端界面、Agent 、工具、编排流，每一层都是可热插拔的 package ，Rust 写的 core 只管能力调度，不写死任何功能。 所以同一套底座，现在跑着几个完全不同的东西： 聊天 + 自动选工具（本地语义选择器，ONNX ，几毫秒挑出该用哪个工具） RSS 阅读器（划词翻译、划词问 AI 、按阅读偏好推荐） AI Director （把视频剪辑铺成一张 AI 自…",
    "content": "做了个开源的 AI 平台，叫 Weft 。核心想法是「可变架构」——前端界面、Agent 、工具、编排流，每一层都是可热插拔的 package ，Rust 写的 core 只管能力调度，不写死任何功能。 所以同一套底座，现在跑着几个完全不同的东西： 聊天 + 自动选工具（本地语义选择器，ONNX ，几毫秒挑出该用哪个工具） RSS 阅读器（划词翻译、划词问 AI 、按阅读偏好推荐） AI Director （把视频剪辑铺成一张 AI 自动生成的 DAG 画布） 代码助手 Weft Claw （自己选工具、写代码、跑…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223240#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Linux] Linux 上的游戏网络加速",
    "link": "https://www.v2ex.com/t/1223240#reply1",
    "pub_date": "2026-06-27 01:11:17",
    "author": "PeterTerpe",
    "description": "（ Fedora 44 ） 我遇到的问题 - UU 本来今年二月用的 UU 加速器的 steamdeck 插件没啥问题的，最近再启动发现用不了了，估计是插件和 Fedora 的更新终于不再兼容了，毕竟那玩意是给 steam OS 编译好的二进制。 刚开始排查问题的时候，发现开始加速之后有个叫 tun163 的虚拟网卡获得了最高默认优先级，过了几分钟之后这个网卡显示为 down ，但还是最高优先级，（导致）整个系统断网。这时的插件版本应该…",
    "content": "（ Fedora 44 ） 我遇到的问题 - UU 本来今年二月用的 UU 加速器的 steamdeck 插件没啥问题的，最近再启动发现用不了了，估计是插件和 Fedora 的更新终于不再兼容了，毕竟那玩意是给 steam OS 编译好的二进制。 刚开始排查问题的时候，发现开始加速之后有个叫 tun163 的虚拟网卡获得了最高默认优先级，过了几分钟之后这个网卡显示为 down ，但还是最高优先级，（导致）整个系统断网。这时的插件版本应该是 4 月份发布的 后来更新到了 6 月发布的版本，倒是不会整个系统断网了，但是…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223239#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 做了个工作室用的 AI 生图工具",
    "link": "https://www.v2ex.com/t/1223239#reply1",
    "pub_date": "2026-06-27 01:09:37",
    "author": "NEXTROAD",
    "description": "最近给工作室写了一个 AI 生图相关的小项目，叫 MuseCanvas 。 项目地址： https://github.com/nextroad-dev/MuseCanvas 一开始做它主要是因为工作室 AIGC 方向有一些实际需求。我们会用到 GPT-Image-2 之类的图像生成模型，但内网环境下代理不太稳定，经常容易被阻断；而且直接调用模型的话，生成质量也比较吃 Prompt ，效果不太稳定。 所以我想做一个简单的生图工作台，先把工…",
    "content": "最近给工作室写了一个 AI 生图相关的小项目，叫 MuseCanvas 。 项目地址： https://github.com/nextroad-dev/MuseCanvas 一开始做它主要是因为工作室 AIGC 方向有一些实际需求。我们会用到 GPT-Image-2 之类的图像生成模型，但内网环境下代理不太稳定，经常容易被阻断；而且直接调用模型的话，生成质量也比较吃 Prompt ，效果不太稳定。 所以我想做一个简单的生图工作台，先把工作室里常用的东西整合起来，而不是每次都临时拼接口、改脚本、手动整理结果。 目前主…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223237#reply4",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Reddit] 混 china_irl 的，给头像投个票把，否则这 logo 又成娘子了。。",
    "link": "https://www.v2ex.com/t/1223237#reply4",
    "pub_date": "2026-06-27 00:56:46",
    "author": "meyino",
    "description": "https://www.reddit.com/r/China_irl/comments/1udvw0w/2026_%E5%B9%B4_sub_%E5%A4%B4%E5%83%8F%E5%BE%81%E9%9B%86%E6%B4%BB%E5%8A%A8_%E7%AC%AC%E4%B8%80%E8%BD%AE%E6%8A%95%E7%A5%A8/ 要么投茶壶一票，有独立 ip 的各位大哥们，来投一个",
    "content": "https://www.reddit.com/r/China_irl/comments/1udvw0w/2026_%E5%B9%B4_sub_%E5%A4%B4%E5%83%8F%E5%BE%81%E9%9B%86%E6%B4%BB%E5%8A%A8_%E7%AC%AC%E4%B8%80%E8%BD%AE%E6%8A%95%E7%A5%A8/ 要么投茶壶一票，有独立 ip 的各位大哥们，来投一个"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16790#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "孩子们，我回来了",
    "link": "https://forum.archlinuxcn.org/t/topic/16790#post_2",
    "pub_date": "2026-06-27 00:56:32",
    "author": "",
    "description": "cachyos内核会不会更好？",
    "content": "cachyos内核会不会更好？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223236#reply7",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[VPS] 今年 6 月是怎么了，搬瓦工已经换了三次 IP 了",
    "link": "https://www.v2ex.com/t/1223236#reply7",
    "pub_date": "2026-06-27 00:19:21",
    "author": "kqz901002",
    "description": "Bandwagonhost Created: 2019-05-26",
    "content": "Bandwagonhost Created: 2019-05-26"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223235#reply2",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 分享一个自己做的去水印小工具 TinyErase",
    "link": "https://www.v2ex.com/t/1223235#reply2",
    "pub_date": "2026-06-27 00:17:41",
    "author": "wildworm",
    "description": "最近玩了一下 Nana Banana 生成图片，效果还不错，就是导出的图会带水印。 试了几个去水印的网站，功能能用，但广告太多，有些还要登录/付费，体验一般。 刚好最近 vibe coding 很火，我也想试试能不能快速做点小东西，于是花了两个小时做了个简单版： TinyErase.com - Free AI Watermark Remover 现在部署在 Cloudflare 上，主要就是去图片/视频水印。没做复杂功能，先给自己和朋友…",
    "content": "最近玩了一下 Nana Banana 生成图片，效果还不错，就是导出的图会带水印。 试了几个去水印的网站，功能能用，但广告太多，有些还要登录/付费，体验一般。 刚好最近 vibe coding 很火，我也想试试能不能快速做点小东西，于是花了两个小时做了个简单版： TinyErase.com - Free AI Watermark Remover 现在部署在 Cloudflare 上，主要就是去图片/视频水印。没做复杂功能，先给自己和朋友免费用。 大家如果刚好有类似需求，可以试试看。有问题或者建议欢迎反馈，我再慢慢改…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223234#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] Claude 新一轮大规模封号",
    "link": "https://www.v2ex.com/t/1223234#reply1",
    "pub_date": "2026-06-26 23:55:32",
    "author": "LonelyM",
    "description": "我的 Claude 今天被封号了，大家的还好吗？ 上一波 指控 DeepSeek 蒸馏，Claude 进行了大规模封号 这次指控阿里 Qwen 蒸馏，又来一波？？ 💔",
    "content": "我的 Claude 今天被封号了，大家的还好吗？ 上一波 指控 DeepSeek 蒸馏，Claude 进行了大规模封号 这次指控阿里 Qwen 蒸馏，又来一波？？ 💔"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223233#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[AI Agent 智能体] MatrixMedia：本地运行的多平台视频矩阵发布工具",
    "link": "https://www.v2ex.com/t/1223233#reply0",
    "pub_date": "2026-06-26 23:50:31",
    "author": "hanliang",
    "description": "MatrixMedia 是一款多平台视频矩阵发布工具，支持抖音、快手、B 站、百家号、头条、视频号、小红书共 7 个平台。 项目刚刚突破 100 Star ，顺手写了一篇介绍文章，记录了它的设计思路和使用方式。 核心解决的问题是多平台重复发布——同一条视频，以前要逐个平台手动上传，现在一次搞定。除了视频发布，也支持图文内容。 对 AI 工作流有需求的话，MatrixMedia 提供了 MCP 协议、CLI 和 HTTP API 三种调用…",
    "content": "MatrixMedia 是一款多平台视频矩阵发布工具，支持抖音、快手、B 站、百家号、头条、视频号、小红书共 7 个平台。 项目刚刚突破 100 Star ，顺手写了一篇介绍文章，记录了它的设计思路和使用方式。 核心解决的问题是多平台重复发布——同一条视频，以前要逐个平台手动上传，现在一次搞定。除了视频发布，也支持图文内容。 对 AI 工作流有需求的话，MatrixMedia 提供了 MCP 协议、CLI 和 HTTP API 三种调用方式，可以直接接入 Claude 、Cursor 等 AI Agent ，让自动…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223232#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[教育] 关于高考与教育的疑问",
    "link": "https://www.v2ex.com/t/1223232#reply3",
    "pub_date": "2026-06-26 23:45:23",
    "author": "kkcling",
    "description": "改开后高考恢复也已经快 50 年了，为什么高考试卷还不能全国统一，只用同一套卷子，本科线全国统一，感觉教育资源太不平均，山河四省的考生太苦了",
    "content": "改开后高考恢复也已经快 50 年了，为什么高考试卷还不能全国统一，只用同一套卷子，本科线全国统一，感觉教育资源太不平均，山河四省的考生太苦了"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223231#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] Agent 协作平台",
    "link": "https://www.v2ex.com/t/1223231#reply0",
    "pub_date": "2026-06-26 23:31:52",
    "author": "Roy3",
    "description": "https://mp.weixin.qq.com/s/grLVGDVBv0b56RIPRiWNMA",
    "content": "https://mp.weixin.qq.com/s/grLVGDVBv0b56RIPRiWNMA"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223230#reply8",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 今晚 3 个梯子炸了 2 个，发力了？",
    "link": "https://www.v2ex.com/t/1223230#reply8",
    "pub_date": "2026-06-26 23:13:33",
    "author": "maxwellz",
    "description": "买的一台 vps 中国全红，不会被墙了吧😭，别人搭的 dmit 也挂了，翻出来好久没用的机场才勉强连上来，而且很卡",
    "content": "买的一台 vps 中国全红，不会被墙了吧😭，别人搭的 dmit 也挂了，翻出来好久没用的机场才勉强连上来，而且很卡"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223229#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 国区上架 2 天， app 日活破 700 了🎉",
    "link": "https://www.v2ex.com/t/1223229#reply5",
    "pub_date": "2026-06-26 23:11:50",
    "author": "MagicCoder",
    "description": "我写的VirPulse从公测到现在差不多 6 天的时间，收获了 1212 个注册用户，昨天上架国区的，今天的日活已经 721 了，看来我的软件还是解决了一部分人的需求的☺️",
    "content": "我写的 VirPulse 从公测到现在差不多 6 天的时间，收获了 1212 个注册用户，昨天上架国区的，今天的日活已经 721 了，看来我的软件还是解决了一部分人的需求的☺️"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223226#reply8",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[OpenWrt] 2026 年，有没有啥，可以推荐刷 openwrt 的软路由",
    "link": "https://www.v2ex.com/t/1223226#reply8",
    "pub_date": "2026-06-26 22:45:12",
    "author": "sonnetbreeze",
    "description": "我现在 openwrt 一直部署在 Proxmox 上，也用了好几年，奈何有时候关机调试家里没网比较麻烦，想独立出来，需求很简单，最好 ImmortalWrt 官网有直接支持的，我直接 web 编译比较方便，软件包也就 passwall ，组网软件，iptv 软件，无须 wifi 功能。所以目前有啥可以推荐的，感激不尽。",
    "content": "我现在 openwrt 一直部署在 Proxmox 上，也用了好几年，奈何有时候关机调试家里没网比较麻烦，想独立出来，需求很简单，最好 ImmortalWrt 官网有直接支持的，我直接 web 编译比较方便，软件包也就 passwall ，组网软件，iptv 软件，无须 wifi 功能。所以目前有啥可以推荐的，感激不尽。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223225#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[macOS] codex 解决了困扰我很久的耳机问题",
    "link": "https://www.v2ex.com/t/1223225#reply1",
    "pub_date": "2026-06-26 22:45:10",
    "author": "mingoing428",
    "description": "耳机默认接管了声音输入,导致播放的声音效果差了很多",
    "content": "耳机默认接管了声音输入,导致播放的声音效果差了很多"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16804#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "kde如何使用核显",
    "link": "https://forum.archlinuxcn.org/t/topic/16804#post_2",
    "pub_date": "2026-06-26 22:41:20",
    "author": "",
    "description": "最简单的办法：把显示器接在核显的输出口上应该就可以了",
    "content": "最简单的办法：把显示器接在核显的输出口上应该就可以了"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223224#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 送懒猫微服中奖结果公布！",
    "link": "https://www.v2ex.com/t/1223224#reply0",
    "pub_date": "2026-06-26 22:37:34",
    "author": "CherryGods",
    "description": "送懒猫微服中奖结果公布！ 今晚直播中奖的用户是来自 nodeseek 的 LazyEase 老板 哈哈哈哈，这个 ID 和我们产品 LazyCat 还挺像的 我们下周五还有直播抽微服的活动 想要参与的老板看下这个链接： https://www.v2ex.com/t/1222480#reply0",
    "content": "送懒猫微服中奖结果公布！ 今晚直播中奖的用户是来自 nodeseek 的 LazyEase 老板 哈哈哈哈，这个 ID 和我们产品 LazyCat 还挺像的 我们下周五还有直播抽微服的活动 想要参与的老板看下这个链接： https://www.v2ex.com/t/1222480#reply0"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16804#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "kde如何使用核显",
    "link": "https://forum.archlinuxcn.org/t/topic/16804#post_1",
    "pub_date": "2026-06-26 22:36:31",
    "author": "",
    "description": "我想让kde使用核显运行，去网上找不到合适的教程，ai的方法也没有用",
    "content": "我想让kde使用核显运行，去网上找不到合适的教程，ai的方法也没有用 kde6,cachyos"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223223#reply6",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Claude] 今晚是怎么了？ Claude 注册一个封一个",
    "link": "https://www.v2ex.com/t/1223223#reply6",
    "pub_date": "2026-06-26 22:34:42",
    "author": "TaurusXin",
    "description": "连着 3 个邮箱 3 个账号都被封号，都是注册上去一句话没说，一个小时后就直接 suspended 了。 不知道 A\\在搞什么，有人碰到同样问题了吗？今天大量封号",
    "content": "连着 3 个邮箱 3 个账号都被封号，都是注册上去一句话没说，一个小时后就直接 suspended 了。 不知道 A\\在搞什么，有人碰到同样问题了吗？今天大量封号"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223222#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[人工智能] AI 怎么更好地处理 word 格式？",
    "link": "https://www.v2ex.com/t/1223222#reply0",
    "pub_date": "2026-06-26 22:34:35",
    "author": "hanssx",
    "description": "无论是 Claude ，还是 Codex ，都是用 python 或者 shell 来处理 word 的，不知为何有些格式会出错，比如 假设有一个任务，是复制 word 中的某个表格，或者复制某篇论文的封皮，那么复制出来的结果和原来的结果差别很大，基本上格式丢失了。 像这种问题怎么解决呢？",
    "content": "无论是 Claude ，还是 Codex ，都是用 python 或者 shell 来处理 word 的，不知为何有些格式会出错，比如 假设有一个任务，是复制 word 中的某个表格，或者复制某篇论文的封皮，那么复制出来的结果和原来的结果差别很大，基本上格式丢失了。 像这种问题怎么解决呢？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223219#reply9",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] dmit 线路出问题了？",
    "link": "https://www.v2ex.com/t/1223219#reply9",
    "pub_date": "2026-06-26 22:16:39",
    "author": "iron101",
    "description": "",
    "content": ""
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16802#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "VSR Player：基于 NVIDIA Video Effects SDK 的 Linux 实时超分视频播放器",
    "link": "https://forum.archlinuxcn.org/t/topic/16802#post_1",
    "pub_date": "2026-06-26 22:13:59",
    "author": "",
    "description": "一个直接调用 NVIDIA Video Effects SDK 的 Linux 桌面播放器，让 RTX 显卡的 AI 超分能力在 Linux 上可用。 项目地址：github.com/zhangmq/vsr-player 声明：本文及项目文档均由 AI 生成。文中可能包含过度热情的表达，不代表作者本人的精神状态。 背景 NVIDIA RTX Video Super Resolution（RTX VSR）在 Windows 上已经可用了一…",
    "content": "一个直接调用 NVIDIA Video Effects SDK 的 Linux 桌面播放器，让 RTX 显卡的 AI 超分能力在 Linux 上可用。 项目地址： github.com/zhangmq/vsr-player 声明：本文及项目文档均由 AI 生成。文中可能包含过度热情的表达，不代表作者本人的精神状态。 背景 NVIDIA RTX Video Super Resolution（RTX VSR）在 Windows 上已经可用了一段时间——通过驱动集成，浏览器（Edge、Chrome）和主流播放器（mpv、…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223218#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 鸣鹤 (MingHe) 最小化安全 SIP 语音通信服务器 — 纯 Rust 编写",
    "link": "https://www.v2ex.com/t/1223218#reply0",
    "pub_date": "2026-06-26 22:05:31",
    "author": "Facilis",
    "description": "替代语音电话的自建方案，没有诈骗和推销。 https://github.com/619dev/minghe 🔒 TLS 信令加密 — SIP over TLS (SIPS)，端口 5061 ，支持 TLS 1.2/1.3 🎵 SRTP 媒体加密 — AES_CM_128_HMAC_SHA1_80 ，SDES 密钥交换 🔑 SIP Digest 认证 — MD5 摘要认证，支持默认密码和分机独立密码 📡 RTP 媒体中继 — 服务…",
    "content": "替代语音电话的自建方案，没有诈骗和推销。 https://github.com/619dev/minghe 🔒 TLS 信令加密 — SIP over TLS (SIPS)，端口 5061 ，支持 TLS 1.2/1.3 🎵 SRTP 媒体加密 — AES_CM_128_HMAC_SHA1_80 ，SDES 密钥交换 🔑 SIP Digest 认证 — MD5 摘要认证，支持默认密码和分机独立密码 📡 RTP 媒体中继 — 服务器侧透明中继，地址学习，隐藏内部拓扑 📱 内部分机 — 1000–2000 号…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223217#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 最近看到很多人说 cursor 的 Composer 2.5 fast 很好用，是真的吗？",
    "link": "https://www.v2ex.com/t/1223217#reply5",
    "pub_date": "2026-06-26 22:04:30",
    "author": "yuan321",
    "description": "一般的开发好像说完全够用，不知道具体情况如何，有点担心改乱代码",
    "content": "一般的开发好像说完全够用，不知道具体情况如何，有点担心改乱代码"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223216#reply2",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 不用 Python 也能搞 AI Agent —— 一个纯 Go 实现的 SDK 和 Agent 平台",
    "link": "https://www.v2ex.com/t/1223216#reply2",
    "pub_date": "2026-06-26 21:58:49",
    "author": "Ifade",
    "description": "之前看到不少人说搞 AI Agent 绑定 Python ，想试试用 Go 能做到什么程度。 起因是 OpenAI 开源了 openai-agents-python，觉得设计挺好的，就拿当时刚出的 Claude Fable 5 一把梭把核心逻辑移植成了 Go 版本（后来 Fable 5 下线了，后续用 Claude Code 断断续续补完的）。 SDK 在这里：github.com/zzir/agents-go 移植完 SDK 之后顺手…",
    "content": "之前看到不少人说搞 AI Agent 绑定 Python ，想试试用 Go 能做到什么程度。 起因是 OpenAI 开源了 openai-agents-python ，觉得设计挺好的，就拿当时刚出的 Claude Fable 5 一把梭把核心逻辑移植成了 Go 版本（后来 Fable 5 下线了，后续用 Claude Code 断断续续补完的）。 SDK 在这里： github.com/zzir/agents-go 移植完 SDK 之后顺手写了个完整的 Web Demo ，算是验证 SDK 能不能真正跑起来： ag…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223215#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[OpenAI] AI 的生活减支： 家庭物体录入快速索引？",
    "link": "https://www.v2ex.com/t/1223215#reply1",
    "pub_date": "2026-06-26 21:35:05",
    "author": "jackenliu",
    "description": "每次搬家的时候，我都发现我买了太多的东西，总是记不住我东西，但要解决一些问题，例如修理加湿的时候不知道我家里的某些杂物是不是可以足够修理完成，我有没有买 502 、双面胶等等 这时候我要重新买了重复的东西去解决这样的问题 这样一来又费钱又费时间 我在想可以在大扫除的时候，把家里的所有物体都拍照录入到 AI 数据库修理，修理家私的时候直接问 AI 我家里的哪些物品和工具可以修理这个问题，这是不是很有用的功能？",
    "content": "每次搬家的时候，我都发现我买了太多的东西，总是记不住我东西，但要解决一些问题，例如修理加湿的时候不知道我家里的某些杂物是不是可以足够修理完成，我有没有买 502 、双面胶等等 这时候我要重新买了重复的东西去解决这样的问题 这样一来又费钱又费时间 我在想可以在大扫除的时候，把家里的所有物体都拍照录入到 AI 数据库修理，修理家私的时候直接问 AI 我家里的哪些物品和工具可以修理这个问题，这是不是很有用的功能？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223214#reply6",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 突然发现，很多蚊子飞行都没有声音了？",
    "link": "https://www.v2ex.com/t/1223214#reply6",
    "pub_date": "2026-06-26 21:27:12",
    "author": "tho",
    "description": "我记得之前蚊子飞到头周围都是有声音的， 怎么今年遇到的大部分蚊子都开了静音飞行模式，没声音啊？",
    "content": "我记得之前蚊子飞到头周围都是有声音的， 怎么今年遇到的大部分蚊子都开了静音飞行模式，没声音啊？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223213#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[全球工单系统] 关于美团 App 的“电话人工客服”和“网络在线客服”的问题！",
    "link": "https://www.v2ex.com/t/1223213#reply0",
    "pub_date": "2026-06-26 21:26:48",
    "author": "bclerdx",
    "description": "现在美团的人工在线客服，无论什么时间段拨打，都是人工客服繁忙，就是死活接不进去“活人”，让联系“网络在线客服”，网络在线客服也是“转接中...预计等待 X 分钟”，反正就是无限循环。这难道就是现在的美团资本的服务吗？",
    "content": "现在美团的人工在线客服，无论什么时间段拨打，都是人工客服繁忙，就是死活接不进去“活人”，让联系“网络在线客服”，网络在线客服也是“转接中...预计等待 X 分钟”，反正就是无限循环。这难道就是现在的美团资本的服务吗？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223211#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] 世界杯你买了吗？中了多少？赔了多少？交流经验",
    "link": "https://www.v2ex.com/t/1223211#reply5",
    "pub_date": "2026-06-26 21:02:16",
    "author": "rangoBen",
    "description": "",
    "content": ""
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223210#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[全球工单系统] 雷神加速器崩了",
    "link": "https://www.v2ex.com/t/1223210#reply3",
    "pub_date": "2026-06-26 20:55:05",
    "author": "MiMiGe",
    "description": "想换个 UU 或者奇游，哪个好点",
    "content": "想换个 UU 或者奇游，哪个好点"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223209#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] v2ex 网站右边的未读提醒上面的那个横线是做什么的",
    "link": "https://www.v2ex.com/t/1223209#reply5",
    "pub_date": "2026-06-26 20:48:05",
    "author": "cpalead",
    "description": "一会颜色是灰色，一会是绿色，一会是黄色，是做什么用的，没明白，问 ai 也答不出来",
    "content": "一会颜色是灰色，一会是绿色，一会是黄色，是做什么用的，没明白，问 ai 也答不出来"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223208#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Claude] 用了 4 个月的 Claude 今天被 suspended",
    "link": "https://www.v2ex.com/t/1223208#reply5",
    "pub_date": "2026-06-26 20:43:05",
    "author": "yibin001",
    "description": "用了 4 个月相安无事，今天也是很平常的一天。 一个小时前连续收到三封内容完全一样的邮件： Hello, An internal investigation of suspicious signals associated with your account indicates you may be in violation of our Supported Countries Policy. As a result, we have …",
    "content": "用了 4 个月相安无事，今天也是很平常的一天。 一个小时前连续收到三封内容完全一样的邮件： Hello, An internal investigation of suspicious signals associated with your account indicates you may be in violation of our Supported Countries Policy. As a result, we have revoked your access to Claude. To appeal…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223206#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] 把自己的 Android 手机，接入 Phones Cloud",
    "link": "https://www.v2ex.com/t/1223206#reply1",
    "pub_date": "2026-06-26 20:26:52",
    "author": "openerx",
    "description": "把自己的 Android 手机，接入 Phones Cloud ，变成可远程访问的自有云设备。 Phones Cloud 自注册设备功能目前正在内测中。现在支持在 Android 手机上安装设备端 APK ，登录账号并添加本机后，就可以在 Web 控制台或 iOS 客户端远程使用这台手机。 内测期间，自注册设备可以一直免费续期使用。到期后可在设备续费入口领取免费续期，继续使用远控和设备管理能力。 适合这些场景： 备用 Android 手…",
    "content": "把自己的 Android 手机，接入 Phones Cloud ，变成可远程访问的自有云设备。 Phones Cloud 自注册设备功能目前正在内测中。现在支持在 Android 手机上安装设备端 APK ，登录账号并添加本机后，就可以在 Web 控制台或 iOS 客户端远程使用这台手机。 内测期间，自注册设备可以一直免费续期使用。到期后可在设备续费入口领取免费续期，继续使用远控和设备管理能力。 适合这些场景： 备用 Android 手机远程管理 移动应用测试 多账号环境隔离 团队共享自有设备 出门不带手机，也能远…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223205#reply2",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 现在很多技术活，是不是已经开始被 AI 吃掉一部分了？",
    "link": "https://www.v2ex.com/t/1223205#reply2",
    "pub_date": "2026-06-26 20:24:12",
    "author": "fgghyyfk",
    "description": "最近自己用 Claude / Codex 做内部工具，感触越来越明显。 以前很多我一定会排给技术同事的活，现在会先让 AI 搓一版。 比如一个后台页面、一个数据导入导出、一个小报表、一个简单手机端页面、一些测试和文案调整。 不是说 AI 做得多完美。 但很多内部工具，本来目标也不是“代码多漂亮”，而是先能跑、能验证、能把重复活压下去。 我以前写过几年代码，后来创业做跨境，这些年更多是在公司里哪儿漏补哪儿。站在我这种半技术老板的角度看，这…",
    "content": "最近自己用 Claude / Codex 做内部工具，感触越来越明显。 以前很多我一定会排给技术同事的活，现在会先让 AI 搓一版。 比如一个后台页面、一个数据导入导出、一个小报表、一个简单手机端页面、一些测试和文案调整。 不是说 AI 做得多完美。 但很多内部工具，本来目标也不是“代码多漂亮”，而是先能跑、能验证、能把重复活压下去。 我以前写过几年代码，后来创业做跨境，这些年更多是在公司里哪儿漏补哪儿。站在我这种半技术老板的角度看，这件事其实挺明显： 前端、测试、设计、客户端，甚至一部分后端的执行型工作，肯定会被…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223204#reply11",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[电动汽车] 国产车企在卷什么？",
    "link": "https://www.v2ex.com/t/1223204#reply11",
    "pub_date": "2026-06-26 20:09:58",
    "author": "SmartNeo",
    "description": "今天看了一篇文章，讲到国产车企的内卷式竞争，说得十分悲壮。 可我完全没有任何同情的感觉，说实话看看现在的汽车，我都不知道他们在那里卷什么。 三十万算是豪车的分界线，那么我们现在三十万能买到外观好看安全耐用做工精致用料良心驾乘舒适的车吗？恐怕不能。 首先说外观，三十万的车大概只有小米 SU7 的外观能让人眼前一亮，其它那些都是什么玩意儿，照着抄都抄不会。 其次说安全，个个都说自己在碰撞测试中能拿到全优成绩，但电池起火却没一个能彻底解决的，…",
    "content": "今天看了一篇文章，讲到国产车企的内卷式竞争，说得十分悲壮。 可我完全没有任何同情的感觉，说实话看看现在的汽车，我都不知道他们在那里卷什么。 三十万算是豪车的分界线，那么我们现在三十万能买到外观好看安全耐用做工精致用料良心驾乘舒适的车吗？恐怕不能。 首先说外观，三十万的车大概只有小米 SU7 的外观能让人眼前一亮，其它那些都是什么玩意儿，照着抄都抄不会。 其次说安全，个个都说自己在碰撞测试中能拿到全优成绩，但电池起火却没一个能彻底解决的，天天在那里吹那个傻逼辅助驾驶。 耐用，这个要求不用说了，个个都是只给首任车主终身…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16801#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "在 Plymouth 输入密码时启用数字键盘",
    "link": "https://forum.archlinuxcn.org/t/topic/16801#post_1",
    "pub_date": "2026-06-26 19:49:42",
    "author": "",
    "description": "nicolasyang's blog https://blog.nicolasyang.me/posts/turn-on-numpad-for-plymouth-password-prompt/ - Linux 在启动时会把键盘的 numlock 状态重置为关闭，这让全键盘用户在输入 luks 密码，或者在 tty 控制台登录时很麻烦，总是要按一下 numlock. 在 tty 上其实可以通过 setleds +num 来打开 numl…",
    "content": "nicolasyang's blog https://blog.nicolasyang.me/posts/turn-on-numpad-for-plymouth-password-prompt/ - Linux 在启动时会把键盘的 numlock 状态重置为关闭，这让全键盘用户在输入 luks 密码，或者在 tty 控制台登录时很麻烦，总是要按一下 numlock. 在 tty 上其实可以通过 setleds +num 来打开 numlock, 但现在 linux 在启动过程中要从 simpledrmfb 切换到显…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/15547#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "QQ在Hyprland 下无法输入中文",
    "link": "https://forum.archlinuxcn.org/t/topic/15547#post_5",
    "pub_date": "2026-06-26 19:49:26",
    "author": "",
    "description": "需要设置哪些环境变量？",
    "content": "需要设置哪些环境变量？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223203#reply15",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Claude] 从模型蒸馏想到， AI 模型的护城河可能并不深",
    "link": "https://www.v2ex.com/t/1223203#reply15",
    "pub_date": "2026-06-26 19:46:53",
    "author": "GeorgeV",
    "description": "经常看到某家 AI 公司在公开场合上蹿下跳、各种举报投诉中国公司蒸馏了自己家的模型，由此想到可能目前 AI （即使是闭源）模型的护城河其实并不深。若属实，可能很快就会看到目前这种 AI 狂热的泡沫破裂时刻。",
    "content": "经常看到某家 AI 公司在公开场合上蹿下跳、各种举报投诉中国公司蒸馏了自己家的模型，由此想到可能目前 AI （即使是闭源）模型的护城河其实并不深。若属实，可能很快就会看到目前这种 AI 狂热的泡沫破裂时刻。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223202#reply6",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 坐标成都，孩子小升初，大家有提前安排学奥数去考试的吗？",
    "link": "https://www.v2ex.com/t/1223202#reply6",
    "pub_date": "2026-06-26 19:37:07",
    "author": "Pzdmultiverse",
    "description": "子坐标天府新区，有没有这样的伙伴，或者正在经历、准备干这个的伙伴，交流交流啊",
    "content": "子坐标天府新区，有没有这样的伙伴，或者正在经历、准备干这个的伙伴，交流交流啊"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223201#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 我给 codex 做了一个外挂知识库--codex-brain",
    "link": "https://www.v2ex.com/t/1223201#reply3",
    "pub_date": "2026-06-26 19:24:54",
    "author": "yinshaojun96",
    "description": "先把地址放上，开源地址： https://github.com/yinshaojun001/projectbrain 最近做了一个小工具叫 Project Brain ，MVP 阶段，想发出来听听大家意见。 起因挺现实的：组里有同学要离职，我不得不接手一些支付相关的活儿，第一个需求就是在抖音支付的原有代码上做一整套流程修改。 接手之后才发现，真正麻烦的不是代码本身，而是代码背后的上下文。支付流程怎么走的、哪段代码对应哪份文档、某个字段为…",
    "content": "先把地址放上，开源地址： https://github.com/yinshaojun001/projectbrain 最近做了一个小工具叫 Project Brain ，MVP 阶段，想发出来听听大家意见。 起因挺现实的：组里有同学要离职，我不得不接手一些支付相关的活儿，第一个需求就是在抖音支付的原有代码上做一整套流程修改。 接手之后才发现，真正麻烦的不是代码本身，而是代码背后的上下文。支付流程怎么走的、哪段代码对应哪份文档、某个字段为什么要这么传、历史上踩过哪些坑、改一个地方会不会牵连回调和退款链路……这些东西散…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223200#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 现在外包签的都是劳务合同？",
    "link": "https://www.v2ex.com/t/1223200#reply0",
    "pub_date": "2026-06-26 19:21:08",
    "author": "hubayi",
    "description": "坐标杭州，某国企外包，由于国企在 2025 年未招标，直到 2026 年才招标，原来一个标能分两个包给两家单位，现在不允许了，一家单位中标后，私下转钱给另外一家单位。没错，我就在这家倒霉的未中标的外包公司。 所以导致我一年半了只拿到国企的预付款的 30%，我盘算着 2025 年的 70%要等到明年的 2 月份左右，想想还是得把钱要回来，不能再等了，必须劳动仲裁，8 月开庭。 国企得知后，部门领导认为我把邮件记录提交给仲裁委是泄密，要我撤…",
    "content": "坐标杭州，某国企外包，由于国企在 2025 年未招标，直到 2026 年才招标，原来一个标能分两个包给两家单位，现在不允许了，一家单位中标后，私下转钱给另外一家单位。没错，我就在这家倒霉的未中标的外包公司。 所以导致我一年半了只拿到国企的预付款的 30%，我盘算着 2025 年的 70%要等到明年的 2 月份左右，想想还是得把钱要回来，不能再等了，必须劳动仲裁，8 月开庭。 国企得知后，部门领导认为我把邮件记录提交给仲裁委是泄密，要我撤诉，我肯定不答应。四方坐下来协商，说 7 月会把 2025 年剩下的钱给我，但今…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223199#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 征集一起投诉和起诉小米",
    "link": "https://www.v2ex.com/t/1223199#reply1",
    "pub_date": "2026-06-26 19:14:48",
    "author": "liuxyon",
    "description": "征集一起投诉和起诉小米 小米手机质量太差，售后更差，付费更换屏幕花了近 1200 一年多，售后不给维修. 屏幕绿线是硬件质量问题. .谁有小米类似问题,可以联系我,我打算投诉和起诉.我们一起干。。",
    "content": "征集一起投诉和起诉小米 小米手机质量太差，售后更差，付费更换屏幕花了近 1200 一年多，售后不给维修. 屏幕绿线是硬件质量问题. .谁有小米类似问题,可以联系我,我打算投诉和起诉.我们一起干。。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223198#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] 香港办公 / 远程 | 智能合约工程师（SUI 链 DEX · ve3,3）",
    "link": "https://www.v2ex.com/t/1223198#reply0",
    "pub_date": "2026-06-26 18:58:45",
    "author": "784801530",
    "description": "Momentum 是基于 SUI 区块链的 ve(3,3) DEX ，由安全的多签托管钱包 MSafe 演变而来。项目由前 Meta Libra 工程师创立，已获得 Coinbase Ventures 、Circle Ventures 、Sui Foundation 等顶级机构超过 1000 万美元的投资 岗位职责： 1 。负责 Momentum Dex 核心智能合约的设计与开发，包括 CLMM 、ve3,3 模型、流动性激励、投票市场…",
    "content": "Momentum 是基于 SUI 区块链的 ve(3,3) DEX ，由安全的多签托管钱包 MSafe 演变而来。项目由前 Meta Libra 工程师创立，已获得 Coinbase Ventures 、Circle Ventures 、Sui Foundation 等顶级机构超过 1000 万美元的投资 岗位职责： 1 。负责 Momentum Dex 核心智能合约的设计与开发，包括 CLMM 、ve3,3 模型、流动性激励、投票市场等模块； 2 。使用 Move 语言开发 SUI 链上的 DeFi 协议，理解并…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223196#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Mac mini] 现有的 m4 mac mini 应该卖多少钱合适",
    "link": "https://www.v2ex.com/t/1223196#reply0",
    "pub_date": "2026-06-26 18:53:33",
    "author": "ycyppq123",
    "description": "手里有一个 m4 mac mini 16+256g 前段时间二手好像是 3700 现在 Mac 都涨价了 不知道卖多少合适",
    "content": "手里有一个 m4 mac mini 16+256g 前段时间二手好像是 3700 现在 Mac 都涨价了 不知道卖多少合适"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223195#reply4",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 基于 MLX Vibe 了一个本地翻译工具， AI 做上架真是方便",
    "link": "https://www.v2ex.com/t/1223195#reply4",
    "pub_date": "2026-06-26 18:47:24",
    "author": "Rand01ph",
    "description": "自从 AI 用得多了，读英文的频率反而高了不少，是不是冒点英文我觉得也挺好。之前一直靠 PopClip 配个本地词典凑合，查单词够用，但整句、长句就差点意思。后来用了几次 AI 翻译，效果是真好；又赶上 WWDC26 看到 MLX ，我就动了个念头：能不能干脆在本地跑个小模型做翻译？翻译这活儿对参数量要求没那么高，正合适。于是就让 AI 开干了。 模型挑了 Google 的 Gemma 4 （ 4-bit ），框架用 MLX-Swift…",
    "content": "自从 AI 用得多了，读英文的频率反而高了不少，是不是冒点英文我觉得也挺好。之前一直靠 PopClip 配个本地词典凑合，查单词够用，但整句、长句就差点意思。后来用了几次 AI 翻译，效果是真好；又赶上 WWDC26 看到 MLX ，我就动了个念头：能不能干脆在本地跑个小模型做翻译？翻译这活儿对参数量要求没那么高，正合适。于是就让 AI 开干了。 模型挑了 Google 的 Gemma 4 （ 4-bit ），框架用 MLX-Swift ，在我那台 16G 的 MacBook Air M2 上跑得动。做成了菜单栏 …"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223192#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 进群领取福利 10 刀体验（扣扣群： 537777741）地址 https://www.eirouter.com",
    "link": "https://www.v2ex.com/t/1223192#reply0",
    "pub_date": "2026-06-26 18:37:26",
    "author": "yanwei19892000",
    "description": "国内直连国际模型 API ，主要痛点：网络不通，自建代理不稳定官方按美元计费，充值麻烦多模型切换要维护多个 key 随着 AI API 的使用场景越来越多，个人开发者、团队测试和企业项目对接口服务的要求也越来越高。大家不只是需要一个能调用的接口，更需要稳定的响应、清晰的价格、顺手的接入体验，以及可以长期使用的服务。 进群报 ID 领取 10🔪体验 充值有优惠 另外我们承若已充值客户未使用完额度或者用户本身原因想要退会余额可以随时联系管…",
    "content": "国内直连国际模型 API ，主要痛点：网络不通，自建代理不稳定官方按美元计费，充值麻烦多模型切换要维护多个 key 随着 AI API 的使用场景越来越多，个人开发者、团队测试和企业项目对接口服务的要求也越来越高。大家不只是需要一个能调用的接口，更需要稳定的响应、清晰的价格、顺手的接入体验，以及可以长期使用的服务。 进群报 ID 领取 10🔪体验 充值有优惠 另外我们承若已充值客户未使用完额度或者用户本身原因想要退会余额可以随时联系管理员退款 来去自由 祝贺大家每天开心快乐"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223191#reply10",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 新开的一家中转站, codetoken.uk",
    "link": "https://www.v2ex.com/t/1223191#reply10",
    "pub_date": "2026-06-26 18:32:54",
    "author": "crazyu",
    "description": "gpt 可以给专属的折扣 0.15 以管方价格计价 欢迎大家使用以及提点建议，新人刚做，请大家留情，多提点好的建议，🙏 希望大家都能工作顺利，生活美满，买彩票都中一等奖",
    "content": "gpt 可以给专属的折扣 0.15 以管方价格计价 欢迎大家使用以及提点建议，新人刚做，请大家留情，多提点好的建议，🙏 希望大家都能工作顺利，生活美满，买彩票都中一等奖"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223190#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 完了完了又续费了，付费上班第二年",
    "link": "https://www.v2ex.com/t/1223190#reply1",
    "pub_date": "2026-06-26 18:29:59",
    "author": "left7410",
    "description": "染上 Token 了，这辈子完了。 https://imgur.com/a/1zHfAlM https://imgur.com/a/vIV5g4m",
    "content": "染上 Token 了，这辈子完了。 https://imgur.com/a/1zHfAlM https://imgur.com/a/vIV5g4m"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223189#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[路由器] 想在路由器上跑 Mihomo，配置文件里 \"auto-route\" 和 \"auto-redirect\" 有什么区别？",
    "link": "https://www.v2ex.com/t/1223189#reply1",
    "pub_date": "2026-06-26 18:27:25",
    "author": "ciaoSora",
    "description": "我不是很懂计算机网络和路由器，想请教下大佬们。我想在路由器里面跑 Mihomo ，以实现任何设备连了 Wi-Fi 后不需任何配置即可科学上网。在 Mihomo 的文档里看到有这两个选项，有几个问题想不通： 关于 auto-route 选项，文档里写道“自动设置全局路由，可以自动将全局流量路由进入 tun 网卡”。什么情况下这个选项会是 false 呢？我都新建了一个虚拟网卡了，不就是想让流量都走这个虚拟网卡吗？如果设置为 false 的…",
    "content": "我不是很懂计算机网络和路由器，想请教下大佬们。我想在路由器里面跑 Mihomo ，以实现任何设备连了 Wi-Fi 后不需任何配置即可科学上网。在 Mihomo 的 文档 里看到有这两个选项，有几个问题想不通： 关于 auto-route 选项，文档里写道“自动设置全局路由，可以自动将全局流量路由进入 tun 网卡”。什么情况下这个选项会是 false 呢？我都新建了一个虚拟网卡了，不就是想让流量都走这个虚拟网卡吗？如果设置为 false 的话，意思是光新建一个虚拟网卡，然后什么都不干？ 关于 auto-redire…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223188#reply4",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[宽带症候群] 上海电信小黑屋问题，重新注销宽带在安装，还存在限速吗。",
    "link": "https://www.v2ex.com/t/1223188#reply4",
    "pub_date": "2026-06-26 18:24:25",
    "author": "sonnetbreeze",
    "description": "前景提要： https://www.v2ex.com/t/1221645?p=1#reply4 https://www.v2ex.com/t/1215412?p=1#reply22 https://www.v2ex.com/t/1212528?p=1#reply6 https://www.v2ex.com/t/1211613?p=1#reply52 副宽带，昨天将限速问题投诉工信部，第二天有人打电话，我问他们有没有限速，他们说不清楚，也…",
    "content": "前景提要： https://www.v2ex.com/t/1221645?p=1#reply4 https://www.v2ex.com/t/1215412?p=1#reply22 https://www.v2ex.com/t/1212528?p=1#reply6 https://www.v2ex.com/t/1211613?p=1#reply52 副宽带，昨天将限速问题投诉工信部，第二天有人打电话，我问他们有没有限速，他们说不清楚，也不承认，对方只说我是负责工信部投诉的，给你解决方案，师傅上门测试，我说你们有测速…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1223187#reply8",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 统计一下，有多少人因为 ai 赚钱了",
    "link": "https://www.v2ex.com/t/1223187#reply8",
    "pub_date": "2026-06-26 18:21:36",
    "author": "Monkeypox",
    "description": "看到苹果涨价，有所感触，感觉 ai 确实能提高生产力，但又有多少人通过 ai 赚钱了，互联网公司开始裁员，硬件价格上涨，好多时候还要自己买 token ，工资却没上涨，是我赚钱思维不够活吗。想统计一下有多少佬通过 ai 赚钱了。",
    "content": "看到苹果涨价，有所感触，感觉 ai 确实能提高生产力，但又有多少人通过 ai 赚钱了，互联网公司开始裁员，硬件价格上涨，好多时候还要自己买 token ，工资却没上涨，是我赚钱思维不够活吗。想统计一下有多少佬通过 ai 赚钱了。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16777#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "对于 Vim 语言服务器（LSP）类插件的选择和比较",
    "link": "https://forum.archlinuxcn.org/t/topic/16777#post_5",
    "pub_date": "2026-06-26 16:59:34",
    "author": "",
    "description": "这个似乎不错哦，先用这个叭",
    "content": "这个似乎不错哦，先用这个叭"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16795#post_8",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "无法找到或读取软件包",
    "link": "https://forum.archlinuxcn.org/t/topic/16795#post_8",
    "pub_date": "2026-06-26 15:16:00",
    "author": "",
    "description": "如果本来就不使用它的ocr功能，那随便敲一个 1 最省事（",
    "content": "如果本来就不使用它的ocr功能，那随便敲一个 1 最省事（"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_2",
    "pub_date": "2026-06-26 11:57:02",
    "author": "",
    "description": "没有原始报错信息、也没有包名……",
    "content": "没有原始报错信息、也没有包名……"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_1",
    "pub_date": "2026-06-26 10:37:55",
    "author": "",
    "description": "key更新过，sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com root@pedrohlc.com” 未改变 -> 已本地签名 1 把密钥。 ==> 正在更新可信数据库...",
    "content": "key更新过，sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com gpg: 密钥 3056513887B78AEB：“Pedro Henrique Lara Campos root@pedrohlc.com ” 未改变 gpg: 处理的总数：1 gpg: 未改变：1 ❯ sudo pacman-key --lsign-key 3056513887B78AEB -&gt; 已本地签名 1 把密钥。 ==&gt; 正在…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16795#post_7",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "无法找到或读取软件包",
    "link": "https://forum.archlinuxcn.org/t/topic/16795#post_7",
    "pub_date": "2026-06-26 09:04:22",
    "author": "",
    "description": "应该用--debug选项来看问题所在。 tesseract是spectacle的新依赖。你选个-eng或者-chi-sim的数据包就好了。",
    "content": "应该用 --debug 选项来看问题所在。 tesseract是spectacle的新依赖。你选个-eng或者-chi-sim的数据包就好了。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16795#post_6",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "无法找到或读取软件包",
    "link": "https://forum.archlinuxcn.org/t/topic/16795#post_6",
    "pub_date": "2026-06-25 23:41:49",
    "author": "",
    "description": "无法读取软件包这种情况是在图里这个软件仓库extra出现之后发生的，不知为何出现了“128个软件仓库可提供tessdata”，之后就一直更新失败了。",
    "content": "无法读取软件包这种情况是在图里这个软件仓库extra出现之后发生的，不知为何出现了“128个软件仓库可提供tessdata”，之后就一直更新失败了。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16795#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "无法找到或读取软件包",
    "link": "https://forum.archlinuxcn.org/t/topic/16795#post_5",
    "pub_date": "2026-06-25 23:27:36",
    "author": "",
    "description": "yay",
    "content": "yay"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16727#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "文件系统选择求助",
    "link": "https://forum.archlinuxcn.org/t/topic/16727#post_5",
    "pub_date": "2026-06-25 22:15:18",
    "author": "",
    "description": "最近刚开始尝试这个文件系统。稳定是肯定稳定的，只要别启用官方文档里面明确说不稳定的功能",
    "content": "最近刚开始尝试这个文件系统。稳定是肯定稳定的，只要别启用官方文档里面明确说不稳定的功能"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16795#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "无法找到或读取软件包",
    "link": "https://forum.archlinuxcn.org/t/topic/16795#post_4",
    "pub_date": "2026-06-25 21:08:56",
    "author": "",
    "description": "对了，你用的是pacman还是其他的东西（AUR helper之类）？",
    "content": "对了，你用的是pacman还是其他的东西（AUR helper之类）？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16795#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "无法找到或读取软件包",
    "link": "https://forum.archlinuxcn.org/t/topic/16795#post_3",
    "pub_date": "2026-06-25 21:08:26",
    "author": "",
    "description": "pacman -Syu --verbose 试试？",
    "content": "pacman -Syu --verbose 试试？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16795#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "无法找到或读取软件包",
    "link": "https://forum.archlinuxcn.org/t/topic/16795#post_2",
    "pub_date": "2026-06-25 20:53:37",
    "author": "",
    "description": "wiki.archlinuxcn.org 安装时无法获取软件包 - pacman - Arch Linux 中文维基 错误内容包含：Not found in sync db, Target not found 或 Failed retrieving file.",
    "content": "wiki.archlinuxcn.org 安装时无法获取软件包 - pacman - Arch Linux 中文维基 错误内容包含：Not found in sync db, Target not found 或 Failed retrieving file."
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16624#post_6",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "用niri的是小男娘吗",
    "link": "https://forum.archlinuxcn.org/t/topic/16624#post_6",
    "pub_date": "2026-06-25 20:48:05",
    "author": "",
    "description": "冯·诺伊曼派更加稳重，超然脱俗，不愿与世俗有太多勾结，只想安心古法手搓程序。 以上内容纯属胡编乱造，如有雷同那说明我们两同样逆天（",
    "content": "冯·诺伊曼派更加稳重，超然脱俗，不愿与世俗有太多勾结，只想安心古法手搓程序。 图灵派更加奔放，乐于展示自己，常与他人发生交互。 以上内容纯属胡编乱造，如有雷同那说明我们两同样逆天（"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16795#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "无法找到或读取软件包",
    "link": "https://forum.archlinuxcn.org/t/topic/16795#post_1",
    "pub_date": "2026-06-25 20:00:09",
    "author": "",
    "description": "如图，请问这个问题如何解决呢，已经持续一周了。每天都在正常滚动更新。",
    "content": "如图，请问这个问题如何解决呢，已经持续一周了。每天都在正常滚动更新。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16624#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "用niri的是小男娘吗",
    "link": "https://forum.archlinuxcn.org/t/topic/16624#post_5",
    "pub_date": "2026-06-25 18:30:23",
    "author": "",
    "description": "也许快了，也许慢了，也许永远都到达不了 没有官方统计数据，并且 新生代 Geek 和 xnn & 新技术的重合度一直很高说是 Rust forever",
    "content": "也许快了，也许慢了，也许永远都到达不了 没有官方统计数据，并且 新生代 Geek 和 xnn &amp; 新技术的重合度一直很高说是 Rust forever"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16287#post_10",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "fcitx5在wayland下的chromium, electron等软件输入偶发漏字问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16287#post_10",
    "pub_date": "2026-06-25 16:56:49",
    "author": "",
    "description": "之前我也遇到过vscode终端中会出现漏字的情况，我当时的解决方法是在fcitx5全局设置中 勾选 *在程序中显示预编辑文本。*似乎现在这个问题已经得到了修复？现在取消勾选后也能在终端中正常输入",
    "content": "之前我也遇到过vscode终端中会出现漏字的情况，我当时的解决方法是在fcitx5全局设置中 勾选 *在程序中显示预编辑文本。*似乎现在这个问题已经得到了修复？现在取消勾选后也能在终端中正常输入"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16791#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "archinstall选择中文乱码的问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16791#post_2",
    "pub_date": "2026-06-25 14:14:45",
    "author": "",
    "description": "不是乱码，而是 Linux 内核 console 没有中文字体，导致只能渲染成豆腐块。 没有很好的解决办法，任何办法都需要联网下载安装某些文件，比如使用 cage -d -s -- foot -f \"Hack,Noto Sans Mono CJK SC\"，这也需要你在运行它之前手动完成联网、换源、扩容 rootfs 尺寸、安装 cage、foot 和所需字体这些步骤。因此可能还不如直接用英文方便",
    "content": "不是乱码，而是 Linux 内核 console 没有中文字体，导致只能渲染成豆腐块。 没有很好的解决办法，任何办法都需要联网下载安装某些文件，比如使用 cage -d -s -- foot -f \"Hack,Noto Sans Mono CJK SC\" ，这也需要你在运行它之前手动完成联网、换源、 扩容 rootfs 尺寸 、安装 cage、foot 和所需字体这些步骤。因此可能还不如直接用英文方便"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16791#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "archinstall选择中文乱码的问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16791#post_1",
    "pub_date": "2026-06-25 14:05:32",
    "author": "",
    "description": "有了这个选项，应该是很好的事，但会显示乱码，无法使用，有什么好的解决方案吗？",
    "content": "有了这个选项，应该是很好的事，但会显示乱码，无法使用，有什么好的解决方案吗？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/15547#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "QQ在Hyprland 下无法输入中文",
    "link": "https://forum.archlinuxcn.org/t/topic/15547#post_4",
    "pub_date": "2026-06-25 13:49:28",
    "author": "",
    "description": "hyprland只设置环境变量就能直接用的。也不用在QQ目录设置。WPS,微信更没问题了。",
    "content": "hyprland只设置环境变量就能直接用的。也不用在QQ目录设置。WPS,微信更没问题了。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16598#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "fcitx5在非wayland程序，输入框会大一圈，这是为什么？",
    "link": "https://forum.archlinuxcn.org/t/topic/16598#post_4",
    "pub_date": "2026-06-25 11:58:40",
    "author": "",
    "description": "同样疑问，实际上wechat倒是反而缩小了一圈",
    "content": "同样疑问，实际上wechat倒是反而缩小了一圈"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16790#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "孩子们，我回来了",
    "link": "https://forum.archlinuxcn.org/t/topic/16790#post_1",
    "pub_date": "2026-06-25 10:06:19",
    "author": "",
    "description": "考完试也是成功拥有了一个X64的ArchLinux",
    "content": "考完试也是成功拥有了一个X64的ArchLinux"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/15934#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助] Fcitx5 托盘图标显示异常",
    "link": "https://forum.archlinuxcn.org/t/topic/15934#post_4",
    "pub_date": "2026-06-25 09:28:58",
    "author": "",
    "description": "*可能相关 Busyo's Blog – 6 Oct 25 niri 疑难解答 niri 是一款比较新颖的滚动平铺窗口管理器，这也意味着在使用的过程中会产生一些问题",
    "content": "*可能相关 Busyo's Blog – 6 Oct 25 niri 疑难解答 niri 是一款比较新颖的滚动平铺窗口管理器，这也意味着在使用的过程中会产生一些问题"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16777#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "对于 Vim 语言服务器（LSP）类插件的选择和比较",
    "link": "https://forum.archlinuxcn.org/t/topic/16777#post_4",
    "pub_date": "2026-06-24 15:46:08",
    "author": "",
    "description": "可以试试 yegappan/lsp.",
    "content": "可以试试 yegappan/lsp ."
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16438#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "新人，能不能看看大家的hyprland 桌面",
    "link": "https://forum.archlinuxcn.org/t/topic/16438#post_3",
    "pub_date": "2026-06-24 15:15:17",
    "author": "",
    "description": "hyprland能有什么桌面？方便使用的话是加个waybar，waybar仓库里有例子可以参考。",
    "content": "hyprland能有什么桌面？方便使用的话是加个waybar，waybar仓库里有例子可以参考。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16598#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "fcitx5在非wayland程序，输入框会大一圈，这是为什么？",
    "link": "https://forum.archlinuxcn.org/t/topic/16598#post_3",
    "pub_date": "2026-06-24 15:09:26",
    "author": "",
    "description": "steam是GTK_IM_MODULE=xim所以字母也在框内。wechat /tg不会的。hyprland配置里不用添加gtk的了吧。",
    "content": "steam是GTK_IM_MODULE=xim 所以字母也在框内。wechat /tg不会的。hyprland配置里不用添加gtk的了吧。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16777#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "对于 Vim 语言服务器（LSP）类插件的选择和比较",
    "link": "https://forum.archlinuxcn.org/t/topic/16777#post_3",
    "pub_date": "2026-06-24 09:43:56",
    "author": "",
    "description": "我用lazyvim自带的就有, 不用自己特意配置.",
    "content": "我用lazyvim自带的就有, 不用自己特意配置."
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/10500#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "AUR里的lunar-calendar+lunar-date能用吗？",
    "link": "https://forum.archlinuxcn.org/t/topic/10500#post_4",
    "pub_date": "2026-06-24 09:43:00",
    "author": "",
    "description": "试试这个？ extensions.gnome.org Chinese Calendar - GNOME Shell Extensions",
    "content": "试试这个？ extensions.gnome.org Chinese Calendar - GNOME Shell Extensions"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16745#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "腾讯会议 linux 版本 nvidia 支持问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16745#post_3",
    "pub_date": "2026-06-24 09:11:08",
    "author": "",
    "description": "感谢，这个问题我解决了，你这个评论很关键，我在 aur 社区也看到了，看名字一样，都是你，感谢！ 你说 在单nvidia显卡环境下未测试 然后我测试了可行。最终我的方案我写成了一个 md 文档， at https://git.940304.xyz/dk/textfiles/src/branch/main/titanplus/机械革命泰钽plus-Debian-Wayland-独显直连-调优全记录.md",
    "content": "感谢，这个问题我解决了，你这个评论很关键，我在 aur 社区也看到了，看名字一样，都是你，感谢！ 你说 在单nvidia显卡环境下未测试 然后我测试了可行。最终我的方案我写成了一个 md 文档， at https://git.940304.xyz/dk/textfiles/src/branch/main/titanplus/机械革命泰钽plus-Debian-Wayland-独显直连-调优全记录.md"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16773#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "更新系统后，外接显示器竖屏显示异常",
    "link": "https://forum.archlinuxcn.org/t/topic/16773#post_3",
    "pub_date": "2026-06-24 03:13:07",
    "author": "",
    "description": "一样出现了，竖屏显示颠倒了",
    "content": "一样出现了，竖屏显示颠倒了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16776#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Claude/最近火起来了",
    "link": "https://forum.archlinuxcn.org/t/topic/16776#post_4",
    "pub_date": "2026-06-23 15:55:25",
    "author": "",
    "description": "已封禁。",
    "content": "已封禁。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16776#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Claude/最近火起来了",
    "link": "https://forum.archlinuxcn.org/t/topic/16776#post_3",
    "pub_date": "2026-06-23 15:52:44",
    "author": "",
    "description": "怎么成为VIP会员，我要发贴置顶",
    "content": "怎么成为VIP会员，我要发贴置顶"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16576?page=2#post_26",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "搓了一个中国农历gnome-shell 时钟日历插件",
    "link": "https://forum.archlinuxcn.org/t/topic/16576?page=2#post_26",
    "pub_date": "2026-06-23 15:42:04",
    "author": "",
    "description": "搞定了",
    "content": "搞定了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16779#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "腾讯会议在 Plasma 6.7 Wayland 下共享桌面时画面上下翻转",
    "link": "https://forum.archlinuxcn.org/t/topic/16779#post_1",
    "pub_date": "2026-06-23 14:40:20",
    "author": "",
    "description": "22 号之前使用腾讯会议还可以正常的共享桌面，但是昨天更新了 plasma 之后共享视频就出现了这个问题，此外我使用 obs 进行屏幕捕获得到的视频是正常的",
    "content": "22 号之前使用腾讯会议还可以正常的共享桌面，但是昨天更新了 plasma 之后共享视频就出现了这个问题，此外我使用 obs 进行屏幕捕获得到的视频是正常的"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16576?page=2#post_25",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "搓了一个中国农历gnome-shell 时钟日历插件",
    "link": "https://forum.archlinuxcn.org/t/topic/16576?page=2#post_25",
    "pub_date": "2026-06-23 14:07:34",
    "author": "",
    "description": "@zqs 可以了，github 发布了， gnome extensions 网站也审核通过了。",
    "content": "@zqs 可以了，github 发布了， gnome extensions 网站也审核通过了。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16576?page=2#post_24",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "搓了一个中国农历gnome-shell 时钟日历插件",
    "link": "https://forum.archlinuxcn.org/t/topic/16576?page=2#post_24",
    "pub_date": "2026-06-23 11:18:14",
    "author": "",
    "description": "不过有一点需要注意，这里的年干支切换，是按照春节的，不是立春节气的。遵循了大部分日常农历的操作。",
    "content": "不过有一点需要注意，这里的年干支切换，是按照春节的，不是立春节气的。遵循了大部分日常农历的操作。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16576?page=2#post_23",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "搓了一个中国农历gnome-shell 时钟日历插件",
    "link": "https://forum.archlinuxcn.org/t/topic/16576?page=2#post_23",
    "pub_date": "2026-06-23 11:16:25",
    "author": "",
    "description": "效果图， 这两天会在 1.4 版本中发布，github 能先发， gnome extensions 网站会同步申请。",
    "content": "效果图， 这两天会在 1.4 版本中发布，github 能先发， gnome extensions 网站会同步申请。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16576?page=2#post_22",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "搓了一个中国农历gnome-shell 时钟日历插件",
    "link": "https://forum.archlinuxcn.org/t/topic/16576?page=2#post_22",
    "pub_date": "2026-06-23 10:38:25",
    "author": "",
    "description": "需要删除重新安装吗",
    "content": "需要删除重新安装吗"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16576?page=2#post_21",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "搓了一个中国农历gnome-shell 时钟日历插件",
    "link": "https://forum.archlinuxcn.org/t/topic/16576?page=2#post_21",
    "pub_date": "2026-06-23 10:37:20",
    "author": "",
    "description": "我的为什么没有干支历？",
    "content": "我的为什么没有干支历？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16777#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "对于 Vim 语言服务器（LSP）类插件的选择和比较",
    "link": "https://forum.archlinuxcn.org/t/topic/16777#post_2",
    "pub_date": "2026-06-23 10:17:57",
    "author": "",
    "description": "我用ALE来调用linter。我不太用LSP，只配置了coc-rust，但也很少用。",
    "content": "我用ALE来调用linter。我不太用LSP，只配置了coc-rust，但也很少用。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16778#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "最近开机有时候扫不到一个可用wifi,重启后才可以，谁知道为啥",
    "link": "https://forum.archlinuxcn.org/t/topic/16778#post_1",
    "pub_date": "2026-06-23 07:08:16",
    "author": "",
    "description": "journalctl -b -1 -p3 6月 23 06:46:31 archlinux kernel: Bluetooth: hci0: No support for _PRR ACPI method 6月 23 06:46:37 archlinux kernel: iwlwifi 0000:04:00.0: Microcode SW error detected. Restarting 0x0. 6月 23 06:46:37 ar…",
    "content": "journalctl -b -1 -p3 6月 23 06:46:31 archlinux kernel: Bluetooth: hci0: No support for _PRR ACPI method 6月 23 06:46:37 archlinux kernel: iwlwifi 0000:04:00.0: Microcode SW error detected. Restarting 0x0. 6月 23 06:46:37 archlinux kernel: iwlwifi 0000:04:00.0: St…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16777#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "对于 Vim 语言服务器（LSP）类插件的选择和比较",
    "link": "https://forum.archlinuxcn.org/t/topic/16777#post_1",
    "pub_date": "2026-06-23 01:24:15",
    "author": "",
    "description": "我有对自动补全和提示这种功能的需求，但是我看有好多这种功能的 Vim 插件：YCM，vim-language-server，ALE和coc。暂时用的是 ALE ，但是最近发现 ALE 时不时会很卡（调整了配置也还是这样）故想着换掉，想来问问大家推荐哪个插件来用",
    "content": "我有对自动补全和提示这种功能的需求，但是我看有好多这种功能的 Vim 插件： YCM ， vim-language-server ， ALE 和 coc 。暂时用的是 ALE ，但是最近发现 ALE 时不时会很卡（调整了配置也还是这样）故想着换掉，想来问问大家推荐哪个插件来用"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16576#post_20",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "搓了一个中国农历gnome-shell 时钟日历插件",
    "link": "https://forum.archlinuxcn.org/t/topic/16576#post_20",
    "pub_date": "2026-06-22 20:09:43",
    "author": "",
    "description": "太好了，功能比较齐全",
    "content": "太好了，功能比较齐全"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16776#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Claude/最近火起来了",
    "link": "https://forum.archlinuxcn.org/t/topic/16776#post_2",
    "pub_date": "2026-06-22 19:50:36",
    "author": "",
    "description": "千问竟然没干掉你…… 不要在技术版块发送无关的内容，更不要乱打标签，不然我要手动封禁你了。",
    "content": "千问竟然没干掉你…… 不要在技术版块发送无关的内容，更不要乱打标签，不然我要手动封禁你了。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16776#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Claude/最近火起来了",
    "link": "https://forum.archlinuxcn.org/t/topic/16776#post_1",
    "pub_date": "2026-06-22 19:46:11",
    "author": "",
    "description": "我最近用的Claude很火，已经不在乎他的生产力领先，而是在最为普通的对话交流需求上，被越来越多的人用到。",
    "content": "我最近用的Claude很火，已经不在乎他的生产力领先，而是在最为普通的对话交流需求上，被越来越多的人用到。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/13464?page=2#post_35",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "linuxqq无法使用输入法",
    "link": "https://forum.archlinuxcn.org/t/topic/13464?page=2#post_35",
    "pub_date": "2026-06-22 18:08:25",
    "author": "",
    "description": "谢谢我哥",
    "content": "谢谢我哥"
  }
];

export default jsonData;
