const jsonData = [
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802095-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "有没有出富婆HGC229/299的,溢价好说",
    "link": "https://www.nodeseek.com/post-802095-1",
    "pub_date": "2026-07-01 17:30:16",
    "author": "",
    "description": "过去198天了还没收到太想拥有了",
    "content": "过去198天了还没收到太想拥有了"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802094-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "cloudafra买的光帆",
    "link": "https://www.nodeseek.com/post-802094-1",
    "pub_date": "2026-07-01 17:29:59",
    "author": "",
    "description": "怎么更换IP",
    "content": "怎么更换IP"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802093-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "锐驰现在Q的麻了,被jc大军蹬烂了吗",
    "link": "https://www.nodeseek.com/post-802093-1",
    "pub_date": "2026-07-01 17:28:36",
    "author": "",
    "description": "开机20G就开始qqq大白天也q",
    "content": "开机20G就开始qqq大白天也q"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802092-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "论坛邮箱",
    "link": "https://www.nodeseek.com/post-802092-1",
    "pub_date": "2026-07-01 17:27:44",
    "author": "",
    "description": "大佬们交易走论坛邮箱是怎么操作啊，没找到咋操作的",
    "content": "大佬们交易走论坛邮箱是怎么操作啊，没找到咋操作的"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802091-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "请教下aws光帆速度问题",
    "link": "https://www.nodeseek.com/post-802091-1",
    "pub_date": "2026-07-01 17:26:14",
    "author": "",
    "description": "下午刚注册了aws并开启了光帆的日本东京实例，使用的vless，延迟很不错40ms左右，可是用wifi的话延迟很好就是速度拉跨（打开油管加载很快就是播放速度卡的要死）。而使用蜂窝的话速度又很快。后来我试了下用hy2，wifi下速度马上就飙升了。这个原因是不是运营商的qos限制导致的？",
    "content": "下午刚注册了aws并开启了光帆的日本东京实例，使用的vless，延迟很不错40ms左右，可是用wifi的话延迟很好就是速度拉跨（打开油管加载很快就是播放速度卡的要死）。而使用蜂窝的话速度又很快。后来我试了下用hy2，wifi下速度马上就飙升了。这个原因是不是运营商的qos限制导致的？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224280#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 有没有便宜或者免费用 grok 的方法",
    "link": "https://www.v2ex.com/t/1224280#reply0",
    "pub_date": "2026-07-01 17:26:08",
    "author": "wuwuta170",
    "description": "如题 现在官方充值的话 有 5 刀，10 刀，20 刀几个选项 但国内没法充，问了网上，说是找代充，但代充只能充 super grok ， 一充就是几十刀，只能是会员那种",
    "content": "如题 现在官方充值的话 有 5 刀，10 刀，20 刀几个选项 但国内没法充，问了网上，说是找代充，但代充只能充 super grok ， 一充就是几十刀，只能是会员那种"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802090-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "bybit第一次注册",
    "link": "https://www.nodeseek.com/post-802090-1",
    "pub_date": "2026-07-01 17:23:57",
    "author": "",
    "description": "1、具体注册选的地区有没有什么讲究？2、bybit是什么卡都能申到吗？最近讨论的eu卡，是一个账户可以申请很多地区的卡头吗？3、邀请码的作用，填别人邀请码有什么好处吗？4、wise虚拟卡和bybit有什么区别？",
    "content": "1、具体注册选的地区有没有什么讲究？2、bybit是什么卡都能申到吗？最近讨论的eu卡，是一个账户可以申请很多地区的卡头吗？3、邀请码的作用，填别人邀请码有什么好处吗？4、wise虚拟卡和bybit有什么区别？"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802089-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "【闲聊】绿云 SG Gen2",
    "link": "https://www.nodeseek.com/post-802089-1",
    "pub_date": "2026-07-01 17:22:56",
    "author": "",
    "description": "前段时间第一次用绿云，买了CNPremiumOptimizedPlanMini(Singapore)然后忘记开机了想着赶紧开机用刚装好系统，IP是被ban的，说实话第一次遇到。他家经常这样吗？",
    "content": "前段时间第一次用绿云，买了CNPremiumOptimizedPlanMini(Singapore)然后忘记开机了想着赶紧开机用刚装好系统，IP是被ban的，说实话第一次遇到。他家经常这样吗？"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802088-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "各位18cm，请问Instagram登录位置怎么总跳国内？",
    "link": "https://www.nodeseek.com/post-802088-1",
    "pub_date": "2026-07-01 17:22:45",
    "author": "",
    "description": "我用sk5落地，用美国或者香港中转过去，电脑v2打开了tun也会跳到国内ip",
    "content": "我用sk5落地，用美国或者香港中转过去，电脑v2打开了tun也会跳到国内ip"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802087-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "特价出几个GV短信号 可以短信保号 邮箱支持更改别名",
    "link": "https://www.nodeseek.com/post-802087-1",
    "pub_date": "2026-07-01 17:22:43",
    "author": "",
    "description": "(252)368-8999(707)336-2888(773)819-9666‬(352)559-9333(956)335-522270R/个售后说明：当天首次登录正常即视为交付完成。不保证任何平台注册及用途结果，请自行测试。",
    "content": "(252)368-8999(707)336-2888(773)819-9666‬(352)559-9333(956)335-522270R/个售后说明：当天首次登录正常即视为交付完成。不保证任何平台注册及用途结果，请自行测试。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224279#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] 用技术聚集人才，共同成长｜(株)GSD 东京 it 本社 2026 年度多岗位扩招中！",
    "link": "https://www.v2ex.com/t/1224279#reply0",
    "pub_date": "2026-07-01 17:22:28",
    "author": "GSDgsd",
    "description": "今天这篇文章，是想重新认真介绍一下我们公司——株式会社 GSD ，以及我们目前在招的岗位。不管您是人在国内想赴日，还是已经在日想转职，都欢迎往下看。 关于 GSD 株式会社 GSD 成立于 2015 年，总部位于东京都文京区。以软件开发、委托开发及互联网服务为核心业务，在金融（银行/证券/保险）、商业、物流等领域深耕多年，积累了大量企业级项目经验。 公司官网： https://www.g-s-d.co.jp/ 目前开放的岗位有以下几类，…",
    "content": "今天这篇文章，是想重新认真介绍一下我们公司——株式会社 GSD ，以及我们目前在招的岗位。不管您是人在国内想赴日，还是已经在日想转职，都欢迎往下看。 关于 GSD 株式会社 GSD 成立于 2015 年，总部位于东京都文京区。以软件开发、委托开发及互联网服务为核心业务，在金融（银行/证券/保险）、商业、物流等领域深耕多年，积累了大量企业级项目经验。 公司官网： https://www.g-s-d.co.jp/ 目前开放的岗位有以下几类，大家可以对照自己的情况看看： [ AI 开发工程师] AI 是我们今年重点发力的…"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802086-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "被骗了 Apple one，曝光一下",
    "link": "https://www.nodeseek.com/post-802086-1",
    "pub_date": "2026-07-01 17:22:02",
    "author": "",
    "description": "昨天拼的车，今天就把我踢出来了，我还没捂热呢，完全联系不上，长记性了!大家避雷！image",
    "content": "昨天拼的车，今天就把我踢出来了，我还没捂热呢，完全联系不上，长记性了!大家避雷！image"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224277#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 做了个虚拟信用卡平台，方便可以直接从官方订阅 Claude 和 OpenAI 了",
    "link": "https://www.v2ex.com/t/1224277#reply0",
    "pub_date": "2026-07-01 17:21:35",
    "author": "rnldburn",
    "description": "试运行了一个月了，目前不少人成功官方订阅了 Claude 和 OpenAI 。 想尝试的用户务必认真阅读以下提醒： 1.充值按照自己实际需要充值，最低 20USDT 。下个月扣费前再充值也可以。钱在你自己账户里面，用多少扣多少。 2.新上线一个月，可能会有 bug 。如您有遇到，欢迎反馈给我，确认是 bug ，有小小奖励。 3.关于退款，不想用了可以注销，没用掉的余额原路退回。 到目前为止，有两个退款的，基本当天处理完。 4.关于费用，…",
    "content": "试运行了一个月了，目前不少人成功官方订阅了 Claude 和 OpenAI 。 想尝试的用户务必认真阅读以下提醒： 1.充值按照自己实际需要充值，最低 20USDT 。下个月扣费前再充值也可以。钱在你自己账户里面，用多少扣多少。 2.新上线一个月，可能会有 bug 。如您有遇到，欢迎反馈给我，确认是 bug ，有小小奖励。 3.关于退款，不想用了可以注销，没用掉的余额原路退回。 到目前为止，有两个退款的，基本当天处理完。 4.关于费用，充值 USDT2%，开卡 1USDT ，充值到卡 2%USDT ，费用明示，评估…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224276#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 做了一个新的字幕站， subrain.tv，欢迎广大字幕制作者和爱好者使用",
    "link": "https://www.v2ex.com/t/1224276#reply0",
    "pub_date": "2026-07-01 17:21:24",
    "author": "yoa1q7y",
    "description": "最近用 Cloudflare 和 React 做了一个新的字幕站 主要亮点： 现代、精致、易用的界面设计，提供良好的用户体验 可以自行创建字幕组，并邀请其他字幕制作者加入 功能丰富的上传字幕页面，支持详细的元数据信息 由于网站刚刚上线，资源还明显不足，欢迎广大字幕制作者和爱好者使用，如果有认识的字幕制作者，也可帮忙宣传一下，感谢大家的支持！ 传送门： 网站： https://subrain.tv Telegram： https://t.…",
    "content": "最近用 Cloudflare 和 React 做了一个新的字幕站 主要亮点： 现代、精致、易用的界面设计，提供良好的用户体验 可以自行创建字幕组，并邀请其他字幕制作者加入 功能丰富的上传字幕页面，支持详细的元数据信息 由于网站刚刚上线，资源还明显不足，欢迎广大字幕制作者和爱好者使用，如果有认识的字幕制作者，也可帮忙宣传一下，感谢大家的支持！ 传送门： 网站： https://subrain.tv Telegram： https://t.me/subraintv 界面预览： 首页： 上传页： 字幕组管理页： 如果有使…"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802085-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "感觉好浪费啊",
    "link": "https://www.nodeseek.com/post-802085-1",
    "pub_date": "2026-07-01 17:20:41",
    "author": "",
    "description": "准备开个小鸡，不知道白嫖的pro，后期会不会有问题。",
    "content": "准备开个小鸡，不知道白嫖的pro，后期会不会有问题。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224275#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] Claude/gpt 满血纯净稳定 注册回帖留 ID 领 10 刀体验金",
    "link": "https://www.v2ex.com/t/1224275#reply0",
    "pub_date": "2026-07-01 17:20:05",
    "author": "eizzz",
    "description": "家人们，谁懂啊！做 AI 开发最头疼的就是接各种模型的 API 一会儿 OpenAI 额度没了，一会儿 Claude 又连不上了，切来切去真的心累... 直到我发现了 eirouter.com ！真的是打开了新世界的大门 它是一个统一的 AI API 网关，简单说就是： 你只需要接它一个接口，就能调遍全网主流大模型！ 核心亮点： ✅ 全模型覆盖：GPT Claude Sonnet, Gemini, DeepSeek 等... 你想要的它…",
    "content": "家人们，谁懂啊！做 AI 开发最头疼的就是接各种模型的 API 一会儿 OpenAI 额度没了，一会儿 Claude 又连不上了，切来切去真的心累... 直到我发现了 eirouter.com ！真的是打开了新世界的大门 它是一个统一的 AI API 网关，简单说就是： 你只需要接它一个接口，就能调遍全网主流大模型！ 核心亮点： ✅ 全模型覆盖：GPT Claude Sonnet, Gemini, DeepSeek 等... 你想要的它都有！ ✅ 满血纯净：拒绝阉割版！每一条调用都是原汁原味的“满血”性能，响应速度…"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802084-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "BestVM 德国 9929 预售 (更新优惠码)",
    "link": "https://www.nodeseek.com/post-802084-1",
    "pub_date": "2026-07-01 17:18:58",
    "author": "",
    "description": "BestVM德国9929预售https://bestvm.cloud/store/de-pro月九折：QDMY5UZI99季八折：O9YYR4TSO3年7折：IBUUO6BUJ5没有AFF，我没有挣AFF的觉悟。",
    "content": "BestVM德国9929预售https://bestvm.cloud/store/de-pro月九折：QDMY5UZI99季八折：O9YYR4TSO3年7折：IBUUO6BUJ5没有AFF，我没有挣AFF的觉悟。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802083-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "溢价700慢出DMIT EB Wee",
    "link": "https://www.nodeseek.com/post-802083-1",
    "pub_date": "2026-07-01 17:18:38",
    "author": "",
    "description": "11月5号到期，原油，无pp。收了瓦工，出了回血。",
    "content": "11月5号到期，原油，无pp。收了瓦工，出了回血。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802082-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "【🔥抽🔥】🔥火云指纹浏览器🔥10个无门槛免费窗口 欢迎体验~",
    "link": "https://www.nodeseek.com/post-802082-1",
    "pub_date": "2026-07-01 17:18:28",
    "author": "",
    "description": "xhj015xhj015xhj015下载链接：https://www.hotlogin.com/?inviteCode=nodeseek&source=hotlogin支持手机号、邮箱注册只是使用指纹浏览器无需实名领取方式：私信or扫码添加官网底部企业微信or添加TG发送本帖截图可获得：1、火云指纹浏览器无",
    "content": "xhj015xhj015xhj015下载链接：https://www.hotlogin.com/?inviteCode=nodeseek&amp;source=hotlogin支持手机号、邮箱注册只是使用指纹浏览器无需实名领取方式：私信or扫码添加官网底部企业微信or添加TG发送本帖截图可获得：1、火云指纹浏览器无"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802081-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "出 yxvm jp 3u",
    "link": "https://www.nodeseek.com/post-802081-1",
    "pub_date": "2026-07-01 17:18:11",
    "author": "",
    "description": "rt还有十天60出",
    "content": "rt还有十天60出"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802079-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "K12焚决来了",
    "link": "https://www.nodeseek.com/post-802079-1",
    "pub_date": "2026-07-01 17:16:34",
    "author": "",
    "description": "隔壁站发的，我不是作者不好转载。有母号的可以爽玩，那个脚本知道空间ID能强进，非自己域名注册的不要泄露自己空间ID。不然死翘翘的。",
    "content": "隔壁站发的，我不是作者不好转载。有母号的可以爽玩，那个脚本知道空间ID能强进，非自己域名注册的不要泄露自己空间ID。不然死翘翘的。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802078-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "K12要没了吗？K12焚绝泄露",
    "link": "https://www.nodeseek.com/post-802078-1",
    "pub_date": "2026-07-01 17:16:30",
    "author": "",
    "description": "在隔壁论坛看见了别人发的脚本，说是不用同意直接进入空间搞到空间id就行了",
    "content": "在隔壁论坛看见了别人发的脚本，说是不用同意直接进入空间搞到空间id就行了"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802077-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "求推荐itx配置 预算3-5k",
    "link": "https://www.nodeseek.com/post-802077-1",
    "pub_date": "2026-07-01 17:16:09",
    "author": "",
    "description": "不怎么玩特别大的3a偶尔玩玩三角洲无畏契约啥的谢谢",
    "content": "不怎么玩特别大的3a偶尔玩玩三角洲无畏契约啥的谢谢"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802076-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "sg.gs美国-新加坡爆炸",
    "link": "https://www.nodeseek.com/post-802076-1",
    "pub_date": "2026-07-01 17:15:57",
    "author": "",
    "description": "TelegramDC5延迟爆炸了刚说完就恢复。。。",
    "content": "TelegramDC5延迟爆炸了刚说完就恢复。。。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-802075-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "网易云每个月免费",
    "link": "https://www.nodeseek.com/post-802075-1",
    "pub_date": "2026-07-01 17:14:53",
    "author": "",
    "description": "1http:/$2IrIRn2d1fdf37$【復淛整段文案并咑閞「网易云音乐」，领免费会员】黑胶邀请官下***遇送你网易云音乐7月黑胶会员卡，领取享20+会员权益。https://163cn.tv/967Hciv",
    "content": "1http:/$2IrIRn2d1fdf37$【復淛整段文案并咑閞「网易云音乐」，领免费会员】黑胶邀请官下***遇送你网易云音乐7月黑胶会员卡，领取享20+会员权益。https://163cn.tv/967Hciv"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224274#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] Magic Context 大模型防痴呆插件",
    "link": "https://www.v2ex.com/t/1224274#reply0",
    "pub_date": "2026-07-01 17:14:09",
    "author": "yidinghe",
    "description": "https://github.com/cortexkit/magic-context 再牛的大模型，上下文过长都会变成痴呆。 这个 harness 插件的作用就是管住上下文，让你在一个会话里面可以永远聊下去。具体就是： 一个项目只需一个会话，这个插件会主动控制上下文的长度，将不需要的内容清理掉，将暂时不需要的记忆存档，需要时又重新加入上下文。 多个项目的记忆可以共享，包括环境配置、命名风格、设计意图，你可以将多个项目放在一个 works…",
    "content": "https://github.com/cortexkit/magic-context 再牛的大模型，上下文过长都会变成痴呆。 这个 harness 插件的作用就是管住上下文，让你在一个会话里面可以永远聊下去。具体就是： 一个项目只需一个会话，这个插件会主动控制上下文的长度，将不需要的内容清理掉，将暂时不需要的记忆存档，需要时又重新加入上下文。 多个项目的记忆可以共享，包括环境配置、命名风格、设计意图，你可以将多个项目放在一个 workspace 里面来共享记忆。 用户画像，记录用户的开发习惯、表达习惯，让大模型更精…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224272#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 做了一个 AI 情侣头像生成器",
    "link": "https://www.v2ex.com/t/1224272#reply0",
    "pub_date": "2026-07-01 17:10:18",
    "author": "MaxPool",
    "description": "最近给自己的网站做了一个 AI 情侣头像生成的小功能。 很多 AI 工具只能生成一张图，想要情侣合照、男生头像、女生头像，通常得生成三次，而且人物和画风很容易不一致。 所以我做了这个功能：上传一张情侣合照，选择喜欢的风格，就能一次生成： 一张情侣合照 男生头像 女生头像 三张图片的人物和画风都会尽量保持一致，省得反复生成。 有兴趣的话欢迎 m 免费体验，也欢迎提点建议： https://meiya.app/ai-couple-photo…",
    "content": "最近给自己的网站做了一个 AI 情侣头像生成的小功能。 很多 AI 工具只能生成一张图，想要情侣合照、男生头像、女生头像，通常得生成三次，而且人物和画风很容易不一致。 所以我做了这个功能：上传一张情侣合照，选择喜欢的风格，就能一次生成： 一张情侣合照 男生头像 女生头像 三张图片的人物和画风都会尽量保持一致，省得反复生成。 有兴趣的话欢迎 m 免费体验，也欢迎提点建议： https://meiya.app/ai-couple-photo-generator"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224271#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 写了一个克隆网站样式的产品，大家有需求吗",
    "link": "https://www.v2ex.com/t/1224271#reply0",
    "pub_date": "2026-07-01 17:07:18",
    "author": "bojue",
    "description": "根据网站的 Url 拷贝网站的样式： 目前已经处理：html/JS/css/图片/视频等样式原生 可以设计爬虫频率，尽量避免触发反爬 网站 https://ibb.co/0ydJ8tM4 DEMO 视频地址： http://viz.nocokit.cn/uploads/media/c1f9e57d3551833ff81df04816eedd28.mov 效果 1.mintlify.com https://ibb.co/0ydJ8tM4 …",
    "content": "根据网站的 Url 拷贝网站的样式： 目前已经处理：html/JS/css/图片/视频等样式原生 可以设计爬虫频率，尽量避免触发反爬 网站 https://ibb.co/0ydJ8tM4 DEMO 视频地址： http://viz.nocokit.cn/uploads/media/c1f9e57d3551833ff81df04816eedd28.mov 效果 1.mintlify.com https://ibb.co/0ydJ8tM4 2.V2ex.com https://ibb.co/zhkMThxB"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224270#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] AI 时代下是不是专业深度更有价值了？",
    "link": "https://www.v2ex.com/t/1224270#reply3",
    "pub_date": "2026-07-01 17:05:58",
    "author": "zidiyo",
    "description": "我指的专业深度不是精通某一种编程语言，而是多年生产环境积累下来的工程判断：如何做架构取舍、如何评估系统风险、如何保障可靠性、如何预测可能发生的线上事故，以及如何在复杂场景下做出正确决策 感觉现在 ai 贬值的是“写代码”这一层，而如何审核代码，改代码，为线上兜底反而更有价值了",
    "content": "我指的专业深度不是精通某一种编程语言，而是多年生产环境积累下来的工程判断：如何做架构取舍、如何评估系统风险、如何保障可靠性、如何预测可能发生的线上事故，以及如何在复杂场景下做出正确决策 感觉现在 ai 贬值的是“写代码”这一层，而如何审核代码，改代码，为线上兜底反而更有价值了"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224269#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 小白用 codex 写了一个原生 ios 的相册 app，模仿 ios 自带相册的那种缩放，写不动了，这里改了另一处出问题",
    "link": "https://www.v2ex.com/t/1224269#reply1",
    "pub_date": "2026-07-01 17:04:05",
    "author": "budingkaka2013",
    "description": "= 演示视频： https://youtube.com/shorts/BNUhr-YKgd0?feature=share = 写累了，和 ai 交流了几个月，想放弃了，这是一个瓦片的相册系统，支持海量照片，我自己的测试数据是 500k 级别，不懂代码的我，真的 ai 改了一个地方另一个地方出问题，目前代码数量大概是 1w 多行。 = 还有安卓原生端，和 react 端，和后端，但是我想先把 ios 调节精细，真的太累了，全程 5.5 超…",
    "content": "= 演示视频： https://youtube.com/shorts/BNUhr-YKgd0?feature=share = 写累了，和 ai 交流了几个月，想放弃了，这是一个瓦片的相册系统，支持海量照片，我自己的测试数据是 500k 级别，不懂代码的我，真的 ai 改了一个地方另一个地方出问题，目前代码数量大概是 1w 多行。 = 还有安卓原生端，和 react 端，和后端，但是我想先把 ios 调节精细，真的太累了，全程 5.5 超高模型，顶不住了 = 有共同爱好的友友吗 交流交流，或者有大佬吗"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224268#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Apple] 做了一个 macOS App： Surge Relay，用来集中管理、转换和发布 Surge 模块。",
    "link": "https://www.v2ex.com/t/1224268#reply0",
    "pub_date": "2026-07-01 17:01:33",
    "author": "Lutto",
    "description": "最近做了一个 macOS App ，叫 Surge Relay 。老刘没做的，我给补上了！ GitHub： https://github.com/EEliberto/SurgeRelay-macOS 它主要用于集中管理、转换、编辑和发布 Surge 模块，比较适合经常通过 Script-Hub 将 Loon / Quantumult X / 其他代理工具格式转换为 Surge .sgmodule 的场景。 我自己遇到的痛点是：Surge…",
    "content": "最近做了一个 macOS App ，叫 Surge Relay 。老刘没做的，我给补上了！ GitHub： https://github.com/EEliberto/SurgeRelay-macOS 它主要用于集中管理、转换、编辑和发布 Surge 模块，比较适合经常通过 Script-Hub 将 Loon / Quantumult X / 其他代理工具格式转换为 Surge .sgmodule 的场景。 我自己遇到的痛点是：Surge 里已经安装的模块不方便批量修改来源地址。如果上游作者修改了仓库地址、文件路径或…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224267#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 闲鱼 16G 价格在 300 上下 是否可以买？求 18cm 给点建议",
    "link": "https://www.v2ex.com/t/1224267#reply0",
    "pub_date": "2026-07-01 17:00:28",
    "author": "newmancity",
    "description": "如题，如果要买的话有什么需要关注的吗",
    "content": "如题，如果要买的话有什么需要关注的吗"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224264#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] PopTrans 基于最新腾讯 Hy-MT2-1.8B 大模型开源翻译软件",
    "link": "https://www.v2ex.com/t/1224264#reply0",
    "pub_date": "2026-07-01 16:51:43",
    "author": "shenpVip",
    "description": "一款 Windows 桌面翻译工具。选中文本或框选屏幕区域，按下快捷键即可弹出翻译结果。基于腾讯 Hy-MT2-1.8B 离线翻译与 RapidOCR 引擎，支持中英文互译、OCR 截图翻译、自定义快捷键、深色主题 UI 。 🌐 一键翻译 — 选中文本，按下快捷键即可翻译 🖼️ OCR 截图翻译 — 框选屏幕区域，识别图片/视频/PDF 中的文字并翻译 ⌨️ 自定义快捷键 — 翻译与 OCR 各自独立快捷键，通过托盘菜单设置 🔄 …",
    "content": "一款 Windows 桌面翻译工具。选中文本或框选屏幕区域，按下快捷键即可弹出翻译结果。基于腾讯 Hy-MT2-1.8B 离线翻译与 RapidOCR 引擎，支持中英文互译、OCR 截图翻译、自定义快捷键、深色主题 UI 。 🌐 一键翻译 — 选中文本，按下快捷键即可翻译 🖼️ OCR 截图翻译 — 框选屏幕区域，识别图片/视频/PDF 中的文字并翻译 ⌨️ 自定义快捷键 — 翻译与 OCR 各自独立快捷键，通过托盘菜单设置 🔄 智能方向 — 自动识别中文→英文 / 英文→中文 🔌 离线工作 — 翻译用腾讯…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224262#reply15",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[硬件] 没人讨论小米 NAS 吗？",
    "link": "https://www.v2ex.com/t/1224262#reply15",
    "pub_date": "2026-07-01 16:41:42",
    "author": "balalalalallala",
    "description": "看到 B 站有的 UP 已经拿到并开箱了，但是没有详细介绍，群里大佬有更详细的介绍吗？",
    "content": "看到 B 站有的 UP 已经拿到并开箱了，但是没有详细介绍，群里大佬有更详细的介绍吗？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224261#reply31",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Claude] 无脑黑 A\\ 似乎成为流量密码了",
    "link": "https://www.v2ex.com/t/1224261#reply31",
    "pub_date": "2026-07-01 16:41:35",
    "author": "plants",
    "description": "近期发现的流量博主脑残言论： “通过邮件追踪中国人”，其实是很普遍邮件已读回执 “A\\ 精准锁定杭州用户进行批量封号” 这扯得不了，无需解释 “claude code 监控中国人”，我看下来，只有在使用第三方中转站才会触发隐水印，如果使用官方订阅是不会触发的，如果你的 api 发往中国模型，A\\收不到，很容易理解到这是为了监控中转站滥用的合理行为",
    "content": "近期发现的流量博主脑残言论： “通过邮件追踪中国人”，其实是很普遍邮件已读回执 “A\\ 精准锁定杭州用户进行批量封号” 这扯得不了，无需解释 “claude code 监控中国人”，我看下来，只有在使用第三方中转站才会触发隐水印，如果使用官方订阅是不会触发的，如果你的 api 发往中国模型，A\\收不到，很容易理解到这是为了监控中转站滥用的合理行为"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224260#reply20",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 办公室有个逼，一年多了，每天每隔 3s 就要咳一下，还有 adhd，经常发出奇怪的声音，做出奇怪的动作，该怎么办？",
    "link": "https://www.v2ex.com/t/1224260#reply20",
    "pub_date": "2026-07-01 16:40:34",
    "author": "semiboldhung",
    "description": "有没有什么神奇的办法，可以神不知鬼不觉把 ta 鲨掉？",
    "content": "有没有什么神奇的办法，可以神不知鬼不觉把 ta 鲨掉？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224259#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 写了一个文本加解密工具，大家可以用用看看",
    "link": "https://www.v2ex.com/t/1224259#reply5",
    "pub_date": "2026-07-01 16:37:36",
    "author": "pxiphx891",
    "description": "今天想把一些个人文本数据通过在线服务（比如easychuan）传递到另一台电脑，所以让 Claude 写了一个本地加解密的网页，零依赖，老电脑老浏览器也能用，大家有需要的可以试试 代码： https://github.com/erniu3/pocket-crypt/blob/master/index.html 直接使用： https://erniu3.github.io/pocket-crypt/",
    "content": "今天想把一些个人文本数据通过在线服务（比如 easychuan ）传递到另一台电脑，所以让 Claude 写了一个本地加解密的网页，零依赖，老电脑老浏览器也能用，大家有需要的可以试试 代码： https://github.com/erniu3/pocket-crypt/blob/master/index.html 直接使用： https://erniu3.github.io/pocket-crypt/"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224258#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[宽带症候群] 求推荐大流量物联网卡",
    "link": "https://www.v2ex.com/t/1224258#reply0",
    "pub_date": "2026-07-01 16:32:02",
    "author": "lo0pback",
    "description": "",
    "content": ""
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224257#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] 🚀 NVIDIA | 高级测试开发工程师（GPU 编译器方向）",
    "link": "https://www.v2ex.com/t/1224257#reply3",
    "pub_date": "2026-07-01 16:31:38",
    "author": "zoe1016aaa",
    "description": "热衷于为顶级 GPU 软件构建世界级质量保障体系？喜欢把自动化测试、编译器验证和代码分析玩在一起？这个岗位可能适合你。 我们正在寻找一位优秀的测试开发工程师，加入 NVIDIA 核心软件团队，负责 CUTLASS DSL 测试框架的研发与演进，制定基于 MLIR 编译流水线的全链路测试策略，让编译器和内核创新能够快速、安全地迭代上线。 [你将做什么] 开发并持续演进面向下一代 GPU 软件的 CUTLASS DSL 测试框架 制定、完善…",
    "content": "热衷于为顶级 GPU 软件构建世界级质量保障体系？喜欢把自动化测试、编译器验证和代码分析玩在一起？这个岗位可能适合你。 我们正在寻找一位优秀的测试开发工程师，加入 NVIDIA 核心软件团队，负责 CUTLASS DSL 测试框架的研发与演进，制定基于 MLIR 编译流水线的全链路测试策略，让编译器和内核创新能够快速、安全地迭代上线。 [你将做什么] 开发并持续演进面向下一代 GPU 软件的 CUTLASS DSL 测试框架 制定、完善并执行面向开源社区发布的完整产品测试策略 保障基于 MLIR 的编译流水线及相关…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224256#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 有人注意到了 AI 时代 Java 的问题了吗？",
    "link": "https://www.v2ex.com/t/1224256#reply0",
    "pub_date": "2026-07-01 16:30:24",
    "author": "systemGuest",
    "description": "公司分享总结，发现需求少的 java 部门消耗 Token 还更多(排除用到其他地方)，问了下 AI 可能的原因，有意思的一些信息出来了。 1. Token 成本高 对大型多 agent 系统不友好（你的 manifest-based 路由，Java 实现会吃更多窗口） 显式声明 + 类型注解 + 访问修饰符，同功能代码比 Python/Go 多 30-50% 企业框架（ Spring ）天然臃肿，即使简单需求也要大量样板代码 同样的 …",
    "content": "公司分享总结，发现需求少的 java 部门消耗 Token 还更多(排除用到其他地方)，问了下 AI 可能的原因，有意思的一些信息出来了。 1. Token 成本高 对大型多 agent 系统不友好（你的 manifest-based 路由，Java 实现会吃更多窗口） 显式声明 + 类型注解 + 访问修饰符，同功能代码比 Python/Go 多 30-50% 企业框架（ Spring ）天然臃肿，即使简单需求也要大量样板代码 同样的 token 预算，Java 项目能加载的代码量更少，长期使用 Java 开发者的…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224255#reply29",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 你左手按 b 键还是右手",
    "link": "https://www.v2ex.com/t/1224255#reply29",
    "pub_date": "2026-07-01 16:24:55",
    "author": "cj323",
    "description": "楼主用右手按 b 按了不知道多少年，今天 gpt 告诉我现在建议用左手……",
    "content": "楼主用右手按 b 按了不知道多少年，今天 gpt 告诉我现在建议用左手……"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224254#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Apple] 新款 APPLE TV 什么时候出， 9 月会出么？",
    "link": "https://www.v2ex.com/t/1224254#reply5",
    "pub_date": "2026-07-01 16:20:27",
    "author": "wang794822947",
    "description": "想入手个 apple tv 了 9 月会出新品么",
    "content": "想入手个 apple tv 了 9 月会出新品么"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224253#reply15",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Apple] [送激活码] 🎉 Wins 3.4 发布！把 Mac 刘海变成悬浮分屏岛，抽奖送激活码～",
    "link": "https://www.v2ex.com/t/1224253#reply15",
    "pub_date": "2026-07-01 16:14:07",
    "author": "eggsblue",
    "description": "👋 嗨，V 站的朋友们，大家好～ 🙋 我是 Wins 的开发者，距离 Wins 3.0 发布竟然 9 个月过去了，又来和大家同步最近的一次更新了。 这次主要打磨了一个我自己很喜欢的新交互： 🏝️ Wins 3.4 发布：「悬浮分屏岛」来了 这不是一个普通的悬浮面板。 我想做的是：当你拖动窗口到屏幕顶部时，它像 iOS 灵动岛一样，从 MacBook 的刘海区域自然出现；你继续拖动，就可以快速选择布局并完成分屏。 也就是说，MacB…",
    "content": "👋 嗨，V 站的朋友们，大家好～ 🙋 我是 Wins 的开发者，距离 Wins 3.0 发布竟然 9 个月过去了，又来和大家同步最近的一次更新了。 这次主要打磨了一个我自己很喜欢的新交互： 🏝️ Wins 3.4 发布：「悬浮分屏岛」来了 这不是一个普通的悬浮面板。 我想做的是：当你拖动窗口到屏幕顶部时，它像 iOS 灵动岛一样，从 MacBook 的刘海区域自然出现；你继续拖动，就可以快速选择布局并完成分屏。 也就是说，MacBook 的刘海不再只是一个“缺口”，它也可以变成窗口管理的入口。 在没有刘海的 …"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224252#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Mac mini] 去年 4 月份购入 Mac Mini M4 32G + 512，现在能卖什么价",
    "link": "https://www.v2ex.com/t/1224252#reply0",
    "pub_date": "2026-07-01 16:14:03",
    "author": "XLeopard",
    "description": "",
    "content": ""
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224251#reply6",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] n 年前互联网繁荣期有一个 35 岁的“免毕业”方案是“转管理”，现在大家应该人均手下几个 agent 员工，很少参与大规模代码手写，是否算是完成了“夙愿”——转管理",
    "link": "https://www.v2ex.com/t/1224251#reply6",
    "pub_date": "2026-07-01 16:11:10",
    "author": "YanSeven",
    "description": "现在的码农可以说是人均“小主管”。",
    "content": "现在的码农可以说是人均“小主管”。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224249#reply2",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 是否有技术方案，可以运行一个软件而模拟完全不同于物理机的机器特征",
    "link": "https://www.v2ex.com/t/1224249#reply2",
    "pub_date": "2026-07-01 16:06:54",
    "author": "bigdogbigpig",
    "description": "看到最近 Claude 封号多讨论，想到这个方向 我知道很像指纹浏览器，但是浏览器里要做的事情没有软件多。 类似 Claude 这种编程的，可能需要运行一些本机存在的命令，不仅仅是修改文件，如果用 docker sbx 之类的就不能用了",
    "content": "看到最近 Claude 封号多讨论，想到这个方向 我知道很像指纹浏览器，但是浏览器里要做的事情没有软件多。 类似 Claude 这种编程的，可能需要运行一些本机存在的命令，不仅仅是修改文件，如果用 docker sbx 之类的就不能用了"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224248#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Codex] 不是 这对吗 plus 我 vscode 接了 codex 的扩展插件用",
    "link": "https://www.v2ex.com/t/1224248#reply0",
    "pub_date": "2026-07-01 15:53:31",
    "author": "linglongll",
    "description": "就五个问题 用完了配额",
    "content": "就五个问题 用完了配额"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224247#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[AI Agent 智能体] 周末打了个 AI Agents 黑客松，把过程整理成了一个 Hackathon Skill",
    "link": "https://www.v2ex.com/t/1224247#reply0",
    "pub_date": "2026-07-01 15:51:10",
    "author": "kangkona",
    "description": "周末参加了一个 AI Agents 主题的黑客松，最后运气不错拿了一等奖。 这帖不是来晒奖的，主要是想分享一下这次和 Codex 一起打黑客松的过程。比赛结束后我翻了一下两天里的聊天记录，发现里面其实留下了一条挺完整的路径：怎么选方向、怎么误判、怎么止损、怎么收敛 demo 、怎么准备 Q&A 。 所以顺手把它整理成了一个开源 Skill： https://github.com/kangkona/kangkona-skills 里面目前…",
    "content": "周末参加了一个 AI Agents 主题的黑客松，最后运气不错拿了一等奖。 这帖不是来晒奖的，主要是想分享一下这次和 Codex 一起打黑客松的过程。比赛结束后我翻了一下两天里的聊天记录，发现里面其实留下了一条挺完整的路径：怎么选方向、怎么误判、怎么止损、怎么收敛 demo 、怎么准备 Q&amp;A 。 所以顺手把它整理成了一个开源 Skill： https://github.com/kangkona/kangkona-skills 里面目前有一个 Hackathon Skill ，算是一个黑客松实战手册。目标不…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224246#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Codex] [车找人] codex 20x pro 拼车，车上 2 人，再找 3 人",
    "link": "https://www.v2ex.com/t/1224246#reply0",
    "pub_date": "2026-07-01 15:46:04",
    "author": "hexubbgt",
    "description": "已稳定两个月，美区账号，日本服务器，国内可直连，出口美国家宽，sup2api 分发，不破限，不逆向，不颜色，封号按天退款，闲鱼收款 车位 300 只有 codex 车位 gpt-pro 250 只有 gpt-web codex 日限 150 刀 周限 550 刀 月限 2200 刀 tg QGJiZ3R4eA==",
    "content": "已稳定两个月，美区账号，日本服务器，国内可直连，出口美国家宽，sup2api 分发，不破限，不逆向，不颜色，封号按天退款，闲鱼收款 车位 300 只有 codex 车位 gpt-pro 250 只有 gpt-web codex 日限 150 刀 周限 550 刀 月限 2200 刀 tg QGJiZ3R4eA=="
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224245#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Claude] claude function_call 时经常会蹦出个 random word 导致输出中断",
    "link": "https://www.v2ex.com/t/1224245#reply0",
    "pub_date": "2026-07-01 15:45:01",
    "author": "Dav1s",
    "description": "这两天开始出现的 有人出现和我一样的状况吗 怀疑被打 tag 了",
    "content": "这两天开始出现的 有人出现和我一样的状况吗 怀疑被打 tag 了"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224244#reply9",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[宽带症候群] 关于我宽带上行被限速 5M，我该怎么办",
    "link": "https://www.v2ex.com/t/1224244#reply9",
    "pub_date": "2026-07-01 15:42:21",
    "author": "OmoineMie",
    "description": "这是我上篇帖子 https://www.v2ex.com/t/1223826 ，说了宽带被限速 5m 上行，但测速网站有的正常，有的不正常 用一台云服务器，用 iperf 测速，上行确实是被限速 5mbps ，但是用 ssh 往这台服务器传文件，上行却能跑满 50mbps ，这是为什么呢？ 我远程家里的电脑，nas 卡的一批，最高才 10mbps,都是通过公网 IP 直连的。 我正在家里搭建了一个测速服务器，http://27.10.1…",
    "content": "这是我上篇帖子 https://www.v2ex.com/t/1223826 ，说了宽带被限速 5m 上行，但测速网站有的正常，有的不正常 用一台云服务器，用 iperf 测速，上行确实是被限速 5mbps ，但是用 ssh 往这台服务器传文件，上行却能跑满 50mbps ，这是为什么呢？ 我远程家里的电脑，nas 卡的一批，最高才 10mbps,都是通过公网 IP 直连的。 我正在家里搭建了一个测速服务器， http://27.10.122.228:30000 ，你们试一下测速能达到多少"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224243#reply7",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] 那把电脑时间调成新加坡时区岂不是就可以用 Claude 了",
    "link": "https://www.v2ex.com/t/1224243#reply7",
    "pub_date": "2026-07-01 15:39:11",
    "author": "Hilalum",
    "description": "中文系统，新加坡时区也是东 8 区，完全没影响了",
    "content": "中文系统，新加坡时区也是东 8 区，完全没影响了"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224242#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 2026 年过半， 5 万外汇额度用完被银行拒收谷歌外汇款项，接下来半年谷歌的款我将是这样收",
    "link": "https://www.v2ex.com/t/1224242#reply1",
    "pub_date": "2026-07-01 15:39:04",
    "author": "Livy15669",
    "description": "哈喽大家好久不见！这里是 Livy 2026 年一晃眼已经过半了，最近不少出海做个人独立开发、YouTube 运营的朋友，都在和我倒苦水。 最让人头疼的是，因为上半年收入还不错，个人的 5 万美金外汇额度已经早早用完了！ 眼看着下半年的谷歌（ Google/Apple ）外汇款项又要汇入，国内银行却直接甩来一张“拒绝入账/退单”的通知。一边是辛辛苦苦赚来的美金，一边是卡死在限额里的政策，这下半年，谷歌的款到底还能怎么收？ 今天我就来给大…",
    "content": "哈喽大家好久不见！这里是 Livy 2026 年一晃眼已经过半了，最近不少出海做个人独立开发、YouTube 运营的朋友，都在和我倒苦水。 最让人头疼的是，因为上半年收入还不错，个人的 5 万美金外汇额度已经早早用完了！ 眼看着下半年的谷歌（ Google/Apple ）外汇款项又要汇入，国内银行却直接甩来一张“拒绝入账/退单”的通知。一边是辛辛苦苦赚来的美金，一边是卡死在限额里的政策，这下半年，谷歌的款到底还能怎么收？ 今天我就来给大家分享三种方案，希望对大家有所帮助。 一、第三方收款平台 有许多第三方跨境收款平…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224241#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] PDD 算法岗位，大量缺人",
    "link": "https://www.v2ex.com/t/1224241#reply3",
    "pub_date": "2026-07-01 15:36:01",
    "author": "reidstark",
    "description": "有兴趣的可以来撩",
    "content": "有兴趣的可以来撩"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224240#reply2",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] 我找到了世界上最好用的西瓜勺!",
    "link": "https://www.v2ex.com/t/1224240#reply2",
    "pub_date": "2026-07-01 15:31:25",
    "author": "ggbond2233",
    "description": "https://item.m.jd.com/product/100081994232.html 尖头 加深 强烈推荐!!!",
    "content": "https://item.m.jd.com/product/100081994232.html 尖头 加深 强烈推荐!!!"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224238#reply18",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 用 AI 写代码时，你们还逐行看代码吗？",
    "link": "https://www.v2ex.com/t/1224238#reply18",
    "pub_date": "2026-07-01 15:22:35",
    "author": "fgghyyfk",
    "description": "最近用 Claude / Codex 写公司内部工具，我发现自己越来越少逐行看代码。 原因也简单：我早年写过几年代码，但很多年没正经写了。现在让我看 AI 写的一堆后端、接口、SQL 、测试，很多地方我也看不懂。硬看一遍，未必比 AI 自己写得更靠谱。 所以我现在更偏向结果验收： 先把我要的结果讲清楚； 让 AI 补测试用例； 页面真实跑一遍； 业务口径自己验； 异常和失败日志必须能看出来。 比如日报功能，我不会逐行看它怎么查表，但我会…",
    "content": "最近用 Claude / Codex 写公司内部工具，我发现自己越来越少逐行看代码。 原因也简单：我早年写过几年代码，但很多年没正经写了。现在让我看 AI 写的一堆后端、接口、SQL 、测试，很多地方我也看不懂。硬看一遍，未必比 AI 自己写得更靠谱。 所以我现在更偏向结果验收： 先把我要的结果讲清楚； 让 AI 补测试用例； 页面真实跑一遍； 业务口径自己验； 异常和失败日志必须能看出来。 比如日报功能，我不会逐行看它怎么查表，但我会验：昨天数据取没取对，DAU / 销量 / 利润口径对不对，没数据时会不会乱写，…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224237#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 奈云没跑路，国内团队失联了，正在恢复中，换了新官网",
    "link": "https://www.v2ex.com/t/1224237#reply5",
    "pub_date": "2026-07-01 15:20:34",
    "author": "zhuyao",
    "description": "新官网地址： https://naiun.io naiun.org naiyun.org 是假的登录会跳到银河云。 最近机场都不稳定，仔细甄别，因为用了他家觉得还不错，之前有家宽，一直在用 cc 也没被封，所以宣传下",
    "content": "新官网地址： https://naiun.io 或者 naiun.org 重要提醒： naiyun.org 是假的登录会跳到银河云。 最近机场都不稳定，仔细甄别，因为用了他家觉得还不错，之前有家宽，一直在用 cc 也没被封，所以宣传下"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224236#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] vibe coding 多了和技术同事之间的工作沟通都异步了",
    "link": "https://www.v2ex.com/t/1224236#reply1",
    "pub_date": "2026-07-01 15:14:20",
    "author": "yyttrr",
    "description": "之前同事向我提出问题,我大概率会当场解决.稍微复杂一些的问题需要当面敲命令查一下之后给个回答,之后同事离开 现在同事提出问题,我大概率无法当面给出回答,经常是让他先回去忙别的,之后我开个 cluade code 窗口查一下,之后在 im 上给答复 甚至后面发展到,同事在 im 上向我丢一个他 agent 生成的 md 文件提出问题,之后我用 agent 读取这个 md 文件之后在后面续写上回答,再用 im 丢 md 文件回去.有几次我自…",
    "content": "之前同事向我提出问题,我大概率会当场解决.稍微复杂一些的问题需要当面敲命令查一下之后给个回答,之后同事离开 现在同事提出问题,我大概率无法当面给出回答,经常是让他先回去忙别的,之后我开个 cluade code 窗口查一下,之后在 im 上给答复 甚至后面发展到,同事在 im 上向我丢一个他 agent 生成的 md 文件提出问题,之后我用 agent 读取这个 md 文件之后在后面续写上回答,再用 im 丢 md 文件回去.有几次我自己完全都没看这个 md 文件里面的内容 也不知道这种变化是不是好的方向"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224235#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 想要一个 AI 笔记应用的看过来",
    "link": "https://www.v2ex.com/t/1224235#reply0",
    "pub_date": "2026-07-01 15:13:24",
    "author": "feng950704",
    "description": "潜心驱使 Codex ，开通 Pro 会员猛造，终于成果新鲜出炉： 一个适合 AI 笔记、AI 写作的编辑器，所有的东西 All in one ，再也不用在各种应用间切来切去的。 🔍 全网素材搜索 把 Google 搜索做进了笔记里，想搜什么直接搜，让 AI 去抓取和搬运，形成自己的素材： 选中某个结果，就可以加入素材库，AI 会自动去抓取的。之后可以素材直接拖动到文章编辑器里，也可以让 AI 基于素材进行二次加工，非常方便。 还有搜…",
    "content": "潜心驱使 Codex ，开通 Pro 会员猛造，终于成果新鲜出炉： 一个适合 AI 笔记、AI 写作的编辑器，所有的东西 All in one ，再也不用在各种应用间切来切去的。 🔍 全网素材搜索 把 Google 搜索做进了笔记里，想搜什么直接搜，让 AI 去抓取和搬运，形成自己的素材： 选中某个结果，就可以加入素材库，AI 会自动去抓取的。之后可以素材直接拖动到文章编辑器里，也可以让 AI 基于素材进行二次加工，非常方便。 还有搜索白板功能，在二维平面上展开搜索结果，还能连续不断搜索，我觉得很酷。(仿照警匪片…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224234#reply2",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[反馈] 在帖子内回复自己使用的网站导致被误封禁",
    "link": "https://www.v2ex.com/t/1224234#reply2",
    "pub_date": "2026-07-01 15:08:55",
    "author": "YaNanGe",
    "description": "在帖子 [梯子怎么都挂了？] ：/t/1224104 中分享自己觉得比较稳定的机场后不小心触发了自动封禁，然后就把我经常使用的 ip 给 ban 了，现在使用 ip 为：67.230.160.53 的主机访问本站会提示 503 。请求解除误封",
    "content": "在帖子 [梯子怎么都挂了？] ：/t/1224104 中分享自己觉得比较稳定的机场后不小心触发了自动封禁，然后就把我经常使用的 ip 给 ban 了，现在使用 ip 为：67.230.160.53 的主机访问本站会提示 503 。请求解除误封"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224233#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 一个 PR 换 $10 + 高流量外链 + 返佣？支持 Ofox 接入、或基于 Ofox 开发一键获得",
    "link": "https://www.v2ex.com/t/1224233#reply0",
    "pub_date": "2026-07-01 15:08:30",
    "author": "Celeste1900",
    "description": "你的应用只要用得上 Ofox 就可以提交得到 10🔪 不管是让用户填自己的 Ofox Key （集成），还是产品本身基于 Ofox 开发（构建）—— 都能提个 PR 收录进我们的展示墙 Works with Ofox（ ofox.ai/awesome-ofox ），一次拿三样： 💰 $10 开发激励金，审核通过直接进你的 Ofox 账户 🔗 一条来自高流量 AI 站点、指向你站点的真实反链（懂 SEO 的都知道这值多少） 🤝 自…",
    "content": "你的应用只要用得上 Ofox 就可以提交得到 10🔪 不管是让用户填自己的 Ofox Key （集成），还是产品本身基于 Ofox 开发（构建）—— 都能提个 PR 收录进我们的展示墙 Works with Ofox （ ofox.ai/awesome-ofox ），一次拿三样： 💰 $10 开发激励金 ，审核通过直接进你的 Ofox 账户 🔗 一条来自高流量 AI 站点、指向你站点的真实反链 （懂 SEO 的都知道这值多少） 🤝 自动成 Partner ：以后有人通过你的专属链接注册用 Ofox ，你持续…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224232#reply22",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 南京四天三夜 求过来人推荐吃玩住！",
    "link": "https://www.v2ex.com/t/1224232#reply22",
    "pub_date": "2026-07-01 15:03:31",
    "author": "programbao",
    "description": "南京四天三夜 求过来人推荐吃玩住！ 目前收集到的散乱攻略，求补充/纠错～ 吃： 大肉面 | 皮肚面 | 南京烤鸭 | 七家湾牛肉锅贴 游： 瞻园 · 南京省博物馆 · 梧桐大道 · 红山动物园 紫金山 · 中山陵 · 音乐台 · 总统府 · 德基广场 住（新街口地铁站附近）： 酒店：全季 / 亚朵 / 如家精选 / 南京中心大酒店 民宿：自由生长民宿 求解答： 1️⃣ 看民宿房间布局还不错，值得住吗？有具体推荐的民宿店吗？ 2️⃣ 有没…",
    "content": "南京四天三夜 求过来人推荐吃玩住！ 目前收集到的散乱攻略，求补充/纠错～ 吃： 大肉面 | 皮肚面 | 南京烤鸭 | 七家湾牛肉锅贴 游： 瞻园 · 南京省博物馆 · 梧桐大道 · 红山动物园 紫金山 · 中山陵 · 音乐台 · 总统府 · 德基广场 住（新街口地铁站附近）： 酒店：全季 / 亚朵 / 如家精选 / 南京中心大酒店 民宿：自由生长民宿 求解答： 1️⃣ 看民宿房间布局还不错，值得住吗？有具体推荐的民宿店吗？ 2️⃣ 有没有具体推荐的店/避雷提醒？ 蹲一波过来人经验🙏"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224231#reply7",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 访问不了 Reddit，除了换节点还有啥招",
    "link": "https://www.v2ex.com/t/1224231#reply7",
    "pub_date": "2026-07-01 14:57:30",
    "author": "mingtdlb",
    "description": "同一个节点，有时候可以有时候不行，反正大部分节点都不行（三个机场都一样），不干净吗 机场节点都万人蹭的...",
    "content": "同一个节点，有时候可以有时候不行，反正大部分节点都不行（三个机场都一样），不干净吗 机场节点都万人蹭的..."
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224230#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 分享一个非官方 ServerCat app 的 CLI 工具： sc",
    "link": "https://www.v2ex.com/t/1224230#reply0",
    "pub_date": "2026-07-01 14:57:29",
    "author": "kashgari4j",
    "description": "ServerCat 用户好， 写了一个简单的命令行工具 sc，可以直接管理 ServerCat 的 Core Data 数据库（服务器、容器、Snippet 、SSH Key ），支持批量导入 docker-compose 和 ~/.ssh/config。 纯本地工具，零依赖，macOS only 。配合 AI Agent 使用效果不错（--json 输出）。 仓库： https://github.com/pengyanai/serve…",
    "content": "ServerCat 用户好， 写了一个简单的命令行工具 sc ，可以直接管理 ServerCat 的 Core Data 数据库（服务器、容器、Snippet 、SSH Key ），支持批量导入 docker-compose 和 ~/.ssh/config 。 纯本地工具，零依赖，macOS only 。配合 AI Agent 使用效果不错（ --json 输出）。 仓库： https://github.com/pengyanai/servercat-cli 非官方作品，如有冒犯请随时告知，会立即删除。感谢 Ser…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224229#reply13",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 630 过去了，今天是下半年了，统计一个各位大佬公司的裁员比例？",
    "link": "https://www.v2ex.com/t/1224229#reply13",
    "pub_date": "2026-07-01 14:52:27",
    "author": "linzhai",
    "description": "RT:我所在的公司根据不同的部门大约 30%到 50%",
    "content": "RT:我所在的公司根据不同的部门大约 30%到 50%"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224228#reply11",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[投资] 坐看寒武纪崩盘",
    "link": "https://www.v2ex.com/t/1224228#reply11",
    "pub_date": "2026-07-01 14:47:20",
    "author": "Nexora",
    "description": "我就搬凳子坐着看寒武纪什么时候崩盘，等吃瓜。还有易中天三兄弟，都不远了。",
    "content": "我就搬凳子坐着看寒武纪什么时候崩盘，等吃瓜。还有易中天三兄弟，都不远了。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224227#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] 苏州，组内直推，汇川。AI 数据治理",
    "link": "https://www.v2ex.com/t/1224227#reply0",
    "pub_date": "2026-07-01 14:46:45",
    "author": "sinnosong1",
    "description": "岗位概述 我们正在寻找一位同时具备数据工程能力与 AI Agent 系统构建能力的工程师，参与构建企业级数据与智能体一体化基础设施。该岗位将同时覆盖两条核心技术主线： 数据基座方向：构建高质量数据链路与统一语义数据层（ ETL/ELT 、湖仓、数据治理） 智能体方向：设计与实现面向业务执行的 Agent 系统（规划、工具调用、多智能体协同、记忆与上下文管理） 你将深度参与从“数据产生 → 数据治理 → 数据服务 → Agent 消费”的…",
    "content": "岗位概述 我们正在寻找一位同时具备数据工程能力与 AI Agent 系统构建能力的工程师，参与构建企业级数据与智能体一体化基础设施。该岗位将同时覆盖两条核心技术主线： 数据基座方向：构建高质量数据链路与统一语义数据层（ ETL/ELT 、湖仓、数据治理） 智能体方向：设计与实现面向业务执行的 Agent 系统（规划、工具调用、多智能体协同、记忆与上下文管理） 你将深度参与从“数据产生 → 数据治理 → 数据服务 → Agent 消费”的完整闭环系统设计与落地。 主要职责 负责基于 Python/SQL/Spark …"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224226#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 请教九寨沟游玩攻略",
    "link": "https://www.v2ex.com/t/1224226#reply0",
    "pub_date": "2026-07-01 14:45:46",
    "author": "brader",
    "description": "从广州出发，大概 4-5 天假期，预计 10 月中下旬去。 一般去九寨沟，还搭配其他哪个地方游玩吗（不去看大熊猫）？不是很熟悉那边。 建议报团去吗？",
    "content": "从广州出发，大概 4-5 天假期，预计 10 月中下旬去。 一般去九寨沟，还搭配其他哪个地方游玩吗（不去看大熊猫）？不是很熟悉那边。 建议报团去吗？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224225#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 有没有便宜大碗的国产模型中转",
    "link": "https://www.v2ex.com/t/1224225#reply0",
    "pub_date": "2026-07-01 14:44:37",
    "author": "tt83",
    "description": "推广里都是国外那三家的中转，国产前沿模型基本十几/二十几每百万 token 了，其实也不便宜，那么有没有便宜大碗的国产模型中转？",
    "content": "推广里都是国外那三家的中转，国产前沿模型基本十几/二十几每百万 token 了，其实也不便宜，那么有没有便宜大碗的国产模型中转？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1224224#reply11",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 用 Tauri 写运维软件很好，但是？ ——OxideTerm 开发小记",
    "link": "https://www.v2ex.com/t/1224224#reply11",
    "pub_date": "2026-07-01 14:36:07",
    "author": "soleilune",
    "description": "OxideTerm 是一款我开发的免费开源的运维软件，具备 SSH 、SFTP 、端口转发、文件编辑、serial 、telnet 等功能。 GPUI 是 Zed 编辑器团队开源的 Rust 原生 UI 框架，直接用 Rust 构建桌面界面，不依赖浏览器 WebView 。最近在做 OxideTerm 的 GPUI 版本，顺便回头看了一下之前用 Tauri 的过程。我们最早用 Tauri 起步，就是因为它真的很适合快速做桌面端：前端生态…",
    "content": "OxideTerm 是一款我开发的 免费开源 的运维软件，具备 SSH 、SFTP 、端口转发、文件编辑、serial 、telnet 等功能。 GPUI 是 Zed 编辑器团队开源的 Rust 原生 UI 框架，直接用 Rust 构建桌面界面，不依赖浏览器 WebView 。 最近在做 OxideTerm 的 GPUI 版本 ，顺便回头看了一下之前用 Tauri 的过程。我们最早用 Tauri 起步，就是因为它真的很适合快速做桌面端：前端生态成熟，Rust 后端也好用，包体积小，看起来也比 Electron 清爽…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_19",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_19",
    "pub_date": "2026-07-01 14:24:56",
    "author": "",
    "description": "這怎麼說",
    "content": "這怎麼說"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16808#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "外星人M16R2装arch英伟达4070显卡，熄屏后就死机",
    "link": "https://forum.archlinuxcn.org/t/topic/16808#post_2",
    "pub_date": "2026-07-01 07:07:00",
    "author": "",
    "description": "plasma(wayland)是nouveua吗？ 非官方驱动对于睡眠的支持好像都有一定问题，如果经常遇到这样的问题，可以考虑使用nvidia官方驱动。 如果pacman启用了archlinuxcn仓库，那么可以直接下面这样。在图灵架构及以后的显卡我认为最好选择nvidia-open。 paru -S nvidia",
    "content": "plasma(wayland)是nouveua吗？ 非官方驱动对于睡眠的支持好像都有一定问题，如果经常遇到这样的问题，可以考虑使用nvidia官方驱动。 如果pacman启用了archlinuxcn仓库，那么可以直接下面这样。在图灵架构及以后的显卡我认为最好选择nvidia-open。 paru -S nvidia"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16126#post_8",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "ntfs不能挂载",
    "link": "https://forum.archlinuxcn.org/t/topic/16126#post_8",
    "pub_date": "2026-07-01 00:05:31",
    "author": "",
    "description": "没有，我直接格了，你可以试一下yay中修复ntfs的工具或到windows中用chdsk试试看能不能修好，不行的话也没法了",
    "content": "没有，我直接格了，你可以试一下yay中修复ntfs的工具或到windows中用chdsk试试看能不能修好，不行的话也没法了 因为没人知道怎么办，所以这帖子我就开着"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16126#post_7",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "ntfs不能挂载",
    "link": "https://forum.archlinuxcn.org/t/topic/16126#post_7",
    "pub_date": "2026-06-30 22:41:03",
    "author": "",
    "description": "我的也是这样的问题，你的问题后面找到解决的办法了吗",
    "content": "我的也是这样的问题，你的问题后面找到解决的办法了吗"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_18",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_18",
    "pub_date": "2026-06-30 21:39:16",
    "author": "",
    "description": "和德國可能也關係不大。 關於 mirror list 裏面列的taiwan的名字，之前有過 https://bugs.archlinux.org/task/30444 和 https://lists.archlinux.org/pipermail/arch-general/2012-July/027730.html 的討論。 現在 archweb 用的 django-counties 列出的名字，django-counties 大概採取…",
    "content": "和德國可能也關係不大。 關於 mirror list 裏面列的taiwan的名字，之前有過 https://bugs.archlinux.org/task/30444 和 https://lists.archlinux.org/pipermail/arch-general/2012-July/027730.html 的討論。 現在 archweb 用的 django-counties 列出的名字，django-counties 大概採取的是 iso-codes 中的 iso_3166-1 裏的 common_nam…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16791#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "archinstall选择中文乱码的问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16791#post_3",
    "pub_date": "2026-06-30 17:07:00",
    "author": "",
    "description": "默认的TTY不支持CJK字符显示。虽然有补丁或者kmscon之类的东西能用，但在默认的archiso中这些东西都没有。",
    "content": "默认的TTY不支持CJK字符显示。虽然有补丁或者kmscon之类的东西能用，但在默认的archiso中这些东西都没有。 非常想用中文可以开ssh连上去。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_17",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_17",
    "pub_date": "2026-06-30 15:34:16",
    "author": "",
    "description": "onikage: 可以游到台湾或美国硬刚。 和美国没什么关系啊，可以去德国。",
    "content": "onikage: 可以游到台湾或美国硬刚。 和美国没什么关系啊，可以去德国。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_16",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_16",
    "pub_date": "2026-06-30 14:56:24",
    "author": "",
    "description": "第一个这么做的人名利双收，我不反对楼主的言论，不过楼主是不是没搞清楚这是什么地方？ arch有个比这里更官方的地方。你可以到那边去。如果实在找不到，可以游到台湾或美国硬刚。",
    "content": "第一个这么做的人名利双收，我不反对楼主的言论，不过楼主是不是没搞清楚这是什么地方？ arch有个比这里更官方的地方。你可以到那边去。如果实在找不到，可以游到台湾或美国硬刚。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_15",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_15",
    "pub_date": "2026-06-30 14:25:55",
    "author": "",
    "description": "当然“管”不到，但如果真的是有价值的问题，提建议讨论讨论还是能做到的",
    "content": "当然“管”不到，但如果真的是有价值的问题，提建议讨论讨论还是能做到的"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_14",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_14",
    "pub_date": "2026-06-30 14:19:03",
    "author": "",
    "description": "嵌一个画了 Flag Emoji 的字体就好了 然后用户又不能更换自己喜欢的字体了 话说 Arch Linux CN 管得到 Arch Linux 吗...",
    "content": "嵌一个画了 Flag Emoji 的字体就好了 然后用户又不能更换自己喜欢的字体了 话说 Arch Linux CN 管得到 Arch Linux 吗..."
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_13",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_13",
    "pub_date": "2026-06-30 13:07:36",
    "author": "",
    "description": "你想想这个页面是哪年做的……",
    "content": "你想想这个页面是哪年做的……"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16822#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "librime-1:1.17.0-2 导致 fcitx5-rime 没法输出简体中文",
    "link": "https://forum.archlinuxcn.org/t/topic/16822#post_3",
    "pub_date": "2026-06-30 10:00:57",
    "author": "",
    "description": "github.com/fcitx/fcitx5-rime fcitx5-rime 切换到简体中文后输入，会导致程序崩溃 12:38AM - 30 Jun 26 UTC 01:01AM - 30 Jun 26 UTC Packages (27) capnproto-1.4.0-2 gflags-2.2.2-6 google-glog-0.7.1-2 kitemviews…-6.27.0-1 leveldb-1.23-4 librime-1…",
    "content": "github.com/fcitx/fcitx5-rime fcitx5-rime 切换到简体中文后输入，会导致程序崩溃 打开于 12:38AM - 30 Jun 26 UTC 关闭于 01:01AM - 30 Jun 26 UTC WantenMN Packages (27) capnproto-1.4.0-2 gflags-2.2.2-6 google-glog-0.7.1-2 kitemviews … -6.27.0-1 leveldb-1.23-4 librime-1:1.17.0-2 librime-dat…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16822#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "librime-1:1.17.0-2 导致 fcitx5-rime 没法输出简体中文",
    "link": "https://forum.archlinuxcn.org/t/topic/16822#post_2",
    "pub_date": "2026-06-30 08:13:02",
    "author": "",
    "description": "不一定是librime的问题，我也不知道怎么回事，今天输入法突然变成繁体了，切换回简体后输入会导致程序崩溃。",
    "content": "不一定是librime的问题，我也不知道怎么回事，今天输入法突然变成繁体了，切换回简体后输入会导致程序崩溃。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16822#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "librime-1:1.17.0-2 导致 fcitx5-rime 没法输出简体中文",
    "link": "https://forum.archlinuxcn.org/t/topic/16822#post_1",
    "pub_date": "2026-06-30 07:49:05",
    "author": "",
    "description": "切换选项后输入会导致程序崩溃，键盘按键无任何响应。 （点击了解更多详细信息） rime配置 （点击了解更多详细信息）",
    "content": "切换选项后输入会导致程序崩溃，键盘按键无任何响应。 崩溃日志 （点击了解更多详细信息） rime配置 （点击了解更多详细信息）"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16804#post_13",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "kde如何使用核显",
    "link": "https://forum.archlinuxcn.org/t/topic/16804#post_13",
    "pub_date": "2026-06-29 19:34:35",
    "author": "",
    "description": "推荐用 PCI id 来指定，因为 cardN 这个编号重启可能会变。另外就是你得确保这个环境变量在 kwin 启动前设置，且以会被 kwin 继承的方式设置，详见 arch wiki：Environment variables",
    "content": "推荐用 PCI id 来指定，因为 cardN 这个编号重启可能会变。另外就是你得确保这个环境变量在 kwin 启动前设置，且以会被 kwin 继承的方式设置，详见 arch wiki： Environment variables"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16804#post_12",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "kde如何使用核显",
    "link": "https://forum.archlinuxcn.org/t/topic/16804#post_12",
    "pub_date": "2026-06-29 19:09:12",
    "author": "",
    "description": "export KWIN_DRM_DEVICES=\"/sys/class/drm/card2:/sys/class/drm/card1\" 是这样吗，card2是我的核显",
    "content": "export KWIN_DRM_DEVICES=\"/sys/class/drm/card2:/sys/class/drm/card1\" 是这样吗，card2是我的核显 好像没啥用"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_11",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_11",
    "pub_date": "2026-06-29 15:37:49",
    "author": "",
    "description": "主要是最近chaotic下载不太顺利，试着不同顺序哪个快点，但可能有的镜像个别软件有问题，也有可能某个镜像被系统缓存了，每次哪怕重新现在也会停在同一个位置。",
    "content": "主要是最近chaotic下载不太顺利，试着不同顺序哪个快点，但可能有的镜像个别软件有问题，也有可能某个镜像被系统缓存了，每次哪怕重新现在也会停在同一个位置。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_10",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_10",
    "pub_date": "2026-06-29 15:34:21",
    "author": "",
    "description": "可以了，换了一下镜像顺序",
    "content": "可以了，换了一下镜像顺序"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16287#post_11",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "fcitx5在wayland下的chromium, electron等软件输入偶发漏字问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16287#post_11",
    "pub_date": "2026-06-29 14:40:27",
    "author": "",
    "description": "看起来貌似是被修复了，我恢复了初始设置之后没啥问题了",
    "content": "看起来貌似是被修复了，我恢复了初始设置之后没啥问题了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_12",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_12",
    "pub_date": "2026-06-29 13:21:54",
    "author": "",
    "description": "把旗帜图片替换成 emoji 似乎是个不错的提议，不过不知道在某些老旧或者奇怪的设备上会不会渲染得很奇怪。我目前见过的最坏的情况似乎就是渲染成两字母，不知道这会不会给用户带来不便",
    "content": "把旗帜图片替换成 emoji 似乎是个不错的提议，不过不知道在某些老旧或者奇怪的设备上会不会渲染得很奇怪。我目前见过的最坏的情况似乎就是渲染成两字母，不知道这会不会给用户带来不便"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_11",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_11",
    "pub_date": "2026-06-29 12:51:40",
    "author": "",
    "description": "诶，居然不是用的emoji吗……雪碧图都好多年没怎么听说过了的说。",
    "content": "诶，居然不是用的emoji吗……雪碧图都好多年没怎么听说过了的说。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_10",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_10",
    "pub_date": "2026-06-29 12:50:41",
    "author": "",
    "description": "这里还真不是 emoji，这里是雪碧图",
    "content": "这里还真不是 emoji，这里是雪碧图"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_9",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_9",
    "pub_date": "2026-06-29 11:11:26",
    "author": "",
    "description": "嗯，看起来是没下完。检查一下两边用的镜像站和网络？",
    "content": "嗯，看起来是没下完。检查一下两边用的镜像站和网络？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16397#post_9",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Linux 下真的没有输入法能媲美商业输入法吗？",
    "link": "https://forum.archlinuxcn.org/t/topic/16397#post_9",
    "pub_date": "2026-06-29 11:01:13",
    "author": "",
    "description": "不要搞什么拼音输入法了，来跟我一起加入语音识别的世界吧。https://github.com/devcxl/fcitx5-voice-input",
    "content": "不要搞什么拼音输入法了，来跟我一起加入语音识别的世界吧。 https://github.com/devcxl/fcitx5-voice-input"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16811#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "给 Fcitx5 写了个语音输入插件， VAD 自动分割，不用按键",
    "link": "https://forum.archlinuxcn.org/t/topic/16811#post_2",
    "pub_date": "2026-06-29 10:45:25",
    "author": "",
    "description": "演示demo在此。",
    "content": "演示demo在此。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_8",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_8",
    "pub_date": "2026-06-29 10:41:51",
    "author": "",
    "description": "文件大小不对，完整文件800个M左右，但在manaro上只下载了100多个M",
    "content": "文件大小不对，完整文件800个M左右，但在manaro上只下载了100多个M"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_7",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_7",
    "pub_date": "2026-06-29 10:39:07",
    "author": "",
    "description": "出问题的manjaro上： sha256sum wps-office-cn-12.1.2.26885-1-x86_64.pkg.tar.zst arch上：",
    "content": "出问题的manjaro上： sha256sum wps-office-cn-12.1.2.26885-1-x86_64.pkg.tar.zst 20ffa739b0cb78eb2c24b181531cc1924017e43256a2b68b705fed65ec55c5ca wps-office-cn-12.1.2.26885-1-x86_64.pkg.tar.zst arch上： 727179d255ab214bc9d21566c3bbfd9830cfb15d14a8ae38756a07155ad0b4a9 wps…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_6",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_6",
    "pub_date": "2026-06-29 09:36:08",
    "author": "",
    "description": "好大的包。sha256sum /var/cache/pacman/pkg/wps-office-cn-12.1.2.26885-1-x86_64.pkg.tar.zst看看？",
    "content": "好大的包。 sha256sum /var/cache/pacman/pkg/wps-office-cn-12.1.2.26885-1-x86_64.pkg.tar.zst 看看？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_5",
    "pub_date": "2026-06-29 09:16:31",
    "author": "",
    "description": "另外，发生问题的是manjaro系统，另一台arch + cathyos内核的没有问题。",
    "content": "另外，发生问题的是manjaro系统，另一台arch + cathyos内核的没有问题。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_4",
    "pub_date": "2026-06-29 09:07:36",
    "author": "",
    "description": "删除下一次操作也同样错误",
    "content": "删除下一次操作也同样错误"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16796#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装chaotic aur的软件包，总是报 xx.pkg.tar.zst.已损坏 (无效或已损坏的软件包 (检验值)).",
    "link": "https://forum.archlinuxcn.org/t/topic/16796#post_3",
    "pub_date": "2026-06-29 09:06:14",
    "author": "",
    "description": ":: 文件 /var/cache/pacman/pkg/wps-office-cn-12.1.2.26885-1-x86_64.pkg.tar.zst 已损坏 (无效或已损坏的软件包 (检验值)).",
    "content": ":: 文件 /var/cache/pacman/pkg/wps-office-cn-12.1.2.26885-1-x86_64.pkg.tar.zst 已损坏 (无效或已损坏的软件包 (检验值)). 打算删除吗？ [Y/n] n 错误：无法提交处理 (无效或已损坏的软件包) 发生错误，没有软件包被更新。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16812#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "安装hyprland后，出现错误提示",
    "link": "https://forum.archlinuxcn.org/t/topic/16812#post_1",
    "pub_date": "2026-06-29 08:08:22",
    "author": "",
    "description": "安装hyprland后进入桌面时提示这个，解决办法是什么样的请指导一下",
    "content": "安装hyprland后进入桌面时提示这个，解决办法是什么样的请指导一下"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16811#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "给 Fcitx5 写了个语音输入插件， VAD 自动分割，不用按键",
    "link": "https://forum.archlinuxcn.org/t/topic/16811#post_1",
    "pub_date": "2026-06-29 06:59:41",
    "author": "",
    "description": "github.com GitHub - devcxl/fcitx5-voice-input: Fcitx5 voice input addon — PulseAudio/PipeWire... Fcitx5 voice input addon — PulseAudio/PipeWire capture, Silero VAD, OpenAI-compatible ASR 先说说为什么会有这个项目。 我一直想搞 Linux 下的语音输入，…",
    "content": "github.com GitHub - devcxl/fcitx5-voice-input: Fcitx5 voice input addon — PulseAudio/PipeWire... Fcitx5 voice input addon — PulseAudio/PipeWire capture, Silero VAD, OpenAI-compatible ASR 先说说为什么会有这个项目。 我一直想搞 Linux 下的语音输入，最开始找到的是 fcitx5-vinput。这项目想法很好，走本地模型，完全离线…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_9",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_9",
    "pub_date": "2026-06-28 22:22:45",
    "author": "",
    "description": "地区指示字符如何渲染是由你使用的字体决定的。你可以换个你喜欢的字体。",
    "content": "地区指示字符如何渲染是由你使用的字体决定的。你可以换个你喜欢的字体。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_8",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_8",
    "pub_date": "2026-06-28 21:52:14",
    "author": "",
    "description": "只是你不承认而已，不要强迫别人",
    "content": "只是你不承认而已，不要强迫别人"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_7",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_7",
    "pub_date": "2026-06-28 21:26:05",
    "author": "",
    "description": "更重要的是他用的那个旗子的问题……那个标志是不被承认的",
    "content": "更重要的是他用的那个旗子的问题……那个标志是不被承认的"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_6",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_6",
    "pub_date": "2026-06-28 18:19:37",
    "author": "",
    "description": "这种按网络划分地域的，实际上基本上是用的ccTLD那套划分体系，毕竟除了少数代管的情况之外，这些实体都有自己的网络信息中心（NIC）来管理自己的网络，无论是网络上还是物理上都会比较接近。",
    "content": "这种按网络划分地域的，实际上基本上是用的 ccTLD 那套划分体系，毕竟除了少数代管的情况之外，这些实体都有自己的网络信息中心（NIC）来管理自己的网络，无论是网络上还是物理上都会比较接近。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_5",
    "pub_date": "2026-06-28 18:16:19",
    "author": "",
    "description": "当是就看见了一个台湾，忽略了上面的hongkong 抱歉哈香港也是中国的",
    "content": "当是就看见了一个台湾，忽略了上面的hongkong 抱歉哈香港也是中国的"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_4",
    "pub_date": "2026-06-28 18:09:52",
    "author": "",
    "description": "zxxc: 独立国家 嗯嗯，我们还有个独立国家叫「全世界」……",
    "content": "zxxc: 独立国家 嗯嗯，我们还有个独立国家叫「全世界」……"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_3",
    "pub_date": "2026-06-28 18:08:01",
    "author": "",
    "description": "zxxc: 我发现arch Linux官方网站Arch Linux - Downloads下载镜像页面将Taiwan（台湾）和各国并列为独立国家，违背一个中国事实。 你看到还有 Hong Kong 了吗？",
    "content": "zxxc: 我发现arch Linux官方网站 Arch Linux - Downloads 下载镜像页面将 Taiwan（台湾）和各国并列为独立国家 ，违背一个中国事实。 你看到还有 Hong Kong 了吗？ 其实整个界面完全没有提 country,也没有提独立。不要太过敏感了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_2",
    "pub_date": "2026-06-28 18:00:35",
    "author": "",
    "description": "此页面好像没有任何地方提及“country”这个词",
    "content": "此页面好像没有任何地方提及“country”这个词"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16810#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "诉求：archlinux在下载页将台湾列为国家！违背一个中国原则！",
    "link": "https://forum.archlinuxcn.org/t/topic/16810#post_1",
    "pub_date": "2026-06-28 17:56:07",
    "author": "",
    "description": "我发现arch Linux官方网站Arch Linux - Downloads下载镜像页面将Taiwan（台湾）和各国并列为独立国家，违背一个中国事实。 根据联合国及全球绝大多数国家公认的一个中国原则，台湾是中国的省级地区，应当把台湾省的镜像站并入中国的镜像站 希望中文社区维护者们帮忙对接上游开发团队，修正此页面错误的地区分类，截图证据在此↓",
    "content": "我发现arch Linux官方网站 Arch Linux - Downloads 下载镜像页面将 Taiwan（台湾）和各国并列为独立国家 ，违背一个中国事实。 根据联合国及全球绝大多数国家公认的一个中国原则，台湾是中国的省级地区，应当把台湾省的镜像站并入中国的镜像站 希望中文社区维护者们帮忙对接上游开发团队，修正此页面错误的地区分类，截图证据在此↓"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16804#post_11",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "kde如何使用核显",
    "link": "https://forum.archlinuxcn.org/t/topic/16804#post_11",
    "pub_date": "2026-06-28 17:26:01",
    "author": "",
    "description": "看上去还真是连在核显上的。那就试试上面说的环境变量吧",
    "content": "看上去还真是连在核显上的。那就试试上面说的环境变量吧"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16804#post_10",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "kde如何使用核显",
    "link": "https://forum.archlinuxcn.org/t/topic/16804#post_10",
    "pub_date": "2026-06-28 16:46:37",
    "author": "",
    "description": "  ~ sudo drm_info -j | curl -d @- https://drmdb.emersion.fr/submit 3s  04:45:56 PM  https://drmdb.emersion.fr/snapshots/9a7f08b61c84 https://drmdb.emersion.fr/snapshots/49f7e9aec73f",
    "content": "  ~ sudo drm_info -j | curl -d @- https://drmdb.emersion.fr/submit 3s  04:45:56 PM  drmModeGetPropertyBlob: No such file or directory drmModeGetPropertyBlob: No such file or directory drmModeGetPropertyBlob: No such file or directory drmModeGetPropertyBlob…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16808#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "外星人M16R2装arch英伟达4070显卡，熄屏后就死机",
    "link": "https://forum.archlinuxcn.org/t/topic/16808#post_1",
    "pub_date": "2026-06-28 13:04:48",
    "author": "",
    "description": "我有一个外星人M16R2电脑，英伟达4070laptop显卡，但是这个电脑装arch之后，一旦自动熄屏，就再也不能唤醒，只能进tty下reboot指令，有没有什么好办法能解决这一问题现在状态时，显卡直接驱动plasma(Wayland）",
    "content": "我有一个外星人M16R2电脑，英伟达4070laptop显卡，但是这个电脑装arch之后，一旦自动熄屏，就再也不能唤醒，只能进tty下reboot指令，有没有什么好办法能解决这一问题现在状态时，显卡直接驱动plasma(Wayland）"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16805#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "系统崩溃,整个界面卡住，altf4也没用",
    "link": "https://forum.archlinuxcn.org/t/topic/16805#post_5",
    "pub_date": "2026-06-27 22:52:46",
    "author": "",
    "description": "之前还有更难蚌的 开机自检过不去，最后发现是有个内存槽坏了",
    "content": "之前还有更难蚌的 开机自检过不去，最后发现是有个内存槽坏了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16805#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "系统崩溃,整个界面卡住，altf4也没用",
    "link": "https://forum.archlinuxcn.org/t/topic/16805#post_4",
    "pub_date": "2026-06-27 22:49:19",
    "author": "",
    "description": "真坏了这个时间也真南蚌了",
    "content": "真坏了这个时间也真南蚌了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16805#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "系统崩溃,整个界面卡住，altf4也没用",
    "link": "https://forum.archlinuxcn.org/t/topic/16805#post_3",
    "pub_date": "2026-06-27 22:31:20",
    "author": "",
    "description": "你先看眼是不是内存条坏了?",
    "content": "你先看眼是不是内存条坏了? 我之前遇到过出现 nvidia-drm 的报错，最后安装Windows发现安装显卡驱动后开机就蓝屏，找人修发现是内存条坏了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16804#post_9",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "kde如何使用核显",
    "link": "https://forum.archlinuxcn.org/t/topic/16804#post_9",
    "pub_date": "2026-06-27 21:39:57",
    "author": "",
    "description": "和 Kwin 相关的环境变量：KDE/plasma/kwin: Environment Variables",
    "content": "和 Kwin 相关的环境变量： KDE/plasma/kwin: Environment Variables 可以在 ~/.config/plasma-workspace/env/ 里设置环境变量，这样就只影响 kwin。我记得我过去搞过类似的操作，具体是哪些环境变量我记不大清了。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16804#post_8",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "kde如何使用核显",
    "link": "https://forum.archlinuxcn.org/t/topic/16804#post_8",
    "pub_date": "2026-06-27 21:33:10",
    "author": "",
    "description": "你确定在核显控制笔记本内屏的情况下 kde 也在独显跑吗？安装一下 drm-info 这个包，然后运行 sudo drm_info -j | curl -d @- https://drmdb.emersion.fr/submit 上传，把链接发出来看一下。 如果确认无误的话，可以设置 KWIN_DRM_DEVICES 环境变量来手动设置使用的显卡",
    "content": "你确定在核显控制笔记本内屏的情况下 kde 也在独显跑吗？安装一下 drm-info 这个包，然后运行 sudo drm_info -j | curl -d @- https://drmdb.emersion.fr/submit 上传，把链接发出来看一下。 如果确认无误的话，可以设置 KWIN_DRM_DEVICES 环境变量来手动设置使用的显卡"
  }
];

export default jsonData;
