const jsonData = [
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727617-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "巴基斯坦家宽或者尼日利亚家宽VPS",
    "link": "https://www.nodeseek.com/post-727617-1",
    "pub_date": "2026-05-13 07:55:05",
    "author": "",
    "description": "求购尼日利亚家宽或者是巴基斯坦家宽",
    "content": "求购尼日利亚家宽或者是巴基斯坦家宽"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727616-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "甲骨文负载太低，用保活脚本",
    "link": "https://www.nodeseek.com/post-727616-1",
    "pub_date": "2026-05-13 07:51:34",
    "author": "",
    "description": "为了避免甲骨文的闲置收回规定，跑了保活脚本，使负载率稳定在1-14之间，不知道有没有用，更不知道会不会被检测异常，有过来人吗？指点一下",
    "content": "为了避免甲骨文的闲置收回规定，跑了保活脚本，使负载率稳定在1-14之间，不知道有没有用，更不知道会不会被检测异常，有过来人吗？指点一下"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727615-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "BreadCloud面包云 US 0.6刀小鸡",
    "link": "https://www.nodeseek.com/post-727615-1",
    "pub_date": "2026-05-13 07:49:23",
    "author": "",
    "description": "4r，给账密，邮箱是主力，给不了，如果可以改邮，可以配合改邮，不知道能不能改",
    "content": "4r，给账密，邮箱是主力，给不了，如果可以改邮，可以配合改邮，不知道能不能改"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727614-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "请问有代开team车的可能吗？",
    "link": "https://www.nodeseek.com/post-727614-1",
    "pub_date": "2026-05-13 07:40:07",
    "author": "",
    "description": "有没有可能有大佬能帮忙代开一辆team车，然后每月续费呢？",
    "content": "有没有可能有大佬能帮忙代开一辆team车，然后每月续费呢？"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727613-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "【留档】云悠的 ip 这么有意思的吗，注册地就是 CN",
    "link": "https://www.nodeseek.com/post-727613-1",
    "pub_date": "2026-05-13 07:37:44",
    "author": "",
    "description": "这算送中呢还是算没问题呢hhhttps://Report.Check.Place/ip/OHEXA8IRF.svg",
    "content": "这算送中呢还是算没问题呢hhhttps://Report.Check.Place/ip/OHEXA8IRF.svg"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727612-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "母鸡如何开安卓小鸡和ios小鸡？",
    "link": "https://www.nodeseek.com/post-727612-1",
    "pub_date": "2026-05-13 07:35:57",
    "author": "",
    "description": "母鸡是windows，如何开安卓和ios小鸡？",
    "content": "母鸡是windows，如何开安卓和ios小鸡？"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727611-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "各位哪有这电影在线",
    "link": "https://www.nodeseek.com/post-727611-1",
    "pub_date": "2026-05-13 07:29:42",
    "author": "",
    "description": "给阿嫲的情书线上有嘛谢谢",
    "content": "给阿嫲的情书线上有嘛谢谢"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212293#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Ai2You智友社] Ai2You 智友社---让更多的人用上更好的 Ai，解决您的 AI 焦虑",
    "link": "https://www.v2ex.com/t/1212293#reply0",
    "pub_date": "2026-05-13 07:27:59",
    "author": "Ai2You",
    "description": "首先感谢 V 版管理和 V 版各位朋友一直以来的支持！！ 鉴于目前国外主流 AI 的正价订购价格昂贵，我们发现市面上有不少的特价 AI 渠道，可惜质量参差不齐，为了节省大家的时间跟金钱，我们花了不少精力对各个渠道商的特价 AI 进行了购买评测，再从中选取稳定的渠道上架出售。 我们智友社的初衷是帮大家寻找市面上稳定的主流 AI 特价渠道，也欢迎大家随时跟我们推荐稳定的特价 AI 渠道，这样能让更多的人能受益！ 虽然我们找到的渠道稳定，但是…",
    "content": "首先感谢 V 版管理和 V 版各位朋友一直以来的支持！！ 鉴于目前国外主流 AI 的正价订购价格昂贵，我们发现市面上有不少的特价 AI 渠道，可惜质量参差不齐，为了节省大家的时间跟金钱，我们花了不少精力对各个渠道商的特价 AI 进行了购买评测，再从中选取稳定的渠道上架出售。 我们智友社的初衷是帮大家寻找市面上稳定的主流 AI 特价渠道，也欢迎大家随时跟我们推荐稳定的特价 AI 渠道，这样能让更多的人能受益！ 虽然我们找到的渠道稳定，但是我们定价确非常克制，扣去我们的成本，到手其实微利，但是我们愿意做下去，因为我们觉…"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727610-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "破案了？美西 GIA 年付 50 刀，香港 GIA 月付 33 刀",
    "link": "https://www.nodeseek.com/post-727610-1",
    "pub_date": "2026-05-13 07:26:04",
    "author": "",
    "description": "一直想不通，都是电信GIA。美西搬瓦工、DMIT经常有年付50-80刀的促销，用起来也挺稳。反观香港GIA，不说月付30刀起步，那些绝版机器溢价几千块竟然还有人收。​大家常说“物以稀为贵”，难道深港之间的那几根光缆，比跨太平洋的海底光缆还要贵、还要窄吗？AI跟我说是因为海缆口子大，陆缆配额死。但我寻思，香港离得这么",
    "content": "一直想不通，都是电信GIA。美西搬瓦工、DMIT经常有年付50-80刀的促销，用起来也挺稳。反观香港GIA，不说月付30刀起步，那些绝版机器溢价几千块竟然还有人收。​大家常说“物以稀为贵”，难道深港之间的那几根光缆，比跨太平洋的海底光缆还要贵、还要窄吗？AI跟我说是因为海缆口子大，陆缆配额死。但我寻思，香港离得这么"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727609-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "币安出505个U",
    "link": "https://www.nodeseek.com/post-727609-1",
    "pub_date": "2026-05-13 07:24:57",
    "author": "",
    "description": "RT",
    "content": "RT"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727608-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "[收]evoxt 马来西亚 2.84刀月付250g",
    "link": "https://www.nodeseek.com/post-727608-1",
    "pub_date": "2026-05-13 07:24:35",
    "author": "",
    "description": "剩余价值收这款，如果你论坛级别更高，就我先支付宝口令付款，否则你先转移邮箱。",
    "content": "剩余价值收这款，如果你论坛级别更高，就我先支付宝口令付款，否则你先转移邮箱。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727607-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "我发现我想要的不是鸡鸡，而是一种人性的贪婪。",
    "link": "https://www.nodeseek.com/post-727607-1",
    "pub_date": "2026-05-13 07:20:08",
    "author": "",
    "description": "当看到别人说收到一台便宜的好鸡鸡的时候。心里就开始别扭，就开始嫉妒，就开始自己也想要了。但是事实上手里已经有很多鸡鸡了，甚至很多都吃灰了。这种欲望只是一种单纯的贪婪和炫耀虚荣心作祟。",
    "content": "当看到别人说收到一台便宜的好鸡鸡的时候。心里就开始别扭，就开始嫉妒，就开始自己也想要了。但是事实上手里已经有很多鸡鸡了，甚至很多都吃灰了。这种欲望只是一种单纯的贪婪和炫耀虚荣心作祟。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727606-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "这家是不是又被打了",
    "link": "https://www.nodeseek.com/post-727606-1",
    "pub_date": "2026-05-13 07:18:36",
    "author": "",
    "description": "",
    "content": ""
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727605-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "出racknerd 1c1g 价格60r到明年5月",
    "link": "https://www.nodeseek.com/post-727605-1",
    "pub_date": "2026-05-13 07:18:24",
    "author": "",
    "description": "1GBKVMVPSSpecial-racknerd-dc855ad(05/12/2026-05/11/2027)$21.99USDExtraIPv4:NoneOperatingSystem:Ubuntu24.0464BitLocation:SanJose,CA(TestIP:192.210.207.88)RAM:1",
    "content": "1GBKVMVPSSpecial-racknerd-dc855ad(05/12/2026-05/11/2027)$21.99USDExtraIPv4:NoneOperatingSystem:Ubuntu24.0464BitLocation:SanJose,CA(TestIP:192.210.207.88)RAM:1"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727604-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "收台续费10左右的RN",
    "link": "https://www.nodeseek.com/post-727604-1",
    "pub_date": "2026-05-13 07:14:29",
    "author": "",
    "description": "主用机器死了，收个备用",
    "content": "主用机器死了，收个备用"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727603-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "早上起来第一件事就是看dmit",
    "link": "https://www.nodeseek.com/post-727603-1",
    "pub_date": "2026-05-13 07:10:13",
    "author": "",
    "description": "价格现在如何了。",
    "content": "价格现在如何了。"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727602-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "佬们是怎么监听RN的放货通知的",
    "link": "https://www.nodeseek.com/post-727602-1",
    "pub_date": "2026-05-13 07:09:29",
    "author": "",
    "description": "虽然还没到黑五，但特价机平常是不是也会放点货出来？要怎么监控补货消息，能尽快抢到呢？",
    "content": "虽然还没到黑五，但特价机平常是不是也会放点货出来？要怎么监控补货消息，能尽快抢到呢？"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727601-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "【求购】美国静态 ISP / 固定 IP 节点，4节点，预算 40 元/月以内，支持 SOCKS5",
    "link": "https://www.nodeseek.com/post-727601-1",
    "pub_date": "2026-05-13 07:08:33",
    "author": "",
    "description": "各位大佬好，想找一组美国方向的稳定静态ISP节点，主要需求如下：地区：美国类型：静态ISP/固定IP节点数：4个左右协议：希望可直接提供SOCKS5，如有其他可直接接入的协议也可以说明用途：海外业务访问与日常网页登录，要求环境稳定，不频繁更换IP稳定性：优先长期稳定、可持续使用的线路速度：够日常访问和页面加载即可，",
    "content": "各位大佬好，想找一组美国方向的稳定静态ISP节点，主要需求如下：地区：美国类型：静态ISP/固定IP节点数：4个左右协议：希望可直接提供SOCKS5，如有其他可直接接入的协议也可以说明用途：海外业务访问与日常网页登录，要求环境稳定，不频繁更换IP稳定性：优先长期稳定、可持续使用的线路速度：够日常访问和页面加载即可，"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727600-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "新加坡现在有什么优质线路的机器吗？",
    "link": "https://www.nodeseek.com/post-727600-1",
    "pub_date": "2026-05-13 07:01:19",
    "author": "",
    "description": "好像没听说过cn2gia或者9929…",
    "content": "好像没听说过cn2gia或者9929…"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727599-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "一根入户光纤有办法使用两家运营商吗",
    "link": "https://www.nodeseek.com/post-727599-1",
    "pub_date": "2026-05-13 06:53:52",
    "author": "",
    "description": "rt",
    "content": "rt"
  },
  {
    "id": "论坛-NodeSeek-https://www.nodeseek.com/post-727597-1",
    "feed_name": "NodeSeek",
    "category": "论坛",
    "title": "大伙看看这是GPT bug号吗",
    "link": "https://www.nodeseek.com/post-727597-1",
    "pub_date": "2026-05-13 06:48:10",
    "author": "",
    "description": "号到期了,怎么还是plus",
    "content": "号到期了,怎么还是plus"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16535#post_10",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助]git-remote-https的cpu占用问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16535#post_10",
    "pub_date": "2026-05-13 06:23:39",
    "author": "",
    "description": "这就不奇怪了，记得挂梯子（",
    "content": "这就不奇怪了，记得挂梯子（"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212292#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[职场话题] 35 岁，美院毕业，创业十年：从“圈养动物”到“野生动物”的独立开发之路",
    "link": "https://www.v2ex.com/t/1212292#reply5",
    "pub_date": "2026-05-13 04:46:36",
    "author": "hashtome",
    "description": "背景： 08 年上大学，美术专业（八大美院之一）。 坐标：目前在老家，折腾独立开发中。 1. 阴差阳错的艺考之路 我是 08 年上的大学。其实回想起来，我属于那种典型的“被指挥棒拨弄”的学生。那时候信息封闭，高考落榜后听朋友建议说“艺考能考上”，就突击学了半年。其实我骨子里一直对美术有点天分，只是之前一直被圈在文理科的死胡同里。最后顺利考入了八大美院之一，也算是人生第一个转折点。 08 年那会儿，国内经济非常有朝气。在美院里，身边同学大…",
    "content": "背景： 08 年上大学，美术专业（八大美院之一）。 坐标：目前在老家，折腾独立开发中。 1. 阴差阳错的艺考之路 我是 08 年上的大学。其实回想起来，我属于那种典型的“被指挥棒拨弄”的学生。那时候信息封闭，高考落榜后听朋友建议说“艺考能考上”，就突击学了半年。其实我骨子里一直对美术有点天分，只是之前一直被圈在文理科的死胡同里。最后顺利考入了八大美院之一，也算是人生第一个转折点。 08 年那会儿，国内经济非常有朝气。在美院里，身边同学大多家境优渥，相比之下我属于家庭条件平平的那一类。为了生活，我从大一就开始在校外打…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212291#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[VXNA] 申请收录个人博客: https://blog.mxdyeah.com",
    "link": "https://www.v2ex.com/t/1212291#reply0",
    "pub_date": "2026-05-13 01:07:00",
    "author": "mxdyeah",
    "description": "希望 VXNA 能够收录我的个人博客 :) 域名: https://blog.mxdyeah.com RSS: https://blog.mxdyeah.com/feed @Livid ，谢谢。 十分感谢。",
    "content": "希望 VXNA 能够收录我的个人博客 :) 域名: https://blog.mxdyeah.com RSS: https://blog.mxdyeah.com/feed @ Livid ，谢谢。 十分感谢。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212289#reply6",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] Android 开发如何 vibe coding",
    "link": "https://www.v2ex.com/t/1212289#reply6",
    "pub_date": "2026-05-13 00:32:53",
    "author": "Suger828",
    "description": "没用 ai 开发过安卓项目, 感觉无论原生还是跨端用 claude code 之类的都不方便,没有虚拟机用来调试",
    "content": "没用 ai 开发过安卓项目, 感觉无论原生还是跨端用 claude code 之类的都不方便,没有虚拟机用来调试"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212287#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] Pet Gatekeeper：让你家的宠物接管你的屏幕",
    "link": "https://www.v2ex.com/t/1212287#reply0",
    "pub_date": "2026-05-13 00:22:59",
    "author": "x1shir",
    "description": "灵感来自最近推上爆火的 Cat Gatekeeper：当你沉迷娱乐网站太久，它会跳出来打断你。但原版不能自定义宠物，这让家里有毛孩子的我怎么忍？ 于是我直接用 Claude Code 干出了增强版： AI 视频生成：接入 Seedance 2.0 ，支持上传自家宠物照片，一键生成专属的透明背景视频（ API 成本确实极高，所以定价略贵，望理解）。 全平台覆盖：不仅支持浏览器插件，还顺手撸了桌面端（ Mac/Win ）。 社区生态：不想花…",
    "content": "灵感来自最近推上爆火的 Cat Gatekeeper：当你沉迷娱乐网站太久，它会跳出来打断你。但原版不能自定义宠物，这让家里有毛孩子的我怎么忍？ 于是我直接用 Claude Code 干出了增强版： AI 视频生成：接入 Seedance 2.0 ，支持上传自家宠物照片，一键生成专属的透明背景视频（ API 成本确实极高，所以定价略贵，望理解）。 全平台覆盖：不仅支持浏览器插件，还顺手撸了桌面端（ Mac/Win ）。 社区生态：不想花钱生成也没问题，内置了多只萌宠，也可以兑换其他用户公开分享的宠物。 目前进度： …"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212286#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Android] 关于一些 Android App 对 Google 密码管理器（Google Password Manager）及密码管理器的自动填充的支持情况？",
    "link": "https://www.v2ex.com/t/1212286#reply0",
    "pub_date": "2026-05-13 00:08:15",
    "author": "bclerdx",
    "description": "很好奇，为何有些 Android App 能支持当你第一次手动输入账密并登录成功后，会提示你“是否保存密码？”，那么下次你再次登录的时候，就会自动把账密填充进去，然后点登录就可以了。而有些 Android App 确不支持 Google 密码管理器（ Google Password Manager ）的保存与填充呢？这是什么原因造成的？",
    "content": "很好奇，为何有些 Android App 能支持当你第一次手动输入账密并登录成功后，会提示你“是否保存密码？”，那么下次你再次登录的时候，就会自动把账密填充进去，然后点登录就可以了。而有些 Android App 确不支持 Google 密码管理器（ Google Password Manager ）的保存与填充呢？这是什么原因造成的？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212285#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[科技] 大家对于 Anthropic 估值的看法",
    "link": "https://www.v2ex.com/t/1212285#reply5",
    "pub_date": "2026-05-13 00:07:06",
    "author": "sdzg",
    "description": "近三个月，anthropic 估值从 3800 亿涨到了最近的 9000 亿。大家觉得它上市后能到什么什么水平。单单挣程序员的钱能支撑这么高的估值吗。",
    "content": "近三个月，anthropic 估值从 3800 亿涨到了最近的 9000 亿。大家觉得它上市后能到什么什么水平。单单挣程序员的钱能支撑这么高的估值吗。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212284#reply7",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Apple] 紧急提醒：在国行 Mac 上开了 Apple Intelligence 的朋友，请不要升级到最新的 26.5",
    "link": "https://www.v2ex.com/t/1212284#reply7",
    "pub_date": "2026-05-13 00:03:08",
    "author": "neiltroyer849",
    "description": "如题，今天刚出来手一滑点了升级，结果可用的 Apple Intelligence 所有功能全部失效。现在悔不当初正在紧急做 U 盘降级中，还不知道能不能保资料中。后悔不迭，希望给朋友们提个醒吧",
    "content": "如题，今天刚出来手一滑点了升级，结果可用的 Apple Intelligence 所有功能全部失效。现在悔不当初正在紧急做 U 盘降级中，还不知道能不能保资料中。后悔不迭，希望给朋友们提个醒吧"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212283#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] 花 50～ 80w 招一个全栈开发的工程师，有人来吗？",
    "link": "https://www.v2ex.com/t/1212283#reply0",
    "pub_date": "2026-05-12 23:42:34",
    "author": "hcs66",
    "description": "全栈开发工程师（ Agent 方向 | 急招） 公司介绍 Kapibala 正组建全球化 AI 团队,聚焦 Sales AGI——覆盖获客、触达、谈判、成交、交付全链路的商业智能体,运行于主流 IM 平台。 产品已进入付费内测,被头部加密交易所、Web3/RWA 、跨境广告等客户采用,在手签约亿级 RMB,Pre-Seed 已完成。 海外独立数据渠道构成核心护城河。团队<10 人:CEO 连续创业成功并退出实现变现;CTO 现任字节 T…",
    "content": "全栈开发工程师（ Agent 方向 | 急招） 公司介绍 Kapibala 正组建全球化 AI 团队,聚焦 Sales AGI——覆盖获客、触达、谈判、成交、交付全链路的商业智能体,运行于主流 IM 平台。 产品已进入付费内测,被头部加密交易所、Web3/RWA 、跨境广告等客户采用,在手签约亿级 RMB,Pre-Seed 已完成。 海外独立数据渠道构成核心护城河。团队&lt;10 人:CEO 连续创业成功并退出实现变现;CTO 现任字节 TRAE 国际顾问; AI 团队来自中科院、南洋理工、悉尼大学硕博。与 MB…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212282#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] [自荐] fmhy 的多语言版本",
    "link": "https://www.v2ex.com/t/1212282#reply0",
    "pub_date": "2026-05-12 23:36:57",
    "author": "vkccchannn",
    "description": "fmhy 号称是互联网上最大的免费资源合集，但官方只有英文版本，对于部分用户不太友好，我做了一个多语言版本：ifmhy（目前只翻译和中文和日语）。不过还有一个问题：收录的资源大部分是英文的，需要想法办解决。。",
    "content": "fmhy 号称是互联网上最大的免费资源合集，但官方只有英文版本，对于部分用户不太友好，我做了一个多语言版本： ifmhy （目前只翻译和中文和日语）。不过还有一个问题：收录的资源大部分是英文的，需要想法办解决。。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212281#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 最近拿 AI 撸了一个隐私优先的“卡片式”书签管理插件：书签白板",
    "link": "https://www.v2ex.com/t/1212281#reply0",
    "pub_date": "2026-05-12 23:34:55",
    "author": "k332159915",
    "description": "各位大佬好，最近自己动手写了一个 Chrome 插件：书签白板。 起因：传统的书签栏文件夹套文件夹，找起来太心累；市面上有些插件又太重，还要登录账号。 我想要一个像“看板”一样直观，且数据绝对安全的工具。 核心逻辑： 视觉化：书签不再是冷冰冰的文字，而是像卡片一样排在白板上。 纯本地： 隐私第一，不设服务器，不上传任何数据，你的书签只属于你。 轻量： 支持侧边栏呼出，不干扰正常浏览。 目前状态：版本刚过审，目前还在持续开发中（ TODO…",
    "content": "各位大佬好，最近自己动手写了一个 Chrome 插件：书签白板。 起因：传统的书签栏文件夹套文件夹，找起来太心累；市面上有些插件又太重，还要登录账号。 我想要一个像“看板”一样直观，且数据绝对安全的工具。 核心逻辑： 视觉化：书签不再是冷冰冰的文字，而是像卡片一样排在白板上。 纯本地： 隐私第一，不设服务器，不上传任何数据，你的书签只属于你。 轻量： 支持侧边栏呼出，不干扰正常浏览。 目前状态：版本刚过审，目前还在持续开发中（ TODO：优化视觉 UI 、增加更多分组图标等）。 商店地址： https://chro…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212280#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] 分享一个 tailscale peer relay 相比自建 derp 的优势",
    "link": "https://www.v2ex.com/t/1212280#reply1",
    "pub_date": "2026-05-12 23:31:52",
    "author": "haukuen",
    "description": "这件事有个背景故事：我以前一直是自建的 derp 来中继，体验一直很好，有次朋友的一台 nas 分享到我的 tailnet ，控制面板一切正常但当时就是访问不了。过了好几天排查出来是因为我自建 derp 后就关闭了官方的中继节点，朋友分享的设备不会走我自建中继，又打不了洞所以一直连不上，最后开启官方中继后解决此问题。 今天搞了个 peer relay 玩，无意中发现朋友的那台 nas 竟然会走我 tailnet 里的这台 peer re…",
    "content": "这件事有个背景故事：我以前一直是自建的 derp 来中继，体验一直很好，有次朋友的一台 nas 分享到我的 tailnet ，控制面板一切正常但当时就是访问不了。过了好几天排查出来是因为我自建 derp 后就关闭了官方的中继节点，朋友分享的设备不会走我自建中继，又打不了洞所以一直连不上，最后开启官方中继后解决此问题。 今天搞了个 peer relay 玩，无意中发现朋友的那台 nas 竟然会走我 tailnet 里的这台 peer relay 节点，然后手动测试了一下。 上图是 ping 朋友的设备，可以看到只会走…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212279#reply2",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[macOS] 豆包输入法 mac 版来了",
    "link": "https://www.v2ex.com/t/1212279#reply2",
    "pub_date": "2026-05-12 23:26:27",
    "author": "Johnnysx",
    "description": "用过的来说下怎么样",
    "content": "用过的来说下怎么样"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212278#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] 北京招慕 ai 产品经理",
    "link": "https://www.v2ex.com/t/1212278#reply1",
    "pub_date": "2026-05-12 23:18:41",
    "author": "zh1997",
    "description": "千问和元宝招慕 ai 产品经理 千问需要语音经验， 元宝需要大厂经验 年龄 35 岁以下，本硕均要 985 或 211 还有很多 tob 岗位（在线教育，国企等） 有兴趣联系微信：ifloor",
    "content": "千问和元宝招慕 ai 产品经理 千问需要语音经验， 元宝需要大厂经验 年龄 35 岁以下，本硕均要 985 或 211 还有很多 tob 岗位（在线教育，国企等） 有兴趣联系微信：ifloor"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16535#post_9",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助]git-remote-https的cpu占用问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16535#post_9",
    "pub_date": "2026-05-12 23:10:31",
    "author": "",
    "description": "抱歉工作比较忙，这个情况一般是我在不用魔法更新系统paru -Syu时会出现的情况，如果带梯子的话是不会这样的",
    "content": "抱歉工作比较忙，这个情况一般是我在不用魔法更新系统 paru -Syu 时会出现的情况，如果带梯子的话是不会这样的"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212277#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Hermes Agent] Hermes TTS（语音回复， Discord 语音频道交互）本地搭建分享（4GB 显存要求）",
    "link": "https://www.v2ex.com/t/1212277#reply0",
    "pub_date": "2026-05-12 23:09:22",
    "author": "sentinelK",
    "description": "简而言之：Fish Speech 1.5 + 真实参考音色（可以直接让 hermes 去 youtube 和 bilibili 去扒，选自己喜欢的，没有 bgm 的，最好是那种纯聊天的视频） 关键配置： \"chunk_length\": 400, \"temperature\": 0.7, \"top_p\": 0.8, \"repetition_penalty\": 1.1, 参考音色控制在 15 秒以内（超过 20 秒会过拟合，起反效果） 推理精…",
    "content": "简而言之：Fish Speech 1.5 + 真实参考音色（可以直接让 hermes 去 youtube 和 bilibili 去扒，选自己喜欢的，没有 bgm 的，最好是那种纯聊天的视频） 关键配置： \"chunk_length\": 400, \"temperature\": 0.7, \"top_p\": 0.8, \"repetition_penalty\": 1.1, 参考音色控制在 15 秒以内（超过 20 秒会过拟合，起反效果） 推理精度：FP32 （~3.5GB VRAM ；也可以 --half FP16 ~1.…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212276#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[酷工作] Crypto CEX 客服组长 中英文 远程办公 3000-4000 USDT/月",
    "link": "https://www.v2ex.com/t/1212276#reply0",
    "pub_date": "2026-05-12 23:09:17",
    "author": "AriaWanax",
    "description": "远程办公，弹性制不打卡，东八区时间 面试方式：线上面试 欢迎自荐推荐，简历投递👇🏻 TG: @AriaWanax VX: Aurora_Wanax 工作地点： 远程（优先时区：UTC+8 ） 招聘人数：1 人 一、职位定位 作为交易所客服团队的管理者，负责带领一线客服团队，为全球数百万用户提供 7×24 小时专业、高效、合规的客户支持。您需要平衡服务质量与运营效率，同时关注团队士气与人才成长，在日常服务中识别并向上反馈产品与流程优化…",
    "content": "远程办公，弹性制不打卡，东八区时间 面试方式：线上面试 欢迎自荐推荐，简历投递👇🏻 TG: @ AriaWanax VX: Aurora_Wanax 工作地点： 远程（优先时区：UTC+8 ） 招聘人数：1 人 一、职位定位 作为交易所客服团队的管理者，负责带领一线客服团队，为全球数百万用户提供 7×24 小时专业、高效、合规的客户支持。您需要平衡服务质量与运营效率，同时关注团队士气与人才成长，在日常服务中识别并向上反馈产品与流程优化机会。 二、核心职责 1. 团队管理（ 35%） - 带领 5-10 人的客服…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212275#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[投资] 我买半导体了，大家还不跑吗",
    "link": "https://www.v2ex.com/t/1212275#reply1",
    "pub_date": "2026-05-12 23:07:27",
    "author": "orion1",
    "description": "看着英伟达这些长太高了，还不下跌就难受。按我经验我买啥跌啥。。。",
    "content": "看着英伟达这些长太高了，还不下跌就难受。按我经验我买啥跌啥。。。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212273#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 极简 CodeBuddy CLI 备份/恢复命令",
    "link": "https://www.v2ex.com/t/1212273#reply0",
    "pub_date": "2026-05-12 22:52:20",
    "author": "ocleo1",
    "description": "说明 CodeBuddy CLI 支持导出会话记录到文件，所以做两个命令，用于备份/恢复通话记录。在线存储使用腾讯云 COS ，需要提前设置好自己的存储桶 使用 备份命令 恢复命令 下载 release 附件包，然后解压到以下位置 macOS 或 Linux ，~/.codebuddy/commands Windows ，C:\\Users .codebuddy\\commands 然后运行 cbc /backup-to-cloud con…",
    "content": "说明 CodeBuddy CLI 支持导出会话记录到文件，所以做两个命令，用于备份/恢复通话记录。在线存储使用腾讯云 COS ，需要提前设置好自己的存储桶 使用 备份命令 恢复命令 下载 release 附件包，然后解压到以下位置 macOS 或 Linux ，~/.codebuddy/commands Windows ，C:\\Users&lt;用户名&gt;.codebuddy\\commands 然后运行 cbc /backup-to-cloud conversation.txt /restore-from-cl…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212272#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[AI Tools 精品 AI 工具导航] 做了一个音/视频转文本的工具",
    "link": "https://www.v2ex.com/t/1212272#reply1",
    "pub_date": "2026-05-12 22:44:38",
    "author": "Dkphhh",
    "description": "做了一个音/视频转文本的工具，叫 video to text 功能非常简单直接，把音频或者视频文件拖进去，就能转化成文本，支持 4 种导出格式：srt, vtt, txt, or csv。srt 和 vtt 是字幕文件的格式。 导出的字段包括：这句话的开始时间、结束时间、发言人标签（不同的人会标注 speaker A 、speaker B ）和这句话的文本。 支持 99 种语言，也支持多语言音/视频的识别。 比较适合用来做会议记录、课堂…",
    "content": "做了一个音/视频转文本的工具，叫 video to text 功能非常简单直接，把音频或者视频文件拖进去，就能转化成文本，支持 4 种导出格式： srt , vtt , txt , or csv 。 srt 和 vtt 是字幕文件的格式。 导出的字段包括：这句话的开始时间、结束时间、发言人标签（不同的人会标注 speaker A 、speaker B ）和这句话的文本。 支持 99 种语言，也支持多语言音/视频的识别。 比较适合用来做会议记录、课堂录音或者是采访录音的转写。 使用前需要登录，新用户有 30 分钟免费…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212271#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] [分享] 我用闲暇时间做的一款弹珠/物理小球游戏，欢迎来玩！",
    "link": "https://www.v2ex.com/t/1212271#reply0",
    "pub_date": "2026-05-12 22:37:24",
    "author": "mtouei",
    "description": "做了一款游戏。核心玩法就是通过鼠标/触摸控制方向，把小球准确地打进目标区域，操作简单，还挺上头 游戏链接： https://ball-game-taupe.vercel.app/ 后续有空会继续迭代，欢迎大家试玩、提建议、找 Bug ！ 玩的时候有啥感受或者想吐槽的地方，欢迎在这里留言～谢谢大家！",
    "content": "做了一款游戏。核心玩法就是通过鼠标/触摸控制方向，把小球准确地打进目标区域，操作简单，还挺上头 游戏链接： https://ball-game-taupe.vercel.app/ 后续有空会继续迭代，欢迎大家试玩、提建议、找 Bug ！ 玩的时候有啥感受或者想吐槽的地方，欢迎在这里留言～谢谢大家！"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212270#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] rclone 个人使用修改版（123 云盘后端添加版）分享",
    "link": "https://www.v2ex.com/t/1212270#reply3",
    "pub_date": "2026-05-12 22:29:53",
    "author": "PianCat",
    "description": "设计上基本上照搬了 Openlist 的 123pan 的设计 项目地址 之前是想给 rclone 官方投 pr 的，后面来来回回就没人审核了就算了 目前是加了自动写 Release 和 fetch 上游，如果有问题还请大家多多提 issue 或者在这里面反馈",
    "content": "设计上基本上照搬了 Openlist 的 123pan 的设计 项目地址 之前是想给 rclone 官方投 pr 的，后面来来回回就没人审核了就算了 目前是加了自动写 Release 和 fetch 上游，如果有问题还请大家多多提 issue 或者在这里面反馈"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212268#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[游戏] 地平线 6 未加密的文件到底是不是官方泄露的",
    "link": "https://www.v2ex.com/t/1212268#reply3",
    "pub_date": "2026-05-12 22:23:07",
    "author": "darkTianTian",
    "description": "听说登录会被封号，不知道 520 switch 下的能不能玩。 另外搞了个网站方便自己边查边玩。 https://forzahorizon6wiki.com/zh/",
    "content": "听说登录会被封号，不知道 520 switch 下的能不能玩。 另外搞了个网站方便自己边查边玩。 https://forzahorizon6wiki.com/zh/"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212267#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] Xiaomi HyperOS 短短几天连续更新 2 次，对它的信任又下降了",
    "link": "https://www.v2ex.com/t/1212267#reply1",
    "pub_date": "2026-05-12 22:22:15",
    "author": "HeasyYS",
    "description": "机器：Mi13 第二次更新版本号：3.0.307.0.WMCCNXM |70MB",
    "content": "机器：Mi13 第二次更新版本号：3.0.307.0.WMCCNXM |70MB"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212266#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Claude] claude 为啥我的账号用不了 Design 功能呢",
    "link": "https://www.v2ex.com/t/1212266#reply0",
    "pub_date": "2026-05-12 22:12:18",
    "author": "jake361",
    "description": "其他都正常，我还是开的 5x 的 max 会员",
    "content": "其他都正常，我还是开的 5x 的 max 会员"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212265#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] BiliNote Pro（一款 AI 视频笔记助手）内测上线了，聊聊为什么我要把开源项目做成付费版",
    "link": "https://www.v2ex.com/t/1212265#reply0",
    "pub_date": "2026-05-12 21:58:33",
    "author": "jefferyH",
    "description": "BiliNote Pro 内测版上线了。 先说背景。 BiliNote 开源版已经做了一段时间，目前 GitHub 6000+ Stars ，也有不少朋友在实际使用。 但这段时间收到最多的问题其实不是功能，而是： 部署太麻烦 GPU / CUDA 环境问题 ffmpeg / whisper 配置 API key 网络环境 转录模型下载 视频解析稳定性 很多普通用户其实根本没法真正跑起来。 所以后来就在想： 是不是应该做一个真正“开箱即用…",
    "content": "BiliNote Pro 内测版上线了。 先说背景。 BiliNote 开源版已经做了一段时间，目前 GitHub 6000+ Stars ，也有不少朋友在实际使用。 但这段时间收到最多的问题其实不是功能，而是： 部署太麻烦 GPU / CUDA 环境问题 ffmpeg / whisper 配置 API key 网络环境 转录模型下载 视频解析稳定性 很多普通用户其实根本没法真正跑起来。 所以后来就在想： 是不是应该做一个真正“开箱即用”的版本。 于是就有了 BiliNote Pro 。 现在的 Pro 版主要做了…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212264#reply17",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[OpenAI] ChatGPT 突然被封号了",
    "link": "https://www.v2ex.com/t/1212264#reply17",
    "pub_date": "2026-05-12 21:54:53",
    "author": "fancy2020",
    "description": "订阅的是 20 刀的 plus 。 大概一个小时前还在跟它交流，结果再打开的时候突然被登出，然后显示 You do not have an account because it has been deleted or deactivated. If you believe this was an error, please contact us through our help center at help.openai.com and…",
    "content": "订阅的是 20 刀的 plus 。 大概一个小时前还在跟它交流，结果再打开的时候突然被登出，然后显示 You do not have an account because it has been deleted or deactivated. If you believe this was an error, please contact us through our help center at help.openai.com and include the request ID fee015e2-f328-42…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212263#reply4",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[奇思妙想] 实现 token 自由了，可以干些什么有意思有意义的事情",
    "link": "https://www.v2ex.com/t/1212263#reply4",
    "pub_date": "2026-05-12 21:54:35",
    "author": "realcaoqi95",
    "description": "感谢公司大方，不限制 token 使用，公司也鼓励大家往 one person company 方向走，希望消耗了 token 之后，大家都可以养成一些新时代的技能。 刚加入 vibe coding 行列不久，思维都还停留在老旧的传统的阶段，目前有哪些东西可以学习，并快速用到自己的工作流上面的？ 目前配置是： 1.飞书 Openclaw 搭 gpt-5.5 用来专业领域论文搜寻-论文深度解读&可行性分析-形成专利想法写专利或者复现论文方…",
    "content": "感谢公司大方，不限制 token 使用，公司也鼓励大家往 one person company 方向走，希望消耗了 token 之后，大家都可以养成一些新时代的技能。 刚加入 vibe coding 行列不久，思维都还停留在老旧的传统的阶段，目前有哪些东西可以学习，并快速用到自己的工作流上面的？ 目前配置是： 1.飞书 Openclaw 搭 gpt-5.5 用来专业领域论文搜寻-论文深度解读&amp;可行性分析-形成专利想法写专利或者复现论文方法和当前方法做对比 2.本地开发用 Codex CLI （ GPT-5.…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212260#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] [FK Claude] 专注 Claude 的中转站",
    "link": "https://www.v2ex.com/t/1212260#reply0",
    "pub_date": "2026-05-12 21:39:48",
    "author": "sx931210",
    "description": "https://www.fkclaude.xyz/ FK CLaude 低至官方 2.6 折 自搭建 Claude Max 号池 国内直连,无需翻墙 支持分发,量大可谈 欢迎体验!",
    "content": "https://www.fkclaude.xyz/ FK CLaude 低至官方 2.6 折 自搭建 Claude Max 号池 国内直连,无需翻墙 支持分发,量大可谈 欢迎体验!"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16382#post_8",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "如何在Arch Linux中玩洛克王国：世界？踩坑中（尚未无解决办法）",
    "link": "https://forum.archlinuxcn.org/t/topic/16382#post_8",
    "pub_date": "2026-05-12 21:31:54",
    "author": "",
    "description": "waydroid和dwproton我之前也试了，都不行，没招了",
    "content": "waydroid和dwproton我之前也试了，都不行，没招了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16382#post_7",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "如何在Arch Linux中玩洛克王国：世界？踩坑中（尚未无解决办法）",
    "link": "https://forum.archlinuxcn.org/t/topic/16382#post_7",
    "pub_date": "2026-05-12 21:30:16",
    "author": "",
    "description": "我看b站有用qemu装win11+反虚拟化检测修改+显卡直通玩的。我单显卡不好显卡直通，用virtiogpu是玩不了的，不支持D3D11相关api",
    "content": "我看b站有用qemu装win11+反虚拟化检测修改+显卡直通玩的。我单显卡不好显卡直通，用virtiogpu是玩不了的，不支持D3D11相关api"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212259#reply14",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 小米路由器 AX3000T 两年半使用体验(差一点就成为米粉了，换华为路由器了！)",
    "link": "https://www.v2ex.com/t/1212259#reply14",
    "pub_date": "2026-05-12 21:23:51",
    "author": "wuyiccc",
    "description": "2023 年 11 月中旬花 180 在京东自营购买的小米 AX3000T 路由器，到手使用的前两年确实很惊艳，感觉符合小米物美价廉的映像，差点成为米粉了!!! 结果 2025 年 11 月过保，2026 年 4 月份开始不间断的打游戏会突然延迟巨高，然后掉线. 一直以为是公寓的宽带不行(恰逢公寓宽带升级，所以一直没有怀疑是路由器的问题). 于是我每次打游戏都会让电脑连手机热点，就这样坚持了一个月. 然后五月份开始，不仅打游戏卡顿，看视…",
    "content": "2023 年 11 月中旬花 180 在京东自营购买的小米 AX3000T 路由器，到手使用的前两年确实很惊艳，感觉符合小米物美价廉的映像，差点成为米粉了!!! 结果 2025 年 11 月过保，2026 年 4 月份开始不间断的打游戏会突然延迟巨高，然后掉线. 一直以为是公寓的宽带不行(恰逢公寓宽带升级，所以一直没有怀疑是路由器的问题). 于是我每次打游戏都会让电脑连手机热点，就这样坚持了一个月. 然后五月份开始，不仅打游戏卡顿，看视频也开始突然卡，然后后面恢复正常，感觉像抽风了一样. 然后五月初公寓宽带升级完成…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212258#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 从‘查不到’到‘看得懂’的罕见病知识库",
    "link": "https://www.v2ex.com/t/1212258#reply3",
    "pub_date": "2026-05-12 21:13:17",
    "author": "WaylonZzz",
    "description": "很多罕见病家庭都有过这种经历：医生说出一个很陌生的病名，回家一搜，信息不是太专业，就是太零散。 想知道： 这个病到底是什么？ 该先看哪个科？ 哪些检查值得问医生？ 会不会遗传？ 有没有长期管理办法？ 但真正能看懂、能追溯来源、又适合就医前准备的中文信息，并不好找。 所以我上线了一个罕见病知识站。 为什么用 AI 做罕见病知识站？ 因为这类信息太分散、太专业、更新也慢。 AI 比较适合把大量公开资料先整理成结构化内容，再反复检查来源、术语…",
    "content": "很多罕见病家庭都有过这种经历：医生说出一个很陌生的病名，回家一搜，信息不是太专业，就是太零散。 想知道： 这个病到底是什么？ 该先看哪个科？ 哪些检查值得问医生？ 会不会遗传？ 有没有长期管理办法？ 但真正能看懂、能追溯来源、又适合就医前准备的中文信息，并不好找。 所以我上线了一个罕见病知识站。 为什么用 AI 做罕见病知识站？ 因为这类信息太分散、太专业、更新也慢。 AI 比较适合把大量公开资料先整理成结构化内容，再反复检查来源、术语和阅读体验。 但 AI 不是医生。 所以这个网站不是线上问诊，也不替代医生诊断。…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212257#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] 买什么样的 SIM 卡能稳定收到海外应用的验证码？",
    "link": "https://www.v2ex.com/t/1212257#reply1",
    "pub_date": "2026-05-12 21:12:59",
    "author": "lxzv2xe",
    "description": "买了一张 hahasim 卡，回来一试才发现 X 直接不支持号码，TG 注册直接显示被 BAN ，麻了。",
    "content": "买了一张 hahasim 卡，回来一试才发现 X 直接不支持号码，TG 注册直接显示被 BAN ，麻了。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212254#reply9",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[OpenAI] IOS 美区订阅的 200x,过了 Cyber 认证的账号被封了 😭 😭 😭",
    "link": "https://www.v2ex.com/t/1212254#reply9",
    "pub_date": "2026-05-12 20:57:03",
    "author": "mnoputd20adfadf3",
    "description": "申诉也没用 ... 没过 Cyber 认证的没事儿 ... 😭 😭 😭",
    "content": "申诉也没用 ... 没过 Cyber 认证的没事儿 ... 😭 😭 😭"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212252#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[贵阳] 有没有贵州移动有线 A 车头？",
    "link": "https://www.v2ex.com/t/1212252#reply0",
    "pub_date": "2026-05-12 20:47:56",
    "author": "svipghy",
    "description": "贵州移动异地两条宽带，每月 10+8 ，哪里可以办理，走鱼！",
    "content": "贵州移动异地两条宽带，每月 10+8 ，哪里可以办理，走鱼！"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212251#reply27",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] NET 已死",
    "link": "https://www.v2ex.com/t/1212251#reply27",
    "pub_date": "2026-05-12 20:46:11",
    "author": "duwenink248",
    "description": "这么好的语言 这么优雅的语言，在这片土地上 打不过 JAVA 唉",
    "content": "这么好的语言 这么优雅的语言，在这片土地上 打不过 JAVA 唉"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16450#post_12",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Wine运行微软的Office2010很流畅，无任何报错。",
    "link": "https://forum.archlinuxcn.org/t/topic/16450#post_12",
    "pub_date": "2026-05-12 20:39:10",
    "author": "",
    "description": "一切正常 未发现任何Bug",
    "content": "一切正常 未发现任何Bug"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212249#reply7",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[反馈] 登录状态每天都会失效",
    "link": "https://www.v2ex.com/t/1212249#reply7",
    "pub_date": "2026-05-12 20:24:59",
    "author": "vmoewill",
    "description": "每次登 V 站似乎都要重新登录一下，似乎从近 1 年开始就这样了，用谷歌登录的，请问是因为我触发了什么吗？还是 token 时效本身就很短？",
    "content": "每次登 V 站似乎都要重新登录一下，似乎从近 1 年开始就这样了，用谷歌登录的，请问是因为我触发了什么吗？还是 token 时效本身就很短？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212248#reply11",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[程序员] 历史两个多月，终于把我理想中的远程 vibe 工具打磨差不多了",
    "link": "https://www.v2ex.com/t/1212248#reply11",
    "pub_date": "2026-05-12 20:06:31",
    "author": "yandc",
    "description": "https://github.com/a9gent/mindfs 我的刚需 必须可以远程随时随地 vibe 主流 agent 都要支持 agent 电脑上的文件访问 远程时能随时拉起历史 session 继续 必须自托管，没有 relay 我用 ip:port 一样可以访问 能远程添加本地/github/空白项目/worktree app 锁屏通知提醒任务完成 缘由 去年 vibe 停不下来，试过各种远程 vibe 的姿势，都很让人抓狂…",
    "content": "https://github.com/a9gent/mindfs 我的刚需 必须可以远程随时随地 vibe 主流 agent 都要支持 agent 电脑上的文件访问 远程时能随时拉起历史 session 继续 必须自托管，没有 relay 我用 ip:port 一样可以访问 能远程添加本地/github/空白项目/worktree app 锁屏通知提醒任务完成 缘由 去年 vibe 停不下来，试过各种远程 vibe 的姿势，都很让人抓狂，包括 happy 这种。 年初只有一个模糊的想法，主要诉求就上面几点，改了很多…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212246#reply21",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[职场话题] 再三思量，还是辞了。",
    "link": "https://www.v2ex.com/t/1212246#reply21",
    "pub_date": "2026-05-12 19:57:57",
    "author": "stay4u",
    "description": "年前身体就开始预警了，近一年处于睡眠障碍加焦虑状态，用一句鸡汤安慰自己 - “以前总觉得赢了才叫厉害,后来才明白, 能主动退出消耗自己的局,才是真的强大。” 共勉",
    "content": "年前身体就开始预警了，近一年处于睡眠障碍加焦虑状态，用一句鸡汤安慰自己 - “以前总觉得赢了才叫厉害,后来才明白, 能主动退出消耗自己的局,才是真的强大。” 共勉"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212245#reply8",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[Claude Code] 中转站有开源版本吗?",
    "link": "https://www.v2ex.com/t/1212245#reply8",
    "pub_date": "2026-05-12 19:46:46",
    "author": "csfreshman",
    "description": "打算自己搭一个，小圈子使用，不对外。 现在热门帖子里，中转站就像浇了大粪一样，突突突的冒了出来？ 看 web ui 和使用方式都不一样，随时都有跑路的风险。 想自己搞一个，让家人、朋友使用，有没有开源的版本？",
    "content": "打算自己搭一个，小圈子使用，不对外。 现在热门帖子里，中转站就像浇了大粪一样，突突突的冒了出来？ 看 web ui 和使用方式都不一样，随时都有跑路的风险。 想自己搞一个，让家人、朋友使用，有没有开源的版本？"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212244#reply1",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 做了个批量生成手机壁纸样品的工具",
    "link": "https://www.v2ex.com/t/1212244#reply1",
    "pub_date": "2026-05-12 19:41:36",
    "author": "milktank",
    "description": "AI 生图的时候，想着很多图做壁纸都挺好看的，就做了这个工具方便快速批量生成在手机或者电脑壁纸的效果。地址 https://phonewallpapermockup.com/zh/",
    "content": "AI 生图的时候，想着很多图做壁纸都挺好看的，就做了这个工具方便快速批量生成在手机或者电脑壁纸的效果。地址 https://phonewallpapermockup.com/zh/"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16526#post_18",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "绝区零新版本无法启动",
    "link": "https://forum.archlinuxcn.org/t/topic/16526#post_18",
    "pub_date": "2026-05-12 19:40:11",
    "author": "",
    "description": "我下载了旧的mhypbase.dll进行替换，成功进游戏了，但是有概率在游戏一开始自检的时候触发异常并提示你使用HoYoPlay的一键修复",
    "content": "我下载了旧的 mhypbase.dll 进行替换，成功进游戏了，但是有概率在游戏一开始自检的时候触发异常并提示你使用HoYoPlay的一键修复"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212243#reply7",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[云计算] 卧槽 ucloud 台湾比白嫖的服务器 还差劲！",
    "link": "https://www.v2ex.com/t/1212243#reply7",
    "pub_date": "2026-05-12 19:36:32",
    "author": "123128xyz",
    "description": "买了个中国台湾 轻量 2h2g 30mbps 两岸低时延通道 97 元/年 实测速度 40kb/s ping 80%丢包 。。。。。。 究竟该买哪个啊？腾讯云试过了一般 至少能用，还有别的推荐吗？",
    "content": "买了个中国台湾 轻量 2h2g 30mbps 两岸低时延通道 97 元/年 实测速度 40kb/s ping 80%丢包 。。。。。。 究竟该买哪个啊？腾讯云试过了一般 至少能用，还有别的推荐吗？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16546#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助]Steam无法选取本地文件",
    "link": "https://forum.archlinuxcn.org/t/topic/16546#post_2",
    "pub_date": "2026-05-12 19:13:43",
    "author": "",
    "description": "你安装 xdg-desktop-portal-gtk和xdg-desktop-portal-gnome了吗？ GitHub Important Software A scrollable-tiling Wayland compositor. Contribute to niri-wm/niri development by creating an account on GitHub.",
    "content": "你安装 xdg-desktop-portal-gtk和xdg-desktop-portal-gnome了吗？ GitHub Important Software A scrollable-tiling Wayland compositor. Contribute to niri-wm/niri development by creating an account on GitHub."
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16546#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助]Steam无法选取本地文件",
    "link": "https://forum.archlinuxcn.org/t/topic/16546#post_1",
    "pub_date": "2026-05-12 19:09:26",
    "author": "",
    "description": "系统环境：arch linux 桌面环境：niri 在非steam游戏加载页面 browse选择本地文件的按钮按不动",
    "content": "系统环境：arch linux 桌面环境：niri 在非steam游戏加载页面 browse选择本地文件的按钮按不动"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212242#reply2",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] readme-html-convert skill 将超长的 readme.md 文件转为 readmd.html",
    "link": "https://www.v2ex.com/t/1212242#reply2",
    "pub_date": "2026-05-12 18:45:46",
    "author": "MuskZhou",
    "description": "https://github.com/paipaiio/readme.html 将过于冗长的 readme.md 文件转为阅读体验更好的 html 网页，在保留原有信息的基础上添加分层分标签和交互功能。",
    "content": "https://github.com/paipaiio/readme.html 将过于冗长的 readme.md 文件转为阅读体验更好的 html 网页，在保留原有信息的基础上添加分层分标签和交互功能。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212241#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[问与答] [不懂就问] 有什么好办法可以往 polymarket 上入金呀？",
    "link": "https://www.v2ex.com/t/1212241#reply0",
    "pub_date": "2026-05-12 18:34:40",
    "author": "TimeNewRome",
    "description": "我感觉今年汉坦病毒要大爆发",
    "content": "我感觉今年汉坦病毒要大爆发"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16544#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助] Plasma Login Manager无法设置",
    "link": "https://forum.archlinuxcn.org/t/topic/16544#post_2",
    "pub_date": "2026-05-12 18:28:38",
    "author": "",
    "description": "会不会kcm模块没做好",
    "content": "会不会kcm模块没做好"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212239#reply0",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[推广] 1000 刀 codex 福利，快蹬",
    "link": "https://www.v2ex.com/t/1212239#reply0",
    "pub_date": "2026-05-12 18:16:10",
    "author": "travelcc",
    "description": "1000 刀 codex 福利，快来蹬！ url： https://aicodelink.top/v1 令牌：sk-EubIp1v9kIi6Ytp8QCc93dxfbbhSm5eYEqTsdfmO5bicFxjH 亲测这个站很稳： 💻 开发专用：1 秒首字响应，支持超高并发，适配多文件分析。 🧠 模型全：Claude 4.7 、GPT-5.5 长期稳定在线。 💰 计费透明： 纯按量付费，比例 1:1 ，低至一毛钱一刀（$1 ），成…",
    "content": "1000 刀 codex 福利，快来蹬！ url： https://aicodelink.top/v1 令牌：sk-EubIp1v9kIi6Ytp8QCc93dxfbbhSm5eYEqTsdfmO5bicFxjH 亲测这个站很稳： 💻 开发专用：1 秒首字响应，支持超高并发，适配多文件分析。 🧠 模型全：Claude 4.7 、GPT-5.5 长期稳定在线。 💰 计费透明： 纯按量付费，比例 1:1 ，低至一毛钱一刀（$1 ），成本直接打下来。 💡 限时福利： 注册送测试额度，群内常有抽奖，主打一个交朋友。…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212238#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 我在小程序 iOS 6 Play 里，复刻了 iOS 6 拟物化的体验，请看",
    "link": "https://www.v2ex.com/t/1212238#reply5",
    "pub_date": "2026-05-12 18:12:16",
    "author": "nanxiaobei",
    "description": "小程序：iOS 6 Play 微信扫码，或微信搜索小程序 iOS 6 Play 体验： 请注意，这个 iOS 6 Play 小程序不仅仅是 UI 展示： 它的 短信 是可以 \"用\" 的，你可以用来体验废话聊天 它的 备忘录 是可以用的，你完全可以把它当做一个备忘录用，数据存在微信本地 它的 提醒事项 是可以用的，你完全可以把它当做一个 ToDo List 用，数据存在微信本地 它的 计算器 是可以用的，你完全可以把它当做一个 ... 计…",
    "content": "小程序： iOS 6 Play 微信扫码，或微信搜索小程序 iOS 6 Play 体验： 请注意，这个 iOS 6 Play 小程序不仅仅是 UI 展示： 它的 短信 是可以 \"用\" 的，你可以用来体验废话聊天 它的 备忘录 是可以用的，你完全可以把它当做一个备忘录用，数据存在微信本地 它的 提醒事项 是可以用的，你完全可以把它当做一个 ToDo List 用，数据存在微信本地 它的 计算器 是可以用的，你完全可以把它当做一个 ... 计算器用 它的 Safari 是 不可以 用的，但你可以用它来看猫，如果你稍微多…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212237#reply17",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[职场话题] 每个月少拿 2000，换来居家办公，感觉挺合算的",
    "link": "https://www.v2ex.com/t/1212237#reply17",
    "pub_date": "2026-05-12 18:11:55",
    "author": "lg106",
    "description": "去年年底取保候审，也没去找工作，同事介绍了工作先远程干着，前段时间检察院拿到了不起诉，然后去那上了一段时间班，基本上下午过去，晚上回家，很不自在，感觉自己被困在办公室，过去七八年时间经历过的三家公司都很自由，活干完都可以不去公司或者晚去公司。 昨天前公司老板找到我和我同事，说让我们跟着他干，办公室已经租好了，在我小区门口，不会约束我们时间，我们先是撮合前公司老板和现在我的老板合作，结果两人都是想自己单干，怕别人来干预，我考虑了一晚上，准…",
    "content": "去年年底取保候审，也没去找工作，同事介绍了工作先远程干着，前段时间检察院拿到了不起诉，然后去那上了一段时间班，基本上下午过去，晚上回家，很不自在，感觉自己被困在办公室，过去七八年时间经历过的三家公司都很自由，活干完都可以不去公司或者晚去公司。 昨天前公司老板找到我和我同事，说让我们跟着他干，办公室已经租好了，在我小区门口，不会约束我们时间，我们先是撮合前公司老板和现在我的老板合作，结果两人都是想自己单干，怕别人来干预，我考虑了一晚上，准备还是和前公司老板混，主要是自由离家近，还可以随意怼老板，偶尔还可以敲下老板竹杠…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212236#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享发现] 钉钉这是在干什么？",
    "link": "https://www.v2ex.com/t/1212236#reply3",
    "pub_date": "2026-05-12 18:05:04",
    "author": "zander",
    "description": "今天无意中看到的。搜了下这个西游妖魔榜养成系统也没搜到啊。 https://github.com/DingTalk-Real-AI/dingtalk-openclaw-connector/commit/60961a7ffd206a656bc54554c3b79f4eed742dac",
    "content": "今天无意中看到的。搜了下这个西游妖魔榜养成系统也没搜到啊。 https://github.com/DingTalk-Real-AI/dingtalk-openclaw-connector/commit/60961a7ffd206a656bc54554c3b79f4eed742dac"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212234#reply3",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 我的第三个小程序审核通过了，这次不是“记账”了，也不带名字了",
    "link": "https://www.v2ex.com/t/1212234#reply3",
    "pub_date": "2026-05-12 17:56:07",
    "author": "finecho",
    "description": "昨天大家对程序员做记账这件事感觉深恶痛绝 😂 我想了一下， 为什么我第一个拿来练手的小程序会是记账。 可能真的是到了这个年纪， 开始慢慢有一点“财商焦虑”了。 会开始关注： 钱花去哪了、 每个月到底存下来多少、 自己的资产流动到底健不健康。 所以才顺手做了个记账小程序给自己用。 不过这第三个小程序，自我觉得同质化不严重吧？ 这个新小程序叫「先别买」。 起因是我发现自己最近冲动消费有点严重。 于是我就想： 能不能做一个东西， 在“准备下…",
    "content": "昨天大家对程序员做记账这件事感觉深恶痛绝 😂 我想了一下， 为什么我第一个拿来练手的小程序会是记账。 可能真的是到了这个年纪， 开始慢慢有一点“财商焦虑”了。 会开始关注： 钱花去哪了、 每个月到底存下来多少、 自己的资产流动到底健不健康。 所以才顺手做了个记账小程序给自己用。 不过这第三个小程序，自我觉得同质化不严重吧？ 这个新小程序叫「先别买」。 起因是我发现自己最近冲动消费有点严重。 于是我就想： 能不能做一个东西， 在“准备下单”的前几秒， 先帮我冷静一下？ 现在它的玩法大概是： 把你想买的东西丢进去， …"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212233#reply22",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[分享创造] 我做了一个 iOS 本地电子书阅读器「StoryBoat / 故舟」，支持 EPUB/TXT/PDF/Kindle 和朗读，送一些 Pro 码换真实反馈",
    "link": "https://www.v2ex.com/t/1212233#reply22",
    "pub_date": "2026-05-12 17:49:24",
    "author": "LincolnAt",
    "description": "大家好，我刚上架了一个 iOS 阅读器：StoryBoat / 故舟。 App Store： https://apps.apple.com/cn/app/storyboat/id6761174091 它不是书城，也不提供书源。主要给已经有本地书和长文档的人用：EPUB 、TXT 、PDF 、Kindle 格式、Markdown 、长文本都可以导入到一个安静的书架里读。 我自己做它的出发点是：很多阅读器要么偏书城，要么 TXT/EPUB/…",
    "content": "大家好，我刚上架了一个 iOS 阅读器：StoryBoat / 故舟。 App Store： https://apps.apple.com/cn/app/storyboat/id6761174091 它不是书城，也不提供书源。主要给已经有本地书和长文档的人用：EPUB 、TXT 、PDF 、Kindle 格式、Markdown 、长文本都可以导入到一个安静的书架里读。 我自己做它的出发点是：很多阅读器要么偏书城，要么 TXT/EPUB/PDF 分散在不同工具里，要么朗读功能比较割裂。我想做一个更专注的本地阅读工具，…"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212232#reply4",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[摄影] 准备入手 action6 了",
    "link": "https://www.v2ex.com/t/1212232#reply4",
    "pub_date": "2026-05-12 17:49:04",
    "author": "sorakaite",
    "description": "但整体看下来貌似没那么简单，一些配件看的眼花缭乱 有没有入手过的大佬谈谈哪些配件比较实用一些，目前看下来伸缩杆和挂绳应该是必需品了",
    "content": "但整体看下来貌似没那么简单，一些配件看的眼花缭乱 有没有入手过的大佬谈谈哪些配件比较实用一些，目前看下来伸缩杆和挂绳应该是必需品了"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16526#post_17",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "绝区零新版本无法启动",
    "link": "https://forum.archlinuxcn.org/t/topic/16526#post_17",
    "pub_date": "2026-05-12 17:45:41",
    "author": "",
    "description": "我查了下zzz好像已经有相关讨论了：an-anime-team/sleepy-launcher#104。",
    "content": "我查了下zzz好像已经有相关讨论了： an-anime-team/sleepy-launcher#104 。"
  },
  {
    "id": "论坛-V2EX-https://www.v2ex.com/t/1212231#reply5",
    "feed_name": "V2EX",
    "category": "论坛",
    "title": "[职场话题] 4 年经验 Java 后端开发现在建议往什么方向转？",
    "link": "https://www.v2ex.com/t/1212231#reply5",
    "pub_date": "2026-05-12 17:45:25",
    "author": "EvanChou",
    "description": "背景 目前是 4 年经验后端开发，总感觉现在的岗位要被替换掉，所以想着提前做点准备。 方向 1 、AI 增强型后端开发 做什么： 在当前 Java 项目里落地 AI 能力。比如用 Spring AI Alibaba 、LangChain4j 给现有系统加个智能问答、代码生成、日志分析助手。 适合： 求稳、不想放弃 Java 积累的人。 2 、AI 应用/Agent 开发（热门方向） 做什么： 用 Java/Go/Python 开发 AI…",
    "content": "背景 目前是 4 年经验后端开发，总感觉现在的岗位要被替换掉，所以想着提前做点准备。 方向 1 、AI 增强型后端开发 做什么： 在当前 Java 项目里落地 AI 能力。比如用 Spring AI Alibaba 、LangChain4j 给现有系统加个智能问答、代码生成、日志分析助手。 适合： 求稳、不想放弃 Java 积累的人。 2 、AI 应用/Agent 开发（热门方向） 做什么： 用 Java/Go/Python 开发 AI 应用的后端。比如 RAG 系统的文档解析、向量检索服务、AI Agent 的工…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16544#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助] Plasma Login Manager无法设置",
    "link": "https://forum.archlinuxcn.org/t/topic/16544#post_1",
    "pub_date": "2026-05-12 17:22:21",
    "author": "",
    "description": "如题，从SDDM切到PLM后，没有在设置应用里找到PLM的配置界面，SDDM的配置界面也是被隐藏的状态（虽然可以通过搜索配置项打开界面）。",
    "content": "如题，从SDDM切到PLM后，没有在设置应用里找到PLM的配置界面，SDDM的配置界面也是被隐藏的状态（虽然可以通过搜索配置项打开界面）。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16526#post_16",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "绝区零新版本无法启动",
    "link": "https://forum.archlinuxcn.org/t/topic/16526#post_16",
    "pub_date": "2026-05-12 17:16:46",
    "author": "",
    "description": "大概率就是这个了，一家的游戏出同样的问题概率还是挺大的。",
    "content": "大概率就是这个了，一家的游戏出同样的问题概率还是挺大的。 根据12楼的情况推测大概是第一次启动的时候需要编译什么东西导致进程自动延迟了一小段时间，刚好错开了竞态，后面直接使用已编译的单元缩短了时间导致碰上了。 求详细教程，给个链接也行，我自己没找到。 以及我看网上也有很多Windows下的人说是和DirectX和Visual C++运行库相关的，重装DXVK和vcruntime也可以试试。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16499#post_12",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "来个成语接龙吧",
    "link": "https://forum.archlinuxcn.org/t/topic/16499#post_12",
    "pub_date": "2026-05-12 17:14:31",
    "author": "",
    "description": "地广人稀",
    "content": "地广人稀"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16457#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "KDE Plasma 下有一些软件如 Jetbrain DataGrip, Bruno 等无法使用中文输入法",
    "link": "https://forum.archlinuxcn.org/t/topic/16457#post_4",
    "pub_date": "2026-05-12 17:03:38",
    "author": "",
    "description": "取消设置多余的环境变量并且设置虚拟键盘为 Fcitx 5 Wayland 启动器 (实验性) 后在 shell 中使用如下命令 qdbus org.kde.KWin /VirtualKeyboard org.kde.kwin.VirtualKeyboard.enabled true 桌面会弹出一个虚拟键盘就绪的提示，然后所有 Electron 相关的应用都可以正常输入中文了，其实之前也设置上了但是一直没有用过那行命令，虽然不知道原理但总…",
    "content": "取消设置多余的环境变量并且设置虚拟键盘为 Fcitx 5 Wayland 启动器 (实验性) 后在 shell 中使用如下命令 qdbus org.kde.KWin /VirtualKeyboard org.kde.kwin.VirtualKeyboard.enabled true 桌面会弹出一个虚拟键盘就绪的提示，然后所有 Electron 相关的应用都可以正常输入中文了，其实之前也设置上了但是一直没有用过那行命令，虽然不知道原理但总算解决了这个问题。。 参考的这个回复 [已解决]使用vsc中文输入法无法使用 应…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_9",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_9",
    "pub_date": "2026-05-12 15:49:41",
    "author": "",
    "description": "GalaxySnail: Android 如果 72 小时不输入锁屏密码还要强制你输入一次呢。 在外面的时候遇到就超级难受，尤其是像地铁这种四周到处都是人的地方……它应该加一个推迟的功能的。",
    "content": "GalaxySnail: Android 如果 72 小时不输入锁屏密码还要强制你输入一次呢。 在外面的时候遇到就超级难受，尤其是像地铁这种四周到处都是人的地方……它应该加一个推迟的功能的。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16450#post_11",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Wine运行微软的Office2010很流畅，无任何报错。",
    "link": "https://forum.archlinuxcn.org/t/topic/16450#post_11",
    "pub_date": "2026-05-12 15:42:12",
    "author": "",
    "description": "请问光标跟随正常吗",
    "content": "请问光标跟随正常吗"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/13904?page=5#post_83",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "求安利，想问一下论坛里大家为什么安装arch linux",
    "link": "https://forum.archlinuxcn.org/t/topic/13904?page=5#post_83",
    "pub_date": "2026-05-12 15:33:30",
    "author": "",
    "description": "你说得对，很遗憾，我们目前的 Readme.md 文件是空的。我和我弟弟在土耳其读11年级，考试马上就要开始了。不过既然你问了，我们正在考虑添加一个 Readme.md 文件",
    "content": "你说得对，很遗憾，我们目前的 Readme.md 文件是空的。我和我弟弟在土耳其读11年级，考试马上就要开始了。不过既然你问了，我们正在考虑添加一个 Readme.md 文件"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_8",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_8",
    "pub_date": "2026-05-12 15:09:03",
    "author": "",
    "description": "前段时间我也收到警告说我的密码可能被泄露了.....不过我基本都开的2FA用ente auth或者验证码登录, 不知道需不需要担心",
    "content": "前段时间我也收到警告说我的密码可能被泄露了.....不过我基本都开的2FA用ente auth或者验证码登录, 不知道需不需要担心 有啥好用的密码管理软件吗"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/13904?page=4#post_82",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "求安利，想问一下论坛里大家为什么安装arch linux",
    "link": "https://forum.archlinuxcn.org/t/topic/13904?page=4#post_82",
    "pub_date": "2026-05-12 15:08:44",
    "author": "",
    "description": "我明白，我只是好奇你的意见。我和我哥哥最近把我们的基础设施迁移到了 Codeberg，我们在 GitHub 和 GitLab 上都有备份。我们的新链接是 https://codeberg.org/gamestime102/PrivOS 。请放心，我会认真考虑你的建议。",
    "content": "我明白，我只是好奇你的意见。我和我哥哥最近把我们的基础设施迁移到了 Codeberg，我们在 GitHub 和 GitLab 上都有备份。我们的新链接是 https://codeberg.org/gamestime102/PrivOS 。请放心，我会认真考虑你的建议。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16526#post_15",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "绝区零新版本无法启动",
    "link": "https://forum.archlinuxcn.org/t/topic/16526#post_15",
    "pub_date": "2026-05-12 15:00:00",
    "author": "",
    "description": "无果...总不能是写到游戏文件里面了吧...",
    "content": "无果...总不能是写到游戏文件里面了吧..."
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_7",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_7",
    "pub_date": "2026-05-12 14:52:45",
    "author": "",
    "description": "GalaxySnail: 而是使用真正的骰子。 我去买俩骰子，一会儿见（bushi",
    "content": "GalaxySnail: 而是使用真正的骰子。 我去买俩骰子，一会儿见（bushi"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_6",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_6",
    "pub_date": "2026-05-12 14:49:35",
    "author": "",
    "description": "推荐看看我上面提到的 diceware（其实 wiki 也提到了，不过 wiki 的特点就是堆砌一堆信息让你分辨不出来重点（",
    "content": "推荐看看我上面提到的 diceware（其实 wiki 也提到了，不过 wiki 的特点就是堆砌一堆信息让你分辨不出来重点（"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_5",
    "pub_date": "2026-05-12 14:48:32",
    "author": "",
    "description": "随机字符组成的密码往往需要很长时间才能记住，而且大概率往往打了很久也记不住，所以如果你经常需要手动输入一个密码的话其实是不推荐用纯随机字符的 我的建议是将没那么常见的但是能记住的东西做一些变形然后作为这种情况下的密码，在保证安全乃至复杂性的同时也能记得住",
    "content": "随机字符组成的密码往往需要很长时间才能记住，而且大概率往往打了很久也记不住，所以如果你经常需要手动输入一个密码的话其实是不推荐用纯随机字符的 我的建议是将没那么常见的但是能记住的东西做一些变形然后作为这种情况下的密码，在保证安全乃至复杂性的同时也能记得住"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_4",
    "pub_date": "2026-05-12 14:47:20",
    "author": "",
    "description": "搬运一下我在知乎上的一篇回答：知乎 - 如何设置一个高强度密码，方便自己记，又不容易被破解呢？ 顺便一提，wiki 上引用的 diceware 网站不是官网，虽然现在它在搜索引擎排第一，但最早提出 diceware 的网站实际上是 https://theworld.com/~reinhold/diceware.html，官网不建议使用计算机的随机数生成器，而是使用真正的骰子。 在我看来，复杂的 diceware 密码只需要用在需要手动输…",
    "content": "搬运一下我在知乎上的一篇回答： 知乎 - 如何设置一个高强度密码，方便自己记，又不容易被破解呢？ 顺便一提，wiki 上引用的 diceware 网站不是官网，虽然现在它在搜索引擎排第一，但最早提出 diceware 的网站实际上是 https://theworld.com/~reinhold/diceware.html ，官网不建议使用计算机的随机数生成器，而是使用真正的骰子。 在我看来，复杂的 diceware 密码只需要用在需要手动输入的密码上，比如密码管理器主密码、LUKS 密码。其它网站的密码可以让密码管…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/13904?page=4#post_81",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "求安利，想问一下论坛里大家为什么安装arch linux",
    "link": "https://forum.archlinuxcn.org/t/topic/13904?page=4#post_81",
    "pub_date": "2026-05-12 14:41:30",
    "author": "",
    "description": "自己用，而且不告诉任何人，装不起来啊",
    "content": "自己用，而且不告诉任何人，装不起来啊"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/13904?page=4#post_80",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "求安利，想问一下论坛里大家为什么安装arch linux",
    "link": "https://forum.archlinuxcn.org/t/topic/13904?page=4#post_80",
    "pub_date": "2026-05-12 14:35:02",
    "author": "",
    "description": "别的发行版没有想像中的那么自由，比如，魔改了很多软件、默认某一种桌面环境",
    "content": "别的发行版没有想像中的那么自由，比如，魔改了很多软件、默认某一种桌面环境"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_3",
    "pub_date": "2026-05-12 14:07:22",
    "author": "",
    "description": "随机密码是和密码管理软件搭配使用的。每个地方用不同的随机密码，可以避免某个网站泄漏数据后，你的所有密码都需要修改。",
    "content": "随机密码是和密码管理软件搭配使用的。每个地方用不同的随机密码，可以避免某个网站泄漏数据后，你的所有密码都需要修改。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_2",
    "pub_date": "2026-05-12 14:06:40",
    "author": "",
    "description": "随机密码是配合密码管理器使用的——也就是根本不需要你手动输入的场景。 rainbowsern: 即使输对了账号和密码，也需要短信验证码或者扫二维码等等 一般不都是不需要密码、直接短信或者扫码登录的吗？说到底这些服务还是不信任用户能保护好自己的密码，导致复杂密码带来的安全性提高几乎为零、但成本依旧在——劣币驱逐良币的又一案例啦。 我一般是这样处理的： 核心加密密钥，比如LUKS密码、密码管理器的加密密码：使用非随机的强密码。自己记住的同时…",
    "content": "随机密码是配合密码管理器使用的——也就是根本不需要你手动输入的场景。 rainbowsern: 即使输对了账号和密码，也需要短信验证码或者扫二维码等等 一般不都是不需要密码、直接短信或者扫码登录的吗？说到底这些服务还是不信任用户能保护好自己的密码，导致复杂密码带来的安全性提高几乎为零、但成本依旧在——劣币驱逐良币的又一案例啦。 我一般是这样处理的： 核心加密密钥，比如LUKS密码、密码管理器的加密密码：使用非随机的强密码。自己记住的同时需要防暴力破解 本地登录密码、PIN：使用简短的密码。这些密码难以被暴力破解 正…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16543#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "关于复杂密码必要性的讨论",
    "link": "https://forum.archlinuxcn.org/t/topic/16543#post_1",
    "pub_date": "2026-05-12 13:55:09",
    "author": "",
    "description": "前段时间摸鱼逛wiki，读到了安全页面的密码（安全-密码）部分，wiki建议使用随机复杂的密码，并且推荐了密码生成软件，以及建议不要使用各种中英词语，因为它们会让密码更容易被破解。我采用了wiki的建议，更换了密码，但是也随之产生了很多问题。 首先复杂随机的密码除非每天都输入，否则一般人根本记不住，而我又不止一个密码，并且也不是每个都每天输一遍，当我需要输入不常用的密码时，我就需要去开我的密码簿，非常麻烦。 其次是国内的软件，我不知道从…",
    "content": "前段时间摸鱼逛wiki，读到了安全页面的密码（ 安全-密码 ）部分，wiki建议使用随机复杂的密码，并且推荐了密码生成软件，以及建议不要使用各种中英词语，因为它们会让密码更容易被破解。我采用了wiki的建议，更换了密码，但是也随之产生了很多问题。 首先复杂随机的密码除非每天都输入，否则一般人根本记不住，而我又不止一个密码，并且也不是每个都每天输一遍，当我需要输入不常用的密码时，我就需要去开我的密码簿，非常麻烦。 其次是国内的软件，我不知道从什么时候开始，很多国内的软件，即使输对了账号和密码，也需要短信验证码或者扫二…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16526#post_14",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "绝区零新版本无法启动",
    "link": "https://forum.archlinuxcn.org/t/topic/16526#post_14",
    "pub_date": "2026-05-12 13:03:29",
    "author": "",
    "description": "这看起来和原神的情况有点像，也是mhypbase出问题，概率性闪退。原神这边是启动时有竞争条件，在启动时通过ptrace暂时性拖慢进程来解决的。",
    "content": "这看起来和原神的情况有点像，也是mhypbase出问题，概率性闪退。原神这边是启动时有竞争条件，在启动时通过ptrace暂时性拖慢进程来解决的。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16526#post_13",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "绝区零新版本无法启动",
    "link": "https://forum.archlinuxcn.org/t/topic/16526#post_13",
    "pub_date": "2026-05-12 11:39:04",
    "author": "",
    "description": "likeyumi: 怀疑你米可能往什么地方写入了什么，再启动碰到这个就直接crash…… 用 bubblewrap 给可写的目录（比如家目录）叠一个 overlayfs 看看？不过我怀疑也不能排除是什么竞争条件，只是被着色器缓存之类的东西影响了触发顺序",
    "content": "likeyumi: 怀疑你米可能往什么地方写入了什么，再启动碰到这个就直接crash…… 用 bubblewrap 给可写的目录（比如家目录）叠一个 overlayfs 看看？不过我怀疑也不能排除是什么竞争条件，只是被着色器缓存之类的东西影响了触发顺序"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16541#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "自定义系统默认中文字体",
    "link": "https://forum.archlinuxcn.org/t/topic/16541#post_2",
    "pub_date": "2026-05-12 11:23:37",
    "author": "",
    "description": "虽然在两张图片对比时，我能看出区别，但是单独拿一张图片出来我却看不出这是哪一种字体",
    "content": "虽然在两张图片对比时，我能看出区别，但是单独拿一张图片出来我却看不出这是哪一种字体"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/13904?page=4#post_79",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "求安利，想问一下论坛里大家为什么安装arch linux",
    "link": "https://forum.archlinuxcn.org/t/topic/13904?page=4#post_79",
    "pub_date": "2026-05-12 10:54:51",
    "author": "",
    "description": "特别是在2026年AI Agent普及以后对小白解决arch Linux的问题也有很大的帮助。使用门槛进一步的降低了。",
    "content": "特别是在2026年AI Agent普及以后对小白解决arch Linux的问题也有很大的帮助。使用门槛进一步的降低了。"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16539#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助] DMS + Niri环境下通过yay安装typora后无法启用fcitx5框架中文输入法",
    "link": "https://forum.archlinuxcn.org/t/topic/16539#post_5",
    "pub_date": "2026-05-12 10:41:53",
    "author": "",
    "description": "诊断的输出是这样的： 系统信息: uname -a: Linux ArchComp 7.0.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 May 2026 09:29:23 +0000 x86_64 GNU/Linux lsb_release: lsb_release 未找到. /etc/lsb-release: /etc/lsb-release 未找到. /etc/os-release: NAME=…",
    "content": "诊断的输出是这样的： 系统信息: uname -a : Linux ArchComp 7.0.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 May 2026 09:29:23 +0000 x86_64 GNU/Linux lsb_release : lsb_release 未找到. /etc/lsb-release : /etc/lsb-release 未找到. /etc/os-release : NAME=\"Arch Linux\" PRETTY_NAME=\"Arch Linux…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16539#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助] DMS + Niri环境下通过yay安装typora后无法启用fcitx5框架中文输入法",
    "link": "https://forum.archlinuxcn.org/t/topic/16539#post_4",
    "pub_date": "2026-05-12 10:36:53",
    "author": "",
    "description": "fcitx5-diagnose看看？",
    "content": "fcitx5-diagnose看看？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16539#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助] DMS + Niri环境下通过yay安装typora后无法启用fcitx5框架中文输入法",
    "link": "https://forum.archlinuxcn.org/t/topic/16539#post_3",
    "pub_date": "2026-05-12 09:29:51",
    "author": "",
    "description": "我安装了typora-electron，但是依旧无法呼出fcitx5的中文输入",
    "content": "我安装了typora-electron，但是依旧无法呼出fcitx5的中文输入"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16499#post_11",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "来个成语接龙吧",
    "link": "https://forum.archlinuxcn.org/t/topic/16499#post_11",
    "pub_date": "2026-05-12 01:03:10",
    "author": "",
    "description": "弹丸之地",
    "content": "弹丸之地"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16526#post_12",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "绝区零新版本无法启动",
    "link": "https://forum.archlinuxcn.org/t/topic/16526#post_12",
    "pub_date": "2026-05-12 00:50:08",
    "author": "",
    "description": "首先问题出在mhypbase.dll无疑了，你可以在drive_c/users/[USER_NAME]/AppData/Local/Temp/miHoYo/ZenlessZoneZero/Crashes/下找到player.log，试了很多次的可以清一下，log最后会几十行' (mhypbase) (function-name not available) ERROR:SymGetSymFromAddr64,GetLastError: …",
    "content": "首先问题出在mhypbase.dll无疑了，你可以在drive_c/users/[USER_NAME]/AppData/Local/Temp/miHoYo/ZenlessZoneZero/Crashes/下找到player.log，试了很多次的可以清一下，log最后会几十行' (mhypbase) (function-name not available) ERROR:SymGetSymFromAddr64,GetLastError: Success'，另外我这边还有灵异事件（？）当我重装显卡驱动或者游戏本体的时候…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16526#post_11",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "绝区零新版本无法启动",
    "link": "https://forum.archlinuxcn.org/t/topic/16526#post_11",
    "pub_date": "2026-05-12 00:31:55",
    "author": "",
    "description": "同样的错误，一周了才找到这里，来汇报一点自己的发现",
    "content": "同样的错误，一周了才找到这里，来汇报一点自己的发现"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16541#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "自定义系统默认中文字体",
    "link": "https://forum.archlinuxcn.org/t/topic/16541#post_1",
    "pub_date": "2026-05-12 00:05:05",
    "author": "",
    "description": "本文来自依云's Blog，转载请注明。 一开始使用Linux系统的时候，并没有多少自由开源的中文字体。那时候几乎所有人的选择都是文泉驿正黑。我就一直用啊用了好多年，直到后来截图时被网友说该换字体了，我才知道原来文泉驿项目已经停止很久了，网站上的新闻截止于2008年——都快20年啦。 pango-view --dpi=1024 --font=思源黑体 --annotate=glyph,layout,baselines -t A测试中文T…",
    "content": "本文来自 依云's Blog ，转载请注明。 一开始使用Linux系统的时候，并没有多少自由开源的中文字体。那时候几乎所有人的选择都是文泉驿正黑。我就一直用啊用了好多年，直到后来截图时被网友说该换字体了，我才知道原来文泉驿项目已经停止很久了， 网站 上的新闻截止于2008年——都快20年啦。 文泉驿正黑的字形比较「旧时代」——以屏幕清晰度为优先，由于当时的屏幕普遍dpi低，笔画迁就像素风格，所以比较丑。另外也有些bug，比如「撨䑾詺㘃㞈㟯㫥」这几个字会有一片漆黑的区域。 文泉驿正黑看起来是这样的。注意截图中只有除标…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16539#post_2",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助] DMS + Niri环境下通过yay安装typora后无法启用fcitx5框架中文输入法",
    "link": "https://forum.archlinuxcn.org/t/topic/16539#post_2",
    "pub_date": "2026-05-11 20:15:29",
    "author": "",
    "description": "试试 typora-electron",
    "content": "试试 typora-electron"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16539#post_1",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助] DMS + Niri环境下通过yay安装typora后无法启用fcitx5框架中文输入法",
    "link": "https://forum.archlinuxcn.org/t/topic/16539#post_1",
    "pub_date": "2026-05-11 17:11:30",
    "author": "",
    "description": "在网上找了很多办法，询问AI也尝试了很多办法但都没有解决 系统信息 Kernel: Linux 7.0.5-arch1-1 Locale: zh_CN.UTF-8 软件信息 dms v1.4.6 niri 26.04 (8ed0da4) typora 1.13.4 尝试过的办法 配置 Typora 的 Wayland 支持 尝试了在~/.config下创建配置文件typora-flags.conf，添加启动参数： --ozone-pla…",
    "content": "在网上找了很多办法，询问AI也尝试了很多办法但都没有解决 系统信息 Kernel: Linux 7.0.5-arch1-1 Locale: zh_CN.UTF-8 软件信息 dms v1.4.6 niri 26.04 (8ed0da4) typora 1.13.4 尝试过的办法 配置 Typora 的 Wayland 支持 尝试了在 ~/.config 下创建配置文件 typora-flags.conf ，添加启动参数： --ozone-platform-hint=auto --enable-wayland-ime…"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16535#post_8",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助]git-remote-https的cpu占用问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16535#post_8",
    "pub_date": "2026-05-11 12:23:53",
    "author": "",
    "description": "不一定是直接由 systemd 运行的，也可能单纯是孤儿进程被 init 收养。最好是再看一下 systemd-cgls",
    "content": "不一定是直接由 systemd 运行的，也可能单纯是孤儿进程被 init 收养。最好是再看一下 systemd-cgls"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16535#post_7",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "[求助]git-remote-https的cpu占用问题",
    "link": "https://forum.archlinuxcn.org/t/topic/16535#post_7",
    "pub_date": "2026-05-11 10:19:59",
    "author": "",
    "description": "直接由systemd运行的啊——是不是有更新git仓库的服务？",
    "content": "直接由systemd运行的啊——是不是有更新git仓库的服务？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/15836#post_7",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "chromium144和electron39之后, gtk4软件有点问题",
    "link": "https://forum.archlinuxcn.org/t/topic/15836#post_7",
    "pub_date": "2026-05-11 09:51:32",
    "author": "",
    "description": "niri更新后已修复 GitHub v26.04 · niri-wm/niri · Discussion #3899 Niri is a scrollable-tiling Wayland compositor. Windows are arranged in columns on an infinite strip going to the right. Opening a new window never causes existi…",
    "content": "niri更新后已修复 GitHub v26.04 · niri-wm/niri · Discussion #3899 Niri is a scrollable-tiling Wayland compositor. Windows are arranged in columns on an infinite strip going to the right. Opening a new window never causes existing windows to resize. As you may hav..."
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/13904?page=4#post_78",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "求安利，想问一下论坛里大家为什么安装arch linux",
    "link": "https://forum.archlinuxcn.org/t/topic/13904?page=4#post_78",
    "pub_date": "2026-05-11 02:22:32",
    "author": "",
    "description": "hi, x-dit. Thank you for inviting. I checked your github repo. but the Readme.md file seem is empty. i have no idea what do you want to do for this project.",
    "content": "hi, x-dit. Thank you for inviting. I checked your github repo. but the Readme.md file seem is empty. i have no idea what do you want to do for this project."
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16499#post_10",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "来个成语接龙吧",
    "link": "https://forum.archlinuxcn.org/t/topic/16499#post_10",
    "pub_date": "2026-05-10 23:29:24",
    "author": "",
    "description": "愁云慘淡",
    "content": "愁云慘淡"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16524#post_5",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Arch Linux 出现无法连接 Wi-Fi 的 Bug",
    "link": "https://forum.archlinuxcn.org/t/topic/16524#post_5",
    "pub_date": "2026-05-10 22:13:56",
    "author": "",
    "description": "ShenMian: 手机热点不就是 Wi-Fi 吗? 也可能是想说 USB 共享网络？",
    "content": "ShenMian: 手机热点不就是 Wi-Fi 吗? 也可能是想说 USB 共享网络？"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16524#post_4",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Arch Linux 出现无法连接 Wi-Fi 的 Bug",
    "link": "https://forum.archlinuxcn.org/t/topic/16524#post_4",
    "pub_date": "2026-05-10 22:13:25",
    "author": "",
    "description": "AkarinLiu: 展示下我的电脑配置 展示电脑配置建议用 inxi 命令，该命令输出的是纯文本，便于直接插入到帖文中。而且 inxi 可以提供更详细的配置信息。 linuxjoy.com 在 Linux 终端使用 inxi 命令获取各种系统信息 – 麟悦 Linux Joy",
    "content": "AkarinLiu: 展示下我的电脑配置 展示电脑配置建议用 inxi 命令，该命令输出的是纯文本，便于直接插入到帖文中。而且 inxi 可以提供更详细的配置信息。 linuxjoy.com 在 Linux 终端使用 inxi 命令获取各种系统信息 – 麟悦 Linux Joy"
  },
  {
    "id": "论坛-Arch Linux 中文论坛-https://forum.archlinuxcn.org/t/topic/16524#post_3",
    "feed_name": "Arch Linux 中文论坛",
    "category": "论坛",
    "title": "Arch Linux 出现无法连接 Wi-Fi 的 Bug",
    "link": "https://forum.archlinuxcn.org/t/topic/16524#post_3",
    "pub_date": "2026-05-10 21:42:24",
    "author": "",
    "description": "我感觉有点困惑, 手机热点不就是 Wi-Fi 吗?",
    "content": "我感觉有点困惑, 手机热点不就是 Wi-Fi 吗?"
  }
];

export default jsonData;
