import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "News--Create By Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-200`}
      >
        <header className="text-white p-4 bg-blue-500 text-xl font-bold text-center sticky top-0">
          <nav>
            <ul className="flex space-x-4 justify-center">
              <li><a href="/" className="hover:text-gray-300">首页</a></li>
              <li><a href="/news" className="hover:text-gray-300">新闻</a></li>
              <li><a href="/foreign" className="hover:text-gray-300">国外</a></li>
              <li><a href="/tech" className="hover:text-gray-300">科技</a></li>
              <li><a href="/code" className="hover:text-gray-300">技术</a></li>
              <li><a href="/live" className="hover:text-gray-300">生活</a></li>
              <li><a href="/info" className="hover:text-gray-300">资讯</a></li>
              <li><a href="/blog" className="hover:text-gray-300">博客</a></li>
              <li><a href="/forum" className="hover:text-gray-300">论坛</a></li>
              <li><a href="/funny" className="hover:text-gray-300">娱乐</a></li>
              <li><a href="/public" className="hover:text-gray-300">公众号</a></li>
            </ul>
          </nav>
        </header>
        <main>{children}
        </main>
      </body>
    </html>
  );
}

