const jsonData = [
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260526-%E6%B8%AF%E8%B4%A2%E7%88%B7%E6%8C%87%E6%AC%A7%E6%B4%B2%E6%B1%82%E5%8F%98-%E5%8F%AF%E5%90%88%E4%BD%9C-%E6%83%9F%E6%B3%95%E5%9B%BD%E5%AD%A6%E8%80%85%E7%A7%B0%E6%AC%A7%E4%BC%81%E5%9C%A8%E6%B8%AF%E8%90%A5%E5%95%86%E6%97%A5%E5%9B%B0-%E6%AC%A7%E7%9B%9F%E5%BA%94%E5%87%8F%E5%AF%B9%E5%8D%8E%E5%80%9A%E8%B5%96",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "港财爷指欧洲求变 可合作 惟法国学者称欧企在港营商日困 欧盟应减对华倚赖 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260526-%E6%B8%AF%E8%B4%A2%E7%88%B7%E6%8C%87%E6%AC%A7%E6%B4%B2%E6%B1%82%E5%8F%98-%E5%8F%AF%E5%90%88%E4%BD%9C-%E6%83%9F%E6%B3%95%E5%9B%BD%E5%AD%A6%E8%80%85%E7%A7%B0%E6%AC%A7%E4%BC%81%E5%9C%A8%E6%B8%AF%E8%90%A5%E5%95%86%E6%97%A5%E5%9B%B0-%E6%AC%A7%E7%9B%9F%E5%BA%94%E5%87%8F%E5%AF%B9%E5%8D%8E%E5%80%9A%E8%B5%96",
    "pub_date": "2026-05-26 14:45:01",
    "author": "",
    "description": "26/05/2026 - 08:20 香港政府近月加强与欧盟和欧洲国家的联系，财政司长陈茂波日前从欧洲回港後更表示，此行让他感受到欧洲求变意识十分强烈，认为港欧在经贸丶投资和创科等多个领域可以合作丶共创双赢。不过，法国政治学者高敬文(Prof. Jean-Pierre Cabestan）向本台指出，欧盟确有兴趣与香港开展更多业务，但在对华政策不变和香港市场日益被中资企业主导的情况下，欧洲企业在香港营商日益困难；若欧盟要去风险，便应减少对…",
    "content": "26/05/2026 - 08:20 香港政府近月加强与欧盟和欧洲国家的联系，财政司长陈茂波日前从欧洲回港後更表示，此行让他感受到欧洲求变意识十分强烈，认为港欧在经贸丶投资和创科等多个领域可以合作丶共创双赢。不过，法国政治学者高敬文(Prof. Jean-Pierre Cabestan）向本台指出，欧盟确有兴趣与香港开展更多业务，但在对华政策不变和香港市场日益被中资企业主导的情况下，欧洲企业在香港营商日益困难；若欧盟要去风险，便应减少对华倚赖。 陈茂波上述说法刚好在欧盟执委会本周五(29日)讨论对华政策前出现；与此…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cn8pp235vw8o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "伊朗戰爭下，環球貨幣誰勝誰敗？",
    "link": "https://www.bbc.com/zhongwen/articles/cn8pp235vw8o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-26 14:39:04",
    "author": "",
    "description": "Getty Images / 在伊朗战事期间，一些货币大幅贬值，另一些维持稳定，还有少数展现较强韧性——例如中国的人民币。 美国与以色列在2月底与伊朗爆发战争时，受到冲击的并不仅仅是中东地区。随着冲突扰乱全球商业航运与商品流通，油价飙升，推高通胀并动摇全球市场。 一如不确定时期常见的情况，一些投资者撤出潜在风险较高的新兴市场投资，将资金转向传统上被视为避险资产的美元。 这对许多货币产生了影响——部分货币大幅贬值，另一些则波动加剧，甚至有…",
    "content": "Getty Images / 在伊朗战事期间，一些货币大幅贬值，另一些维持稳定，还有少数展现较强韧性——例如中国的人民币。 美国与以色列在2月底与伊朗爆发战争时，受到冲击的并不仅仅是中东地区。随着冲突扰乱全球商业航运与商品流通，油价飙升，推高通胀并动摇全球市场。 一如不确定时期常见的情况，一些投资者撤出潜在风险较高的新兴市场投资，将资金转向传统上被视为避险资产的美元。 这对许多货币产生了影响——部分货币大幅贬值，另一些则波动加剧，甚至有少数出现升值。 巴西经济学家、顾问公司APCE负责人安德烈·佩费托（André …"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/health/20260526/longevity-wellness-industry/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "花更多钱能让你活得更久、更健康吗？",
    "link": "https://cn.nytimes.com/health/20260526/longevity-wellness-industry/dual",
    "pub_date": "2026-05-26 13:06:02",
    "author": "",
    "description": "PAUL SULLIVAN2026年5月26日 Dadu Shin Humans have — presumably — always aspired to living longer, healthier lives. Now that might be more possible than ever before — especially if you have enough money. 人类一直渴望活得更长久、更健康——大概是这…",
    "content": "PAUL SULLIVAN 2026年5月26日 Dadu Shin Humans have — presumably — always aspired to living longer, healthier lives. Now that might be more possible than ever before — especially if you have enough money. 人类一直渴望活得更长久、更健康——大概是这样。如今，这个愿望或许比以往任何时候都更有可能实现——尤其是如果你有足够的钱。…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cjwppy2z8w5o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "教宗良十四世警告「新型數碼奴役」風險 呼籲AI必須被「繳械」",
    "link": "https://www.bbc.com/zhongwen/articles/cjwppy2z8w5o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-26 12:59:07",
    "author": "",
    "description": "Getty Images / 良十四世在其首份通谕中同时警告崭新科技造成“新型数码奴役”的风险。 罗马天主教教宗良十四世（Pope Leo XIV）发表其任内首份重要教导文件，警告人工智能（AI，人工智慧）需要被“缴械”（disarmed）。 教宗表示：“我知道这个词语很强烈，但我刻意选用，因为当下需要能引起关注的字眼。” 通谕（encyclical）在技术上是致罗马天主教主教的书信，但过去数十年来，这类文件已成为教宗向全世界传达讯息的…",
    "content": "Getty Images / 良十四世在其首份通谕中同时警告崭新科技造成“新型数码奴役”的风险。 罗马天主教教宗良十四世（Pope Leo XIV）发表其任内首份重要教导文件，警告人工智能（AI，人工智慧）需要被“缴械”（disarmed）。 教宗表示：“我知道这个词语很强烈，但我刻意选用，因为当下需要能引起关注的字眼。” 通谕（encyclical）在技术上是致罗马天主教主教的书信，但过去数十年来，这类文件已成为教宗向全世界传达讯息的方式。 这封信虽主要聚焦人工智能，但良十四世同时亦就教会在奴隶制度中的角色，发表…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/usa/20260526/constitution-framers-president-executive-monarch/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "美国的制宪者们是不是过于乐观了？",
    "link": "https://cn.nytimes.com/usa/20260526/constitution-framers-president-executive-monarch/dual",
    "pub_date": "2026-05-26 12:36:02",
    "author": "",
    "description": "ADAM LIPTAK2026年5月26日 The men who drafted the Constitution knew they were playing with fire when they created a novel and powerful new office: the president of the United States. 签署宪法的人很清楚，当他们创造一个崭新且强大的新职位——美利坚合众国总统时，他们是…",
    "content": "ADAM LIPTAK 2026年5月26日 The men who drafted the Constitution knew they were playing with fire when they created a novel and powerful new office: the president of the United States. 签署宪法的人很清楚，当他们创造一个崭新且强大的新职位——美利坚合众国总统时，他们是在玩火。 “The first man put at the helm wil…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cwy22pde88po/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "美軍稱已對伊朗南部發動新一輪空襲",
    "link": "https://www.bbc.com/zhongwen/articles/cwy22pde88po/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-26 11:50:46",
    "author": "",
    "description": "Getty Images / 一架美国空军F-35“闪电 II”战斗机（2026年4月资料照片） 美军表示已对伊朗南部发动新一轮打击，目标包括伊朗的导弹发射场以及试图布设水雷的船只。 美国中央司令部在声明中指出，这些空袭属于“自卫”行动，旨在“保护我方部队免受伊朗部队带来的威胁”。 美国中央司令部发言人提姆·霍金斯（Tim Hawkins）上尉表示，美军“在持续停火期间仍保持克制，同时持续保卫我方部队”。 这些打击发生之际，伊朗外交部发…",
    "content": "Getty Images / 一架美国空军F-35“闪电 II”战斗机（2026年4月资料照片） 美军表示已对伊朗南部发动新一轮打击，目标包括伊朗的导弹发射场以及试图布设水雷的船只。 美国中央司令部在声明中指出，这些空袭属于“自卫”行动，旨在“保护我方部队免受伊朗部队带来的威胁”。 美国中央司令部发言人提姆·霍金斯（Tim Hawkins）上尉表示，美军“在持续停火期间仍保持克制，同时持续保卫我方部队”。 这些打击发生之际，伊朗外交部发言人伊斯梅尔·贝卡伊（Esmaeil Baqaei）表示，与美国的谈判已有部分进…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/opinion/20260526/us-china-ai-future/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "中美共同的人工智能焦虑：被未来收割",
    "link": "https://cn.nytimes.com/opinion/20260526/us-china-ai-future/dual",
    "pub_date": "2026-05-26 11:06:02",
    "author": "",
    "description": "YI-LING LIU2026年5月26日 Chris W. Kim Within an hour of landing in Shanghai, I was sitting in the back of a Didi cab while the driver pleaded with me to game the company’s algorithm. Didi is the “Uber of China” and has a ub…",
    "content": "YI-LING LIU 2026年5月26日 Chris W. Kim Within an hour of landing in Shanghai, I was sitting in the back of a Didi cab while the driver pleaded with me to game the company’s algorithm. Didi is the “Uber of China” and has a ubiquitous footprint in the country, disp…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/technology/20260526/pope-ai-silicon-valley/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "教宗良十四世挑战硅谷，警告人工智能风险",
    "link": "https://cn.nytimes.com/technology/20260526/pope-ai-silicon-valley/dual",
    "pub_date": "2026-05-26 10:06:03",
    "author": "",
    "description": "DAVID STREITFELD2026年5月26日 Remo Casilli/Reuters Silicon Valley has always had messianic dreams, dating back to the days when computers filled entire rooms. 硅谷一直以来都怀揣着救世主式的梦想，这可以追溯到计算机动辄占据整个房间的时代。 One of the oldest indust…",
    "content": "DAVID STREITFELD 2026年5月26日 Remo Casilli/Reuters Silicon Valley has always had messianic dreams, dating back to the days when computers filled entire rooms. 硅谷一直以来都怀揣着救世主式的梦想，这可以追溯到计算机动辄占据整个房间的时代。 One of the oldest industry jokes has a programmer asking a comp…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/business/20260526/asia-currency-iran-dollar/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "亚洲多国货币贬值，加剧经济紧张",
    "link": "https://cn.nytimes.com/business/20260526/asia-currency-iran-dollar/dual",
    "pub_date": "2026-05-26 08:36:02",
    "author": "",
    "description": "CATIE EDMONDSON2026年5月26日一名工人在印度尼西亚帕蒂港搬运冷冻鱼。随着柴油价格上涨，许多船只不再出海。 Willy Kurniawan/Reuters The Indian rupee and the Philippine peso have fallen to record lows. Japan and South Korea have spent billions propping up their curr…",
    "content": "CATIE EDMONDSON 2026年5月26日 一名工人在印度尼西亚帕蒂港搬运冷冻鱼。随着柴油价格上涨，许多船只不再出海。 Willy Kurniawan/Reuters The Indian rupee and the Philippine peso have fallen to record lows. Japan and South Korea have spent billions propping up their currencies in an attempt to avoid the same…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/crmp1mk2k82o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "人在死後會被記住什麼？現在思考你的遺產可能對你有益",
    "link": "https://www.bbc.com/zhongwen/articles/crmp1mk2k82o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-26 08:14:25",
    "author": "",
    "description": "Getty Images/BBC/Serenity Strull 研究显示，思考我们在死后会留下什么样的遗产，有助于改善心理健康，并让我们在生命中找到更多意义——即使我们仍然年轻。 当贝丝·亨特（Beth Hunter）的父亲被诊断出阿兹海默症（Alzheimer's disease）时，她问父亲是否可以录下他们的对话，好让她在未来的岁月里能再次聆听。 他拒绝了。亨特说，他不是那种会与她深入谈论彼此关系的人——他不面对自己的诊断，也不谈…",
    "content": "Getty Images/BBC/Serenity Strull 研究显示，思考我们在死后会留下什么样的遗产，有助于改善心理健康，并让我们在生命中找到更多意义——即使我们仍然年轻。 当贝丝·亨特（Beth Hunter）的父亲被诊断出阿兹海默症（Alzheimer's disease）时，她问父亲是否可以录下他们的对话，好让她在未来的岁月里能再次聆听。 他拒绝了。亨特说，他不是那种会与她深入谈论彼此关系的人——他不面对自己的诊断，也不谈论死亡。相反地，他优先书写自己的战争故事，先用手写，再请人协助打字。这是他认为死…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E9%9D%9E%E6%B4%B2/20260525-rfi%E6%B3%95%E5%B9%BF-%E9%9D%9E%E6%B4%B2-%E5%B0%BC%E5%8F%A4%E6%8B%89-%E9%9D%9E%E6%B4%B2-%E8%B4%9D%E5%AE%81%E6%96%B0%E6%80%BB%E7%BB%9F%E5%B0%B1%E8%81%8C-1-4%E5%86%85%E9%98%81%E6%98%AF%E5%A5%B3%E6%80%A7",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "贝宁新总统就职:1/4内阁是女性 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E9%9D%9E%E6%B4%B2/20260525-rfi%E6%B3%95%E5%B9%BF-%E9%9D%9E%E6%B4%B2-%E5%B0%BC%E5%8F%A4%E6%8B%89-%E9%9D%9E%E6%B4%B2-%E8%B4%9D%E5%AE%81%E6%96%B0%E6%80%BB%E7%BB%9F%E5%B0%B1%E8%81%8C-1-4%E5%86%85%E9%98%81%E6%98%AF%E5%A5%B3%E6%80%A7",
    "pub_date": "2026-05-26 07:45:01",
    "author": "",
    "description": "26/05/2026 - 01:00 在西非法语国家贝宁（le Bénin）。新总统罗穆亚尔德·瓦达尼（président béninois Romuald Wadagni）已于2026年05月24日星期天在位于科托努（Coutonou）的贝宁宪法法院（Cour constitutionnelle）前宣誓，正式接替帕特里斯·塔隆（Patrice TALON），成为国家元首。宣誓结束后，现场传出十二响礼炮和六千名宾客的热烈鼓掌声。有大约十…",
    "content": "26/05/2026 - 01:00 在西非法语国家贝宁（le Bénin）。新总统罗穆亚尔德·瓦达尼（président béninois Romuald Wadagni）已于2026年05月24日星期天在位于科托努（Coutonou）的贝宁宪法法院（Cour constitutionnelle）前宣誓，正式接替帕特里斯·塔隆（Patrice TALON），成为国家元首。宣誓结束后，现场传出十二响礼炮和六千名宾客的热烈鼓掌声。有大约十五支外国代表团见证了贝宁的这一历史性时刻，其中包括[萨赫勒国家联盟]（AES-A…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E4%B8%96%E5%8D%AB%E7%BB%84%E7%BB%87%E6%80%BB%E5%B9%B2%E4%BA%8B%E8%AD%A6%E5%91%8A%EF%BC%8C%E5%88%9A%E6%9E%9C-%E9%87%91-%E7%9A%84%E5%9F%83%E5%8D%9A%E6%8B%89%E7%96%AB%E6%83%85-%E6%9E%81%E5%85%B6%E4%B8%A5%E9%87%8D",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "世卫组织总干事警告，刚果（金）的埃博拉疫情“极其严重” - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E4%B8%96%E5%8D%AB%E7%BB%84%E7%BB%87%E6%80%BB%E5%B9%B2%E4%BA%8B%E8%AD%A6%E5%91%8A%EF%BC%8C%E5%88%9A%E6%9E%9C-%E9%87%91-%E7%9A%84%E5%9F%83%E5%8D%9A%E6%8B%89%E7%96%AB%E6%83%85-%E6%9E%81%E5%85%B6%E4%B8%A5%E9%87%8D",
    "pub_date": "2026-05-26 06:45:02",
    "author": "",
    "description": "26/05/2026 - 00:14 世界卫生组织（WHO）总干事谭德塞将于周二前往刚果民主共和国（简称刚果（金））。他周一警告说，当前在该国蔓延的埃博拉疫情“极其严重且难以控制”，他并呼吁周边国家“立即采取行动”。 在非洲联盟疾病控制与预防中心（Africa CDC）周一组织的线上部长级会议上，谭德塞解释说，首批病例发现较晚、受影响地区安全局势恶化、部分民众不信任政府以及缺乏疫苗等因素，使疫情防控工作变得异常复杂。 他表示：“疫情发现…",
    "content": "26/05/2026 - 00:14 世界卫生组织（WHO）总干事谭德塞将于周二前往刚果民主共和国（简称刚果（金））。他周一警告说，当前在该国蔓延的埃博拉疫情“极其严重且难以控制”，他并呼吁周边国家“立即采取行动”。 在非洲联盟疾病控制与预防中心（Africa CDC）周一组织的线上部长级会议上，谭德塞解释说，首批病例发现较晚、受影响地区安全局势恶化、部分民众不信任政府以及缺乏疫苗等因素，使疫情防控工作变得异常复杂。 他表示：“疫情发现得太晚，这意味着我们现在正在努力追赶一场传播速度极快的疫情。我们正在紧急加强应对…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E6%9E%81%E7%AB%AF%E7%83%AD%E6%B5%AA%E8%A2%AD%E5%87%BB%E6%AC%A7%E6%B4%B2-%E4%B8%93%E5%AE%B6%E6%8F%90%E9%86%92%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "极端热浪袭击欧洲 专家提醒注意事项 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E6%9E%81%E7%AB%AF%E7%83%AD%E6%B5%AA%E8%A2%AD%E5%87%BB%E6%AC%A7%E6%B4%B2-%E4%B8%93%E5%AE%B6%E6%8F%90%E9%86%92%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9",
    "pub_date": "2026-05-26 06:45:02",
    "author": "",
    "description": "26/05/2026 - 00:32 欧洲多国正在遭遇提前袭来的热浪，给人体带来严峻考验。法国气象学家认为：这次热浪前所未有，其发生概率一年中仅为千分之一。极端高温可能导致脱水，中暑甚至死亡，需认真防范。 健康风险 极端高温会对健康造成不同后果，世卫组织指出，极端高温往往会加剧既往病史，可能导致过早死亡或残疾。 人体体温调节机制可能不堪重负，从而出现疲劳、头痛、发热或睡眠障碍等与高温相关的症状。 这些症状有时预示着严重的健康问题，例如脱…",
    "content": "26/05/2026 - 00:32 欧洲多国正在遭遇提前袭来的热浪，给人体带来严峻考验。法国气象学家认为：这次热浪前所未有，其发生概率一年中仅为千分之一。极端高温可能导致脱水，中暑甚至死亡，需认真防范。 健康风险 极端高温会对健康造成不同后果，世卫组织指出，极端高温往往会加剧既往病史，可能导致过早死亡或残疾。 人体体温调节机制可能不堪重负，从而出现疲劳、头痛、发热或睡眠障碍等与高温相关的症状。 这些症状有时预示着严重的健康问题，例如脱水或因过度日晒导致的日射病。而最严重的风险是中暑，可能导致死亡。中暑是指人体过热…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E4%BE%9D%E6%97%A7%E6%98%AF-%E5%90%83%E4%BA%BA%E7%9A%84%E7%9F%BF%E5%B1%B1",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "依旧是“吃人的矿山”？ - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E4%BE%9D%E6%97%A7%E6%98%AF-%E5%90%83%E4%BA%BA%E7%9A%84%E7%9F%BF%E5%B1%B1",
    "pub_date": "2026-05-26 06:15:02",
    "author": "",
    "description": "25/05/2026 - 23:56 山西留神峪煤矿发生瓦斯爆炸，吞噬至少82名矿工，中国媒体相继揭露出的一些细节怵目惊心：下井矿工不让带定位卡，救援无法及时到位，企业盗采，下井人数远超公示牌显示名单…… 2000年代初期，中国矿山事故频繁，每年都有成千上万矿工死在井下。5月22日，山西长治市沁源县通洲集团留神峪煤矿发生瓦斯爆炸，根据官方数字，造成82人死亡、2人失联、128人受伤。一夜之间，似乎又回到了过去不久的被人形容为“吃人的矿山…",
    "content": "25/05/2026 - 23:56 山西留神峪煤矿发生瓦斯爆炸，吞噬至少82名矿工，中国媒体相继揭露出的一些细节怵目惊心：下井矿工不让带定位卡，救援无法及时到位，企业盗采，下井人数远超公示牌显示名单…… 2000年代初期，中国矿山事故频繁，每年都有成千上万矿工死在井下。5月22日，山西长治市沁源县通洲集团留神峪煤矿发生瓦斯爆炸，根据官方数字，造成82人死亡、2人失联、128人受伤。一夜之间，似乎又回到了过去不久的被人形容为“吃人的矿山”的黑暗年代。 为什么会发生如此惨重的事故？中国应急管理报24日报道表示，247…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E4%BF%84%E7%BD%97%E6%96%AF%E5%A8%81%E8%83%81%E5%B0%86%E5%8F%91%E5%8A%A8%E6%96%B0%E4%B8%80%E8%BD%AE%E6%89%93%E5%87%BB-%E5%91%BC%E5%90%81%E5%A4%96%E5%9B%BD%E4%BA%BA%E6%92%A4%E7%A6%BB%E5%9F%BA%E8%BE%85",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "俄罗斯威胁将发动新一轮打击 呼吁外国人撤离基辅 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E4%BF%84%E7%BD%97%E6%96%AF%E5%A8%81%E8%83%81%E5%B0%86%E5%8F%91%E5%8A%A8%E6%96%B0%E4%B8%80%E8%BD%AE%E6%89%93%E5%87%BB-%E5%91%BC%E5%90%81%E5%A4%96%E5%9B%BD%E4%BA%BA%E6%92%A4%E7%A6%BB%E5%9F%BA%E8%BE%85",
    "pub_date": "2026-05-26 05:45:02",
    "author": "",
    "description": "25/05/2026 - 23:30 俄罗斯外交部周一(5月25日）呼吁居住在基辅的外国公民，包括外交人员，尽快撤离乌克兰首都，并警告俄军将对基辅发动新一轮空袭。俄罗斯外长拉夫罗夫与美国国务卿鲁比奥通话，敦促美国撤离驻基辅使馆人员。基辅方面则敦促盟友“不要被俄罗斯的威胁所左右”。 法新社报道，俄罗斯上周末对乌克兰发动大规模空袭后发出新的警告。包括基辅在内的多个地区遭到猛烈打击，已造成至少4人死亡、约100人受伤。俄方还第三次动用新一代“…",
    "content": "25/05/2026 - 23:30 俄罗斯外交部周一(5月25日）呼吁居住在基辅的外国公民，包括外交人员，尽快撤离乌克兰首都，并警告俄军将对基辅发动新一轮空袭。俄罗斯外长拉夫罗夫与美国国务卿鲁比奥通话，敦促美国撤离驻基辅使馆人员。基辅方面则敦促盟友“不要被俄罗斯的威胁所左右”。 法新社报道，俄罗斯上周末对乌克兰发动大规模空袭后发出新的警告。包括基辅在内的多个地区遭到猛烈打击，已造成至少4人死亡、约100人受伤。俄方还第三次动用新一代“榛树”（Orechnik）导弹。 俄罗斯外交部周一在声明中警告，俄军将继续打击基…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E4%B8%AD%E5%9B%BD%E9%A6%96%E6%AC%A1%E5%AE%9E%E6%96%BD%E8%88%AA%E5%A4%A9%E5%91%98%E4%B8%80%E5%B9%B4%E6%9C%9F%E5%A4%AA%E7%A9%BA%E9%A9%BB%E7%95%99-%E4%B8%BA2030%E7%99%BB%E6%9C%88%E9%93%BA%E8%B7%AF",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "中国首次实施航天员一年期太空驻留 为2030登月铺路 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E4%B8%AD%E5%9B%BD%E9%A6%96%E6%AC%A1%E5%AE%9E%E6%96%BD%E8%88%AA%E5%A4%A9%E5%91%98%E4%B8%80%E5%B9%B4%E6%9C%9F%E5%A4%AA%E7%A9%BA%E9%A9%BB%E7%95%99-%E4%B8%BA2030%E7%99%BB%E6%9C%88%E9%93%BA%E8%B7%AF",
    "pub_date": "2026-05-26 05:45:02",
    "author": "",
    "description": "25/05/2026 - 23:35 在中美围绕载人登月展开新一轮太空竞争之际，中国24日向空间站发射神舟23号载人飞船，3名航天员进入太空，其中一人将执行长达一年的驻留任务，创下中国载人航天最长在轨纪录。路透社指出，北京希望借此研究长期太空驻留对人体的影响，并为2030年前实现载人登月积累经验。 神舟23号飞船于当地时间24日晚11时08分，在西北部酒泉卫星发射中心搭乘长征二号F遥二十三运载火箭升空。此次乘组包括任务专家李嘉颖、指令长…",
    "content": "25/05/2026 - 23:35 在中美围绕载人登月展开新一轮太空竞争之际，中国24日向空间站发射神舟23号载人飞船，3名航天员进入太空，其中一人将执行长达一年的驻留任务，创下中国载人航天最长在轨纪录。路透社指出，北京希望借此研究长期太空驻留对人体的影响，并为2030年前实现载人登月积累经验。 神舟23号飞船于当地时间24日晚11时08分，在西北部酒泉卫星发射中心搭乘长征二号F遥二十三运载火箭升空。此次乘组包括任务专家李嘉颖、指令长朱杨柱以及飞行员张宇智。其中，曾任香港警务督察的李嘉颖，成为首位参与中国载人航天…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E6%AC%A7%E6%B4%B2%E9%81%AD%E9%81%87%E7%BD%95%E8%A7%815%E6%9C%88%E9%85%B7%E6%9A%91-%E8%8B%B1%E5%9B%BD%E5%88%B7%E6%96%B0%E7%99%BE%E5%B9%B4%E9%AB%98%E6%B8%A9%E7%BA%AA%E5%BD%95-%E6%B3%95%E5%9B%BD%E5%8F%91%E5%B8%83%E8%AD%A6%E6%8A%A5",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "欧洲遭遇罕见5月酷暑 英国刷新百年高温纪录 法国发布警报 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E6%AC%A7%E6%B4%B2%E9%81%AD%E9%81%87%E7%BD%95%E8%A7%815%E6%9C%88%E9%85%B7%E6%9A%91-%E8%8B%B1%E5%9B%BD%E5%88%B7%E6%96%B0%E7%99%BE%E5%B9%B4%E9%AB%98%E6%B8%A9%E7%BA%AA%E5%BD%95-%E6%B3%95%E5%9B%BD%E5%8F%91%E5%B8%83%E8%AD%A6%E6%8A%A5",
    "pub_date": "2026-05-26 05:45:02",
    "author": "",
    "description": "25/05/2026 - 23:27 欧洲多国本周遭遇罕见5月热浪，英国首都伦敦25日刷新有记录以来5月最高气温，法国西部则进入酷暑预警状态。气候专家指出，这场异常高温再次凸显，欧洲正成为全球升温最快的地区之一。 英国气象局（Met Office）周一称，伦敦西南部皇家植物园邱园（Kew Gardens）当天气温首次升至34.8摄氏度，创下英国5月历史最高纪录。 英国气象局在社交平台X上表示：“25日成为英国有记录以来最热的5月天，较此…",
    "content": "25/05/2026 - 23:27 欧洲多国本周遭遇罕见5月热浪，英国首都伦敦25日刷新有记录以来5月最高气温，法国西部则进入酷暑预警状态。气候专家指出，这场异常高温再次凸显，欧洲正成为全球升温最快的地区之一。 英国气象局（Met Office）周一称，伦敦西南部皇家植物园邱园（Kew Gardens）当天气温首次升至34.8摄氏度，创下英国5月历史最高纪录。 英国气象局在社交平台X上表示：“25日成为英国有记录以来最热的5月天，较此前32.8摄氏度的纪录高出2度。”这一纪录此前曾分别于1922年和1944年出现…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E4%BC%8A%E6%9C%97%E9%AB%98%E7%BA%A7%E5%88%AB%E4%BB%A3%E8%A1%A8%E5%9B%A2%E8%B5%B4%E5%A4%9A%E5%93%88%E7%A3%8B%E5%95%86%E5%92%8C%E5%B9%B3%E5%8D%8F%E8%AE%AE-%E7%89%B9%E6%9C%97%E6%99%AE%E6%8E%A8%E5%8A%A8%E9%98%BF%E4%BB%A5%E5%85%B3%E7%B3%BB%E6%AD%A3%E5%B8%B8%E5%8C%96",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "伊朗高级别代表团赴多哈磋商和平协议 特朗普推动阿以关系正常化 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260525-%E4%BC%8A%E6%9C%97%E9%AB%98%E7%BA%A7%E5%88%AB%E4%BB%A3%E8%A1%A8%E5%9B%A2%E8%B5%B4%E5%A4%9A%E5%93%88%E7%A3%8B%E5%95%86%E5%92%8C%E5%B9%B3%E5%8D%8F%E8%AE%AE-%E7%89%B9%E6%9C%97%E6%99%AE%E6%8E%A8%E5%8A%A8%E9%98%BF%E4%BB%A5%E5%85%B3%E7%B3%BB%E6%AD%A3%E5%B8%B8%E5%8C%96",
    "pub_date": "2026-05-26 05:45:01",
    "author": "",
    "description": "25/05/2026 - 23:23 伊朗多名高级官员周一(5月25日）前往卡塔尔首都多哈，就中东和平协议展开磋商。与此同时，美国总统特朗普进一步提高谈判筹码，呼吁卡塔尔和沙特阿拉伯推动与以色列关系正常化。伊朗总统佩泽希齐扬周一下令恢复国际互联网接入服务。 此次赴多哈的伊朗代表团阵容罕见，包括首席谈判代表穆罕默德·巴盖尔·加利巴夫、外长阿拉格齐以及伊朗央行行长。这也是伊朗在战争期间对海湾邻国发动报复性打击后，首次派出如此高级别代表团访问…",
    "content": "25/05/2026 - 23:23 伊朗多名高级官员周一(5月25日）前往卡塔尔首都多哈，就中东和平协议展开磋商。与此同时，美国总统特朗普进一步提高谈判筹码，呼吁卡塔尔和沙特阿拉伯推动与以色列关系正常化。伊朗总统佩泽希齐扬周一下令恢复国际互联网接入服务。 此次赴多哈的伊朗代表团阵容罕见，包括首席谈判代表穆罕默德·巴盖尔·加利巴夫、外长阿拉格齐以及伊朗央行行长。这也是伊朗在战争期间对海湾邻国发动报复性打击后，首次派出如此高级别代表团访问卡塔尔。 伊朗官方通讯社IRNA报道称，“部分美国承诺可能将在多哈协助下落实”，…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E5%A4%A9%E4%B8%BB%E6%95%99%E7%9A%87%E8%89%AF%E5%8D%81%E5%9B%9B%E5%91%BC%E5%90%81%E8%A7%A3%E9%99%A4%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD%E6%AD%A6%E8%A3%85-%E9%98%B2%E5%85%B6%E6%94%AF%E9%85%8D%E4%BA%BA%E7%B1%BB",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "教皇良十四呼吁解除人工智能的武装 防止其支配人类 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E5%A4%A9%E4%B8%BB%E6%95%99%E7%9A%87%E8%89%AF%E5%8D%81%E5%9B%9B%E5%91%BC%E5%90%81%E8%A7%A3%E9%99%A4%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD%E6%AD%A6%E8%A3%85-%E9%98%B2%E5%85%B6%E6%94%AF%E9%85%8D%E4%BA%BA%E7%B1%BB",
    "pub_date": "2026-05-26 02:15:02",
    "author": "",
    "description": "25/05/2026 - 19:52 法新社5月25日消息，在梵蒂冈周一发布文件中，教皇良十四呼吁“解除”人工智能（AI）的“武装”，以“防止其统治人类，并要求对算法进行规范和监管，并谴责了其迅猛发展背后所隐藏的“新型奴役”。 在这篇题为《Magnifica Humanitas》（伟大的人类）的130页文本中，美籍教皇良十四以数字革命时代人类尊严的捍卫者的姿态，回应了当今时代的诸多挑战：生态问题、多边主义危机、经济垄断。 在这份致全体信…",
    "content": "25/05/2026 - 19:52 法新社5月25日消息，在梵蒂冈周一发布文件中，教皇良十四呼吁“解除”人工智能（AI）的“武装”，以“防止其统治人类，并要求对算法进行规范和监管，并谴责了其迅猛发展背后所隐藏的“新型奴役”。 在这篇题为《Magnifica Humanitas》（伟大的人类）的130页文本中，美籍教皇良十四以数字革命时代人类尊严的捍卫者的姿态，回应了当今时代的诸多挑战：生态问题、多边主义危机、经济垄断。 在这份致全体信徒的通谕中，他就社会、道德或神学问题阐明了立场，呼吁超越“正义战争”的概念，并谴…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E7%BE%8E%E4%BC%8A%E8%B0%88%E5%88%A4%E4%B9%8B%E9%99%85-%E5%85%A8%E7%90%83%E8%B6%85%E8%BF%87%E4%B8%80%E7%99%BE%E4%B8%87%E7%A9%86%E6%96%AF%E6%9E%97%E5%BC%80%E5%A7%8B%E6%9C%9D%E8%A7%90%E4%B9%8B%E6%97%85",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "美伊谈判之际 全球超过一百万穆斯林开始朝觐之旅 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E7%BE%8E%E4%BC%8A%E8%B0%88%E5%88%A4%E4%B9%8B%E9%99%85-%E5%85%A8%E7%90%83%E8%B6%85%E8%BF%87%E4%B8%80%E7%99%BE%E4%B8%87%E7%A9%86%E6%96%AF%E6%9E%97%E5%BC%80%E5%A7%8B%E6%9C%9D%E8%A7%90%E4%B9%8B%E6%97%85",
    "pub_date": "2026-05-26 01:15:02",
    "author": "",
    "description": "25/05/2026 - 18:52 周一，约150万穆斯林开始遵循古老的朝觐仪式，前往麦加参加穆斯林的盛大朝觐活动，此时正值各方为寻求中东冲突的持久解决方案而进行外交磋商之际。 法新社5月25日发自麦加的报道说，身着白衣的朝圣者们，聚集在伊斯兰教最神圣的城市，在高达45摄氏度的酷热中，完成了“塔瓦夫”仪式，即围绕位于大清真寺中心的黑石立方体——克尔白——转圈，世界各地的穆斯林都面向此处祈祷。 随后，当朝圣者们顶着令人窒息的酷热涌向米纳…",
    "content": "25/05/2026 - 18:52 周一，约150万穆斯林开始遵循古老的朝觐仪式，前往麦加参加穆斯林的盛大朝觐活动，此时正值各方为寻求中东冲突的持久解决方案而进行外交磋商之际。 法新社5月25日发自麦加的报道说，身着白衣的朝圣者们，聚集在伊斯兰教最神圣的城市，在高达45摄氏度的酷热中，完成了“塔瓦夫”仪式，即围绕位于大清真寺中心的黑石立方体——克尔白——转圈，世界各地的穆斯林都面向此处祈祷。 随后，当朝圣者们顶着令人窒息的酷热涌向米纳（Mina）广阔的帐篷城时，沙特当局再次呼吁他们使用遮阳伞并尽量减少日晒，以防中…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E4%BC%8A%E6%9C%97%E7%A7%B0%E4%B8%8E%E7%BE%8E%E5%9B%BD%E8%B0%88%E5%88%A4%E6%9C%89%E8%BF%9B%E5%B1%95-%E5%90%A6%E8%AE%A4%E5%8D%B3%E5%B0%86%E7%AD%BE%E7%BD%B2%E5%8D%8F%E8%AE%AE",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "伊朗称与美国谈判有进展 否认即将签署协议 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E4%BC%8A%E6%9C%97%E7%A7%B0%E4%B8%8E%E7%BE%8E%E5%9B%BD%E8%B0%88%E5%88%A4%E6%9C%89%E8%BF%9B%E5%B1%95-%E5%90%A6%E8%AE%A4%E5%8D%B3%E5%B0%86%E7%AD%BE%E7%BD%B2%E5%8D%8F%E8%AE%AE",
    "pub_date": "2026-05-26 00:15:02",
    "author": "",
    "description": "25/05/2026 - 17:20 据伊朗发言人周一重申，最关键的伊朗核计划的细节并未纳入谈判框架，并说，该问题将在达成总体框架议后才会讨论。 伊朗周一表示，与美国就持久结束战争进行的谈判取得了进展，但否认即将达成协议的说法。 伊朗外交部发言人巴盖依在例行记者会上表示：“可以说，我们在讨论的大部分问题上已达成共识”。“但要说协议即将签署，这谁也无法断言”。他并指责华盛顿态度反复无常。 该发言人在记者会上强调，目前正在制定的框架“旨在结…",
    "content": "25/05/2026 - 17:20 据伊朗发言人周一重申，最关键的伊朗核计划的细节并未纳入谈判框架，并说，该问题将在达成总体框架议后才会讨论。 伊朗周一表示，与美国就持久结束战争进行的谈判取得了进展，但否认即将达成协议的说法。 伊朗外交部发言人巴盖依在例行记者会上表示：“可以说，我们在讨论的大部分问题上已达成共识”。“但要说协议即将签署，这谁也无法断言”。他并指责华盛顿态度反复无常。 该发言人在记者会上强调，目前正在制定的框架“旨在结束整个地区，包括黎巴嫩在内的战争”。 他还重申，伊朗核计划的细节并未纳入其中，并…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E4%B9%8C%E5%85%8B%E5%85%B0%E8%A2%AD%E4%BF%84%E8%83%BD%E6%BA%90%E8%AE%BE%E6%96%BD-%E6%8D%AE%E6%8A%A5%E4%BF%84%E5%A2%83%E5%86%85%E4%B8%A4%E4%BA%BA%E6%AD%BB%E4%BA%A1",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "乌克兰袭俄能源设施 据报俄境内两人死亡 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E4%B9%8C%E5%85%8B%E5%85%B0%E8%A2%AD%E4%BF%84%E8%83%BD%E6%BA%90%E8%AE%BE%E6%96%BD-%E6%8D%AE%E6%8A%A5%E4%BF%84%E5%A2%83%E5%86%85%E4%B8%A4%E4%BA%BA%E6%AD%BB%E4%BA%A1",
    "pub_date": "2026-05-26 00:15:02",
    "author": "",
    "description": "25/05/2026 - 17:44 法新社25日莫斯科消息，周一，乌克兰对与其接壤的俄罗斯别尔哥罗德州和布良斯克州发动空袭，造成两人死亡。之前一天俄罗斯轰炸乌克兰造成4人死亡，100多人受伤。 周一，俄罗斯别尔哥罗德州当局在一份声明中称：“一架无人机袭击了格拉伊沃罗恩市的一辆汽车”，并对“一名平民遇难”表示哀悼。 布良斯克州代理州长科瓦尔丘克在电报群Telegram上写道，该州的贝拉亚别里奥兹卡镇遭到乌克兰空袭，一名男子死亡。 据路透…",
    "content": "25/05/2026 - 17:44 法新社25日莫斯科消息，周一，乌克兰对与其接壤的俄罗斯别尔哥罗德州和布良斯克州发动空袭，造成两人死亡。之前一天俄罗斯轰炸乌克兰造成4人死亡，100多人受伤。 周一，俄罗斯别尔哥罗德州当局在一份声明中称：“一架无人机袭击了格拉伊沃罗恩市的一辆汽车”，并对“一名平民遇难”表示哀悼。 布良斯克州代理州长科瓦尔丘克在电报群Telegram上写道，该州的贝拉亚别里奥兹卡镇遭到乌克兰空袭，一名男子死亡。 据路透社引述俄文传社消息，周一当地政府消息称，俄罗斯与乌克兰接壤的别尔哥罗德州遭到大规…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E4%B8%9C%E4%BA%AC%E9%93%B6%E5%BA%A7%E4%B8%80%E5%90%8D%E7%96%91%E4%BC%BC%E7%94%B7%E5%96%B7%E6%B4%92%E6%9F%90%E7%A7%8D%E7%89%A9%E8%B4%A8%E9%80%A0%E6%88%90%E7%BA%A620%E4%BA%BA%E5%8F%97%E4%BC%A4",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "东京银座一男喷洒某种物质造成约20人受伤 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E4%B8%9C%E4%BA%AC%E9%93%B6%E5%BA%A7%E4%B8%80%E5%90%8D%E7%96%91%E4%BC%BC%E7%94%B7%E5%96%B7%E6%B4%92%E6%9F%90%E7%A7%8D%E7%89%A9%E8%B4%A8%E9%80%A0%E6%88%90%E7%BA%A620%E4%BA%BA%E5%8F%97%E4%BC%A4",
    "pub_date": "2026-05-25 23:15:01",
    "author": "",
    "description": "25/05/2026 - 16:51 日本警方和消防部门官员周一表示，一名男子在东京市中心银座购物中心喷洒某种物质，导致大约20人受伤。警方正在追查。 据共同社说，一名女性在现场拨打110电话称，在东京都中央区银座的商业设施“GINZA SIX”出现“刺激性气味，大家都在咳嗽”。据东京警视厅筑地警署透露，约有25名男女表示身体不适，至少19人被送医，均无生命危险。 监控摄像头影像等显示，在接到报警前，一名似乎是男性的人在位于GINZA …",
    "content": "25/05/2026 - 16:51 日本警方和消防部门官员周一表示，一名男子在东京市中心银座购物中心喷洒某种物质，导致大约20人受伤。警方正在追查。 据共同社说，一名女性在现场拨打110电话称，在东京都中央区银座的商业设施“GINZA SIX”出现“刺激性气味，大家都在咳嗽”。据东京警视厅筑地警署透露，约有25名男女表示身体不适，至少19人被送医，均无生命危险。 监控摄像头影像等显示，在接到报警前，一名似乎是男性的人在位于GINZA SIX一楼的银行ATM区域喷射了喷雾。据称，该人已离开现场。警方以涉嫌伤害为由，…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ce8ppdxe023o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國山西礦難至少82死 十七年來最致命事故",
    "link": "https://www.bbc.com/zhongwen/articles/ce8ppdxe023o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-25 23:10:02",
    "author": "",
    "description": "Reuters / 中国山西省留神峪煤矿发生爆炸，是中国自2009年以来最严重的矿难。 中国山西省留神峪煤矿发生爆炸，官方公布已造成至少82人死亡、2人失踪、128人受伤，是中国自2009年以来最严重的矿难。事故发生后三天，央视于5月25日释出事发一刻片段，显示瓦斯爆炸冲击力强大。 留神峪煤矿由通洲集团营运，当局初步判断营运涉嫌严重违法。据报事发时有247名矿工当值，但一半人没有正式打卡报到，也未配戴紧急定位追踪器，令搜救工作难上加难。…",
    "content": "Reuters / 中国山西省留神峪煤矿发生爆炸，是中国自2009年以来最严重的矿难。 中国山西省留神峪煤矿发生爆炸，官方公布已造成至少82人死亡、2人失踪、128人受伤，是中国自2009年以来最严重的矿难。事故发生后三天，央视于5月25日释出事发一刻片段，显示瓦斯爆炸冲击力强大。 留神峪煤矿由通洲集团营运，当局初步判断营运涉嫌严重违法。据报事发时有247名矿工当值，但一半人没有正式打卡报到，也未配戴紧急定位追踪器，令搜救工作难上加难。 尽管中国在再生能源领域取得惊人发展，但仍是全球最大的煤炭消费国。近年矿难次数大…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E7%89%B9%E6%9C%97%E6%99%AE%E7%A7%B0%E8%A6%81%E4%B9%88%E6%98%AF%E4%B8%80%E9%A1%B9%E4%BC%9F%E5%A4%A7%E8%80%8C%E6%9C%89%E6%84%8F%E4%B9%89%E7%9A%84%E5%8D%8F%E8%AE%AE%EF%BC%8C%E8%A6%81%E4%B9%88%E5%B0%B1%E6%A0%B9%E6%9C%AC%E4%B8%8D%E4%BC%9A%E6%9C%89%E4%BB%BB%E4%BD%95%E5%8D%8F%E8%AE%AE",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "特朗普称要么是一项伟大而有意义的协议，要么就根本不会有任何协议 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E7%89%B9%E6%9C%97%E6%99%AE%E7%A7%B0%E8%A6%81%E4%B9%88%E6%98%AF%E4%B8%80%E9%A1%B9%E4%BC%9F%E5%A4%A7%E8%80%8C%E6%9C%89%E6%84%8F%E4%B9%89%E7%9A%84%E5%8D%8F%E8%AE%AE%EF%BC%8C%E8%A6%81%E4%B9%88%E5%B0%B1%E6%A0%B9%E6%9C%AC%E4%B8%8D%E4%BC%9A%E6%9C%89%E4%BB%BB%E4%BD%95%E5%8D%8F%E8%AE%AE",
    "pub_date": "2026-05-25 22:45:02",
    "author": "",
    "description": "25/05/2026 - 16:21 美国总统特朗普周一表示，与伊朗达成的协议，要么是一项伟大而有意义的协议，要么就根本不会有任何协议。 法新社说，尽管美伊双方都展现取得进展的迹象，但特朗普总统降低了人们对达成协议以永久结束中东战争的希望。 特朗普总统周日在其“真相社媒”（Truth Social）写道：“我已指示我的代表不要仓促达成协议，因为时间对我们有利”。他还警告说，美国继续对伊朗港口实施封锁，“直到达成协议、获得确认并签署协议为…",
    "content": "25/05/2026 - 16:21 美国总统特朗普周一表示，与伊朗达成的协议，要么是一项伟大而有意义的协议，要么就根本不会有任何协议。 法新社说，尽管美伊双方都展现取得进展的迹象，但特朗普总统降低了人们对达成协议以永久结束中东战争的希望。 特朗普总统周日在其“真相社媒”（Truth Social）写道：“我已指示我的代表不要仓促达成协议，因为时间对我们有利”。他还警告说，美国继续对伊朗港口实施封锁，“直到达成协议、获得确认并签署协议为止”。 据Axios新闻网报道，一位美国高级官员表示，白宫预计该协议不会在周日最…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E7%89%B9%E6%9C%97%E6%99%AE%E8%A6%81%E6%B1%82%E6%B2%99%E7%89%B9%E5%92%8C%E5%8D%A1%E5%A1%94%E5%B0%94%E5%9C%A8%E4%B8%8E%E4%BC%8A%E6%9C%97%E6%BD%9C%E5%9C%A8%E5%92%8C%E5%B9%B3%E6%A1%86%E6%9E%B6%E5%86%85%E7%AD%BE%E7%BD%B2-%E4%BA%9A%E4%BC%AF%E6%8B%89%E7%BD%95%E5%8D%8F%E8%AE%AE",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "特朗普要求沙特和卡塔尔在与伊朗潜在和平框架内签署《亚伯拉罕协议》 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E7%89%B9%E6%9C%97%E6%99%AE%E8%A6%81%E6%B1%82%E6%B2%99%E7%89%B9%E5%92%8C%E5%8D%A1%E5%A1%94%E5%B0%94%E5%9C%A8%E4%B8%8E%E4%BC%8A%E6%9C%97%E6%BD%9C%E5%9C%A8%E5%92%8C%E5%B9%B3%E6%A1%86%E6%9E%B6%E5%86%85%E7%AD%BE%E7%BD%B2-%E4%BA%9A%E4%BC%AF%E6%8B%89%E7%BD%95%E5%8D%8F%E8%AE%AE",
    "pub_date": "2026-05-25 22:45:02",
    "author": "",
    "description": "25/05/2026 - 16:24 美国总统唐纳德·特朗普周一要求以穆斯林为主的国家，尤其是沙特阿拉伯和卡塔尔，在关于伊朗的潜在和平协议框架内，与以色列实现关系正常化。 在“真相社交”（Truth Social）平台上的一篇长文中，特朗普列举了上周六他为结束与伊朗的战争而与一些领导人进行磋商的国家。他说：“我表示，鉴于美国为解决这一极其复杂的局势所做的一切努力，所有这些国家至少应被要求同时签署《亚伯拉罕协议》。” 法新社说《亚伯拉罕协…",
    "content": "25/05/2026 - 16:24 美国总统唐纳德·特朗普周一要求以穆斯林为主的国家，尤其是沙特阿拉伯和卡塔尔，在关于伊朗的潜在和平协议框架内，与以色列实现关系正常化。 在“真相社交”（Truth Social）平台上的一篇长文中，特朗普列举了上周六他为结束与伊朗的战争而与一些领导人进行磋商的国家。他说：“我表示，鉴于美国为解决这一极其复杂的局势所做的一切努力，所有这些国家至少应被要求同时签署《亚伯拉罕协议》。” 法新社说《亚伯拉罕协议》由唐纳德·特朗普在他第一个总统任期内推动，于2020年签署，该协议促成了以色…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E7%94%9F%E6%80%81/20260525-%E4%B8%96%E5%8D%AB%E7%BB%84%E7%BB%87-%E5%88%9A%E6%9E%9C-%E8%BF%91-%E5%87%BA%E7%8E%B0900%E5%A4%9A%E4%BE%8B%E7%96%91%E4%BC%BC%E5%9F%83%E5%8D%9A%E6%8B%89%E7%97%85%E4%BE%8B",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "世卫组织：刚果(金)出现900多例疑似埃博拉病例 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E7%94%9F%E6%80%81/20260525-%E4%B8%96%E5%8D%AB%E7%BB%84%E7%BB%87-%E5%88%9A%E6%9E%9C-%E8%BF%91-%E5%87%BA%E7%8E%B0900%E5%A4%9A%E4%BE%8B%E7%96%91%E4%BC%BC%E5%9F%83%E5%8D%9A%E6%8B%89%E7%97%85%E4%BE%8B",
    "pub_date": "2026-05-25 22:15:02",
    "author": "",
    "description": "25/05/2026 - 16:01 世界卫生组织总干事谭德塞周日宣布，刚果(金)迄今已发现900多例埃博拉疑似病例，其中包括101例确诊病例。 在刚果（金）爆发埃博拉疫情的中心地带，随着疫情恶化和死亡人数攀升，当地人处在恐惧和否认中。 蒙布瓦卢是一座拥有约13万居民的城市，位于刚果（金）东北部伊图里省，而埃博拉疫情的中心就在这里，目前已有204人死亡。 世卫组织总干事谭德塞于5月24日周日晚间宣布，刚果（金）疑似有900多人感染埃博拉…",
    "content": "25/05/2026 - 16:01 世界卫生组织总干事谭德塞周日宣布，刚果(金)迄今已发现900多例埃博拉疑似病例，其中包括101例确诊病例。 在刚果（金）爆发埃博拉疫情的中心地带，随着疫情恶化和死亡人数攀升，当地人处在恐惧和否认中。 蒙布瓦卢是一座拥有约13万居民的城市，位于刚果（金）东北部伊图里省，而埃博拉疫情的中心就在这里，目前已有204人死亡。 世卫组织总干事谭德塞于5月24日周日晚间宣布，刚果（金）疑似有900多人感染埃博拉，出现高烧和出血等症状。 世卫总干事谭德塞在X网站上写道：“随着刚果（金）抗击埃…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c8jvvywlmezo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國15年來最嚴重煤礦事故後，民眾怒火升溫",
    "link": "https://www.bbc.com/zhongwen/articles/c8jvvywlmezo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-25 18:33:25",
    "author": "",
    "description": "CCTV / 影片：中国煤矿发生气体爆炸事故 中国发生15年来最严重的矿难后，外界对涉嫌违反安全规定的情况愈发愤怒。 上周五，位于山西省、属于中国庞大煤矿产业核心地带的留神峪煤矿发生爆炸，造成至少82人死亡、超过120人受伤。 对许多在中国的人而言，这场悲剧令人想起2000年代那段煤矿事故频繁、死伤惨重的时期。许多人原以为，那样的年代早已过去。 如今，这些忧虑再次浮现，并在中国受到严密管控的互联网上蔓延。民众要求追责，质疑事故为何会发生…",
    "content": "CCTV / 影片：中国煤矿发生气体爆炸事故 中国发生15年来最严重的矿难后，外界对涉嫌违反安全规定的情况愈发愤怒。 上周五，位于山西省、属于中国庞大煤矿产业核心地带的留神峪煤矿发生爆炸，造成至少82人死亡、超过120人受伤。 对许多在中国的人而言，这场悲剧令人想起2000年代那段煤矿事故频繁、死伤惨重的时期。许多人原以为，那样的年代早已过去。 如今，这些忧虑再次浮现，并在中国受到严密管控的互联网上蔓延。民众要求追责，质疑事故为何会发生：“太令人心碎了，这么多宝贵生命逝去。我们到底何时才能真正把安全放在第一位？” …"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%BA%9A%E6%B4%B2/20260525-%E5%B7%B4%E5%9F%BA%E6%96%AF%E5%9D%A6%E9%99%86%E5%86%9B%E5%8F%82%E8%B0%8B%E9%95%BF%E7%A9%86%E5%B0%BC%E5%B0%94%E9%99%AA%E6%80%BB%E7%90%86%E8%AE%BF%E5%8D%8E-%E5%B0%86%E5%8C%97%E4%BA%AC%E7%BA%B3%E5%85%A5%E7%BE%8E%E4%BC%8A%E8%B0%83%E8%A7%A3%E8%BF%9B%E7%A8%8B%E6%A0%B8%E5%BF%83",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "巴基斯坦陆军参谋长穆尼尔陪总理访华 将北京纳入美伊调解进程核心？ - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%BA%9A%E6%B4%B2/20260525-%E5%B7%B4%E5%9F%BA%E6%96%AF%E5%9D%A6%E9%99%86%E5%86%9B%E5%8F%82%E8%B0%8B%E9%95%BF%E7%A9%86%E5%B0%BC%E5%B0%94%E9%99%AA%E6%80%BB%E7%90%86%E8%AE%BF%E5%8D%8E-%E5%B0%86%E5%8C%97%E4%BA%AC%E7%BA%B3%E5%85%A5%E7%BE%8E%E4%BC%8A%E8%B0%83%E8%A7%A3%E8%BF%9B%E7%A8%8B%E6%A0%B8%E5%BF%83",
    "pub_date": "2026-05-25 17:15:02",
    "author": "",
    "description": "25/05/2026 - 10:46 法新社引述巴基斯坦国家电视台周一（5月25号）报道，美国与伊朗冲突首席调解人，巴基斯坦陆军参谋长阿西姆·穆尼尔（Asim Munir）已经抵达北京，与总理谢赫巴兹·谢里夫（Shehbaz Sharif）一同访问中国，与中国领导人举行会晤。 据巴基斯坦国家电视台PTV播出的画面显示，谢里夫总理在北京与穆尼尔元帅一同会见中国领导人时表示，“世界正处于关键时刻”。他说：“巴基斯坦一直在美国和伊朗之间发挥真…",
    "content": "25/05/2026 - 10:46 法新社引述巴基斯坦国家电视台周一（5月25号）报道，美国与伊朗冲突首席调解人，巴基斯坦陆军参谋长阿西姆·穆尼尔（Asim Munir）已经抵达北京，与总理谢赫巴兹·谢里夫（Shehbaz Sharif）一同访问中国，与中国领导人举行会晤。 据巴基斯坦国家电视台PTV播出的画面显示，谢里夫总理在北京与穆尼尔元帅一同会见中国领导人时表示，“世界正处于关键时刻”。他说：“巴基斯坦一直在美国和伊朗之间发挥真诚的调解作用。穆尼尔元帅之前正在德黑兰，他不想错过这次重要的访问。”他最后说道：…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%B8%AF%E6%BE%B3%E5%8F%B0/20260525-%E5%8F%B0%E6%B9%BE%E5%A4%96%E9%95%BF%E6%9E%97%E4%BD%B3%E9%BE%99-%E7%BE%8E%E5%9B%BD%E5%AF%B9%E5%8F%B0140%E4%BA%BF%E7%BE%8E%E5%85%83%E5%86%9B%E5%94%AE%E4%BE%9D%E6%B3%95%E8%BF%9B%E8%A1%8C%E4%B8%94%E5%AF%B9%E5%8F%B0%E6%94%BF%E7%AD%96%E6%B2%A1%E6%9C%89%E6%94%B9%E5%8F%98",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "台湾外长林佳龙：美国对台140亿美元军售依法进行且对台政策没有改变 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%B8%AF%E6%BE%B3%E5%8F%B0/20260525-%E5%8F%B0%E6%B9%BE%E5%A4%96%E9%95%BF%E6%9E%97%E4%BD%B3%E9%BE%99-%E7%BE%8E%E5%9B%BD%E5%AF%B9%E5%8F%B0140%E4%BA%BF%E7%BE%8E%E5%85%83%E5%86%9B%E5%94%AE%E4%BE%9D%E6%B3%95%E8%BF%9B%E8%A1%8C%E4%B8%94%E5%AF%B9%E5%8F%B0%E6%94%BF%E7%AD%96%E6%B2%A1%E6%9C%89%E6%94%B9%E5%8F%98",
    "pub_date": "2026-05-25 17:15:02",
    "author": "",
    "description": "25/05/2026 - 10:48 特习会后美国对台军售成焦点。特朗普表示会就140亿美元军售案尽快做出决定。台湾外交部长与国安局长25日表示，再次重申美国对台政策不变，对台军售则依法进行中。 美国海军代理部长日前指称，美国因伊朗战争暂停140亿美元的对台军售案，美方人士则向媒体表示，如同特朗普总统所言，他很快会就对台军售案做出决定。 台湾外交部长林佳龙与国安局长蔡明彦25日在立法院出席「美中元首峰会后地缘政治新局对我国外交及总体国家…",
    "content": "25/05/2026 - 10:48 特习会后美国对台军售成焦点。特朗普表示会就140亿美元军售案尽快做出决定。台湾外交部长与国安局长25日表示，再次重申美国对台政策不变，对台军售则依法进行中。 美国海军代理部长日前指称，美国因伊朗战争暂停140亿美元的对台军售案，美方人士则向媒体表示，如同特朗普总统所言，他很快会就对台军售案做出决定。 台湾外交部长林佳龙与国安局长蔡明彦25日在立法院出席「美中元首峰会后地缘政治新局对我国外交及总体国家安全之冲击评估与因应」 并接受质询。 关于军售议题，林佳龙表示，诚如美方所提，特…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E6%B3%95%E5%B9%BFrfi%E6%8E%A8%E5%87%BA%E4%BA%9A%E7%BE%8E%E5%B0%BC%E4%BA%9A%E8%AF%AD%E7%A4%BE%E5%AA%92%E9%A2%91%E9%81%93%E6%97%A8%E5%9C%A8%E5%AF%B9%E6%8A%97%E7%BD%91%E7%BB%9C%E8%99%9A%E5%81%87%E4%BF%A1%E6%81%AF",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "法广RFI推出亚美尼亚语社媒频道旨在对抗网络虚假信息 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260525-%E6%B3%95%E5%B9%BFrfi%E6%8E%A8%E5%87%BA%E4%BA%9A%E7%BE%8E%E5%B0%BC%E4%BA%9A%E8%AF%AD%E7%A4%BE%E5%AA%92%E9%A2%91%E9%81%93%E6%97%A8%E5%9C%A8%E5%AF%B9%E6%8A%97%E7%BD%91%E7%BB%9C%E8%99%9A%E5%81%87%E4%BF%A1%E6%81%AF",
    "pub_date": "2026-05-25 17:15:01",
    "author": "",
    "description": "25/05/2026 - 10:44 法国国际广播电台（RFI）5月25日周一推出亚美尼亚语社交媒体咨询，主要面向年轻人，当务之急是在6月亚美尼亚议会选举前，对抗来自俄罗斯的受操纵和虚假信息”。 法广RFI母公司，负责管理法国对外公共视听媒体的“法国世界媒体集团”FMM 宣布，这项“RFI全新亚美尼亚语资讯服务将100%采用数字化形式，通过社交媒体（Instagram、TikTok、Facebook）发布”，并将“侧重于视频以及趣味性、…",
    "content": "25/05/2026 - 10:44 法国国际广播电台（RFI）5月25日周一推出亚美尼亚语社交媒体咨询，主要面向年轻人，当务之急是在6月亚美尼亚议会选举前，对抗来自俄罗斯的受操纵和虚假信息”。 法广RFI母公司，负责管理法国对外公共视听媒体的“法国世界媒体集团”FMM 宣布，这项“RFI全新亚美尼亚语资讯服务将100%采用数字化形式，通过社交媒体（Instagram、TikTok、Facebook）发布”，并将“侧重于视频以及趣味性、互动性和教育性的内容形式”。 法国世界媒体集团(France Médias Mo…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c1l22592njmo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "黎家盈：首位香港太空人被寄望激發民族主義浪潮",
    "link": "https://www.bbc.com/zhongwen/articles/c1l22592njmo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-25 16:26:42",
    "author": "",
    "description": "Reuters 2026年5月24日晚，黎家盈随中国“神舟二十三号”太空船升空，成为首位进入太空的香港公民。此事件在香港舆论引起广泛讨论与关注。 黎家盈在任务准备期间多次公开表达对祖国的感谢，提及“心怀家国”及希望香港青年融入国家发展大局等说法。她的“背靠祖国”言论被中港媒体广为引用，分析称中国当局希望藉此带动民族主义情绪，持续刺激香港年轻一代的爱国情怀。 港大博士和警方高官 Getty Images / 5月23日，黎家盈在酒泉参加记…",
    "content": "Reuters 2026年5月24日晚，黎家盈随中国“神舟二十三号”太空船升空，成为首位进入太空的香港公民。此事件在香港舆论引起广泛讨论与关注。 黎家盈在任务准备期间多次公开表达对祖国的感谢，提及“心怀家国”及希望香港青年融入国家发展大局等说法。她的“背靠祖国”言论被中港媒体广为引用，分析称中国当局希望藉此带动民族主义情绪，持续刺激香港年轻一代的爱国情怀。 港大博士和警方高官 Getty Images / 5月23日，黎家盈在酒泉参加记者会。 黎家盈1982年出生于香港。她在香港大学完成电脑科学理学士、密码学硕士及…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/business/20260525/chinese-luxury-brands/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "百万元豪华电动车、古法黄金：中国本土奢侈品崛起",
    "link": "https://cn.nytimes.com/business/20260525/chinese-luxury-brands/dual",
    "pub_date": "2026-05-25 14:36:02",
    "author": "",
    "description": "JOY DONG2026年5月25日李茂载驾驶着由华为和江淮汽车联合打造的尊界S800轿车。 Gilles Sabrié for The New York Times After years of driving a Mercedes-Benz and a BMW, Li Maozai made a choice that surprised even himself: He bought a Chinese luxury car. 开…",
    "content": "JOY DONG 2026年5月25日 李茂载驾驶着由华为和江淮汽车联合打造的尊界S800轿车。 Gilles Sabrié for The New York Times After years of driving a Mercedes-Benz and a BMW, Li Maozai made a choice that surprised even himself: He bought a Chinese luxury car. 开了多年的梅赛德斯-奔驰和宝马之后，李茂载（音）做了一个连他自己都感到惊讶的选…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/usa/20260525/strait-of-hormuz-reopen-iran-deal/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "霍尔木兹海峡有望重开，但特朗普的伊朗问题仍难解",
    "link": "https://cn.nytimes.com/usa/20260525/strait-of-hormuz-reopen-iran-deal/dual",
    "pub_date": "2026-05-25 14:06:02",
    "author": "",
    "description": "DAVID E. SANGER, TYLER PAGER2026年5月25日自冲突爆发以来，霍尔木兹海峡一直是焦点所在。 Reuters The temporary agreement that the Trump administration announced with Iran this weekend isn’t a peace deal. It isn’t a nuclear deal. It isn’t a missile …",
    "content": "DAVID E. SANGER, TYLER PAGER 2026年5月25日 自冲突爆发以来，霍尔木兹海峡一直是焦点所在。 Reuters The temporary agreement that the Trump administration announced with Iran this weekend isn’t a peace deal. It isn’t a nuclear deal. It isn’t a missile deal. 特朗普政府本周末宣布与伊朗达成的临时协议并非和平协议。它也不是核…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/czr2e5xjg42o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "足球世界盃2026：伊朗足協主席稱球隊基地已由美國改至墨西哥",
    "link": "https://www.bbc.com/zhongwen/articles/czr2e5xjg42o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-25 12:47:22",
    "author": "",
    "description": "Getty Images / 伊朗正在土耳其的训练营备战世界杯 伊朗足协主席表示，国际足联（FIFA）已批准将伊朗队的世界杯训练基地，从美国改至墨西哥。 梅赫迪·塔吉（Mehdi Taj）表示，伊朗队将改为驻紮在墨西哥边境城市蒂华纳市（Tijuana），但此变更尚未获得国际足联的最终确认。 伊朗原本被分配在美国亚利桑那州的图森（Tucson）作为世界杯基地，但由于中东地区持续的战争及相关安全疑虑，使得他们的参赛安排出现不确定性。 本届世…",
    "content": "Getty Images / 伊朗正在土耳其的训练营备战世界杯 伊朗足协主席表示，国际足联（FIFA）已批准将伊朗队的世界杯训练基地，从美国改至墨西哥。 梅赫迪·塔吉（Mehdi Taj）表示，伊朗队将改为驻紮在墨西哥边境城市蒂华纳市（Tijuana），但此变更尚未获得国际足联的最终确认。 伊朗原本被分配在美国亚利桑那州的图森（Tucson）作为世界杯基地，但由于中东地区持续的战争及相关安全疑虑，使得他们的参赛安排出现不确定性。 本届世界杯由美国、加拿大和墨西哥共同主办。伊朗预计于6月15日对阵新西兰、6月21日对…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cm2p9z51zj5o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "《007：黎明曙光》游戲新作揭示詹士邦脆弱一面",
    "link": "https://www.bbc.com/zhongwen/articles/cm2p9z51zj5o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-25 12:02:51",
    "author": "",
    "description": "IO Interactive / 《007黎明曙光》将会带来了伊恩·弗莱明笔下年轻版的特工。 一位全新的“詹士邦”（James Bond，又译詹姆斯·邦德）即将登场——但不是在大银幕，而是在电子游戏中亮相。 《007黎明曙光》（007 First Light ）呈现了伊恩·弗莱明（Ian Fleming）笔下这位经典特工的年轻版本，由爱尔兰演员派翠克·吉布森（Patrick Gibson，帕特里克・吉布森）饰演。 游戏描绘詹士邦在获得“…",
    "content": "IO Interactive / 《007黎明曙光》将会带来了伊恩·弗莱明笔下年轻版的特工。 一位全新的“詹士邦”（James Bond，又译詹姆斯·邦德）即将登场——但不是在大银幕，而是在电子游戏中亮相。 《007黎明曙光》（007 First Light ）呈现了伊恩·弗莱明（Ian Fleming）笔下这位经典特工的年轻版本，由爱尔兰演员派翠克·吉布森（Patrick Gibson，帕特里克・吉布森）饰演。 游戏描绘詹士邦在获得“00”特工资格之前的模样，为这个过去60多年来不断被重塑的角色带来全新的诠释。 …"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ckgpxkg35kwo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普指示談判代表「不要急於與伊朗達成協議」 油價大幅下跌",
    "link": "https://www.bbc.com/zhongwen/articles/ckgpxkg35kwo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-25 11:26:10",
    "author": "",
    "description": "AFP via Getty Images / 美国总统特朗普表示，“双方都必需花时间”达成协议。 美国总统特朗普（Donald Trump，川普）表示，他已指示谈判代表“不要急于与伊朗达成协议”，在此之前，他曾经暗示即将达成协议。 据报，相关协议内容包括延长为期60天的停火安排、重新开放霍尔木兹海峡，以及就伊朗核计划展开进一步谈判的方案。 特朗普在社交媒体发文称，谈判正朝向“建设性”的方式推进，但“双方都必需花时间把事情做好。” 他在上…",
    "content": "AFP via Getty Images / 美国总统特朗普表示，“双方都必需花时间”达成协议。 美国总统特朗普（Donald Trump，川普）表示，他已指示谈判代表“不要急于与伊朗达成协议”，在此之前，他曾经暗示即将达成协议。 据报，相关协议内容包括延长为期60天的停火安排、重新开放霍尔木兹海峡，以及就伊朗核计划展开进一步谈判的方案。 特朗普在社交媒体发文称，谈判正朝向“建设性”的方式推进，但“双方都必需花时间把事情做好。” 他在上周六表示，协议已“基本上谈妥”，引发外界猜测可能很快会正式公布。 周末，伊朗官员…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/business/20260525/what-is-naphtha/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "东亚陷入“石油脑危机”：伊朗战事引发供应链冲击",
    "link": "https://cn.nytimes.com/business/20260525/what-is-naphtha/dual",
    "pub_date": "2026-05-25 11:06:02",
    "author": "",
    "description": "RIVER AKIRA DAVIS, HISAKO UENO2026年5月25日日本食品巨头卡乐比表示，由于石脑油短缺，该公司被迫将薯片的包装更换为黑白样式。 Eugene Hoshiko/Associated Press Countries in Asia are reeling from a shortage of naphtha, a petroleum derivative used in a dizzying array of…",
    "content": "RIVER AKIRA DAVIS, HISAKO UENO 2026年5月25日 日本食品巨头卡乐比表示，由于石脑油短缺，该公司被迫将薯片的包装更换为黑白样式。 Eugene Hoshiko/Associated Press Countries in Asia are reeling from a shortage of naphtha, a petroleum derivative used in a dizzying array of products, from household plastic wrap…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/usa/20260525/green-card-application-changes-trump/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "美国绿卡申请流程突变引发困惑与焦虑",
    "link": "https://cn.nytimes.com/usa/20260525/green-card-application-changes-trump/dual",
    "pub_date": "2026-05-25 10:06:01",
    "author": "",
    "description": "CHRISTINA MORALES2026年5月25日公民及移民服务局负责管理公民身份系统。 Shannon Stapleton/Reuters A new federal policy that could require thousands of immigrants to return to their home countries before petitioning for green cards has applicants…",
    "content": "CHRISTINA MORALES 2026年5月25日 公民及移民服务局负责管理公民身份系统。 Shannon Stapleton/Reuters A new federal policy that could require thousands of immigrants to return to their home countries before petitioning for green cards has applicants and immigration lawyers scrambling to…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/world/20260525/trump-rubio-india-china/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "特朗普向中国示好引发印度担忧",
    "link": "https://cn.nytimes.com/world/20260525/trump-rubio-india-china/dual",
    "pub_date": "2026-05-25 09:36:02",
    "author": "",
    "description": "黄安伟2026年5月25日特朗普总统希望与习近平建立伙伴关系，这一愿望使得国务卿鲁比奥不得不向印度领导人解释特朗普的亚洲愿景。 Pool photo by Kenny Holston Between the military honor guard, flag-waving schoolchildren and state banquet in Beijing last week, President Trump found time …",
    "content": "黄安伟 2026年5月25日 特朗普总统希望与习近平建立伙伴关系，这一愿望使得国务卿鲁比奥不得不向印度领导人解释特朗普的亚洲愿景。 Pool photo by Kenny Holston Between the military honor guard, flag-waving schoolchildren and state banquet in Beijing last week, President Trump found time to lavish praise on Xi Jinping, the he…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c5y98055lqwo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "足球世界盃2026：值得關注的黑馬球隊",
    "link": "https://www.bbc.com/zhongwen/articles/c5y98055lqwo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-24 14:56:24",
    "author": "",
    "description": "AFP via Getty Images 国际足联（FIFA）世界杯决赛周的抽签已于去年在华盛顿特区举行，已晋级球队的球迷们将迫切想知道他们将与哪些其他国家进行比赛——但世界上大多数人口将没有代表参加。 印度、中国、印尼、巴基斯坦及尼日利亚——全球六个人口最多的国家之中有五个——都将缺席这个由美国、加拿大及墨西哥共同主办的赛事。 事实上，在最初参加资格赛的209个国家中，只剩64队仍有机会晋级决赛周。而经过3月的附加赛，最终晋级6月和7…",
    "content": "AFP via Getty Images 国际足联（FIFA）世界杯决赛周的抽签已于去年在华盛顿特区举行，已晋级球队的球迷们将迫切想知道他们将与哪些其他国家进行比赛——但世界上大多数人口将没有代表参加。 印度、中国、印尼、巴基斯坦及尼日利亚——全球六个人口最多的国家之中有五个——都将缺席这个由美国、加拿大及墨西哥共同主办的赛事。 事实上，在最初参加资格赛的209个国家中，只剩64队仍有机会晋级决赛周。而经过3月的附加赛，最终晋级6月和7月决赛圈的队伍将缩减至48支。 那么，如果你的国家未能晋级世界杯，应该支持哪一队…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c5y79gpxzp2o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "在日本離婚導致父母與子女分離，法律改革能否終結單獨監護的情況？",
    "link": "https://www.bbc.com/zhongwen/articles/c5y79gpxzp2o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-24 12:51:27",
    "author": "",
    "description": "Jiro Akiba/BBC / 在日本，父母分居后，只有一方拥有子女的法定监护权。 在日本一个平日的午后，邓约翰（John Deng，化名）站在公园一旁，听着其他孩子玩耍嬉笑的声音。 但他的儿子及女儿并不在其中。他怀念曾经与孩子们共度的那些平凡时光：带他们去公园、看着他们醒来、成为他们生活的一部分。 来自香港的邓约翰，过去22年一直居住在日本。在这里，他建立了自己的生活，遇上了前度，并且成为两个孩子的父亲——一名8岁的儿子和一名10岁…",
    "content": "Jiro Akiba/BBC / 在日本，父母分居后，只有一方拥有子女的法定监护权。 在日本一个平日的午后，邓约翰（John Deng，化名）站在公园一旁，听着其他孩子玩耍嬉笑的声音。 但他的儿子及女儿并不在其中。他怀念曾经与孩子们共度的那些平凡时光：带他们去公园、看着他们醒来、成为他们生活的一部分。 来自香港的邓约翰，过去22年一直居住在日本。在这里，他建立了自己的生活，遇上了前度，并且成为两个孩子的父亲——一名8岁的儿子和一名10岁的女儿。 但他表示，那种生活已经彻底崩塌了。他的婚姻破裂，在毫无预警的情况下，孩…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c332jgrkypeo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國山西煤礦爆炸據報至少82死，我們目前已知道什麼？",
    "link": "https://www.bbc.com/zhongwen/articles/c332jgrkypeo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-24 11:23:50",
    "author": "",
    "description": "Reuters / 事发时据报有247名工人在工作。 中国北部一个煤矿发生爆炸，根据官方新闻发布会，该事故已导致82人死亡、2人失联、128人受伤。 这宗瓦斯爆炸发生在山西省通洲集团营运的留神峪煤矿，是中国自2009年以来最严重的矿难。当局初步判断，涉事的通洲集团煤矿有重大违法行为。 爆炸发生于当地时间周五（5月22日）晚上19时29分（格林尼治标准时间11时29分），据报当时有247名工人在值班。数百名救援人员已被派往现场，超过100…",
    "content": "Reuters / 事发时据报有247名工人在工作。 中国北部一个煤矿发生爆炸，根据官方新闻发布会，该事故已导致82人死亡、2人失联、128人受伤。 这宗瓦斯爆炸发生在山西省通洲集团营运的留神峪煤矿，是中国自2009年以来最严重的矿难。当局初步判断，涉事的通洲集团煤矿有重大违法行为。 爆炸发生于当地时间周五（5月22日）晚上19时29分（格林尼治标准时间11时29分），据报当时有247名工人在值班。数百名救援人员已被派往现场，超过100人获救出。 中国国家主席习近平要求全力救治伤者，“科学组织搜救，妥善做好善后处置…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cm2prj02pdgo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "分析：美中新建貿易、投資委員會，能否為關稅戰「加裝防撞欄」？",
    "link": "https://www.bbc.com/zhongwen/articles/cm2prj02pdgo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-22 16:52:03",
    "author": "",
    "description": "Getty Images / 中国浙江省义乌市，一名摊商于义乌国际商贸城检查足球相关商品。 特朗普第二任期的中美贸易战，和第一任期相比，风格明显不同。 八年前，外界的注意力几乎都钉在“贸易协议”四个字上。中美双方也确实在努力推动签署一个“第一阶段”贸易协定，希望借由一揽子安排，缓和贸易争端，降低关税，增加大豆采购，以期抹平贸易逆差。 但到了第二任期，局面似乎变了。双方开始更坦率地承认，经贸分歧不是短期摩擦，而是结构性的、长期性的。想靠一…",
    "content": "Getty Images / 中国浙江省义乌市，一名摊商于义乌国际商贸城检查足球相关商品。 特朗普第二任期的中美贸易战，和第一任期相比，风格明显不同。 八年前，外界的注意力几乎都钉在“贸易协议”四个字上。中美双方也确实在努力推动签署一个“第一阶段”贸易协定，希望借由一揽子安排，缓和贸易争端，降低关税，增加大豆采购，以期抹平贸易逆差。 但到了第二任期，局面似乎变了。双方开始更坦率地承认，经贸分歧不是短期摩擦，而是结构性的、长期性的。想靠一纸协议，或者几轮谈判，就把中美之间的经贸问题一并解决，恐怕并不现实。 比如中国去…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cm2p1d71833o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「我愛世界盃，但價格實在太離譜」：門票價暴漲五倍，球迷什麼反應？",
    "link": "https://www.bbc.com/zhongwen/articles/cm2p1d71833o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-22 16:00:44",
    "author": "",
    "description": "Getty Images 圭多・佩拉尔塔（Guido Peralta）是一名会计师，也是阿根廷国家队的长期支持者。他在2022年卡塔尔世界杯结束后，便开始为2026年世界杯存钱，但他没有预料到这次需要这么多钱。 “卡塔尔世界杯时，我的门票花了1470美元。但这届世界杯，我已经花了6960美元买门票，”他接受BBC访问时说。他已经买到了从第一场比赛到决赛的每一场门票。 卫冕的阿根廷未必能打到决赛，于是他的部分门票之后或许可以退款——但如果…",
    "content": "Getty Images 圭多・佩拉尔塔（Guido Peralta）是一名会计师，也是阿根廷国家队的长期支持者。他在2022年卡塔尔世界杯结束后，便开始为2026年世界杯存钱，但他没有预料到这次需要这么多钱。 “卡塔尔世界杯时，我的门票花了1470美元。但这届世界杯，我已经花了6960美元买门票，”他接受BBC访问时说。他已经买到了从第一场比赛到决赛的每一场门票。 卫冕的阿根廷未必能打到决赛，于是他的部分门票之后或许可以退款——但如果球队一路杀到最后，他光是门票的花费就等同于自己在上届卡塔尔世界杯的全部开支。 “…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/clyp8zq1zrlo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "法航與空中巴士被裁定須為2009年空難過失殺人負責",
    "link": "https://www.bbc.com/zhongwen/articles/clyp8zq1zrlo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-22 13:05:04",
    "author": "",
    "description": "Getty Images / AF447航班在飞越大西洋途中失事坠海。 就2009年造成228人死亡的空难，法国航空（Air France）与空中巴士（Airbus）被裁定犯有过失杀人罪。 巴黎上诉法院裁定，航空公司与飞机制造商需对事件“单独且完全负责”。当时涉事航班AF447原由巴西里约热内卢飞往巴黎，途中坠入大西洋。 该客机在暴风雨中失速，随后坠海，机上所有人员罹难。 法院此前曾于2023年4月裁定两家公司无罪，但经历为期八周的审讯…",
    "content": "Getty Images / AF447航班在飞越大西洋途中失事坠海。 就2009年造成228人死亡的空难，法国航空（Air France）与空中巴士（Airbus）被裁定犯有过失杀人罪。 巴黎上诉法院裁定，航空公司与飞机制造商需对事件“单独且完全负责”。当时涉事航班AF447原由巴西里约热内卢飞往巴黎，途中坠入大西洋。 该客机在暴风雨中失速，随后坠海，机上所有人员罹难。 法院此前曾于2023年4月裁定两家公司无罪，但经历为期八周的审讯后，法院于周四改判有罪。两家公司一直否认控罪，并表示将提出上诉。 事故中，机上1…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c1k2gm0xx31o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "美國起訴卡斯特羅後，古巴局勢的三種可能",
    "link": "https://www.bbc.com/zhongwen/articles/c1k2gm0xx31o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-22 12:46:19",
    "author": "",
    "description": "Getty Images / 许多在美国的古巴流亡人士希望哈瓦那政府被推翻 美国以谋杀罪起诉94岁的古巴前总统劳尔・卡斯特罗（Raúl Castro），引发外界猜测，古巴会否成为华府下一个推动政权更替的目标。 在最大压力政策之下，古巴正面临数十年来最严重的燃料和能源短缺，多名美国官员亦持续呼吁结束这个已有66年历史的共产政权。 美国总统特朗普表示，他不认为有必要“升级行动”，但白宫同时强调，不会容忍距离美国本土仅90英里的“流氓国家”。…",
    "content": "Getty Images / 许多在美国的古巴流亡人士希望哈瓦那政府被推翻 美国以谋杀罪起诉94岁的古巴前总统劳尔・卡斯特罗（Raúl Castro），引发外界猜测，古巴会否成为华府下一个推动政权更替的目标。 在最大压力政策之下，古巴正面临数十年来最严重的燃料和能源短缺，多名美国官员亦持续呼吁结束这个已有66年历史的共产政权。 美国总统特朗普表示，他不认为有必要“升级行动”，但白宫同时强调，不会容忍距离美国本土仅90英里的“流氓国家”。 接下来的发展难以预测：可能是经济崩溃、国内动荡，甚至美国军事介入。以下是三种可…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cx21ywx9y2xo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "未來「正被推入黑暗」：從緬甸到委內瑞拉，民間如何抵抗官方網絡封鎖",
    "link": "https://www.bbc.com/zhongwen/articles/cx21ywx9y2xo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-22 08:20:48",
    "author": "",
    "description": "Thierry Falise/LightRocket via Getty Images / 随着军政府在部分地区实施网络封锁，“星链咖啡店”在缅甸各地涌现。 在缅甸的一间小型竹棚亭内，“敏”（Min）正准备开门营业。 凌乱的电线把一套离网太阳能系统连接到插座上，塑胶椅静候客人，手写菜单上列着肉类和沙拉小吃。 出于安全考量，我们替他化名。敏知道顾客会在这里逗留一段时间，他们来的原因只有一个——上网。 他说每天约有30人光顾这间咖啡店，两年…",
    "content": "Thierry Falise/LightRocket via Getty Images / 随着军政府在部分地区实施网络封锁，“星链咖啡店”在缅甸各地涌现。 在缅甸的一间小型竹棚亭内，“敏”（Min）正准备开门营业。 凌乱的电线把一套离网太阳能系统连接到插座上，塑胶椅静候客人，手写菜单上列着肉类和沙拉小吃。 出于安全考量，我们替他化名。敏知道顾客会在这里逗留一段时间，他们来的原因只有一个——上网。 他说每天约有30人光顾这间咖啡店，两年多前刚开业时，类似的咖啡店十分稀少，每天有300至400名顾客到访。他说：“需求…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c202gy98lg5o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普稱不樂見「台獨」，台灣民眾怎麼看？",
    "link": "https://www.bbc.com/zhongwen/articles/c202gy98lg5o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-21 17:46:32",
    "author": "",
    "description": "BBC / 特朗普称不乐见“台独” ，台湾民众怎么看？ 美国总统特朗普在结束访华行程后，接受媒体采访称“不想让任何人独立”，并认为对台军售将会是“很好的谈判筹码”，这番言论引发台湾社会舆论震荡。 作为回应，台湾总统赖清德首先是在民进党活动上明确定义“台独”，但随后发文称“没有所谓的‘台独’问题”。 他在5月20日就任两周年记者会上，重申“中华民国台湾是一个主权独立的国家”立场，但被追问“台独”问题时没有再进一步说明。 在台湾，“独立”的…",
    "content": "BBC / 特朗普称不乐见“台独” ，台湾民众怎么看？ 美国总统特朗普在结束访华行程后，接受媒体采访称“不想让任何人独立”，并认为对台军售将会是“很好的谈判筹码”，这番言论引发台湾社会舆论震荡。 作为回应，台湾总统赖清德首先是在民进党活动上明确定义“台独”，但随后发文称“没有所谓的‘台独’问题”。 他在5月20日就任两周年记者会上，重申“中华民国台湾是一个主权独立的国家”立场，但被追问“台独”问题时没有再进一步说明。 在台湾，“独立”的概念长期存在不同解读，“华独派”或“实质台独派”主张，中华民国已是主权独立国家，…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cg4pee61p2xo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "BBC俄羅斯編輯：普京享受了習近平的中式歡迎，卻沒把輸油管合同帶回家",
    "link": "https://www.bbc.com/zhongwen/articles/cg4pee61p2xo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-21 12:27:48",
    "author": "",
    "description": "EPA / 普京与习近平已见过不下40次。 有那么一刻，人们几乎会把北京误认成莫斯科。 当弗拉基米尔·普京（Vladimir Putin；普丁）与习近平踏上红地毯、走向人民大会堂时，一支中国军乐队奏起俄罗斯经典浪漫曲《莫斯科郊外的晚上》。 歌词中唱道：“如果你知道这些莫斯科的夜晚对我有多么珍贵。” 在乐声之中，是否隐约流露出一丝政治上的浪漫？ 甚至是“兄弟情谊”（bromance）……？ 普京对习近平说：“我亲爱的朋友。” 习近平回应普…",
    "content": "EPA / 普京与习近平已见过不下40次。 有那么一刻，人们几乎会把北京误认成莫斯科。 当弗拉基米尔·普京（Vladimir Putin；普丁）与习近平踏上红地毯、走向人民大会堂时，一支中国军乐队奏起俄罗斯经典浪漫曲《莫斯科郊外的晚上》。 歌词中唱道：“如果你知道这些莫斯科的夜晚对我有多么珍贵。” 在乐声之中，是否隐约流露出一丝政治上的浪漫？ 甚至是“兄弟情谊”（bromance）……？ 普京对习近平说：“我亲爱的朋友。” 习近平回应普京：“我的老朋友。” 这是两位领导人惯用的语言——他们乐于展示彼此建立了一种特殊…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cr7pjvl52j4o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "谷歌時隔十餘年再度推出智慧眼鏡 私隱問題仍受關注",
    "link": "https://www.bbc.com/zhongwen/articles/cr7pjvl52j4o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-21 09:05:51",
    "author": "",
    "description": "Bloomberg via Getty Images 备受关注的Google Glass失败十多年后，谷歌（Google）将再次尝试推出智慧眼镜（智能眼镜）。 这款眼镜预计于今年秋季上市，镜框内设有小型摄影机，镜脚内则配备扬声器，让谷歌的人工智能产品Gemini可与使用者互动。 谷歌在周二（5月19日）的年度开发者大会上首次展示这款产品，并推出由Warby Parker和镜特梦（Gentle Monster）设计的两种款式。 Googl…",
    "content": "Bloomberg via Getty Images 备受关注的Google Glass失败十多年后，谷歌（Google）将再次尝试推出智慧眼镜（智能眼镜）。 这款眼镜预计于今年秋季上市，镜框内设有小型摄影机，镜脚内则配备扬声器，让谷歌的人工智能产品Gemini可与使用者互动。 谷歌在周二（5月19日）的年度开发者大会上首次展示这款产品，并推出由Warby Parker和镜特梦（Gentle Monster）设计的两种款式。 Google Glass于2013年推出，但在2015年于英国上市仅七个月后便因价格与私隐…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cpdp9v8gl4no/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "《臺灣漫遊錄》奪布克文學獎：楊双子筆下的台灣美食與殖民記憶",
    "link": "https://www.bbc.com/zhongwen/articles/cpdp9v8gl4no/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-21 08:31:25",
    "author": "",
    "description": "BBC CHINESE/ JOY CHANG / 杨双子的作品尝试与国际读者对话，谈台湾历史与台湾人身份认同。 台湾作家杨双子凭着小说《臺湾漫游录》，夺得全球最具影响力的文学奖之一英国布克奖（Booker Prize）。她是本届唯一来自亚洲的作家，也刷新台湾作家在此奖项的纪录。 在颁奖前夕，她接受BBC中文专访，谈论这部关于台湾殖民历史的小说。 1938年，中日战争爆发不久。 在日本殖民地台湾，火车正一节节穿越纵贯铁道，运送战争物资。车…",
    "content": "BBC CHINESE/ JOY CHANG / 杨双子的作品尝试与国际读者对话，谈台湾历史与台湾人身份认同。 台湾作家杨双子凭着小说《臺湾漫游录》，夺得全球最具影响力的文学奖之一英国布克奖（Booker Prize）。她是本届唯一来自亚洲的作家，也刷新台湾作家在此奖项的纪录。 在颁奖前夕，她接受BBC中文专访，谈论这部关于台湾殖民历史的小说。 1938年，中日战争爆发不久。 在日本殖民地台湾，火车正一节节穿越纵贯铁道，运送战争物资。车厢内两名年轻女子并肩而坐，一个是穿着西式洋装的日本贵族，另一个是仍身着朴素传统大…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c202zlxy904o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "普京晤習近平：美俄元首「前後腳訪華」隱含的外交訊號",
    "link": "https://www.bbc.com/zhongwen/articles/c202zlxy904o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-20 19:56:51",
    "author": "",
    "description": "Reuters / 俄罗斯总统普京抵京与中国国家主席习近平会谈，距离美国总统特朗普完成访华行程不足一周。 俄罗斯总统普京抵达北京，于5月20日与中国国家主席习近平会谈。此行距离美国总统特朗普完成访华行程不足一周，北京连续接待美俄领导人，分析认为这种罕见的外交节奏，让中国再成为国际关注中心。 这次已是普京第25次访华，此行他与中方达成多项合作协议，涵盖能源、经贸、教育、科技等领域。外界更关注他与习近平有否讨论俄乌战事，以及中美俄关系。普京…",
    "content": "Reuters / 俄罗斯总统普京抵京与中国国家主席习近平会谈，距离美国总统特朗普完成访华行程不足一周。 俄罗斯总统普京抵达北京，于5月20日与中国国家主席习近平会谈。此行距离美国总统特朗普完成访华行程不足一周，北京连续接待美俄领导人，分析认为这种罕见的外交节奏，让中国再成为国际关注中心。 这次已是普京第25次访华，此行他与中方达成多项合作协议，涵盖能源、经贸、教育、科技等领域。外界更关注他与习近平有否讨论俄乌战事，以及中美俄关系。普京访华期间，克里姆林宫发言人向媒体表示，不排除普京与特朗普在11月中国主办的APE…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c4g04lk8x2eo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "從「定義台獨」到「有所收斂」的演說：賴清德如何論述台灣主權？",
    "link": "https://www.bbc.com/zhongwen/articles/c4g04lk8x2eo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-20 19:37:02",
    "author": "",
    "description": "Getty Images / 5月20日赖清德在执政两周年记者会中重申主权立场。 特朗普访华后的涉台言论，使“台湾独立”议题成为国际焦点。 台湾总统赖清德日前先是定调“台独”意涵，再发文称“没有所谓的‘台独’问题”、“中华民国台湾是一个主权独立的国家”。 他在5月20日执政二周年演说中重申，“中华民国与中华人民共和国互不隶属，是铁一般的事实”，同时说会“不卑不亢、维持现状”。他没有再就“台独”进一步说明，被指措辞“有所收敛”。 多名专家…",
    "content": "Getty Images / 5月20日赖清德在执政两周年记者会中重申主权立场。 特朗普访华后的涉台言论，使“台湾独立”议题成为国际焦点。 台湾总统赖清德日前先是定调“台独”意涵，再发文称“没有所谓的‘台独’问题”、“中华民国台湾是一个主权独立的国家”。 他在5月20日执政二周年演说中重申，“中华民国与中华人民共和国互不隶属，是铁一般的事实”，同时说会“不卑不亢、维持现状”。他没有再就“台独”进一步说明，被指措辞“有所收敛”。 多名专家对BBC中文指出，赖清德的主权论述本质上延续蔡英文路线，但其作风和直白的语言表述…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c8d80qm6jllo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普前腳離開，普京後腳抵京：兩場訪問背後的中國外交密碼",
    "link": "https://www.bbc.com/zhongwen/articles/c8d80qm6jllo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-20 17:16:10",
    "author": "",
    "description": "Reuters / 俄罗斯总统普京抵京与中国国家主席习近平会谈，距离美国总统特朗普完成访华行程不足一周。 美国总统特朗普（Donald Trump；川普）前脚刚离开中国，俄罗斯总统普京（Vladimir Putin；普丁）后脚就抵达北京。 短短一周内，北京连续接待来自华盛顿与莫斯科的两位领导人。 这种罕见的外交节奏，让中国再次成为全球政治关注的中心。 在当前国际秩序重组、俄乌战争长期化、中美竞争持续升级的背景下，这两场访问被放在同一个时…",
    "content": "Reuters / 俄罗斯总统普京抵京与中国国家主席习近平会谈，距离美国总统特朗普完成访华行程不足一周。 美国总统特朗普（Donald Trump；川普）前脚刚离开中国，俄罗斯总统普京（Vladimir Putin；普丁）后脚就抵达北京。 短短一周内，北京连续接待来自华盛顿与莫斯科的两位领导人。 这种罕见的外交节奏，让中国再次成为全球政治关注的中心。 在当前国际秩序重组、俄乌战争长期化、中美竞争持续升级的背景下，这两场访问被放在同一个时间轴上比较，几乎不可避免。 而在中国这个高度讲究礼仪与政治象征的外交体系中，谁得…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c4g09912wgdo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "解讀「中美建設性戰略穩定關係」：習近平新詞反映兩國關係現實境遇",
    "link": "https://www.bbc.com/zhongwen/articles/c4g09912wgdo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-19 17:51:58",
    "author": "",
    "description": "China News Service / 从“新型大国关系”换成“建设性战略稳定关系”，中美关系是升级还是降级？目前不得而知。 美国总统特朗普（Donald Trump；川普）结束了从落地到离开历时仅42小时的访华行程。两国官方与观察人士对这场缺乏具体协议的峰会众说纷纭，但一个外交新词汇从此诞生。 中国国家主席习近平在与特朗普谈判时称，中美两国将以构建“中美建设性战略稳定关系”作为新的目标——取代了他在2013年提出的“中美新型大国关系…",
    "content": "China News Service / 从“新型大国关系”换成“建设性战略稳定关系”，中美关系是升级还是降级？目前不得而知。 美国总统特朗普（Donald Trump；川普）结束了从落地到离开历时仅42小时的访华行程。两国官方与观察人士对这场缺乏具体协议的峰会众说纷纭，但一个外交新词汇从此诞生。 中国国家主席习近平在与特朗普谈判时称，中美两国将以构建“中美建设性战略稳定关系”作为新的目标——取代了他在2013年提出的“中美新型大国关系”。 中国官方媒体接连刊发文章，称新的定位“意义重大”，是中美关系“新典范”。中…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cg4pnn3rplqo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "為何人們對斯沃琪的Royal Pop系列如此瘋狂？",
    "link": "https://www.bbc.com/zhongwen/articles/cg4pnn3rplqo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-19 16:12:37",
    "author": "",
    "description": "AFP via Getty Images / 人们为了入手这款“Royal Pop”而排队数日。 一款限量发售的怀表上市，引发一场热潮，迫使全球多地门市关闭，部分地点甚至需要警方与保安人员介入，以应付失控的大批人潮。 “Royal Pop”出自斯沃琪（Swatch）与奢侈钟表品牌爱彼（Audemars Piguet，AP）备受瞩目的联名合作，上周六（5月16日）起在全球部分门市正式发售。 和过往类似的销售情况一样，有些人为了买到该系列八…",
    "content": "AFP via Getty Images / 人们为了入手这款“Royal Pop”而排队数日。 一款限量发售的怀表上市，引发一场热潮，迫使全球多地门市关闭，部分地点甚至需要警方与保安人员介入，以应付失控的大批人潮。 “Royal Pop”出自斯沃琪（Swatch）与奢侈钟表品牌爱彼（Audemars Piguet，AP）备受瞩目的联名合作，上周六（5月16日）起在全球部分门市正式发售。 和过往类似的销售情况一样，有些人为了买到该系列八款新表之一，排队等候了好几天。 然而，无论在线上或实体店面，市场对这款产品的狂热…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cvgzjje13jyo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "文革發動60週年：那十年，中國經歷了什麼？",
    "link": "https://www.bbc.com/zhongwen/articles/cvgzjje13jyo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-19 15:00:52",
    "author": "",
    "description": "Getty Images / 文革发动60周年：那十年，中国经历了什么？ 60年前，中共领导人毛泽东发动文化大革命，中国自此陷入长达十年的动乱。一场追求“民主”、“平等”，要建立理想社会的革命，为何最终会将整个民族拖入灾难的深渊？",
    "content": "Getty Images / 文革发动60周年：那十年，中国经历了什么？ 60年前，中共领导人毛泽东发动文化大革命，中国自此陷入长达十年的动乱。一场追求“民主”、“平等”，要建立理想社会的革命，为何最终会将整个民族拖入灾难的深渊？"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cn7pxxm1n3ko/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "專訪台灣作家楊双子：從美食探尋台灣殖民歷史",
    "link": "https://www.bbc.com/zhongwen/articles/cn7pxxm1n3ko/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-17 12:24:05",
    "author": "",
    "description": "BBC / 专访台湾作家杨双子：从美食探寻台湾殖民历史 英国最具指标的文学奖之一“布克奖”将于5月19日公布得主，台湾作家杨双子以小说《臺湾漫游录》入围决选名单。 她是本届唯一来自亚洲的作家、也刷新了台湾作家在此奖项的纪录。 《臺湾漫游录》以日本殖民时代的台湾为背景，讲述中日战争后的1938年，名为青山千鹤子的日本作家到台湾旅行，认识了本地通译王千鹤。故事围绕着她们的旅行与情谊展开，探讨在殖民权力的鸿沟之下，两方是否能平等、坦诚地交往。…",
    "content": "BBC / 专访台湾作家杨双子：从美食探寻台湾殖民历史 英国最具指标的文学奖之一“布克奖”将于5月19日公布得主，台湾作家杨双子以小说《臺湾漫游录》入围决选名单。 她是本届唯一来自亚洲的作家、也刷新了台湾作家在此奖项的纪录。 《臺湾漫游录》以日本殖民时代的台湾为背景，讲述中日战争后的1938年，名为青山千鹤子的日本作家到台湾旅行，认识了本地通译王千鹤。故事围绕着她们的旅行与情谊展开，探讨在殖民权力的鸿沟之下，两方是否能平等、坦诚地交往。 小说共有12章，每章以一道主角们品尝过的料理命名，食物暗示角色们的关系已经发展…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/czr2pjdj8ypo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普訪華落幕：美中各取所需，台灣、關稅等未解之事走向何方？",
    "link": "https://www.bbc.com/zhongwen/articles/czr2pjdj8ypo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-16 18:06:55",
    "author": "",
    "description": "Brendan Smialowski - Pool/Getty Images 红毯迎接、国宴款待、天坛参观、中南海漫步、受赠月季种子……美国总统特朗普的访华行程在一连串高规格接待与个人化互动中落幕。 但当镜头逐渐淡出，北京与华盛顿之间的棘手问题几乎都还留在桌上。 截至当前，没有确认的大订单、没有宣布关税休战延续、没有新的台湾共识，国际媒体普遍形容这次峰会“未达成重大协议”。 全球股市亦普遍下跌，反映市场对峰会成果感到失望。 某种程度上，…",
    "content": "Brendan Smialowski - Pool/Getty Images 红毯迎接、国宴款待、天坛参观、中南海漫步、受赠月季种子……美国总统特朗普的访华行程在一连串高规格接待与个人化互动中落幕。 但当镜头逐渐淡出，北京与华盛顿之间的棘手问题几乎都还留在桌上。 截至当前，没有确认的大订单、没有宣布关税休战延续、没有新的台湾共识，国际媒体普遍形容这次峰会“未达成重大协议”。 全球股市亦普遍下跌，反映市场对峰会成果感到失望。 某种程度上，这场峰会像是一部在高潮处突然停下的政治剧——气氛热烈，但真正的结局还未揭晓。 中…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c8xwr7vdk0no/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普與習近平舉行峰會數小時後，告誡台灣不要宣布獨立",
    "link": "https://www.bbc.com/zhongwen/articles/c8xwr7vdk0no/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-16 10:55:29",
    "author": "",
    "description": "Reuters / 特朗普在回程飞机上接受媒体采访时多次谈到台湾问题。 美国总统唐纳德·特朗普（川普）告诫台湾不要正式宣布脱离中国独立。 他在周五接受福斯新闻（Fox News，福克斯新闻）访问时表示：“我不希望有人走向独立。”这番言论是在他与中国国家主席习近平于北京结束为期两天的峰会后作出。 台湾总统赖清德此前表示，台湾无需正式宣布独立，因为台湾本身已将自己视为一个主权国家。 美国长期以来支持台湾，包括依法向其提供自我防卫的手段，但同…",
    "content": "Reuters / 特朗普在回程飞机上接受媒体采访时多次谈到台湾问题。 美国总统唐纳德·特朗普（川普）告诫台湾不要正式宣布脱离中国独立。 他在周五接受福斯新闻（Fox News，福克斯新闻）访问时表示：“我不希望有人走向独立。”这番言论是在他与中国国家主席习近平于北京结束为期两天的峰会后作出。 台湾总统赖清德此前表示，台湾无需正式宣布独立，因为台湾本身已将自己视为一个主权国家。 美国长期以来支持台湾，包括依法向其提供自我防卫的手段，但同时也必须在维持对台关系与与中国的外交关系之间取得平衡。 Reuters / 习近…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c152l37yvyyo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國「文化大革命」爆發60周年：學界詳解被掩蓋的文革真相 ——「集體殺戮」",
    "link": "https://www.bbc.com/zhongwen/articles/c152l37yvyyo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-16 09:45:07",
    "author": "",
    "description": "Getty Images 历史事实和大量学术研究显示，共产政权国家的每一场运动常常伴随着可怕的政治暴力与“集体杀戮”（包括国家恐怖、清洗、镇压、强制劳动、饥荒导致的大规模死亡等），半个多世纪前发生在中国的“文化大革命”也不例外。 然而，“文革”时期的极端暴力与“集体杀戮”，是一段极力被掩盖和扭曲，世人所普遍忽视的历史。 近年来，随着文革资料的收集和研究的深入，这一段鲜为人知的“集体杀戮”历史也开始浮现出来。 这些研究不仅对文革时期的死亡…",
    "content": "Getty Images 历史事实和大量学术研究显示，共产政权国家的每一场运动常常伴随着可怕的政治暴力与“集体杀戮”（包括国家恐怖、清洗、镇压、强制劳动、饥荒导致的大规模死亡等），半个多世纪前发生在中国的“文化大革命”也不例外。 然而，“文革”时期的极端暴力与“集体杀戮”，是一段极力被掩盖和扭曲，世人所普遍忽视的历史。 近年来，随着文革资料的收集和研究的深入，这一段鲜为人知的“集体杀戮”历史也开始浮现出来。 这些研究不仅对文革时期的死亡人数有了更接地一些的估算，更有助改变人们对文革的一些错误认识：文革时期造成死亡最…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cx21r0y12r8o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普訪華結果分析：美國盯著3B，中國盯著3T，誰佔了上風？",
    "link": "https://www.bbc.com/zhongwen/articles/cx21r0y12r8o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-15 19:30:03",
    "author": "",
    "description": "Getty Images / 习近平和特朗普在中南海春藕斋前合影。 “我能问一下主席吗？其他国家的贵宾，像总统或总理，他也会带他们来这里吗？”特朗普一边和习近平以及翻译走在中南海花园里，一边问道。 “很少，”习近平回答。“我们通常不会在这里举行外交活动。即使后来开始办一些，也还是非常少见。” “比如普京，”习近平补充说。俄罗斯总统普京在过去几次访华期间，曾多次到访中南海。 “很好，我喜欢。”特朗普说。 这是特朗普此次访华的最后一站。习近…",
    "content": "Getty Images / 习近平和特朗普在中南海春藕斋前合影。 “我能问一下主席吗？其他国家的贵宾，像总统或总理，他也会带他们来这里吗？”特朗普一边和习近平以及翻译走在中南海花园里，一边问道。 “很少，”习近平回答。“我们通常不会在这里举行外交活动。即使后来开始办一些，也还是非常少见。” “比如普京，”习近平补充说。俄罗斯总统普京在过去几次访华期间，曾多次到访中南海。 “很好，我喜欢。”特朗普说。 这是特朗普此次访华的最后一站。习近平邀请特朗普到中南海春耦斋茶叙，两人在这座1949年后成为中共中央和国务院办公中…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c362j4npz5xo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普時隔九年再度訪華，中國年輕一代的「美國夢」在褪色嗎？",
    "link": "https://www.bbc.com/zhongwen/articles/c362j4npz5xo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-14 11:09:58",
    "author": "",
    "description": "Alex Wong/Getty Images 今年31岁的姜方洲记得，上一次美国总统特朗普（Donald Trump；川普）访华的时候，他才刚刚大学毕业，当时中美关系仍处于稳定的趋势，中美贸易战亦未正式展开。 他认为，尽管当时也有关注特朗普访华一事，但心态比较像是看待历任美国总统访华那样，“我觉得每一次美国总统访华的话，都会在国内引起比较多的关注度。” 特朗普周三（5月13日）抵达北京，在他的第二任期首次访华，也是时隔近九年之后，再有在…",
    "content": "Alex Wong/Getty Images 今年31岁的姜方洲记得，上一次美国总统特朗普（Donald Trump；川普）访华的时候，他才刚刚大学毕业，当时中美关系仍处于稳定的趋势，中美贸易战亦未正式展开。 他认为，尽管当时也有关注特朗普访华一事，但心态比较像是看待历任美国总统访华那样，“我觉得每一次美国总统访华的话，都会在国内引起比较多的关注度。” 特朗普周三（5月13日）抵达北京，在他的第二任期首次访华，也是时隔近九年之后，再有在任美国总统访华。 姜方洲感受到，这些年间，中美关系经历了不同的起伏，“经过这些年…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c1j2pl97p1zo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「文化大革命」60週年：從幾大關鍵詞看這場十年文化浩劫",
    "link": "https://www.bbc.com/zhongwen/articles/c1j2pl97p1zo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-14 08:28:35",
    "author": "",
    "description": "Getty Images 1966年，中共领导人毛泽东发动“无产阶级文化大革命”。 此后的十年间，成千上万的学生组成“红卫兵”开展阶级斗争，知识分子、官员和普通百姓成为目标遭迫害，批斗、抄家、告密成为社会日常。 各界造反派亦在多地大规模夺权，时任中国国家主席刘少奇、大批军队将领、中共干部被被迫害致死。 全中国陷入一片红色狂欢，暴力活动使经济及教育停滞；被打死、迫害致死、自杀在内的“非正常死亡”人数至今没有正式统计数字。但综合学者研究，人…",
    "content": "Getty Images 1966年，中共领导人毛泽东发动“无产阶级文化大革命”。 此后的十年间，成千上万的学生组成“红卫兵”开展阶级斗争，知识分子、官员和普通百姓成为目标遭迫害，批斗、抄家、告密成为社会日常。 各界造反派亦在多地大规模夺权，时任中国国家主席刘少奇、大批军队将领、中共干部被被迫害致死。 全中国陷入一片红色狂欢，暴力活动使经济及教育停滞；被打死、迫害致死、自杀在内的“非正常死亡”人数至今没有正式统计数字。但综合学者研究，人数从两百万到两千万不等。 这场民间称之为“十年浩劫”的革命，后来官方给的定性结论…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cdxpv1r6y0zo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「八年貿易戰」後特朗普再訪華：打破舊平衡，還是重構新底線？",
    "link": "https://www.bbc.com/zhongwen/articles/cdxpv1r6y0zo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-12 15:24:22",
    "author": "",
    "description": "Getty Images / 一名参观者于2025年8月2日在印尼泗水举办的ARTSUBS展览期间，站在格兰・祖基菲里（Galam Zulkifli）的艺术装置旁，该装置描绘了三国领导人（从左至右）：中国的习近平、美国的唐纳德・特朗普与俄罗斯的弗拉基米尔・普京。 如果说特朗普第一次上任，彻底改变了中美经贸关系的走向，这么说可能一点都不为过。 在他之前，奥巴马执政的最后几年，裂缝已经在悄悄出现：贸易摩擦升温，技术竞争的苗头隐隐浮现。但几十…",
    "content": "Getty Images / 一名参观者于2025年8月2日在印尼泗水举办的ARTSUBS展览期间，站在格兰・祖基菲里（Galam Zulkifli）的艺术装置旁，该装置描绘了三国领导人（从左至右）：中国的习近平、美国的唐纳德・特朗普与俄罗斯的弗拉基米尔・普京。 如果说特朗普第一次上任，彻底改变了中美经贸关系的走向，这么说可能一点都不为过。 在他之前，奥巴马执政的最后几年，裂缝已经在悄悄出现：贸易摩擦升温，技术竞争的苗头隐隐浮现。但几十年积累的合作机制和外交惯性，依然在维系着这段关系的基本盘。经贸，是中美关系的“压…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c5yerdxdvz6o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "老鼠、選票與科學：拆解台北「安鼠之亂」背後的治理危機",
    "link": "https://www.bbc.com/zhongwen/articles/c5yerdxdvz6o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-08 20:03:23",
    "author": "",
    "description": "台北市政府 / 蒋万安召开记者会回应鼠患问题 距离台北市长选举约半年，寻求连任的国民党籍市长蒋万安遇到难题——鼠患，台湾网民戏称是“安鼠之乱”。 危机起点是台北年初出现怀疑是老鼠传播的“汉他病毒”死亡个案，随后社交平台疯传各类鼠踪影片，引发舆论热议，最新民调显示约一半台北市民认为鼠患严重。 在恐慌情绪之下，当局强调会“全力灭鼠”，但事实上各方都未能掌握鼠患的实际规模——因为不同于其他国际大城市，台北市并没有科学监测鼠患的机制。 分析指，…",
    "content": "台北市政府 / 蒋万安召开记者会回应鼠患问题 距离台北市长选举约半年，寻求连任的国民党籍市长蒋万安遇到难题——鼠患，台湾网民戏称是“安鼠之乱”。 危机起点是台北年初出现怀疑是老鼠传播的“汉他病毒”死亡个案，随后社交平台疯传各类鼠踪影片，引发舆论热议，最新民调显示约一半台北市民认为鼠患严重。 在恐慌情绪之下，当局强调会“全力灭鼠”，但事实上各方都未能掌握鼠患的实际规模——因为不同于其他国际大城市，台北市并没有科学监测鼠患的机制。 分析指，鼠患事件在网路传播下形成“后真相”现象，并演变为政治攻防，为年底地方选举增添变数…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cpd5j2nepp8o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國爆發式增長的團播潮背後：情感詐騙、主播收入和隱秘活動",
    "link": "https://www.bbc.com/zhongwen/articles/cpd5j2nepp8o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-04-13 11:58:20",
    "author": "",
    "description": "weibo / 团播过去几年在中国飞速发展。 20岁的杨女士在南京一家团播MCN公司（Multi-Channel Network，一种网红经济运作模式）工作三个月后决定辞职。“毫不夸张地说，做了团播主播后，你将告别所有个人生活。” 她告诉记者。 在做主播的这三个月里，杨女士每天下午2点起床，打出租车前往公司，花一个小时整理发型和化妆，并在晚上7点左右开始舞蹈团播，直到次日淩晨4点下班。 直播休息间隙和下播后，杨女士还要在抖音或微信等社交…",
    "content": "weibo / 团播过去几年在中国飞速发展。 20岁的杨女士在南京一家团播MCN公司（Multi-Channel Network，一种网红经济运作模式）工作三个月后决定辞职。“毫不夸张地说，做了团播主播后，你将告别所有个人生活。” 她告诉记者。 在做主播的这三个月里，杨女士每天下午2点起床，打出租车前往公司，花一个小时整理发型和化妆，并在晚上7点左右开始舞蹈团播，直到次日淩晨4点下班。 直播休息间隙和下播后，杨女士还要在抖音或微信等社交平台上“写作业”，与“榜一大哥”（高额打赏者）保持线上互动，通过营造暧昧甚至恋爱…"
  }
];

export default jsonData;
