const jsonData = [
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260911-%E9%A6%99%E6%B8%AF%E6%94%AF%E8%81%94%E4%BC%9A%E6%A1%88%E5%88%A4%E5%88%91-%E5%8F%B0%E9%99%86%E5%A7%94%E4%BC%9A-%E8%BF%BD%E6%B1%82%E6%B0%91%E4%B8%BB%E4%BA%BA%E6%9D%83%E6%97%A0%E7%BD%AA%EF%BC%8C%E5%91%BC%E5%90%81%E7%AB%8B%E5%8D%B3%E9%87%8A%E6%94%BE%E6%B0%91%E4%B8%BB%E4%BA%BA%E5%A3%AB",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "香港支联会案判刑 台陆委会：追求民主人权无罪，呼吁立即释放民主人士 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260911-%E9%A6%99%E6%B8%AF%E6%94%AF%E8%81%94%E4%BC%9A%E6%A1%88%E5%88%A4%E5%88%91-%E5%8F%B0%E9%99%86%E5%A7%94%E4%BC%9A-%E8%BF%BD%E6%B1%82%E6%B0%91%E4%B8%BB%E4%BA%BA%E6%9D%83%E6%97%A0%E7%BD%AA%EF%BC%8C%E5%91%BC%E5%90%81%E7%AB%8B%E5%8D%B3%E9%87%8A%E6%94%BE%E6%B0%91%E4%B8%BB%E4%BA%BA%E5%A3%AB",
    "pub_date": "2026-09-11 17:15:02",
    "author": "",
    "description": "11/09/2026 - 11:02 已解散的香港市民支援爱国民主运动联合会（简称支联会）、前主席李卓人、前副主席何俊仁及邹幸彤涉及煽动他人颠覆国家政权罪。何俊仁开审前认罪；支联会、李卓人及邹幸彤否认控罪，受审后被裁定罪成。案件周五在香港高等法院（借用西九龙裁判法院）作判刑。首被告支联会罚款150万元，李卓人判7年监禁、何俊仁判囚5年2个月、邹幸彤判囚7年3个月。对此，台湾陆委会通过新闻稿表示遗憾与谴责。陆委会强调，“追求民主人权无罪，…",
    "content": "11/09/2026 - 11:02 已解散的香港市民支援爱国民主运动联合会（简称支联会）、前主席李卓人、前副主席何俊仁及邹幸彤涉及煽动他人颠覆国家政权罪。何俊仁开审前认罪；支联会、李卓人及邹幸彤否认控罪，受审后被裁定罪成。案件周五在香港高等法院（借用西九龙裁判法院）作判刑。首被告支联会罚款150万元，李卓人判7年监禁、何俊仁判囚5年2个月、邹幸彤判囚7年3个月。对此，台湾陆委会通过新闻稿表示遗憾与谴责。陆委会强调，“追求民主人权无罪，有关方面以国安为由罗织罪名、进行政治审判，为专制政权护航，再次向国际社会证明所谓…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/china/20260911/hong-kong-tiananman-vigil-prison-sentence/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "香港天安门事件守夜活动组织者被判入狱",
    "link": "https://cn.nytimes.com/china/20260911/hong-kong-tiananman-vigil-prison-sentence/dual",
    "pub_date": "2026-09-11 17:06:02",
    "author": "",
    "description": "TIFFANY MAY2026年9月11日左起：李卓人，摄于2019年；邹幸彤，摄于2021年；何俊仁，摄于2019年。 Philip Fong/AFP — Getty Images; Lam Yik/Reuters; Isaac Lawrence/AFP — Getty Images A court in Hong Kong, once the only place in China where the victims of the …",
    "content": "TIFFANY MAY 2026年9月11日 左起：李卓人，摄于2019年；邹幸彤，摄于2021年；何俊仁，摄于2019年。 Philip Fong/AFP — Getty Images; Lam Yik/Reuters; Isaac Lawrence/AFP — Getty Images A court in Hong Kong, once the only place in China where the victims of the 1989 military massacre in Tiananmen Sq…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%B8%AF%E6%BE%B3%E5%8F%B0/20260911-%E5%8F%B0%E6%B9%BE%E5%89%AF%E6%80%BB%E7%BB%9F%E8%90%A7%E7%BE%8E%E7%90%B4%E8%A1%8C%E7%A8%8B%E4%BF%9D%E5%AF%86%E6%8A%B5%E6%AC%A7%E5%8F%82%E5%8A%A0%E8%AE%BA%E5%9D%9B-%E6%AC%A7%E6%B4%B2%E8%AE%AE%E4%BC%9A%E5%89%AF%E8%AE%AE%E9%95%BF%E5%BC%BA%E8%B0%83%E4%B8%AD%E5%9B%BD%E6%97%A0%E6%9D%83%E5%B9%B2%E9%A2%84",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "台湾副总统萧美琴行程保密抵欧参加论坛 欧洲议会副议长强调中国无权干预 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%B8%AF%E6%BE%B3%E5%8F%B0/20260911-%E5%8F%B0%E6%B9%BE%E5%89%AF%E6%80%BB%E7%BB%9F%E8%90%A7%E7%BE%8E%E7%90%B4%E8%A1%8C%E7%A8%8B%E4%BF%9D%E5%AF%86%E6%8A%B5%E6%AC%A7%E5%8F%82%E5%8A%A0%E8%AE%BA%E5%9D%9B-%E6%AC%A7%E6%B4%B2%E8%AE%AE%E4%BC%9A%E5%89%AF%E8%AE%AE%E9%95%BF%E5%BC%BA%E8%B0%83%E4%B8%AD%E5%9B%BD%E6%97%A0%E6%9D%83%E5%B9%B2%E9%A2%84",
    "pub_date": "2026-09-11 16:45:03",
    "author": "",
    "description": "11/09/2026 - 10:17 台湾副总统萧美琴低调抵达意大利参加第二届「文托泰内欧洲自由与民主论坛」。会议中，欧洲议会副议长皮齐耶诺表示，没有人可以决定谁能在此被接待或不被接待，特别是中国政权更无法做此决定。 台湾副总统萧美琴在外交部长林佳龙陪同下于11日抵达义大利，并前往文托泰内岛（Ventotene）出席第二届「文托泰内欧洲自由与民主论坛」。 民进党立法院党团书记长范云11日上午表示，很高兴萧副总统这次的外交突破。如同过去政…",
    "content": "11/09/2026 - 10:17 台湾副总统萧美琴低调抵达意大利参加第二届「文托泰内欧洲自由与民主论坛」。会议中，欧洲议会副议长皮齐耶诺表示，没有人可以决定谁能在此被接待或不被接待，特别是中国政权更无法做此决定。 台湾副总统萧美琴在外交部长林佳龙陪同下于11日抵达义大利，并前往文托泰内岛（Ventotene）出席第二届「文托泰内欧洲自由与民主论坛」。 民进党立法院党团书记长范云11日上午表示，很高兴萧副总统这次的外交突破。如同过去政府一再坚持，台湾不会因为有恶邻，就不出门交朋友。很高兴民主世界没有因为恐吓，就不…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260911-%E6%97%A5%E6%9C%AC%E9%98%B2%E5%8D%AB%E5%A4%A7%E8%87%A3%E5%86%8D%E6%AC%A1%E6%8F%90%E5%8F%8A%E6%97%A5%E6%9C%AC%E6%8B%A5%E6%9C%89%E6%A0%B8%E5%8A%A8%E5%8A%9B%E6%BD%9C%E8%89%87%E7%9A%84%E5%8F%AF%E8%83%BD%E6%80%A7",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "日本防卫大臣再次提及日本拥有核动力潜艇的可能性 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260911-%E6%97%A5%E6%9C%AC%E9%98%B2%E5%8D%AB%E5%A4%A7%E8%87%A3%E5%86%8D%E6%AC%A1%E6%8F%90%E5%8F%8A%E6%97%A5%E6%9C%AC%E6%8B%A5%E6%9C%89%E6%A0%B8%E5%8A%A8%E5%8A%9B%E6%BD%9C%E8%89%87%E7%9A%84%E5%8F%AF%E8%83%BD%E6%80%A7",
    "pub_date": "2026-09-11 16:45:03",
    "author": "",
    "description": "11/09/2026 - 10:26 日本防卫大臣小泉进次郎11日在记者会上就日本可否拥有核动力潜艇一事表示，在围绕年内修订日本安保相关三份文件的讨论中，将“在不排除任何选项的情况下进行研究”。 小泉6日在TBS电视节目中提到了引进核动力潜艇的必要性。他谈及美国总统特朗普承认韩国建造核动力潜艇一事时指出，“周边国家都拥有核潜艇”。他表示，关于潜艇的动力，“日本周边的环境已经严峻到必须讨论究竟像过去一样采用柴油动力，还是采用核动力的程度”…",
    "content": "11/09/2026 - 10:26 日本防卫大臣小泉进次郎11日在记者会上就日本可否拥有核动力潜艇一事表示，在围绕年内修订日本安保相关三份文件的讨论中，将“在不排除任何选项的情况下进行研究”。 小泉6日在TBS电视节目中提到了引进核动力潜艇的必要性。他谈及美国总统特朗普承认韩国建造核动力潜艇一事时指出，“周边国家都拥有核潜艇”。他表示，关于潜艇的动力，“日本周边的环境已经严峻到必须讨论究竟像过去一样采用柴油动力，还是采用核动力的程度”。 高市内阁一直试图推动日本导入核动力潜艇，高市早苗首相于2025年12月24日…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%B8%AF%E6%BE%B3%E5%8F%B0/20260911-%E7%BE%8E-%E5%8D%8E%E6%97%A5-%E9%98%BB%E6%8C%A0%E5%91%98%E5%B7%A5%E9%83%91%E5%98%89%E5%A6%82%E5%8F%82%E4%B8%8E%E8%AE%B0%E5%8D%8F%E4%B8%BB%E5%B8%AD%E9%80%89%E4%B8%BE%E7%BD%AA%E6%88%90",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "美《华日》阻挠员工郑嘉如参与记协主席选举罪成 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%B8%AF%E6%BE%B3%E5%8F%B0/20260911-%E7%BE%8E-%E5%8D%8E%E6%97%A5-%E9%98%BB%E6%8C%A0%E5%91%98%E5%B7%A5%E9%83%91%E5%98%89%E5%A6%82%E5%8F%82%E4%B8%8E%E8%AE%B0%E5%8D%8F%E4%B8%BB%E5%B8%AD%E9%80%89%E4%B8%BE%E7%BD%AA%E6%88%90",
    "pub_date": "2026-09-11 16:15:04",
    "author": "",
    "description": "11/09/2026 - 08:24 香港记者协会主席郑嘉如先被雇主《华尔街日报》(简称《华日》，WSJ）要求退选主席丶後在当选后不足一个月遭公司以「职位重组」为由解雇，为此提出私人检控，控告《华日》母公司违反《雇佣条例》。法庭周四（10日）裁定，被告涉及「阻止或阻吓雇员参与工会」的罪名成立，是香港第三宗雇主因阻止员工参与工会工作而被成功检控的个案。不过，另一项涉及因郑嘉如行使参与工会的权利而被解雇的罪名则不成立。郑嘉如认为，法庭的裁决…",
    "content": "11/09/2026 - 08:24 香港记者协会主席郑嘉如先被雇主《华尔街日报》(简称《华日》，WSJ）要求退选主席丶後在当选后不足一个月遭公司以「职位重组」为由解雇，为此提出私人检控，控告《华日》母公司违反《雇佣条例》。法庭周四（10日）裁定，被告涉及「阻止或阻吓雇员参与工会」的罪名成立，是香港第三宗雇主因阻止员工参与工会工作而被成功检控的个案。不过，另一项涉及因郑嘉如行使参与工会的权利而被解雇的罪名则不成立。郑嘉如认为，法庭的裁决有理和公平，但并非所有雇员有资源提私人检控，政府理应为雇员向违法的雇主提告，才能…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260911-%E6%B8%AF%E5%BA%9C%E4%BB%A5%E4%B8%80%E5%8F%A5%E5%8F%A3%E5%8F%B7%E9%87%8D%E5%88%A4%E6%94%AF%E8%81%94%E4%BC%9A%E9%AA%A8%E5%B9%B2%E5%85%A5%E7%8B%B15%E8%87%B37%E5%B9%B43%E4%B8%AA%E6%9C%88-%E9%82%B9%E5%B9%B8%E5%BD%A4%E6%9C%80%E9%87%8D-%E8%A2%AB%E5%91%8A%E8%AA%93%E4%B8%8A%E8%AF%89",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "港府以一句口号重判支联会骨干入狱5至7年3个月 邹幸彤最重 被告誓上诉 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260911-%E6%B8%AF%E5%BA%9C%E4%BB%A5%E4%B8%80%E5%8F%A5%E5%8F%A3%E5%8F%B7%E9%87%8D%E5%88%A4%E6%94%AF%E8%81%94%E4%BC%9A%E9%AA%A8%E5%B9%B2%E5%85%A5%E7%8B%B15%E8%87%B37%E5%B9%B43%E4%B8%AA%E6%9C%88-%E9%82%B9%E5%B9%B8%E5%BD%A4%E6%9C%80%E9%87%8D-%E8%A2%AB%E5%91%8A%E8%AA%93%E4%B8%8A%E8%AF%89",
    "pub_date": "2026-09-11 16:15:03",
    "author": "",
    "description": "11/09/2026 - 09:48 在香港举办六四烛光悼念晚会逾三十年后被迫解散的香港市民支援爱国民主运动联合会（支联会）及其领导人，因纲领中有「结束一党专政」的口号而被裁定「煽动颠覆国家政权」罪成，法庭认定此案「情节严重」，判处前主席李卓人和前副主席邹幸彤分别入狱 7年和 7年3个月；认罪的何俊仁在扣减刑期後须囚 5年2个月；至於已解散的支联会，则须缴交150万港元（约16.4万欧元）的罚款。不过，李卓人和邹幸彤已表明会上诉(详见另…",
    "content": "11/09/2026 - 09:48 在香港举办六四烛光悼念晚会逾三十年后被迫解散的香港市民支援爱国民主运动联合会（支联会）及其领导人，因纲领中有「结束一党专政」的口号而被裁定「煽动颠覆国家政权」罪成，法庭认定此案「情节严重」，判处前主席李卓人和前副主席邹幸彤分别入狱 7年和 7年3个月；认罪的何俊仁在扣减刑期後须囚 5年2个月；至於已解散的支联会，则须缴交150万港元（约16.4万欧元）的罚款。不过，李卓人和邹幸彤已表明会上诉(详见另文)。 三名国安法指定法官周五（11日）就支联会案判刑，指支联会案虽然没有涉及暴…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260911-%E6%9D%8E%E5%8D%93%E4%BA%BA%E5%A6%BB%E9%97%BB%E5%88%A4%E6%B4%92%E6%B3%AA%E7%A7%B0%E4%B8%8A%E8%AF%89-%E5%9B%BD%E5%AE%89%E8%AD%A6%E5%90%81%E5%A4%96%E5%8A%9B%E5%8B%BF%E6%8A%A8%E5%87%BB-%E4%BA%BA%E6%9D%83%E7%BB%84%E7%BB%87%E6%89%B9%E4%BB%A5%E8%A8%80%E5%85%A5%E7%BD%AA%E5%90%81%E6%94%BE%E4%BA%BA",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "李卓人妻闻判洒泪称上诉 国安警吁外力勿抨击 人权组织批以言入罪吁放人 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260911-%E6%9D%8E%E5%8D%93%E4%BA%BA%E5%A6%BB%E9%97%BB%E5%88%A4%E6%B4%92%E6%B3%AA%E7%A7%B0%E4%B8%8A%E8%AF%89-%E5%9B%BD%E5%AE%89%E8%AD%A6%E5%90%81%E5%A4%96%E5%8A%9B%E5%8B%BF%E6%8A%A8%E5%87%BB-%E4%BA%BA%E6%9D%83%E7%BB%84%E7%BB%87%E6%89%B9%E4%BB%A5%E8%A8%80%E5%85%A5%E7%BD%AA%E5%90%81%E6%94%BE%E4%BA%BA",
    "pub_date": "2026-09-11 16:15:03",
    "author": "",
    "description": "11/09/2026 - 09:54 被迫解散的香港市民支援爱国民主运动联合会(支联会)及其三名前正副主席因为煽动颠覆国家政权罪成而被重判 7年3个月至 5年2个月，当中两名被告家属誓言上诉，当中，李卓人妻子强调，三人只因发声而被重判，象征香港的言论自由已成「过去式」。另外，海外的香港人权资讯中心亦认定，案件明显是「以言入罪」，指港府违反国际公约，要求立刻释放三人。 邓燕娥：判刑俨如罚六四悼念港人 一定上诉 闻判后，李卓人妻子邓燕娥和邹…",
    "content": "11/09/2026 - 09:54 被迫解散的香港市民支援爱国民主运动联合会(支联会)及其三名前正副主席因为煽动颠覆国家政权罪成而被重判 7年3个月至 5年2个月，当中两名被告家属誓言上诉，当中，李卓人妻子强调，三人只因发声而被重判，象征香港的言论自由已成「过去式」。另外，海外的香港人权资讯中心亦认定，案件明显是「以言入罪」，指港府违反国际公约，要求立刻释放三人。 邓燕娥：判刑俨如罚六四悼念港人 一定上诉 闻判后，李卓人妻子邓燕娥和邹幸彤母亲神情哀伤，她们在前支联会常委刘家仪等人陪同下在法院外接受媒体访问。邓燕娥…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cq63868gq5qo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "香港支聯會「煽動顛覆」案：被告們的伴侶與戰友",
    "link": "https://www.bbc.com/zhongwen/articles/cq63868gq5qo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-11 15:48:01",
    "author": "",
    "description": "EPA / 支联会案判刑后，邓燕娥（左二）、刘家仪（右二）、邹幸彤母亲刘华珍（中）、前民主派政党社民连义工李盈姿（左一）、前支联会常委关振邦（后）与前泛民主派区议员陈剑琴（右一）在法院外举起“六四”手势合照。 香港支联会被指煽动颠覆政权的案件，历经5年，三名核心人物的判刑结果尘埃落定。 前主席李卓人被判囚7年，邹幸彤的刑期最高，达7年3个月；在开审前认罪的何俊仁被判囚5年2个月。 散庭时，李卓人作出罗马天主教“划十字”的手势，并向公众席…",
    "content": "EPA / 支联会案判刑后，邓燕娥（左二）、刘家仪（右二）、邹幸彤母亲刘华珍（中）、前民主派政党社民连义工李盈姿（左一）、前支联会常委关振邦（后）与前泛民主派区议员陈剑琴（右一）在法院外举起“六四”手势合照。 香港支联会被指煽动颠覆政权的案件，历经5年，三名核心人物的判刑结果尘埃落定。 前主席李卓人被判囚7年，邹幸彤的刑期最高，达7年3个月；在开审前认罪的何俊仁被判囚5年2个月。 散庭时，李卓人作出罗马天主教“划十字”的手势，并向公众席鞠躬。邹幸彤向公众席飞吻，亦有向律师挥手示意，带着笑容捧着文件；何俊仁转身离去。…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ced75zwgd1lo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "911事件25年後 美國機場安檢醞釀「鬆綁」：無票可到登機口送行、滿瓶水可過安檢",
    "link": "https://www.bbc.com/zhongwen/articles/ced75zwgd1lo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-11 15:40:27",
    "author": "",
    "description": "Getty Images 911事件后，美国机场发生了翻天覆地的变化；25年过去，新的政策调整正让部分昔日被禁的做法重新回归。 美国运输安全管理局（TSA）宣布，未来将允许没有机票的人通过安检，到登机门与亲友见面或送行。 美国运输安全管理局也正在考虑允许部分美国旅客携带装满水的水瓶通过安检。这将推翻2006年一宗未遂恐怖袭击阴谋后实施的政策。 一位航空安全专家向BBC表示，这些改变是数十年来航空安全领域最重大的调整之一，而背后原因很可能…",
    "content": "Getty Images 911事件后，美国机场发生了翻天覆地的变化；25年过去，新的政策调整正让部分昔日被禁的做法重新回归。 美国运输安全管理局（TSA）宣布，未来将允许没有机票的人通过安检，到登机门与亲友见面或送行。 美国运输安全管理局也正在考虑允许部分美国旅客携带装满水的水瓶通过安检。这将推翻2006年一宗未遂恐怖袭击阴谋后实施的政策。 一位航空安全专家向BBC表示，这些改变是数十年来航空安全领域最重大的调整之一，而背后原因很可能是技术进步，而非安全标准下降。 参与美国预先安检计画（TSA PreCheck计…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/usa/20260911/did-9-11-really-change-everything/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "9·11事件真的改变了一切吗？",
    "link": "https://cn.nytimes.com/usa/20260911/did-9-11-really-change-everything/dual",
    "pub_date": "2026-09-11 15:06:02",
    "author": "",
    "description": "CHARLES HOMANS2026年9月11日 Illustration by Chantal Jahchan One of the best firsthand accounts of the Sept. 11 attacks I’ve read is a short essay titled “Diary of Disaster” by Nicholas Spangler, at the time a 25-year-old jo…",
    "content": "CHARLES HOMANS 2026年9月11日 Illustration by Chantal Jahchan One of the best firsthand accounts of the Sept. 11 attacks I’ve read is a short essay titled “ Diary of Disaster ” by Nicholas Spangler, at the time a 25-year-old journalism-school student and today a r…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/usa/20260911/vance-iran-war-trump-munitions/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "副总统万斯向军方官员寻求伊朗战争真实评估",
    "link": "https://cn.nytimes.com/usa/20260911/vance-iran-war-trump-munitions/dual",
    "pub_date": "2026-09-11 13:36:03",
    "author": "",
    "description": "JONATHAN SWAN, ADAM ENTOUS, MAGGIE HABERMAN2026年9月11日 Vice President JD Vance took the unusual step over the spring and summer of calling U.S. military commanders in the Middle East, Europe and Asia directly, seeking the…",
    "content": "JONATHAN SWAN, ADAM ENTOUS, MAGGIE HABERMAN 2026年9月11日 Vice President JD Vance took the unusual step over the spring and summer of calling U.S. military commanders in the Middle East, Europe and Asia directly, seeking their unvarnished assessments of the Iran …"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c74e03x93l7o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "為甚麼我們會記錯911事件？",
    "link": "https://www.bbc.com/zhongwen/articles/c74e03x93l7o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-11 13:31:27",
    "author": "",
    "description": "BBC / 为甚么我们会记错911事件？ 记忆可能是错的？911事件发生后，大部分人也许能清楚记得自己当时身在何处，以及是如何得知这消息。其他重大新闻事件也有类似的鲜明记忆。 这种记忆被称为“闪光灯记忆”（flashbulb memories），感觉非常真实和准确，但研究显示，它们其实可能和其他记忆一样不可靠。 为甚么我们会如此相信这些记忆？而记错事情，是否反而可能对我们有好处？",
    "content": "BBC / 为甚么我们会记错911事件？ 记忆可能是错的？911事件发生后，大部分人也许能清楚记得自己当时身在何处，以及是如何得知这消息。其他重大新闻事件也有类似的鲜明记忆。 这种记忆被称为“闪光灯记忆”（flashbulb memories），感觉非常真实和准确，但研究显示，它们其实可能和其他记忆一样不可靠。 为甚么我们会如此相信这些记忆？而记错事情，是否反而可能对我们有好处？"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c99dg718vg2o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "間諜、戰略與錯失的機會：911的教訓至今仍在消化",
    "link": "https://www.bbc.com/zhongwen/articles/c99dg718vg2o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-11 13:31:09",
    "author": "",
    "description": "BBC 数十年来，无数领导人都曾表示，政府的首要职责是保障人民安全。2001年9月11日，美国显然未能做到这一点。情报其实已经存在，但令人遗憾的是，当时没有人及时将所有线索串联起来。 911，也就是后来人们对这场美国袭击事件的称呼，连同其后续回应，共同塑造了本世纪前20年的外交、安全与情报政策。 2001年9月11日，当“基地组织”（al-Qaeda）的自杀式劫机者驾驶劫持的客机撞向世界贸易中心时，我刚结束在BBC中东分社的工作。当一名…",
    "content": "BBC 数十年来，无数领导人都曾表示，政府的首要职责是保障人民安全。2001年9月11日，美国显然未能做到这一点。情报其实已经存在，但令人遗憾的是，当时没有人及时将所有线索串联起来。 911，也就是后来人们对这场美国袭击事件的称呼，连同其后续回应，共同塑造了本世纪前20年的外交、安全与情报政策。 2001年9月11日，当“基地组织”（al-Qaeda）的自杀式劫机者驾驶劫持的客机撞向世界贸易中心时，我刚结束在BBC中东分社的工作。当一名巴勒斯坦计程车司机载着我穿过耶路撒冷以西松林覆盖的丘陵，前往特拉维夫的本古里安机…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/world/20260911/afghanistan-war-photojournalism/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "美国在阿富汗的“永久战争”：25年影像全记录",
    "link": "https://cn.nytimes.com/world/20260911/afghanistan-war-photojournalism/dual",
    "pub_date": "2026-09-11 12:06:02",
    "author": "",
    "description": "《纽约时报》2026年9月11日 Jim Huylebroek for The New York Times America’s “forever war” in Afghanistan began only weeks after the Sept. 11 attacks and lasted just short of 20 years, ending in the chaos of Aug. 15, 2021, when the …",
    "content": "《纽约时报》 2026年9月11日 Jim Huylebroek for The New York Times America’s “forever war” in Afghanistan began only weeks after the Sept. 11 attacks and lasted just short of 20 years, ending in the chaos of Aug. 15, 2021, when the capital, Kabul, fell once again to the …"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cvgyrjx1n7yo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普真的能向每位美國成年人發放5000美元嗎？",
    "link": "https://www.bbc.com/zhongwen/articles/cvgyrjx1n7yo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-11 11:25:35",
    "author": "",
    "description": "Reuters/BBC / BBC记者萨米拉．侯赛因（Samira Hussain）解释，要让特朗普向每名美国成年人送出5,000美元成真，需要具备哪些条件（英语影片） 美国总统唐纳德．特朗普（Donald Trump）表示，如果共和党赢得11月的期中选举，每名美国成年人都将获得5,000美元（3,700英镑），但目前尚不清楚这项计划将如何筹措资金，以及是否合法。 他的言论在周三晚间的党代表大会上引发支持者热烈欢呼，但民主党则称之为“空…",
    "content": "Reuters/BBC / BBC记者萨米拉．侯赛因（Samira Hussain）解释，要让特朗普向每名美国成年人送出5,000美元成真，需要具备哪些条件（英语影片） 美国总统唐纳德．特朗普（Donald Trump）表示，如果共和党赢得11月的期中选举，每名美国成年人都将获得5,000美元（3,700英镑），但目前尚不清楚这项计划将如何筹措资金，以及是否合法。 他的言论在周三晚间的党代表大会上引发支持者热烈欢呼，但民主党则称之为“空头承诺”。 特朗普还向共和党大会表示，这笔钱必须在美国境内使用，但目前尚不清楚将…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cvgyj1x17vko/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "香港支聯會「煽動顛覆」案：李卓人、鄒幸彤、何俊仁判囚5至7年",
    "link": "https://www.bbc.com/zhongwen/articles/cvgyj1x17vko/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-11 11:12:06",
    "author": "",
    "description": "AFP via Getty Images / 李卓人（左二）、邹幸彤（中）、何俊仁（右二）为香港支联会末代领导层。 已解散的香港支联会被控违反中国《香港国安法》案件，前主席李卓人被判囚7年，前副主席邹幸彤7年3个月，前副主席何俊仁5年2个月。 支联会则被判罚款150万港元（19万美元；128万人民币；605万元新台币），限3个月内缴交。 判刑于周五（9月11日）早上进行，香港高等法院裁定被告“煽动颠覆国家”罪成。 全称“香港市民支援爱国…",
    "content": "AFP via Getty Images / 李卓人（左二）、邹幸彤（中）、何俊仁（右二）为香港支联会末代领导层。 已解散的香港支联会被控违反中国《香港国安法》案件，前主席李卓人被判囚7年，前副主席邹幸彤7年3个月，前副主席何俊仁5年2个月。 支联会则被判罚款150万港元（19万美元；128万人民币；605万元新台币），限3个月内缴交。 判刑于周五（9月11日）早上进行，香港高等法院裁定被告“煽动颠覆国家”罪成。 全称“香港市民支援爱国民主运动联合会”的支联会，一直主办1989年北京“六四”天安门学运镇压事件的悼念…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/technology/20260911/ai-humanity-risk/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "人工智能末日论：人类为何会如此担忧？",
    "link": "https://cn.nytimes.com/technology/20260911/ai-humanity-risk/dual",
    "pub_date": "2026-09-11 11:06:01",
    "author": "",
    "description": "WILLIAM J. BROAD, CADE METZ2026年9月11日从大流行病到致命小行星，再到生态崩溃，人类面临诸多灭顶之灾。人工智能超智能不过是最近一个引发人们无限想象的话题。 Andrew Harnik/Associated Press It could launch a bioweapon attack, or a global drone war. It could set off a nuclear bomb. Or …",
    "content": "WILLIAM J. BROAD, CADE METZ 2026年9月11日 从大流行病到致命小行星，再到生态崩溃，人类面临诸多灭顶之灾。人工智能超智能不过是最近一个引发人们无限想象的话题。 Andrew Harnik/Associated Press It could launch a bioweapon attack, or a global drone war. It could set off a nuclear bomb. Or it could destroy human society more gr…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/technology/20260911/anthropic-ai-biological-weapons/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "利用AI开发生物武器？Anthropic称阻止多起相关企图",
    "link": "https://cn.nytimes.com/technology/20260911/anthropic-ai-biological-weapons/dual",
    "pub_date": "2026-09-11 10:36:02",
    "author": "",
    "description": "DUSTIN VOLZ2026年9月11日Anthropic周四发布的报告列举了过去八个月其AI模型——包括聊天机器人Claude——遭到的一系列滥用情况。 Marissa Leshnov for The New York Times Anthropic said it had disrupted several potential plots this year by scientists who used its leading a…",
    "content": "DUSTIN VOLZ 2026年9月11日 Anthropic周四发布的报告列举了过去八个月其AI模型——包括聊天机器人Claude——遭到的一系列滥用情况。 Marissa Leshnov for The New York Times Anthropic said it had disrupted several potential plots this year by scientists who used its leading artificial intelligence models to condu…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/china/20260911/china-cargo-ship-fire-qingdao/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "青岛造船厂内外籍货船起火，25人遇难",
    "link": "https://cn.nytimes.com/china/20260911/china-cargo-ship-fire-qingdao/dual",
    "pub_date": "2026-09-11 09:06:02",
    "author": "",
    "description": "BERRY WANG, ALI WATKINS2026年9月11日周四，一艘货轮在中国青岛靠港时起火，消防车停靠在该货轮附近，图片由中国官方媒体发布。 Li Aoqiu/Xinhua, via Associated Press Twenty-five people were killed on Thursday after a fire broke out on a cargo ship that was docked in Qingd…",
    "content": "BERRY WANG, ALI WATKINS 2026年9月11日 周四，一艘货轮在中国青岛靠港时起火，消防车停靠在该货轮附近，图片由中国官方媒体发布。 Li Aoqiu/Xinhua, via Associated Press Twenty-five people were killed on Thursday after a fire broke out on a cargo ship that was docked in Qingdao, China, state media outlets reporte…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ckgwygp9nero/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「無時無刻都在想」：911事件25年後審訊仍未了，遇難者家屬傷痛難癒",
    "link": "https://www.bbc.com/zhongwen/articles/ckgwygp9nero/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-11 08:22:53",
    "author": "",
    "description": "Tom Resta / 约翰·雷斯塔（John Resta）与妻子西尔维亚（Sylvia）在911事件中丧生。 2001年9月11日的恐怖攻击，美国政府形容是“现代美国本土最令人发指的犯罪行为”。 但四分之一个世纪过去，被指策划这场袭击的主谋审讯仍未展开，遇难者家属担心，等待正义的时间已经所剩不多。 汤姆·雷斯塔（Tom Resta）的兄弟约翰（John）与怀孕七个月的妻子西尔维亚（Sylvia），是911事件近3,000名死者的其中两…",
    "content": "Tom Resta / 约翰·雷斯塔（John Resta）与妻子西尔维亚（Sylvia）在911事件中丧生。 2001年9月11日的恐怖攻击，美国政府形容是“现代美国本土最令人发指的犯罪行为”。 但四分之一个世纪过去，被指策划这场袭击的主谋审讯仍未展开，遇难者家属担心，等待正义的时间已经所剩不多。 汤姆·雷斯塔（Tom Resta）的兄弟约翰（John）与怀孕七个月的妻子西尔维亚（Sylvia），是911事件近3,000名死者的其中两人。 当天，劫机者驾驶民航客机撞向纽约市世界贸易中心（World Trade C…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260910-%E5%8A%A0%E6%8B%BF%E5%A4%A7%E5%AE%A3%E5%B8%83%E5%90%91%E4%B9%8C%E5%85%8B%E5%85%B0%E6%8F%90%E4%BE%9B%E8%B6%85%E8%BF%872%E4%BA%BF%E6%AC%A7%E5%85%83%E7%9A%84%E9%98%B2%E7%A9%BA%E6%8F%B4%E5%8A%A9",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "加拿大宣布向乌克兰提供超过2亿欧元的防空援助 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260910-%E5%8A%A0%E6%8B%BF%E5%A4%A7%E5%AE%A3%E5%B8%83%E5%90%91%E4%B9%8C%E5%85%8B%E5%85%B0%E6%8F%90%E4%BE%9B%E8%B6%85%E8%BF%872%E4%BA%BF%E6%AC%A7%E5%85%83%E7%9A%84%E9%98%B2%E7%A9%BA%E6%8F%B4%E5%8A%A9",
    "pub_date": "2026-09-11 05:45:03",
    "author": "",
    "description": "10/09/2026 - 23:33 乌克兰总统泽连斯基周四访问加拿大，与加拿大总理卡尼举行了会谈。当天，加拿大宣布向乌克兰提供超过2亿欧元的防空援助。双方还签署了一项“长期伙伴关系”协议，将合作生产无人机以及反无人机系统。最后，两国领导人还签署了一份声明。根据声明，加拿大和乌克兰将建立一个为期100年的安全与经济伙伴关系。 乌克兰总统泽连斯基周四访问加拿大，与加拿大总理卡尼举行了会谈。 卡尼当天宣布，加拿大将拨款3.5亿加元（约合2.…",
    "content": "10/09/2026 - 23:33 乌克兰总统泽连斯基周四访问加拿大，与加拿大总理卡尼举行了会谈。当天，加拿大宣布向乌克兰提供超过2亿欧元的防空援助。双方还签署了一项“长期伙伴关系”协议，将合作生产无人机以及反无人机系统。最后，两国领导人还签署了一份声明。根据声明，加拿大和乌克兰将建立一个为期100年的安全与经济伙伴关系。 乌克兰总统泽连斯基周四访问加拿大，与加拿大总理卡尼举行了会谈。 卡尼当天宣布，加拿大将拨款3.5亿加元（约合2.18亿欧元），向乌克兰提供防空装备。这些防空拦截弹将由加拿大通过一项美国主导的计…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260910-%E4%B9%8C%E5%85%8B%E5%85%B0%E8%B4%AD%E7%89%A9%E4%B8%AD%E5%BF%83%E9%81%AD%E8%A2%AD%E8%87%B45%E6%AD%BB67%E4%BC%A4",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "乌克兰购物中心遭俄罗斯袭击，致5死67伤 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260910-%E4%B9%8C%E5%85%8B%E5%85%B0%E8%B4%AD%E7%89%A9%E4%B8%AD%E5%BF%83%E9%81%AD%E8%A2%AD%E8%87%B45%E6%AD%BB67%E4%BC%A4",
    "pub_date": "2026-09-11 05:15:03",
    "author": "",
    "description": "10/09/2026 - 22:48 乌克兰当局表示，周四（9月10日），俄罗斯对乌克兰中东部城市帕夫洛格勒（Pavlograd）一座购物中心发动袭击，造成至少5人死亡、67人受伤，其中包括8名儿童。 乌克兰内政部长伊万·维吉夫斯基在Telegram上表示：“大约一小时前，俄罗斯人袭击了位于帕夫洛格勒市中心的一座购物中心。当时正值白天，街道上人群密集。” 乌克兰外交部长安德里·瑟比加谴责称：“这是一种胁迫战术。俄罗斯认为，对平民发动持续…",
    "content": "10/09/2026 - 22:48 乌克兰当局表示，周四（9月10日），俄罗斯对乌克兰中东部城市帕夫洛格勒（Pavlograd）一座购物中心发动袭击，造成至少5人死亡、67人受伤，其中包括8名儿童。 乌克兰内政部长伊万·维吉夫斯基在Telegram上表示：“大约一小时前，俄罗斯人袭击了位于帕夫洛格勒市中心的一座购物中心。当时正值白天，街道上人群密集。” 乌克兰外交部长安德里·瑟比加谴责称：“这是一种胁迫战术。俄罗斯认为，对平民发动持续不断的袭击，可以让乌克兰人筋疲力尽，并迫使乌克兰作出让步。” 在俄罗斯方面，救援…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260910-%E5%91%A8%E5%9B%9B%E6%B2%B9%E4%BB%B7%E6%9A%B4%E6%B6%A8%E8%B6%856-%EF%BC%8C%E5%88%9B%E8%BF%91%E4%B8%A4%E6%9C%88%E6%9D%A5%E6%9C%80%E5%A4%A7%E5%8D%95%E6%97%A5%E6%B6%A8%E5%B9%85%EF%BC%8C%E5%88%86%E6%9E%90%E7%A7%B0%E6%B2%B9%E4%BB%B7%E4%B8%8A%E6%B6%A8%E8%83%BD%E5%90%A6%E6%8C%81%E7%BB%AD%E6%88%96%E5%8F%96%E5%86%B3%E4%BA%8E%E4%B8%AD%E5%9B%BD",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "周四油价暴涨超6%，创近两月来最大单日涨幅，分析称油价上涨能否持续或取决于中国 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260910-%E5%91%A8%E5%9B%9B%E6%B2%B9%E4%BB%B7%E6%9A%B4%E6%B6%A8%E8%B6%856-%EF%BC%8C%E5%88%9B%E8%BF%91%E4%B8%A4%E6%9C%88%E6%9D%A5%E6%9C%80%E5%A4%A7%E5%8D%95%E6%97%A5%E6%B6%A8%E5%B9%85%EF%BC%8C%E5%88%86%E6%9E%90%E7%A7%B0%E6%B2%B9%E4%BB%B7%E4%B8%8A%E6%B6%A8%E8%83%BD%E5%90%A6%E6%8C%81%E7%BB%AD%E6%88%96%E5%8F%96%E5%86%B3%E4%BA%8E%E4%B8%AD%E5%9B%BD",
    "pub_date": "2026-09-11 04:45:03",
    "author": "",
    "description": "10/09/2026 - 22:13 路透社消息称，周四（9月10日），油价大幅上涨超过6%。布伦特原油和美国原油两大基准价格均突破每桶100美元。 据悉，布伦特原油期货收涨6.42美元，涨幅6.34%，报每桶107.63美元。美国原油价格则自5月以来首次突破每桶100美元。西得克萨斯中质原油（WTI）期货上涨6.43美元，涨幅6.69%，报每桶102.48美元。 两大基准油价均创下5月19日以来最高水平，同时录得近两个月来的最大单日涨…",
    "content": "10/09/2026 - 22:13 路透社消息称，周四（9月10日），油价大幅上涨超过6%。布伦特原油和美国原油两大基准价格均突破每桶100美元。 据悉，布伦特原油期货收涨6.42美元，涨幅6.34%，报每桶107.63美元。美国原油价格则自5月以来首次突破每桶100美元。西得克萨斯中质原油（WTI）期货上涨6.43美元，涨幅6.69%，报每桶102.48美元。 两大基准油价均创下5月19日以来最高水平，同时录得近两个月来的最大单日涨幅。 周四，与伊朗结盟的胡塞武装控制了也门的摩卡港（Mocha），进一步威胁红海…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260910-%E7%BE%8E%E5%9B%BD%E6%89%93%E5%87%BB%E4%B9%8B%E5%90%8E%EF%BC%8C%E9%9C%8D%E5%B0%94%E6%9C%A8%E5%85%B9%E6%B5%B7%E5%B3%A1%E9%99%84%E8%BF%91%E6%B5%B7%E5%9F%9F%E7%96%91%E4%BC%BC%E5%87%BA%E7%8E%B0%E4%BA%86%E6%B5%AE%E6%B2%B9%E5%B8%A6",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "美国打击之后，霍尔木兹海峡附近海域疑似出现了浮油带 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260910-%E7%BE%8E%E5%9B%BD%E6%89%93%E5%87%BB%E4%B9%8B%E5%90%8E%EF%BC%8C%E9%9C%8D%E5%B0%94%E6%9C%A8%E5%85%B9%E6%B5%B7%E5%B3%A1%E9%99%84%E8%BF%91%E6%B5%B7%E5%9F%9F%E7%96%91%E4%BC%BC%E5%87%BA%E7%8E%B0%E4%BA%86%E6%B5%AE%E6%B2%B9%E5%B8%A6",
    "pub_date": "2026-09-11 04:45:02",
    "author": "",
    "description": "10/09/2026 - 22:19 法新社报道，欧洲“哥白尼”计划周三拍摄的一张图像显示，在海峡以东、距伊朗海岸约20公里的水面上，出现了褐色的条带状痕迹。其中两条被探测到的轨迹，它的起点恰好位于油轮 Riesco 和 Kylo 发出最后信号的位置；这两艘油轮分别于 9 月 8 日和 5 日被击沉。 “哥白尼”计划周四在同一地点拍摄的另一张图像也显示了长度相当的蜿蜒条带。 美军宣布，为回应伊朗革命卫队针对一艘美国军舰发动的弹道导弹袭击…",
    "content": "10/09/2026 - 22:19 法新社报道，欧洲“哥白尼”计划周三拍摄的一张图像显示，在海峡以东、距伊朗海岸约20公里的水面上，出现了褐色的条带状痕迹。其中两条被探测到的轨迹，它的起点恰好位于油轮 Riesco 和 Kylo 发出最后信号的位置；这两艘油轮分别于 9 月 8 日和 5 日被击沉。 “哥白尼”计划周四在同一地点拍摄的另一张图像也显示了长度相当的蜿蜒条带。 美军宣布，为回应伊朗革命卫队针对一艘美国军舰发动的弹道导弹袭击，美军于周二在阿曼湾摧毁了五艘油轮。 根据美军在 X 平台上发布的图像，长 24…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E7%BB%8F%E8%B4%B8/20260910-%E4%BA%AC%E4%B8%9C%E6%94%B6%E8%B4%AD%E5%BE%B7%E5%9B%BD%E7%94%B5%E5%AD%90%E9%9B%B6%E5%94%AE%E5%B7%A8%E5%A4%B4%E9%81%87%E9%98%BB%EF%BC%8C%E9%81%AD%E6%AC%A7%E7%9B%9F%E5%AE%A1%E6%9F%A5%E4%B8%8E%E7%AB%9E%E4%BA%89%E5%AF%B9%E6%89%8B%E5%8F%8C%E9%87%8D%E6%96%BD%E5%8E%8B",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "京东收购德国电子零售巨头遇阻，遭欧盟审查与竞争对手双重施压 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E7%BB%8F%E8%B4%B8/20260910-%E4%BA%AC%E4%B8%9C%E6%94%B6%E8%B4%AD%E5%BE%B7%E5%9B%BD%E7%94%B5%E5%AD%90%E9%9B%B6%E5%94%AE%E5%B7%A8%E5%A4%B4%E9%81%87%E9%98%BB%EF%BC%8C%E9%81%AD%E6%AC%A7%E7%9B%9F%E5%AE%A1%E6%9F%A5%E4%B8%8E%E7%AB%9E%E4%BA%89%E5%AF%B9%E6%89%8B%E5%8F%8C%E9%87%8D%E6%96%BD%E5%8E%8B",
    "pub_date": "2026-09-11 04:15:03",
    "author": "",
    "description": "10/09/2026 - 21:42 路透社周四（9月10日）报导称，知情人士向路透社透露，京东为缓解欧盟对其以25亿美元收购德国电子产品零售商Ceconomy所涉及的外国补贴问题而提出的让步方案，已经引发竞争对手的批评。知情人士表示，作为欧盟竞争监管机构的欧盟委员会本周早些时候已将竞争对手针对京东上月提出的让步方案所提交的反馈意见告知京东。 欧盟委员会将于10月23日前就是否批准这项交易作出决定。这些负面意见可能给京东带来更大压力，迫…",
    "content": "10/09/2026 - 21:42 路透社周四（9月10日）报导称，知情人士向路透社透露，京东为缓解欧盟对其以25亿美元收购德国电子产品零售商Ceconomy所涉及的外国补贴问题而提出的让步方案，已经引发竞争对手的批评。知情人士表示，作为欧盟竞争监管机构的欧盟委员会本周早些时候已将竞争对手针对京东上月提出的让步方案所提交的反馈意见告知京东。 欧盟委员会将于10月23日前就是否批准这项交易作出决定。这些负面意见可能给京东带来更大压力，迫使其进一步改善让步方案。 其中一名知情人士透露，根据京东提出的方案，Cecono…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260910-%E9%98%BF%E8%81%94%E9%85%8B%E5%B0%86%E5%90%91%E5%BE%B7%E5%9B%BD%E6%8A%95%E8%B5%84400%E4%BA%BF%E6%AC%A7%E5%85%83%EF%BC%8C%E9%87%8D%E7%82%B9%E7%94%A8%E4%BA%8E%E5%BB%BA%E8%AE%BE%E5%B0%96%E7%AB%AF%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "阿联酋将向德国投资400亿欧元，重点用于建设尖端数据中心 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260910-%E9%98%BF%E8%81%94%E9%85%8B%E5%B0%86%E5%90%91%E5%BE%B7%E5%9B%BD%E6%8A%95%E8%B5%84400%E4%BA%BF%E6%AC%A7%E5%85%83%EF%BC%8C%E9%87%8D%E7%82%B9%E7%94%A8%E4%BA%8E%E5%BB%BA%E8%AE%BE%E5%B0%96%E7%AB%AF%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83",
    "pub_date": "2026-09-11 03:45:03",
    "author": "",
    "description": "10/09/2026 - 20:01 周四（9月10日），阿联酋总统对德国进行访问期间，两国宣布，阿联酋将向德国一系列项目总计投资400亿欧元，其中包括用于建设和发展新数据中心的项目。据悉，这是阿联酋国家元首首次访问德国。 根据柏林方面周四公布的一份联合声明，该计划包括“对先进数字基础设施进行投资，其中包括开发新一代尖端数据中心，其总容量约为1吉瓦”。两国领导人还宣布成立一个双边“投资委员会”。该委员会将“作为一个旨在促进投资、加强公共…",
    "content": "10/09/2026 - 20:01 周四（9月10日），阿联酋总统对德国进行访问期间，两国宣布，阿联酋将向德国一系列项目总计投资400亿欧元，其中包括用于建设和发展新数据中心的项目。据悉，这是阿联酋国家元首首次访问德国。 根据柏林方面周四公布的一份联合声明，该计划包括“对先进数字基础设施进行投资，其中包括开发新一代尖端数据中心，其总容量约为1吉瓦”。两国领导人还宣布成立一个双边“投资委员会”。该委员会将“作为一个旨在促进投资、加强公共和私营部门之间交流的平台”。此外，两国领导人还共同见证了两国企业签署的29份谅解…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E7%A4%BE%E4%BC%9A/20260910-%E6%B3%95%E5%9B%BD%E5%8C%97%E9%83%A8%E6%95%A6%E5%88%BB%E5%B0%94%E5%85%8B%E6%B8%AF%E6%9F%A5%E8%8E%B7%E8%BF%914%E5%90%A8%E5%8F%AF%E5%8D%A1%E5%9B%A0%EF%BC%8C%E4%BB%B7%E5%80%BC%E7%BA%A62-25%E4%BA%BF%E6%AC%A7%E5%85%83",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "法国北部敦刻尔克港查获近4吨可卡因，价值约2.25亿欧元 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E7%A4%BE%E4%BC%9A/20260910-%E6%B3%95%E5%9B%BD%E5%8C%97%E9%83%A8%E6%95%A6%E5%88%BB%E5%B0%94%E5%85%8B%E6%B8%AF%E6%9F%A5%E8%8E%B7%E8%BF%914%E5%90%A8%E5%8F%AF%E5%8D%A1%E5%9B%A0%EF%BC%8C%E4%BB%B7%E5%80%BC%E7%BA%A62-25%E4%BA%BF%E6%AC%A7%E5%85%83",
    "pub_date": "2026-09-11 03:15:03",
    "author": "",
    "description": "10/09/2026 - 21:11 法新社消息称，法国北部敦刻尔克港本周查获约3.9吨可卡因，估值接近2.25亿欧元。这批毒品于周一被发现，但直到周四（9月10日）才由法国国家有组织犯罪检察机关（Pnaco）对外公布。 法国海关敦刻尔克港外部监控大队的工作人员在一个集装箱内发现了这批毒品，共有167包可卡因，藏匿于“塑料废弃物”之中。负责案件的检察官在一份声明中表示，这个集装箱来自加纳，原本“主要计划运往安特卫普港”。 法国国家有组织…",
    "content": "10/09/2026 - 21:11 法新社消息称，法国北部敦刻尔克港本周查获约3.9吨可卡因，估值接近2.25亿欧元。这批毒品于周一被发现，但直到周四（9月10日）才由法国国家有组织犯罪检察机关（Pnaco）对外公布。 法国海关敦刻尔克港外部监控大队的工作人员在一个集装箱内发现了这批毒品，共有167包可卡因，藏匿于“塑料废弃物”之中。负责案件的检察官在一份声明中表示，这个集装箱来自加纳，原本“主要计划运往安特卫普港”。 法国国家有组织犯罪检察机关指出，2025年，法国海关在全国范围内共查获108.81吨各类毒品，…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260910-%E7%89%B9%E6%9C%97%E6%99%AE%E6%89%BF%E8%AF%BA%E8%8B%A5%E4%B8%AD%E6%9C%9F%E9%80%89%E4%B8%BE%E8%8E%B7%E8%83%9C%E6%AF%8F%E4%BA%BA%E5%8F%915000%E7%BE%8E%E5%85%83%EF%BC%8C%E6%80%BB%E8%AE%A1%E8%B6%851-3%E4%B8%87%E4%BA%BF%E7%BE%8E%E5%85%83%EF%BC%8C%E9%92%B1%E4%BB%8E%E5%93%AA%E5%84%BF%E6%9D%A5",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "特朗普承诺若中期选举获胜每人发5000美元，总计超1.3万亿美元，钱从哪儿来？ - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260910-%E7%89%B9%E6%9C%97%E6%99%AE%E6%89%BF%E8%AF%BA%E8%8B%A5%E4%B8%AD%E6%9C%9F%E9%80%89%E4%B8%BE%E8%8E%B7%E8%83%9C%E6%AF%8F%E4%BA%BA%E5%8F%915000%E7%BE%8E%E5%85%83%EF%BC%8C%E6%80%BB%E8%AE%A1%E8%B6%851-3%E4%B8%87%E4%BA%BF%E7%BE%8E%E5%85%83%EF%BC%8C%E9%92%B1%E4%BB%8E%E5%93%AA%E5%84%BF%E6%9D%A5",
    "pub_date": "2026-09-11 03:15:03",
    "author": "",
    "description": "10/09/2026 - 21:02 美国总统特朗普周三（9月9日）承诺，如果共和党赢得11月举行的国会选举，他将向每一名美国成年人发放5000美元的“特朗普红利”。除了提到将使用关税收入之外，特朗普并未说明这项承诺将通过何种方式筹集资金。这一方案能否实施以及是否合法，目前都引发了诸多疑问。法新社对此作出了详细的解读。 在这次选举季，共和党人寄希望于总统特朗普以及他在达拉斯举行的为期两天的大型活动，来动员选民，帮助共和党守住在众议院和参…",
    "content": "10/09/2026 - 21:02 美国总统特朗普周三（9月9日）承诺，如果共和党赢得11月举行的国会选举，他将向每一名美国成年人发放5000美元的“特朗普红利”。除了提到将使用关税收入之外，特朗普并未说明这项承诺将通过何种方式筹集资金。这一方案能否实施以及是否合法，目前都引发了诸多疑问。法新社对此作出了详细的解读。 在这次选举季，共和党人寄希望于总统特朗普以及他在达拉斯举行的为期两天的大型活动，来动员选民，帮助共和党守住在众议院和参议院的多数席位。 大会首晚，共和党人纷纷指责民主党人是极端分子。随后，特朗普在周…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%BA%9A%E6%B4%B2/20260910-rfi%E6%B3%95%E5%B9%BF-%E4%B8%AD%E6%96%87-%E5%B0%BC%E5%8F%A4%E6%8B%89-%E9%9F%A9%E5%9B%BD%E4%B8%8E%E9%9D%9E%E6%B4%B22026%E7%BB%8F%E5%90%88%E9%83%A8%E9%95%BF%E7%BA%A7%E4%BC%9A%E8%AE%AE",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "韩国与非洲2026经合部长级会议 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%BA%9A%E6%B4%B2/20260910-rfi%E6%B3%95%E5%B9%BF-%E4%B8%AD%E6%96%87-%E5%B0%BC%E5%8F%A4%E6%8B%89-%E9%9F%A9%E5%9B%BD%E4%B8%8E%E9%9D%9E%E6%B4%B22026%E7%BB%8F%E5%90%88%E9%83%A8%E9%95%BF%E7%BA%A7%E4%BC%9A%E8%AE%AE",
    "pub_date": "2026-09-11 02:45:04",
    "author": "",
    "description": "10/09/2026 - 20:19 韩国（2026年）与非洲大陆第八届经合部长会议（KOAFEC）预计将于2026年09月11日周五落幕。非洲大陆所有54个国家都派出了代表团前往首尔。韩国女总理韩圣淑（Mme Han Seongsook）承诺，作为全球高科技的冠军之一，韩国愿把其在此领域的技能传授给非洲大陆。 据本台法广非洲组（RFI Afrique）的法文报道，由韩国（la Corée du Sud）组办的2026年第八届非洲大陆经…",
    "content": "10/09/2026 - 20:19 韩国（2026年）与非洲大陆第八届经合部长会议（KOAFEC）预计将于2026年09月11日周五落幕。非洲大陆所有54个国家都派出了代表团前往首尔。韩国女总理韩圣淑（Mme Han Seongsook）承诺，作为全球高科技的冠军之一，韩国愿把其在此领域的技能传授给非洲大陆。 据本台法广 非洲 组（RFI Afrique）的法文报道，由韩国（la Corée du Sud）组办的2026年第八届 非洲 大陆经济合作部长级会议（ KOAFEC ）吸引到全非洲所有54个国家派出代表团…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260910-%E6%8A%A5%E5%91%8A-%E7%BE%8E%E5%9B%BD%E4%BC%81%E4%B8%9A%E5%AF%B9%E4%B8%AD%E5%9B%BD%E5%B8%82%E5%9C%BA%E4%BF%A1%E5%BF%83%E5%9B%9E%E5%8D%87",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "报告：美国企业对中国市场信心回升 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260910-%E6%8A%A5%E5%91%8A-%E7%BE%8E%E5%9B%BD%E4%BC%81%E4%B8%9A%E5%AF%B9%E4%B8%AD%E5%9B%BD%E5%B8%82%E5%9C%BA%E4%BF%A1%E5%BF%83%E5%9B%9E%E5%8D%87",
    "pub_date": "2026-09-11 02:45:04",
    "author": "",
    "description": "10/09/2026 - 20:17 调查显示，去年仅41%企业对未来5年中国业务前景感到乐观，创下历史低点，今年则回升至58%。持悲观或略为悲观态度的企业比例也由去年的37%降至16%。 上海美国商会主席杰弗里·雷曼（Jeffrey Lehman）说：“我们的会员明显注意到情绪正在转变。” 雷曼表示，去年的调查是在新一轮贸易紧张升高期间进行，今年调查则是在美国总统特朗普（Donald Trump）与中国国家主席习近平今年5月在北京会面…",
    "content": "10/09/2026 - 20:17 调查显示，去年仅41%企业对未来5年中国业务前景感到乐观，创下历史低点，今年则回升至58%。持悲观或略为悲观态度的企业比例也由去年的37%降至16%。 上海美国商会主席杰弗里·雷曼（Jeffrey Lehman）说：“我们的会员明显注意到情绪正在转变。” 雷曼表示，去年的调查是在新一轮贸易紧张升高期间进行，今年调查则是在美国总统特朗普（Donald Trump）与中国国家主席习近平今年5月在北京会面后进行。他说，两国领导人同意朝着“以公平和互惠为基础、具有战略稳定性的建设性关系…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260910-%E9%9F%A9%E5%9B%BD%E6%83%85%E6%8A%A5%E9%83%A8%E9%97%A8-%E9%87%91%E6%AD%A3%E6%81%A9%E7%9A%84%E5%A5%B3%E5%84%BF%E9%87%91%E4%B8%BB%E7%88%B1%E5%8F%AF%E8%83%BD%E8%BF%98%E6%9C%89%E4%B8%80%E4%B8%AA%E5%BC%9F%E5%BC%9F%E6%88%96%E5%A6%B9%E5%A6%B9",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "韩国情报部门：金正恩的女儿金主爱可能还有一个弟弟或妹妹 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260910-%E9%9F%A9%E5%9B%BD%E6%83%85%E6%8A%A5%E9%83%A8%E9%97%A8-%E9%87%91%E6%AD%A3%E6%81%A9%E7%9A%84%E5%A5%B3%E5%84%BF%E9%87%91%E4%B8%BB%E7%88%B1%E5%8F%AF%E8%83%BD%E8%BF%98%E6%9C%89%E4%B8%80%E4%B8%AA%E5%BC%9F%E5%BC%9F%E6%88%96%E5%A6%B9%E5%A6%B9",
    "pub_date": "2026-09-11 02:15:03",
    "author": "",
    "description": "10/09/2026 - 19:46 据法新社消息，韩国情报部门周四（9月10日）表示，朝鲜最高领导人金正恩的女儿金主爱（Kim Ju Ae）被认为可能是潜在的接班人，而她似乎还有一名年龄更小的弟弟或妹妹。 韩国国家情报院（NIS）在一份声明中表示：“国家情报院目前认为，金主爱正以继承人的身份受到对待，并了解到她还有一名更年幼的兄弟或姐妹。” 韩国国家情报院此前曾判断，金正恩很可能有三个孩子，但他们出生的先后顺序一直无法确定。 金正恩本…",
    "content": "10/09/2026 - 19:46 据法新社消息，韩国情报部门周四（9月10日）表示，朝鲜最高领导人金正恩的女儿金主爱（Kim Ju Ae）被认为可能是潜在的接班人，而她似乎还有一名年龄更小的弟弟或妹妹。 韩国国家情报院（NIS）在一份声明中表示：“国家情报院目前认为，金主爱正以继承人的身份受到对待，并了解到她还有一名更年幼的兄弟或姐妹。” 韩国国家情报院此前曾判断，金正恩很可能有三个孩子，但他们出生的先后顺序一直无法确定。 金正恩本人一直对自己的子女情况保持神秘。2011年，他接替父亲金正日成为朝鲜最高领导人，…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%BA%9A%E6%B4%B2/20260910-%E4%B8%AD%E6%96%B9%E6%8D%AE%E6%8A%A5%E6%84%BF%E5%8D%8F%E5%8A%A9%E4%BF%83%E6%88%90%E7%89%B9%E9%87%91%E5%86%8D%E4%BC%9A-%E5%8C%97%E4%BA%AC%E6%AD%A3%E7%9D%80%E6%89%8B%E5%8F%91%E6%8C%A5-%E7%A7%AF%E6%9E%81-%E5%BB%BA%E8%AE%BE%E6%80%A7-%E4%BD%9C%E7%94%A8",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "中方据报愿协助促成特金再会 北京正着手发挥“积极、建设性”作用 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%BA%9A%E6%B4%B2/20260910-%E4%B8%AD%E6%96%B9%E6%8D%AE%E6%8A%A5%E6%84%BF%E5%8D%8F%E5%8A%A9%E4%BF%83%E6%88%90%E7%89%B9%E9%87%91%E5%86%8D%E4%BC%9A-%E5%8C%97%E4%BA%AC%E6%AD%A3%E7%9D%80%E6%89%8B%E5%8F%91%E6%8C%A5-%E7%A7%AF%E6%9E%81-%E5%BB%BA%E8%AE%BE%E6%80%A7-%E4%BD%9C%E7%94%A8",
    "pub_date": "2026-09-11 00:15:03",
    "author": "",
    "description": "10/09/2026 - 17:38 据《南华早报》援引消息人士报导称，中国愿意协助促成美国总统特朗普与朝鲜最高领导人金正恩之间可能举行的会晤；而就在几周后，中国国家主席习近平预计将前往华盛顿参加美中峰会。 多位知情人士向该报表示，随着特朗普寻求重启与平壤方面的接触，北京正着手发挥“积极”且“建设性”的作用，以推动美朝外交接触的恢复；此举凸显了中方决心在朝鲜半岛问题谈判中继续保持核心参与者的地位。 两位消息人士称，北京将支持所有有助于重…",
    "content": "10/09/2026 - 17:38 据《南华早报》援引消息人士报导称，中国愿意协助促成美国总统特朗普与朝鲜最高领导人金正恩之间可能举行的会晤；而就在几周后，中国国家主席习近平预计将前往华盛顿参加美中峰会。 多位知情人士向该报表示，随着特朗普寻求重启与平壤方面的接触，北京正着手发挥“积极”且“建设性”的作用，以推动美朝外交接触的恢复；此举凸显了中方决心在朝鲜半岛问题谈判中继续保持核心参与者的地位。 两位消息人士称，北京将支持所有有助于重启对话的可信努力。但他们认为，鉴于金正恩与俄罗斯——这为平壤提供了更大的外交和军…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E7%A4%BE%E4%BC%9A/20260910-%E7%89%B9%E6%9C%97%E6%99%AE%E6%94%BF%E5%BA%9C%E6%8F%90%E8%AE%AE%E5%8F%96%E6%B6%88h-1b%E6%8C%81%E6%9C%89%E8%80%85%E5%A4%B1%E4%B8%9A%E5%90%8E%E7%9A%8460%E5%A4%A9%E5%AE%BD%E9%99%90%E6%9C%9F",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "特朗普政府提案取消H-1B签证持有者失业后的60天宽限期 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E7%A4%BE%E4%BC%9A/20260910-%E7%89%B9%E6%9C%97%E6%99%AE%E6%94%BF%E5%BA%9C%E6%8F%90%E8%AE%AE%E5%8F%96%E6%B6%88h-1b%E6%8C%81%E6%9C%89%E8%80%85%E5%A4%B1%E4%B8%9A%E5%90%8E%E7%9A%8460%E5%A4%A9%E5%AE%BD%E9%99%90%E6%9C%9F",
    "pub_date": "2026-09-11 00:15:03",
    "author": "",
    "description": "10/09/2026 - 17:57 根据周四在线发布的一份政府公告，特朗普政府提议取消一项为期60天的宽限期；该宽限期允许包括持有H-1B签证的熟练工人在内的特定移民在失业后继续留美并寻找新的担保雇主。 根据美国国土安全部在《联邦公报》上公布的这项拟议规则变更，持有H-1B及其他特定临时工作签证的人员一旦雇佣关系终止，必须立即离境——这对严重依赖外籍员工的美国顶尖科技公司来说，或会构成沉重打击。 这是美国总统特朗普（Donald Tr…",
    "content": "10/09/2026 - 17:57 根据周四在线发布的一份政府公告，特朗普政府提议取消一项为期60天的宽限期；该宽限期允许包括持有H-1B签证的熟练工人在内的特定移民在失业后继续留美并寻找新的担保雇主。 根据美国国土安全部在《联邦公报》上公布的这项拟议规则变更，持有H-1B及其他特定临时工作签证的人员一旦雇佣关系终止，必须立即离境——这对严重依赖外籍员工的美国顶尖科技公司来说，或会构成沉重打击。 这是美国总统特朗普（Donald Trump）自2025年1月重返白宫以来，为限制合法移民而采取的最新举措。特朗普政府…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E4%B8%9C/20260910-%E5%9B%BD%E9%99%85%E5%8E%9F%E5%AD%90%E8%83%BD%E6%9C%BA%E6%9E%84%E6%80%BB%E5%B9%B2%E4%BA%8B-%E4%BC%8A%E6%9C%97%E9%95%90%E5%B1%B1%E5%AD%98%E5%9C%A8%E6%96%BD%E5%B7%A5%E6%B4%BB%E5%8A%A8-%E7%89%B9%E6%9C%97%E6%99%AE-%E6%88%91%E4%BB%AC%E6%B3%A8%E6%84%8F%E5%88%B0%E9%82%A3%E8%BE%B9%E6%9C%89%E5%8A%A8%E9%9D%99",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "国际原子能机构总干事：伊朗镐山存在施工活动 特朗普：我们注意到那边有动静 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E4%B8%9C/20260910-%E5%9B%BD%E9%99%85%E5%8E%9F%E5%AD%90%E8%83%BD%E6%9C%BA%E6%9E%84%E6%80%BB%E5%B9%B2%E4%BA%8B-%E4%BC%8A%E6%9C%97%E9%95%90%E5%B1%B1%E5%AD%98%E5%9C%A8%E6%96%BD%E5%B7%A5%E6%B4%BB%E5%8A%A8-%E7%89%B9%E6%9C%97%E6%99%AE-%E6%88%91%E4%BB%AC%E6%B3%A8%E6%84%8F%E5%88%B0%E9%82%A3%E8%BE%B9%E6%9C%89%E5%8A%A8%E9%9D%99",
    "pub_date": "2026-09-10 23:15:02",
    "author": "",
    "description": "10/09/2026 - 17:01 国际原子能机构向彭博社表示，该机构监测到伊朗镐山（Pickaxe Mountain）存在施工活动。这处被称为镐山的设施位于德黑兰以南约225公里处的纳坦兹核设施附近，长期以来一直是情报机构关注的焦点；这些机构认为，该地点很可能是伊朗政权为保护其未来核计划相关活动而选定的场所。 国际原子能机构总干事格罗西（Rafael Grossi）表示：“有一些迹象显示该施工现场周边有活动，但对于现场具体正在进行的…",
    "content": "10/09/2026 - 17:01 国际原子能机构向彭博社表示，该机构监测到伊朗镐山（Pickaxe Mountain）存在施工活动。这处被称为镐山的设施位于德黑兰以南约225公里处的纳坦兹核设施附近，长期以来一直是情报机构关注的焦点；这些机构认为，该地点很可能是伊朗政权为保护其未来核计划相关活动而选定的场所。 国际原子能机构总干事格罗西（Rafael Grossi）表示：“有一些迹象显示该施工现场周边有活动，但对于现场具体正在进行的活动，我们尚无确切信息”。 格罗西表示，其领导的这家联合国核监督机构尚未派遣视察…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/czjzvdxw8gvo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "青島北海造船廠外籍貨輪大火 失聯25人已確定全部死亡",
    "link": "https://www.bbc.com/zhongwen/articles/czjzvdxw8gvo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-10 20:47:54",
    "author": "",
    "description": "Xinhua / 官方媒体称事发时有42人在货轮上。 中国官方媒体报导，9月10日上午11时15分（格林尼治标准时间03:15），一外籍货船在中国船舶集团青岛北海造船有限公司检修过程中起火。 船上共有42人，其中，12人安全撤出；5人受伤送医，目前生命体徵平稳；25人失联。 据央视新闻消息，截至当日晚19时24分，25名失联人员全部找到，均无生命体徵。 官媒报导称，中国国家主席习近平与总理李强分别下达了救灾指示。 习近平称，要抓紧搜救失…",
    "content": "Xinhua / 官方媒体称事发时有42人在货轮上。 中国官方媒体报导，9月10日上午11时15分（格林尼治标准时间03:15），一外籍货船在中国船舶集团青岛北海造船有限公司检修过程中起火。 船上共有42人，其中，12人安全撤出；5人受伤送医，目前生命体徵平稳；25人失联。 据央视新闻消息，截至当日晚19时24分，25名失联人员全部找到，均无生命体徵。 官媒报导称，中国国家主席习近平与总理李强分别下达了救灾指示。 习近平称，要抓紧搜救失联人员，妥善做好善后安抚等工作，并尽快查明事故原因，依法严肃追究责任。 据报导，…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ckgxyvrel0ko/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "香港記協主席訴《華爾街日報》解僱案 法庭判局部有罪",
    "link": "https://www.bbc.com/zhongwen/articles/ckgxyvrel0ko/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-10 18:46:03",
    "author": "",
    "description": "Reuters / 郑嘉如（左）2024年首次当选香港记协主席。 香港记者协会主席郑嘉如（Selina Cheng）指控美国《华尔街日报》（Wall Street Journal）出版商道琼斯（Dow Jones），因其参与工会活动，而将其革职。香港一所法院裁定资方局部有罪。 原本专门报导中国电动车行业的郑嘉如2024年当选记协主席后，于同年7月被《华尔街日报》解雇，郑嘉如就此提起私人刑事检控，资方否认全部控罪。控方在庭上指控资方主管曾…",
    "content": "Reuters / 郑嘉如（左）2024年首次当选香港记协主席。 香港记者协会主席郑嘉如（Selina Cheng）指控美国《华尔街日报》（Wall Street Journal）出版商道琼斯（Dow Jones），因其参与工会活动，而将其革职。香港一所法院裁定资方局部有罪。 原本专门报导中国电动车行业的郑嘉如2024年当选记协主席后，于同年7月被《华尔街日报》解雇，郑嘉如就此提起私人刑事检控，资方否认全部控罪。控方在庭上指控资方主管曾要求郑嘉如退选记协，辩方则称郑嘉如是被裁员。 中国香港特区东区裁判法院星期四（9…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/czezw30076zo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "為甚麼Gen Z的測試成績正在下跌？",
    "link": "https://www.bbc.com/zhongwen/articles/czezw30076zo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-10 16:58:11",
    "author": "",
    "description": "为甚么Gen Z的测试成绩正在下跌？ 一整代人真的会变得越来越不聪明吗？ 在全球最大的15岁青少年国际测试中，阅读、数学和科学成绩都正在下跌。这一下跌趋势大约始于2012年，而且似乎正在加速，尤其是阅读能力。本影片探讨导致这一下跌的各种可能原因。",
    "content": "为甚么Gen Z的测试成绩正在下跌？ 一整代人真的会变得越来越不聪明吗？ 在全球最大的15岁青少年国际测试中，阅读、数学和科学成绩都正在下跌。这一下跌趋势大约始于2012年，而且似乎正在加速，尤其是阅读能力。本影片探讨导致这一下跌的各种可能原因。"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/usa/20260910/trump-canada-tariffs/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "特朗普引发“新仇”，但美国加拿大早有“旧怨”",
    "link": "https://cn.nytimes.com/usa/20260910/trump-canada-tariffs/dual",
    "pub_date": "2026-09-10 14:06:02",
    "author": "",
    "description": "MICHAEL CROWLEY2026年9月10日1961年5月17日，约翰·肯尼迪总统在渥太华向加拿大议会联席会议发表讲话。 Associated Press The invasion of Canada was to be swift and overwhelming. 对加拿大的入侵本应迅速而且势如破竹。 U.S. forces would take the port city of Halifax before seizing …",
    "content": "MICHAEL CROWLEY 2026年9月10日 1961年5月17日，约翰·肯尼迪总统在渥太华向加拿大议会联席会议发表讲话。 Associated Press The invasion of Canada was to be swift and overwhelming. 对加拿大的入侵本应迅速而且势如破竹。 U.S. forces would take the port city of Halifax before seizing power plants near Niagara Falls. More …"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/usa/20260910/trump-social-media-ai-reality/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "10小时60条社交媒体动态：特朗普的“现实”世界",
    "link": "https://cn.nytimes.com/usa/20260910/trump-social-media-ai-reality/dual",
    "pub_date": "2026-09-10 13:06:02",
    "author": "",
    "description": "PETER BAKER2026年9月10日7月4日美国国庆日活动期间，特朗普在使用手机。发布数十条关于自己和对手的表情包及AI生成图像已成为他第二个任期的标志性特征。 Al Drago for The New York Times Just before noon on a holiday weekend, while many Americans were at the beach, President Trump’s social …",
    "content": "PETER BAKER 2026年9月10日 7月4日美国国庆日活动期间，特朗普在使用手机。发布数十条关于自己和对手的表情包及AI生成图像已成为他第二个任期的标志性特征。 Al Drago for The New York Times Just before noon on a holiday weekend, while many Americans were at the beach, President Trump’s social media account roared to life. In what …"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/technology/20260910/anthropic-researchers-raise-alarm/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "AI可能消灭人类？Anthropic研究人员警告行业发展过速",
    "link": "https://cn.nytimes.com/technology/20260910/anthropic-researchers-raise-alarm/dual",
    "pub_date": "2026-09-10 11:06:02",
    "author": "",
    "description": "KATE CONGER2026年9月10日Anthropic旧金山办公室外的抗议活动。 Lucas Foglia for The New York Times For years, the artificial intelligence industry raced to improve its technology as quickly as possible. Now some researchers are increasingl…",
    "content": "KATE CONGER 2026年9月10日 Anthropic旧金山办公室外的抗议活动。 Lucas Foglia for The New York Times For years, the artificial intelligence industry raced to improve its technology as quickly as possible. Now some researchers are increasingly sounding the alarm about the need to…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ced7g3qpyyjo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "911事件25週年：震驚世界的襲擊如何發生，造成多少人死亡？",
    "link": "https://www.bbc.com/zhongwen/articles/ced7g3qpyyjo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-10 08:14:46",
    "author": "",
    "description": "Getty Images / 2001年9月11日袭击发生后不久，浓烟从纽约世界贸易中心双子塔升起。 美国将于9月11日（星期四）举行一系列活动，纪念九一一袭击25周年。 2001年9月11日，自杀式袭击者劫持美国客机，撞向纽约两座摩天大楼，造成数千人死亡。 这场事件对全球产生了深远影响。 哪些建筑物成为袭击目标？ 四架飞越美国东部的飞机同时遭到小规模劫机团队劫持。 其后，这些飞机被当成巨型导引导弹，撞向纽约和华盛顿的地标建筑。 两架飞…",
    "content": "Getty Images / 2001年9月11日袭击发生后不久，浓烟从纽约世界贸易中心双子塔升起。 美国将于9月11日（星期四）举行一系列活动，纪念九一一袭击25周年。 2001年9月11日，自杀式袭击者劫持美国客机，撞向纽约两座摩天大楼，造成数千人死亡。 这场事件对全球产生了深远影响。 哪些建筑物成为袭击目标？ 四架飞越美国东部的飞机同时遭到小规模劫机团队劫持。 其后，这些飞机被当成巨型导引导弹，撞向纽约和华盛顿的地标建筑。 两架飞机撞上纽约世界贸易中心（World Trade Center）双子塔，第二次撞击…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cn74d8mr640o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "AI「性轉」視頻風靡中國網絡：一場「 新文化運動」的覺醒與侷限",
    "link": "https://www.bbc.com/zhongwen/articles/cn74d8mr640o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-10 08:14:34",
    "author": "",
    "description": "PROVIDED @大粒雞架 一名男子身着粉色清凉裙装，蹲在地上擦地。镜头暧昧地缓缓上移，数次掠过裙摆，男子朝镜头害羞一笑。画面一转，一名西装女性正专注工作，她走近男子，轻抚他的头；随后一个小男孩抱着一箱“好丈夫”拖把走向男子，说这是送给他最好的礼物。 评论区里，不少网友写道：“这个辣弟（对应‘美女’一词的新造词）好美”，或“这才是真正让我想下单的广告”。 这段影片首发于抖音，并非真实广告，而是对传统“好太太”系列家居广告的性别反转创作…",
    "content": "PROVIDED @大粒雞架 一名男子身着粉色清凉裙装，蹲在地上擦地。镜头暧昧地缓缓上移，数次掠过裙摆，男子朝镜头害羞一笑。画面一转，一名西装女性正专注工作，她走近男子，轻抚他的头；随后一个小男孩抱着一箱“好丈夫”拖把走向男子，说这是送给他最好的礼物。 评论区里，不少网友写道：“这个辣弟（对应‘美女’一词的新造词）好美”，或“这才是真正让我想下单的广告”。 这段影片首发于抖音，并非真实广告，而是对传统“好太太”系列家居广告的性别反转创作。这个夏天，“性转”已成为中国互联网上最受瞩目的创作热潮：数以千计的创作者涌入这…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cp931k7xx4do/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "2026台灣地方選舉：「九合一」為何重要？選舉時程是什麼？",
    "link": "https://www.bbc.com/zhongwen/articles/cp931k7xx4do/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-09 17:32:11",
    "author": "",
    "description": "Getty Images / 台湾的地方选举又称“九合一”选举，图为2022年选举开票。 台湾将在今年11月28日举行“九合一”地方选举，选出直辖市长和县市长在内9类地方公职。 其中，蓝绿差距较小、全台人口最多的新北市，被视为决定胜负的重要战场。 分析指出，这场选举不仅是针对总统赖清德的执政信任票，亦是2028年总统大选的起跑赛。对于两岸路线遭党内质疑的国民党主席郑丽文而言，此役也是她能否取得总统大选提名的关键。 相较于“抗中保台”，此…",
    "content": "Getty Images / 台湾的地方选举又称“九合一”选举，图为2022年选举开票。 台湾将在今年11月28日举行“九合一”地方选举，选出直辖市长和县市长在内9类地方公职。 其中，蓝绿差距较小、全台人口最多的新北市，被视为决定胜负的重要战场。 分析指出，这场选举不仅是针对总统赖清德的执政信任票，亦是2028年总统大选的起跑赛。对于两岸路线遭党内质疑的国民党主席郑丽文而言，此役也是她能否取得总统大选提名的关键。 相较于“抗中保台”，此次选举议题更聚焦于民生经济。选前三个月，赖清德宣布派发一万现金、在野阵营则提出三…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cx2yn54wn4eo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "董建華逝世：從船王富二代到香港首任特首，中共的「親密朋友」",
    "link": "https://www.bbc.com/zhongwen/articles/cx2yn54wn4eo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-09 17:29:34",
    "author": "",
    "description": "South China Morning Post/Getty Images / 董建华以89岁之龄辞世。 前中国人民政治协商会议全国委员会副主席，香港政权移交后首任行政长官董建华逝世，享年89岁。 中国官方新华社报导，董建华星期二（9月8日）香港时间近22:00（格林尼治标准时间14:00）在香港逝世。形容董建华是“‘一国两制’杰出贡献者”，“中国共产党的亲密朋友”。 1985年《中英联合声明》签订，香港主权于1997年7月1日从英国移…",
    "content": "South China Morning Post/Getty Images / 董建华以89岁之龄辞世。 前中国人民政治协商会议全国委员会副主席，香港政权移交后首任行政长官董建华逝世，享年89岁。 中国官方新华社报导，董建华星期二（9月8日）香港时间近22:00（格林尼治标准时间14:00）在香港逝世。形容董建华是“‘一国两制’杰出贡献者”，“中国共产党的亲密朋友”。 1985年《中英联合声明》签订，香港主权于1997年7月1日从英国移交中国成为定局。但直到时任中共中央总书记江泽民在北京人民大会堂找他握手，引发“钦…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cx2z9pgprrdo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「教員萬歲」：中國Z世代為何重新「擁抱」毛澤東？",
    "link": "https://www.bbc.com/zhongwen/articles/cx2z9pgprrdo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-09 15:57:41",
    "author": "",
    "description": "BBC / “教员万岁”：中国Z世代为何重新“拥抱”毛泽东？ 今天，距毛泽东去世已整整50年。但在中国网络上，他并没有被年轻人遗忘。 不少Z世代不再叫他“毛主席”，而是称他为“教员”。他的影片在中国网络上获得数百万观看，《毛泽东选集》甚至多年登上清华图书馆年度借阅榜首。 分析认为，这不只是怀旧。面对就业压力和贫富差距，一些年轻人重新从毛泽东的阶级论述寻找答案；毛时代强调的“独立自主、自力更生”，在今日中西方竞争的背景下，也再次产生吸引力…",
    "content": "BBC / “教员万岁”：中国Z世代为何重新“拥抱”毛泽东？ 今天，距毛泽东去世已整整50年。但在中国网络上，他并没有被年轻人遗忘。 不少Z世代不再叫他“毛主席”，而是称他为“教员”。他的影片在中国网络上获得数百万观看，《毛泽东选集》甚至多年登上清华图书馆年度借阅榜首。 分析认为，这不只是怀旧。面对就业压力和贫富差距，一些年轻人重新从毛泽东的阶级论述寻找答案；毛时代强调的“独立自主、自力更生”，在今日中西方竞争的背景下，也再次产生吸引力。 但这股“毛泽东热”也引发疑问：年轻人重新拥抱毛泽东时，究竟记住了什么，又遗忘…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cr4vwye0z02o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「我一度認不出我的男朋友」：我是如何發現自己患有臉盲症的",
    "link": "https://www.bbc.com/zhongwen/articles/cr4vwye0z02o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-09 09:05:42",
    "author": "",
    "description": "BBC/Maryam Nikan 那时候，我曾经认不出我的男朋友。 我们交往大约六个月后，有一次在超市不期而遇。但当我们在谷片货架的走道擦身而过时，我完全不知道他是谁。我记得当时因为他离我太近而感到不安，直到他开口说话，我才从声音认出他。 不用说，他对此并不高兴。但对我而言，这很正常。无论我和某人有多熟，我一直都很难辨认人脸。 因此，作为BBC播客节目《云端科学》（CrowdScience）的一部分，我决定接受脸盲症（face blin…",
    "content": "BBC/Maryam Nikan 那时候，我曾经认不出我的男朋友。 我们交往大约六个月后，有一次在超市不期而遇。但当我们在谷片货架的走道擦身而过时，我完全不知道他是谁。我记得当时因为他离我太近而感到不安，直到他开口说话，我才从声音认出他。 不用说，他对此并不高兴。但对我而言，这很正常。无论我和某人有多熟，我一直都很难辨认人脸。 因此，作为BBC播客节目《云端科学》（CrowdScience）的一部分，我决定接受脸盲症（face blindness）——又称相貌失认症（prosopagnosia）——的测试。这是一种…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c33k4zjm6lro/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "推崇⽑澤東的「Z世代」：彈幕、「教員」與政治失語",
    "link": "https://www.bbc.com/zhongwen/articles/c33k4zjm6lro/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-09 09:05:37",
    "author": "",
    "description": "Getty Images “伟人有很多，教员只有一个。”在中国年轻人的网络语境中，“教员”是对已故中国领导人毛泽东的代指。 在视频网站哔哩哔哩（B站）上搜寻“毛泽东”或者“教员”，很容易看到这样一类影片：剪辑自各类影视剧的毛泽东片段，集合在一起。而每当他的形象出现，密密麻麻的弹幕便会迅速盖过整面萤幕，其中不乏“伟人万岁”“再造中华”“全体起立”之类的溢美之词。 B站用户以年轻人为主，18到24岁的Z世代占比近六成。这类毛泽东影片的内容覆…",
    "content": "Getty Images “伟人有很多，教员只有一个。”在中国年轻人的网络语境中，“教员”是对已故中国领导人毛泽东的代指。 在视频网站哔哩哔哩（B站）上搜寻“毛泽东”或者“教员”，很容易看到这样一类影片：剪辑自各类影视剧的毛泽东片段，集合在一起。而每当他的形象出现，密密麻麻的弹幕便会迅速盖过整面萤幕，其中不乏“伟人万岁”“再造中华”“全体起立”之类的溢美之词。 B站用户以年轻人为主，18到24岁的Z世代占比近六成。这类毛泽东影片的内容覆盖他人生不同阶段，包括他指挥的四渡赤水战役、冷战期间的中美苏关系，以及青年时期的…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cx2n75en5g6o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "董建華：從「船王」之子到香港首任行政長官",
    "link": "https://www.bbc.com/zhongwen/articles/cx2n75en5g6o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-09 02:50:53",
    "author": "",
    "description": "China News Service 香港特区前任行政长官，中国人民政治协商会议全国委员会前副主席董建华9月9日在香港逝世，享年89岁。 董建华出身于航运世家，晚年踏上从政之路，1997年成为英国向中国移交香港主权后首任行政长官，任内先后经历亚洲金融风暴、萨斯（SARS；非典、沙士）冠状病毒疫情和《基本法》第23条国家安全立法争议，连续两年大规模“七一”游行表达对其不满后，最终在时任中国国家主席胡锦涛的“查找不足”训话余音中辞职，没能完…",
    "content": "China News Service 香港特区前任行政长官，中国人民政治协商会议全国委员会前副主席董建华9月9日在香港逝世，享年89岁。 董建华出身于航运世家，晚年踏上从政之路，1997年成为英国向中国移交香港主权后首任行政长官，任内先后经历亚洲金融风暴、萨斯（SARS；非典、沙士）冠状病毒疫情和《基本法》第23条国家安全立法争议，连续两年大规模“七一”游行表达对其不满后，最终在时任中国国家主席胡锦涛的“查找不足”训话余音中辞职，没能完成两任10年任期。 董建华下台后当选全国政协副主席，跻身中国国家领导人序列。20…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c87v33gxr01o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "美軍航母全數撤離印太：台灣該擔心「空窗期」嗎？",
    "link": "https://www.bbc.com/zhongwen/articles/c87v33gxr01o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-08 14:35:07",
    "author": "",
    "description": "Getty Images / 母港位于日本横须贺的“乔治·华盛顿号”航母已被派往中东。目前印太地区已无美国航母驻留。 美国目前部署在东亚的两艘航空母舰已双双离开印太——“林肯号”（USS Abraham Lincoln）结束近九个月、支援对伊朗军事行动的部署后，先驶往泰国休整，已于9月6日启航离境；母港位于日本横须贺的“乔治·华盛顿号”（USS George Washington）则被调往中东接替“林肯号”的任务。这意味着，印太地区目前…",
    "content": "Getty Images / 母港位于日本横须贺的“乔治·华盛顿号”航母已被派往中东。目前印太地区已无美国航母驻留。 美国目前部署在东亚的两艘航空母舰已双双离开印太——“林肯号”（USS Abraham Lincoln）结束近九个月、支援对伊朗军事行动的部署后，先驶往泰国休整，已于9月6日启航离境；母港位于日本横须贺的“乔治·华盛顿号”（USS George Washington）则被调往中东接替“林肯号”的任务。这意味着，印太地区目前没有美国航母“驻留”。 长期以来，航空母舰一直是白宫应对台海紧张局势的关键工具，…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cz9zk1vx53vo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "偏頭痛女性比男性慘痛太多 這裏舒緩有方",
    "link": "https://www.bbc.com/zhongwen/articles/cz9zk1vx53vo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-08 08:17:44",
    "author": "",
    "description": "PonyWang/E+/Getty Images / 女性偏头痛发作的机率是男性的三倍。 躺在黑暗房间里，任由持续不断的疼痛钻入额头，对许多偏头痛（migraine）患者而言，是一种令人十分熟悉的痛苦经历。 这种令人精神衰弱的疾病，可能对人际关系、工作及心理健康造成巨大影响。而女性尤其受到影响，她们偏头痛发作的机率是男性的三倍。 但究竟是甚么原因令偏头痛发作？又有哪些方法可以帮助管理病情？ View this post on Insta…",
    "content": "PonyWang/E+/Getty Images / 女性偏头痛发作的机率是男性的三倍。 躺在黑暗房间里，任由持续不断的疼痛钻入额头，对许多偏头痛（migraine）患者而言，是一种令人十分熟悉的痛苦经历。 这种令人精神衰弱的疾病，可能对人际关系、工作及心理健康造成巨大影响。而女性尤其受到影响，她们偏头痛发作的机率是男性的三倍。 但究竟是甚么原因令偏头痛发作？又有哪些方法可以帮助管理病情？ View this post on Instagram 偏头痛有哪些症状？ 根据英国慈善机构“偏头痛信托基金会”（Migrai…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cddvzm721vpo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "從特朗普到中國，德國極右翼政黨州選獲勝意義在哪？",
    "link": "https://www.bbc.com/zhongwen/articles/cddvzm721vpo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-07 22:36:09",
    "author": "",
    "description": "Reuters / 德国另类选择党（AfD）首席候选人乌尔里希·西格蒙德（Ulrich Siegmund）表示，该党已获得明确的执政授权。 “地壳板块运动级的变化”、“一场社会政治地震”、“德国的分水岭时刻”。 政治分析人士及许多媒体以这些词语，形容反移民的德国另类选择党（Alternative for Germany, AfD）星期日（9月6日）在德国地方选举中的惊人胜利。这是否言过其实？ 萨克森—安哈特（Saxony-Anhalt）…",
    "content": "Reuters / 德国另类选择党（AfD）首席候选人乌尔里希·西格蒙德（Ulrich Siegmund）表示，该党已获得明确的执政授权。 “地壳板块运动级的变化”、“一场社会政治地震”、“德国的分水岭时刻”。 政治分析人士及许多媒体以这些词语，形容反移民的德国另类选择党（Alternative for Germany, AfD）星期日（9月6日）在德国地方选举中的惊人胜利。这是否言过其实？ 萨克森—安哈特（Saxony-Anhalt）是德国16个州之中规模最小的州之一。全国5,900万名合资格选民中，该州仅有17…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c3057m5q127o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "氣候變暖如何影響你的飛行旅程？",
    "link": "https://www.bbc.com/zhongwen/articles/c3057m5q127o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-07 14:39:29",
    "author": "",
    "description": "BBC 6月底，当英国正经历炎热夏季中的其中一轮热浪，酷热难耐之际，高耸的雷雨云正聚集在英格兰南部上空，以及北欧大部分地区。 那是个星期六，随着假期旺季开始，数以千计的乘客正前往伦敦希思路和盖特威克机场，准备乘搭航班出国。这注定会是非常繁忙的一天。 然而，接下来发生的事情却令旅客陷入混乱。 空中交通管制员努力让飞机绕过暴风雨，空域变得严重挤塞，许多原定起飞的航班被迫留在地面等待。最终，往返两个机场的约900班航班延误，部分延误时间长达1…",
    "content": "BBC 6月底，当英国正经历炎热夏季中的其中一轮热浪，酷热难耐之际，高耸的雷雨云正聚集在英格兰南部上空，以及北欧大部分地区。 那是个星期六，随着假期旺季开始，数以千计的乘客正前往伦敦希思路和盖特威克机场，准备乘搭航班出国。这注定会是非常繁忙的一天。 然而，接下来发生的事情却令旅客陷入混乱。 空中交通管制员努力让飞机绕过暴风雨，空域变得严重挤塞，许多原定起飞的航班被迫留在地面等待。最终，往返两个机场的约900班航班延误，部分延误时间长达11小时。另有数十班航班被取消。 在欧洲各地的机场，原本预计飞往伦敦的乘客同样面对…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cwyzv9w5w6yo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "歐洲國家為何提走北美黃金儲備",
    "link": "https://www.bbc.com/zhongwen/articles/cwyzv9w5w6yo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-07 08:03:22",
    "author": "",
    "description": "Getty Images 荷兰的中央银行上周证实，已将数十吨黄金从北美移出，并表示此举将使其“更能为严重危机做好准备”。 该行表示，考虑到“日益加剧的地缘政治动荡”，已将存放于美国和加拿大、总量约313吨黄金中的86吨迁往伦敦，让这些闪闪发亮的资产能够在“危机情况下随时可供使用”。 随之而来的疑问在所难免。荷兰为何要这样做？是否预期地平线上将出现某种重大经济冲击？ 看来并非如此，但这项举措显然是回应当前世界所面对的不稳定和不确定局势。随…",
    "content": "Getty Images 荷兰的中央银行上周证实，已将数十吨黄金从北美移出，并表示此举将使其“更能为严重危机做好准备”。 该行表示，考虑到“日益加剧的地缘政治动荡”，已将存放于美国和加拿大、总量约313吨黄金中的86吨迁往伦敦，让这些闪闪发亮的资产能够在“危机情况下随时可供使用”。 随之而来的疑问在所难免。荷兰为何要这样做？是否预期地平线上将出现某种重大经济冲击？ 看来并非如此，但这项举措显然是回应当前世界所面对的不稳定和不确定局势。随着贸易战与军事冲突持续，各国正采取预防措施，并将黄金保存在更接近本土的地方。 今…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cj4j2kp0818o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "印度洋蔥「政治敏感」得要坐上鐵路快車",
    "link": "https://www.bbc.com/zhongwen/articles/cj4j2kp0818o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-06 21:17:31",
    "author": "",
    "description": "BBC / 洋蔥在印度犹如主食，其价格波动直接造成民怨。 在亚洲的洋蔥之都，数十名工人弯下腰来手工分拣洋蔥，并把装满洋蔥的防水帆布袋搬上小型货车后方。 他们加紧工作；一列特别包租的货运列车正在等待，准备将这座气味浓烈的“洋蔥山”从印度西部的拉萨尔冈（Lasalgaon）运往首都，在那里，这种厨房必备食材的价格已飙升多时。 政府希望透过动用国家储备，并向至少11个主要城市运送洋蔥，来抑制成本急升。 当涉及这种至关重要的葱属蔬菜时，政府往往…",
    "content": "BBC / 洋蔥在印度犹如主食，其价格波动直接造成民怨。 在亚洲的洋蔥之都，数十名工人弯下腰来手工分拣洋蔥，并把装满洋蔥的防水帆布袋搬上小型货车后方。 他们加紧工作；一列特别包租的货运列车正在等待，准备将这座气味浓烈的“洋蔥山”从印度西部的拉萨尔冈（Lasalgaon）运往首都，在那里，这种厨房必备食材的价格已飙升多时。 政府希望透过动用国家储备，并向至少11个主要城市运送洋蔥，来抑制成本急升。 当涉及这种至关重要的葱属蔬菜时，政府往往会迅速介入。洋蔥贸易的价格波动曾驱使民众走上街头，影响邻里关系，甚至左右选举结果…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cm2q6pyyzn0o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普取態何以左右福克蘭群島爭議",
    "link": "https://www.bbc.com/zhongwen/articles/cm2q6pyyzn0o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-06 15:42:46",
    "author": "",
    "description": "Tomas Cuesta/Getty Images / 阿根廷总统哈维尔·米莱与特朗普总统关系密切。 早于上周稍早有关制裁的深夜全国演说之前，阿根廷总统哈维尔·米莱（Javier Milei；米雷伊）围绕福克兰群岛（Falkland Islands；阿根廷称马尔维纳斯群岛，Islas Malvinas）争议的语气就已日益强硬。 人们很容易将这种紧张局势视为今夏国际足协（FIFA）世界杯上阿根廷球员艰苦击败英格兰后欢庆场面的具象化呈现。当…",
    "content": "Tomas Cuesta/Getty Images / 阿根廷总统哈维尔·米莱与特朗普总统关系密切。 早于上周稍早有关制裁的深夜全国演说之前，阿根廷总统哈维尔·米莱（Javier Milei；米雷伊）围绕福克兰群岛（Falkland Islands；阿根廷称马尔维纳斯群岛，Islas Malvinas）争议的语气就已日益强硬。 人们很容易将这种紧张局势视为今夏国际足协（FIFA）世界杯上阿根廷球员艰苦击败英格兰后欢庆场面的具象化呈现。当时，他们在欣喜若狂的球迷面前高举一面写着“Las Malvinas son Ar…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c0re1x8wg24o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "尼泊爾給水力發電押下重注，泥石流把問題徹底暴露",
    "link": "https://www.bbc.com/zhongwen/articles/c0re1x8wg24o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-06 13:19:17",
    "author": "",
    "description": "Didier Marti / 直到八年前，尼泊尔仍一直受长时间停电所困扰。 尼泊尔近100%的电力来自水力发电，而且产量高到每年向印度和孟加拉出口水电可赚取近2亿美元（13.4亿元人民币；63.2亿元新台币）。 但是赋予尼泊尔这项巨大天然优势的冰川和山脉，正屈服于全球暖化，8月26日的致命洪灾暴露了该国水力发电雄心所面临的风险。 泥石流造成超过1300人丧生，数千人仍然失踪。 这场洪灾摧毁了尼泊尔与西藏交界附近的整个村庄，并严重破坏特里…",
    "content": "Didier Marti / 直到八年前，尼泊尔仍一直受长时间停电所困扰。 尼泊尔近100%的电力来自水力发电，而且产量高到每年向印度和孟加拉出口水电可赚取近2亿美元（13.4亿元人民币；63.2亿元新台币）。 但是赋予尼泊尔这项巨大天然优势的冰川和山脉，正屈服于全球暖化，8月26日的致命洪灾暴露了该国水力发电雄心所面临的风险。 泥石流造成超过1300人丧生，数千人仍然失踪。 这场洪灾摧毁了尼泊尔与西藏交界附近的整个村庄，并严重破坏特里苏里河（Trishuli River）流域的12座水力发电厂，使尼泊尔总发电能力…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/crm9k8pggjvo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "不同版本的世界地圖有哪些正確及錯誤之處？",
    "link": "https://www.bbc.com/zhongwen/articles/crm9k8pggjvo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-06 12:35:53",
    "author": "",
    "description": "BBC / 墨卡托投影是全球广泛使用的地图投影方式，但它对国家和大陆面积的描绘并不准确。 联合国（UN）刚刚呼吁用一张能够更准确反映非洲等各大洲真实大小的地图来取代目前主流的世界地图。 联合国大会通过的“修正地图”决议旨在纠正墨卡托地图（Mercator map）上的差异，该地图显示非洲大陆与格陵兰岛大小相似——尽管实际上非洲大陆比格陵兰岛大约14倍。 它采用了新的地图——等地球投影，这种投影能更好地表示陆地的真实大小——但它本身也存在…",
    "content": "BBC / 墨卡托投影是全球广泛使用的地图投影方式，但它对国家和大陆面积的描绘并不准确。 联合国（UN）刚刚呼吁用一张能够更准确反映非洲等各大洲真实大小的地图来取代目前主流的世界地图。 联合国大会通过的“修正地图”决议旨在纠正墨卡托地图（Mercator map）上的差异，该地图显示非洲大陆与格陵兰岛大小相似——尽管实际上非洲大陆比格陵兰岛大约14倍。 它采用了新的地图——等地球投影，这种投影能更好地表示陆地的真实大小——但它本身也存在一些问题。 事实上，多年来，人们曾多次尝试解决在平面矩形上精确表示球面的问题，每…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cn5dx6gqxn9o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "機器人開始索要小費，但錢到底進了誰的口袋？",
    "link": "https://www.bbc.com/zhongwen/articles/cn5dx6gqxn9o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-06 10:02:19",
    "author": "",
    "description": "BBC/ Serenity Strull 机器正伸出它们的数字手掌。你的反应，或将塑造服务业的未来。 如果你在拉斯维加斯威尼斯人酒店（Venetian Hotel）对老虎机提不起兴趣，可以到一间名为“The Tipsy Robot”的酒吧找点乐子。那里有个俗气的噱头：两只自动调制鸡尾酒的机械臂。 我在屏幕上按下“玛格丽特”，看着它们猛然动起来。它们把龙舌兰酒与青柠汁和橙味利口酒调和在一起，还不必要地多转了几圈来炫技，最后微微一躬，把酒杯…",
    "content": "BBC/ Serenity Strull 机器正伸出它们的数字手掌。你的反应，或将塑造服务业的未来。 如果你在拉斯维加斯威尼斯人酒店（Venetian Hotel）对老虎机提不起兴趣，可以到一间名为“The Tipsy Robot”的酒吧找点乐子。那里有个俗气的噱头：两只自动调制鸡尾酒的机械臂。 我在屏幕上按下“玛格丽特”，看着它们猛然动起来。它们把龙舌兰酒与青柠汁和橙味利口酒调和在一起，还不必要地多转了几圈来炫技，最后微微一躬，把酒杯递到我面前。这一切或许在 20 年前会令我惊叹。如今，这几乎已成陈腔滥调。 这杯…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c2kwv977qlko/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「究竟是誰在批准什麼？」：光州雙年展台灣改名風波背後的角力",
    "link": "https://www.bbc.com/zhongwen/articles/c2kwv977qlko/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-04 22:33:16",
    "author": "",
    "description": "鄭亭亭提供 / 创办于1995年的光州双年展，是亚洲历史最悠久、最具影响力的国际当代艺术展之一。 8月初，台湾艺术家郑亭亭突然得知，自己将参展的韩国“光州双年展”海报中，“台湾”的名字消失了。 五颜六色的海报中，本来写着“Taiwan”的部分，开幕前被取代为“NTMoFA”。改名之前，主办方并未告知台湾参展人。 郑亭亭告诉BBC中文，自己很被动才得知这个消息，“（当初）是另一个艺术家的朋友看到海报后来问他说，‘你不是说你参加台湾馆吗？怎…",
    "content": "鄭亭亭提供 / 创办于1995年的光州双年展，是亚洲历史最悠久、最具影响力的国际当代艺术展之一。 8月初，台湾艺术家郑亭亭突然得知，自己将参展的韩国“光州双年展”海报中，“台湾”的名字消失了。 五颜六色的海报中，本来写着“Taiwan”的部分，开幕前被取代为“NTMoFA”。改名之前，主办方并未告知台湾参展人。 郑亭亭告诉BBC中文，自己很被动才得知这个消息，“（当初）是另一个艺术家的朋友看到海报后来问他说，‘你不是说你参加台湾馆吗？怎么没有台湾馆？’” 她在数月前获邀以作品〈口述影像〉，参与9月登场的光州双年展台…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cz6zd7j8nn0o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "韓國光州雙年展: 中國退展，「台灣館」風波透露什麼？",
    "link": "https://www.bbc.com/zhongwen/articles/cz6zd7j8nn0o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-04 18:56:52",
    "author": "",
    "description": "BBC / 韩国光州双年展: 中国退展，“台湾馆”风波透露什么？ 韩国举行的光州双年展因“台湾馆”名称遭改动陷入争议，中国周四（9月3日）宣布退出展览。 今年初，国立台湾美术馆申请参展，并以“台湾馆”（Taiwan Pavilion）名称与主办方往来。 然而，八月初公布的电子文宣中，原本的“Taiwan”却被改为国美馆的英文缩写“NTMoFA”。事件曝光后，台湾参展艺术家提出抗议，当地许多艺术家、民众也进行声援。主办单位最终同意恢复使用…",
    "content": "BBC / 韩国光州双年展: 中国退展，“台湾馆”风波透露什么？ 韩国举行的光州双年展因“台湾馆”名称遭改动陷入争议，中国周四（9月3日）宣布退出展览。 今年初，国立台湾美术馆申请参展，并以“台湾馆”（Taiwan Pavilion）名称与主办方往来。 然而，八月初公布的电子文宣中，原本的“Taiwan”却被改为国美馆的英文缩写“NTMoFA”。事件曝光后，台湾参展艺术家提出抗议，当地许多艺术家、民众也进行声援。主办单位最终同意恢复使用“台湾馆”，但引起中方不满。 光州市政府则发声明道歉，指尊重“一个中国”。然而，…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cwyznp4qlg9o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "行走在紐約：我發現監控攝像頭數量遠超想像",
    "link": "https://www.bbc.com/zhongwen/articles/cwyznp4qlg9o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-04 14:25:54",
    "author": "",
    "description": "BBC/ Serenity Strull 在隐私与安全之间的权衡中，了解你所在社区的监控基础设施究竟有多少，会有所帮助。现在有一些简单的方法可以做到这一点。 我没有告诉任何人，我要与监控科技监督项目（Surveillance Technology Oversight Project）的执行主任米歇尔·达尔（Michelle Dahl）见面。这是一个监督组织。但当我在纽约布鲁克林与她打招呼时，系统已经知道我们在一起。 “如果你不是刻意去找…",
    "content": "BBC/ Serenity Strull 在隐私与安全之间的权衡中，了解你所在社区的监控基础设施究竟有多少，会有所帮助。现在有一些简单的方法可以做到这一点。 我没有告诉任何人，我要与监控科技监督项目（Surveillance Technology Oversight Project）的执行主任米歇尔·达尔（Michelle Dahl）见面。这是一个监督组织。但当我在纽约布鲁克林与她打招呼时，系统已经知道我们在一起。 “如果你不是刻意去找，这一切其实是隐形的。”达尔说着指向一根路灯——两个标有纽约市警察局（NYPD）…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c1dlr007vkgo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "豬腎在人體內運作271天——這會是器官移植的未來嗎？",
    "link": "https://www.bbc.com/zhongwen/articles/c1dlr007vkgo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-04 13:57:06",
    "author": "",
    "description": "Kate Flock/Massachusetts General Hospital / 患者蒂姆·安德鲁斯（中）与川井达夫医生（左）和莱昂纳多·里埃拉医生（右）合影 美国病人蒂姆·安德鲁斯（Tim Andrews）的肾脏功能正在衰竭。去年，他接受了一个由猪只移植的肾脏。猪肾在他体内正常运作了271天，创下目前最长的国际纪录。 安德鲁斯表示，这次移植让他“重新有了希望”，也让他免于数月来往医院，依靠透析机过滤血液（俗称洗肾）。 不过，这个…",
    "content": "Kate Flock/Massachusetts General Hospital / 患者蒂姆·安德鲁斯（中）与川井达夫医生（左）和莱昂纳多·里埃拉医生（右）合影 美国病人蒂姆·安德鲁斯（Tim Andrews）的肾脏功能正在衰竭。去年，他接受了一个由猪只移植的肾脏。猪肾在他体内正常运作了271天，创下目前最长的国际纪录。 安德鲁斯表示，这次移植让他“重新有了希望”，也让他免于数月来往医院，依靠透析机过滤血液（俗称洗肾）。 不过，这个猪肾最终失去功能并被移除。安德鲁斯其后需要短暂接受透析，直到找到合适的人类捐赠器…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c3wj1gd3x9no/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "執迷於「睡眠分數」如何反讓你睡得更差？",
    "link": "https://www.bbc.com/zhongwen/articles/c3wj1gd3x9no/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-04 10:05:55",
    "author": "",
    "description": "BBC 睡眠评分、镁补充剂、白噪音机器——睡觉曾经是简单的事，如今却成了一片雷区。 这种尝试优化睡眠的做法，被称为“睡眠极大化”（sleepmaxxing）。如果做得太过火，就可能会演变成“完美睡眠主义症”（orthosomnia），临床上指追求完美睡眠的一种执着。 虽然这在英国并未被正式列为疾病，但医生向BBC表示，他们留意到部分病人出现完美睡眠主义症的迹象。有些病人带着睡眠追踪数据求诊，错误地深信自己患有睡眠障碍。 医生警告，对睡眠…",
    "content": "BBC 睡眠评分、镁补充剂、白噪音机器——睡觉曾经是简单的事，如今却成了一片雷区。 这种尝试优化睡眠的做法，被称为“睡眠极大化”（sleepmaxxing）。如果做得太过火，就可能会演变成“完美睡眠主义症”（orthosomnia），临床上指追求完美睡眠的一种执着。 虽然这在英国并未被正式列为疾病，但医生向BBC表示，他们留意到部分病人出现完美睡眠主义症的迹象。有些病人带着睡眠追踪数据求诊，错误地深信自己患有睡眠障碍。 医生警告，对睡眠的执着，实际上让人们睡得更差。 到底睡眠为何以变得如此复杂？如果“睡眠极大化”不…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c5yd4361y6no/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "《肖申克的救贖》中國公映：官方字幕翻譯何以引發爭議？",
    "link": "https://www.bbc.com/zhongwen/articles/c5yd4361y6no/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-03 08:24:43",
    "author": "",
    "description": "Getty Images 8月28日，《肖申克的救赎》（The Shawshank Redemption，港译《月黑高飞》、台译《刺激1995》）修复版在中国内地公映，官方字幕的多处翻译选择随即引发网路热议。影片翻译、性别学者接受BBC中文采访，阐述了各自的理解。 500码被译成500米，体制化（institutionalized）译成“牢笼驯化”，同性恋（homosexual）译成“不同的人”，queer译成“变态”，就连那句吐槽识字…",
    "content": "Getty Images 8月28日，《肖申克的救赎》（The Shawshank Redemption，港译《月黑高飞》、台译《刺激1995》）修复版在中国内地公映，官方字幕的多处翻译选择随即引发网路热议。影片翻译、性别学者接受BBC中文采访，阐述了各自的理解。 500码被译成500米，体制化（institutionalized）译成“牢笼驯化”，同性恋（homosexual）译成“不同的人”，queer译成“变态”，就连那句吐槽识字太难、“难得像中文”的台词，也被译成了“天书”。 其中争议最大的，是queer一…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cz6zpzwwxlzo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "尼泊爾—西藏泥石流：堰塞湖和冰湖是下一個「定時炸彈」？",
    "link": "https://www.bbc.com/zhongwen/articles/cz6zpzwwxlzo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-02 08:01:34",
    "author": "",
    "description": "AFP via Getty Images 中国西藏与尼泊尔边境山洪暴发，至今造成过千人遇难、超过4000人失联。 在泥石流灾难过后，危险并未结束。 事发河谷上游已形成两个堰塞湖。与此同时，原本散布在喜马拉雅山区的冰川湖，在灾区内有10座被标记为高风险，专家形容它们是“定时炸弹”。 外界担心，一旦这些天然“水坝”溃堤，恐将带来二度灾害。 堰塞湖的成因为何？高山冰川形成的湖泊会带来哪些隐患？预警措施是否能减轻危害？BBC中文整理出相关资讯。…",
    "content": "AFP via Getty Images 中国西藏与尼泊尔边境山洪暴发，至今造成过千人遇难、超过4000人失联。 在泥石流灾难过后，危险并未结束。 事发河谷上游已形成两个堰塞湖。与此同时，原本散布在喜马拉雅山区的冰川湖，在灾区内有10座被标记为高风险，专家形容它们是“定时炸弹”。 外界担心，一旦这些天然“水坝”溃堤，恐将带来二度灾害。 堰塞湖的成因为何？高山冰川形成的湖泊会带来哪些隐患？预警措施是否能减轻危害？BBC中文整理出相关资讯。 BBC 何谓堰塞湖？ 这次泥石流主因，来自于喜马拉雅山脉朗当利龙峰南坡约5,2…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cp802gnj5kmo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "泥石流摧毀西藏吉隆口岸的關鍵幾分鐘",
    "link": "https://www.bbc.com/zhongwen/articles/cp802gnj5kmo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-09-01 20:01:05",
    "author": "",
    "description": "Vantor / 卫星图片显示尼泊尔与中国吉隆口岸一带在毁灭性洪水冲走建筑物和车辆前的模样。 影片就那短短的几秒钟。 在尼泊尔与西藏边境中方一侧的吉隆（Gyirong），一道黑色高墙从建筑物后方出现。起初，它看起来几乎像一团乌云。随后，它逐渐成形并加速前进：洪水、泥浆、巨石、冰块和岩石沿着山谷奔涌而下。闭路电视画面上的时间戳记显示：当地时间10时59分53秒。 随后几分钟内究竟发生了甚么，至今仍难以完整重建。但灾难发生前后的零散影片与卫…",
    "content": "Vantor / 卫星图片显示尼泊尔与中国吉隆口岸一带在毁灭性洪水冲走建筑物和车辆前的模样。 影片就那短短的几秒钟。 在尼泊尔与西藏边境中方一侧的吉隆（Gyirong），一道黑色高墙从建筑物后方出现。起初，它看起来几乎像一团乌云。随后，它逐渐成形并加速前进：洪水、泥浆、巨石、冰块和岩石沿着山谷奔涌而下。闭路电视画面上的时间戳记显示：当地时间10时59分53秒。 随后几分钟内究竟发生了甚么，至今仍难以完整重建。但灾难发生前后的零散影片与卫星影像，已开始揭示破坏的规模。边境设施的大部分似乎已被冲走，曾经挤满谷底的建筑如…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cnvl38dyyq0o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國審查西藏口岸遭洪災衝擊畫面，當地災民情況我們所知甚少",
    "link": "https://www.bbc.com/zhongwen/articles/cnvl38dyyq0o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-08-30 20:37:59",
    "author": "",
    "description": "BBC/CCTV / 中国官媒上为何看不到西藏洪灾冲击画面？ 如此冲击影片实在难以忽视：一股洪流冲过吉隆口岸，这个尼泊尔与西藏之间的主要边境口岸之一，所到之处尽被冲毁，数百人为了逃命而奔逃。 这些由闭路电视拍下的画面迅速在社交媒体上传播，并登上世界各地的萤幕。 除了中国本身。 迄今为止，中国官方主导的国家级新闻联播只播出了一张定格画面。 在中国受到严格审查的网际网路上，也很难找到完整影片，尽管有关这场灾难的不同面向曾在网上被讨论。 但更…",
    "content": "BBC/CCTV / 中国官媒上为何看不到西藏洪灾冲击画面？ 如此冲击影片实在难以忽视：一股洪流冲过吉隆口岸，这个尼泊尔与西藏之间的主要边境口岸之一，所到之处尽被冲毁，数百人为了逃命而奔逃。 这些由闭路电视拍下的画面迅速在社交媒体上传播，并登上世界各地的萤幕。 除了中国本身。 迄今为止，中国官方主导的国家级新闻联播只播出了一张定格画面。 在中国受到严格审查的网际网路上，也很难找到完整影片，尽管有关这场灾难的不同面向曾在网上被讨论。 但更难找到的是生还者亲身讲述这场山洪暴发的经历。自星期三（8月26日）以来，这场灾害…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c9v9pkd7ejpo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國科技公司新嘗試：「性愛」機器人，瞄準「陪伴經濟」",
    "link": "https://www.bbc.com/zhongwen/articles/c9v9pkd7ejpo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-08-28 16:51:11",
    "author": "",
    "description": "Getty Images / 一些人形机器人能做到微表情和人类高度相似 8月23日在北京闭幕的世界机器人大会上，一批外形高度接近真人的仿生机器人亮相：骨骼立体、皮肤柔软，甚至能做出人类的微表情。 与过去主要展示跳舞、行走等功能的人形机器人不同，这一批新产品把重点放在微表情、声音、触觉，以及与人工智慧（AI，人工智能）结合的情感互动上。 中国科技公司优必选在大会上提出，要让机器人实现从“像人”到“懂人”的跨越。从现场展示的机器人新品来看，…",
    "content": "Getty Images / 一些人形机器人能做到微表情和人类高度相似 8月23日在北京闭幕的世界机器人大会上，一批外形高度接近真人的仿生机器人亮相：骨骼立体、皮肤柔软，甚至能做出人类的微表情。 与过去主要展示跳舞、行走等功能的人形机器人不同，这一批新产品把重点放在微表情、声音、触觉，以及与人工智慧（AI，人工智能）结合的情感互动上。 中国科技公司优必选在大会上提出，要让机器人实现从“像人”到“懂人”的跨越。从现场展示的机器人新品来看，这也正成为中国多家科技公司竞逐的新方向。 这些产品背后，瞄准的是中国近年来快速发…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cdj013krm3no/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "霍爾木茲海峽動盪，如何在巴拿馬運河引發中美角力？",
    "link": "https://www.bbc.com/zhongwen/articles/cdj013krm3no/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-08-21 21:39:35",
    "author": "",
    "description": "Getty Images / 巴拿马运河约占全球海运贸易量5%，但美国近40%的集装箱运输都经过这里。 随着伊朗战争持续干扰全球其中一条最重要的航运通道霍尔木兹海峡（Strait of Hormuz，荷莫兹海峡），数千公里以外另一个战略咽喉也成为新的角力焦点，那就是连接大西洋与太平洋的重要通道——巴拿马运河。 最新一轮交锋上周在联合国上演。美国警告，中国在巴拿马运河周边的影响力日益扩大，可能威胁全球贸易和安全。 北京驳斥这项说法，指责华…",
    "content": "Getty Images / 巴拿马运河约占全球海运贸易量5%，但美国近40%的集装箱运输都经过这里。 随着伊朗战争持续干扰全球其中一条最重要的航运通道霍尔木兹海峡（Strait of Hormuz，荷莫兹海峡），数千公里以外另一个战略咽喉也成为新的角力焦点，那就是连接大西洋与太平洋的重要通道——巴拿马运河。 最新一轮交锋上周在联合国上演。美国警告，中国在巴拿马运河周边的影响力日益扩大，可能威胁全球贸易和安全。 北京驳斥这项说法，指责华盛顿以此为藉口，企图扩大对运河的控制。 夹在两国之间的巴拿马则重申对运河拥有主权…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cq6d1y1212po/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "美國稱數十國助中國避特朗普關稅",
    "link": "https://www.bbc.com/zhongwen/articles/cq6d1y1212po/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-08-14 13:11:59",
    "author": "",
    "description": "AFP via Getty Images 白宫在一份报告中称，超过40个国家透过将出口商品绕道经由面临较低美国进口关税的国家，协助中国规避美国关税。 星期四（8月13日）发表的报告点名的国家包括加拿大、印度、墨西哥、日本和南韩。白宫表示，这些国家协助中国规避价值数百亿美元的关税。 白宫贸易顾问彼得·纳瓦罗（Peter Navarro）表示，这已造成“美国就业机会流失及数十亿美元收入损失”。 中国驻美国大使馆发言人回应BBC查询时表示，“…",
    "content": "AFP via Getty Images 白宫在一份报告中称，超过40个国家透过将出口商品绕道经由面临较低美国进口关税的国家，协助中国规避美国关税。 星期四（8月13日）发表的报告点名的国家包括加拿大、印度、墨西哥、日本和南韩。白宫表示，这些国家协助中国规避价值数百亿美元的关税。 白宫贸易顾问彼得·纳瓦罗（Peter Navarro）表示，这已造成“美国就业机会流失及数十亿美元收入损失”。 中国驻美国大使馆发言人回应BBC查询时表示，“贸易战没有赢家”，并指中国反对美国的关税措施，以及利用国家力量针对中国企业。 该…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cqx7z51qvpgo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特習會後美中再現摩擦 「建設性穩定」能否撐到九月？",
    "link": "https://www.bbc.com/zhongwen/articles/cqx7z51qvpgo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-08-04 08:01:45",
    "author": "",
    "description": "Getty Images 美国总统特朗普（Donald Trump，川普）今年5月访问北京，与中国国家主席习近平会谈后，美中双方定调建立“建设性战略稳定关系”，意图在竞争中寻找可控互动，避免冲突进一步升级。 然而，短短数月内，特朗普在全国电视演说中突然重提“中国干预美国大选”指控；美国随后以“强迫劳动”为由，对包括中国在内的多个经济体加征新的301条款关税（中国税率达12.5%），立即引发北京强烈不满与反击。 这些举措背后，双方各自打着…",
    "content": "Getty Images 美国总统特朗普（Donald Trump，川普）今年5月访问北京，与中国国家主席习近平会谈后，美中双方定调建立“建设性战略稳定关系”，意图在竞争中寻找可控互动，避免冲突进一步升级。 然而，短短数月内，特朗普在全国电视演说中突然重提“中国干预美国大选”指控；美国随后以“强迫劳动”为由，对包括中国在内的多个经济体加征新的301条款关税（中国税率达12.5%），立即引发北京强烈不满与反击。 这些举措背后，双方各自打着什么算盘？ 多名接受BBC中文访问的学者认为，目前双方仍在“管理竞争”的框架内互…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cgljn380r59o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中美俄的太空攻防戰：衛星如何成為現代戰爭的第一擊？",
    "link": "https://www.bbc.com/zhongwen/articles/cgljn380r59o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-08-01 17:56:01",
    "author": "",
    "description": "Getty Images 在现代战争中，环绕地球运行的人造卫星几乎未曾受到波及；但到了21世纪，太空或许已不再是安全的避风港。 2022年2月24日凌晨约3时，乌克兰及中欧数以千计的卫星数据机突然断线。数小时后，俄罗斯正式入侵乌克兰。 美国智库“战略与国际研究中心”（CSIS）航空航天安全项目主任卡丽·宾根（Kari Bingen）说：“俄乌战争打响的第一击，不是坦克驶进乌克兰，而是针对一套商业卫星系统发动网络攻击，后来被认定是俄罗斯政…",
    "content": "Getty Images 在现代战争中，环绕地球运行的人造卫星几乎未曾受到波及；但到了21世纪，太空或许已不再是安全的避风港。 2022年2月24日凌晨约3时，乌克兰及中欧数以千计的卫星数据机突然断线。数小时后，俄罗斯正式入侵乌克兰。 美国智库“战略与国际研究中心”（CSIS）航空航天安全项目主任卡丽·宾根（Kari Bingen）说：“俄乌战争打响的第一击，不是坦克驶进乌克兰，而是针对一套商业卫星系统发动网络攻击，后来被认定是俄罗斯政府所为。” “他们为什么这样做？因为他们想削弱乌克兰军方和政府的通讯能力。” 现…"
  }
];

export default jsonData;
