const jsonData = [
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260706-%E7%9F%A2%E6%9D%BF%E6%98%8E%E5%A4%AB%E5%8F%B0%E4%B8%AD%E9%81%AD%E6%8C%A5%E6%8B%B3%E6%94%BB%E5%87%BB-%E7%8A%AF%E6%A1%88%E9%BB%91%E8%A1%A3%E7%94%B7%E6%9C%BA%E5%9C%BA%E8%90%BD%E7%BD%91",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "矢板明夫台中遭挥拳攻击 犯案黑衣男机场落网 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%94%BF%E6%B2%BB/20260706-%E7%9F%A2%E6%9D%BF%E6%98%8E%E5%A4%AB%E5%8F%B0%E4%B8%AD%E9%81%AD%E6%8C%A5%E6%8B%B3%E6%94%BB%E5%87%BB-%E7%8A%AF%E6%A1%88%E9%BB%91%E8%A1%A3%E7%94%B7%E6%9C%BA%E5%9C%BA%E8%90%BD%E7%BD%91",
    "pub_date": "2026-07-06 17:15:03",
    "author": "",
    "description": "06/07/2026 - 10:40 据中央社报导，印太战略智库执行长矢板明夫受邀担任春雨文教基金会在台中市举办的营队讲师，当地时间周一中午结束离开饭店时，遭不明人士尾随挥拳攻击脸部，经工作人员送医后，随即前往警方报案。联合新闻网等媒体最新消息指，警方周一下午4时许，在台中机场将涉案廖姓男子缉捕到案，依伤害罪侦办，将建请检察官声请羁押。 据了解，矢板明夫受邀担任春雨文教基金会在台中永丰栈酒店举办的“NEXT CITY─春雨创生行动营－前…",
    "content": "06/07/2026 - 10:40 据中央社报导，印太战略智库执行长矢板明夫受邀担任春雨文教基金会在台中市举办的营队讲师，当地时间周一中午结束离开饭店时，遭不明人士尾随挥拳攻击脸部，经工作人员送医后，随即前往警方报案。联合新闻网等媒体最新消息指，警方周一下午4时许，在台中机场将涉案廖姓男子缉捕到案，依伤害罪侦办，将建请检察官声请羁押。 据了解，矢板明夫受邀担任春雨文教基金会在台中永丰栈酒店举办的“NEXT CITY─春雨创生行动营－前进新台中”营队讲师，当天中午演讲结束离开时，遭不明人士尾随、挥拳攻击，犯嫌随后逃…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%B3%95%E5%9B%BD/20260706-%E9%98%BF%E7%BB%B4%E5%B0%BC%E7%BF%81%E9%95%9C%E9%9D%A2%E8%88%AC%E5%8F%8D%E6%98%A0%E6%B3%95%E5%9B%BD%E6%94%BF%E6%B2%BB%E7%94%9F%E6%B4%BB-%E8%88%9E%E5%8F%B0%E6%97%A2%E7%BB%99%E5%89%8D%E6%80%BB%E7%BB%9F%EF%BC%8C-%E4%B9%9F%E7%BB%99%E6%80%BB%E7%BB%9F%E5%80%99%E9%80%89%E4%BA%BA",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "阿维尼翁镜面般反映法国政治生活： 舞台既给前总统， 也给总统候选人 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%B3%95%E5%9B%BD/20260706-%E9%98%BF%E7%BB%B4%E5%B0%BC%E7%BF%81%E9%95%9C%E9%9D%A2%E8%88%AC%E5%8F%8D%E6%98%A0%E6%B3%95%E5%9B%BD%E6%94%BF%E6%B2%BB%E7%94%9F%E6%B4%BB-%E8%88%9E%E5%8F%B0%E6%97%A2%E7%BB%99%E5%89%8D%E6%80%BB%E7%BB%9F%EF%BC%8C-%E4%B9%9F%E7%BB%99%E6%80%BB%E7%BB%9F%E5%80%99%E9%80%89%E4%BA%BA",
    "pub_date": "2026-07-06 16:15:02",
    "author": "",
    "description": "06/07/2026 - 09:48 先说戏里。阿维尼翁的蓝色列车剧院每天都在上演身份戏剧Sarkhollande《萨科-奥朗德》。 萨科齐是法国右翼前总统，奥兰德是法国左翼前总统。舞台上前总统尼古拉·萨科齐这个角色讲述自己一波三折的情史，表演与时任德国总理默克尔的通电话打情景，他问到 “2008年我拯救了银行。那是件好事吗？” 奥朗德则以小丑形象登场，演员模仿奥朗德那句著名的口头禅“我，作为总统……”（Me, as President…",
    "content": "06/07/2026 - 09:48 先说戏里。阿维尼翁的蓝色列车剧院每天都在上演身份戏剧Sarkhollande《萨科-奥朗德》。 萨科齐是法国右翼前总统，奥兰德是法国左翼前总统。舞台上前总统尼古拉·萨科齐这个角色讲述自己一波三折的情史，表演与时任德国总理默克尔的通电话打情景，他问到 “2008年我拯救了银行。那是件好事吗？” 奥朗德则以小丑形象登场，演员模仿奥朗德那句著名的口头禅“我，作为总统……”（Me, as President）的语气，说：“我， 作为小丑……”正当他费力摆弄一张摇摇晃晃的桌子、甚至差点摔…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%B8%AF%E6%BE%B3%E5%8F%B0/20260706-%E9%99%86%E5%A6%87%E6%9D%A5%E6%B8%AF%E4%BA%A7%E5%AD%90%E5%A9%B4%E5%8F%98%E8%84%91%E7%98%AB-%E8%BF%BD%E8%B4%A316%E5%B9%B4%E7%BB%88%E5%BE%97%E8%BF%9F%E6%9D%A5%E5%85%AC%E4%B9%89-%E5%8C%BB%E7%94%9F%E8%A2%AB%E9%99%A4%E7%89%8C%E4%B9%9D%E4%B8%AA%E6%9C%88",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "陆妇来港产子婴变脑瘫 追责16年终得迟来公义 医生被除牌九个月 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%B8%AF%E6%BE%B3%E5%8F%B0/20260706-%E9%99%86%E5%A6%87%E6%9D%A5%E6%B8%AF%E4%BA%A7%E5%AD%90%E5%A9%B4%E5%8F%98%E8%84%91%E7%98%AB-%E8%BF%BD%E8%B4%A316%E5%B9%B4%E7%BB%88%E5%BE%97%E8%BF%9F%E6%9D%A5%E5%85%AC%E4%B9%89-%E5%8C%BB%E7%94%9F%E8%A2%AB%E9%99%A4%E7%89%8C%E4%B9%9D%E4%B8%AA%E6%9C%88",
    "pub_date": "2026-07-06 15:45:03",
    "author": "",
    "description": "06/07/2026 - 09:39 中国内地妇人16年前来香港产子，但婴儿出生三天後出院时，发现患上脑瘫，涉事夫妇向香港医务委员会(医委会)投诉，一直到昨(5日)早才获医委会裁定，涉事的儿科医生薜守智未有在男婴首次出现「新生儿癫痫」後立刻返回医院处理，属专业失当，且薛未有悔意，须立即除牌九个月。涉事夫妇认为这虽是迟来的公义，但惩处属恰当，日後会透过民事向医生及医疗机构索偿。 这宗迟来的公义差点无疾而终，因为事主黎远建脑在後翌年开始，他…",
    "content": "06/07/2026 - 09:39 中国内地妇人16年前来香港产子，但婴儿出生三天後出院时，发现患上脑瘫，涉事夫妇向香港医务委员会(医委会)投诉，一直到昨(5日)早才获医委会裁定，涉事的儿科医生薜守智未有在男婴首次出现「新生儿癫痫」後立刻返回医院处理，属专业失当，且薛未有悔意，须立即除牌九个月。涉事夫妇认为这虽是迟来的公义，但惩处属恰当，日後会透过民事向医生及医疗机构索偿。 这宗迟来的公义差点无疾而终，因为事主黎远建脑在後翌年开始，他的父母便已向负责医生注册和纪律规管事宜的医委会投诉，而平均处理投诉时间为27个月…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260706-%E9%87%91%E7%AE%A1%E5%B1%80-%E9%A6%99%E6%B8%AF%E5%B7%B2%E5%B0%86%E4%BA%BA%E6%B0%91%E5%B8%81%E5%B9%85%E5%B0%84%E8%87%B312%E5%9B%BD-%E6%9C%AA%E6%9D%A5%E6%95%B0%E5%91%A8%E6%8E%A8%E6%9B%B4%E5%A4%9A%E4%BA%BA%E5%B8%81%E5%9B%BD%E9%99%85%E5%8C%96%E6%8E%AA%E6%96%BD",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "金管局：香港已将人民币幅射至12国 未来数周推更多人币国际化措施 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260706-%E9%87%91%E7%AE%A1%E5%B1%80-%E9%A6%99%E6%B8%AF%E5%B7%B2%E5%B0%86%E4%BA%BA%E6%B0%91%E5%B8%81%E5%B9%85%E5%B0%84%E8%87%B312%E5%9B%BD-%E6%9C%AA%E6%9D%A5%E6%95%B0%E5%91%A8%E6%8E%A8%E6%9B%B4%E5%A4%9A%E4%BA%BA%E5%B8%81%E5%9B%BD%E9%99%85%E5%8C%96%E6%8E%AA%E6%96%BD",
    "pub_date": "2026-07-06 15:45:03",
    "author": "",
    "description": "06/07/2026 - 09:26 在人民币於全球国际支付中占比逐年下降丶而中国卻在「十五五」经济规划中声言要建设金融强国之际，香港这个全球最大的离岸人民币中心正努力协助人民币国际化「提速」。金融管理局总裁余伟文透露，该局已将人民币业务资金安排总额度倍增至 2000亿元人民币(折合约 258亿欧元)，并经香港的银行体系，联汇至12个不同国家及地区。预计未来数周，将会有更多关於人民币国际化和债券市场的措施推出。 但实际情况是，人民币在全…",
    "content": "06/07/2026 - 09:26 在人民币於全球国际支付中占比逐年下降丶而中国卻在「十五五」经济规划中声言要建设金融强国之际，香港这个全球最大的离岸人民币中心正努力协助人民币国际化「提速」。金融管理局总裁余伟文透露，该局已将人民币业务资金安排总额度倍增至 2000亿元人民币(折合约 258亿欧元)，并经香港的银行体系，联汇至12个不同国家及地区。预计未来数周，将会有更多关於人民币国际化和债券市场的措施推出。 但实际情况是，人民币在全球国际支付中的占比有所下降。根据环球银行金融电信协会(SWIFT)的数据，今年5…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/china/20260706/china-pacific-nuclear-missile-launch/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "中国在太平洋试射潜射弹道导弹，激怒邻国",
    "link": "https://cn.nytimes.com/china/20260706/china-pacific-nuclear-missile-launch/dual",
    "pub_date": "2026-07-06 15:36:03",
    "author": "",
    "description": "VICTORIA KIM, 储百亮2026年7月6日 China test fired an long-range ballistic missile with a dummy warhead in the Pacific Ocean on Monday, the first such launch in two years. 周一，中国在太平洋试射了一枚携载有模拟弹头的远程弹道导弹，这是两年来的首次此类发射。 The missile …",
    "content": "VICTORIA KIM, 储百亮 2026年7月6日 China test fired an long-range ballistic missile with a dummy warhead in the Pacific Ocean on Monday, the first such launch in two years. 周一，中国在太平洋试射了一枚携载有模拟弹头的远程弹道导弹，这是两年来的首次此类发射。 The missile was launched from a Chinese nuclear-pow…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/world/20260706/iran-funeral-khamenei-tehran/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "哈梅内伊葬礼中的德黑兰：告别、奇观与变局",
    "link": "https://cn.nytimes.com/world/20260706/iran-funeral-khamenei-tehran/dual",
    "pub_date": "2026-07-06 14:06:03",
    "author": "",
    "description": "ABDI LATIF DAHIR2026年7月6日周六，德黑兰市中心的人群站在一幅年轻时的阿亚图拉阿里·哈梅内伊画像下方。在这座首都的各个角落都能看到这位已故领导人的肖像。 Ayatollah Ali Khamenei, Iran’s slain supreme leader, had seemed immovable for decades, a man whose authority had become so deeply wov…",
    "content": "ABDI LATIF DAHIR 2026年7月6日 周六，德黑兰市中心的人群站在一幅年轻时的阿亚图拉阿里·哈梅内伊画像下方。在这座首都的各个角落都能看到这位已故领导人的肖像。 Ayatollah Ali Khamenei, Iran’s slain supreme leader, had seemed immovable for decades, a man whose authority had become so deeply woven into Iran’s political and religious…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/asia-pacific/20260706/australia-china-politics/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "中国驻澳大使批评澳洲情报机构针对中国",
    "link": "https://cn.nytimes.com/asia-pacific/20260706/australia-china-politics/dual",
    "pub_date": "2026-07-06 13:06:03",
    "author": "",
    "description": "VICTORIA KIM, 郭莉莉2026年7月6日6月，澳大利亚安全情报组织总干事迈克·伯吉斯在该机构堪培拉总部。他此前曾对澳大利亚面临的外国干涉发出了警告。 David Gray/Agence France-Presse — Getty Images Since resuscitating relations with China from a low point a few years ago, the Australian go…",
    "content": "VICTORIA KIM, 郭莉莉 2026年7月6日 6月，澳大利亚安全情报组织总干事迈克·伯吉斯在该机构堪培拉总部。他此前曾对澳大利亚面临的外国干涉发出了警告。 David Gray/Agence France-Presse — Getty Images Since resuscitating relations with China from a low point a few years ago, the Australian government has relied on an oft-repeated…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/china/20260706/ezra-jin-mingri-china-christian-xi-trump/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "特朗普斡旋下，中国地下教会牧师金明日获释",
    "link": "https://cn.nytimes.com/china/20260706/ezra-jin-mingri-china-christian-xi-trump/dual",
    "pub_date": "2026-07-06 11:06:02",
    "author": "",
    "description": "黄瑞黎2026年7月6日2018年，在北京锡安教会的金明日牧师。他是中国大规模打击宗教团体行动中被拘留的人士之一。 Ng Han Guan/Associated Press The pastor of a prominent underground church in China who was detained last year as part of a crackdown on religious activity was rel…",
    "content": "黄瑞黎 2026年7月6日 2018年，在北京锡安教会的金明日牧师。他是中国大规模打击宗教团体行动中被拘留的人士之一。 Ng Han Guan/Associated Press The pastor of a prominent underground church in China who was detained last year as part of a crackdown on religious activity was released on Friday, his daughter said, le…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/china/20260706/china-taiwan-east-coast-guard-patrols/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "中国扩大海上“执法巡查”范围，进一步向台湾施压",
    "link": "https://cn.nytimes.com/china/20260706/china-taiwan-east-coast-guard-patrols/dual",
    "pub_date": "2026-07-06 11:06:02",
    "author": "",
    "description": "储百亮2026年7月6日在中国东南部的厦门市海岸附近，可见一艘中国海警船。迄今为止，中国海警在台湾周边的巡逻主要集中在台湾与大陆之间的海峡。 Hector-Retamal-Agence-France-Presse-—-Getty-Images China is opening a new front in its pressure campaign against Taiwan, sending ships to its east to…",
    "content": "储百亮 2026年7月6日 在中国东南部的厦门市海岸附近，可见一艘中国海警船。迄今为止，中国海警在台湾周边的巡逻主要集中在台湾与大陆之间的海峡。 Hector-Retamal-Agence-France-Presse-—-Getty-Images China is opening a new front in its pressure campaign against Taiwan, sending ships to its east to drive home a political point: Beijing…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/china/20260706/china-ethnic-unity-tibetan-uyghurs/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "民族团结法引发广泛批评，中国强硬回击",
    "link": "https://cn.nytimes.com/china/20260706/china-ethnic-unity-tibetan-uyghurs/dual",
    "pub_date": "2026-07-06 10:36:06",
    "author": "",
    "description": "郭莉莉2026年7月6日中国最高领导人习近平在北京参加民族团结法表决。在习近平的领导下，中共对任何针对其少数民族政策的批评变得愈发不能容忍。 Tingshu Wang/Reuters With robots, publicity events and official speeches, China is mounting a propaganda effort to promote and defend a new “ethnic u…",
    "content": "郭莉莉 2026年7月6日 中国最高领导人习近平在北京参加民族团结法表决。在习近平的领导下，中共对任何针对其少数民族政策的批评变得愈发不能容忍。 Tingshu Wang/Reuters With robots, publicity events and official speeches, China is mounting a propaganda effort to promote and defend a new “ethnic unity” law that critics say will furthe…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/china/20260706/china-xi-leadership-cai-qi/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "习近平最倚重的副手蔡奇：总书记的“超级幕僚长”",
    "link": "https://cn.nytimes.com/china/20260706/china-xi-leadership-cai-qi/dual",
    "pub_date": "2026-07-06 09:36:02",
    "author": "",
    "description": "储百亮2026年7月6日蔡奇，中国领导人习近平备受信任的手下。他极可能是习近平核心圈子里最具影响力的官员。 Florence Lo/Reuters As China’s leader, Xi Jinping, forges toward a fourth term in power, he confronts a dilemma common to aging autocrats: testing and recruiting a ri…",
    "content": "储百亮 2026年7月6日 蔡奇，中国领导人习近平备受信任的手下。他极可能是习近平核心圈子里最具影响力的官员。 Florence Lo/Reuters As China’s leader, Xi Jinping, forges toward a fourth term in power, he confronts a dilemma common to aging autocrats: testing and recruiting a rising generation of loyal officials whi…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E7%BB%A7%E6%B3%95%E5%9B%BD%E6%91%A9%E6%B4%9B%E5%93%A5%E6%8C%AA%E5%A8%81%E4%B9%8B%E5%90%8E-%E8%B0%81%E8%BF%98%E6%A2%A6%E6%83%B3%E6%99%8B%E7%BA%A7%E5%85%AB%E5%BC%BA",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "继法国摩洛哥挪威之后 谁还梦想晋级八强 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E7%BB%A7%E6%B3%95%E5%9B%BD%E6%91%A9%E6%B4%9B%E5%93%A5%E6%8C%AA%E5%A8%81%E4%B9%8B%E5%90%8E-%E8%B0%81%E8%BF%98%E6%A2%A6%E6%83%B3%E6%99%8B%E7%BA%A7%E5%85%AB%E5%BC%BA",
    "pub_date": "2026-07-06 07:45:03",
    "author": "",
    "description": "06/07/2026 - 01:21 八分之一决赛正在如火如荼地在美加墨大地展开，周日晚巴西与挪威展开决战，出乎预料的是，巴西队败北，挪威历史性晋级八强。 我们先来展望一下谁还能晋级八强？周六，法国摩洛哥各自抢先赢得八强席位，然而，姆巴佩和他的队友刚刚摆脱巴拉圭陷阱，却要在在星期四遭遇摩洛哥。摩洛哥队3比0 横扫加拿大，势头正旺，曾在上届世界杯闯入半决赛，然而遭法国淘汰，这次法摩再度交锋，难免虎视眈眈，抱着复仇的决心。 法国队被迫与打法…",
    "content": "06/07/2026 - 01:21 八分之一决赛正在如火如荼地在美加墨大地展开，周日晚巴西与挪威展开决战，出乎预料的是，巴西队败北，挪威历史性晋级八强。 我们先来展望一下谁还能晋级八强？周六，法国摩洛哥各自抢先赢得八强席位，然而，姆巴佩和他的队友刚刚摆脱巴拉圭陷阱，却要在在星期四遭遇摩洛哥。摩洛哥队3比0 横扫加拿大，势头正旺，曾在上届世界杯闯入半决赛，然而遭法国淘汰，这次法摩再度交锋，难免虎视眈眈，抱着复仇的决心。 法国队被迫与打法过于粗野的巴拉圭队较量，面对这支侵略性强且决心搅乱比赛节奏的对手，备受赞誉的法兰…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E5%B7%B4%E8%A5%BF%E9%98%9F%E6%9C%AA%E8%83%BD%E6%89%93%E7%A0%B4%E9%AD%94%E5%92%92%E8%BE%93%E6%8C%AA%E5%A8%81-%E5%90%8E%E8%80%85%E5%8E%86%E5%8F%B2%E6%80%A7%E6%99%8B%E7%BA%A7%E4%B8%96%E7%95%8C%E6%9D%AF%E5%85%AB%E5%BC%BA",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "巴西队未能打破魔咒输挪威 后者历史性晋级世界杯八强 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E5%B7%B4%E8%A5%BF%E9%98%9F%E6%9C%AA%E8%83%BD%E6%89%93%E7%A0%B4%E9%AD%94%E5%92%92%E8%BE%93%E6%8C%AA%E5%A8%81-%E5%90%8E%E8%80%85%E5%8E%86%E5%8F%B2%E6%80%A7%E6%99%8B%E7%BA%A7%E4%B8%96%E7%95%8C%E6%9D%AF%E5%85%AB%E5%BC%BA",
    "pub_date": "2026-07-06 07:45:03",
    "author": "",
    "description": "06/07/2026 - 00:50 第三场八分之一决赛周日在巴西队与挪威队之间进行。表现稳健的挪威队凭借哈兰德在比赛尾声的两粒进球，以2比1淘汰巴西队历史性晋级世界杯八强。 这场比赛可谓双方旗鼓相当，一开始就争夺激烈，上半场互有攻势，第10分钟，巴西球员冲入挪威禁区，对方球员挡人被判犯规，巴西由吉马良斯罚点球，可惜错失良机，被表现神勇的挪威门将尼兰德扑出。 下半场前15分钟，巴西队频繁进攻，多次冲入挪威禁区，至少三次射球，构成威胁，但…",
    "content": "06/07/2026 - 00:50 第三场八分之一决赛周日在巴西队与挪威队之间进行。表现稳健的挪威队凭借哈兰德在比赛尾声的两粒进球，以2比1淘汰巴西队历史性晋级世界杯八强。 这场比赛可谓双方旗鼓相当，一开始就争夺激烈，上半场互有攻势，第10分钟，巴西球员冲入挪威禁区，对方球员挡人被判犯规，巴西由吉马良斯罚点球，可惜错失良机，被表现神勇的挪威门将尼兰德扑出。 下半场前15分钟，巴西队频繁进攻，多次冲入挪威禁区，至少三次射球，构成威胁，但都被挪威门将扑救。第60分钟后，挪威突然多次突入巴西禁区，有两球差点射入，但被巴…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/china/20260706/tibet-self-immolation-united-nations-china/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "西藏活动人士在纽约联合国总部外自焚身亡",
    "link": "https://cn.nytimes.com/china/20260706/tibet-self-immolation-united-nations-china/dual",
    "pub_date": "2026-07-06 07:36:03",
    "author": "",
    "description": "郭莉莉2026年7月6日周四傍晚，一名西藏活动人士在纽约联合国总部外点火自焚。他此前曾表示：“我这么做是为了西藏的独立，为了西藏的抗争。” Daniel Slim/Agence France-Presse — Getty Images A Tibetan activist lit himself on fire and outside of the United Nations headquarters in New York on T…",
    "content": "郭莉莉 2026年7月6日 周四傍晚，一名西藏活动人士在纽约联合国总部外点火自焚。他此前曾表示：“我这么做是为了西藏的独立，为了西藏的抗争。” Daniel Slim/Agence France-Presse — Getty Images A Tibetan activist lit himself on fire and outside of the United Nations headquarters in New York on Thursday to protest China’s control ove…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E9%9D%9E%E6%B4%B2/20260705-rfi%E6%B3%95%E5%B9%BF-%E5%B0%BC%E5%8F%A4%E6%8B%89-%E9%9D%9E%E6%B4%B2-%E5%8D%97%E9%9D%9E%E6%94%BF%E5%BA%9C%E4%B8%8A%E8%AF%89%E9%98%BB%E7%8A%80%E7%89%9B%E8%A7%92%E5%87%BA%E5%8F%A3%E5%A4%B1%E8%B4%A5",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "南非政府上诉阻犀牛角出口失败 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E9%9D%9E%E6%B4%B2/20260705-rfi%E6%B3%95%E5%B9%BF-%E5%B0%BC%E5%8F%A4%E6%8B%89-%E9%9D%9E%E6%B4%B2-%E5%8D%97%E9%9D%9E%E6%94%BF%E5%BA%9C%E4%B8%8A%E8%AF%89%E9%98%BB%E7%8A%80%E7%89%9B%E8%A7%92%E5%87%BA%E5%8F%A3%E5%A4%B1%E8%B4%A5",
    "pub_date": "2026-07-06 05:45:06",
    "author": "",
    "description": "05/07/2026 - 21:29 南非拥有全球绝大多数现存的犀牛。该国政府试图通过法律程序取消一个私人公园业主拥有的犀牛角出口许可。不过，北开普（Cap-Nord）省高等法院刚刚驳回了政府的这一上诉。本台法广非洲组（RFI Afrique）法文报道说，南非环境事务部保留向更高级别司法机关继续上诉的权利。 本台法广非洲组（RFI Afrique）2026年07月04日星期六的法文消息说，南非（Afrique du Sud）政府未能阻止…",
    "content": "05/07/2026 - 21:29 南非拥有全球绝大多数现存的犀牛。该国政府试图通过法律程序取消一个私人公园业主拥有的犀牛角出口许可。不过，北开普（Cap-Nord）省高等法院刚刚驳回了政府的这一上诉。本台法广非洲组（RFI Afrique）法文报道说，南非环境事务部保留向更高级别司法机关继续上诉的权利。 本台法广 非洲 组（RFI Afrique）2026年07月04日星期六的法文消息说， 南非 （ Afrique du Sud ）政府未能阻止犀牛角的出口。不过，依照《濒危野生动植物种国际贸易公约》（CITES…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E9%9D%9E%E6%B4%B2/20260705-rfi%E6%B3%95%E5%B9%BF-%E5%B0%BC%E5%8F%A4%E6%8B%89-%E9%9D%9E%E6%B4%B2-%E5%A1%9E%E5%86%85%E5%8A%A0%E5%B0%94%E6%80%BB%E7%BB%9F%E6%B3%95%E8%80%B6%E8%A6%81%E8%87%AA%E5%88%9B%E6%96%B0%E6%94%BF%E5%85%9A",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "塞内加尔总统法耶要自创新政党 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E9%9D%9E%E6%B4%B2/20260705-rfi%E6%B3%95%E5%B9%BF-%E5%B0%BC%E5%8F%A4%E6%8B%89-%E9%9D%9E%E6%B4%B2-%E5%A1%9E%E5%86%85%E5%8A%A0%E5%B0%94%E6%80%BB%E7%BB%9F%E6%B3%95%E8%80%B6%E8%A6%81%E8%87%AA%E5%88%9B%E6%96%B0%E6%94%BF%E5%85%9A",
    "pub_date": "2026-07-06 05:45:05",
    "author": "",
    "description": "05/07/2026 - 23:11 在塞内加尔，与议长松科（Ousmane Sonko）之间发生严重分歧的现总统法耶（président sénégalais Bassirou Diomaye Faye），面对在（Pastef）党内遭到孤立，宣布要自创一个新政党。本台法广非洲组（RFI Afrique）法语通讯员发回报道说，这一决定是塞内加尔国家元首于本周五，在总统府召集与其结盟的300多名塞内加尔市长们与会时宣布的。 据本台法广非洲…",
    "content": "05/07/2026 - 23:11 在塞内加尔，与议长松科（Ousmane Sonko）之间发生严重分歧的现总统法耶（président sénégalais Bassirou Diomaye Faye），面对在（Pastef）党内遭到孤立，宣布要自创一个新政党。本台法广非洲组（RFI Afrique）法语通讯员发回报道说，这一决定是塞内加尔国家元首于本周五，在总统府召集与其结盟的300多名塞内加尔市长们与会时宣布的。 据本台法广 非洲 组（RFI Afrique）今天（2026年07月05号星期日）更新的法文消…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E7%99%BD%E5%AE%AB-%E7%89%B9%E6%9C%97%E6%99%AE%E5%B0%86%E5%9C%A8%E5%8C%97%E7%BA%A6%E5%B3%B0%E4%BC%9A%E6%9C%9F%E9%97%B4%E4%BC%9A%E6%99%A4%E6%B3%BD%E8%BF%9E%E6%96%AF%E5%9F%BA%E5%92%8C%E5%8F%99%E5%88%A9%E4%BA%9A%E6%80%BB%E7%BB%9F",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "白宫：特朗普将在北约峰会期间会晤泽连斯基和叙利亚总统 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E7%99%BD%E5%AE%AB-%E7%89%B9%E6%9C%97%E6%99%AE%E5%B0%86%E5%9C%A8%E5%8C%97%E7%BA%A6%E5%B3%B0%E4%BC%9A%E6%9C%9F%E9%97%B4%E4%BC%9A%E6%99%A4%E6%B3%BD%E8%BF%9E%E6%96%AF%E5%9F%BA%E5%92%8C%E5%8F%99%E5%88%A9%E4%BA%9A%E6%80%BB%E7%BB%9F",
    "pub_date": "2026-07-06 05:45:05",
    "author": "",
    "description": "05/07/2026 - 23:38 美国白宫周日（7月5日）宣布，美国总统特朗普将于下周在土耳其安卡拉举行的北约峰会期间，分别与乌克兰总统泽连斯基和叙利亚总统艾哈迈德·沙拉举行双边会谈。 白宫副发言人安娜·凯利在电话记者会上表示，特朗普将于周三（7月8日）下午分别会见泽连斯基和沙拉。 一名美国高级官员表示，特朗普与泽连斯基会晤的主要目的是讨论如何结束乌克兰战争，他表示，“这是总统长期以来的优先事项”。这名不愿透露姓名的美国高级官员补充…",
    "content": "05/07/2026 - 23:38 美国白宫周日（7月5日）宣布，美国总统特朗普将于下周在土耳其安卡拉举行的北约峰会期间，分别与乌克兰总统泽连斯基和叙利亚总统艾哈迈德·沙拉举行双边会谈。 白宫副发言人安娜·凯利在电话记者会上表示，特朗普将于周三（7月8日）下午分别会见泽连斯基和沙拉。 一名美国高级官员表示，特朗普与泽连斯基会晤的主要目的是讨论如何结束乌克兰战争，他表示，“这是总统长期以来的优先事项”。这名不愿透露姓名的美国高级官员补充说，特朗普随后还将同俄罗斯总统普京进行沟通。 在美国独立250周年之际，普京和泽…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E5%8F%B0%E6%B9%BE%E5%86%9B%E6%96%B9%E6%81%A2%E5%A4%8D%E5%86%9B%E5%AE%98%E5%AD%A6%E6%A0%A1%E6%AF%95%E4%B8%9A%E7%94%9F-%E5%8F%8D%E5%85%B1%E7%88%B1%E5%9B%BD%E6%95%99%E8%82%B2-%E8%AF%BE%E7%A8%8B-%E5%BA%94%E5%AF%B9%E5%A4%A7%E9%99%86%E5%86%9B%E4%BA%8B%E5%8E%8B%E5%8A%9B",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "台湾军方恢复军官学校毕业生“反共爱国教育”课程 “应对大陆军事压力” - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E5%8F%B0%E6%B9%BE%E5%86%9B%E6%96%B9%E6%81%A2%E5%A4%8D%E5%86%9B%E5%AE%98%E5%AD%A6%E6%A0%A1%E6%AF%95%E4%B8%9A%E7%94%9F-%E5%8F%8D%E5%85%B1%E7%88%B1%E5%9B%BD%E6%95%99%E8%82%B2-%E8%AF%BE%E7%A8%8B-%E5%BA%94%E5%AF%B9%E5%A4%A7%E9%99%86%E5%86%9B%E4%BA%8B%E5%8E%8B%E5%8A%9B",
    "pub_date": "2026-07-06 05:45:05",
    "author": "",
    "description": "05/07/2026 - 23:32 台湾防务部门周日（7月5日）表示，在中断多年后，台湾军方今年恢复军官学校毕业生“反共爱国教育”课程，理由是来自中国大陆的军事威胁及渗透风险不断升高。台湾一名高级官员周日表示，大陆海军在第一岛链的活动进一步增加。 路透社报道，台湾防务部门表示，军官学校毕业生“反共爱国教育”课程曾于2006年更名为“爱国教育”，今年恢复使用“反共爱国教育”名称，以应对大陆日益增加的军事压力和渗透风险。声明称：“有必要让…",
    "content": "05/07/2026 - 23:32 台湾防务部门周日（7月5日）表示，在中断多年后，台湾军方今年恢复军官学校毕业生“反共爱国教育”课程，理由是来自中国大陆的军事威胁及渗透风险不断升高。台湾一名高级官员周日表示，大陆海军在第一岛链的活动进一步增加。 路透社报道，台湾防务部门表示，军官学校毕业生“反共爱国教育”课程曾于2006年更名为“爱国教育”，今年恢复使用“反共爱国教育”名称，以应对大陆日益增加的军事压力和渗透风险。声明称：“有必要让学员清楚认识国家安全威胁，理解军人的使命，即‘为何而战、为谁而战’。” 冷战时期…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E6%B3%95%E5%9B%BD%E6%8B%89%E5%88%A9%E5%85%8B%E5%8D%9A%E7%89%A9%E9%A6%86%E9%81%AD%E7%AA%83-%E6%95%B0%E7%99%BE%E4%B8%87%E6%AC%A7%E5%85%83%E7%8F%8D%E8%B4%B5%E9%A6%96%E9%A5%B0%E8%A2%AB%E7%9B%97",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "法国拉利克博物馆遭窃 数百万欧元珍贵首饰被盗 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E6%B3%95%E5%9B%BD%E6%8B%89%E5%88%A9%E5%85%8B%E5%8D%9A%E7%89%A9%E9%A6%86%E9%81%AD%E7%AA%83-%E6%95%B0%E7%99%BE%E4%B8%87%E6%AC%A7%E5%85%83%E7%8F%8D%E8%B4%B5%E9%A6%96%E9%A5%B0%E8%A2%AB%E7%9B%97",
    "pub_date": "2026-07-06 05:45:05",
    "author": "",
    "description": "05/07/2026 - 23:44 法国阿尔萨斯地区拉利克博物馆周日（7月5日）凌晨遭入室盗窃，馆内多件价值昂贵的首饰被盗，损失估计达数百万欧元。自2025年10月巴黎卢浮宫失窃案后，拉利克博物馆一直受到重点保护，但调查人员认为，现有安保措施仍不足以防范此次盗窃。 一名接近调查的消息人士想法新社表示：“约20件首饰被盗。损失金额仍在评估中，但可能达到数百万欧元，或接近400万欧元。” 拉利克博物馆位于下莱茵省温让-叙尔-莫代尔，专门收…",
    "content": "05/07/2026 - 23:44 法国阿尔萨斯地区拉利克博物馆周日（7月5日）凌晨遭入室盗窃，馆内多件价值昂贵的首饰被盗，损失估计达数百万欧元。自2025年10月巴黎卢浮宫失窃案后，拉利克博物馆一直受到重点保护，但调查人员认为，现有安保措施仍不足以防范此次盗窃。 一名接近调查的消息人士想法新社表示：“约20件首饰被盗。损失金额仍在评估中，但可能达到数百万欧元，或接近400万欧元。” 拉利克博物馆位于下莱茵省温让-叙尔-莫代尔，专门收藏和展示新艺术运动及装饰艺术时期珠宝与玻璃艺术大师勒内·拉利克（René Lal…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E6%B3%95%E5%9B%BD%E6%96%B0%E4%B8%80%E8%BD%AE%E9%AB%98%E6%B8%A9%E6%9D%A5%E8%A2%AD-16%E7%9C%81%E8%BF%9B%E5%85%A5%E6%A9%99%E8%89%B2%E9%AB%98%E6%B8%A9%E9%A2%84%E8%AD%A6-%E5%A4%9A%E5%9C%B0%E5%B1%B1%E7%81%AB%E6%8C%81%E7%BB%AD%E8%94%93%E5%BB%B6",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "法国新一轮高温来袭 16省进入橙色高温预警 多地山火持续蔓延 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E6%B3%95%E5%9B%BD%E6%96%B0%E4%B8%80%E8%BD%AE%E9%AB%98%E6%B8%A9%E6%9D%A5%E8%A2%AD-16%E7%9C%81%E8%BF%9B%E5%85%A5%E6%A9%99%E8%89%B2%E9%AB%98%E6%B8%A9%E9%A2%84%E8%AD%A6-%E5%A4%9A%E5%9C%B0%E5%B1%B1%E7%81%AB%E6%8C%81%E7%BB%AD%E8%94%93%E5%BB%B6",
    "pub_date": "2026-07-06 05:45:04",
    "author": "",
    "description": "05/07/2026 - 23:35 法国上一轮创纪录热浪刚刚结束，新一轮高温天气又接踵而至。法国气象局周日（7月5日）宣布，从7月6日中午起，全国进入橙色高温预警的省份将由7个增至16个，南部部分地区最高气温预计可达40摄氏度。与此同时，多地大型森林火灾仍在持续蔓延。 法国气象局周日预告，自周一中午起，夏朗德省、滨海夏朗德省、多尔多涅省、吉伦特省、朗德省、洛特省、洛特-加龙省、德塞夫勒省和旺代省将加入橙色高温预警行列，与法国南部此前已…",
    "content": "05/07/2026 - 23:35 法国上一轮创纪录热浪刚刚结束，新一轮高温天气又接踵而至。法国气象局周日（7月5日）宣布，从7月6日中午起，全国进入橙色高温预警的省份将由7个增至16个，南部部分地区最高气温预计可达40摄氏度。与此同时，多地大型森林火灾仍在持续蔓延。 法国气象局周日预告，自周一中午起，夏朗德省、滨海夏朗德省、多尔多涅省、吉伦特省、朗德省、洛特省、洛特-加龙省、德塞夫勒省和旺代省将加入橙色高温预警行列，与法国南部此前已处于预警状态的7个省份共同进入警戒。 在已经发布橙色预警的7个省，5日最高气温预…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E4%B8%96%E7%95%8C%E6%9D%AF-%E5%9B%BD%E9%99%85%E8%B6%B3%E8%81%94%E6%92%A4%E9%94%80%E7%BE%8E%E5%9B%BD%E5%89%8D%E9%94%8B%E5%B7%B4%E6%B4%9B%E8%B4%A1%E8%87%AA%E5%8A%A8%E5%81%9C%E8%B5%9B-%E7%89%B9%E6%9C%97%E6%99%AE%E8%87%B4%E8%B0%A2-%E6%AF%94%E5%88%A9%E6%97%B6%E8%B6%B3%E5%8D%8F%E8%A1%A8%E7%A4%BA%E9%9C%87%E6%83%8A",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "世界杯：国际足联撤销美国前锋巴洛贡自动停赛 特朗普致谢 比利时足协表示震惊 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E4%B8%96%E7%95%8C%E6%9D%AF-%E5%9B%BD%E9%99%85%E8%B6%B3%E8%81%94%E6%92%A4%E9%94%80%E7%BE%8E%E5%9B%BD%E5%89%8D%E9%94%8B%E5%B7%B4%E6%B4%9B%E8%B4%A1%E8%87%AA%E5%8A%A8%E5%81%9C%E8%B5%9B-%E7%89%B9%E6%9C%97%E6%99%AE%E8%87%B4%E8%B0%A2-%E6%AF%94%E5%88%A9%E6%97%B6%E8%B6%B3%E5%8D%8F%E8%A1%A8%E7%A4%BA%E9%9C%87%E6%83%8A",
    "pub_date": "2026-07-06 05:45:03",
    "author": "",
    "description": "05/07/2026 - 23:29 国际足联（FIFA）纪律委员会决定撤销美国前锋弗拉林·巴洛贡的自动停赛处罚，使其得以出战7月6日世界杯十六强对阵比利时的比赛。美国总统特朗普对此公开表示感谢，而比利时足协则称这一决定“令人震惊”。《纽约时报》披露，特朗普早在国际足联改判前数日，就曾亲自致电国际足联主席因凡蒂诺，要求重新审查巴洛贡的停赛决定。 巴洛贡在7月1日美国队2比0战胜波黑队的十六分之一决赛中，因踩踏波黑后卫塔里克·穆哈雷莫维奇…",
    "content": "05/07/2026 - 23:29 国际足联（FIFA）纪律委员会决定撤销美国前锋弗拉林·巴洛贡的自动停赛处罚，使其得以出战7月6日世界杯十六强对阵比利时的比赛。美国总统特朗普对此公开表示感谢，而比利时足协则称这一决定“令人震惊”。《纽约时报》披露，特朗普早在国际足联改判前数日，就曾亲自致电国际足联主席因凡蒂诺，要求重新审查巴洛贡的停赛决定。 巴洛贡在7月1日美国队2比0战胜波黑队的十六分之一决赛中，因踩踏波黑后卫塔里克·穆哈雷莫维奇腿部，被主裁判直接出示红牌罚下。 按照国际足联纪律规定，球员被红牌罚下后将自动停…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E6%AC%A7%E6%B4%B2/20260705-%E5%BE%B7%E5%9B%BD%E9%80%89%E9%A1%B9%E5%85%9A%E5%AF%BB%E6%B1%82%E6%89%A7%E6%8E%8C%E6%94%BF%E6%9D%83",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "德国选项党寻求执掌政权 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E6%AC%A7%E6%B4%B2/20260705-%E5%BE%B7%E5%9B%BD%E9%80%89%E9%A1%B9%E5%85%9A%E5%AF%BB%E6%B1%82%E6%89%A7%E6%8E%8C%E6%94%BF%E6%9D%83",
    "pub_date": "2026-07-06 04:15:03",
    "author": "",
    "description": "05/07/2026 - 21:58 据德国电视一台和德国广播电台报道，德国选项党（AfD）在埃尔福特举行的为期两天的联邦党代表大会于周日结束。选项党两位联邦主席蒂诺·赫鲁帕拉和爱丽丝·魏德尔均于周六再次当选联合党主席。大会最后通过了多项党章修改。联合主席赫鲁帕拉表示，目前工作的重点是即将举行的州议会选举，选项党必须摆脱反对党的地位。 联合党主席爱丽丝·魏德尔也表示，党的目标是执掌政府。9月，萨克森-安哈尔特州、梅克伦堡-前波美拉尼亚州…",
    "content": "05/07/2026 - 21:58 据德国电视一台和德国广播电台报道，德国选项党（AfD）在埃尔福特举行的为期两天的联邦党代表大会于周日结束。选项党两位联邦主席蒂诺·赫鲁帕拉和爱丽丝·魏德尔均于周六再次当选联合党主席。大会最后通过了多项党章修改。联合主席赫鲁帕拉表示，目前工作的重点是即将举行的州议会选举，选项党必须摆脱反对党的地位。 联合党主席爱丽丝·魏德尔也表示，党的目标是执掌政府。9月，萨克森-安哈尔特州、梅克伦堡-前波美拉尼亚州和柏林将举行州议会选举。据媒体估测，选项党有望在萨安州和梅前州州议会选举中成为最…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E7%BE%8E%E5%86%9B%E7%BB%93%E6%9D%9F%E9%98%BF%E6%8B%89%E4%BC%AF%E6%B5%B7%E5%A4%B1%E8%B8%AA%E6%9C%BA%E7%BB%84%E4%BA%BA%E5%91%98%E6%90%9C%E6%95%91%E8%A1%8C%E5%8A%A8",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "美军结束阿拉伯海失踪机组人员搜救行动 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E4%B8%AD%E5%9B%BD/20260705-%E7%BE%8E%E5%86%9B%E7%BB%93%E6%9D%9F%E9%98%BF%E6%8B%89%E4%BC%AF%E6%B5%B7%E5%A4%B1%E8%B8%AA%E6%9C%BA%E7%BB%84%E4%BA%BA%E5%91%98%E6%90%9C%E6%95%91%E8%A1%8C%E5%8A%A8",
    "pub_date": "2026-07-06 04:15:03",
    "author": "",
    "description": "05/07/2026 - 21:58 美国海军5日宣布，正式结束在阿拉伯海针对一名失踪机组人员的搜救行动。 这名机组人员日前搭乘一架MH-60S“海鹰直升机执行任务期间，因突发状况迫降海面后失踪。美军表示，搜救行动历时超过102小时，搜索范围超过1万4000平方英里，但最终仍未能找到失踪人员。 美国海军第五舰队发表声明指出，搜救行动由美国海军与美国空军共同执行，涵盖美军中央司令部责任区域，并于美东时间5日上午8时正式停止主动搜救。 美军…",
    "content": "05/07/2026 - 21:58 美国海军5日宣布，正式结束在阿拉伯海针对一名失踪机组人员的搜救行动。 这名机组人员日前搭乘一架MH-60S“海鹰直升机执行任务期间，因突发状况迫降海面后失踪。美军表示，搜救行动历时超过102小时，搜索范围超过1万4000平方英里，但最终仍未能找到失踪人员。 美国海军第五舰队发表声明指出，搜救行动由美国海军与美国空军共同执行，涵盖美军中央司令部责任区域，并于美东时间5日上午8时正式停止主动搜救。 美军在声明中表示：“在美国海军与美国空军于美军中央司令部责任区内展开广泛搜索后，搜救…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-%E5%8C%97%E7%BA%A6%E5%B3%B0%E4%BC%9A%E5%89%8D%EF%BC%8C%E6%B3%BD%E8%BF%9E%E6%96%AF%E5%9F%BA%E5%92%8C%E6%99%AE%E4%BA%AC%E9%83%BD%E5%9C%A8%E7%BE%8E%E5%9B%BD%E7%8B%AC%E7%AB%8B250%E5%91%A8%E5%B9%B4%E8%87%B4%E7%94%B5%E7%89%B9%E6%9C%97%E6%99%AE",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "北约峰会前:泽连斯基和普京都在美国独立250周年致电特朗普 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-%E5%8C%97%E7%BA%A6%E5%B3%B0%E4%BC%9A%E5%89%8D%EF%BC%8C%E6%B3%BD%E8%BF%9E%E6%96%AF%E5%9F%BA%E5%92%8C%E6%99%AE%E4%BA%AC%E9%83%BD%E5%9C%A8%E7%BE%8E%E5%9B%BD%E7%8B%AC%E7%AB%8B250%E5%91%A8%E5%B9%B4%E8%87%B4%E7%94%B5%E7%89%B9%E6%9C%97%E6%99%AE",
    "pub_date": "2026-07-06 02:45:03",
    "author": "",
    "description": "05/07/2026 - 19:50 基辅周六晚宣布，泽连斯基在美国独立宣言纪念日与特朗普进行了电话交谈。克里姆林宫周日宣布，普京与特朗普就乌克兰问题及国际事务进行了电话交谈。 泽连斯基-特朗普 法新社说，周六晚间，基辅方面宣布，乌克兰总统沃洛迪米尔·泽连斯基与唐纳德·特朗普进行了电话交谈。 泽连斯基总统在社交媒体上表示，“特朗普总统和我讨论了前线当前局势以及我们的外交努力”。他并说，“结束这场战争确实存在希望，而美国的决心至关重要”。…",
    "content": "05/07/2026 - 19:50 基辅周六晚宣布，泽连斯基在美国独立宣言纪念日与特朗普进行了电话交谈。克里姆林宫周日宣布，普京与特朗普就乌克兰问题及国际事务进行了电话交谈。 泽连斯基-特朗普 法新社说，周六晚间，基辅方面宣布，乌克兰总统沃洛迪米尔·泽连斯基与唐纳德·特朗普进行了电话交谈。 泽连斯基总统在社交媒体上表示，“特朗普总统和我讨论了前线当前局势以及我们的外交努力”。他并说，“结束这场战争确实存在希望，而美国的决心至关重要”。 他接着说：“我们商定将在安卡拉举行的北约峰会上继续这些讨论”。 包括唐纳德·特…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-2026%E4%B8%96%E7%95%8C%E6%9D%AF-%E6%B3%95%E5%9B%BD%E5%AF%B9%E9%98%B5%E5%B7%B4%E6%8B%89%E5%9C%AD%E8%B5%9B%E5%90%8E-%E8%A3%81%E5%88%A4%E6%88%90%E4%B8%BA%E4%BA%89%E8%AE%AE%E7%84%A6%E7%82%B9",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "2026世界杯：法国对阵巴拉圭赛后 裁判成为争议焦点 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-2026%E4%B8%96%E7%95%8C%E6%9D%AF-%E6%B3%95%E5%9B%BD%E5%AF%B9%E9%98%B5%E5%B7%B4%E6%8B%89%E5%9C%AD%E8%B5%9B%E5%90%8E-%E8%A3%81%E5%88%A4%E6%88%90%E4%B8%BA%E4%BA%89%E8%AE%AE%E7%84%A6%E7%82%B9",
    "pub_date": "2026-07-06 01:45:03",
    "author": "",
    "description": "05/07/2026 - 19:18 周六，法国队以1比0战胜了作风极其粗野的巴拉圭队，成功晋级世界杯八强。然而，乌兹别克斯坦籍裁判伊尔吉兹·坦塔舍夫（Ilgiz Tantashev）对南美球员大量犯规的反竞技行为表现出的宽容态度，在周日引发了广泛争议。 法新社周六的报道说，在费城的这场支离破碎、气氛极其紧张的比赛中，法国队凭借基利安·姆巴佩在第70分钟通过德西雷·杜埃（Désiré Doué）制造的点球，成功逃离了巴拉圭队的陷阱。 而…",
    "content": "05/07/2026 - 19:18 周六，法国队以1比0战胜了作风极其粗野的巴拉圭队，成功晋级世界杯八强。然而，乌兹别克斯坦籍裁判伊尔吉兹·坦塔舍夫（Ilgiz Tantashev）对南美球员大量犯规的反竞技行为表现出的宽容态度，在周日引发了广泛争议。 法新社周六的报道说，在费城的这场支离破碎、气氛极其紧张的比赛中，法国队凭借基利安·姆巴佩在第70分钟通过德西雷·杜埃（Désiré Doué）制造的点球，成功逃离了巴拉圭队的陷阱。 而这个点球，是裁判坦塔舍夫先生在巴拉圭13次犯规中，唯一判罚的一次。这个数字少得可…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-2026%E4%B8%96%E7%95%8C%E6%9D%AF-%E6%B3%95%E5%9B%BD%E9%98%9F%E5%B1%95%E7%8E%B0%E4%BA%86%E4%BB%96%E4%BB%AC%E8%83%BD%E8%B8%A2%E5%8F%A6%E4%B8%80%E7%A7%8D%E8%B6%B3%E7%90%83",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "2026世界杯：法国队展现了他们能踢另一种足球 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-2026%E4%B8%96%E7%95%8C%E6%9D%AF-%E6%B3%95%E5%9B%BD%E9%98%9F%E5%B1%95%E7%8E%B0%E4%BA%86%E4%BB%96%E4%BB%AC%E8%83%BD%E8%B8%A2%E5%8F%A6%E4%B8%80%E7%A7%8D%E8%B6%B3%E7%90%83",
    "pub_date": "2026-07-05 23:45:03",
    "author": "",
    "description": "05/07/2026 - 17:24 路透社说，自本届世界杯开赛以来，法国队在进攻端表现令人惊叹。而在周六八分之一决赛以1-0淘汰巴拉圭队的比赛中，他们展现出不同的品质，这场胜利或许将成为球队在本届赛事后续征程中的奠基之作。 在周六与巴拉圭比赛之前，法国队在世界杯赛场上火力全开，在前四场比赛中每场至少攻入三球。但周六在费城，他们遭遇了巴拉圭队严密的防守布阵，以及对方有时游走在犯规边缘的粗野拼抢。 左边锋布拉德利·巴尔科拉（Bradley…",
    "content": "05/07/2026 - 17:24 路透社说，自本届世界杯开赛以来，法国队在进攻端表现令人惊叹。而在周六八分之一决赛以1-0淘汰巴拉圭队的比赛中，他们展现出不同的品质，这场胜利或许将成为球队在本届赛事后续征程中的奠基之作。 在周六与巴拉圭比赛之前，法国队在世界杯赛场上火力全开，在前四场比赛中每场至少攻入三球。但周六在费城，他们遭遇了巴拉圭队严密的防守布阵，以及对方有时游走在犯规边缘的粗野拼抢。 左边锋布拉德利·巴尔科拉（Bradley Barcola）在混采区解释道：“我从未踢过这样一场比赛，充满了暗算和背后推搡…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-%E4%B8%AD%E5%9B%BD%E5%AE%A3%E5%B8%83%E5%B0%86%E4%BA%8E7%E6%9C%88%E4%B8%8E%E4%BF%84%E7%BD%97%E6%96%AF%E4%B8%BE%E8%A1%8C%E6%B5%B7%E5%86%9B%E8%81%94%E5%90%88%E6%BC%94%E4%B9%A0",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "中国宣布将于7月与俄罗斯举行海军联合演习 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-%E4%B8%AD%E5%9B%BD%E5%AE%A3%E5%B8%83%E5%B0%86%E4%BA%8E7%E6%9C%88%E4%B8%8E%E4%BF%84%E7%BD%97%E6%96%AF%E4%B8%BE%E8%A1%8C%E6%B5%B7%E5%86%9B%E8%81%94%E5%90%88%E6%BC%94%E4%B9%A0",
    "pub_date": "2026-07-05 23:15:03",
    "author": "",
    "description": "05/07/2026 - 16:55 中国周日宣布，将于7月与俄罗斯举行年度联合海军演习，此次演习将首先在中国近海举行，然后在太平洋一个未指明海域进行联合巡逻。 中俄两国是重要的外交和经济伙伴，双方共同致力于提供一种替代方案，要取代他们认为的美国对世界秩序的霸权。 法新社说，多年来，中俄一直举行联合军事演习，但在乌克兰战争背景下，包括西方国家在内的许多国家如今对此投以怀疑的目光。 中国国防部表示，两国海军将在“青岛近海的空域和海域”举行…",
    "content": "05/07/2026 - 16:55 中国周日宣布，将于7月与俄罗斯举行年度联合海军演习，此次演习将首先在中国近海举行，然后在太平洋一个未指明海域进行联合巡逻。 中俄两国是重要的外交和经济伙伴，双方共同致力于提供一种替代方案，要取代他们认为的美国对世界秩序的霸权。 法新社说，多年来，中俄一直举行联合军事演习，但在乌克兰战争背景下，包括西方国家在内的许多国家如今对此投以怀疑的目光。 中国国防部表示，两国海军将在“青岛近海的空域和海域”举行“海上联合-2026”演习。 该部在一份声明中强调：“此次联合演习结束后，两国部…"
  },
  {
    "id": "国外-RFI 法国国际广播电台-https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-%E7%8E%8B%E6%AF%85%E8%AE%BF%E7%91%9E%E5%85%B8-10%E5%B9%B4%E5%89%8D%E8%A2%AB%E4%B8%AD%E5%9B%BD%E7%BB%91%E6%9E%B6%E7%9B%91%E7%A6%81%E7%9A%84%E5%87%BA%E7%89%88%E5%95%86%E6%A1%82%E6%95%8F%E6%B5%B7%E4%BB%8D%E6%B4%BB%E7%9D%80%E4%B8%94%E8%BA%AB%E4%BD%93%E5%81%A5%E5%BA%B7",
    "feed_name": "RFI 法国国际广播电台",
    "category": "国外",
    "title": "王毅访瑞典:10年前被中国绑架监禁的出版商桂敏海仍活着且身体健康 - RFI - 法国国际广播电台",
    "link": "https://www.rfi.fr/cn/%E5%9B%BD%E9%99%85/20260705-%E7%8E%8B%E6%AF%85%E8%AE%BF%E7%91%9E%E5%85%B8-10%E5%B9%B4%E5%89%8D%E8%A2%AB%E4%B8%AD%E5%9B%BD%E7%BB%91%E6%9E%B6%E7%9B%91%E7%A6%81%E7%9A%84%E5%87%BA%E7%89%88%E5%95%86%E6%A1%82%E6%95%8F%E6%B5%B7%E4%BB%8D%E6%B4%BB%E7%9D%80%E4%B8%94%E8%BA%AB%E4%BD%93%E5%81%A5%E5%BA%B7",
    "pub_date": "2026-07-05 21:45:02",
    "author": "",
    "description": "05/07/2026 - 15:40 中国外长王毅到访斯德哥尔摩。瑞典外交大臣说，她从中国外长王毅得知，十年前中国绑架监禁的出版商桂敏海仍然活着且身体健康。 据瑞典公共电视台svt周六报道，中国外长王毅此次访问瑞典，将举行双边会晤，预计讨论欧盟与中国之间的贸易关系等议题。瑞典首相克里斯特松也将出席此次会晤。 周六近中午，瑞典外交大臣玛丽亚·斯滕纳加德在斯德哥尔摩接待了中国外长王毅。 周六下午，这位瑞典外交大臣告诉媒体，她已向中国外长提出…",
    "content": "05/07/2026 - 15:40 中国外长王毅到访斯德哥尔摩。瑞典外交大臣说，她从中国外长王毅得知，十年前中国绑架监禁的出版商桂敏海仍然活着且身体健康。 据瑞典公共电视台svt周六报道，中国外长王毅此次访问瑞典，将举行双边会晤，预计讨论欧盟与中国之间的贸易关系等议题。瑞典首相克里斯特松也将出席此次会晤。 周六近中午，瑞典外交大臣玛丽亚·斯滕纳加德在斯德哥尔摩接待了中国外长王毅。 周六下午，这位瑞典外交大臣告诉媒体，她已向中国外长提出要求必须释放瑞典公民桂民海。她表示，王毅在会谈中告知，目前这位被羁押的出版商兼作…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/culture/20260703/what-is-the-definitive-movie-about-america/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "哪部电影最能代表美国？",
    "link": "https://cn.nytimes.com/culture/20260703/what-is-the-definitive-movie-about-america/dual",
    "pub_date": "2026-07-03 14:36:02",
    "author": "",
    "description": "《纽约时报》2026年7月3日 Paramount Vantage How the world sees America, and how the country sees itself, can be credited, at least in part, to Hollywood. For as long as movies have been around, they have reinforced the stories we …",
    "content": "《纽约时报》 2026年7月3日 Paramount Vantage How the world sees America, and how the country sees itself, can be credited, at least in part, to Hollywood. For as long as movies have been around, they have reinforced the stories we tell ourselves about our national chara…"
  },
  {
    "id": "国外-纽约时报双语版-https://cn.nytimes.com/health/20260703/healthy-eating-advice-2026/dual",
    "feed_name": "纽约时报双语版",
    "category": "国外",
    "title": "2026年上半年最佳健康饮食建议",
    "link": "https://cn.nytimes.com/health/20260703/healthy-eating-advice-2026/dual",
    "pub_date": "2026-07-03 13:36:03",
    "author": "",
    "description": "AMANDA SCHUPAK2026年7月3日 Nada Hayek As a nutrition reporter, healthy eating is my bread and butter (pardon the pun). I spend a lot of time dissecting the latest nutrition news, studies and trends, and asking experts for g…",
    "content": "AMANDA SCHUPAK 2026年7月3日 Nada Hayek As a nutrition reporter, healthy eating is my bread and butter (pardon the pun). I spend a lot of time dissecting the latest nutrition news, studies and trends, and asking experts for guidance on what to eat and why. 作为一名报道营…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c4gy88jye51o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國能否透過《民族團結進步促進法》針對海外批評者？",
    "link": "https://www.bbc.com/zhongwen/articles/c4gy88jye51o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-07-01 20:14:25",
    "author": "",
    "description": "Getty Images / 居于海外的中国政府批评者担心这项新法律会对他们带来影响 23岁的张雅笛，又名Tara，原本应在英国一所著名大学就读。 然而，外界相信，她现正被关押于中国。 她于社交平台X的其中一则最后的发文中，她祝愿达赖喇嘛90岁生日快乐。她在法国求学期间，曾经协助一个促进西藏人权的中文网上平台进行编辑工作。 她在海外发表支持西藏人的言论，被认为是导致她入狱的原因。 北京将这位流亡精神领袖视为分裂分子，并认为其于1950年…",
    "content": "Getty Images / 居于海外的中国政府批评者担心这项新法律会对他们带来影响 23岁的张雅笛，又名Tara，原本应在英国一所著名大学就读。 然而，外界相信，她现正被关押于中国。 她于社交平台X的其中一则最后的发文中，她祝愿达赖喇嘛90岁生日快乐。她在法国求学期间，曾经协助一个促进西藏人权的中文网上平台进行编辑工作。 她在海外发表支持西藏人的言论，被认为是导致她入狱的原因。 北京将这位流亡精神领袖视为分裂分子，并认为其于1950年并入的西藏自治区是中国领土不可分割的一部分。 据报道，张雅笛于去年7月到访中国云…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c621ggjkyd0o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "主權移交29年：香港政府首次同日舉辦「中共建黨」慶典的解讀",
    "link": "https://www.bbc.com/zhongwen/articles/c621ggjkyd0o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-07-01 18:12:48",
    "author": "",
    "description": "Getty Images / 港府与中联办合办“庆祝中国共产党成立105周年活动啓动仪式”，出席者包括：行政长官李家超、中联办主任周霁、全国政协副主席梁振英，以及解放军、国安公署及中国外交部代表等。 7月1日是香港主权移交纪念日，也是中国共产党建党日。 以往在“一国两制”下，香港政府不会在这天同时庆祝中共党庆，今年却打破禁忌——港府在特区庆祝活动后，与中联办合办“中共建党”活动，并播放中共中央总书记习近平演讲。 这种两个庆典紧接而来的安…",
    "content": "Getty Images / 港府与中联办合办“庆祝中国共产党成立105周年活动啓动仪式”，出席者包括：行政长官李家超、中联办主任周霁、全国政协副主席梁振英，以及解放军、国安公署及中国外交部代表等。 7月1日是香港主权移交纪念日，也是中国共产党建党日。 以往在“一国两制”下，香港政府不会在这天同时庆祝中共党庆，今年却打破禁忌——港府在特区庆祝活动后，与中联办合办“中共建党”活动，并播放中共中央总书记习近平演讲。 这种两个庆典紧接而来的安排，是历来首次。 回顾五年前中共百年党庆时，港府也曾破例举办大型展览、刊登广告及…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cj4gz0zw5y4o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "台灣海巡官員如何從神明信仰汲取力量？",
    "link": "https://www.bbc.com/zhongwen/articles/cj4gz0zw5y4o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-07-01 17:54:41",
    "author": "",
    "description": "Reuters / 台湾海巡官员如何从神明信仰汲取力量？ 面对中国威胁升高，台湾有海巡官员从神明信仰中汲取力量。 叶志盛是一艘2,400吨级巡防舰的大副，驻守于澎湖群岛，也是台湾海上防线的一员。他经常面对中国海警与海军在台湾周边海域的活动。中方称这些行动是为维护其对台湾的主权主张。 执勤之外，他还是澎湖一间供奉“五府千岁”庙宇的法师助理。五府千岁长年受到沿海居民信奉，被视为保佑航海平安、驱除瘟疫的守护神。",
    "content": "Reuters / 台湾海巡官员如何从神明信仰汲取力量？ 面对中国威胁升高，台湾有海巡官员从神明信仰中汲取力量。 叶志盛是一艘2,400吨级巡防舰的大副，驻守于澎湖群岛，也是台湾海上防线的一员。他经常面对中国海警与海军在台湾周边海域的活动。中方称这些行动是为维护其对台湾的主权主张。 执勤之外，他还是澎湖一间供奉“五府千岁”庙宇的法师助理。五府千岁长年受到沿海居民信奉，被视为保佑航海平安、驱除瘟疫的守护神。"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cdejxrxn904o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "兩岸旅遊融冰了？金門人如何看待上海遊客開放",
    "link": "https://www.bbc.com/zhongwen/articles/cdejxrxn904o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-07-01 17:13:31",
    "author": "",
    "description": "BBC CHINESE/LEE LOK / 六月初，有上海旅客开始尝试前往金门旅游，当地商家与旅宿业者看见新的契机。 今年4月底，两岸旅游迎来新发展，中国官方公告上海市文旅局正式落实居民赴金门、马祖旅游的申请安排，是继两年前开放福建旅客后的进一步放宽措施。 这项让金门商家和旅游业者感到振奋的政策，却引发困惑——过了两个月，许多商家和旅宿业者仍未接待过第一位上海旅客。 “我原本认为，一开放（上海）应该会很多人来申请，结果发现不是那么一回事…",
    "content": "BBC CHINESE/LEE LOK / 六月初，有上海旅客开始尝试前往金门旅游，当地商家与旅宿业者看见新的契机。 今年4月底，两岸旅游迎来新发展，中国官方公告上海市文旅局正式落实居民赴金门、马祖旅游的申请安排，是继两年前开放福建旅客后的进一步放宽措施。 这项让金门商家和旅游业者感到振奋的政策，却引发困惑——过了两个月，许多商家和旅宿业者仍未接待过第一位上海旅客。 “我原本认为，一开放（上海）应该会很多人来申请，结果发现不是那么一回事。”金门酒厂总经理王中圣对BBC中文说。 多名金门商家与旅宿业者都表示，与前年开…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ce8j2r4rnpro/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "特朗普加密幣賺逾10億美元 他還有哪些額外收入",
    "link": "https://www.bbc.com/zhongwen/articles/ce8j2r4rnpro/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-07-01 14:10:52",
    "author": "",
    "description": "Reuters / 二度入主白宫的特朗普背后有着庞大的家族生意。 根据美国总统唐纳德·特朗普（Donald Trump；川普）2025年的法定财务申报文件，他去年透过加密货币相关商业交易获利超过10亿美元（67.9亿元人民币；318.4亿元新台币）。 在这份长达927页的申报文件中，他申报从“特朗普迷因币”（Trump meme coin）获得6.35亿美元的特许权收益。这种加密货币在他就职前数日推出后，价值已大幅下跌。 他还申报从世界…",
    "content": "Reuters / 二度入主白宫的特朗普背后有着庞大的家族生意。 根据美国总统唐纳德·特朗普（Donald Trump；川普）2025年的法定财务申报文件，他去年透过加密货币相关商业交易获利超过10亿美元（67.9亿元人民币；318.4亿元新台币）。 在这份长达927页的申报文件中，他申报从“特朗普迷因币”（Trump meme coin）获得6.35亿美元的特许权收益。这种加密货币在他就职前数日推出后，价值已大幅下跌。 他还申报从世界自由金融（World Liberty Financial）获得超过5亿美元收入。…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cdej4ggn490o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "美國最高法院維持「出生公民權」，重挫特朗普但令其擴權",
    "link": "https://www.bbc.com/zhongwen/articles/cdej4ggn490o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-07-01 12:32:57",
    "author": "",
    "description": "BBC / 观看：BBC记者加里·奥多诺霍（Gary O'Donoghue）称，最高法院关于“出生公民权”的裁决对特朗普构成重大打击（英语影片） 美国最高法院裁定，在美国出生的婴儿依宪法享有公民权，驳回了特朗普（Donald Trump，川普）终止这项已有150年历史的政策的企图。 在一项6比3的裁决中，首席大法官约翰·罗伯茨（John Roberts）裁定，根据宪法第14修正案，在美国出生、“其父母为非法或暂时在境内居留”的儿童，自“…",
    "content": "BBC / 观看：BBC记者加里·奥多诺霍（Gary O'Donoghue）称，最高法院关于“出生公民权”的裁决对特朗普构成重大打击（英语影片） 美国最高法院裁定，在美国出生的婴儿依宪法享有公民权，驳回了特朗普（Donald Trump，川普）终止这项已有150年历史的政策的企图。 在一项6比3的裁决中，首席大法官约翰·罗伯茨（John Roberts）裁定，根据宪法第14修正案，在美国出生、“其父母为非法或暂时在境内居留”的儿童，自“出生起即成为公民”。 特朗普总统曾试图透过行政命令限制这项权利，主张无证移民及一…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c4gyrgqypwlo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國現象級遊戲「引狼入室」：《戀與深空》如何觸發玩家抵制",
    "link": "https://www.bbc.com/zhongwen/articles/c4gyrgqypwlo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-07-01 08:37:08",
    "author": "",
    "description": "Getty Images / 女性面向游戏《恋与深空》在两岸四地及海外共有超过8000万玩家。 “我哭了三天，没法睡觉没法吃饭，今天还要被迫上班，”今年35岁在深圳工作的卢女士在中国著名乙女向恋爱游戏《恋与深空》发布新角色视频后感到“绝望又崩溃”，她表示这个游戏曾给自己多少安全和幸福，如今感到的痛苦就有多少同样数值。 《恋与深空》在近期上线新角色，由于发布视频里反复套用威胁女性安全语句，比如“不要在锅里洗澡”、以及“引狼入室有什么不好？…",
    "content": "Getty Images / 女性面向游戏《恋与深空》在两岸四地及海外共有超过8000万玩家。 “我哭了三天，没法睡觉没法吃饭，今天还要被迫上班，”今年35岁在深圳工作的卢女士在中国著名乙女向恋爱游戏《恋与深空》发布新角色视频后感到“绝望又崩溃”，她表示这个游戏曾给自己多少安全和幸福，如今感到的痛苦就有多少同样数值。 《恋与深空》在近期上线新角色，由于发布视频里反复套用威胁女性安全语句，比如“不要在锅里洗澡”、以及“引狼入室有什么不好？只要探头进去看看，他便会为你敞开大门”等，使得这款游戏在近日引海内外玩家大规模抵…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c70yknxg05go/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「中國尊」撞機後數日，當局仍未說明發生了什麼事",
    "link": "https://www.bbc.com/zhongwen/articles/c70yknxg05go/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-07-01 08:34:25",
    "author": "",
    "description": "AFP / 小型飞机如何闯入禁飞区？三大疑点梳理 一架小型飞机撞上北京最高摩天大楼，造成机上惟一一人的机师死亡。事件另造成13人受伤。事发至今已有四天，但事故为何以及如何发生，仍然不明。 中国至今就这宗坠机事故发布的唯一官方说法，是官媒《北京日报》一篇60字的报道，交代了最基本事实。事故发生地点距离中国共产党权力核心中南海只有数公里。 上周五的撞击在109层高的中信大厦外墙留下破洞，目前已被木板封起。事故的震撼影片已从互联网上被清除。至…",
    "content": "AFP / 小型飞机如何闯入禁飞区？三大疑点梳理 一架小型飞机撞上北京最高摩天大楼，造成机上惟一一人的机师死亡。事件另造成13人受伤。事发至今已有四天，但事故为何以及如何发生，仍然不明。 中国至今就这宗坠机事故发布的唯一官方说法，是官媒《北京日报》一篇60字的报道，交代了最基本事实。事故发生地点距离中国共产党权力核心中南海只有数公里。 上周五的撞击在109层高的中信大厦外墙留下破洞，目前已被木板封起。事故的震撼影片已从互联网上被清除。至少三间航空公司向BBC表示，它们已被要求暂停轻型飞机营运，但拒绝进一步说明，称已…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c7vy088g5lgo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中歐貿易摩擦加劇，默茨暗示推中國版《廣場協議》會成功嗎？",
    "link": "https://www.bbc.com/zhongwen/articles/c7vy088g5lgo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-30 18:12:09",
    "author": "",
    "description": "Getty Images / 2024年2月6日，德国美因茨，在即将到来的玫瑰星期一游行之前，一辆描绘中国国家主席习近平拔掉电动汽车插头、将德国汽车制造商甩在身后的花车将参与游行。 德国总理默茨（Friedrich Merz；梅尔茨）身上的一个重要标签，就是他对已故美国总统里根（Ronald Reagan）的崇拜。他也像自己的偶像一样，推崇自由市场经济模式以及跨大西洋的亲善关系。对于1980年代在里根治下美日之间的汇率谈判，以及最终签下…",
    "content": "Getty Images / 2024年2月6日，德国美因茨，在即将到来的玫瑰星期一游行之前，一辆描绘中国国家主席习近平拔掉电动汽车插头、将德国汽车制造商甩在身后的花车将参与游行。 德国总理默茨（Friedrich Merz；梅尔茨）身上的一个重要标签，就是他对已故美国总统里根（Ronald Reagan）的崇拜。他也像自己的偶像一样，推崇自由市场经济模式以及跨大西洋的亲善关系。对于1980年代在里根治下美日之间的汇率谈判，以及最终签下的《广场协议》（The Plaza Accord），默茨可能比大多数欧洲政客都更…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c20yg50wg02o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "大馬榴槤大跌價：為何曾經矜貴的果王如今要半賣半送？",
    "link": "https://www.bbc.com/zhongwen/articles/c20yg50wg02o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-30 16:47:16",
    "author": "",
    "description": "Kelly Ng/ BBC / 由于供过于求，榴梿价格大幅下跌。 连日来，新加坡东部繁忙市镇淡滨尼（Tampines）两个街区外都排起一条蜿蜒长龙，直通榴梿摊档“榴梿忍者（Durian Ninja）”。 人们耐心等候摊贩自6月中旬起每天免费派发的水果：每位顾客可获两个榴梿，每日派出约600公斤。 这份大方的举动源于邻国马来西亚榴梿供应过剩。马来西亚每年通常生产约55万吨榴梿。 但2026年异常丰收，令这种带刺、气味浓烈、深受亚洲多地民众…",
    "content": "Kelly Ng/ BBC / 由于供过于求，榴梿价格大幅下跌。 连日来，新加坡东部繁忙市镇淡滨尼（Tampines）两个街区外都排起一条蜿蜒长龙，直通榴梿摊档“榴梿忍者（Durian Ninja）”。 人们耐心等候摊贩自6月中旬起每天免费派发的水果：每位顾客可获两个榴梿，每日派出约600公斤。 这份大方的举动源于邻国马来西亚榴梿供应过剩。马来西亚每年通常生产约55万吨榴梿。 但2026年异常丰收，令这种带刺、气味浓烈、深受亚洲多地民众喜爱的水果价格大跌。 69岁的新加坡本地人庄先生正在排队，他向BBC表示，自己最…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cy8dpl03e3xo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "郭文貴美國詐騙案以判囚30年告一段落",
    "link": "https://www.bbc.com/zhongwen/articles/cy8dpl03e3xo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-30 13:24:58",
    "author": "",
    "description": "Reuters / 郭文贵被捕前在美国维持奢华生活。 流亡美国的中国富商郭文贵因诈骗等罪名，被法院判处30年监禁，并没收8.89亿美元（60.4亿元人民币；283.7亿元新台币）非法所得。 郭文贵周一（6月29日）在纽约南区联邦法院被判刑，美联社引述联邦法官表示，其大规模金融诈骗令全球逾1000人损失数以亿计美元。 郭文贵十多年前离开中国，在美国重塑“中共批评者”的形象，并在网络建立一群忠实的追随者。 法官阿纳丽莎·托雷斯（Analis…",
    "content": "Reuters / 郭文贵被捕前在美国维持奢华生活。 流亡美国的中国富商郭文贵因诈骗等罪名，被法院判处30年监禁，并没收8.89亿美元（60.4亿元人民币；283.7亿元新台币）非法所得。 郭文贵周一（6月29日）在纽约南区联邦法院被判刑，美联社引述联邦法官表示，其大规模金融诈骗令全球逾1000人损失数以亿计美元。 郭文贵十多年前离开中国，在美国重塑“中共批评者”的形象，并在网络建立一群忠实的追随者。 法官阿纳丽莎·托雷斯（Analisa Torres）判刑时表示，郭文贵“利用那些希望为中国带来民主的人”，骗取金钱…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cg4we27y99xo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國實施「民族團結進步促進法」，為何引起台灣憂慮？",
    "link": "https://www.bbc.com/zhongwen/articles/cg4we27y99xo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-30 12:41:04",
    "author": "",
    "description": "AFP via Getty Images 中国7月1日起实施“民族团结进步促进法”，明文指出依法追究“境外组织和个人”破坏民族团结进步、制造民族分裂行为。 中方学者视新法律为反制分裂的“法治利器”，台湾方面则批评该法律采取“非统即独”逻辑，令台湾民众“自我审查”，同时阻止其他国家的人“挺台湾”。 有日本政治人物表达忧虑，未来公开支持台湾，理论上可被该法律追究。另有学者分析，台湾若在两岸交流活动主张“对等尊严”原则，也将面临挑战。 哪些群…",
    "content": "AFP via Getty Images 中国7月1日起实施“民族团结进步促进法”，明文指出依法追究“境外组织和个人”破坏民族团结进步、制造民族分裂行为。 中方学者视新法律为反制分裂的“法治利器”，台湾方面则批评该法律采取“非统即独”逻辑，令台湾民众“自我审查”，同时阻止其他国家的人“挺台湾”。 有日本政治人物表达忧虑，未来公开支持台湾，理论上可被该法律追究。另有学者分析，台湾若在两岸交流活动主张“对等尊严”原则，也将面临挑战。 哪些群体恐受影响？ 台湾东海大学中国大陆暨区域发展研究中心副执行长洪浦钊向BBC中文表…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cy9rp1rxzvgo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「一場充滿意外的旅行」：首批上海遊客重返金門、馬祖",
    "link": "https://www.bbc.com/zhongwen/articles/cy9rp1rxzvgo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-30 11:37:53",
    "author": "",
    "description": "BBC CHINESE/ LEE LOK / 中国近期开放上海旅客赴金马旅游，首批旅客兴奋在金门当地拍照留影。 踏上摇晃的客船甲板，上海人Lily穿梭在人群之间，耳边交错着台湾腔与福建沿海口音，两天来紧绷的心情，终于在海风中逐渐松开。 船班的目的地是金门——一个她未曾踏足、过去几年也无法自由旅游的地方。 自2019年起，两岸政治情势与新冠疫情使中国大幅限制赴台旅游。直到2024年中，北京宣布部分开放，允许福建居民透过“小三通”前往金门、…",
    "content": "BBC CHINESE/ LEE LOK / 中国近期开放上海旅客赴金马旅游，首批旅客兴奋在金门当地拍照留影。 踏上摇晃的客船甲板，上海人Lily穿梭在人群之间，耳边交错着台湾腔与福建沿海口音，两天来紧绷的心情，终于在海风中逐渐松开。 船班的目的地是金门——一个她未曾踏足、过去几年也无法自由旅游的地方。 自2019年起，两岸政治情势与新冠疫情使中国大幅限制赴台旅游。直到2024年中，北京宣布部分开放，允许福建居民透过“小三通”前往金门、马祖，今年4月底再扩及上海居民。 “虽然不是台湾本岛，还是很远的金门，但也是要过…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ckg8jkg3n4yo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "北京「中國尊」遭輕型飛機撞擊：禁區管制、飛行員身份與動機引發三大疑點",
    "link": "https://www.bbc.com/zhongwen/articles/ckg8jkg3n4yo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-30 00:25:21",
    "author": "",
    "description": "AFP / 小型飞机如何闯入禁飞区？三大疑点梳理 北京最高建筑物“中国尊”上周五傍晚遭一架山河阿若拉 SA60L 轻型运动飞机撞击，造成飞行员当场死亡、13人受伤。在全中国空域管制最严格的北京中心，这架“低、慢、小”飞机如何穿透防线？社交媒体流传的飞行员身份与中信集团有何关联？这究竟是一场挟私报复还是纯粹意外？BBC中文梳理事件背后的禁区、动机与飞行员三大疑点。",
    "content": "AFP / 小型飞机如何闯入禁飞区？三大疑点梳理 北京最高建筑物“中国尊”上周五傍晚遭一架山河阿若拉 SA60L 轻型运动飞机撞击，造成飞行员当场死亡、13人受伤。在全中国空域管制最严格的北京中心，这架“低、慢、小”飞机如何穿透防线？社交媒体流传的飞行员身份与中信集团有何关联？这究竟是一场挟私报复还是纯粹意外？BBC中文梳理事件背后的禁区、动机与飞行员三大疑点。"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cr5j7q29vmjo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "27航班、24場比賽 國際足總主席如何穿梭世界盃",
    "link": "https://www.bbc.com/zhongwen/articles/cr5j7q29vmjo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-29 19:41:41",
    "author": "",
    "description": "BBC 国际足协（FIFA）主席詹尼·因凡蒂诺（Gianni Infantino，恩芬天奴）在今年夏季世界杯期间，已在短短两周多内造访北美各地24场比赛，累积数千英里的飞行里程。 本届赛事横跨美国、加拿大与墨西哥三国，共16个主办城市，且因小组赛扩编，比赛场次比以往更多。 在FIFA 2026世界杯永续发展与人权策略中，主席表示：“无论是气候、人权、疾病或残障议题，我们都致力于尽一份力。” 但BBC事实查核（BBC Verify）与BB…",
    "content": "BBC 国际足协（FIFA）主席詹尼·因凡蒂诺（Gianni Infantino，恩芬天奴）在今年夏季世界杯期间，已在短短两周多内造访北美各地24场比赛，累积数千英里的飞行里程。 本届赛事横跨美国、加拿大与墨西哥三国，共16个主办城市，且因小组赛扩编，比赛场次比以往更多。 在FIFA 2026世界杯永续发展与人权策略中，主席表示：“无论是气候、人权、疾病或残障议题，我们都致力于尽一份力。” 但BBC事实查核（BBC Verify）与BBC体育网（BBC Sport）追踪了一架与FIFA及因凡蒂诺有关的私人飞机，发现…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cgevz5p98plo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "歐洲「正在融化」：熱浪襲來 超過千人因高溫相關原因死亡",
    "link": "https://www.bbc.com/zhongwen/articles/cgevz5p98plo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-29 17:21:42",
    "author": "",
    "description": "Getty Images / 欧洲“正在融化”：热浪袭来 超过千人因高温相关原因死亡 前所未见的热浪正席卷欧洲，从上周开始，各国都陆续观察到超过摄氏40度的破纪录高温。世界卫生组织总干事谭德塞（Tedros Adhanom Ghebreyesus）表示，6月21日以来因高温死亡的人数比预期多了1300人。 “只能把窗户打开、开着电风扇。睡前洗澡，睡觉时盖着湿毛巾，”一名巴黎居民告诉记者。 热浪在法国的影响尤其严重。该国是欧洲冷气普及率最…",
    "content": "Getty Images / 欧洲“正在融化”：热浪袭来 超过千人因高温相关原因死亡 前所未见的热浪正席卷欧洲，从上周开始，各国都陆续观察到超过摄氏40度的破纪录高温。世界卫生组织总干事谭德塞（Tedros Adhanom Ghebreyesus）表示，6月21日以来因高温死亡的人数比预期多了1300人。 “只能把窗户打开、开着电风扇。睡前洗澡，睡觉时盖着湿毛巾，”一名巴黎居民告诉记者。 热浪在法国的影响尤其严重。该国是欧洲冷气普及率最低的国家之一，全国仅约四分之一的家庭装有空调。当局表示在最热的几天内，每日的平均…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/clyemvy4x17o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "這些西方人為嚮往俄羅斯價值而移民 如今卻落得一個失落",
    "link": "https://www.bbc.com/zhongwen/articles/clyemvy4x17o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-29 16:58:23",
    "author": "",
    "description": "Ben/ BBC / 来自英国德比的班恩于 2023 年持私人家庭签证移居俄罗斯，并表示他觉得在俄国生活更安全。 当利奥·黑尔（Leo Hare）于2023年底从美国德州移居俄罗斯并获得庇护后，他深信自己正为家人打造更美好的未来。 这位三个孩子的父亲全力投入新生活：品尝俄式饺子、在农场挤羊奶，并拍摄关于俄罗斯生活的影片给他的网路追随者。 利奥是一位虔诚的基督徒，他对美国的政治分裂、基因改造食品，以及他眼中LGBTQ运动的兴起日益感到希望…",
    "content": "Ben/ BBC / 来自英国德比的班恩于 2023 年持私人家庭签证移居俄罗斯，并表示他觉得在俄国生活更安全。 当利奥·黑尔（Leo Hare）于2023年底从美国德州移居俄罗斯并获得庇护后，他深信自己正为家人打造更美好的未来。 这位三个孩子的父亲全力投入新生活：品尝俄式饺子、在农场挤羊奶，并拍摄关于俄罗斯生活的影片给他的网路追随者。 利奥是一位虔诚的基督徒，他对美国的政治分裂、基因改造食品，以及他眼中LGBTQ运动的兴起日益感到希望幻灭。 当时，他相信俄罗斯提供了一个诱人的替代选择：一个建立在基督教信仰与家庭价…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c0myk4dj84xo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "韓國總統要求徹查世界盃「荒唐」敗仗 警察防主教練回國遇刺",
    "link": "https://www.bbc.com/zhongwen/articles/c0myk4dj84xo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-29 16:24:29",
    "author": "",
    "description": "Reuters / 这是洪明甫第二次出任韩国队主帅。 在韩国（南韩）男子国家足球队未能晋级世界杯淘汰赛后，主教练洪明甫经已辞职。 球队原本希望仍可作为成绩最佳的第三名之一晋级下一轮，但这一希望在星期六（6月27日）落空。 这次提早出局在国内引发广泛批评，总统李在明要求调查为何球队表现会如此令人失望。洪明甫星期日（28日）向球迷道歉，并表示责任“完全在我这位主教练身上”。 当地媒体报道指，由于周末洪明甫返韩期间，有网上出现针对他的死亡威胁…",
    "content": "Reuters / 这是洪明甫第二次出任韩国队主帅。 在韩国（南韩）男子国家足球队未能晋级世界杯淘汰赛后，主教练洪明甫经已辞职。 球队原本希望仍可作为成绩最佳的第三名之一晋级下一轮，但这一希望在星期六（6月27日）落空。 这次提早出局在国内引发广泛批评，总统李在明要求调查为何球队表现会如此令人失望。洪明甫星期日（28日）向球迷道歉，并表示责任“完全在我这位主教练身上”。 当地媒体报道指，由于周末洪明甫返韩期间，有网上出现针对他的死亡威胁，韩国警方表示，正加强监察仁川机场及其他地点的保安风险。 在国际足协（FIFA）…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cn4d1ev0vlpo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「中國尊」撞機事件背後的三大疑點：禁區、動機、飛行員",
    "link": "https://www.bbc.com/zhongwen/articles/cn4d1ev0vlpo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-28 18:09:30",
    "author": "",
    "description": "Getty Images / 在北京第一高大楼“中国尊”上，小型飞机撞出的窟窿清楚可见。 一架飞机撞上大楼，这个画面太过熟悉，深深印刻在当代人的大脑中。熟悉到任何人在看到新闻的第一秒，脑子里都会闪过同一个词：“911”。 911的烈度史无前例：两架满载燃油的波音767客机，近3000人遇难，美国纽约世界贸易中心（WTC）双子塔化为废墟。 而这一次事件的烈度则小得多：一架轻型运动飞机，仅重340公斤，在108层高的北京中信大厦“中国尊”上…",
    "content": "Getty Images / 在北京第一高大楼“中国尊”上，小型飞机撞出的窟窿清楚可见。 一架飞机撞上大楼，这个画面太过熟悉，深深印刻在当代人的大脑中。熟悉到任何人在看到新闻的第一秒，脑子里都会闪过同一个词：“911”。 911的烈度史无前例：两架满载燃油的波音767客机，近3000人遇难，美国纽约世界贸易中心（WTC）双子塔化为废墟。 而这一次事件的烈度则小得多：一架轻型运动飞机，仅重340公斤，在108层高的北京中信大厦“中国尊”上半部撞出一个窟窿，残骸从空中坠落，底层簷篷起火燃烧，浓烟升腾。 正值下班时分，大…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cy73v41yk6mo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "美國小費文化「混亂且昂貴」 世界盃球迷高呼受不了",
    "link": "https://www.bbc.com/zhongwen/articles/cy73v41yk6mo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-28 14:30:39",
    "author": "",
    "description": "Catherine McQueen / Getty Images 许多前往美国观看世界杯的世界各地球迷对于必须向服务生支付小费的文化感到沮丧，甚至向BBC说他们已出现“小费疲劳”。 英格兰球迷杰夫·普赖尔（Geoff Pryor）表示，他理解该为优质服务支付小费，但在购买一瓶水时，“他们甚么都没做却试图索取小费”，这让他感到“奇怪”。 在美国，一些餐厅与酒吧的员工时薪仅略高于2美元（13.6元人民币；63.7元新台币），他们预期顾客支付…",
    "content": "Catherine McQueen / Getty Images 许多前往美国观看世界杯的世界各地球迷对于必须向服务生支付小费的文化感到沮丧，甚至向BBC说他们已出现“小费疲劳”。 英格兰球迷杰夫·普赖尔（Geoff Pryor）表示，他理解该为优质服务支付小费，但在购买一瓶水时，“他们甚么都没做却试图索取小费”，这让他感到“奇怪”。 在美国，一些餐厅与酒吧的员工时薪仅略高于2美元（13.6元人民币；63.7元新台币），他们预期顾客支付约帐单总额20%的小费，以维持生计。 餐饮业员工亦表达了不满，有一名酒吧老板向B…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/crkv75e4dp2o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "英王查爾斯報稅表上的三處「與眾不同」",
    "link": "https://www.bbc.com/zhongwen/articles/crkv75e4dp2o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-28 12:08:28",
    "author": "",
    "description": "Getty Images 英王查尔斯三世（King Charles III；查理斯国王）公开其总值1290万英镑（1700万美元；1.16亿元人民币；5.4亿元新台币）的税单，创下历史，但这笔付款远非一般情况。 该公布与王室发布年度财务报告同时进行。 以下是该文件告诉我们的——以及未告诉我们的——有关国王特殊税务安排的内容。 1. 国王自愿缴纳部分税款 查尔斯国王依法并无需缴纳所得税、资本利得税或遗产税。 相反，他是根据一项与政府达成的…",
    "content": "Getty Images 英王查尔斯三世（King Charles III；查理斯国王）公开其总值1290万英镑（1700万美元；1.16亿元人民币；5.4亿元新台币）的税单，创下历史，但这笔付款远非一般情况。 该公布与王室发布年度财务报告同时进行。 以下是该文件告诉我们的——以及未告诉我们的——有关国王特殊税务安排的内容。 1. 国王自愿缴纳部分税款 查尔斯国王依法并无需缴纳所得税、资本利得税或遗产税。 相反，他是根据一项与政府达成的《谅解备忘录》，自愿缴纳部分所得税、资本利得税及遗产税。 该《谅解备忘录》于19…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c7vy8q88pl0o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "日本簽證漲價五倍，中國人為何反應激烈？",
    "link": "https://www.bbc.com/zhongwen/articles/c7vy8q88pl0o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-26 18:25:00",
    "author": "",
    "description": "Getty Images “我8月不去日本了，”李女士看到赴日签证涨价的消息，立即停下手边的工作，在好友群聊里发了这一句。 她快速转卖8月在东京举办的Summer Sonic音乐节门票，退掉了机票和酒店。 李女士今年27岁，在广东从事一份月入近两万人民币的工作。她对BBC中文说：“日本还是很值得去旅游探索，但这次涨价对我的出行计划影响很大，所以还是算了。” 该国政府6月19日宣布，自7月1日起，外国人单次入境签证费从3000日元上涨至1…",
    "content": "Getty Images “我8月不去日本了，”李女士看到赴日签证涨价的消息，立即停下手边的工作，在好友群聊里发了这一句。 她快速转卖8月在东京举办的Summer Sonic音乐节门票，退掉了机票和酒店。 李女士今年27岁，在广东从事一份月入近两万人民币的工作。她对BBC中文说：“日本还是很值得去旅游探索，但这次涨价对我的出行计划影响很大，所以还是算了。” 该国政府6月19日宣布，自7月1日起，外国人单次入境签证费从3000日元上涨至1.5万日元（631元人民币；92.82美元）；多次入境签证费由6000日元上涨至…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cd6e7w6lwe3o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國票房黑馬《給阿嬤的情書》 在新加坡掀起身份認同「大辯論」",
    "link": "https://www.bbc.com/zhongwen/articles/cd6e7w6lwe3o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-26 13:22:22",
    "author": "",
    "description": "Golden Village / 中国电影《给阿嬷的情书》几乎全片都使用潮汕地区的潮州话拍摄。 电影《给阿嬷的情书》讲述家庭、希望与困境的怀旧故事，今夏在中国票房横扫而过，却也在数千公里外的新加坡，意外掀起了一场关于身份认同的讨论。 这部“黑马”几乎全片使用潮汕地区的潮州话拍摄，而潮州话至今仍在东南亚部分华人长辈之间流通。 但当电影本月登上新加坡院线时，许多人震惊地发现，大部分场次都将以华语配音放映——华语贴近中国的通用语（普通话），也…",
    "content": "Golden Village / 中国电影《给阿嬷的情书》几乎全片都使用潮汕地区的潮州话拍摄。 电影《给阿嬷的情书》讲述家庭、希望与困境的怀旧故事，今夏在中国票房横扫而过，却也在数千公里外的新加坡，意外掀起了一场关于身份认同的讨论。 这部“黑马”几乎全片使用潮汕地区的潮州话拍摄，而潮州话至今仍在东南亚部分华人长辈之间流通。 但当电影本月登上新加坡院线时，许多人震惊地发现，大部分场次都将以华语配音放映——华语贴近中国的通用语（普通话），也是新加坡包括英语在内四种官方语言之一。 “作为潮州人，用潮州话看这部片子会格外特…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cn0v5xzzlgyo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "蓋房子、裝水電、洗空調：中國各地興起「全女維修隊」",
    "link": "https://www.bbc.com/zhongwen/articles/cn0v5xzzlgyo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-26 07:55:16",
    "author": "",
    "description": "Provided / 在深圳的刘梦媛（左一）说，团队成员都一种“想证明自己能干的韧劲 ” 15年前，当黄女士大学毕业进入互联网行业时，从没想过自己有一天会靠电钻和扳手谋生。 “我一直觉得自己会在办公室干到退休”，黄女士说。今年40多岁的她原本已经在互联网公司做到管理层。 如今，在气温超过35摄氏度的南方夏日，她背着几公斤重的工具箱，穿梭于工地之间。她蹲下检查墙角渗水点，又拿起镭射测量仪记录尺寸，再和客户讨论灯光布局。她的工装裤上沾满灰尘…",
    "content": "Provided / 在深圳的刘梦媛（左一）说，团队成员都一种“想证明自己能干的韧劲 ” 15年前，当黄女士大学毕业进入互联网行业时，从没想过自己有一天会靠电钻和扳手谋生。 “我一直觉得自己会在办公室干到退休”，黄女士说。今年40多岁的她原本已经在互联网公司做到管理层。 如今，在气温超过35摄氏度的南方夏日，她背着几公斤重的工具箱，穿梭于工地之间。她蹲下检查墙角渗水点，又拿起镭射测量仪记录尺寸，再和客户讨论灯光布局。她的工装裤上沾满灰尘和水泥。 黄女士并非个例。近两年，深圳、苏州、上海等中国多个城市陆续出现由女性组…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cj4g1v4lz27o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "脫歐十年，對英國經濟的影響愈發清晰",
    "link": "https://www.bbc.com/zhongwen/articles/cj4g1v4lz27o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-25 20:04:42",
    "author": "",
    "description": "Getty Images 2020年英国正式脱离欧盟不久，一家位于布里斯托（Bristol）的公司Eskimo开始销售一种新型高端且节能的电动散热器，其技术源自当地学者的研发。 该公司原计划透过英法海底隧道（Channel Tunnel）将产品销往欧洲各地。 鉴于欧洲推动绿色发展的雄心，该产品可谓恰逢其时，在订单涌入下，其位于伯明翰的工厂一直忙碌不停。 公司负责人菲尔·沃德（Phil Ward）告诉我，这家初创企业持续成长，但在他看来，…",
    "content": "Getty Images 2020年英国正式脱离欧盟不久，一家位于布里斯托（Bristol）的公司Eskimo开始销售一种新型高端且节能的电动散热器，其技术源自当地学者的研发。 该公司原计划透过英法海底隧道（Channel Tunnel）将产品销往欧洲各地。 鉴于欧洲推动绿色发展的雄心，该产品可谓恰逢其时，在订单涌入下，其位于伯明翰的工厂一直忙碌不停。 公司负责人菲尔·沃德（Phil Ward）告诉我，这家初创企业持续成长，但在他看来，如果没有他所称的“长脱欧效应”（the Long Brexit effect），…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ckg54yzl09qo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "從哥倫布到獨立宣言：美國是如何成為一個國家的？",
    "link": "https://www.bbc.com/zhongwen/articles/ckg54yzl09qo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-25 18:16:41",
    "author": "",
    "description": "从哥伦布到独立宣言：美国是如何成为一个国家的？ 今年7月4日美国将庆祝建国250周年 —— 而“美利坚合众国”，最初是如何成为一个国家的呢？ 这片土地数千年来一直有人居住，而英国于17世纪陆续建立的13个殖民地对当地原住民部族造成巨大冲击。他们随后不断扩张，成为我们今天所熟知的美国。 BBC透过地图与历史画像解释美国的起源故事：从哥伦布的航海发现、到最终与英国决裂的战争，以及1776年殖民地发表《独立宣言》、宣告独立的历程。",
    "content": "从哥伦布到独立宣言：美国是如何成为一个国家的？ 今年7月4日美国将庆祝建国250周年 —— 而“美利坚合众国”，最初是如何成为一个国家的呢？ 这片土地数千年来一直有人居住，而英国于17世纪陆续建立的13个殖民地对当地原住民部族造成巨大冲击。他们随后不断扩张，成为我们今天所熟知的美国。 BBC透过地图与历史画像解释美国的起源故事：从哥伦布的航海发现、到最终与英国决裂的战争，以及1776年殖民地发表《独立宣言》、宣告独立的历程。"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cg4w2n5ql32o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國芯片出口額暴增110%，是否意味西方「封鎖失敗」？",
    "link": "https://www.bbc.com/zhongwen/articles/cg4w2n5ql32o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-25 09:48:08",
    "author": "",
    "description": "Getty Images / 中国山东滨州一家芯片生产企业的车间，该企业主要面向海外销售。 “去年我国第一大出口产品为芯片。”前重庆市长黄奇帆在一场公开演讲的言论，在社交媒体上引起的反应几乎是即时的：“封锁失败”、“芯片逆袭”的叙事铺天盖地，仿佛一夜之间，被西方封堵的问题已经翻篇。 黄奇帆的话看似“惊人之语”，但不是空穴来风。 2026年5月，中国海关公布了一组数据：集成电路出口销售额355.5亿美元，同比暴增110.9%，集成电路在出…",
    "content": "Getty Images / 中国山东滨州一家芯片生产企业的车间，该企业主要面向海外销售。 “去年我国第一大出口产品为芯片。”前重庆市长黄奇帆在一场公开演讲的言论，在社交媒体上引起的反应几乎是即时的：“封锁失败”、“芯片逆袭”的叙事铺天盖地，仿佛一夜之间，被西方封堵的问题已经翻篇。 黄奇帆的话看似“惊人之语”，但不是空穴来风。 2026年5月，中国海关公布了一组数据：集成电路出口销售额355.5亿美元，同比暴增110.9%，集成电路在出口量和出口额上均成为最大出口商品。 但这个数字需要拆开来看。墨卡托中国研究所（M…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cy04v1wnp5vo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "一張照片，盡覽銀河系6000萬顆星球——還可能有新的",
    "link": "https://www.bbc.com/zhongwen/articles/cy04v1wnp5vo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-25 07:15:11",
    "author": "",
    "description": "ESA/Euclid/Euclid Consortium/NASA, CFHT, image processing by J.-C. Cuillandre and E. Bertin (CEA Paris-Saclay) / 欧几里得（Euclid）太空望远镜这次拍摄到的星云，距离地球8700光年（8231兆公里）。 欧洲太空总署（ESA；欧洲宇航局）公布了一幅以可见光拍摄下，有史以来最大且最为详尽的银河系核心影像。 这张影像由欧几里得…",
    "content": "ESA/Euclid/Euclid Consortium/NASA, CFHT, image processing by J.-C. Cuillandre and E. Bertin (CEA Paris-Saclay) / 欧几里得（Euclid）太空望远镜这次拍摄到的星云，距离地球8700光年（8231兆公里）。 欧洲太空总署（ESA；欧洲宇航局）公布了一幅以可见光拍摄下，有史以来最大且最为详尽的银河系核心影像。 这张影像由欧几里得（Euclid）太空望远镜拍摄，记录了超过6000万颗恒星、星云和星团。 然而，…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c8d215n1z93o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "台灣大學排名落後，為何卻能培育出世界級半導體工程師？",
    "link": "https://www.bbc.com/zhongwen/articles/c8d215n1z93o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-24 21:11:59",
    "author": "",
    "description": "Getty Images 2027年QS世界大学排名6月18日公布，国立台湾大学虽创下历史新高位居全球第63名，但多数台湾顶尖理工名校仍落在百名之外，与长居前20名的新加坡和中港名校相比，明显落后。 这一差距再度引发讨论：为何台湾的大学多数跌出百名之外，却能培育出世界一流的工程师，让台湾半导体产业在全球市占率超过六成？ 对此，台湾中山大学国际长李明轩教授向BBC中文表示，全球大学排名的计算方式，高度仰赖论文引用率等学术指标，这对“产学导…",
    "content": "Getty Images 2027年QS世界大学排名6月18日公布，国立台湾大学虽创下历史新高位居全球第63名，但多数台湾顶尖理工名校仍落在百名之外，与长居前20名的新加坡和中港名校相比，明显落后。 这一差距再度引发讨论：为何台湾的大学多数跌出百名之外，却能培育出世界一流的工程师，让台湾半导体产业在全球市占率超过六成？ 对此，台湾中山大学国际长李明轩教授向BBC中文表示，全球大学排名的计算方式，高度仰赖论文引用率等学术指标，这对“产学导向”的台湾教育体系并不公平。 “如果QS排名加入培养出来的人才的产业影响力，那么…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c4gyq6k624zo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "被列軍工名單 阿里巴巴狀告美國國防部",
    "link": "https://www.bbc.com/zhongwen/articles/c4gyq6k624zo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-24 11:31:21",
    "author": "",
    "description": "Getty Images / 阿里巴巴向BBC否认其为中国军工企业。 中国电子商务与科技巨头阿里巴巴已对美国政府发起一项高风险的法律挑战，试图从一份五角大楼黑名单中除名，该名单称其与中国军方有关。 美国国防部表示，由于阿里巴巴遵守中国的科技监管规定，因此实际上相当于军方的一个分支。 阿里巴巴向加州某联邦法院提交的诉讼中对此提出反驳，称相关认定“在事实与法律上均毫无依据”。 此项挑战正值五角大楼近期扩大其黑名单之际，该名单规定自本月底起将…",
    "content": "Getty Images / 阿里巴巴向BBC否认其为中国军工企业。 中国电子商务与科技巨头阿里巴巴已对美国政府发起一项高风险的法律挑战，试图从一份五角大楼黑名单中除名，该名单称其与中国军方有关。 美国国防部表示，由于阿里巴巴遵守中国的科技监管规定，因此实际上相当于军方的一个分支。 阿里巴巴向加州某联邦法院提交的诉讼中对此提出反驳，称相关认定“在事实与法律上均毫无依据”。 此项挑战正值五角大楼近期扩大其黑名单之际，该名单规定自本月底起将无法与名单上的公司进行业务往来，其中包括百度、比亚迪和蔚来等大型科技企业。 国防…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c5yz2n27v1go/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "你知道你的「流汗評分」嗎？來看補水技術的崛起",
    "link": "https://www.bbc.com/zhongwen/articles/c5yz2n27v1go/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-24 07:34:02",
    "author": "",
    "description": "Getty Images / 2026年世界杯是首届每场比赛都强制要求球员补水暂停的FIFA世界杯。 嘘声四起，球迷和不满的评论员也纷纷抱怨。 2026年世界杯至今一大争议就是补水暂停时间（hydration breaks）。虽然这并非甚么全新做法，但本届世界杯每场比赛都安排了两次，这在历史上尚属首次。 一些观众认为，这些休息时间并非真正为了补水，而只是某些转播商投放更多广告的机会，打断了比赛的自然节奏，而且在有空调的体育场内完全没有必…",
    "content": "Getty Images / 2026年世界杯是首届每场比赛都强制要求球员补水暂停的FIFA世界杯。 嘘声四起，球迷和不满的评论员也纷纷抱怨。 2026年世界杯至今一大争议就是补水暂停时间（hydration breaks）。虽然这并非甚么全新做法，但本届世界杯每场比赛都安排了两次，这在历史上尚属首次。 一些观众认为，这些休息时间并非真正为了补水，而只是某些转播商投放更多广告的机会，打断了比赛的自然节奏，而且在有空调的体育场内完全没有必要。 无论你是否认同这些抱怨，毫无疑问，补水本身已成为全球日益重要的讨论议题。 …"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c0ey9jyw37po/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "當影像流水線走到極致——中國AI短劇是怎樣煉成的？",
    "link": "https://www.bbc.com/zhongwen/articles/c0ey9jyw37po/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-24 07:25:01",
    "author": "",
    "description": "PROVIDED / AI制作的橘猫创业短剧系列。 对于整个中国短剧行业来说，在过去的两个季度里，几乎唯一被摆在桌上讨论的话题就是AI短剧，以及这个行业如何和谐与之共处。 3月，抖音母公司字节跳动推出了Seedance 2.0，这是一个用于视频生成的更完善的AI大模型。它的出现使得真人短剧行业“7+7+7”（筹备、拍摄、后期“投流”各7天）的效率制作模式也显得不那么诱人。5个人在6天时间里就能做出一个60集的剧，成本不到真人短剧的十分之…",
    "content": "PROVIDED / AI制作的橘猫创业短剧系列。 对于整个中国短剧行业来说，在过去的两个季度里，几乎唯一被摆在桌上讨论的话题就是AI短剧，以及这个行业如何和谐与之共处。 3月，抖音母公司字节跳动推出了Seedance 2.0，这是一个用于视频生成的更完善的AI大模型。它的出现使得真人短剧行业“7+7+7”（筹备、拍摄、后期“投流”各7天）的效率制作模式也显得不那么诱人。5个人在6天时间里就能做出一个60集的剧，成本不到真人短剧的十分之一。 真人不再被需要，AI生成的图片和场景更调动观众情绪，而观众情绪就是短剧行业…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cd95j3x3gxvo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "脫歐十年後，英國新首相在歐洲問題上必須做出重大抉擇",
    "link": "https://www.bbc.com/zhongwen/articles/cd95j3x3gxvo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-23 13:58:06",
    "author": "",
    "description": "AFP via Getty Images 在巴黎蒙马特高地、毗邻圣心堂（Sacre Coeur）的圣皮耶旋转木马（Carrousel de St Pierre），以其带有怀旧气息的彩绘与金色鬃毛的木马，以及随旋转飘扬的法国香颂音乐，长久以来深受游客喜爱。然而，最近当我看着这座旋转木马在那些浪漫的法国旋律中转动时，它让我联想到的，却是英国脱欧（Brexit）。 自英国投票决定离开欧盟至今，已有10年。几乎在公投结果出炉后不久，从欧盟的角度…",
    "content": "AFP via Getty Images 在巴黎蒙马特高地、毗邻圣心堂（Sacre Coeur）的圣皮耶旋转木马（Carrousel de St Pierre），以其带有怀旧气息的彩绘与金色鬃毛的木马，以及随旋转飘扬的法国香颂音乐，长久以来深受游客喜爱。然而，最近当我看着这座旋转木马在那些浪漫的法国旋律中转动时，它让我联想到的，却是英国脱欧（Brexit）。 自英国投票决定离开欧盟至今，已有10年。几乎在公投结果出炉后不久，从欧盟的角度来看，英国便开始向内收缩，踏上长达数年的政治危机之路——国家分裂、争吵不休，在原…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c5yz00486e3o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "誰說羅賓漢是英雄？黑暗、暴力的中世紀起源如何被抹除",
    "link": "https://www.bbc.com/zhongwen/articles/c5yz00486e3o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-23 07:50:33",
    "author": "",
    "description": "Getty Images / 罗宾汉的形象历经数世纪演变，每次改变都反映了重新诠释他的时代。 警告：本文包含部分读者可能感到不适的暴力图像描述。 罗宾汉（Robin Hood）最初是12世纪的口传传统，后来演变成英雄式、适合全家观赏的刻板形象——以下是新作品如何恢复他黑暗的一面。 当电影编剧兼导演麦可·萨诺斯基（Michael Sarnoski）开始拍摄他的新电影时，他让演员和剧组观看一部他一直喜爱的作品。那是迪士尼1973年的动画《罗…",
    "content": "Getty Images / 罗宾汉的形象历经数世纪演变，每次改变都反映了重新诠释他的时代。 警告：本文包含部分读者可能感到不适的暴力图像描述。 罗宾汉（Robin Hood）最初是12世纪的口传传统，后来演变成英雄式、适合全家观赏的刻板形象——以下是新作品如何恢复他黑暗的一面。 当电影编剧兼导演麦可·萨诺斯基（Michael Sarnoski）开始拍摄他的新电影时，他让演员和剧组观看一部他一直喜爱的作品。那是迪士尼1973年的动画《罗宾汉》，主角是一只戴着绿帽、插着羽毛的狐狸，劫富济贫。 这个深受喜爱的版本，与萨…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cpv300kw9wno/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "每天服用健康補充劑？結果可能弊大於利",
    "link": "https://www.bbc.com/zhongwen/articles/cpv300kw9wno/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-23 07:50:03",
    "author": "",
    "description": "Getty Images 我原本不认为自己是狂热的补充剂（supplements）服用者，但当我好好检查橱柜时，才发现自己不知不觉累积了好几包肌酸、维生素D、镁、胶原蛋白、全方位绿色补充剂，以及一些专为更年期前后起伏设计的药片。 我以为自己能免疫于社群媒体上的不断广告，但结果显然并非如此。 那些像是“我无法相信这些补充剂让我感觉有多好！”的评论，已经渗透进我那（半信半疑）被胶原蛋白强化过的肌肤。 事实上，根据消费者权益团体“Which?…",
    "content": "Getty Images 我原本不认为自己是狂热的补充剂（supplements）服用者，但当我好好检查橱柜时，才发现自己不知不觉累积了好几包肌酸、维生素D、镁、胶原蛋白、全方位绿色补充剂，以及一些专为更年期前后起伏设计的药片。 我以为自己能免疫于社群媒体上的不断广告，但结果显然并非如此。 那些像是“我无法相信这些补充剂让我感觉有多好！”的评论，已经渗透进我那（半信半疑）被胶原蛋白强化过的肌肤。 事实上，根据消费者权益团体“Which?”最近的一项调查，76%的受访者定期服用至少一种补充剂——包括维生素、矿物质、O…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/ce8j1rvjjvzo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "中國「後地產時代」：地方政府從賣地轉型到做股東成功了嗎？",
    "link": "https://www.bbc.com/zhongwen/articles/ce8j1rvjjvzo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-19 18:27:51",
    "author": "",
    "description": "Getty Images / 2026 年 4 月 3 日，中国山西省太原市一间张雪摩托（ZXMOTOR）门店内，一名顾客试骑摩托车。中国摩托车制造商张雪摩托（ZXMOTO）日前于葡萄牙举办的世界超级摩托车锦标赛（WSBK）创下历史性双料冠军佳绩后，声势大涨，在网路上引发热议。 2026年1月，一家成立不到两年的草根企业拿到了9000万元人民币（1330万美元）。 张雪机车，2024年4月才注册，紮根重庆，创始人张雪曾一度四处筹措700…",
    "content": "Getty Images / 2026 年 4 月 3 日，中国山西省太原市一间张雪摩托（ZXMOTOR）门店内，一名顾客试骑摩托车。中国摩托车制造商张雪摩托（ZXMOTO）日前于葡萄牙举办的世界超级摩托车锦标赛（WSBK）创下历史性双料冠军佳绩后，声势大涨，在网路上引发热议。 2026年1月，一家成立不到两年的草根企业拿到了9000万元人民币（1330万美元）。 张雪机车，2024年4月才注册，紮根重庆，创始人张雪曾一度四处筹措700万元（103万美元），垫付员工工资。而摩托车，一个又小又老的赛道，在多数创投机构…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cx2de9z1m34o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "經濟制裁、西方代表迴避：國際論壇現場的俄羅斯經濟挑戰",
    "link": "https://www.bbc.com/zhongwen/articles/cx2de9z1m34o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-19 18:25:14",
    "author": "",
    "description": "BBC / 俄乌战争第五年，俄罗斯经济面临挑战 乌克兰六月初的无人机攻击为普京在圣彼得堡举办的年度国际经济论坛蒙上阴影。 这场活动曾被视为俄罗斯版的“达沃斯世界经济论坛（DAVOS）”，长年吸引外国投资者、俄罗斯政界和商界菁英出席。然而今年出席的西方代表寥寥无几，其中包括一些颇具争议性的人物，例如右翼网红、评论员坎迪斯·欧文斯（Candace Owens）。 BBC俄罗斯事务编辑史蒂夫·罗森伯格（Steve Rosenberg）带观众走…",
    "content": "BBC / 俄乌战争第五年，俄罗斯经济面临挑战 乌克兰六月初的无人机攻击为普京在圣彼得堡举办的年度国际经济论坛蒙上阴影。 这场活动曾被视为俄罗斯版的“达沃斯世界经济论坛（DAVOS）”，长年吸引外国投资者、俄罗斯政界和商界菁英出席。然而今年出席的西方代表寥寥无几，其中包括一些颇具争议性的人物，例如右翼网红、评论员坎迪斯·欧文斯（Candace Owens）。 BBC俄罗斯事务编辑史蒂夫·罗森伯格（Steve Rosenberg）带观众走进论坛现场。在那里，乌克兰的无人机攻击以及俄罗斯因战争承受的经济压力都已经开始显…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c0ky3d5ggpmo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「他把單點菜單藏了起來」：誰應該為第一次約會付錢？",
    "link": "https://www.bbc.com/zhongwen/articles/c0ky3d5ggpmo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-19 15:18:38",
    "author": "",
    "description": "BBC 很少有话题会像第一次约会应该由谁付钱那样产生分歧。 当你你向一群朋友提出这个问题，你很可能会得到一连串不同的答案。有人坚持应该各自分摊费用，另一些人相信主动提出邀约的一方应该付钱，即使对于性别角色的观念有所转变，但仍然有不少人将男性结帐视为一个浪漫的举动，而不是过时的传统。 在鸡尾酒普遍超过15英镑、餐厅帐单费用不断上升、不少人密切地关注预算的情况下，即使只是一个休闲外出的晚上，也很快变得非常昂贵。 根据巴克莱银行（Barcla…",
    "content": "BBC 很少有话题会像第一次约会应该由谁付钱那样产生分歧。 当你你向一群朋友提出这个问题，你很可能会得到一连串不同的答案。有人坚持应该各自分摊费用，另一些人相信主动提出邀约的一方应该付钱，即使对于性别角色的观念有所转变，但仍然有不少人将男性结帐视为一个浪漫的举动，而不是过时的传统。 在鸡尾酒普遍超过15英镑、餐厅帐单费用不断上升、不少人密切地关注预算的情况下，即使只是一个休闲外出的晚上，也很快变得非常昂贵。 根据巴克莱银行（Barclays）在2025年的研究，英国成年人每个月花费在约会和交友程式上的花费超过111…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c2lyj7024wwo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "白宮冷待、統戰部同框：鄭麗文15天訪美行程帶回了什麼？",
    "link": "https://www.bbc.com/zhongwen/articles/c2lyj7024wwo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-15 19:34:44",
    "author": "",
    "description": "AFP / 郑丽文访问美国期间举行记者会 国民党党主席郑丽文在“郑习会”后访美，但历史性的15天行程被指“高开低收”。 她不仅未能走入白宫会见美国国安会官员，在侨胞活动上更与中共统战部代表同框，能否让美方“释疑”、巩固党内领导地位引起外界关注。 台湾政治人物访问美国一直被视为“面试”，国民党作为台湾最大在野党，党内巨头今年内接连访美，郑丽文、卢秀燕、韩国瑜等人获待遇规格的高低，都成为了重要的指标，可能左右2028年总统大选布局。 白宫会…",
    "content": "AFP / 郑丽文访问美国期间举行记者会 国民党党主席郑丽文在“郑习会”后访美，但历史性的15天行程被指“高开低收”。 她不仅未能走入白宫会见美国国安会官员，在侨胞活动上更与中共统战部代表同框，能否让美方“释疑”、巩固党内领导地位引起外界关注。 台湾政治人物访问美国一直被视为“面试”，国民党作为台湾最大在野党，党内巨头今年内接连访美，郑丽文、卢秀燕、韩国瑜等人获待遇规格的高低，都成为了重要的指标，可能左右2028年总统大选布局。 白宫会面“无疾而终” 郑丽文结束15天访美行程，她在出发前曾表示“非常愿意”与美国总统…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cx211w7zkkeo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "點擊瀏覽即時更新",
    "link": "https://www.bbc.com/zhongwen/articles/cx211w7zkkeo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-12 12:11:10",
    "author": "",
    "description": "Reuters 由美国、加拿大和墨西哥共同主办的2026年国际足联（FIFA）世界杯决赛周将于6月11日至7月19日举行，你可以在这里查阅赛事安排、跟踪比赛结果。 点击浏览BBC中文2026年FIFA世界杯专页 點擊放大 FIFA 世界盃 2026 小組賽 淘汰賽 南非 0 - 加拿大 - 巴西 2 - 日本 - 德國 1 - 巴拉圭 - 荷蘭 1 - 摩洛哥 - 科特迪瓦 1 - 挪威 - 法國 3 - 瑞典 - 墨西哥 2 - 厄瓜…",
    "content": "Reuters 由美国、加拿大和墨西哥共同主办的2026年国际足联（FIFA）世界杯决赛周将于6月11日至7月19日举行，你可以在这里查阅赛事安排、跟踪比赛结果。 点击浏览BBC中文2026年FIFA世界杯专页 點擊放大 FIFA 世界盃 2026 小組賽 淘汰賽 淘汰賽 32強淘汰賽 6月28日，20:00（GMT+1） 南非 0 - 1 加拿大 (互射12碼) NaN - NaN (互射12碼) (洛杉磯體育場) 6月29日，18:00（GMT+1） 巴西 2 - 1 日本 (互射12碼) NaN - NaN …"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cp9lzne9159o/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "台積電財務長黃仁昭BBC專訪：經營成本上升，晶片不排除加價",
    "link": "https://www.bbc.com/zhongwen/articles/cp9lzne9159o/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-10 07:05:02",
    "author": "",
    "description": "BBC / BBC记者在台积电位于台湾的总部，进行了罕有的专访。 全球最大晶片制造商台积电（TSMC）告诉BBC，通胀正推高经营成本，该公司不排除加价。 台积电生产由英伟达（Nvidia，辉达）、AMD和苹果（Apple）等公司设计的最先进晶片，因此任何价格上调，都可能波及人工智能基础设施的成本，并可能随着时间推移影响消费者购买电子设备的价格。 不过，该公司财务长黄仁昭表示，台积电不会突然涨价“四、五倍”。他说：“我们反映的是我们的价值…",
    "content": "BBC / BBC记者在台积电位于台湾的总部，进行了罕有的专访。 全球最大晶片制造商台积电（TSMC）告诉BBC，通胀正推高经营成本，该公司不排除加价。 台积电生产由英伟达（Nvidia，辉达）、AMD和苹果（Apple）等公司设计的最先进晶片，因此任何价格上调，都可能波及人工智能基础设施的成本，并可能随着时间推移影响消费者购买电子设备的价格。 不过，该公司财务长黄仁昭表示，台积电不会突然涨价“四、五倍”。他说：“我们反映的是我们的价值。”他并提到公司的“领先的技术”和“卓越的生产”。 在一场独家、范围广泛的访问中…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/cx21r3d9y1yo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "2026足球世界盃賽程海報 點擊這裡免費下載",
    "link": "https://www.bbc.com/zhongwen/articles/cx21r3d9y1yo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-06-09 14:33:19",
    "author": "",
    "description": "BBC 想在2026世界杯期间掌握所有赛事动态，并清楚知道每一场比赛的进行时间吗？ 你现在可以下载一份免费的2026世界杯赛程海报，从揭幕战一路追踪到决赛。 点击此链接下载你的赛程海报 每一场比赛、每一个地点！ 将它打印出来，随着赛事进行填写比分，并在整个赛事期间，与朋友和家人比较你的预测结果。 无论你是要追踪每一场比赛，还是只关注你最喜爱的球队，2026世界杯赛程海报都是这项全球最大足球盛事的最佳伙伴。 本届赛事将于墨西哥当地时间20…",
    "content": "BBC 想在2026世界杯期间掌握所有赛事动态，并清楚知道每一场比赛的进行时间吗？ 你现在可以下载一份免费的2026世界杯赛程海报，从揭幕战一路追踪到决赛。 点击此链接下载你的 赛程海报 每一场比赛、每一个地点！ 将它打印出来，随着赛事进行填写比分，并在整个赛事期间，与朋友和家人比较你的预测结果。 无论你是要追踪每一场比赛，还是只关注你最喜爱的球队，2026世界杯赛程海报都是这项全球最大足球盛事的最佳伙伴。 本届赛事将于墨西哥当地时间2026年6月11日下午3点（北京时间6月12日凌晨3点）开始，并于美国纽约当地时…"
  },
  {
    "id": "国外-BBC 中文版-https://www.bbc.com/zhongwen/articles/c4g09912wgdo/simp?at_medium=RSS&at_campaign=rss",
    "feed_name": "BBC 中文版",
    "category": "国外",
    "title": "「中美建設性戰略穩定關係」：習近平新詞反映的現實境遇",
    "link": "https://www.bbc.com/zhongwen/articles/c4g09912wgdo/simp?at_medium=RSS&at_campaign=rss",
    "pub_date": "2026-05-19 17:51:58",
    "author": "",
    "description": "China News Service / 从“新型大国关系”换成“建设性战略稳定关系”，中美关系是升级还是降级？目前不得而知。 美国总统特朗普（Donald Trump；川普）结束了从落地到离开历时仅42小时的访华行程。两国官方与观察人士对这场缺乏具体协议的峰会众说纷纭，但一个外交新词汇从此诞生。 中国国家主席习近平在与特朗普谈判时称，中美两国将以构建“中美建设性战略稳定关系”作为新的目标——取代了他在2013年提出的“中美新型大国关系…",
    "content": "China News Service / 从“新型大国关系”换成“建设性战略稳定关系”，中美关系是升级还是降级？目前不得而知。 美国总统特朗普（Donald Trump；川普）结束了从落地到离开历时仅42小时的访华行程。两国官方与观察人士对这场缺乏具体协议的峰会众说纷纭，但一个外交新词汇从此诞生。 中国国家主席习近平在与特朗普谈判时称，中美两国将以构建“中美建设性战略稳定关系”作为新的目标——取代了他在2013年提出的“中美新型大国关系”。 中国官方媒体接连刊发文章，称新的定位“意义重大”，是中美关系“新典范”。中…"
  }
];

export default jsonData;
